from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("abox.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/abox.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("a box")
head1.addMeta(meta6)
meta7 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta7)
meta8 = metaObject().setName("generator").setContent("X3dToJson.xslt, http://www.web3d.org/x3d/stylesheets/X3dToJson.html")
head1.addMeta(meta8)
meta9 = metaObject().setName("reference").setContent("X3D JSON encoding: http://www.web3d.org/wiki/index.php/X3D_JSON_Encoding")
head1.addMeta(meta9)
meta10 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta10)
meta11 = metaObject().setName("generator").setContent("X3DJSONLD: https://github.com/coderextreme/X3DJSONLD")
head1.addMeta(meta11)
X3D0.setHead(head1)
Scene12 = SceneObject()
ProtoDeclare13 = ProtoDeclareObject().setName("anyShape")
ProtoInterface14 = ProtoInterfaceObject()
field15 = fieldObject().setType(fieldObject.TYPE_MFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Shape16 = ShapeObject()
Sphere17 = SphereObject()
Shape16.setGeometry(Sphere17)
field15.addChild(Shape16)
ProtoInterface14.addField(field15)
ProtoDeclare13.setProtoInterface(ProtoInterface14)
ProtoBody18 = ProtoBodyObject()
Transform19 = TransformObject()
IS20 = ISObject()
connect21 = connectObject().setNodeField("children").setProtoField("myShape")
IS20.addConnect(connect21)
Transform19.setIS(IS20)
ProtoBody18.addChild(Transform19)
ProtoDeclare13.setProtoBody(ProtoBody18)
Scene12.addChild(ProtoDeclare13)
ProtoDeclare22 = ProtoDeclareObject().setName("one")
ProtoInterface23 = ProtoInterfaceObject()
field24 = fieldObject().setType(fieldObject.TYPE_MFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Shape25 = ShapeObject()
Cylinder26 = CylinderObject()
Shape25.setGeometry(Cylinder26)
field24.addChild(Shape25)
ProtoInterface23.addField(field24)
ProtoDeclare22.setProtoInterface(ProtoInterface23)
ProtoBody27 = ProtoBodyObject()
Transform28 = TransformObject()
ProtoInstance29 = ProtoInstanceObject().setName("anyShape")
IS30 = ISObject()
connect31 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS30.addConnect(connect31)
ProtoInstance29.setIS(IS30)
Transform28.addChild(ProtoInstance29)
ProtoBody27.addChild(Transform28)
ProtoDeclare22.setProtoBody(ProtoBody27)
Scene12.addChild(ProtoDeclare22)
ProtoInstance32 = ProtoInstanceObject().setName("one")
fieldValue33 = fieldValueObject().setName("myShape")
Shape34 = ShapeObject()
Box35 = BoxObject().setSize([1,1,1])
Shape34.setGeometry(Box35)
fieldValue33.addChild(Shape34)
ProtoInstance32.addFieldValue(fieldValue33)
Scene12.addChild(ProtoInstance32)
X3D0.setScene(Scene12)

X3D0.toFileX3D("abox.new.x3d")
