from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("arc.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/arc.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("an attempt to implement an arc in a graph")
head1.addMeta(meta6)
meta7 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta7)
meta8 = metaObject().setName("generator").setContent("X3dToJson.xslt, http://www.web3d.org/x3d/stylesheets/X3dToJson.html")
head1.addMeta(meta8)
meta9 = metaObject().setName("reference").setContent("X3D JSON encoding: http://www.web3d.org/wiki/index.php/X3D_JSON_Encoding")
head1.addMeta(meta9)
meta10 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta10)
meta11 = metaObject().setName("generator").setContent("X3DJSONLD: https://github.com/coderextreme/X3DJSONLD")
head1.addMeta(meta11)
X3D0.setHead(head1)
Scene12 = SceneObject()
Viewpoint13 = ViewpointObject().setPosition([0,0,5]).setDescription("a moving graph")
Scene12.addChild(Viewpoint13)
Background14 = BackgroundObject().setSkyColor([0.4,0.4,0.4])
Scene12.addChild(Background14)
Transform15 = TransformObject().setDEF("cylinder1")
Shape16 = ShapeObject()
Appearance17 = AppearanceObject()
Material18 = MaterialObject().setDiffuseColor([0.2,0.7,0.7])
Appearance17.setMaterial(Material18)
Shape16.setAppearance(Appearance17)
Cylinder19 = CylinderObject().setRadius(0.1)
Shape16.setGeometry(Cylinder19)
Transform15.addChild(Shape16)
Scene12.addChild(Transform15)
Transform20 = TransformObject().setDEF("cylinder2")
Shape21 = ShapeObject()
Appearance22 = AppearanceObject()
Material23 = MaterialObject().setDiffuseColor([0.2,0.7,0.7])
Appearance22.setMaterial(Material23)
Shape21.setAppearance(Appearance22)
Cylinder24 = CylinderObject().setRadius(0.1)
Shape21.setGeometry(Cylinder24)
Transform20.addChild(Shape21)
Scene12.addChild(Transform20)
Transform25 = TransformObject().setDEF("cylinder3")
Shape26 = ShapeObject()
Appearance27 = AppearanceObject()
Material28 = MaterialObject().setDiffuseColor([0.2,0.7,0.7])
Appearance27.setMaterial(Material28)
Shape26.setAppearance(Appearance27)
Cylinder29 = CylinderObject().setRadius(0.1)
Shape26.setGeometry(Cylinder29)
Transform25.addChild(Shape26)
Scene12.addChild(Transform25)
ProtoDeclare30 = ProtoDeclareObject().setName("point")
ProtoInterface31 = ProtoInterfaceObject()
field32 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("translation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface31.addField(field32)
ProtoDeclare30.setProtoInterface(ProtoInterface31)
ProtoBody33 = ProtoBodyObject()
Transform34 = TransformObject().setDEF("node")
IS35 = ISObject()
connect36 = connectObject().setNodeField("translation").setProtoField("translation")
IS35.addConnect(connect36)
Transform34.setIS(IS35)
Shape37 = ShapeObject()
Sphere38 = SphereObject().setRadius(0.1)
Shape37.setGeometry(Sphere38)
Appearance39 = AppearanceObject()
Material40 = MaterialObject().setDiffuseColor([1,0,0])
Appearance39.setMaterial(Material40)
Shape37.setAppearance(Appearance39)
Transform34.addChild(Shape37)
PositionInterpolator41 = PositionInterpolatorObject().setDEF("PI1").setKey([0,1]).setKeyValue([0,0,0,0,5,0])
Transform34.addChild(PositionInterpolator41)
Script42 = ScriptObject().setDEF("MB1")
field43 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("translation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("50 50 0")
Script42.addField(field43)
field44 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("old").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
Script42.addField(field44)
field45 = fieldObject().setType(fieldObject.TYPE_SFTIME).setName("set_location").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
Script42.addField(field45)
field46 = fieldObject().setType(fieldObject.TYPE_MFVEC3F).setName("keyValue").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY)
Script42.addField(field46)

Script42.setSourceCode("ecmascript:\n"+
"		function set_location(value) {\n"+
"                    old = translation;\n"+
"		    translation = new SFVec3f(Math.random()*10-5, Math.random()*10-5, Math.random()*10-5);\n"+
"                    keyValue = new MFVec3f(old, translation);\n"+
"		    // Browser.println(translation);\n"+
"		}\n"+
"")
Transform34.addChild(Script42)
TimeSensor47 = TimeSensorObject().setDEF("CL1").setCycleInterval(3).setLoop(True)
Transform34.addChild(TimeSensor47)
ROUTE48 = ROUTEObject().setFromNode("CL1").setFromField("cycleTime").setToNode("MB1").setToField("set_location")
Transform34.addChild(ROUTE48)
ROUTE49 = ROUTEObject().setFromNode("CL1").setFromField("fraction_changed").setToNode("PI1").setToField("set_fraction")
Transform34.addChild(ROUTE49)
ROUTE50 = ROUTEObject().setFromNode("MB1").setFromField("keyValue").setToNode("PI1").setToField("keyValue")
Transform34.addChild(ROUTE50)
ROUTE51 = ROUTEObject().setFromNode("PI1").setFromField("value_changed").setToNode("node").setToField("set_translation")
Transform34.addChild(ROUTE51)
ProtoBody33.addChild(Transform34)
ProtoDeclare30.setProtoBody(ProtoBody33)
Scene12.addChild(ProtoDeclare30)

Scene12.addComments(CommentsBlock("from doug sanden"))
ProtoDeclare52 = ProtoDeclareObject().setName("x3dconnector")
ProtoInterface53 = ProtoInterfaceObject()
field54 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("startnode").setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY)
ProtoInterface53.addField(field54)
field55 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("endnode").setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY)
ProtoInterface53.addField(field55)
field56 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("connectornode").setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY)
ProtoInterface53.addField(field56)
field57 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("set_startpoint").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
ProtoInterface53.addField(field57)
field58 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("set_endpoint").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
ProtoInterface53.addField(field58)
ProtoDeclare52.setProtoInterface(ProtoInterface53)
ProtoBody59 = ProtoBodyObject()
Script60 = ScriptObject().setDEF("S1")
field61 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("startnode").setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY)
Script60.addField(field61)
field62 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("endnode").setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY)
Script60.addField(field62)
field63 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("connectornode").setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY)
Script60.addField(field63)
field64 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("set_startpoint").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
Script60.addField(field64)
field65 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("set_endpoint").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
Script60.addField(field65)
IS66 = ISObject()
connect67 = connectObject().setNodeField("startnode").setProtoField("startnode")
IS66.addConnect(connect67)
connect68 = connectObject().setNodeField("endnode").setProtoField("endnode")
IS66.addConnect(connect68)
connect69 = connectObject().setNodeField("connectornode").setProtoField("connectornode")
IS66.addConnect(connect69)
connect70 = connectObject().setNodeField("set_startpoint").setProtoField("set_startpoint")
IS66.addConnect(connect70)
connect71 = connectObject().setNodeField("set_endpoint").setProtoField("set_endpoint")
IS66.addConnect(connect71)
Script60.setIS(IS66)

Script60.setSourceCode("ecmascript:\n"+
"            function recompute(startpoint,endpoint) {\n"+
"	        if (typeof endpoint === 'undefined') {\n"+
"			return;\n"+
"		}\n"+
"                var dif = endpoint.subtract(startpoint);\n"+
"                var dist = dif.length()*.5;\n"+
"                var dif2 = dif.multiply(.5);\n"+
"                var norm = dif.normalize();\n"+
"                var trans = startpoint.add(dif2);\n"+
"                connectornode.scale = new SFVec3f(1.0,dist,1.0);\n"+
"                connectornode.translation = trans;\n"+
"                connectornode.rotation = new SFRotation(new SFVec3f(0.0,1.0,0.0),norm);\n"+
"                //Browser.print('norm='+norm.toString());\n"+
"                //Browser.print('rotation='+rotation.toString());\n"+
"            }\n"+
"            function initialize(){\n"+
"                recompute(startnode.translation,endnode.translation);\n"+
"            }\n"+
"            function set_startpoint(val,t){\n"+
"                recompute(val,endnode.translation);\n"+
"            }\n"+
"            function set_endpoint(val,t){\n"+
"                recompute(startnode.translation,val);\n"+
"            }\n"+
"")
ProtoBody59.addChild(Script60)
ProtoDeclare52.setProtoBody(ProtoBody59)
Scene12.addChild(ProtoDeclare52)
ProtoInstance72 = ProtoInstanceObject().setName("point").setDEF("start")
Scene12.addChild(ProtoInstance72)
ProtoInstance73 = ProtoInstanceObject().setName("point").setDEF("end1")
Scene12.addChild(ProtoInstance73)
ProtoInstance74 = ProtoInstanceObject().setName("point").setDEF("end2")
Scene12.addChild(ProtoInstance74)
ProtoInstance75 = ProtoInstanceObject().setName("point").setDEF("end3")
Scene12.addChild(ProtoInstance75)
ProtoInstance76 = ProtoInstanceObject().setName("x3dconnector").setDEF("connector1")
fieldValue77 = fieldValueObject().setName("startnode")
ProtoInstance78 = ProtoInstanceObject().setName("point").setUSE("start")
fieldValue77.addChild(ProtoInstance78)
ProtoInstance76.addFieldValue(fieldValue77)
fieldValue79 = fieldValueObject().setName("endnode")
ProtoInstance80 = ProtoInstanceObject().setName("point").setUSE("end1")
fieldValue79.addChild(ProtoInstance80)
ProtoInstance76.addFieldValue(fieldValue79)
fieldValue81 = fieldValueObject().setName("connectornode")
Transform82 = TransformObject().setUSE("cylinder1")
fieldValue81.addChild(Transform82)
ProtoInstance76.addFieldValue(fieldValue81)
Scene12.addChild(ProtoInstance76)
ProtoInstance83 = ProtoInstanceObject().setName("x3dconnector").setDEF("connector2")
fieldValue84 = fieldValueObject().setName("startnode")
ProtoInstance85 = ProtoInstanceObject().setName("point").setUSE("start")
fieldValue84.addChild(ProtoInstance85)
ProtoInstance83.addFieldValue(fieldValue84)
fieldValue86 = fieldValueObject().setName("endnode")
ProtoInstance87 = ProtoInstanceObject().setName("point").setUSE("end2")
fieldValue86.addChild(ProtoInstance87)
ProtoInstance83.addFieldValue(fieldValue86)
fieldValue88 = fieldValueObject().setName("connectornode")
Transform89 = TransformObject().setUSE("cylinder2")
fieldValue88.addChild(Transform89)
ProtoInstance83.addFieldValue(fieldValue88)
Scene12.addChild(ProtoInstance83)
ProtoInstance90 = ProtoInstanceObject().setName("x3dconnector").setDEF("connector3")
fieldValue91 = fieldValueObject().setName("startnode")
ProtoInstance92 = ProtoInstanceObject().setName("point").setUSE("start")
fieldValue91.addChild(ProtoInstance92)
ProtoInstance90.addFieldValue(fieldValue91)
fieldValue93 = fieldValueObject().setName("endnode")
ProtoInstance94 = ProtoInstanceObject().setName("point").setUSE("end3")
fieldValue93.addChild(ProtoInstance94)
ProtoInstance90.addFieldValue(fieldValue93)
fieldValue95 = fieldValueObject().setName("connectornode")
Transform96 = TransformObject().setUSE("cylinder3")
fieldValue95.addChild(Transform96)
ProtoInstance90.addFieldValue(fieldValue95)
Scene12.addChild(ProtoInstance90)
ROUTE97 = ROUTEObject().setFromNode("start").setFromField("translation").setToNode("connector1").setToField("set_startpoint")
Scene12.addChild(ROUTE97)
ROUTE98 = ROUTEObject().setFromNode("end1").setFromField("translation").setToNode("connector1").setToField("set_endpoint")
Scene12.addChild(ROUTE98)
ROUTE99 = ROUTEObject().setFromNode("start").setFromField("translation").setToNode("connector2").setToField("set_startpoint")
Scene12.addChild(ROUTE99)
ROUTE100 = ROUTEObject().setFromNode("end2").setFromField("translation").setToNode("connector2").setToField("set_endpoint")
Scene12.addChild(ROUTE100)
ROUTE101 = ROUTEObject().setFromNode("start").setFromField("translation").setToNode("connector3").setToField("set_startpoint")
Scene12.addChild(ROUTE101)
ROUTE102 = ROUTEObject().setFromNode("end3").setFromField("translation").setToNode("connector3").setToField("set_endpoint")
Scene12.addChild(ROUTE102)
X3D0.setScene(Scene12)

X3D0.toFileX3D("arc.new.x3d")
