/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://mvnrepository.com/artifacts")
    }

    maven {
        url = uri("https://oss.sonatype.org/content/groups/public")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.apache.commons:commons-lang3:3.4")
    api("org.slf4j:slf4j-log4j12:1.7.12")
    implementation("net.sf.saxon:Saxon-HE:12.3")
    api("org.glassfish:javax.json:1.0.4")
    implementation("org.graalvm.js:js:20.2.0")
    implementation("org.graalvm.js:js-scriptengine:20.2.0")
    implementation("org.web3d.x3d:X3DJSAIL:4.0.full")
}

group = "net.coderextreme"
version = "11.0-SNAPSHOT"
description = "X3DJSONLD"
java.sourceCompatibility = JavaVersion.VERSION_20

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
