#!/bin/bash
export X3DJSONLD=C:/Users/coderextreme/pythonSAI
export CLASSPATH=".;${X3DJSONLD}/saxon9he.jar;${X3DJSONLD}/jslint4java-2.0.5.jar;${X3DJSONLD}/json-schema-validator-2.2.6-lib.jar;${X3DJSONLD}/X3DJSAIL.3.3.full.jar"
# NASHORN DOES NOT TAKE C:
export PYTHONSAI=..\\pythonSAI
export NASHORN_CLASSPATH="${PYTHONSAI}\\X3DJSAIL.3.3.full.jar;.;${PYTHONSAI}\\saxon9he.jar;${PYTHONSAI}\\jslint4java-2.0.5.jar;${PYTHONSAI}\\json-schema-validator-2.2.6-lib.jar"
