#!/bin/bash
export PYSAIHOME=C:\\Users\\coderextreme\\pythonSAI
export X3DJSONLD=../X3DJSONLD
export CLASSPATH=".;${PYSAIHOME}\\X3DJSAIL.3.3.classes.jar;${PYSAIHOME}\\saxon9he.jar"
# NASHORN DOES NOT TAKE C:
export PYTHONSAI=..\\pythonSAI
export NASHORN_CLASSPATH=".;${PYTHONSAI}\\X3DJSAIL.3.3.classes.jar;${PYTHONSAI}\\saxon9he.jar"
export PYTHONPATH=/usr/bin:/c/Python27:/c/Python27/Scripts
export PATH="${PYTHONPATH};${JAVA_HOME}/bin;${JAVA_HOME}/jre/bin/server;${PATH}"
export PYTHON=python.exe
export PIP=pip.exe
export NODE=node.exe
