from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("CoordinateAxis.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("Unknown, see X3D Resources Archives")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/CoordinateAxis.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("a box")
head1.addMeta(meta6)
meta7 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta7)
meta8 = metaObject().setName("generator").setContent("X3dToJson.xslt, http://www.web3d.org/x3d/stylesheets/X3dToJson.html")
head1.addMeta(meta8)
meta9 = metaObject().setName("reference").setContent("X3D JSON encoding: http://www.web3d.org/wiki/index.php/X3D_JSON_Encoding")
head1.addMeta(meta9)
meta10 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta10)
meta11 = metaObject().setName("generator").setContent("X3DJSONLD: https://github.com/coderextreme/X3DJSONLD")
head1.addMeta(meta11)
X3D0.setHead(head1)
Scene12 = SceneObject()
Collision13 = CollisionObject().setDEF("DoNotCollideWithVisualizationWidget")

Collision13.addComments(CommentsBlock("Invoke CoordinateAxes in other scenes as an Inline child inside a scaling Transform node, at the topmost level of the scene graph."))

Collision13.addComments(CommentsBlock("This NavigationInfo allows examine mode and will be overridden by any parent scene."))

Collision13.addComments(CommentsBlock("Each arrow goes from +1m to -1m to allow linear scaling to fit a scene"))

Collision13.addComments(CommentsBlock("Note each label rotates about the scene's vertical Y axis for consistency, enabling local orientation by user"))
Group14 = GroupObject()

Group14.addComments(CommentsBlock("Vertical Y arrow and label"))
Group15 = GroupObject().setDEF("ArrowGreen")
Shape16 = ShapeObject()
Cylinder17 = CylinderObject().setDEF("ArrowCylinder").setRadius(0.025).setTop(False)
Shape16.setGeometry(Cylinder17)
Appearance18 = AppearanceObject().setDEF("Green")
Material19 = MaterialObject().setDiffuseColor([0.1,0.6,0.1]).setEmissiveColor([0.05,0.2,0.05])
Appearance18.setMaterial(Material19)
Shape16.setAppearance(Appearance18)
Group15.addChild(Shape16)
Transform20 = TransformObject().setTranslation([0,1,0])
Shape21 = ShapeObject()
Cone22 = ConeObject().setDEF("ArrowCone").setBottomRadius(0.05).setHeight(0.1)
Shape21.setGeometry(Cone22)
Appearance23 = AppearanceObject().setUSE("Green")
Shape21.setAppearance(Appearance23)
Transform20.addChild(Shape21)
Group15.addChild(Transform20)
Group14.addChild(Group15)
Transform24 = TransformObject().setTranslation([0,1.08,0])
Billboard25 = BillboardObject()
Shape26 = ShapeObject()
Appearance27 = AppearanceObject().setDEF("LABEL_APPEARANCE")
Material28 = MaterialObject().setDiffuseColor([1,1,0.3]).setEmissiveColor([0.33,0.33,0.1])
Appearance27.setMaterial(Material28)
Shape26.setAppearance(Appearance27)
Text29 = TextObject().setString(["Y"])
FontStyle30 = FontStyleObject().setDEF("LABEL_FONT").setFamily(["SANS"]).setJustify(["MIDDLE","MIDDLE"]).setSize(0.2)
Text29.setFontStyle(FontStyle30)
Shape26.setGeometry(Text29)
Billboard25.addChild(Shape26)
Transform24.addChild(Billboard25)
Group14.addChild(Transform24)
Collision13.addChild(Group14)
Transform31 = TransformObject().setRotation([0,0,1,-1.57079])

Transform31.addComments(CommentsBlock("Horizontal X arrow and label"))
Group32 = GroupObject()
Group33 = GroupObject().setDEF("ArrowRed")
Shape34 = ShapeObject()
Cylinder35 = CylinderObject().setUSE("ArrowCylinder")
Shape34.setGeometry(Cylinder35)
Appearance36 = AppearanceObject().setDEF("Red")
Material37 = MaterialObject().setDiffuseColor([0.7,0.1,0.1]).setEmissiveColor([0.33,0,0])
Appearance36.setMaterial(Material37)
Shape34.setAppearance(Appearance36)
Group33.addChild(Shape34)
Transform38 = TransformObject().setTranslation([0,1,0])
Shape39 = ShapeObject()
Cone40 = ConeObject().setUSE("ArrowCone")
Shape39.setGeometry(Cone40)
Appearance41 = AppearanceObject().setUSE("Red")
Shape39.setAppearance(Appearance41)
Transform38.addChild(Shape39)
Group33.addChild(Transform38)
Group32.addChild(Group33)
Transform42 = TransformObject().setRotation([0,0,1,1.57079]).setTranslation([0.072,1.1,0])

Transform42.addComments(CommentsBlock("note label rotated back to original coordinate frame"))
Billboard43 = BillboardObject()
Shape44 = ShapeObject()
Appearance45 = AppearanceObject().setUSE("LABEL_APPEARANCE")
Shape44.setAppearance(Appearance45)
Text46 = TextObject().setString(["X"])
FontStyle47 = FontStyleObject().setUSE("LABEL_FONT")
Text46.setFontStyle(FontStyle47)
Shape44.setGeometry(Text46)
Billboard43.addChild(Shape44)
Transform42.addChild(Billboard43)
Group32.addChild(Transform42)
Transform31.addChild(Group32)
Collision13.addChild(Transform31)
Transform48 = TransformObject().setRotation([1,0,0,1.57079])

Transform48.addComments(CommentsBlock("Perpendicular Z arrow and label, note right-hand rule"))
Group49 = GroupObject()
Group50 = GroupObject().setDEF("ArrowBlue")
Shape51 = ShapeObject()
Cylinder52 = CylinderObject().setUSE("ArrowCylinder")
Shape51.setGeometry(Cylinder52)
Appearance53 = AppearanceObject().setDEF("Blue")
Material54 = MaterialObject().setDiffuseColor([0.3,0.3,1]).setEmissiveColor([0.1,0.1,0.33])
Appearance53.setMaterial(Material54)
Shape51.setAppearance(Appearance53)
Group50.addChild(Shape51)
Transform55 = TransformObject().setTranslation([0,1,0])
Shape56 = ShapeObject()
Cone57 = ConeObject().setUSE("ArrowCone")
Shape56.setGeometry(Cone57)
Appearance58 = AppearanceObject().setUSE("Blue")
Shape56.setAppearance(Appearance58)
Transform55.addChild(Shape56)
Group50.addChild(Transform55)
Group49.addChild(Group50)
Transform59 = TransformObject().setRotation([1,0,0,-1.57079]).setTranslation([0,1.1,0.072])

Transform59.addComments(CommentsBlock("note label rotated back to original coordinate frame"))
Billboard60 = BillboardObject()
Shape61 = ShapeObject()
Appearance62 = AppearanceObject().setUSE("LABEL_APPEARANCE")
Shape61.setAppearance(Appearance62)
Text63 = TextObject().setString(["Z"])
FontStyle64 = FontStyleObject().setUSE("LABEL_FONT")
Text63.setFontStyle(FontStyle64)
Shape61.setGeometry(Text63)
Billboard60.addChild(Shape61)
Transform59.addChild(Billboard60)
Group49.addChild(Transform59)
Transform48.addChild(Group49)
Collision13.addChild(Transform48)
Scene12.addChild(Collision13)
X3D0.setScene(Scene12)

X3D0.toFileX3D("CoordinateAxes.new.x3d")
