from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("geo.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/geo.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("a sphere")
head1.addMeta(meta6)
meta7 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta7)
meta8 = metaObject().setName("generator").setContent("X3dToJson.xslt, http://www.web3d.org/x3d/stylesheets/X3dToJson.html")
head1.addMeta(meta8)
meta9 = metaObject().setName("reference").setContent("X3D JSON encoding: http://www.web3d.org/wiki/index.php/X3D_JSON_Encoding")
head1.addMeta(meta9)
meta10 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta10)
meta11 = metaObject().setName("generator").setContent("X3DJSONLD: https://github.com/coderextreme/X3DJSONLD")
head1.addMeta(meta11)
X3D0.setHead(head1)
Scene12 = SceneObject()
NavigationInfo13 = NavigationInfoObject().setType(["EXAMINE"])
Scene12.addChild(NavigationInfo13)
Viewpoint14 = ViewpointObject().setDEF("Tour").setDescription("Tour Views")
Scene12.addChild(Viewpoint14)
Viewpoint15 = ViewpointObject().setPosition([0,0,4]).setDescription("sphere in road")
Scene12.addChild(Viewpoint15)
Background16 = BackgroundObject().setBackUrl(["bBK.png","http://coderextreme.net/bug/bBK.png"]).setBottomUrl(["bBT.png","http://coderextreme.net/bug/bBT.png"]).setFrontUrl(["bFR.png","http://coderextreme.net/bug/bFR.png"]).setLeftUrl(["bLF.png","http://coderextreme.net/bug/bLF.png"]).setRightUrl(["bRT.png","http://coderextreme.net/bug/bRT.png"]).setTopUrl(["bTP.png","http://coderextreme.net/bug/bTP.png"])
Scene12.addChild(Background16)
Transform17 = TransformObject().setDEF("Rose01")
Shape18 = ShapeObject()
Sphere19 = SphereObject()
Shape18.setGeometry(Sphere19)
Appearance20 = AppearanceObject().setDEF("_01_-_Default")
Material21 = MaterialObject().setDiffuseColor([0.7,0.7,0.7]).setSpecularColor([0.5,0.5,0.5])
Appearance20.setMaterial(Material21)
ComposedCubeMapTexture22 = ComposedCubeMapTextureObject()
ImageTexture23 = ImageTextureObject().setUrl(["bBK.png","http://coderextreme.net/bug/bBK.png"])
ComposedCubeMapTexture22.setBack(ImageTexture23)
ImageTexture24 = ImageTextureObject().setUrl(["bBT.png","http://coderextreme.net/bug/bBT.png"])
ComposedCubeMapTexture22.setBottom(ImageTexture24)
ImageTexture25 = ImageTextureObject().setUrl(["bFR.png","http://coderextreme.net/bug/bFR.png"])
ComposedCubeMapTexture22.setFront(ImageTexture25)
ImageTexture26 = ImageTextureObject().setUrl(["bLF.png","http://coderextreme.net/bug/bLF.png"])
ComposedCubeMapTexture22.setLeft(ImageTexture26)
ImageTexture27 = ImageTextureObject().setUrl(["bRT.png","http://coderextreme.net/bug/bRT.png"])
ComposedCubeMapTexture22.setRight(ImageTexture27)
ImageTexture28 = ImageTextureObject().setUrl(["bTP.png","http://coderextreme.net/bug/bTP.png"])
ComposedCubeMapTexture22.setTop(ImageTexture28)
Appearance20.setTexture(ComposedCubeMapTexture22)
ComposedShader29 = ComposedShaderObject().setDEF("cobweb").setLanguage("GLSL")
field30 = fieldObject().setType(fieldObject.TYPE_SFINT32).setName("cube").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0")
ComposedShader29.addField(field30)
field31 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("chromaticDispertion").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0.98 1 1.033")
ComposedShader29.addField(field31)
field32 = fieldObject().setType(fieldObject.TYPE_SFFLOAT).setName("bias").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0.5")
ComposedShader29.addField(field32)
field33 = fieldObject().setType(fieldObject.TYPE_SFFLOAT).setName("scale").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0.5")
ComposedShader29.addField(field33)
field34 = fieldObject().setType(fieldObject.TYPE_SFFLOAT).setName("power").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("2")
ComposedShader29.addField(field34)
ShaderPart35 = ShaderPartObject().setType("VERTEX").setUrl(["cobweb.vs","http://coderextreme.net/X3DJSONLD/cobweb.vs"])
ComposedShader29.addParts(ShaderPart35)
ShaderPart36 = ShaderPartObject().setType("FRAGMENT").setUrl(["pc_bubbles.fs","http://coderextreme.net/X3DJSONLD/pc_bubbles.fs"])
ComposedShader29.addParts(ShaderPart36)
Appearance20.addShaders(ComposedShader29)
ComposedShader37 = ComposedShaderObject().setDEF("x3dom").setLanguage("GLSL")
field38 = fieldObject().setType(fieldObject.TYPE_SFINT32).setName("cube").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0")
ComposedShader37.addField(field38)
field39 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("chromaticDispertion").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0.98 1 1.033")
ComposedShader37.addField(field39)
field40 = fieldObject().setType(fieldObject.TYPE_SFFLOAT).setName("bias").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0.5")
ComposedShader37.addField(field40)
field41 = fieldObject().setType(fieldObject.TYPE_SFFLOAT).setName("scale").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0.5")
ComposedShader37.addField(field41)
field42 = fieldObject().setType(fieldObject.TYPE_SFFLOAT).setName("power").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("2")
ComposedShader37.addField(field42)
ShaderPart43 = ShaderPartObject().setType("VERTEX").setUrl(["x3dom.vs","http://coderextreme.net/X3DJSONLD/x3dom.vs"])
ComposedShader37.addParts(ShaderPart43)
ShaderPart44 = ShaderPartObject().setType("FRAGMENT").setUrl(["pc_bubbles.fs","http://coderextreme.net/X3DJSONLD/pc_bubbles.fs"])
ComposedShader37.addParts(ShaderPart44)
Appearance20.addShaders(ComposedShader37)
Shape18.setAppearance(Appearance20)
Transform17.addChild(Shape18)
Scene12.addChild(Transform17)
X3D0.setScene(Scene12)

X3D0.toFileX3D("geo.new.x3d")
