from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("ObliqueStrategies.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("description").setContent("Text scripting and animation example using Oblique Strategies card set by Brian Eno.")
head1.addMeta(meta3)
meta4 = metaObject().setName("creator").setContent("Don Brutzman, John Kelly, Ben Cheng")
head1.addMeta(meta4)
meta5 = metaObject().setName("created").setContent("3 November 2013")
head1.addMeta(meta5)
meta6 = metaObject().setName("modified").setContent("18 October 2015")
head1.addMeta(meta6)
meta7 = metaObject().setName("reference").setContent("oblique.html")
head1.addMeta(meta7)
meta8 = metaObject().setName("reference").setContent("ObliqueStrategies.txt")
head1.addMeta(meta8)
meta9 = metaObject().setName("reference").setContent("ObliqueStrategiesScript.js")
head1.addMeta(meta9)
meta10 = metaObject().setName("reference").setContent("http://music.hyperreal.org/artists/brian_eno/oblique/oblique.html")
head1.addMeta(meta10)
meta11 = metaObject().setName("reference").setContent("http://www.eno-web.co.uk/obliques.html")
head1.addMeta(meta11)
meta12 = metaObject().setName("reference").setContent("http://gothpunk.com/haiku-intro.html")
head1.addMeta(meta12)
meta13 = metaObject().setName("reference").setContent("http://www.rtqe.net/ObliqueStrategies/OSintro.html")
head1.addMeta(meta13)
meta14 = metaObject().setName("reference").setContent("https://en.wikipedia.org/wiki/Oblique_Strategies")
head1.addMeta(meta14)
meta15 = metaObject().setName("subject").setContent("Brian Eno, Oblique Strategies")
head1.addMeta(meta15)
meta16 = metaObject().setName("Image").setContent("images/ObliqueStrategiesEntryScreen.png")
head1.addMeta(meta16)
meta17 = metaObject().setName("audio").setContent("http://translate.google.com/translate_tts?tl=en&q=hello%20X3D")
head1.addMeta(meta17)
meta18 = metaObject().setName("audio").setContent("translate_tts_HelloX3D.mp3")
head1.addMeta(meta18)
meta19 = metaObject().setName("audio").setContent("translate_tts_HelloX3D.wav")
head1.addMeta(meta19)
meta20 = metaObject().setName("TODO").setContent("multiliingual translation parameter")
head1.addMeta(meta20)
meta21 = metaObject().setName("reference").setContent("http://stackoverflow.com/questions/9163988/download-mp3-from-google-translate-text-to-speech")
head1.addMeta(meta21)
meta22 = metaObject().setName("reference").setContent("http://www.greenbot.com/article/2105862/how-to-get-started-with-google-text-to-speech.html")
head1.addMeta(meta22)
meta23 = metaObject().setName("warning").setContent("under development, scene Sound/AudioClip triggering (or retrieved file format) not working")
head1.addMeta(meta23)
meta24 = metaObject().setName("warning").setContent("BSContact error: Script node TextScript: parse error: line 15 \" var strategy = [];")
head1.addMeta(meta24)
meta25 = metaObject().setName("identifier").setContent("http://X3dGraphics.com/examples/X3dForAdvancedModeling/Inspiration/ObliqueStrategies.x3d")
head1.addMeta(meta25)
meta26 = metaObject().setName("generator").setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit")
head1.addMeta(meta26)
meta27 = metaObject().setName("license").setContent("../license.html")
head1.addMeta(meta27)
meta28 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta28)
meta29 = metaObject().setName("generator").setContent("X3dToJson.xslt, http://www.web3d.org/x3d/stylesheets/X3dToJson.html")
head1.addMeta(meta29)
meta30 = metaObject().setName("reference").setContent("X3D JSON encoding: http://www.web3d.org/wiki/index.php/X3D_JSON_Encoding")
head1.addMeta(meta30)
meta31 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta31)
meta32 = metaObject().setName("generator").setContent("X3DJSONLD: https://github.com/coderextreme/X3DJSONLD")
head1.addMeta(meta32)
X3D0.setHead(head1)
Scene33 = SceneObject()
NavigationInfo34 = NavigationInfoObject()
Scene33.addChild(NavigationInfo34)
Background35 = BackgroundObject().setSkyColor([0.419608,0.427451,1])
Scene33.addChild(Background35)
Transform36 = TransformObject().setScale([0.4,0.4,0.4]).setTranslation([0,1,0])
TouchSensor37 = TouchSensorObject().setDEF("RandomTextClickedSensor").setDescription("Select to see a new strategy")
Transform36.addChild(TouchSensor37)
Shape38 = ShapeObject()
Text39 = TextObject().setString(["Oblique Strategies","","(Over One Hundred Worthwhile Dilemmas)","","by Brian Eno and Peter Schmidt"])
FontStyle40 = FontStyleObject().setDEF("MessageFont").setFamily(["SANS"]).setJustify(["MIDDLE","MIDDLE"]).setStyle("BOLD")
Text39.setFontStyle(FontStyle40)
Shape38.setGeometry(Text39)
Appearance41 = AppearanceObject()
Material42 = MaterialObject().setDiffuseColor([1,1,1])
Appearance41.setMaterial(Material42)
Shape38.setAppearance(Appearance41)
Transform36.addChild(Shape38)
Transform43 = TransformObject().setScale([10,3,1])
Shape44 = ShapeObject().setDEF("HeadlineClickSurface")
IndexedFaceSet45 = IndexedFaceSetObject().setCoordIndex([0,1,2,3,-1]).setSolid(False)
Coordinate46 = CoordinateObject().setPoint([1,1,0,1,-1,0,-1,-1,0,-1,1,0])
IndexedFaceSet45.setCoord(Coordinate46)
Shape44.setGeometry(IndexedFaceSet45)
Appearance47 = AppearanceObject()
Material48 = MaterialObject().setAmbientIntensity(0.245763).setDiffuseColor([0.34773,0.090909,0.005289]).setShininess(0.07).setSpecularColor([0.336735,0.051091,0.051091]).setTransparency(0.8)
Appearance47.setMaterial(Material48)
Shape44.setAppearance(Appearance47)
Transform43.addChild(Shape44)
Transform36.addChild(Transform43)
Scene33.addChild(Transform36)
Script49 = ScriptObject().setDEF("TextScript").setUrl(["./ObliqueStrategiesScript.js"])

Script49.addComments(CommentsBlock("initialize() method includes unit test to printAllStrategies() to console"))

Script49.addComments(CommentsBlock("TODO insert field definitions here (index string_changed previous next random) and then animate!"))
field50 = fieldObject().setType(fieldObject.TYPE_SFINT32).setName("index").setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY).setAppinfo("index for active strategy card, -1 means no selection").setValue("0")
Script49.addField(field50)
field51 = fieldObject().setType(fieldObject.TYPE_MFSTRING).setName("string_changed").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY).setAppinfo("latest strategy card value")
Script49.addField(field51)
field52 = fieldObject().setType(fieldObject.TYPE_MFSTRING).setName("textToSpeechUrl").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY).setAppinfo("url to invoke Google Translate")
Script49.addField(field52)
field53 = fieldObject().setType(fieldObject.TYPE_SFTIME).setName("newCardTime").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY).setAppinfo("activate Sound node")
Script49.addField(field53)
field54 = fieldObject().setType(fieldObject.TYPE_SFBOOL).setName("selectPreviousCard").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
Script49.addField(field54)
field55 = fieldObject().setType(fieldObject.TYPE_SFBOOL).setName("selectNextCard").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
Script49.addField(field55)
field56 = fieldObject().setType(fieldObject.TYPE_SFBOOL).setName("selectRandomCard").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
Script49.addField(field56)
field57 = fieldObject().setType(fieldObject.TYPE_SFBOOL).setName("traceEnabled").setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY).setAppinfo("controls console tracing").setValue("true")
Script49.addField(field57)
Scene33.addChild(Script49)
Transform58 = TransformObject().setDEF("CardTransform").setScale([0.4,0.4,0.4]).setTranslation([0,-1.5,0])
Shape59 = ShapeObject()
Text60 = TextObject().setDEF("CardText")
FontStyle61 = FontStyleObject().setFamily(["SANS"]).setJustify(["MIDDLE","MIDDLE"]).setStyle("BOLD")
Text60.setFontStyle(FontStyle61)
Shape59.setGeometry(Text60)
Appearance62 = AppearanceObject()
Material63 = MaterialObject().setDiffuseColor([1,1,1])
Appearance62.setMaterial(Material63)
Shape59.setAppearance(Appearance62)
Transform58.addChild(Shape59)
ROUTE64 = ROUTEObject().setFromField("string_changed").setFromNode("TextScript").setToField("string").setToNode("CardText")
Transform58.addChild(ROUTE64)
Sound65 = SoundObject().setDEF("CardSoundSpatialization").setMaxBack(100).setMaxFront(100).setMinBack(20).setMinFront(20)

Sound65.addComments(CommentsBlock("Make sure the sound source AudioClip is audible at the user location"))

Sound65.addComments(CommentsBlock("Not all X3D players seem to use the .mp3"))

Sound65.addComments(CommentsBlock("&#38; is ampersand character, avoids escaping problems and inconsistencies in browsers and X3D players"))

Sound65.addComments(CommentsBlock("%20 is space character used in uri/url encoding"))
AudioClip66 = AudioClipObject().setDEF("TextToSpeechAudioClip").setDescription("sends strategy text google translate").setUrl(["http://translate.google.com/translate_tts?tl=en&amp;q=Feed%20the%20recording%20back%20out%20of%20the%20medium","translate_tts_mp3FileFormatNotSupported.wav"])
Sound65.setSource(AudioClip66)
Transform58.addChild(Sound65)
ROUTE67 = ROUTEObject().setFromField("textToSpeechUrl").setFromNode("TextScript").setToField("url").setToNode("TextToSpeechAudioClip")
Transform58.addChild(ROUTE67)
ROUTE68 = ROUTEObject().setFromField("newCardTime").setFromNode("TextScript").setToField("startTime").setToNode("TextToSpeechAudioClip")
Transform58.addChild(ROUTE68)
Scene33.addChild(Transform58)
Transform69 = TransformObject().setScale([0.4,0.4,0.4]).setTranslation([-3.2,2.5,0])
TouchSensor70 = TouchSensorObject().setDEF("PreviousTextClickedSensor").setDescription("Select to see previous strategy")
Transform69.addChild(TouchSensor70)
ROUTE71 = ROUTEObject().setFromField("isActive").setFromNode("PreviousTextClickedSensor").setToField("selectPreviousCard").setToNode("TextScript")
Transform69.addChild(ROUTE71)
Shape72 = ShapeObject()
Text73 = TextObject().setString(["previous"])
FontStyle74 = FontStyleObject().setUSE("MessageFont")
Text73.setFontStyle(FontStyle74)
Shape72.setGeometry(Text73)
Appearance75 = AppearanceObject().setDEF("InterfaceAppearance")
Material76 = MaterialObject().setDiffuseColor([1,0,0.6])
Appearance75.setMaterial(Material76)
Shape72.setAppearance(Appearance75)
Transform69.addChild(Shape72)
Transform77 = TransformObject().setScale([2,0.6,1])
Shape78 = ShapeObject().setDEF("TransparentClickSurface")

Shape78.addComments(CommentsBlock("support Selectable Text with a scalable IFS"))
IndexedFaceSet79 = IndexedFaceSetObject().setCoordIndex([0,1,2,3,-1]).setSolid(False)
Coordinate80 = CoordinateObject().setPoint([1,1,0,1,-1,0,-1,-1,0,-1,1,0])
IndexedFaceSet79.setCoord(Coordinate80)
Shape78.setGeometry(IndexedFaceSet79)
Appearance81 = AppearanceObject()
Material82 = MaterialObject().setTransparency(1)
Appearance81.setMaterial(Material82)
Shape78.setAppearance(Appearance81)
Transform77.addChild(Shape78)
Transform69.addChild(Transform77)
Scene33.addChild(Transform69)
Transform83 = TransformObject().setScale([0.4,0.4,0.4]).setTranslation([3.5,2.5,0])
TouchSensor84 = TouchSensorObject().setDEF("NextTextClickedSensor").setDescription("Select to see next strategy")
Transform83.addChild(TouchSensor84)
ROUTE85 = ROUTEObject().setFromField("isActive").setFromNode("NextTextClickedSensor").setToField("selectNextCard").setToNode("TextScript")
Transform83.addChild(ROUTE85)
Shape86 = ShapeObject()
Text87 = TextObject().setString(["next"])
FontStyle88 = FontStyleObject().setUSE("MessageFont")
Text87.setFontStyle(FontStyle88)
Shape86.setGeometry(Text87)
Appearance89 = AppearanceObject().setUSE("InterfaceAppearance")
Shape86.setAppearance(Appearance89)
Transform83.addChild(Shape86)
Transform90 = TransformObject().setScale([1.2,0.6,1])
Shape91 = ShapeObject().setUSE("TransparentClickSurface")
Transform90.addChild(Shape91)
Transform83.addChild(Transform90)
Scene33.addChild(Transform83)
Transform92 = TransformObject().setScale([0.4,0.4,0.4]).setTranslation([-3.3,-0.5,0])
TouchSensor93 = TouchSensorObject().setUSE("RandomTextClickedSensor")
Transform92.addChild(TouchSensor93)
ROUTE94 = ROUTEObject().setFromField("isActive").setFromNode("RandomTextClickedSensor").setToField("selectRandomCard").setToNode("TextScript")
Transform92.addChild(ROUTE94)
Shape95 = ShapeObject()
Text96 = TextObject().setString(["random"])
FontStyle97 = FontStyleObject().setUSE("MessageFont")
Text96.setFontStyle(FontStyle97)
Shape95.setGeometry(Text96)
Appearance98 = AppearanceObject().setUSE("InterfaceAppearance")
Shape95.setAppearance(Appearance98)
Transform92.addChild(Shape95)
Transform99 = TransformObject().setScale([1.8,0.6,1])
Shape100 = ShapeObject().setUSE("TransparentClickSurface")
Transform99.addChild(Shape100)
Transform92.addChild(Transform99)
Scene33.addChild(Transform92)
Transform101 = TransformObject().setScale([0.4,0.4,0.4]).setTranslation([3.3,-0.5,0])
Anchor102 = AnchorObject().setDEF("TextToSpeechAnchor").setDescription("text to speech in browser").setParameter(["target=_blank"]).setUrl(["http://translate.google.com/translate_tts?tl=en&amp;q=Overtly%20resist%20change"])
ROUTE103 = ROUTEObject().setFromField("textToSpeechUrl").setFromNode("TextScript").setToField("url").setToNode("TextToSpeechAnchor")
Anchor102.addChild(ROUTE103)
Shape104 = ShapeObject()
Text105 = TextObject().setString(["speech"])
FontStyle106 = FontStyleObject().setUSE("MessageFont")
Text105.setFontStyle(FontStyle106)
Shape104.setGeometry(Text105)
Appearance107 = AppearanceObject().setUSE("InterfaceAppearance")
Shape104.setAppearance(Appearance107)
Anchor102.addChild(Shape104)
Transform108 = TransformObject().setScale([1.8,0.6,1])
Shape109 = ShapeObject().setUSE("TransparentClickSurface")
Transform108.addChild(Shape109)
Anchor102.addChild(Transform108)
Transform101.addChild(Anchor102)
Scene33.addChild(Transform101)
X3D0.setScene(Scene33)

X3D0.toFileX3D("ObliqueStrategies.new.x3d")
