from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("rubik.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/rubik.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("a kind of rubik cube with spheres")
head1.addMeta(meta6)
meta7 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta7)
meta8 = metaObject().setName("generator").setContent("X3dToJson.xslt, http://www.web3d.org/x3d/stylesheets/X3dToJson.html")
head1.addMeta(meta8)
meta9 = metaObject().setName("reference").setContent("X3D JSON encoding: http://www.web3d.org/wiki/index.php/X3D_JSON_Encoding")
head1.addMeta(meta9)
meta10 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta10)
meta11 = metaObject().setName("generator").setContent("X3DJSONLD: https://github.com/coderextreme/X3DJSONLD")
head1.addMeta(meta11)
X3D0.setHead(head1)
Scene12 = SceneObject()
NavigationInfo13 = NavigationInfoObject().setType(["EXAMINE"])
Scene12.addChild(NavigationInfo13)
Viewpoint14 = ViewpointObject().setDescription("Rubiks Cube").setPosition([0,0,12])
Scene12.addChild(Viewpoint14)
ProtoDeclare15 = ProtoDeclareObject().setName("sphere")
ProtoInterface16 = ProtoInterfaceObject()
field17 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("xtranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface16.addField(field17)
ProtoDeclare15.setProtoInterface(ProtoInterface16)
ProtoBody18 = ProtoBodyObject()
Transform19 = TransformObject()
IS20 = ISObject()
connect21 = connectObject().setNodeField("translation").setProtoField("xtranslation")
IS20.addConnect(connect21)
Transform19.setIS(IS20)
Shape22 = ShapeObject()
Sphere23 = SphereObject()
Shape22.setGeometry(Sphere23)
Appearance24 = AppearanceObject()
Material25 = MaterialObject().setDiffuseColor([1,1,1])
Appearance24.setMaterial(Material25)
Shape22.setAppearance(Appearance24)
Transform19.addChild(Shape22)
ProtoBody18.addChild(Transform19)
ProtoDeclare15.setProtoBody(ProtoBody18)
Scene12.addChild(ProtoDeclare15)
ProtoDeclare26 = ProtoDeclareObject().setName("three")
ProtoInterface27 = ProtoInterfaceObject()
field28 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ytranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface27.addField(field28)
ProtoDeclare26.setProtoInterface(ProtoInterface27)
ProtoBody29 = ProtoBodyObject()
Transform30 = TransformObject()
IS31 = ISObject()
connect32 = connectObject().setNodeField("translation").setProtoField("ytranslation")
IS31.addConnect(connect32)
Transform30.setIS(IS31)
ProtoInstance33 = ProtoInstanceObject().setName("sphere")
fieldValue34 = fieldValueObject().setName("xtranslation").setValue("0 0 0")
ProtoInstance33.addFieldValue(fieldValue34)
Transform30.addChild(ProtoInstance33)
ProtoInstance35 = ProtoInstanceObject().setName("sphere")
fieldValue36 = fieldValueObject().setName("xtranslation").setValue("2 0 0")
ProtoInstance35.addFieldValue(fieldValue36)
Transform30.addChild(ProtoInstance35)
ProtoInstance37 = ProtoInstanceObject().setName("sphere")
fieldValue38 = fieldValueObject().setName("xtranslation").setValue("-2 0 0")
ProtoInstance37.addFieldValue(fieldValue38)
Transform30.addChild(ProtoInstance37)
ProtoBody29.addChild(Transform30)
ProtoDeclare26.setProtoBody(ProtoBody29)
Scene12.addChild(ProtoDeclare26)
ProtoDeclare39 = ProtoDeclareObject().setName("nine")
ProtoInterface40 = ProtoInterfaceObject()
field41 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ztranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface40.addField(field41)
ProtoDeclare39.setProtoInterface(ProtoInterface40)
ProtoBody42 = ProtoBodyObject()
Transform43 = TransformObject()
IS44 = ISObject()
connect45 = connectObject().setNodeField("translation").setProtoField("ztranslation")
IS44.addConnect(connect45)
Transform43.setIS(IS44)
ProtoInstance46 = ProtoInstanceObject().setName("three")
fieldValue47 = fieldValueObject().setName("ytranslation").setValue("0 0 0")
ProtoInstance46.addFieldValue(fieldValue47)
Transform43.addChild(ProtoInstance46)
ProtoInstance48 = ProtoInstanceObject().setName("three")
fieldValue49 = fieldValueObject().setName("ytranslation").setValue("0 2 0")
ProtoInstance48.addFieldValue(fieldValue49)
Transform43.addChild(ProtoInstance48)
ProtoInstance50 = ProtoInstanceObject().setName("three")
fieldValue51 = fieldValueObject().setName("ytranslation").setValue("0 -2 0")
ProtoInstance50.addFieldValue(fieldValue51)
Transform43.addChild(ProtoInstance50)
ProtoBody42.addChild(Transform43)
ProtoDeclare39.setProtoBody(ProtoBody42)
Scene12.addChild(ProtoDeclare39)
ProtoDeclare52 = ProtoDeclareObject().setName("twentyseven")
ProtoInterface53 = ProtoInterfaceObject()
field54 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ttranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface53.addField(field54)
ProtoDeclare52.setProtoInterface(ProtoInterface53)
ProtoBody55 = ProtoBodyObject()
Transform56 = TransformObject()
IS57 = ISObject()
connect58 = connectObject().setNodeField("translation").setProtoField("ttranslation")
IS57.addConnect(connect58)
Transform56.setIS(IS57)
ProtoInstance59 = ProtoInstanceObject().setName("nine")
fieldValue60 = fieldValueObject().setName("ztranslation").setValue("0 0 0")
ProtoInstance59.addFieldValue(fieldValue60)
Transform56.addChild(ProtoInstance59)
ProtoInstance61 = ProtoInstanceObject().setName("nine")
fieldValue62 = fieldValueObject().setName("ztranslation").setValue("0 0 2")
ProtoInstance61.addFieldValue(fieldValue62)
Transform56.addChild(ProtoInstance61)
ProtoInstance63 = ProtoInstanceObject().setName("nine")
fieldValue64 = fieldValueObject().setName("ztranslation").setValue("0 0 -2")
ProtoInstance63.addFieldValue(fieldValue64)
Transform56.addChild(ProtoInstance63)
ProtoBody55.addChild(Transform56)
ProtoDeclare52.setProtoBody(ProtoBody55)
Scene12.addChild(ProtoDeclare52)
ProtoInstance65 = ProtoInstanceObject().setName("twentyseven")
fieldValue66 = fieldValueObject().setName("ttranslation").setValue("0 0 0")
ProtoInstance65.addFieldValue(fieldValue66)
Scene12.addChild(ProtoInstance65)
X3D0.setScene(Scene12)

X3D0.toFileX3D("rubik.new.x3d")
