from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("rubikFurnace.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/rubikFurnace.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("a green rubik cube")
head1.addMeta(meta6)
meta7 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta7)
meta8 = metaObject().setName("generator").setContent("X3dToJson.xslt, http://www.web3d.org/x3d/stylesheets/X3dToJson.html")
head1.addMeta(meta8)
meta9 = metaObject().setName("reference").setContent("X3D JSON encoding: http://www.web3d.org/wiki/index.php/X3D_JSON_Encoding")
head1.addMeta(meta9)
meta10 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta10)
meta11 = metaObject().setName("generator").setContent("X3DJSONLD: https://github.com/coderextreme/X3DJSONLD")
head1.addMeta(meta11)
X3D0.setHead(head1)
Scene12 = SceneObject()
NavigationInfo13 = NavigationInfoObject().setType(["EXAMINE"])
Scene12.addChild(NavigationInfo13)
Viewpoint14 = ViewpointObject().setDescription("Rubiks Cube on Fire").setPosition([0,0,12])
Scene12.addChild(Viewpoint14)
ProtoDeclare15 = ProtoDeclareObject().setName("anyShape")
ProtoInterface16 = ProtoInterfaceObject()
field17 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("xtranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface16.addField(field17)
field18 = fieldObject().setType(fieldObject.TYPE_MFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Shape19 = ShapeObject()
Sphere20 = SphereObject()
Shape19.setGeometry(Sphere20)
Appearance21 = AppearanceObject()
Material22 = MaterialObject().setDiffuseColor([1,1,1])
Appearance21.setMaterial(Material22)
Shape19.setAppearance(Appearance21)
field18.addChild(Shape19)
ProtoInterface16.addField(field18)
ProtoDeclare15.setProtoInterface(ProtoInterface16)
ProtoBody23 = ProtoBodyObject()
Transform24 = TransformObject()
IS25 = ISObject()
connect26 = connectObject().setNodeField("translation").setProtoField("xtranslation")
IS25.addConnect(connect26)
connect27 = connectObject().setNodeField("children").setProtoField("myShape")
IS25.addConnect(connect27)
Transform24.setIS(IS25)
ProtoBody23.addChild(Transform24)
ProtoDeclare15.setProtoBody(ProtoBody23)
Scene12.addChild(ProtoDeclare15)
ProtoDeclare28 = ProtoDeclareObject().setName("three")
ProtoInterface29 = ProtoInterfaceObject()
field30 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ytranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface29.addField(field30)
field31 = fieldObject().setType(fieldObject.TYPE_MFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Shape32 = ShapeObject()
Sphere33 = SphereObject()
Shape32.setGeometry(Sphere33)
Appearance34 = AppearanceObject()
Material35 = MaterialObject().setDiffuseColor([1,1,1])
Appearance34.setMaterial(Material35)
Shape32.setAppearance(Appearance34)
field31.addChild(Shape32)
ProtoInterface29.addField(field31)
ProtoDeclare28.setProtoInterface(ProtoInterface29)
ProtoBody36 = ProtoBodyObject()
Transform37 = TransformObject()
IS38 = ISObject()
connect39 = connectObject().setNodeField("translation").setProtoField("ytranslation")
IS38.addConnect(connect39)
Transform37.setIS(IS38)
ProtoInstance40 = ProtoInstanceObject().setName("anyShape")
fieldValue41 = fieldValueObject().setName("xtranslation").setValue("0 0 0")
ProtoInstance40.addFieldValue(fieldValue41)
IS42 = ISObject()
connect43 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS42.addConnect(connect43)
ProtoInstance40.setIS(IS42)
Transform37.addChild(ProtoInstance40)
ProtoInstance44 = ProtoInstanceObject().setName("anyShape")
fieldValue45 = fieldValueObject().setName("xtranslation").setValue("2 0 0")
ProtoInstance44.addFieldValue(fieldValue45)
IS46 = ISObject()
connect47 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS46.addConnect(connect47)
ProtoInstance44.setIS(IS46)
Transform37.addChild(ProtoInstance44)
ProtoInstance48 = ProtoInstanceObject().setName("anyShape")
fieldValue49 = fieldValueObject().setName("xtranslation").setValue("-2 0 0")
ProtoInstance48.addFieldValue(fieldValue49)
IS50 = ISObject()
connect51 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS50.addConnect(connect51)
ProtoInstance48.setIS(IS50)
Transform37.addChild(ProtoInstance48)
ProtoBody36.addChild(Transform37)
ProtoDeclare28.setProtoBody(ProtoBody36)
Scene12.addChild(ProtoDeclare28)
ProtoDeclare52 = ProtoDeclareObject().setName("nine")
ProtoInterface53 = ProtoInterfaceObject()
field54 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ztranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface53.addField(field54)
field55 = fieldObject().setType(fieldObject.TYPE_MFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Shape56 = ShapeObject()
Sphere57 = SphereObject()
Shape56.setGeometry(Sphere57)
Appearance58 = AppearanceObject()
Material59 = MaterialObject().setDiffuseColor([1,1,1])
Appearance58.setMaterial(Material59)
Shape56.setAppearance(Appearance58)
field55.addChild(Shape56)
ProtoInterface53.addField(field55)
ProtoDeclare52.setProtoInterface(ProtoInterface53)
ProtoBody60 = ProtoBodyObject()
Transform61 = TransformObject()
IS62 = ISObject()
connect63 = connectObject().setNodeField("translation").setProtoField("ztranslation")
IS62.addConnect(connect63)
Transform61.setIS(IS62)
ProtoInstance64 = ProtoInstanceObject().setName("three")
fieldValue65 = fieldValueObject().setName("ytranslation").setValue("0 0 0")
ProtoInstance64.addFieldValue(fieldValue65)
IS66 = ISObject()
connect67 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS66.addConnect(connect67)
ProtoInstance64.setIS(IS66)
Transform61.addChild(ProtoInstance64)
ProtoInstance68 = ProtoInstanceObject().setName("three")
fieldValue69 = fieldValueObject().setName("ytranslation").setValue("0 2 0")
ProtoInstance68.addFieldValue(fieldValue69)
IS70 = ISObject()
connect71 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS70.addConnect(connect71)
ProtoInstance68.setIS(IS70)
Transform61.addChild(ProtoInstance68)
ProtoInstance72 = ProtoInstanceObject().setName("three")
fieldValue73 = fieldValueObject().setName("ytranslation").setValue("0 -2 0")
ProtoInstance72.addFieldValue(fieldValue73)
IS74 = ISObject()
connect75 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS74.addConnect(connect75)
ProtoInstance72.setIS(IS74)
Transform61.addChild(ProtoInstance72)
ProtoBody60.addChild(Transform61)
ProtoDeclare52.setProtoBody(ProtoBody60)
Scene12.addChild(ProtoDeclare52)
ProtoDeclare76 = ProtoDeclareObject().setName("twentyseven")
ProtoInterface77 = ProtoInterfaceObject()
field78 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ttranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface77.addField(field78)
field79 = fieldObject().setType(fieldObject.TYPE_MFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Shape80 = ShapeObject()
Sphere81 = SphereObject()
Shape80.setGeometry(Sphere81)
Appearance82 = AppearanceObject()
Material83 = MaterialObject().setDiffuseColor([1,1,1])
Appearance82.setMaterial(Material83)
Shape80.setAppearance(Appearance82)
field79.addChild(Shape80)
ProtoInterface77.addField(field79)
ProtoDeclare76.setProtoInterface(ProtoInterface77)
ProtoBody84 = ProtoBodyObject()
Transform85 = TransformObject()
IS86 = ISObject()
connect87 = connectObject().setNodeField("translation").setProtoField("ttranslation")
IS86.addConnect(connect87)
Transform85.setIS(IS86)
ProtoInstance88 = ProtoInstanceObject().setName("nine")
fieldValue89 = fieldValueObject().setName("ztranslation").setValue("0 0 0")
ProtoInstance88.addFieldValue(fieldValue89)
IS90 = ISObject()
connect91 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS90.addConnect(connect91)
ProtoInstance88.setIS(IS90)
Transform85.addChild(ProtoInstance88)
ProtoInstance92 = ProtoInstanceObject().setName("nine")
fieldValue93 = fieldValueObject().setName("ztranslation").setValue("0 0 2")
ProtoInstance92.addFieldValue(fieldValue93)
IS94 = ISObject()
connect95 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS94.addConnect(connect95)
ProtoInstance92.setIS(IS94)
Transform85.addChild(ProtoInstance92)
ProtoInstance96 = ProtoInstanceObject().setName("nine")
fieldValue97 = fieldValueObject().setName("ztranslation").setValue("0 0 -2")
ProtoInstance96.addFieldValue(fieldValue97)
IS98 = ISObject()
connect99 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS98.addConnect(connect99)
ProtoInstance96.setIS(IS98)
Transform85.addChild(ProtoInstance96)
ProtoBody84.addChild(Transform85)
ProtoDeclare76.setProtoBody(ProtoBody84)
Scene12.addChild(ProtoDeclare76)
ProtoInstance100 = ProtoInstanceObject().setName("twentyseven")
fieldValue101 = fieldValueObject().setName("ttranslation").setValue("0 0 0")
ProtoInstance100.addFieldValue(fieldValue101)
fieldValue102 = fieldValueObject().setName("myShape")
Shape103 = ShapeObject()
Box104 = BoxObject().setSize([1,1,1])
Shape103.setGeometry(Box104)
Appearance105 = AppearanceObject()
Material106 = MaterialObject().setDiffuseColor([0,1,0])
Appearance105.setMaterial(Material106)
Shape103.setAppearance(Appearance105)
fieldValue102.addChild(Shape103)
ProtoInstance100.addFieldValue(fieldValue102)
Scene12.addChild(ProtoInstance100)
X3D0.setScene(Scene12)

X3D0.toFileX3D("rubikFurnace.new.x3d")
