from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Interchange").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("sphere.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/sphere.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("a sphere")
head1.addMeta(meta6)
meta7 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta7)
meta8 = metaObject().setName("generator").setContent("X3dToJson.xslt, http://www.web3d.org/x3d/stylesheets/X3dToJson.html")
head1.addMeta(meta8)
meta9 = metaObject().setName("reference").setContent("X3D JSON encoding: http://www.web3d.org/wiki/index.php/X3D_JSON_Encoding")
head1.addMeta(meta9)
meta10 = metaObject().setName("translated").setContent("10 May 2017")
head1.addMeta(meta10)
meta11 = metaObject().setName("generator").setContent("X3DJSONLD: https://github.com/coderextreme/X3DJSONLD")
head1.addMeta(meta11)
X3D0.setHead(head1)
Scene12 = SceneObject()
Group13 = GroupObject()
Shape14 = ShapeObject()
Appearance15 = AppearanceObject()
Material16 = MaterialObject().setDiffuseColor([1,1,1])
Appearance15.setMaterial(Material16)
Shape14.setAppearance(Appearance15)
Sphere17 = SphereObject()
Shape14.setGeometry(Sphere17)
Group13.addChild(Shape14)
Scene12.addChild(Group13)
X3D0.setScene(Scene12)

X3D0.toFileX3D("sphere.new.x3d")
