from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("creator").setContent("John W Carlson")
head1.addMeta(meta2)
meta3 = metaObject().setName("created").setContent("December 13 2015")
head1.addMeta(meta3)
meta4 = metaObject().setName("title").setContent("text.x3d")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/text.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("test text")
head1.addMeta(meta6)
meta7 = metaObject().setName("generator").setContent("Vim, X3D-Edit, https://savage.nps.edu/X3D-Edit")
head1.addMeta(meta7)
meta8 = metaObject().setName("translated").setContent("08 May 2017")
head1.addMeta(meta8)
meta9 = metaObject().setName("generator").setContent("X3dToJson.xslt, http://www.web3d.org/x3d/stylesheets/X3dToJson.html")
head1.addMeta(meta9)
meta10 = metaObject().setName("reference").setContent("X3D JSON encoding: http://www.web3d.org/wiki/index.php/X3D_JSON_Encoding")
head1.addMeta(meta10)
meta11 = metaObject().setName("translated").setContent("8 May 2017")
head1.addMeta(meta11)
meta12 = metaObject().setName("generator").setContent("X3DJSONLD: https://github.com/coderextreme/X3DJSONLD")
head1.addMeta(meta12)
X3D0.setHead(head1)
Scene13 = SceneObject()
Transform14 = TransformObject()
Shape15 = ShapeObject()
Text16 = TextObject().setString(["Node\\\"\\\"\\\""])
FontStyle17 = FontStyleObject().setJustify(["MIDDLE","MIDDLE"]).setSize(5)
Text16.setFontStyle(FontStyle17)
Shape15.setGeometry(Text16)
Appearance18 = AppearanceObject()
Material19 = MaterialObject().setDiffuseColor([0,0,1])
Appearance18.setMaterial(Material19)
Shape15.setAppearance(Appearance18)
Transform14.addChild(Shape15)
Scene13.addChild(Transform14)
X3D0.setScene(Scene13)

X3D0.toFileX3D("text.new.x3d")
