import x3dpsail as x3d

x3d.ConfigurationProperties.setXsltEngine(x3d.ConfigurationProperties.XSLT_ENGINE_NATIVE_JAVA)
x3d.ConfigurationProperties.setDeleteIntermediateFiles(False)
x3d.ConfigurationProperties.setStripTrailingZeroes(True)
x3d.ConfigurationProperties.setStripDefaultAttributes(True)
X3D0 = x3d.X3D()
X3D0.setProfile("Immersive")
X3D0.setVersion("4.0")
head1 = x3d.head()
meta2 = x3d.meta()
meta2.setName("title")
meta2.setContent("Oxytocin.x3d")

head1.addMeta(meta2)
meta3 = x3d.meta()
meta3.setName("description")
meta3.setContent("Autogenerated version of Oxytocin.x3d scene produced from Oxytocin.xml Chemical Markup Language (CML) version 1.0 source file.")

head1.addMeta(meta3)
meta4 = x3d.meta()
meta4.setName("creator")
meta4.setContent("Nicholas F. Polys")

head1.addMeta(meta4)
meta5 = x3d.meta()
meta5.setName("translator")
meta5.setContent("Don Brutzman")

head1.addMeta(meta5)
meta6 = x3d.meta()
meta6.setName("created")
meta6.setContent("24 November 2005")

head1.addMeta(meta6)
meta7 = x3d.meta()
meta7.setName("translated")
meta7.setContent("2 JAN 2025")

head1.addMeta(meta7)
meta8 = x3d.meta()
meta8.setName("modified")
meta8.setContent("2 JAN 2025")

head1.addMeta(meta8)
meta9 = x3d.meta()
meta9.setName("reference")
meta9.setContent("Oxytocin.xml")

head1.addMeta(meta9)
meta10 = x3d.meta()
meta10.setName("reference")
meta10.setContent("CML sources https://www.xml-cml.org")

head1.addMeta(meta10)
meta11 = x3d.meta()
meta11.setName("reference")
meta11.setContent("Wikipedia https://en.wikipedia.org/wiki/Chemical_Markup_Language")

head1.addMeta(meta11)
meta12 = x3d.meta()
meta12.setName("reference")
meta12.setContent("JUMBO Chemical Format Conversion Tool")

head1.addMeta(meta12)
meta13 = x3d.meta()
meta13.setName("reference")
meta13.setContent("https://webbook.nist.gov/chemistry")

head1.addMeta(meta13)
meta14 = x3d.meta()
meta14.setName("reference")
meta14.setContent("Polys.StylesheetTransformationsInteractiveVisualization.Web3d2003Symposium.pdf")

head1.addMeta(meta14)
meta15 = x3d.meta()
meta15.setName("reference")
meta15.setContent("Originally Published in Proceedings of Web3D 2003, ACM Press")

head1.addMeta(meta15)
meta16 = x3d.meta()
meta16.setName("generator")
meta16.setContent("CmlToX3d.xslt")

head1.addMeta(meta16)
meta17 = x3d.meta()
meta17.setName("identifier")
meta17.setContent("https://www.web3d.org/x3d/content/examples/Basic/ChemicalMarkupLanguage/Oxytocin.x3d")

head1.addMeta(meta17)
meta18 = x3d.meta()
meta18.setName("license")
meta18.setContent("../license.html")

head1.addMeta(meta18)

X3D0.setHead(head1)
Scene19 = x3d.Scene()
ProtoDeclare20 = x3d.ProtoDeclare()
ProtoDeclare20.setName("Carbon")
ProtoInterface21 = x3d.ProtoInterface()
field22 = x3d.field()
field22.setName("position")
field22.setAccessType("inputOutput")
field22.setType("SFVec3f")
field22.setValue("0 0 0")

ProtoInterface21.addField(field22)
field23 = x3d.field()
field23.setName("materialTransparency")
field23.setAccessType("inputOutput")
field23.setType("SFFloat")
field23.setValue("0.6")

ProtoInterface21.addField(field23)

ProtoDeclare20.setProtoInterface(ProtoInterface21)
ProtoBody24 = x3d.ProtoBody()
Group25 = x3d.Group()
Transform26 = x3d.Transform()
Transform26.setDEF("atoC")
IS27 = x3d.IS()
connect28 = x3d.connect()
connect28.setNodeField("translation")
connect28.setProtoField("position")

IS27.addConnect(connect28)

Transform26.setIS(IS27)
Shape29 = x3d.Shape()
Appearance30 = x3d.Appearance()
Material31 = x3d.Material()
Material31.setDEF("atoC_mat")
Material31.setDiffuseColor(x3d.doubleToFloat([0,0,0]))
Material31.setShininess(0.8)
Material31.setSpecularColor(x3d.doubleToFloat([0.29,0.3,0.29]))
IS32 = x3d.IS()
connect33 = x3d.connect()
connect33.setNodeField("transparency")
connect33.setProtoField("materialTransparency")

IS32.addConnect(connect33)

Material31.setIS(IS32)

Appearance30.setMaterial(Material31)

Shape29.setAppearance(Appearance30)
Sphere34 = x3d.Sphere()
Sphere34.setRadius(0.77)

Shape29.setGeometry(Sphere34)

Transform26.addChild(Shape29)
Shape35 = x3d.Shape()
Appearance36 = x3d.Appearance()
Material37 = x3d.Material()
Material37.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance36.setMaterial(Material37)

Shape35.setAppearance(Appearance36)
Text38 = x3d.Text()
Text38.setString(["C"])
FontStyle39 = x3d.FontStyle()
FontStyle39.setSize(0.8)

Text38.setFontStyle(FontStyle39)

Shape35.setGeometry(Text38)

Transform26.addChild(Shape35)

Group25.addChild(Transform26)

ProtoBody24.addChild(Group25)

ProtoDeclare20.setProtoBody(ProtoBody24)

Scene19.addChild(ProtoDeclare20)
ProtoDeclare40 = x3d.ProtoDeclare()
ProtoDeclare40.setName("Hydrogen")
ProtoInterface41 = x3d.ProtoInterface()
field42 = x3d.field()
field42.setName("position")
field42.setAccessType("inputOutput")
field42.setType("SFVec3f")
field42.setValue("0 0 0")

ProtoInterface41.addField(field42)
field43 = x3d.field()
field43.setName("materialTransparency")
field43.setAccessType("inputOutput")
field43.setType("SFFloat")
field43.setValue("0.6")

ProtoInterface41.addField(field43)

ProtoDeclare40.setProtoInterface(ProtoInterface41)
ProtoBody44 = x3d.ProtoBody()
Group45 = x3d.Group()
Transform46 = x3d.Transform()
Transform46.setDEF("atoH")
IS47 = x3d.IS()
connect48 = x3d.connect()
connect48.setNodeField("translation")
connect48.setProtoField("position")

IS47.addConnect(connect48)

Transform46.setIS(IS47)
Shape49 = x3d.Shape()
Appearance50 = x3d.Appearance()
Material51 = x3d.Material()
Material51.setDEF("atoH_mat")
Material51.setAmbientIntensity(0.0933)
Material51.setDiffuseColor(x3d.doubleToFloat([0.38,0.38,0.42]))
Material51.setShininess(0.5)
Material51.setSpecularColor(x3d.doubleToFloat([0.53,0.53,0.53]))
IS52 = x3d.IS()
connect53 = x3d.connect()
connect53.setNodeField("transparency")
connect53.setProtoField("materialTransparency")

IS52.addConnect(connect53)

Material51.setIS(IS52)

Appearance50.setMaterial(Material51)

Shape49.setAppearance(Appearance50)
Sphere54 = x3d.Sphere()
Sphere54.setRadius(0.32)

Shape49.setGeometry(Sphere54)

Transform46.addChild(Shape49)
Shape55 = x3d.Shape()
Appearance56 = x3d.Appearance()
Material57 = x3d.Material()
Material57.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance56.setMaterial(Material57)

Shape55.setAppearance(Appearance56)
Text58 = x3d.Text()
Text58.setString(["H"])
FontStyle59 = x3d.FontStyle()
FontStyle59.setSize(0.4)

Text58.setFontStyle(FontStyle59)

Shape55.setGeometry(Text58)

Transform46.addChild(Shape55)

Group45.addChild(Transform46)

ProtoBody44.addChild(Group45)

ProtoDeclare40.setProtoBody(ProtoBody44)

Scene19.addChild(ProtoDeclare40)
ProtoDeclare60 = x3d.ProtoDeclare()
ProtoDeclare60.setName("Nitrogen")
ProtoInterface61 = x3d.ProtoInterface()
field62 = x3d.field()
field62.setName("position")
field62.setAccessType("inputOutput")
field62.setType("SFVec3f")
field62.setValue("0 0 0")

ProtoInterface61.addField(field62)
field63 = x3d.field()
field63.setName("materialTransparency")
field63.setAccessType("inputOutput")
field63.setType("SFFloat")
field63.setValue("0.6")

ProtoInterface61.addField(field63)

ProtoDeclare60.setProtoInterface(ProtoInterface61)
ProtoBody64 = x3d.ProtoBody()
Group65 = x3d.Group()
Transform66 = x3d.Transform()
Transform66.setDEF("atoN")
IS67 = x3d.IS()
connect68 = x3d.connect()
connect68.setNodeField("translation")
connect68.setProtoField("position")

IS67.addConnect(connect68)

Transform66.setIS(IS67)
Shape69 = x3d.Shape()
Appearance70 = x3d.Appearance()
Material71 = x3d.Material()
Material71.setDEF("atoN_mat")
Material71.setDiffuseColor(x3d.doubleToFloat([0,0,0.72]))
Material71.setEmissiveColor(x3d.doubleToFloat([0,0,0.13]))
Material71.setSpecularColor(x3d.doubleToFloat([0.5,0.5,0.5]))
IS72 = x3d.IS()
connect73 = x3d.connect()
connect73.setNodeField("transparency")
connect73.setProtoField("materialTransparency")

IS72.addConnect(connect73)

Material71.setIS(IS72)

Appearance70.setMaterial(Material71)

Shape69.setAppearance(Appearance70)
Sphere74 = x3d.Sphere()
Sphere74.setRadius(0.75)

Shape69.setGeometry(Sphere74)

Transform66.addChild(Shape69)
Shape75 = x3d.Shape()
Appearance76 = x3d.Appearance()
Material77 = x3d.Material()
Material77.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance76.setMaterial(Material77)

Shape75.setAppearance(Appearance76)
Text78 = x3d.Text()
Text78.setString(["N"])
FontStyle79 = x3d.FontStyle()
FontStyle79.setSize(0.8)

Text78.setFontStyle(FontStyle79)

Shape75.setGeometry(Text78)

Transform66.addChild(Shape75)

Group65.addChild(Transform66)

ProtoBody64.addChild(Group65)

ProtoDeclare60.setProtoBody(ProtoBody64)

Scene19.addChild(ProtoDeclare60)
ProtoDeclare80 = x3d.ProtoDeclare()
ProtoDeclare80.setName("Oxygen")
ProtoInterface81 = x3d.ProtoInterface()
field82 = x3d.field()
field82.setName("position")
field82.setAccessType("inputOutput")
field82.setType("SFVec3f")
field82.setValue("0 0 0")

ProtoInterface81.addField(field82)
field83 = x3d.field()
field83.setName("materialTransparency")
field83.setAccessType("inputOutput")
field83.setType("SFFloat")
field83.setValue("0.6")

ProtoInterface81.addField(field83)

ProtoDeclare80.setProtoInterface(ProtoInterface81)
ProtoBody84 = x3d.ProtoBody()
Group85 = x3d.Group()
Transform86 = x3d.Transform()
Transform86.setDEF("atoO")
IS87 = x3d.IS()
connect88 = x3d.connect()
connect88.setNodeField("translation")
connect88.setProtoField("position")

IS87.addConnect(connect88)

Transform86.setIS(IS87)
Shape89 = x3d.Shape()
Appearance90 = x3d.Appearance()
Material91 = x3d.Material()
Material91.setDEF("atoO_mat")
Material91.setAmbientIntensity(0.487)
Material91.setDiffuseColor(x3d.doubleToFloat([0.54,0.05,0.25]))
Material91.setShininess(0.2)
Material91.setSpecularColor(x3d.doubleToFloat([0.81,0.77,0.75]))
IS92 = x3d.IS()
connect93 = x3d.connect()
connect93.setNodeField("transparency")
connect93.setProtoField("materialTransparency")

IS92.addConnect(connect93)

Material91.setIS(IS92)

Appearance90.setMaterial(Material91)

Shape89.setAppearance(Appearance90)
Sphere94 = x3d.Sphere()
Sphere94.setRadius(0.73)

Shape89.setGeometry(Sphere94)

Transform86.addChild(Shape89)
Shape95 = x3d.Shape()
Appearance96 = x3d.Appearance()
Material97 = x3d.Material()
Material97.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance96.setMaterial(Material97)

Shape95.setAppearance(Appearance96)
Text98 = x3d.Text()
Text98.setString(["O"])
FontStyle99 = x3d.FontStyle()
FontStyle99.setSize(0.8)

Text98.setFontStyle(FontStyle99)

Shape95.setGeometry(Text98)

Transform86.addChild(Shape95)

Group85.addChild(Transform86)

ProtoBody84.addChild(Group85)

ProtoDeclare80.setProtoBody(ProtoBody84)

Scene19.addChild(ProtoDeclare80)
ProtoDeclare100 = x3d.ProtoDeclare()
ProtoDeclare100.setName("Fluorine")
ProtoInterface101 = x3d.ProtoInterface()
field102 = x3d.field()
field102.setName("position")
field102.setAccessType("inputOutput")
field102.setType("SFVec3f")
field102.setValue("0 0 0")

ProtoInterface101.addField(field102)
field103 = x3d.field()
field103.setName("materialTransparency")
field103.setAccessType("inputOutput")
field103.setType("SFFloat")
field103.setValue("0.6")

ProtoInterface101.addField(field103)

ProtoDeclare100.setProtoInterface(ProtoInterface101)
ProtoBody104 = x3d.ProtoBody()
Group105 = x3d.Group()
Transform106 = x3d.Transform()
Transform106.setDEF("atoF")
IS107 = x3d.IS()
connect108 = x3d.connect()
connect108.setNodeField("translation")
connect108.setProtoField("position")

IS107.addConnect(connect108)

Transform106.setIS(IS107)
Shape109 = x3d.Shape()
Appearance110 = x3d.Appearance()
Material111 = x3d.Material()
Material111.setDEF("atoF_mat")
Material111.setDiffuseColor(x3d.doubleToFloat([1,0.48,0.79]))
Material111.setEmissiveColor(x3d.doubleToFloat([0.09,0.04,0.07]))
IS112 = x3d.IS()
connect113 = x3d.connect()
connect113.setNodeField("transparency")
connect113.setProtoField("materialTransparency")

IS112.addConnect(connect113)

Material111.setIS(IS112)

Appearance110.setMaterial(Material111)

Shape109.setAppearance(Appearance110)
Sphere114 = x3d.Sphere()
Sphere114.setRadius(0.72)

Shape109.setGeometry(Sphere114)

Transform106.addChild(Shape109)
Shape115 = x3d.Shape()
Appearance116 = x3d.Appearance()
Material117 = x3d.Material()
Material117.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance116.setMaterial(Material117)

Shape115.setAppearance(Appearance116)
Text118 = x3d.Text()
Text118.setString(["F"])
FontStyle119 = x3d.FontStyle()
FontStyle119.setSize(0.8)

Text118.setFontStyle(FontStyle119)

Shape115.setGeometry(Text118)

Transform106.addChild(Shape115)

Group105.addChild(Transform106)

ProtoBody104.addChild(Group105)

ProtoDeclare100.setProtoBody(ProtoBody104)

Scene19.addChild(ProtoDeclare100)
ProtoDeclare120 = x3d.ProtoDeclare()
ProtoDeclare120.setName("Silicon")
ProtoInterface121 = x3d.ProtoInterface()
field122 = x3d.field()
field122.setName("position")
field122.setAccessType("inputOutput")
field122.setType("SFVec3f")
field122.setValue("0 0 0")

ProtoInterface121.addField(field122)
field123 = x3d.field()
field123.setName("materialTransparency")
field123.setAccessType("inputOutput")
field123.setType("SFFloat")
field123.setValue("0.6")

ProtoInterface121.addField(field123)

ProtoDeclare120.setProtoInterface(ProtoInterface121)
ProtoBody124 = x3d.ProtoBody()
Group125 = x3d.Group()
Transform126 = x3d.Transform()
Transform126.setDEF("atoSi")
IS127 = x3d.IS()
connect128 = x3d.connect()
connect128.setNodeField("translation")
connect128.setProtoField("position")

IS127.addConnect(connect128)

Transform126.setIS(IS127)
Shape129 = x3d.Shape()
Appearance130 = x3d.Appearance()
Material131 = x3d.Material()
Material131.setDEF("atoSi_mat")
Material131.setDiffuseColor(x3d.doubleToFloat([0.8,0.8,0.8]))
IS132 = x3d.IS()
connect133 = x3d.connect()
connect133.setNodeField("transparency")
connect133.setProtoField("materialTransparency")

IS132.addConnect(connect133)

Material131.setIS(IS132)

Appearance130.setMaterial(Material131)

Shape129.setAppearance(Appearance130)
Sphere134 = x3d.Sphere()
Sphere134.setRadius(1.18)

Shape129.setGeometry(Sphere134)

Transform126.addChild(Shape129)
Shape135 = x3d.Shape()
Appearance136 = x3d.Appearance()
Material137 = x3d.Material()
Material137.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance136.setMaterial(Material137)

Shape135.setAppearance(Appearance136)
Text138 = x3d.Text()
Text138.setString(["Si"])
FontStyle139 = x3d.FontStyle()
FontStyle139.setSize(0.8)

Text138.setFontStyle(FontStyle139)

Shape135.setGeometry(Text138)

Transform126.addChild(Shape135)

Group125.addChild(Transform126)

ProtoBody124.addChild(Group125)

ProtoDeclare120.setProtoBody(ProtoBody124)

Scene19.addChild(ProtoDeclare120)
ProtoDeclare140 = x3d.ProtoDeclare()
ProtoDeclare140.setName("Phosphorus")
ProtoInterface141 = x3d.ProtoInterface()
field142 = x3d.field()
field142.setName("position")
field142.setAccessType("inputOutput")
field142.setType("SFVec3f")
field142.setValue("0 0 0")

ProtoInterface141.addField(field142)
field143 = x3d.field()
field143.setName("materialTransparency")
field143.setAccessType("inputOutput")
field143.setType("SFFloat")
field143.setValue("0.6")

ProtoInterface141.addField(field143)

ProtoDeclare140.setProtoInterface(ProtoInterface141)
ProtoBody144 = x3d.ProtoBody()
Group145 = x3d.Group()
Transform146 = x3d.Transform()
Transform146.setDEF("atoP")
IS147 = x3d.IS()
connect148 = x3d.connect()
connect148.setNodeField("translation")
connect148.setProtoField("position")

IS147.addConnect(connect148)

Transform146.setIS(IS147)
Shape149 = x3d.Shape()
Appearance150 = x3d.Appearance()
Material151 = x3d.Material()
Material151.setDEF("atoP_mat")
Material151.setAmbientIntensity(0.11)
Material151.setDiffuseColor(x3d.doubleToFloat([0.9,0.41,0]))
Material151.setEmissiveColor(x3d.doubleToFloat([0.1,0.04,0]))
Material151.setShininess(0.8)
Material151.setSpecularColor(x3d.doubleToFloat([0.1,0.1,0.1]))
IS152 = x3d.IS()
connect153 = x3d.connect()
connect153.setNodeField("transparency")
connect153.setProtoField("materialTransparency")

IS152.addConnect(connect153)

Material151.setIS(IS152)

Appearance150.setMaterial(Material151)

Shape149.setAppearance(Appearance150)
Sphere154 = x3d.Sphere()
Sphere154.setRadius(1.1)

Shape149.setGeometry(Sphere154)

Transform146.addChild(Shape149)
Shape155 = x3d.Shape()
Appearance156 = x3d.Appearance()
Material157 = x3d.Material()
Material157.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance156.setMaterial(Material157)

Shape155.setAppearance(Appearance156)
Text158 = x3d.Text()
Text158.setString(["P"])
FontStyle159 = x3d.FontStyle()
FontStyle159.setSize(0.8)

Text158.setFontStyle(FontStyle159)

Shape155.setGeometry(Text158)

Transform146.addChild(Shape155)

Group145.addChild(Transform146)

ProtoBody144.addChild(Group145)

ProtoDeclare140.setProtoBody(ProtoBody144)

Scene19.addChild(ProtoDeclare140)
ProtoDeclare160 = x3d.ProtoDeclare()
ProtoDeclare160.setName("Sulphur")
ProtoInterface161 = x3d.ProtoInterface()
field162 = x3d.field()
field162.setName("position")
field162.setAccessType("inputOutput")
field162.setType("SFVec3f")
field162.setValue("0 0 0")

ProtoInterface161.addField(field162)
field163 = x3d.field()
field163.setName("materialTransparency")
field163.setAccessType("inputOutput")
field163.setType("SFFloat")
field163.setValue("0.6")

ProtoInterface161.addField(field163)

ProtoDeclare160.setProtoInterface(ProtoInterface161)
ProtoBody164 = x3d.ProtoBody()
Group165 = x3d.Group()
Transform166 = x3d.Transform()
Transform166.setDEF("atoS")
IS167 = x3d.IS()
connect168 = x3d.connect()
connect168.setNodeField("translation")
connect168.setProtoField("position")

IS167.addConnect(connect168)

Transform166.setIS(IS167)
Shape169 = x3d.Shape()
Appearance170 = x3d.Appearance()
Material171 = x3d.Material()
Material171.setDEF("atoS_mat")
Material171.setAmbientIntensity(0.0467)
Material171.setDiffuseColor(x3d.doubleToFloat([0.25,0.39,0.25]))
Material171.setEmissiveColor(x3d.doubleToFloat([0.05,0.08,0.05]))
Material171.setShininess(0.6)
Material171.setSpecularColor(x3d.doubleToFloat([0.11,0.12,0.08]))
IS172 = x3d.IS()
connect173 = x3d.connect()
connect173.setNodeField("transparency")
connect173.setProtoField("materialTransparency")

IS172.addConnect(connect173)

Material171.setIS(IS172)

Appearance170.setMaterial(Material171)

Shape169.setAppearance(Appearance170)
Sphere174 = x3d.Sphere()
Sphere174.setRadius(1.3)

Shape169.setGeometry(Sphere174)

Transform166.addChild(Shape169)
Shape175 = x3d.Shape()
Appearance176 = x3d.Appearance()
Material177 = x3d.Material()
Material177.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance176.setMaterial(Material177)

Shape175.setAppearance(Appearance176)
Text178 = x3d.Text()
Text178.setString(["S"])
FontStyle179 = x3d.FontStyle()
FontStyle179.setSize(0.8)

Text178.setFontStyle(FontStyle179)

Shape175.setGeometry(Text178)

Transform166.addChild(Shape175)

Group165.addChild(Transform166)

ProtoBody164.addChild(Group165)

ProtoDeclare160.setProtoBody(ProtoBody164)

Scene19.addChild(ProtoDeclare160)
ProtoDeclare180 = x3d.ProtoDeclare()
ProtoDeclare180.setName("Chlorine")
ProtoInterface181 = x3d.ProtoInterface()
field182 = x3d.field()
field182.setName("position")
field182.setAccessType("inputOutput")
field182.setType("SFVec3f")
field182.setValue("0 0 0")

ProtoInterface181.addField(field182)
field183 = x3d.field()
field183.setName("materialTransparency")
field183.setAccessType("inputOutput")
field183.setType("SFFloat")
field183.setValue("0.6")

ProtoInterface181.addField(field183)

ProtoDeclare180.setProtoInterface(ProtoInterface181)
ProtoBody184 = x3d.ProtoBody()
Group185 = x3d.Group()
Transform186 = x3d.Transform()
Transform186.setDEF("atoCl")
IS187 = x3d.IS()
connect188 = x3d.connect()
connect188.setNodeField("translation")
connect188.setProtoField("position")

IS187.addConnect(connect188)

Transform186.setIS(IS187)
Shape189 = x3d.Shape()
Appearance190 = x3d.Appearance()
Material191 = x3d.Material()
Material191.setDEF("atoCl_mat")
Material191.setDiffuseColor(x3d.doubleToFloat([0.28,0.7,0]))
Material191.setEmissiveColor(x3d.doubleToFloat([0.06,0.15,0]))
Material191.setShininess(0.8)
Material191.setSpecularColor(x3d.doubleToFloat([0.5,0.5,0.5]))
IS192 = x3d.IS()
connect193 = x3d.connect()
connect193.setNodeField("transparency")
connect193.setProtoField("materialTransparency")

IS192.addConnect(connect193)

Material191.setIS(IS192)

Appearance190.setMaterial(Material191)

Shape189.setAppearance(Appearance190)
Sphere194 = x3d.Sphere()
Sphere194.setRadius(1.01)

Shape189.setGeometry(Sphere194)

Transform186.addChild(Shape189)
Shape195 = x3d.Shape()
Appearance196 = x3d.Appearance()
Material197 = x3d.Material()
Material197.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance196.setMaterial(Material197)

Shape195.setAppearance(Appearance196)
Text198 = x3d.Text()
Text198.setString(["Cl"])
FontStyle199 = x3d.FontStyle()
FontStyle199.setSize(0.8)

Text198.setFontStyle(FontStyle199)

Shape195.setGeometry(Text198)

Transform186.addChild(Shape195)

Group185.addChild(Transform186)

ProtoBody184.addChild(Group185)

ProtoDeclare180.setProtoBody(ProtoBody184)

Scene19.addChild(ProtoDeclare180)
ProtoDeclare200 = x3d.ProtoDeclare()
ProtoDeclare200.setName("Bromine")
ProtoInterface201 = x3d.ProtoInterface()
field202 = x3d.field()
field202.setName("position")
field202.setAccessType("inputOutput")
field202.setType("SFVec3f")
field202.setValue("0 0 0")

ProtoInterface201.addField(field202)
field203 = x3d.field()
field203.setName("materialTransparency")
field203.setAccessType("inputOutput")
field203.setType("SFFloat")
field203.setValue("0.6")

ProtoInterface201.addField(field203)

ProtoDeclare200.setProtoInterface(ProtoInterface201)
ProtoBody204 = x3d.ProtoBody()
Group205 = x3d.Group()
Transform206 = x3d.Transform()
Transform206.setDEF("atoBr")
IS207 = x3d.IS()
connect208 = x3d.connect()
connect208.setNodeField("translation")
connect208.setProtoField("position")

IS207.addConnect(connect208)

Transform206.setIS(IS207)
Shape209 = x3d.Shape()
Appearance210 = x3d.Appearance()
Material211 = x3d.Material()
Material211.setDEF("atoBr_mat")
Material211.setAmbientIntensity(0.0833)
Material211.setDiffuseColor(x3d.doubleToFloat([0.5,0.3,0.19]))
Material211.setEmissiveColor(x3d.doubleToFloat([0.12,0.13,0.08]))
Material211.setShininess(0.17)
Material211.setSpecularColor(x3d.doubleToFloat([0.08,0.08,0.05]))
IS212 = x3d.IS()
connect213 = x3d.connect()
connect213.setNodeField("transparency")
connect213.setProtoField("materialTransparency")

IS212.addConnect(connect213)

Material211.setIS(IS212)

Appearance210.setMaterial(Material211)

Shape209.setAppearance(Appearance210)
Sphere214 = x3d.Sphere()
Sphere214.setRadius(1.14)

Shape209.setGeometry(Sphere214)

Transform206.addChild(Shape209)
Shape215 = x3d.Shape()
Appearance216 = x3d.Appearance()
Material217 = x3d.Material()
Material217.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance216.setMaterial(Material217)

Shape215.setAppearance(Appearance216)
Text218 = x3d.Text()
Text218.setString(["Br"])
FontStyle219 = x3d.FontStyle()
FontStyle219.setSize(0.8)

Text218.setFontStyle(FontStyle219)

Shape215.setGeometry(Text218)

Transform206.addChild(Shape215)

Group205.addChild(Transform206)

ProtoBody204.addChild(Group205)

ProtoDeclare200.setProtoBody(ProtoBody204)

Scene19.addChild(ProtoDeclare200)
ProtoDeclare220 = x3d.ProtoDeclare()
ProtoDeclare220.setName("Iodine")
ProtoInterface221 = x3d.ProtoInterface()
field222 = x3d.field()
field222.setName("position")
field222.setAccessType("inputOutput")
field222.setType("SFVec3f")
field222.setValue("0 0 0")

ProtoInterface221.addField(field222)
field223 = x3d.field()
field223.setName("materialTransparency")
field223.setAccessType("inputOutput")
field223.setType("SFFloat")
field223.setValue("0.6")

ProtoInterface221.addField(field223)

ProtoDeclare220.setProtoInterface(ProtoInterface221)
ProtoBody224 = x3d.ProtoBody()
Group225 = x3d.Group()
Transform226 = x3d.Transform()
Transform226.setDEF("atoI")
IS227 = x3d.IS()
connect228 = x3d.connect()
connect228.setNodeField("translation")
connect228.setProtoField("position")

IS227.addConnect(connect228)

Transform226.setIS(IS227)
Shape229 = x3d.Shape()
Appearance230 = x3d.Appearance()
Material231 = x3d.Material()
Material231.setDEF("atoI_mat")
Material231.setDiffuseColor(x3d.doubleToFloat([0.56,0.37,0.74]))
Material231.setEmissiveColor(x3d.doubleToFloat([0.15,0.1,0.2]))
Material231.setShininess(0.09)
Material231.setSpecularColor(x3d.doubleToFloat([0.12,0.12,0.12]))
IS232 = x3d.IS()
connect233 = x3d.connect()
connect233.setNodeField("transparency")
connect233.setProtoField("materialTransparency")

IS232.addConnect(connect233)

Material231.setIS(IS232)

Appearance230.setMaterial(Material231)

Shape229.setAppearance(Appearance230)
Sphere234 = x3d.Sphere()
Sphere234.setRadius(1.33)

Shape229.setGeometry(Sphere234)

Transform226.addChild(Shape229)
Shape235 = x3d.Shape()
Appearance236 = x3d.Appearance()
Material237 = x3d.Material()
Material237.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance236.setMaterial(Material237)

Shape235.setAppearance(Appearance236)
Text238 = x3d.Text()
Text238.setString(["I"])
FontStyle239 = x3d.FontStyle()
FontStyle239.setSize(0.8)

Text238.setFontStyle(FontStyle239)

Shape235.setGeometry(Text238)

Transform226.addChild(Shape235)

Group225.addChild(Transform226)

ProtoBody224.addChild(Group225)

ProtoDeclare220.setProtoBody(ProtoBody224)

Scene19.addChild(ProtoDeclare220)
ProtoDeclare240 = x3d.ProtoDeclare()
ProtoDeclare240.setName("unknown")
ProtoInterface241 = x3d.ProtoInterface()
field242 = x3d.field()
field242.setName("position")
field242.setAccessType("inputOutput")
field242.setType("SFVec3f")
field242.setValue("0 0 0")

ProtoInterface241.addField(field242)
field243 = x3d.field()
field243.setName("materialTransparency")
field243.setAccessType("inputOutput")
field243.setType("SFFloat")
field243.setValue("0.6")

ProtoInterface241.addField(field243)

ProtoDeclare240.setProtoInterface(ProtoInterface241)
ProtoBody244 = x3d.ProtoBody()
Group245 = x3d.Group()
Transform246 = x3d.Transform()
Transform246.setDEF("ato_")
IS247 = x3d.IS()
connect248 = x3d.connect()
connect248.setNodeField("translation")
connect248.setProtoField("position")

IS247.addConnect(connect248)

Transform246.setIS(IS247)
Shape249 = x3d.Shape()
Appearance250 = x3d.Appearance()
Material251 = x3d.Material()
Material251.setDEF("ato__mat")
Material251.setDiffuseColor(x3d.doubleToFloat([1,1,1]))
Material251.setEmissiveColor(x3d.doubleToFloat([0.15,0.1,0.2]))
Material251.setShininess(0.09)
Material251.setSpecularColor(x3d.doubleToFloat([0.12,0.12,0.12]))
IS252 = x3d.IS()
connect253 = x3d.connect()
connect253.setNodeField("transparency")
connect253.setProtoField("materialTransparency")

IS252.addConnect(connect253)

Material251.setIS(IS252)

Appearance250.setMaterial(Material251)

Shape249.setAppearance(Appearance250)
Sphere254 = x3d.Sphere()
Sphere254.setRadius(1.001)

Shape249.setGeometry(Sphere254)

Transform246.addChild(Shape249)
Shape255 = x3d.Shape()
Appearance256 = x3d.Appearance()
Material257 = x3d.Material()
Material257.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance256.setMaterial(Material257)

Shape255.setAppearance(Appearance256)
Text258 = x3d.Text()
Text258.setString(["?"])
FontStyle259 = x3d.FontStyle()
FontStyle259.setSize(0.8)

Text258.setFontStyle(FontStyle259)

Shape255.setGeometry(Text258)

Transform246.addChild(Shape255)

Group245.addChild(Transform246)

ProtoBody244.addChild(Group245)

ProtoDeclare240.setProtoBody(ProtoBody244)

Scene19.addChild(ProtoDeclare240)
ProtoDeclare260 = x3d.ProtoDeclare()
ProtoDeclare260.setName("line")
ProtoInterface261 = x3d.ProtoInterface()
field262 = x3d.field()
field262.setName("bond_set")
field262.setAccessType("inputOutput")
field262.setType("MFVec3f")
field262.setValue("-1 0 0 1 0 0")

ProtoInterface261.addField(field262)

ProtoDeclare260.setProtoInterface(ProtoInterface261)
ProtoBody263 = x3d.ProtoBody()
Group264 = x3d.Group()
Shape265 = x3d.Shape()
Appearance266 = x3d.Appearance()
Material267 = x3d.Material()
Material267.setDiffuseColor(x3d.doubleToFloat([1,1,1]))
Material267.setEmissiveColor(x3d.doubleToFloat([1,1,1]))

Appearance266.setMaterial(Material267)

Shape265.setAppearance(Appearance266)
IndexedLineSet268 = x3d.IndexedLineSet()
IndexedLineSet268.setCoordIndex([0,1,-1])
Coordinate269 = x3d.Coordinate()
Coordinate269.setDEF("bondo")
IS270 = x3d.IS()
connect271 = x3d.connect()
connect271.setNodeField("point")
connect271.setProtoField("bond_set")

IS270.addConnect(connect271)

Coordinate269.setIS(IS270)

IndexedLineSet268.setCoord(Coordinate269)

Shape265.setGeometry(IndexedLineSet268)

Group264.addChild(Shape265)

ProtoBody263.addChild(Group264)

ProtoDeclare260.setProtoBody(ProtoBody263)

Scene19.addChild(ProtoDeclare260)
ProtoDeclare272 = x3d.ProtoDeclare()
ProtoDeclare272.setName("title_text")
ProtoInterface273 = x3d.ProtoInterface()
field274 = x3d.field()
field274.setName("txt")
field274.setAccessType("inputOutput")
field274.setType("MFString")

ProtoInterface273.addField(field274)

ProtoDeclare272.setProtoInterface(ProtoInterface273)
ProtoBody275 = x3d.ProtoBody()
Transform276 = x3d.Transform()
Group277 = x3d.Group()
Transform278 = x3d.Transform()
Shape279 = x3d.Shape()
Appearance280 = x3d.Appearance()
Material281 = x3d.Material()
Material281.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance280.setMaterial(Material281)

Shape279.setAppearance(Appearance280)
Text282 = x3d.Text()
Text282.setDEF("cmpd_name")
IS283 = x3d.IS()
connect284 = x3d.connect()
connect284.setNodeField("string")
connect284.setProtoField("txt")

IS283.addConnect(connect284)

Text282.setIS(IS283)
FontStyle285 = x3d.FontStyle()

Text282.setFontStyle(FontStyle285)

Shape279.setGeometry(Text282)

Transform278.addChild(Shape279)

Group277.addChild(Transform278)

Transform276.addChild(Group277)

ProtoBody275.addChild(Transform276)

ProtoDeclare272.setProtoBody(ProtoBody275)

Scene19.addChild(ProtoDeclare272)
ProtoDeclare286 = x3d.ProtoDeclare()
ProtoDeclare286.setName("ano1_text")
ProtoInterface287 = x3d.ProtoInterface()
field288 = x3d.field()
field288.setName("txt")
field288.setAccessType("inputOutput")
field288.setType("MFString")

ProtoInterface287.addField(field288)

ProtoDeclare286.setProtoInterface(ProtoInterface287)
ProtoBody289 = x3d.ProtoBody()
Transform290 = x3d.Transform()
Group291 = x3d.Group()
Transform292 = x3d.Transform()
Shape293 = x3d.Shape()
Appearance294 = x3d.Appearance()
Material295 = x3d.Material()
Material295.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance294.setMaterial(Material295)

Shape293.setAppearance(Appearance294)
Text296 = x3d.Text()
Text296.setDEF("cmpd_name1")
IS297 = x3d.IS()
connect298 = x3d.connect()
connect298.setNodeField("string")
connect298.setProtoField("txt")

IS297.addConnect(connect298)

Text296.setIS(IS297)
FontStyle299 = x3d.FontStyle()
FontStyle299.setSize(0.8)

Text296.setFontStyle(FontStyle299)

Shape293.setGeometry(Text296)

Transform292.addChild(Shape293)

Group291.addChild(Transform292)

Transform290.addChild(Group291)

ProtoBody289.addChild(Transform290)

ProtoDeclare286.setProtoBody(ProtoBody289)

Scene19.addChild(ProtoDeclare286)
ProtoDeclare300 = x3d.ProtoDeclare()
ProtoDeclare300.setName("ano2_text")
ProtoInterface301 = x3d.ProtoInterface()
field302 = x3d.field()
field302.setName("txt")
field302.setAccessType("inputOutput")
field302.setType("MFString")

ProtoInterface301.addField(field302)

ProtoDeclare300.setProtoInterface(ProtoInterface301)
ProtoBody303 = x3d.ProtoBody()
Transform304 = x3d.Transform()
Group305 = x3d.Group()
Transform306 = x3d.Transform()
Shape307 = x3d.Shape()
Appearance308 = x3d.Appearance()
Material309 = x3d.Material()
Material309.setDiffuseColor(x3d.doubleToFloat([0.9,0.9,0.9]))

Appearance308.setMaterial(Material309)

Shape307.setAppearance(Appearance308)
Text310 = x3d.Text()
Text310.setDEF("cmpd_name2")
IS311 = x3d.IS()
connect312 = x3d.connect()
connect312.setNodeField("string")
connect312.setProtoField("txt")

IS311.addConnect(connect312)

Text310.setIS(IS311)
FontStyle313 = x3d.FontStyle()
FontStyle313.setSize(0.6)

Text310.setFontStyle(FontStyle313)

Shape307.setGeometry(Text310)

Transform306.addChild(Shape307)

Group305.addChild(Transform306)

Transform304.addChild(Group305)

ProtoBody303.addChild(Transform304)

ProtoDeclare300.setProtoBody(ProtoBody303)

Scene19.addChild(ProtoDeclare300)
Background314 = x3d.Background()
Background314.setGroundAngle(x3d.doubleToFloat([1.309,1.570796]))
Background314.setGroundColor(x3d.doubleToFloat([0,0.5,0.7,0,0.4,0.7,0.6,0.5,0.7]))
Background314.setSkyAngle(x3d.doubleToFloat([1.309,1.570796]))
Background314.setSkyColor(x3d.doubleToFloat([0,0.5,0.8,0,0.6,0.7,0.6,0.6,0.7]))

Scene19.addChild(Background314)
PointLight315 = x3d.PointLight()
PointLight315.setAmbientIntensity(1)
PointLight315.setLocation(x3d.doubleToFloat([0,0,5]))
PointLight315.setRadius(30)

Scene19.addChild(PointLight315)
NavigationInfo316 = x3d.NavigationInfo()
NavigationInfo316.setType(["EXAMINE","FLY","ANY"])

Scene19.addChild(NavigationInfo316)
Viewpoint317 = x3d.Viewpoint()
Viewpoint317.setDescription("Inspect Oxytocin")
Viewpoint317.setPosition(x3d.doubleToFloat([0,2,20]))

Scene19.addChild(Viewpoint317)

Scene19.addComments(x3d.CommentsBlock("""Copyright by the U.S. Sec. Commerce on behalf of U.S.A. All rights reserved."""))

Scene19.addComments(x3d.CommentsBlock("""type=\"3D\" <date day=\"23\" month=\"11\" year=\"1995\"/>"""))
Transform318 = x3d.Transform()
Transform318.setDEF("infogroupa")
Transform318.setTranslation(x3d.doubleToFloat([-8,2,-4]))
Transform319 = x3d.Transform()
Transform319.setTranslation(x3d.doubleToFloat([0,6,0]))
Viewpoint320 = x3d.Viewpoint()
Viewpoint320.setDescription("title billboard")
Viewpoint320.setPosition(x3d.doubleToFloat([6,-2,10]))

Transform319.addChild(Viewpoint320)
ProtoInstance321 = x3d.ProtoInstance()
ProtoInstance321.setName("title_text")
fieldValue322 = x3d.fieldValue()
fieldValue322.setName("txt")
fieldValue322.setValue("\"Oxytocin: \"")

ProtoInstance321.addFieldValue(fieldValue322)

Transform319.addChild(ProtoInstance321)

Transform318.addChild(Transform319)

Scene19.addChild(Transform318)
Group323 = x3d.Group()
Transform324 = x3d.Transform()
ProtoInstance325 = x3d.ProtoInstance()
ProtoInstance325.setName("Nitrogen")
ProtoInstance325.setDEF("a1")
fieldValue326 = x3d.fieldValue()
fieldValue326.setName("position")
fieldValue326.setValue("-2.0514 1.8507 0")

ProtoInstance325.addFieldValue(fieldValue326)

Transform324.addChild(ProtoInstance325)

Group323.addChild(Transform324)
Transform327 = x3d.Transform()
ProtoInstance328 = x3d.ProtoInstance()
ProtoInstance328.setName("Carbon")
ProtoInstance328.setDEF("a2")
fieldValue329 = x3d.fieldValue()
fieldValue329.setName("position")
fieldValue329.setValue("-3.601 1.9845 0")

ProtoInstance328.addFieldValue(fieldValue329)

Transform327.addChild(ProtoInstance328)

Group323.addChild(Transform327)
Transform330 = x3d.Transform()
ProtoInstance331 = x3d.ProtoInstance()
ProtoInstance331.setName("Carbon")
ProtoInstance331.setDEF("a3")
fieldValue332 = x3d.fieldValue()
fieldValue332.setName("position")
fieldValue332.setValue("-1.2821 0.4905 0")

ProtoInstance331.addFieldValue(fieldValue332)

Transform330.addChild(ProtoInstance331)

Group323.addChild(Transform330)
Transform333 = x3d.Transform()
ProtoInstance334 = x3d.ProtoInstance()
ProtoInstance334.setName("Carbon")
ProtoInstance334.setDEF("a4")
fieldValue335 = x3d.fieldValue()
fieldValue335.setName("position")
fieldValue335.setValue("-1.4159 3.2554 0")

ProtoInstance334.addFieldValue(fieldValue335)

Transform333.addChild(ProtoInstance334)

Group323.addChild(Transform333)
Transform336 = x3d.Transform()
ProtoInstance337 = x3d.ProtoInstance()
ProtoInstance337.setName("Carbon")
ProtoInstance337.setDEF("a5")
fieldValue338 = x3d.fieldValue()
fieldValue338.setName("position")
fieldValue338.setValue("-4.649 0.8473 0")

ProtoInstance337.addFieldValue(fieldValue338)

Transform336.addChild(ProtoInstance337)

Group323.addChild(Transform336)
Transform339 = x3d.Transform()
ProtoInstance340 = x3d.ProtoInstance()
ProtoInstance340.setName("Carbon")
ProtoInstance340.setDEF("a6")
fieldValue341 = x3d.fieldValue()
fieldValue341.setName("position")
fieldValue341.setValue("-3.9355 3.5341 0")

ProtoInstance340.addFieldValue(fieldValue341)

Transform339.addChild(ProtoInstance340)

Group323.addChild(Transform339)
Transform342 = x3d.Transform()
ProtoInstance343 = x3d.ProtoInstance()
ProtoInstance343.setName("Carbon")
ProtoInstance343.setDEF("a7")
fieldValue344 = x3d.fieldValue()
fieldValue344.setName("position")
fieldValue344.setValue("0.2341 0.4905 0")

ProtoInstance343.addFieldValue(fieldValue344)

Transform342.addChild(ProtoInstance343)

Group323.addChild(Transform342)
Transform345 = x3d.Transform()
ProtoInstance346 = x3d.ProtoInstance()
ProtoInstance346.setName("Oxygen")
ProtoInstance346.setDEF("a8")
fieldValue347 = x3d.fieldValue()
fieldValue347.setName("position")
fieldValue347.setValue("-2.0514 -0.8362 0")

ProtoInstance346.addFieldValue(fieldValue347)

Transform345.addChild(ProtoInstance346)

Group323.addChild(Transform345)
Transform348 = x3d.Transform()
ProtoInstance349 = x3d.ProtoInstance()
ProtoInstance349.setName("Carbon")
ProtoInstance349.setDEF("a9")
fieldValue350 = x3d.fieldValue()
fieldValue350.setName("position")
fieldValue350.setValue("-2.5753 4.3034 0")

ProtoInstance349.addFieldValue(fieldValue350)

Transform348.addChild(ProtoInstance349)

Group323.addChild(Transform348)
Transform351 = x3d.Transform()
ProtoInstance352 = x3d.ProtoInstance()
ProtoInstance352.setName("Nitrogen")
ProtoInstance352.setDEF("a10")
fieldValue353 = x3d.fieldValue()
fieldValue353.setName("position")
fieldValue353.setValue("-6.1764 1.1595 0")

ProtoInstance352.addFieldValue(fieldValue353)

Transform351.addChild(ProtoInstance352)

Group323.addChild(Transform351)
Transform354 = x3d.Transform()
ProtoInstance355 = x3d.ProtoInstance()
ProtoInstance355.setName("Oxygen")
ProtoInstance355.setDEF("a11")
fieldValue356 = x3d.fieldValue()
fieldValue356.setName("position")
fieldValue356.setValue("-4.1585 -0.6132 0")

ProtoInstance355.addFieldValue(fieldValue356)

Transform354.addChild(ProtoInstance355)

Group323.addChild(Transform354)
Transform357 = x3d.Transform()
ProtoInstance358 = x3d.ProtoInstance()
ProtoInstance358.setName("Nitrogen")
ProtoInstance358.setDEF("a12")
fieldValue359 = x3d.fieldValue()
fieldValue359.setName("position")
fieldValue359.setValue("0.4905 2.0402 0")

ProtoInstance358.addFieldValue(fieldValue359)

Transform357.addChild(ProtoInstance358)

Group323.addChild(Transform357)
Transform360 = x3d.Transform()
ProtoInstance361 = x3d.ProtoInstance()
ProtoInstance361.setName("Carbon")
ProtoInstance361.setDEF("a13")
fieldValue362 = x3d.fieldValue()
fieldValue362.setName("position")
fieldValue362.setValue("0.4905 -1.0257 0")

ProtoInstance361.addFieldValue(fieldValue362)

Transform360.addChild(ProtoInstance361)

Group323.addChild(Transform360)
Transform363 = x3d.Transform()
ProtoInstance364 = x3d.ProtoInstance()
ProtoInstance364.setName("Carbon")
ProtoInstance364.setDEF("a14")
fieldValue365 = x3d.fieldValue()
fieldValue365.setName("position")
fieldValue365.setValue("-7.2243 0.0223 0")

ProtoInstance364.addFieldValue(fieldValue365)

Transform363.addChild(ProtoInstance364)

Group323.addChild(Transform363)
Transform366 = x3d.Transform()
ProtoInstance367 = x3d.ProtoInstance()
ProtoInstance367.setName("Carbon")
ProtoInstance367.setDEF("a15")
fieldValue368 = x3d.fieldValue()
fieldValue368.setName("position")
fieldValue368.setValue("1.2041 3.3892 0")

ProtoInstance367.addFieldValue(fieldValue368)

Transform366.addChild(ProtoInstance367)

Group323.addChild(Transform366)
Transform369 = x3d.Transform()
ProtoInstance370 = x3d.ProtoInstance()
ProtoInstance370.setName("Sulphur")
ProtoInstance370.setDEF("a16")
fieldValue371 = x3d.fieldValue()
fieldValue371.setName("position")
fieldValue371.setValue("1.1706 -2.4081 0")

ProtoInstance370.addFieldValue(fieldValue371)

Transform369.addChild(ProtoInstance370)

Group323.addChild(Transform369)
Transform372 = x3d.Transform()
ProtoInstance373 = x3d.ProtoInstance()
ProtoInstance373.setName("Carbon")
ProtoInstance373.setDEF("a17")
fieldValue374 = x3d.fieldValue()
fieldValue374.setName("position")
fieldValue374.setValue("-8.7071 0.3568 0")

ProtoInstance373.addFieldValue(fieldValue374)

Transform372.addChild(ProtoInstance373)

Group323.addChild(Transform372)
Transform375 = x3d.Transform()
ProtoInstance376 = x3d.ProtoInstance()
ProtoInstance376.setName("Carbon")
ProtoInstance376.setDEF("a18")
fieldValue377 = x3d.fieldValue()
fieldValue377.setName("position")
fieldValue377.setValue("-6.7226 -1.4382 0")

ProtoInstance376.addFieldValue(fieldValue377)

Transform375.addChild(ProtoInstance376)

Group323.addChild(Transform375)
Transform378 = x3d.Transform()
ProtoInstance379 = x3d.ProtoInstance()
ProtoInstance379.setName("Carbon")
ProtoInstance379.setDEF("a19")
fieldValue380 = x3d.fieldValue()
fieldValue380.setName("position")
fieldValue380.setValue("2.3078 4.4929 0")

ProtoInstance379.addFieldValue(fieldValue380)

Transform378.addChild(ProtoInstance379)

Group323.addChild(Transform378)
Transform381 = x3d.Transform()
ProtoInstance382 = x3d.ProtoInstance()
ProtoInstance382.setName("Oxygen")
ProtoInstance382.setDEF("a20")
fieldValue383 = x3d.fieldValue()
fieldValue383.setName("position")
fieldValue383.setValue("-0.0446 4.3368 0")

ProtoInstance382.addFieldValue(fieldValue383)

Transform381.addChild(ProtoInstance382)

Group323.addChild(Transform381)
Transform384 = x3d.Transform()
ProtoInstance385 = x3d.ProtoInstance()
ProtoInstance385.setName("Sulphur")
ProtoInstance385.setDEF("a21")
fieldValue386 = x3d.fieldValue()
fieldValue386.setName("position")
fieldValue386.setValue("2.2855 -3.5118 0")

ProtoInstance385.addFieldValue(fieldValue386)

Transform384.addChild(ProtoInstance385)

Group323.addChild(Transform384)
Transform387 = x3d.Transform()
ProtoInstance388 = x3d.ProtoInstance()
ProtoInstance388.setName("Nitrogen")
ProtoInstance388.setDEF("a22")
fieldValue389 = x3d.fieldValue()
fieldValue389.setName("position")
fieldValue389.setValue("-9.7662 -0.7804 0")

ProtoInstance388.addFieldValue(fieldValue389)

Transform387.addChild(ProtoInstance388)

Group323.addChild(Transform387)
Transform390 = x3d.Transform()
ProtoInstance391 = x3d.ProtoInstance()
ProtoInstance391.setName("Oxygen")
ProtoInstance391.setDEF("a23")
fieldValue392 = x3d.fieldValue()
fieldValue392.setName("position")
fieldValue392.setValue("-9.2088 1.8507 0")

ProtoInstance391.addFieldValue(fieldValue392)

Transform390.addChild(ProtoInstance391)

Group323.addChild(Transform390)
Transform393 = x3d.Transform()
ProtoInstance394 = x3d.ProtoInstance()
ProtoInstance394.setName("Carbon")
ProtoInstance394.setDEF("a24")
fieldValue395 = x3d.fieldValue()
fieldValue395.setName("position")
fieldValue395.setValue("-7.7483 -2.5753 0")

ProtoInstance394.addFieldValue(fieldValue395)

Transform393.addChild(ProtoInstance394)

Group323.addChild(Transform393)
Transform396 = x3d.Transform()
ProtoInstance397 = x3d.ProtoInstance()
ProtoInstance397.setName("Nitrogen")
ProtoInstance397.setDEF("a25")
fieldValue398 = x3d.fieldValue()
fieldValue398.setName("position")
fieldValue398.setValue("3.6902 5.1841 0")

ProtoInstance397.addFieldValue(fieldValue398)

Transform396.addChild(ProtoInstance397)

Group323.addChild(Transform396)
Transform399 = x3d.Transform()
ProtoInstance400 = x3d.ProtoInstance()
ProtoInstance400.setName("Carbon")
ProtoInstance400.setDEF("a26")
fieldValue401 = x3d.fieldValue()
fieldValue401.setName("position")
fieldValue401.setValue("1.3936 5.7416 0")

ProtoInstance400.addFieldValue(fieldValue401)

Transform399.addChild(ProtoInstance400)

Group323.addChild(Transform399)
Transform402 = x3d.Transform()
ProtoInstance403 = x3d.ProtoInstance()
ProtoInstance403.setName("Carbon")
ProtoInstance403.setDEF("a27")
fieldValue404 = x3d.fieldValue()
fieldValue404.setName("position")
fieldValue404.setValue("3.6568 -4.2253 0")

ProtoInstance403.addFieldValue(fieldValue404)

Transform402.addChild(ProtoInstance403)

Group323.addChild(Transform402)
Transform405 = x3d.Transform()
ProtoInstance406 = x3d.ProtoInstance()
ProtoInstance406.setName("Carbon")
ProtoInstance406.setDEF("a28")
fieldValue407 = x3d.fieldValue()
fieldValue407.setName("position")
fieldValue407.setValue("-11.2825 -0.4459 0")

ProtoInstance406.addFieldValue(fieldValue407)

Transform405.addChild(ProtoInstance406)

Group323.addChild(Transform405)
Transform408 = x3d.Transform()
ProtoInstance409 = x3d.ProtoInstance()
ProtoInstance409.setName("Carbon")
ProtoInstance409.setDEF("a29")
fieldValue410 = x3d.fieldValue()
fieldValue410.setName("position")
fieldValue410.setValue("-7.2243 -4.0693 0")

ProtoInstance409.addFieldValue(fieldValue410)

Transform408.addChild(ProtoInstance409)

Group323.addChild(Transform408)
Transform411 = x3d.Transform()
ProtoInstance412 = x3d.ProtoInstance()
ProtoInstance412.setName("Carbon")
ProtoInstance412.setDEF("a30")
fieldValue413 = x3d.fieldValue()
fieldValue413.setName("position")
fieldValue413.setValue("-8.7963 -2.4081 0")

ProtoInstance412.addFieldValue(fieldValue413)

Transform411.addChild(ProtoInstance412)

Group323.addChild(Transform411)
Transform414 = x3d.Transform()
ProtoInstance415 = x3d.ProtoInstance()
ProtoInstance415.setName("Carbon")
ProtoInstance415.setDEF("a31")
fieldValue416 = x3d.fieldValue()
fieldValue416.setName("position")
fieldValue416.setValue("5.2064 5.4405 0")

ProtoInstance415.addFieldValue(fieldValue416)

Transform414.addChild(ProtoInstance415)

Group323.addChild(Transform414)
Transform417 = x3d.Transform()
ProtoInstance418 = x3d.ProtoInstance()
ProtoInstance418.setName("Carbon")
ProtoInstance418.setDEF("a32")
fieldValue419 = x3d.fieldValue()
fieldValue419.setName("position")
fieldValue419.setValue("2.0291 7.1797 0")

ProtoInstance418.addFieldValue(fieldValue419)

Transform417.addChild(ProtoInstance418)

Group323.addChild(Transform417)
Transform420 = x3d.Transform()
ProtoInstance421 = x3d.ProtoInstance()
ProtoInstance421.setName("Carbon")
ProtoInstance421.setDEF("a33")
fieldValue422 = x3d.fieldValue()
fieldValue422.setName("position")
fieldValue422.setValue("5.1841 -4.4818 0")

ProtoInstance421.addFieldValue(fieldValue422)

Transform420.addChild(ProtoInstance421)

Group323.addChild(Transform420)
Transform423 = x3d.Transform()
ProtoInstance424 = x3d.ProtoInstance()
ProtoInstance424.setName("Carbon")
ProtoInstance424.setDEF("a34")
fieldValue425 = x3d.fieldValue()
fieldValue425.setName("position")
fieldValue425.setValue("-12.3304 -1.6054 0")

ProtoInstance424.addFieldValue(fieldValue425)

Transform423.addChild(ProtoInstance424)

Group323.addChild(Transform423)
Transform426 = x3d.Transform()
ProtoInstance427 = x3d.ProtoInstance()
ProtoInstance427.setName("Carbon")
ProtoInstance427.setDEF("a35")
fieldValue428 = x3d.fieldValue()
fieldValue428.setName("position")
fieldValue428.setValue("6.7561 5.1841 0")

ProtoInstance427.addFieldValue(fieldValue428)

Transform426.addChild(ProtoInstance427)

Group323.addChild(Transform426)
Transform429 = x3d.Transform()
ProtoInstance430 = x3d.ProtoInstance()
ProtoInstance430.setName("Oxygen")
ProtoInstance430.setDEF("a36")
fieldValue431 = x3d.fieldValue()
fieldValue431.setName("position")
fieldValue431.setValue("5.2399 6.9791 0")

ProtoInstance430.addFieldValue(fieldValue431)

Transform429.addChild(ProtoInstance430)

Group323.addChild(Transform429)
Transform432 = x3d.Transform()
ProtoInstance433 = x3d.ProtoInstance()
ProtoInstance433.setName("Nitrogen")
ProtoInstance433.setDEF("a37")
fieldValue434 = x3d.fieldValue()
fieldValue434.setName("position")
fieldValue434.setValue("1.126 8.4507 0")

ProtoInstance433.addFieldValue(fieldValue434)

Transform432.addChild(ProtoInstance433)

Group323.addChild(Transform432)
Transform435 = x3d.Transform()
ProtoInstance436 = x3d.ProtoInstance()
ProtoInstance436.setName("Oxygen")
ProtoInstance436.setDEF("a38")
fieldValue437 = x3d.fieldValue()
fieldValue437.setName("position")
fieldValue437.setValue("3.5787 7.3135 0")

ProtoInstance436.addFieldValue(fieldValue437)

Transform435.addChild(ProtoInstance436)

Group323.addChild(Transform435)
Transform438 = x3d.Transform()
ProtoInstance439 = x3d.ProtoInstance()
ProtoInstance439.setName("Carbon")
ProtoInstance439.setDEF("a39")
fieldValue440 = x3d.fieldValue()
fieldValue440.setName("position")
fieldValue440.setValue("6.7226 -4.2253 0")

ProtoInstance439.addFieldValue(fieldValue440)

Transform438.addChild(ProtoInstance439)

Group323.addChild(Transform438)
Transform441 = x3d.Transform()
ProtoInstance442 = x3d.ProtoInstance()
ProtoInstance442.setName("Nitrogen")
ProtoInstance442.setDEF("a40")
fieldValue443 = x3d.fieldValue()
fieldValue443.setName("position")
fieldValue443.setValue("5.1841 -6.0203 0")

ProtoInstance442.addFieldValue(fieldValue443)

Transform441.addChild(ProtoInstance442)

Group323.addChild(Transform441)
Transform444 = x3d.Transform()
ProtoInstance445 = x3d.ProtoInstance()
ProtoInstance445.setName("Nitrogen")
ProtoInstance445.setDEF("a41")
fieldValue446 = x3d.fieldValue()
fieldValue446.setName("position")
fieldValue446.setValue("-13.8466 -1.2709 0")

ProtoInstance445.addFieldValue(fieldValue446)

Transform444.addChild(ProtoInstance445)

Group323.addChild(Transform444)
Transform447 = x3d.Transform()
ProtoInstance448 = x3d.ProtoInstance()
ProtoInstance448.setName("Oxygen")
ProtoInstance448.setDEF("a42")
fieldValue449 = x3d.fieldValue()
fieldValue449.setName("position")
fieldValue449.setValue("-11.8622 -3.0659 0")

ProtoInstance448.addFieldValue(fieldValue449)

Transform447.addChild(ProtoInstance448)

Group323.addChild(Transform447)
Transform450 = x3d.Transform()
ProtoInstance451 = x3d.ProtoInstance()
ProtoInstance451.setName("Nitrogen")
ProtoInstance451.setDEF("a43")
fieldValue452 = x3d.fieldValue()
fieldValue452.setName("position")
fieldValue452.setValue("8.1385 4.4706 0")

ProtoInstance451.addFieldValue(fieldValue452)

Transform450.addChild(ProtoInstance451)

Group323.addChild(Transform450)
Transform453 = x3d.Transform()
ProtoInstance454 = x3d.ProtoInstance()
ProtoInstance454.setName("Carbon")
ProtoInstance454.setDEF("a44")
fieldValue455 = x3d.fieldValue()
fieldValue455.setName("position")
fieldValue455.setValue("7.2243 6.6781 0")

ProtoInstance454.addFieldValue(fieldValue455)

Transform453.addChild(ProtoInstance454)

Group323.addChild(Transform453)
Transform456 = x3d.Transform()
ProtoInstance457 = x3d.ProtoInstance()
ProtoInstance457.setName("Nitrogen")
ProtoInstance457.setDEF("a45")
fieldValue458 = x3d.fieldValue()
fieldValue458.setName("position")
fieldValue458.setValue("8.1051 -3.5341 0")

ProtoInstance457.addFieldValue(fieldValue458)

Transform456.addChild(ProtoInstance457)

Group323.addChild(Transform456)
Transform459 = x3d.Transform()
ProtoInstance460 = x3d.ProtoInstance()
ProtoInstance460.setName("Oxygen")
ProtoInstance460.setDEF("a46")
fieldValue461 = x3d.fieldValue()
fieldValue461.setName("position")
fieldValue461.setValue("7.202 -5.7193 0")

ProtoInstance460.addFieldValue(fieldValue461)

Transform459.addChild(ProtoInstance460)

Group323.addChild(Transform459)
Transform462 = x3d.Transform()
ProtoInstance463 = x3d.ProtoInstance()
ProtoInstance463.setName("Carbon")
ProtoInstance463.setDEF("a47")
fieldValue464 = x3d.fieldValue()
fieldValue464.setName("position")
fieldValue464.setValue("9.2422 3.3669 0")

ProtoInstance463.addFieldValue(fieldValue464)

Transform462.addChild(ProtoInstance463)

Group323.addChild(Transform462)
Transform465 = x3d.Transform()
ProtoInstance466 = x3d.ProtoInstance()
ProtoInstance466.setName("Carbon")
ProtoInstance466.setDEF("a48")
fieldValue467 = x3d.fieldValue()
fieldValue467.setName("position")
fieldValue467.setValue("8.7406 6.9791 0")

ProtoInstance466.addFieldValue(fieldValue467)

Transform465.addChild(ProtoInstance466)

Group323.addChild(Transform465)
Transform468 = x3d.Transform()
ProtoInstance469 = x3d.ProtoInstance()
ProtoInstance469.setName("Carbon")
ProtoInstance469.setDEF("a49")
fieldValue470 = x3d.fieldValue()
fieldValue470.setName("position")
fieldValue470.setValue("9.2088 -2.4304 0")

ProtoInstance469.addFieldValue(fieldValue470)

Transform468.addChild(ProtoInstance469)

Group323.addChild(Transform468)
Transform471 = x3d.Transform()
ProtoInstance472 = x3d.ProtoInstance()
ProtoInstance472.setName("Carbon")
ProtoInstance472.setDEF("a50")
fieldValue473 = x3d.fieldValue()
fieldValue473.setName("position")
fieldValue473.setValue("9.9335 1.9845 0")

ProtoInstance472.addFieldValue(fieldValue473)

Transform471.addChild(ProtoInstance472)

Group323.addChild(Transform471)
Transform474 = x3d.Transform()
ProtoInstance475 = x3d.ProtoInstance()
ProtoInstance475.setName("Oxygen")
ProtoInstance475.setDEF("a51")
fieldValue476 = x3d.fieldValue()
fieldValue476.setName("position")
fieldValue476.setValue("10.4797 4.3034 0")

ProtoInstance475.addFieldValue(fieldValue476)

Transform474.addChild(ProtoInstance475)

Group323.addChild(Transform474)
Transform477 = x3d.Transform()
ProtoInstance478 = x3d.ProtoInstance()
ProtoInstance478.setName("Carbon")
ProtoInstance478.setDEF("a52")
fieldValue479 = x3d.fieldValue()
fieldValue479.setName("position")
fieldValue479.setValue("9.2422 8.4507 0")

ProtoInstance478.addFieldValue(fieldValue479)

Transform477.addChild(ProtoInstance478)

Group323.addChild(Transform477)
Transform480 = x3d.Transform()
ProtoInstance481 = x3d.ProtoInstance()
ProtoInstance481.setName("Carbon")
ProtoInstance481.setDEF("a53")
fieldValue482 = x3d.fieldValue()
fieldValue482.setName("position")
fieldValue482.setValue("10.4797 -3.3446 0")

ProtoInstance481.addFieldValue(fieldValue482)

Transform480.addChild(ProtoInstance481)

Group323.addChild(Transform480)
Transform483 = x3d.Transform()
ProtoInstance484 = x3d.ProtoInstance()
ProtoInstance484.setName("Carbon")
ProtoInstance484.setDEF("a54")
fieldValue485 = x3d.fieldValue()
fieldValue485.setName("position")
fieldValue485.setValue("9.9335 -1.0591 0")

ProtoInstance484.addFieldValue(fieldValue485)

Transform483.addChild(ProtoInstance484)

Group323.addChild(Transform483)
Transform486 = x3d.Transform()
ProtoInstance487 = x3d.ProtoInstance()
ProtoInstance487.setName("Nitrogen")
ProtoInstance487.setDEF("a55")
fieldValue488 = x3d.fieldValue()
fieldValue488.setName("position")
fieldValue488.setValue("10.1787 0.4682 0")

ProtoInstance487.addFieldValue(fieldValue488)

Transform486.addChild(ProtoInstance487)

Group323.addChild(Transform486)
Transform489 = x3d.Transform()
ProtoInstance490 = x3d.ProtoInstance()
ProtoInstance490.setName("Carbon")
ProtoInstance490.setDEF("a56")
fieldValue491 = x3d.fieldValue()
fieldValue491.setName("position")
fieldValue491.setValue("11.4274 2.4862 0")

ProtoInstance490.addFieldValue(fieldValue491)

Transform489.addChild(ProtoInstance490)

Group323.addChild(Transform489)
Transform492 = x3d.Transform()
ProtoInstance493 = x3d.ProtoInstance()
ProtoInstance493.setName("Nitrogen")
ProtoInstance493.setDEF("a57")
fieldValue494 = x3d.fieldValue()
fieldValue494.setName("position")
fieldValue494.setValue("10.7585 8.774 0")

ProtoInstance493.addFieldValue(fieldValue494)

Transform492.addChild(ProtoInstance493)

Group323.addChild(Transform492)
Transform495 = x3d.Transform()
ProtoInstance496 = x3d.ProtoInstance()
ProtoInstance496.setName("Oxygen")
ProtoInstance496.setDEF("a58")
fieldValue497 = x3d.fieldValue()
fieldValue497.setName("position")
fieldValue497.setValue("8.2166 9.6324 0")

ProtoInstance496.addFieldValue(fieldValue497)

Transform495.addChild(ProtoInstance496)

Group323.addChild(Transform495)
Transform498 = x3d.Transform()
ProtoInstance499 = x3d.ProtoInstance()
ProtoInstance499.setName("Carbon")
ProtoInstance499.setDEF("a59")
fieldValue500 = x3d.fieldValue()
fieldValue500.setName("position")
fieldValue500.setValue("10.3237 -4.8943 0")

ProtoInstance499.addFieldValue(fieldValue500)

Transform498.addChild(ProtoInstance499)

Group323.addChild(Transform498)
Transform501 = x3d.Transform()
ProtoInstance502 = x3d.ProtoInstance()
ProtoInstance502.setName("Oxygen")
ProtoInstance502.setDEF("a60")
fieldValue503 = x3d.fieldValue()
fieldValue503.setName("position")
fieldValue503.setValue("11.4274 -1.5274 0")

ProtoInstance502.addFieldValue(fieldValue503)

Transform501.addChild(ProtoInstance502)

Group323.addChild(Transform501)
Transform504 = x3d.Transform()
ProtoInstance505 = x3d.ProtoInstance()
ProtoInstance505.setName("Carbon")
ProtoInstance505.setDEF("a61")
fieldValue506 = x3d.fieldValue()
fieldValue506.setName("position")
fieldValue506.setValue("12.5534 1.427 0")

ProtoInstance505.addFieldValue(fieldValue506)

Transform504.addChild(ProtoInstance505)

Group323.addChild(Transform504)
Transform507 = x3d.Transform()
ProtoInstance508 = x3d.ProtoInstance()
ProtoInstance508.setName("Carbon")
ProtoInstance508.setDEF("a62")
fieldValue509 = x3d.fieldValue()
fieldValue509.setName("position")
fieldValue509.setValue("11.7507 4.0024 0")

ProtoInstance508.addFieldValue(fieldValue509)

Transform507.addChild(ProtoInstance508)

Group323.addChild(Transform507)
Transform510 = x3d.Transform()
ProtoInstance511 = x3d.ProtoInstance()
ProtoInstance511.setName("Carbon")
ProtoInstance511.setDEF("a63")
fieldValue512 = x3d.fieldValue()
fieldValue512.setName("position")
fieldValue512.setValue("8.8855 -5.5297 0")

ProtoInstance511.addFieldValue(fieldValue512)

Transform510.addChild(ProtoInstance511)

Group323.addChild(Transform510)
Transform513 = x3d.Transform()
ProtoInstance514 = x3d.ProtoInstance()
ProtoInstance514.setName("Carbon")
ProtoInstance514.setDEF("a64")
fieldValue515 = x3d.fieldValue()
fieldValue515.setName("position")
fieldValue515.setValue("11.5612 -5.8085 0")

ProtoInstance514.addFieldValue(fieldValue515)

Transform513.addChild(ProtoInstance514)

Group323.addChild(Transform513)
Transform516 = x3d.Transform()
ProtoInstance517 = x3d.ProtoInstance()
ProtoInstance517.setName("Carbon")
ProtoInstance517.setDEF("a65")
fieldValue518 = x3d.fieldValue()
fieldValue518.setName("position")
fieldValue518.setValue("14.0473 1.9064 0")

ProtoInstance517.addFieldValue(fieldValue518)

Transform516.addChild(ProtoInstance517)

Group323.addChild(Transform516)
Transform519 = x3d.Transform()
ProtoInstance520 = x3d.ProtoInstance()
ProtoInstance520.setName("Carbon")
ProtoInstance520.setDEF("a66")
fieldValue521 = x3d.fieldValue()
fieldValue521.setName("position")
fieldValue521.setValue("8.7183 -7.0794 0")

ProtoInstance520.addFieldValue(fieldValue521)

Transform519.addChild(ProtoInstance520)

Group323.addChild(Transform519)
Transform522 = x3d.Transform()
ProtoInstance523 = x3d.ProtoInstance()
ProtoInstance523.setName("Carbon")
ProtoInstance523.setDEF("a67")
fieldValue524 = x3d.fieldValue()
fieldValue524.setName("position")
fieldValue524.setValue("11.3939 -7.347 0")

ProtoInstance523.addFieldValue(fieldValue524)

Transform522.addChild(ProtoInstance523)

Group323.addChild(Transform522)
Transform525 = x3d.Transform()
ProtoInstance526 = x3d.ProtoInstance()
ProtoInstance526.setName("Carbon")
ProtoInstance526.setDEF("a68")
fieldValue527 = x3d.fieldValue()
fieldValue527.setName("position")
fieldValue527.setValue("9.9892 -7.9824 0")

ProtoInstance526.addFieldValue(fieldValue527)

Transform525.addChild(ProtoInstance526)

Group323.addChild(Transform525)
Transform528 = x3d.Transform()
ProtoInstance529 = x3d.ProtoInstance()
ProtoInstance529.setName("Oxygen")
ProtoInstance529.setDEF("a69")
fieldValue530 = x3d.fieldValue()
fieldValue530.setName("position")
fieldValue530.setValue("9.7885 -9.5321 0")

ProtoInstance529.addFieldValue(fieldValue530)

Transform528.addChild(ProtoInstance529)

Group323.addChild(Transform528)

Scene19.addChild(Group323)
Group531 = x3d.Group()
ProtoInstance532 = x3d.ProtoInstance()
ProtoInstance532.setName("line")
ProtoInstance532.setDEF("b1")
fieldValue533 = x3d.fieldValue()
fieldValue533.setName("bond_set")
fieldValue533.setValue("-2.0514 1.8507 0 -3.601 1.9845 0")

ProtoInstance532.addFieldValue(fieldValue533)

Group531.addChild(ProtoInstance532)
ProtoInstance534 = x3d.ProtoInstance()
ProtoInstance534.setName("line")
ProtoInstance534.setDEF("b2")
fieldValue535 = x3d.fieldValue()
fieldValue535.setName("bond_set")
fieldValue535.setValue("-2.0514 1.8507 0 -1.2821 0.4905 0")

ProtoInstance534.addFieldValue(fieldValue535)

Group531.addChild(ProtoInstance534)
ProtoInstance536 = x3d.ProtoInstance()
ProtoInstance536.setName("line")
ProtoInstance536.setDEF("b3")
fieldValue537 = x3d.fieldValue()
fieldValue537.setName("bond_set")
fieldValue537.setValue("-2.0514 1.8507 0 -1.4159 3.2554 0")

ProtoInstance536.addFieldValue(fieldValue537)

Group531.addChild(ProtoInstance536)
ProtoInstance538 = x3d.ProtoInstance()
ProtoInstance538.setName("line")
ProtoInstance538.setDEF("b4")
fieldValue539 = x3d.fieldValue()
fieldValue539.setName("bond_set")
fieldValue539.setValue("-3.601 1.9845 0 -4.649 0.8473 0")

ProtoInstance538.addFieldValue(fieldValue539)

Group531.addChild(ProtoInstance538)
ProtoInstance540 = x3d.ProtoInstance()
ProtoInstance540.setName("line")
ProtoInstance540.setDEF("b5")
fieldValue541 = x3d.fieldValue()
fieldValue541.setName("bond_set")
fieldValue541.setValue("-3.601 1.9845 0 -3.9355 3.5341 0")

ProtoInstance540.addFieldValue(fieldValue541)

Group531.addChild(ProtoInstance540)
ProtoInstance542 = x3d.ProtoInstance()
ProtoInstance542.setName("line")
ProtoInstance542.setDEF("b6")
fieldValue543 = x3d.fieldValue()
fieldValue543.setName("bond_set")
fieldValue543.setValue("-1.2821 0.4905 0 0.2341 0.4905 0")

ProtoInstance542.addFieldValue(fieldValue543)

Group531.addChild(ProtoInstance542)
ProtoInstance544 = x3d.ProtoInstance()
ProtoInstance544.setName("line")
ProtoInstance544.setDEF("b7")
fieldValue545 = x3d.fieldValue()
fieldValue545.setName("bond_set")
fieldValue545.setValue("-1.3021 0.4905 0 -2.0714 -0.8362 0")

ProtoInstance544.addFieldValue(fieldValue545)

Group531.addChild(ProtoInstance544)
ProtoInstance546 = x3d.ProtoInstance()
ProtoInstance546.setName("line")
ProtoInstance546.setDEF("b7_2")
fieldValue547 = x3d.fieldValue()
fieldValue547.setName("bond_set")
fieldValue547.setValue("-1.2621 0.4905 0 -2.0314 -0.8362 0")

ProtoInstance546.addFieldValue(fieldValue547)

Group531.addChild(ProtoInstance546)
ProtoInstance548 = x3d.ProtoInstance()
ProtoInstance548.setName("line")
ProtoInstance548.setDEF("b8")
fieldValue549 = x3d.fieldValue()
fieldValue549.setName("bond_set")
fieldValue549.setValue("-1.4159 3.2554 0 -2.5753 4.3034 0")

ProtoInstance548.addFieldValue(fieldValue549)

Group531.addChild(ProtoInstance548)
ProtoInstance550 = x3d.ProtoInstance()
ProtoInstance550.setName("line")
ProtoInstance550.setDEF("b9")
fieldValue551 = x3d.fieldValue()
fieldValue551.setName("bond_set")
fieldValue551.setValue("-4.649 0.8473 0 -6.1764 1.1595 0")

ProtoInstance550.addFieldValue(fieldValue551)

Group531.addChild(ProtoInstance550)
ProtoInstance552 = x3d.ProtoInstance()
ProtoInstance552.setName("line")
ProtoInstance552.setDEF("b10")
fieldValue553 = x3d.fieldValue()
fieldValue553.setName("bond_set")
fieldValue553.setValue("-4.669 0.8473 0 -4.1785 -0.6132 0")

ProtoInstance552.addFieldValue(fieldValue553)

Group531.addChild(ProtoInstance552)
ProtoInstance554 = x3d.ProtoInstance()
ProtoInstance554.setName("line")
ProtoInstance554.setDEF("b10_2")
fieldValue555 = x3d.fieldValue()
fieldValue555.setName("bond_set")
fieldValue555.setValue("-4.6290000000000004 0.8473 0 -4.1385000000000005 -0.6132 0")

ProtoInstance554.addFieldValue(fieldValue555)

Group531.addChild(ProtoInstance554)
ProtoInstance556 = x3d.ProtoInstance()
ProtoInstance556.setName("line")
ProtoInstance556.setDEF("b11")
fieldValue557 = x3d.fieldValue()
fieldValue557.setName("bond_set")
fieldValue557.setValue("0.2341 0.4905 0 0.4905 2.0402 0")

ProtoInstance556.addFieldValue(fieldValue557)

Group531.addChild(ProtoInstance556)
ProtoInstance558 = x3d.ProtoInstance()
ProtoInstance558.setName("line")
ProtoInstance558.setDEF("b12")
fieldValue559 = x3d.fieldValue()
fieldValue559.setName("bond_set")
fieldValue559.setValue("0.2341 0.4905 0 0.4905 -1.0257 0")

ProtoInstance558.addFieldValue(fieldValue559)

Group531.addChild(ProtoInstance558)
ProtoInstance560 = x3d.ProtoInstance()
ProtoInstance560.setName("line")
ProtoInstance560.setDEF("b13")
fieldValue561 = x3d.fieldValue()
fieldValue561.setName("bond_set")
fieldValue561.setValue("-6.1764 1.1595 0 -7.2243 0.0223 0")

ProtoInstance560.addFieldValue(fieldValue561)

Group531.addChild(ProtoInstance560)
ProtoInstance562 = x3d.ProtoInstance()
ProtoInstance562.setName("line")
ProtoInstance562.setDEF("b14")
fieldValue563 = x3d.fieldValue()
fieldValue563.setName("bond_set")
fieldValue563.setValue("0.4905 2.0402 0 1.2041 3.3892 0")

ProtoInstance562.addFieldValue(fieldValue563)

Group531.addChild(ProtoInstance562)
ProtoInstance564 = x3d.ProtoInstance()
ProtoInstance564.setName("line")
ProtoInstance564.setDEF("b15")
fieldValue565 = x3d.fieldValue()
fieldValue565.setName("bond_set")
fieldValue565.setValue("0.4905 -1.0257 0 1.1706 -2.4081 0")

ProtoInstance564.addFieldValue(fieldValue565)

Group531.addChild(ProtoInstance564)
ProtoInstance566 = x3d.ProtoInstance()
ProtoInstance566.setName("line")
ProtoInstance566.setDEF("b16")
fieldValue567 = x3d.fieldValue()
fieldValue567.setName("bond_set")
fieldValue567.setValue("-7.2243 0.0223 0 -8.7071 0.3568 0")

ProtoInstance566.addFieldValue(fieldValue567)

Group531.addChild(ProtoInstance566)
ProtoInstance568 = x3d.ProtoInstance()
ProtoInstance568.setName("line")
ProtoInstance568.setDEF("b17")
fieldValue569 = x3d.fieldValue()
fieldValue569.setName("bond_set")
fieldValue569.setValue("-7.2243 0.0223 0 -6.7226 -1.4382 0")

ProtoInstance568.addFieldValue(fieldValue569)

Group531.addChild(ProtoInstance568)
ProtoInstance570 = x3d.ProtoInstance()
ProtoInstance570.setName("line")
ProtoInstance570.setDEF("b18")
fieldValue571 = x3d.fieldValue()
fieldValue571.setName("bond_set")
fieldValue571.setValue("1.2041 3.3892 0 2.3078 4.4929 0")

ProtoInstance570.addFieldValue(fieldValue571)

Group531.addChild(ProtoInstance570)
ProtoInstance572 = x3d.ProtoInstance()
ProtoInstance572.setName("line")
ProtoInstance572.setDEF("b19")
fieldValue573 = x3d.fieldValue()
fieldValue573.setName("bond_set")
fieldValue573.setValue("1.1841 3.3892 0 -0.0646 4.3368 0")

ProtoInstance572.addFieldValue(fieldValue573)

Group531.addChild(ProtoInstance572)
ProtoInstance574 = x3d.ProtoInstance()
ProtoInstance574.setName("line")
ProtoInstance574.setDEF("b19_2")
fieldValue575 = x3d.fieldValue()
fieldValue575.setName("bond_set")
fieldValue575.setValue("1.2241 3.3892 0 -0.0246 4.3368 0")

ProtoInstance574.addFieldValue(fieldValue575)

Group531.addChild(ProtoInstance574)
ProtoInstance576 = x3d.ProtoInstance()
ProtoInstance576.setName("line")
ProtoInstance576.setDEF("b20")
fieldValue577 = x3d.fieldValue()
fieldValue577.setName("bond_set")
fieldValue577.setValue("1.1706 -2.4081 0 2.2855 -3.5118 0")

ProtoInstance576.addFieldValue(fieldValue577)

Group531.addChild(ProtoInstance576)
ProtoInstance578 = x3d.ProtoInstance()
ProtoInstance578.setName("line")
ProtoInstance578.setDEF("b21")
fieldValue579 = x3d.fieldValue()
fieldValue579.setName("bond_set")
fieldValue579.setValue("-8.7071 0.3568 0 -9.7662 -0.7804 0")

ProtoInstance578.addFieldValue(fieldValue579)

Group531.addChild(ProtoInstance578)
ProtoInstance580 = x3d.ProtoInstance()
ProtoInstance580.setName("line")
ProtoInstance580.setDEF("b22")
fieldValue581 = x3d.fieldValue()
fieldValue581.setName("bond_set")
fieldValue581.setValue("-8.7271 0.3568 0 -9.2288 1.8507 0")

ProtoInstance580.addFieldValue(fieldValue581)

Group531.addChild(ProtoInstance580)
ProtoInstance582 = x3d.ProtoInstance()
ProtoInstance582.setName("line")
ProtoInstance582.setDEF("b22_2")
fieldValue583 = x3d.fieldValue()
fieldValue583.setName("bond_set")
fieldValue583.setValue("-8.687100000000001 0.3568 0 -9.1888 1.8507 0")

ProtoInstance582.addFieldValue(fieldValue583)

Group531.addChild(ProtoInstance582)
ProtoInstance584 = x3d.ProtoInstance()
ProtoInstance584.setName("line")
ProtoInstance584.setDEF("b23")
fieldValue585 = x3d.fieldValue()
fieldValue585.setName("bond_set")
fieldValue585.setValue("-6.7226 -1.4382 0 -7.7483 -2.5753 0")

ProtoInstance584.addFieldValue(fieldValue585)

Group531.addChild(ProtoInstance584)
ProtoInstance586 = x3d.ProtoInstance()
ProtoInstance586.setName("line")
ProtoInstance586.setDEF("b24")
fieldValue587 = x3d.fieldValue()
fieldValue587.setName("bond_set")
fieldValue587.setValue("2.3078 4.4929 0 3.6902 5.1841 0")

ProtoInstance586.addFieldValue(fieldValue587)

Group531.addChild(ProtoInstance586)
ProtoInstance588 = x3d.ProtoInstance()
ProtoInstance588.setName("line")
ProtoInstance588.setDEF("b25")
fieldValue589 = x3d.fieldValue()
fieldValue589.setName("bond_set")
fieldValue589.setValue("2.3078 4.4929 0 1.3936 5.7416 0")

ProtoInstance588.addFieldValue(fieldValue589)

Group531.addChild(ProtoInstance588)
ProtoInstance590 = x3d.ProtoInstance()
ProtoInstance590.setName("line")
ProtoInstance590.setDEF("b26")
fieldValue591 = x3d.fieldValue()
fieldValue591.setName("bond_set")
fieldValue591.setValue("2.2855 -3.5118 0 3.6568 -4.2253 0")

ProtoInstance590.addFieldValue(fieldValue591)

Group531.addChild(ProtoInstance590)
ProtoInstance592 = x3d.ProtoInstance()
ProtoInstance592.setName("line")
ProtoInstance592.setDEF("b27")
fieldValue593 = x3d.fieldValue()
fieldValue593.setName("bond_set")
fieldValue593.setValue("-9.7662 -0.7804 0 -11.2825 -0.4459 0")

ProtoInstance592.addFieldValue(fieldValue593)

Group531.addChild(ProtoInstance592)
ProtoInstance594 = x3d.ProtoInstance()
ProtoInstance594.setName("line")
ProtoInstance594.setDEF("b28")
fieldValue595 = x3d.fieldValue()
fieldValue595.setName("bond_set")
fieldValue595.setValue("-7.7483 -2.5753 0 -7.2243 -4.0693 0")

ProtoInstance594.addFieldValue(fieldValue595)

Group531.addChild(ProtoInstance594)
ProtoInstance596 = x3d.ProtoInstance()
ProtoInstance596.setName("line")
ProtoInstance596.setDEF("b29")
fieldValue597 = x3d.fieldValue()
fieldValue597.setName("bond_set")
fieldValue597.setValue("-7.7483 -2.5753 0 -8.7963 -2.4081 0")

ProtoInstance596.addFieldValue(fieldValue597)

Group531.addChild(ProtoInstance596)
ProtoInstance598 = x3d.ProtoInstance()
ProtoInstance598.setName("line")
ProtoInstance598.setDEF("b30")
fieldValue599 = x3d.fieldValue()
fieldValue599.setName("bond_set")
fieldValue599.setValue("3.6902 5.1841 0 5.2064 5.4405 0")

ProtoInstance598.addFieldValue(fieldValue599)

Group531.addChild(ProtoInstance598)
ProtoInstance600 = x3d.ProtoInstance()
ProtoInstance600.setName("line")
ProtoInstance600.setDEF("b31")
fieldValue601 = x3d.fieldValue()
fieldValue601.setName("bond_set")
fieldValue601.setValue("1.3936 5.7416 0 2.0291 7.1797 0")

ProtoInstance600.addFieldValue(fieldValue601)

Group531.addChild(ProtoInstance600)
ProtoInstance602 = x3d.ProtoInstance()
ProtoInstance602.setName("line")
ProtoInstance602.setDEF("b32")
fieldValue603 = x3d.fieldValue()
fieldValue603.setName("bond_set")
fieldValue603.setValue("3.6568 -4.2253 0 5.1841 -4.4818 0")

ProtoInstance602.addFieldValue(fieldValue603)

Group531.addChild(ProtoInstance602)
ProtoInstance604 = x3d.ProtoInstance()
ProtoInstance604.setName("line")
ProtoInstance604.setDEF("b33")
fieldValue605 = x3d.fieldValue()
fieldValue605.setName("bond_set")
fieldValue605.setValue("-11.2825 -0.4459 0 -12.3304 -1.6054 0")

ProtoInstance604.addFieldValue(fieldValue605)

Group531.addChild(ProtoInstance604)
ProtoInstance606 = x3d.ProtoInstance()
ProtoInstance606.setName("line")
ProtoInstance606.setDEF("b34")
fieldValue607 = x3d.fieldValue()
fieldValue607.setName("bond_set")
fieldValue607.setValue("5.2064 5.4405 0 6.7561 5.1841 0")

ProtoInstance606.addFieldValue(fieldValue607)

Group531.addChild(ProtoInstance606)
ProtoInstance608 = x3d.ProtoInstance()
ProtoInstance608.setName("line")
ProtoInstance608.setDEF("b35")
fieldValue609 = x3d.fieldValue()
fieldValue609.setName("bond_set")
fieldValue609.setValue("5.186400000000001 5.4405 0 5.2199 6.9791 0")

ProtoInstance608.addFieldValue(fieldValue609)

Group531.addChild(ProtoInstance608)
ProtoInstance610 = x3d.ProtoInstance()
ProtoInstance610.setName("line")
ProtoInstance610.setDEF("b35_2")
fieldValue611 = x3d.fieldValue()
fieldValue611.setName("bond_set")
fieldValue611.setValue("5.2264 5.4405 0 5.259899999999999 6.9791 0")

ProtoInstance610.addFieldValue(fieldValue611)

Group531.addChild(ProtoInstance610)
ProtoInstance612 = x3d.ProtoInstance()
ProtoInstance612.setName("line")
ProtoInstance612.setDEF("b36")
fieldValue613 = x3d.fieldValue()
fieldValue613.setName("bond_set")
fieldValue613.setValue("2.0291 7.1797 0 1.126 8.4507 0")

ProtoInstance612.addFieldValue(fieldValue613)

Group531.addChild(ProtoInstance612)
ProtoInstance614 = x3d.ProtoInstance()
ProtoInstance614.setName("line")
ProtoInstance614.setDEF("b37")
fieldValue615 = x3d.fieldValue()
fieldValue615.setName("bond_set")
fieldValue615.setValue("2.0091 7.1797 0 3.5587 7.3135 0")

ProtoInstance614.addFieldValue(fieldValue615)

Group531.addChild(ProtoInstance614)
ProtoInstance616 = x3d.ProtoInstance()
ProtoInstance616.setName("line")
ProtoInstance616.setDEF("b37_2")
fieldValue617 = x3d.fieldValue()
fieldValue617.setName("bond_set")
fieldValue617.setValue("2.0491 7.1797 0 3.5987 7.3135 0")

ProtoInstance616.addFieldValue(fieldValue617)

Group531.addChild(ProtoInstance616)
ProtoInstance618 = x3d.ProtoInstance()
ProtoInstance618.setName("line")
ProtoInstance618.setDEF("b38")
fieldValue619 = x3d.fieldValue()
fieldValue619.setName("bond_set")
fieldValue619.setValue("5.1841 -4.4818 0 6.7226 -4.2253 0")

ProtoInstance618.addFieldValue(fieldValue619)

Group531.addChild(ProtoInstance618)
ProtoInstance620 = x3d.ProtoInstance()
ProtoInstance620.setName("line")
ProtoInstance620.setDEF("b39")
fieldValue621 = x3d.fieldValue()
fieldValue621.setName("bond_set")
fieldValue621.setValue("5.1841 -4.4818 0 5.1841 -6.0203 0")

ProtoInstance620.addFieldValue(fieldValue621)

Group531.addChild(ProtoInstance620)
ProtoInstance622 = x3d.ProtoInstance()
ProtoInstance622.setName("line")
ProtoInstance622.setDEF("b40")
fieldValue623 = x3d.fieldValue()
fieldValue623.setName("bond_set")
fieldValue623.setValue("-12.3304 -1.6054 0 -13.8466 -1.2709 0")

ProtoInstance622.addFieldValue(fieldValue623)

Group531.addChild(ProtoInstance622)
ProtoInstance624 = x3d.ProtoInstance()
ProtoInstance624.setName("line")
ProtoInstance624.setDEF("b41")
fieldValue625 = x3d.fieldValue()
fieldValue625.setName("bond_set")
fieldValue625.setValue("-12.350399999999999 -1.6054 0 -11.8822 -3.0659 0")

ProtoInstance624.addFieldValue(fieldValue625)

Group531.addChild(ProtoInstance624)
ProtoInstance626 = x3d.ProtoInstance()
ProtoInstance626.setName("line")
ProtoInstance626.setDEF("b41_2")
fieldValue627 = x3d.fieldValue()
fieldValue627.setName("bond_set")
fieldValue627.setValue("-12.3104 -1.6054 0 -11.8422 -3.0659 0")

ProtoInstance626.addFieldValue(fieldValue627)

Group531.addChild(ProtoInstance626)
ProtoInstance628 = x3d.ProtoInstance()
ProtoInstance628.setName("line")
ProtoInstance628.setDEF("b42")
fieldValue629 = x3d.fieldValue()
fieldValue629.setName("bond_set")
fieldValue629.setValue("6.7561 5.1841 0 8.1385 4.4706 0")

ProtoInstance628.addFieldValue(fieldValue629)

Group531.addChild(ProtoInstance628)
ProtoInstance630 = x3d.ProtoInstance()
ProtoInstance630.setName("line")
ProtoInstance630.setDEF("b43")
fieldValue631 = x3d.fieldValue()
fieldValue631.setName("bond_set")
fieldValue631.setValue("6.7561 5.1841 0 7.2243 6.6781 0")

ProtoInstance630.addFieldValue(fieldValue631)

Group531.addChild(ProtoInstance630)
ProtoInstance632 = x3d.ProtoInstance()
ProtoInstance632.setName("line")
ProtoInstance632.setDEF("b44")
fieldValue633 = x3d.fieldValue()
fieldValue633.setName("bond_set")
fieldValue633.setValue("6.7226 -4.2253 0 8.1051 -3.5341 0")

ProtoInstance632.addFieldValue(fieldValue633)

Group531.addChild(ProtoInstance632)
ProtoInstance634 = x3d.ProtoInstance()
ProtoInstance634.setName("line")
ProtoInstance634.setDEF("b45")
fieldValue635 = x3d.fieldValue()
fieldValue635.setName("bond_set")
fieldValue635.setValue("6.7026 -4.2253 0 7.182 -5.7193 0")

ProtoInstance634.addFieldValue(fieldValue635)

Group531.addChild(ProtoInstance634)
ProtoInstance636 = x3d.ProtoInstance()
ProtoInstance636.setName("line")
ProtoInstance636.setDEF("b45_2")
fieldValue637 = x3d.fieldValue()
fieldValue637.setName("bond_set")
fieldValue637.setValue("6.7425999999999995 -4.2253 0 7.2219999999999995 -5.7193 0")

ProtoInstance636.addFieldValue(fieldValue637)

Group531.addChild(ProtoInstance636)
ProtoInstance638 = x3d.ProtoInstance()
ProtoInstance638.setName("line")
ProtoInstance638.setDEF("b46")
fieldValue639 = x3d.fieldValue()
fieldValue639.setName("bond_set")
fieldValue639.setValue("8.1385 4.4706 0 9.2422 3.3669 0")

ProtoInstance638.addFieldValue(fieldValue639)

Group531.addChild(ProtoInstance638)
ProtoInstance640 = x3d.ProtoInstance()
ProtoInstance640.setName("line")
ProtoInstance640.setDEF("b47")
fieldValue641 = x3d.fieldValue()
fieldValue641.setName("bond_set")
fieldValue641.setValue("7.2243 6.6781 0 8.7406 6.9791 0")

ProtoInstance640.addFieldValue(fieldValue641)

Group531.addChild(ProtoInstance640)
ProtoInstance642 = x3d.ProtoInstance()
ProtoInstance642.setName("line")
ProtoInstance642.setDEF("b48")
fieldValue643 = x3d.fieldValue()
fieldValue643.setName("bond_set")
fieldValue643.setValue("8.1051 -3.5341 0 9.2088 -2.4304 0")

ProtoInstance642.addFieldValue(fieldValue643)

Group531.addChild(ProtoInstance642)
ProtoInstance644 = x3d.ProtoInstance()
ProtoInstance644.setName("line")
ProtoInstance644.setDEF("b49")
fieldValue645 = x3d.fieldValue()
fieldValue645.setName("bond_set")
fieldValue645.setValue("9.2422 3.3669 0 9.9335 1.9845 0")

ProtoInstance644.addFieldValue(fieldValue645)

Group531.addChild(ProtoInstance644)
ProtoInstance646 = x3d.ProtoInstance()
ProtoInstance646.setName("line")
ProtoInstance646.setDEF("b50")
fieldValue647 = x3d.fieldValue()
fieldValue647.setName("bond_set")
fieldValue647.setValue("9.2222 3.3669 0 10.4597 4.3034 0")

ProtoInstance646.addFieldValue(fieldValue647)

Group531.addChild(ProtoInstance646)
ProtoInstance648 = x3d.ProtoInstance()
ProtoInstance648.setName("line")
ProtoInstance648.setDEF("b50_2")
fieldValue649 = x3d.fieldValue()
fieldValue649.setName("bond_set")
fieldValue649.setValue("9.2622 3.3669 0 10.499699999999999 4.3034 0")

ProtoInstance648.addFieldValue(fieldValue649)

Group531.addChild(ProtoInstance648)
ProtoInstance650 = x3d.ProtoInstance()
ProtoInstance650.setName("line")
ProtoInstance650.setDEF("b51")
fieldValue651 = x3d.fieldValue()
fieldValue651.setName("bond_set")
fieldValue651.setValue("8.7406 6.9791 0 9.2422 8.4507 0")

ProtoInstance650.addFieldValue(fieldValue651)

Group531.addChild(ProtoInstance650)
ProtoInstance652 = x3d.ProtoInstance()
ProtoInstance652.setName("line")
ProtoInstance652.setDEF("b52")
fieldValue653 = x3d.fieldValue()
fieldValue653.setName("bond_set")
fieldValue653.setValue("9.2088 -2.4304 0 10.4797 -3.3446 0")

ProtoInstance652.addFieldValue(fieldValue653)

Group531.addChild(ProtoInstance652)
ProtoInstance654 = x3d.ProtoInstance()
ProtoInstance654.setName("line")
ProtoInstance654.setDEF("b53")
fieldValue655 = x3d.fieldValue()
fieldValue655.setName("bond_set")
fieldValue655.setValue("9.2088 -2.4304 0 9.9335 -1.0591 0")

ProtoInstance654.addFieldValue(fieldValue655)

Group531.addChild(ProtoInstance654)
ProtoInstance656 = x3d.ProtoInstance()
ProtoInstance656.setName("line")
ProtoInstance656.setDEF("b54")
fieldValue657 = x3d.fieldValue()
fieldValue657.setName("bond_set")
fieldValue657.setValue("9.9335 1.9845 0 10.1787 0.4682 0")

ProtoInstance656.addFieldValue(fieldValue657)

Group531.addChild(ProtoInstance656)
ProtoInstance658 = x3d.ProtoInstance()
ProtoInstance658.setName("line")
ProtoInstance658.setDEF("b55")
fieldValue659 = x3d.fieldValue()
fieldValue659.setName("bond_set")
fieldValue659.setValue("9.9335 1.9845 0 11.4274 2.4862 0")

ProtoInstance658.addFieldValue(fieldValue659)

Group531.addChild(ProtoInstance658)
ProtoInstance660 = x3d.ProtoInstance()
ProtoInstance660.setName("line")
ProtoInstance660.setDEF("b56")
fieldValue661 = x3d.fieldValue()
fieldValue661.setName("bond_set")
fieldValue661.setValue("9.2422 8.4507 0 10.7585 8.774 0")

ProtoInstance660.addFieldValue(fieldValue661)

Group531.addChild(ProtoInstance660)
ProtoInstance662 = x3d.ProtoInstance()
ProtoInstance662.setName("line")
ProtoInstance662.setDEF("b57")
fieldValue663 = x3d.fieldValue()
fieldValue663.setName("bond_set")
fieldValue663.setValue("9.2222 8.4507 0 8.1966 9.6324 0")

ProtoInstance662.addFieldValue(fieldValue663)

Group531.addChild(ProtoInstance662)
ProtoInstance664 = x3d.ProtoInstance()
ProtoInstance664.setName("line")
ProtoInstance664.setDEF("b57_2")
fieldValue665 = x3d.fieldValue()
fieldValue665.setName("bond_set")
fieldValue665.setValue("9.2622 8.4507 0 8.2366 9.6324 0")

ProtoInstance664.addFieldValue(fieldValue665)

Group531.addChild(ProtoInstance664)
ProtoInstance666 = x3d.ProtoInstance()
ProtoInstance666.setName("line")
ProtoInstance666.setDEF("b58")
fieldValue667 = x3d.fieldValue()
fieldValue667.setName("bond_set")
fieldValue667.setValue("10.4797 -3.3446 0 10.3237 -4.8943 0")

ProtoInstance666.addFieldValue(fieldValue667)

Group531.addChild(ProtoInstance666)
ProtoInstance668 = x3d.ProtoInstance()
ProtoInstance668.setName("line")
ProtoInstance668.setDEF("b59")
fieldValue669 = x3d.fieldValue()
fieldValue669.setName("bond_set")
fieldValue669.setValue("9.9135 -1.0591 0 11.4074 -1.5274 0")

ProtoInstance668.addFieldValue(fieldValue669)

Group531.addChild(ProtoInstance668)
ProtoInstance670 = x3d.ProtoInstance()
ProtoInstance670.setName("line")
ProtoInstance670.setDEF("b59_2")
fieldValue671 = x3d.fieldValue()
fieldValue671.setName("bond_set")
fieldValue671.setValue("9.9535 -1.0591 0 11.4474 -1.5274 0")

ProtoInstance670.addFieldValue(fieldValue671)

Group531.addChild(ProtoInstance670)
ProtoInstance672 = x3d.ProtoInstance()
ProtoInstance672.setName("line")
ProtoInstance672.setDEF("b60")
fieldValue673 = x3d.fieldValue()
fieldValue673.setName("bond_set")
fieldValue673.setValue("11.4274 2.4862 0 12.5534 1.427 0")

ProtoInstance672.addFieldValue(fieldValue673)

Group531.addChild(ProtoInstance672)
ProtoInstance674 = x3d.ProtoInstance()
ProtoInstance674.setName("line")
ProtoInstance674.setDEF("b61")
fieldValue675 = x3d.fieldValue()
fieldValue675.setName("bond_set")
fieldValue675.setValue("11.4274 2.4862 0 11.7507 4.0024 0")

ProtoInstance674.addFieldValue(fieldValue675)

Group531.addChild(ProtoInstance674)
ProtoInstance676 = x3d.ProtoInstance()
ProtoInstance676.setName("line")
ProtoInstance676.setDEF("b62")
fieldValue677 = x3d.fieldValue()
fieldValue677.setName("bond_set")
fieldValue677.setValue("10.3237 -4.8943 0 8.8855 -5.5297 0")

ProtoInstance676.addFieldValue(fieldValue677)

Group531.addChild(ProtoInstance676)
ProtoInstance678 = x3d.ProtoInstance()
ProtoInstance678.setName("line")
ProtoInstance678.setDEF("b63")
fieldValue679 = x3d.fieldValue()
fieldValue679.setName("bond_set")
fieldValue679.setValue("10.303700000000001 -4.8943 0 11.5412 -5.8085 0")

ProtoInstance678.addFieldValue(fieldValue679)

Group531.addChild(ProtoInstance678)
ProtoInstance680 = x3d.ProtoInstance()
ProtoInstance680.setName("line")
ProtoInstance680.setDEF("b63_2")
fieldValue681 = x3d.fieldValue()
fieldValue681.setName("bond_set")
fieldValue681.setValue("10.3437 -4.8943 0 11.581199999999999 -5.8085 0")

ProtoInstance680.addFieldValue(fieldValue681)

Group531.addChild(ProtoInstance680)
ProtoInstance682 = x3d.ProtoInstance()
ProtoInstance682.setName("line")
ProtoInstance682.setDEF("b64")
fieldValue683 = x3d.fieldValue()
fieldValue683.setName("bond_set")
fieldValue683.setValue("12.5534 1.427 0 14.0473 1.9064 0")

ProtoInstance682.addFieldValue(fieldValue683)

Group531.addChild(ProtoInstance682)
ProtoInstance684 = x3d.ProtoInstance()
ProtoInstance684.setName("line")
ProtoInstance684.setDEF("b65")
fieldValue685 = x3d.fieldValue()
fieldValue685.setName("bond_set")
fieldValue685.setValue("8.8655 -5.5297 0 8.6983 -7.0794 0")

ProtoInstance684.addFieldValue(fieldValue685)

Group531.addChild(ProtoInstance684)
ProtoInstance686 = x3d.ProtoInstance()
ProtoInstance686.setName("line")
ProtoInstance686.setDEF("b65_2")
fieldValue687 = x3d.fieldValue()
fieldValue687.setName("bond_set")
fieldValue687.setValue("8.9055 -5.5297 0 8.738299999999999 -7.0794 0")

ProtoInstance686.addFieldValue(fieldValue687)

Group531.addChild(ProtoInstance686)
ProtoInstance688 = x3d.ProtoInstance()
ProtoInstance688.setName("line")
ProtoInstance688.setDEF("b66")
fieldValue689 = x3d.fieldValue()
fieldValue689.setName("bond_set")
fieldValue689.setValue("11.5612 -5.8085 0 11.3939 -7.347 0")

ProtoInstance688.addFieldValue(fieldValue689)

Group531.addChild(ProtoInstance688)
ProtoInstance690 = x3d.ProtoInstance()
ProtoInstance690.setName("line")
ProtoInstance690.setDEF("b67")
fieldValue691 = x3d.fieldValue()
fieldValue691.setName("bond_set")
fieldValue691.setValue("8.7183 -7.0794 0 9.9892 -7.9824 0")

ProtoInstance690.addFieldValue(fieldValue691)

Group531.addChild(ProtoInstance690)
ProtoInstance692 = x3d.ProtoInstance()
ProtoInstance692.setName("line")
ProtoInstance692.setDEF("b68")
fieldValue693 = x3d.fieldValue()
fieldValue693.setName("bond_set")
fieldValue693.setValue("9.9892 -7.9824 0 9.7885 -9.5321 0")

ProtoInstance692.addFieldValue(fieldValue693)

Group531.addChild(ProtoInstance692)
ProtoInstance694 = x3d.ProtoInstance()
ProtoInstance694.setName("line")
ProtoInstance694.setDEF("b69")
fieldValue695 = x3d.fieldValue()
fieldValue695.setName("bond_set")
fieldValue695.setValue("-3.9355 3.5341 0 -2.5753 4.3034 0")

ProtoInstance694.addFieldValue(fieldValue695)

Group531.addChild(ProtoInstance694)
ProtoInstance696 = x3d.ProtoInstance()
ProtoInstance696.setName("line")
ProtoInstance696.setDEF("b70")
fieldValue697 = x3d.fieldValue()
fieldValue697.setName("bond_set")
fieldValue697.setValue("9.9335 -1.0591 0 10.1787 0.4682 0")

ProtoInstance696.addFieldValue(fieldValue697)

Group531.addChild(ProtoInstance696)
ProtoInstance698 = x3d.ProtoInstance()
ProtoInstance698.setName("line")
ProtoInstance698.setDEF("b71")
fieldValue699 = x3d.fieldValue()
fieldValue699.setName("bond_set")
fieldValue699.setValue("11.3739 -7.347 0 9.9692 -7.9824 0")

ProtoInstance698.addFieldValue(fieldValue699)

Group531.addChild(ProtoInstance698)
ProtoInstance700 = x3d.ProtoInstance()
ProtoInstance700.setName("line")
ProtoInstance700.setDEF("b71_2")
fieldValue701 = x3d.fieldValue()
fieldValue701.setName("bond_set")
fieldValue701.setValue("11.4139 -7.347 0 10.0092 -7.9824 0")

ProtoInstance700.addFieldValue(fieldValue701)

Group531.addChild(ProtoInstance700)

Scene19.addChild(Group531)

X3D0.setScene(Scene19)
X3D0.toFileX3D("../data/Oxytocin.new.graalpy.x3d")
X3D0.toFileJSON("../data/Oxytocin.new.graalpy.x3dj")
