package net.coderextreme.x3d_code.www_web3d_org.x3d.content.examples.Basic.development;
import org.web3d.x3d.jsail.*;
import org.web3d.x3d.jsail.CADGeometry.*;
import org.web3d.x3d.jsail.Core.*;
import org.web3d.x3d.jsail.CubeMapTexturing.*;
import org.web3d.x3d.jsail.DIS.*;
import org.web3d.x3d.jsail.EnvironmentalEffects.*;
import org.web3d.x3d.jsail.EnvironmentalSensor.*;
import org.web3d.x3d.jsail.EventUtilities.*;
import org.web3d.x3d.jsail.Followers.*;
import org.web3d.x3d.jsail.Geometry2D.*;
import org.web3d.x3d.jsail.Geometry3D.*;
import org.web3d.x3d.jsail.Geospatial.*;
import org.web3d.x3d.jsail.Grouping.*;
import org.web3d.x3d.jsail.HAnim.*;
import org.web3d.x3d.jsail.Interpolation.*;
import org.web3d.x3d.jsail.KeyDeviceSensor.*;
import org.web3d.x3d.jsail.Layering.*;
import org.web3d.x3d.jsail.Layout.*;
import org.web3d.x3d.jsail.Lighting.*;
import org.web3d.x3d.jsail.NURBS.*;
import org.web3d.x3d.jsail.Navigation.*;
import org.web3d.x3d.jsail.Networking.*;
import org.web3d.x3d.jsail.ParticleSystems.*;
import org.web3d.x3d.jsail.Picking.*;
import org.web3d.x3d.jsail.PointingDeviceSensor.*;
import org.web3d.x3d.jsail.Rendering.*;
import org.web3d.x3d.jsail.RigidBodyPhysics.*;
import org.web3d.x3d.jsail.Scripting.*;
import org.web3d.x3d.jsail.Shaders.*;
import org.web3d.x3d.jsail.Shape.*;
import org.web3d.x3d.jsail.Sound.*;
import org.web3d.x3d.jsail.Text.*;
import org.web3d.x3d.jsail.Texturing3D.*;
import org.web3d.x3d.jsail.Texturing.*;
import org.web3d.x3d.jsail.Time.*;
import org.web3d.x3d.jsail.VolumeRendering.*;
import org.web3d.x3d.jsail.fields.*;
import org.web3d.x3d.sai.*;
import org.web3d.x3d.sai.CADGeometry.*;
import org.web3d.x3d.sai.Core.*;
import org.web3d.x3d.sai.CubeMapTexturing.*;
import org.web3d.x3d.sai.DIS.*;
import org.web3d.x3d.sai.EnvironmentalEffects.*;
import org.web3d.x3d.sai.EnvironmentalSensor.*;
import org.web3d.x3d.sai.EventUtilities.*;
import org.web3d.x3d.sai.Followers.*;
import org.web3d.x3d.sai.Geometry2D.*;
import org.web3d.x3d.sai.Geometry3D.*;
import org.web3d.x3d.sai.Geospatial.*;
import org.web3d.x3d.sai.Grouping.*;
import org.web3d.x3d.sai.HAnim.*;
import org.web3d.x3d.sai.Interpolation.*;
import org.web3d.x3d.sai.KeyDeviceSensor.*;
import org.web3d.x3d.sai.Layering.*;
import org.web3d.x3d.sai.Layout.*;
import org.web3d.x3d.sai.Lighting.*;
import org.web3d.x3d.sai.NURBS.*;
import org.web3d.x3d.sai.Navigation.*;
import org.web3d.x3d.sai.Networking.*;
import org.web3d.x3d.sai.ParticleSystems.*;
import org.web3d.x3d.sai.Picking.*;
import org.web3d.x3d.sai.PointingDeviceSensor.*;
import org.web3d.x3d.sai.Rendering.*;
import org.web3d.x3d.sai.RigidBodyPhysics.*;
import org.web3d.x3d.sai.Scripting.*;
import org.web3d.x3d.sai.Shaders.*;
import org.web3d.x3d.sai.Shape.*;
import org.web3d.x3d.sai.Sound.*;
import org.web3d.x3d.sai.Text.*;
import org.web3d.x3d.sai.Texturing3D.*;
import org.web3d.x3d.sai.Texturing.*;
import org.web3d.x3d.sai.Time.*;
import org.web3d.x3d.sai.VolumeRendering.*;
public class KeySensorActivationKeySwitchTestInterchange {
  public static void main(String[] args) {
    ConfigurationProperties.setXsltEngine(ConfigurationProperties.XSLT_ENGINE_NATIVE_JAVA);
    ConfigurationProperties.setDeleteIntermediateFiles(false);
    new KeySensorActivationKeySwitchTestInterchange().initialize().toFileJSON("../x3d_code/www_web3d_org/x3d/content/examples/Basic/development/KeySensorActivationKeySwitchTestInterchange.new.json");
    }
    public X3DObject initialize() {
      X3DObject X3D0 =  new X3DObject().setProfile("Interchange").setVersion("3.0")
      .setHead(new headObject()
        .addComments(new CommentsBlock("component Core level 2 in support of ExternProtoDeclare hack for KeySensor"))
        .addComponent(new componentObject().setName("Core").setLevel(2))
        .addMeta(new metaObject().setName("title").setContent("KeySensorActivationKeySwitchTestInterchange.x3d"))
        .addMeta(new metaObject().setName("description").setContent("A simple scene to show KeySensor functionality using Core Profile."))
        .addMeta(new metaObject().setName("creator").setContent("Mr. Philip Sand Hansel II, mr.phillip@home.com"))
        .addMeta(new metaObject().setName("translator").setContent("Don Brutzman"))
        .addMeta(new metaObject().setName("created").setContent("8 July 2001"))
        .addMeta(new metaObject().setName("modified").setContent("20 October 2019"))
        .addMeta(new metaObject().setName("warning").setContent("This won't work because there is no KeySensor implementation yet! Prototype script (written in Java) or native node support for KeySensor is needed."))
        .addMeta(new metaObject().setName("warning").setContent("enabled needs to be changed to exposedField once supported by Script capabilities"))
        .addMeta(new metaObject().setName("reference").setContent("https://www.web3d.org/x3d/specification-2000july/part1/nodesDef.html#KeySensor"))
        .addMeta(new metaObject().setName("reference").setContent("https://www.web3d.org/x3d/sai/javadoc/org/web3d/x3d/sai/Core/KeySensor.html"))
        .addMeta(new metaObject().setName("subject").setContent("KeySensor Core Profile"))
        .addMeta(new metaObject().setName("identifier").setContent("https://www.web3d.org/x3d/content/examples/Basic/development/KeySensorActivationKeySwitchTestInterchange.x3d"))
        .addMeta(new metaObject().setName("reference").setContent("https://www.web3d.org/x3d/content/examples/Basic/ConformanceNist/Sensors/Keyboard/KeySensorActivationKeySwitchTestInterchange.x3d"))
        .addMeta(new metaObject().setName("generator").setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit"))
        .addMeta(new metaObject().setName("license").setContent("../license.html")))
      .setScene(new SceneObject()
        .addChild(new WorldInfoObject().setTitle("KeySensorActivationKeySwitchTestInterchange.x3d"))
        .addChild(new ExternProtoDeclareObject().setName("KeySensor").setUrl(new MFStringObject(new MFString0().getArray()))
          .addField(new fieldObject().setType("SFBool").setName("altKey").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY))
          .addField(new fieldObject().setType("SFInt32").setName("keyPress").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY))
          .addField(new fieldObject().setType("SFBool").setName("set_enabled").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY))
          .addField(new fieldObject().setType("SFInt32").setName("keyRelease").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY))
          .addField(new fieldObject().setType("SFBool").setName("enabled").setAccessType(fieldObject.ACCESSTYPE_INITIALIZEONLY))
          .addField(new fieldObject().setType("SFBool").setName("shiftKey").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY))
          .addField(new fieldObject().setType("SFInt32").setName("actionKeyRelease").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY))
          .addField(new fieldObject().setType("SFBool").setName("isActive").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY))
          .addField(new fieldObject().setType("SFBool").setName("enabled_changed").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY))
          .addField(new fieldObject().setType("SFInt32").setName("actionKeyPress").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY))
          .addField(new fieldObject().setType("SFBool").setName("controlKey").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY)))
        .addChild(new ViewpointObject().setDEF("Viewpoint1").setDescription("Viewpoint1").setFieldOfView(0.79f).setPosition(new float[] {0f,0f,30f}))
        .addChild(new KeySensorObject().setDEF("SingleKeySensor").setEnabled(false))
        .addChild(new ShapeObject().setDEF("A")
          .setAppearance(new AppearanceObject()
            .setMaterial(new MaterialObject().setDEF("red").setDiffuseColor(new float[] {1f,0f,0f}))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setDEF("slab").setCoordIndex(new MFInt32Object(new MFInt321().getArray())).setCreaseAngle(0.5f)
            .setCoord(new CoordinateObject().setPoint(new MFVec3fObject(new MFVec3f2().getArray())))))
        .addChild(new ShapeObject().setDEF("B")
          .setAppearance(new AppearanceObject()
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,0,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("C")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,255,255,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("D")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("E")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("F")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("G")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,255,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,255,255,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("H")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("I")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,255,255,255,255,255,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,255,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("J")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,255,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("K")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,255,0,0,0,0,0,255,0,255,0,0,0,0,0,255,255,0,0,0,0,0,0,255,0,255,0,0,0,0,0,255,0,0,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("L")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("M")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,255,0,255,0,0,0,255,0,255,0,255,0,0,0,0,255,0,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("N")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,255,255,0,0,0,0,255,255,0,255,0,0,0,0,255,0,0,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("O")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("P")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,255,255,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Q")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,255,0,0,0,0,255,255,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,0,255,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("R")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,255,0,0,0,0,0,255,255,0,0,0,0,0,0,255,0,255,0,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("S")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,255,255,0,0,0,0,0,255,0,0,0,0,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("T")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,255,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("U")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("V")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,255,0,255,0,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("W")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,0,255,0,0,0,0,255,0,255,0,255,0,0,0,255,0,255,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("X")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,255,0,0,0,255,0,0,0,0,255,0,255,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,255,0,255,0,0,0,0,255,0,0,0,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Y")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,255,0,255,0,0,0,0,255,0,0,0,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Z")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0,0,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("One")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Two")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Three")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Four")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,255,255,255,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Five")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,255,255,255,0,0,0,0,0,255,0,0,0,0,0,0,0,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Six")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,255,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,255,255,0,0,0,0,0,255,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Seven")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,255,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Eight")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,255,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,0,255,255,0,0,0,0,0,255,0,0,255,0,0,0,0,0,255,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Nine")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,0,0,255,0,0,0,0,0,255,255,255,0,0,0,0,255,0,0,255,0,0,0,0,0,255,255,255,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Zero")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,255,0,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,255,0,0,255,0,0,0,0,0,255,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Colon")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,255,0,0,0,0,0,0,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,255,255,0,0,0,0,0,0,255,255,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Comma")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,255,0,0,0,0,0,0,255,255,0,0,0,0,0,0,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new ShapeObject().setDEF("Dot")
          .setAppearance(new AppearanceObject()
            .setTextureTransform(new TextureTransformObject().setScale(new float[] {0.75f,1f}))
            .setMaterial(new MaterialObject().setUSE("red"))
            .setTexture(new PixelTextureObject().setImage(new int[] {8,8,1,0,0,0,0,0,0,0,0,0,0,255,255,0,0,0,0,0,0,255,255,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0})))
          .setGeometry(new IndexedFaceSetObject().setUSE("slab")))
        .addChild(new GroupObject()
          .addChild(new TransformObject().setTranslation(new float[] {0f,5f,0f})
            .addChild(new TransformObject().setTranslation(new float[] {-12f,0f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {-11f,0f,0f})
              .addChild(new ShapeObject().setUSE("O")))
            .addChild(new TransformObject().setTranslation(new float[] {-10f,0f,0f})
              .addChild(new ShapeObject().setUSE("U")))
            .addChild(new TransformObject().setTranslation(new float[] {-9f,0f,0f})
              .addChild(new ShapeObject().setUSE("C")))
            .addChild(new TransformObject().setTranslation(new float[] {-8f,0f,0f})
              .addChild(new ShapeObject().setUSE("H")))
            .addChild(new TransformObject().setTranslation(new float[] {-6f,0f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {-5f,0f,0f})
              .addChild(new ShapeObject().setUSE("H")))
            .addChild(new TransformObject().setTranslation(new float[] {-4f,0f,0f})
              .addChild(new ShapeObject().setUSE("I")))
            .addChild(new TransformObject().setTranslation(new float[] {-3f,0f,0f})
              .addChild(new ShapeObject().setUSE("S")))
            .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject()
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
              .addChild(new ShapeObject().setUSE("X")))
            .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {4f,0f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {5f,0f,0f})
              .addChild(new ShapeObject().setUSE("O")))
            .addChild(new TransformObject().setTranslation(new float[] {7f,0f,0f})
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {8f,0f,0f})
              .addChild(new ShapeObject().setUSE("N")))
            .addChild(new TransformObject().setTranslation(new float[] {9f,0f,0f})
              .addChild(new ShapeObject().setUSE("A")))
            .addChild(new TransformObject().setTranslation(new float[] {10f,0f,0f})
              .addChild(new ShapeObject().setUSE("B")))
            .addChild(new TransformObject().setTranslation(new float[] {11f,0f,0f})
              .addChild(new ShapeObject().setUSE("L")))
            .addChild(new TransformObject().setTranslation(new float[] {12f,0f,0f})
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {-15f,-1f,0f})
              .addChild(new ShapeObject().setUSE("K")))
            .addChild(new TransformObject().setTranslation(new float[] {-14f,-1f,0f})
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {-13f,-1f,0f})
              .addChild(new ShapeObject().setUSE("Y")))
            .addChild(new TransformObject().setTranslation(new float[] {-12f,-1f,0f})
              .addChild(new ShapeObject().setUSE("S")))
            .addChild(new TransformObject().setTranslation(new float[] {-11f,-1f,0f})
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {-10f,-1f,0f})
              .addChild(new ShapeObject().setUSE("N")))
            .addChild(new TransformObject().setTranslation(new float[] {-9f,-1f,0f})
              .addChild(new ShapeObject().setUSE("S")))
            .addChild(new TransformObject().setTranslation(new float[] {-8f,-1f,0f})
              .addChild(new ShapeObject().setUSE("O")))
            .addChild(new TransformObject().setTranslation(new float[] {-7f,-1f,0f})
              .addChild(new ShapeObject().setUSE("R")))
            .addChild(new TransformObject().setTranslation(new float[] {-5f,-1f,0f})
              .addChild(new ShapeObject().setUSE("A")))
            .addChild(new TransformObject().setTranslation(new float[] {-4f,-1f,0f})
              .addChild(new ShapeObject().setUSE("C")))
            .addChild(new TransformObject().setTranslation(new float[] {-3f,-1f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {-2f,-1f,0f})
              .addChild(new ShapeObject().setUSE("I")))
            .addChild(new TransformObject().setTranslation(new float[] {-1f,-1f,0f})
              .addChild(new ShapeObject().setUSE("V")))
            .addChild(new TransformObject().setTranslation(new float[] {0f,-1f,0f})
              .addChild(new ShapeObject().setUSE("A")))
            .addChild(new TransformObject().setTranslation(new float[] {1f,-1f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {2f,-1f,0f})
              .addChild(new ShapeObject().setUSE("I")))
            .addChild(new TransformObject().setTranslation(new float[] {3f,-1f,0f})
              .addChild(new ShapeObject().setUSE("O")))
            .addChild(new TransformObject().setTranslation(new float[] {4f,-1f,0f})
              .addChild(new ShapeObject().setUSE("N")))
            .addChild(new TransformObject().setTranslation(new float[] {6f,-1f,0f})
              .addChild(new ShapeObject().setUSE("K")))
            .addChild(new TransformObject().setTranslation(new float[] {7f,-1f,0f})
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {8f,-1f,0f})
              .addChild(new ShapeObject().setUSE("Y")))
            .addChild(new TransformObject().setTranslation(new float[] {9f,-1f,0f})
              .addChild(new ShapeObject().setUSE("S")))
            .addChild(new TransformObject().setTranslation(new float[] {10f,-1f,0f})
              .addChild(new ShapeObject().setUSE("Comma")))
            .addChild(new TransformObject().setTranslation(new float[] {12f,-1f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {13f,-1f,0f})
              .addChild(new ShapeObject().setUSE("H")))
            .addChild(new TransformObject().setTranslation(new float[] {14f,-1f,0f})
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {15f,-1f,0f})
              .addChild(new ShapeObject().setUSE("N")))
            .addChild(new TransformObject().setTranslation(new float[] {-15f,-2f,0f})
              .addChild(new ShapeObject().setUSE("P")))
            .addChild(new TransformObject().setTranslation(new float[] {-14f,-2f,0f})
              .addChild(new ShapeObject().setUSE("R")))
            .addChild(new TransformObject().setTranslation(new float[] {-13f,-2f,0f})
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {-12f,-2f,0f})
              .addChild(new ShapeObject().setUSE("S")))
            .addChild(new TransformObject().setTranslation(new float[] {-11f,-2f,0f})
              .addChild(new ShapeObject().setUSE("S")))
            .addChild(new TransformObject().setTranslation(new float[] {-9f,-2f,0f})
              .addChild(new ShapeObject().setUSE("A")))
            .addChild(new TransformObject().setTranslation(new float[] {-8f,-2f,0f})
              .addChild(new ShapeObject().setUSE("C")))
            .addChild(new TransformObject().setTranslation(new float[] {-7f,-2f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {-6f,-2f,0f})
              .addChild(new ShapeObject().setUSE("I")))
            .addChild(new TransformObject().setTranslation(new float[] {-5f,-2f,0f})
              .addChild(new ShapeObject().setUSE("V")))
            .addChild(new TransformObject().setTranslation(new float[] {-4f,-2f,0f})
              .addChild(new ShapeObject().setUSE("A")))
            .addChild(new TransformObject().setTranslation(new float[] {-3f,-2f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {-2f,-2f,0f})
              .addChild(new ShapeObject().setUSE("I")))
            .addChild(new TransformObject().setTranslation(new float[] {-1f,-2f,0f})
              .addChild(new ShapeObject().setUSE("O")))
            .addChild(new TransformObject().setTranslation(new float[] {0f,-2f,0f})
              .addChild(new ShapeObject().setUSE("N")))
            .addChild(new TransformObject().setTranslation(new float[] {2f,-2f,0f})
              .addChild(new ShapeObject().setUSE("K")))
            .addChild(new TransformObject().setTranslation(new float[] {3f,-2f,0f})
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {4f,-2f,0f})
              .addChild(new ShapeObject().setUSE("Y")))
            .addChild(new TransformObject().setTranslation(new float[] {5f,-2f,0f})
              .addChild(new ShapeObject().setUSE("S")))
            .addChild(new TransformObject().setTranslation(new float[] {7f,-2f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {8f,-2f,0f})
              .addChild(new ShapeObject().setUSE("O")))
            .addChild(new TransformObject().setTranslation(new float[] {10f,-2f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {11f,-2f,0f})
              .addChild(new ShapeObject().setUSE("E")))
            .addChild(new TransformObject().setTranslation(new float[] {12f,-2f,0f})
              .addChild(new ShapeObject().setUSE("S")))
            .addChild(new TransformObject().setTranslation(new float[] {13f,-2f,0f})
              .addChild(new ShapeObject().setUSE("T")))
            .addChild(new TransformObject().setTranslation(new float[] {14f,-2f,0f})
              .addChild(new ShapeObject().setUSE("Dot"))))
          .addChild(new SwitchObject().setDEF("ActivationKeyMessageSwitch").setWhichChoice(0)
            .addChild(new TransformObject().setDEF("Nokeypress").setTranslation(new float[] {-2f,0f,0f})
              .addChild(new TransformObject().setTranslation(new float[] {-13f,-4f,0f})
                .addChild(new ShapeObject().setUSE("N")))
              .addChild(new TransformObject().setTranslation(new float[] {-12f,-4f,0f})
                .addChild(new ShapeObject().setUSE("O")))
              .addChild(new TransformObject().setTranslation(new float[] {-10f,-4f,0f})
                .addChild(new ShapeObject().setUSE("A")))
              .addChild(new TransformObject().setTranslation(new float[] {-9f,-4f,0f})
                .addChild(new ShapeObject().setUSE("C")))
              .addChild(new TransformObject().setTranslation(new float[] {-8f,-4f,0f})
                .addChild(new ShapeObject().setUSE("T")))
              .addChild(new TransformObject().setTranslation(new float[] {-7f,-4f,0f})
                .addChild(new ShapeObject().setUSE("I")))
              .addChild(new TransformObject().setTranslation(new float[] {-6f,-4f,0f})
                .addChild(new ShapeObject().setUSE("V")))
              .addChild(new TransformObject().setTranslation(new float[] {-5f,-4f,0f})
                .addChild(new ShapeObject().setUSE("A")))
              .addChild(new TransformObject().setTranslation(new float[] {-4f,-4f,0f})
                .addChild(new ShapeObject().setUSE("T")))
              .addChild(new TransformObject().setTranslation(new float[] {-3f,-4f,0f})
                .addChild(new ShapeObject().setUSE("I")))
              .addChild(new TransformObject().setTranslation(new float[] {-2f,-4f,0f})
                .addChild(new ShapeObject().setUSE("O")))
              .addChild(new TransformObject().setTranslation(new float[] {-1f,-4f,0f})
                .addChild(new ShapeObject().setUSE("N")))
              .addChild(new TransformObject().setTranslation(new float[] {1f,-4f,0f})
                .addChild(new ShapeObject().setUSE("K")))
              .addChild(new TransformObject().setTranslation(new float[] {2f,-4f,0f})
                .addChild(new ShapeObject().setUSE("E")))
              .addChild(new TransformObject().setTranslation(new float[] {3f,-4f,0f})
                .addChild(new ShapeObject().setUSE("Y")))
              .addChild(new TransformObject().setTranslation(new float[] {4f,-4f,0f})
                .addChild(new ShapeObject().setUSE("P")))
              .addChild(new TransformObject().setTranslation(new float[] {5f,-4f,0f})
                .addChild(new ShapeObject().setUSE("R")))
              .addChild(new TransformObject().setTranslation(new float[] {6f,-4f,0f})
                .addChild(new ShapeObject().setUSE("E")))
              .addChild(new TransformObject().setTranslation(new float[] {7f,-4f,0f})
                .addChild(new ShapeObject().setUSE("S")))
              .addChild(new TransformObject().setTranslation(new float[] {8f,-4f,0f})
                .addChild(new ShapeObject().setUSE("S")))
              .addChild(new TransformObject().setTranslation(new float[] {10f,-4f,0f})
                .addChild(new ShapeObject().setUSE("S")))
              .addChild(new TransformObject().setTranslation(new float[] {11f,-4f,0f})
                .addChild(new ShapeObject().setUSE("E")))
              .addChild(new TransformObject().setTranslation(new float[] {12f,-4f,0f})
                .addChild(new ShapeObject().setUSE("N")))
              .addChild(new TransformObject().setTranslation(new float[] {13f,-4f,0f})
                .addChild(new ShapeObject().setUSE("S")))
              .addChild(new TransformObject().setTranslation(new float[] {14f,-4f,0f})
                .addChild(new ShapeObject().setUSE("E")))
              .addChild(new TransformObject().setTranslation(new float[] {15f,-4f,0f})
                .addChild(new ShapeObject().setUSE("D")))
              .addChild(new TransformObject().setTranslation(new float[] {16f,-4f,0f})
                .addChild(new ShapeObject().setUSE("Dot")))
              .addChild(new TransformObject().setTranslation(new float[] {17f,-4f,0f})
                .addChild(new ShapeObject().setUSE("Dot"))))
            .addChild(new TransformObject().setDEF("Functions").setTranslation(new float[] {0f,-6f,0f})
              .addChild(new TransformObject().setDEF("F1")
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("One"))))
              .addChild(new TransformObject().setDEF("F2").setTranslation(new float[] {0f,-1f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("Two"))))
              .addChild(new TransformObject().setDEF("F3").setTranslation(new float[] {0f,-2f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("Three"))))
              .addChild(new TransformObject().setDEF("F4").setTranslation(new float[] {0f,-3f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("Four"))))
              .addChild(new TransformObject().setDEF("F5").setTranslation(new float[] {0f,-4f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("Five"))))
              .addChild(new TransformObject().setDEF("F6").setTranslation(new float[] {0f,-5f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("Six"))))
              .addChild(new TransformObject().setDEF("F7").setTranslation(new float[] {0f,-6f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("Seven"))))
              .addChild(new TransformObject().setDEF("F8").setTranslation(new float[] {0f,-7f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("Eight"))))
              .addChild(new TransformObject().setDEF("F9").setTranslation(new float[] {0f,-8f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("Nine"))))
              .addChild(new TransformObject().setDEF("F10").setTranslation(new float[] {0f,-9f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Zero"))))
              .addChild(new TransformObject().setDEF("F11").setTranslation(new float[] {0f,-10f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("One"))))
              .addChild(new TransformObject().setDEF("F12").setTranslation(new float[] {0f,-11f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Two"))))
              .addChild(new TransformObject().setDEF("Home").setTranslation(new float[] {0f,-12f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-3f,0f,0f})
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {-2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Three")))
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Colon")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("H")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("O")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("M")))
                .addChild(new TransformObject().setTranslation(new float[] {3f,0f,0f})
                  .addChild(new ShapeObject().setUSE("E"))))
              .addChild(new TransformObject().setDEF("End").setTranslation(new float[] {0f,-13f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-3f,0f,0f})
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {-2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Four")))
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Colon")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("E")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("N")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("D"))))
              .addChild(new TransformObject().setDEF("Left").setTranslation(new float[] {0f,-14f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-3f,0f,0f})
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {-2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Five")))
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Colon")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("L")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("E")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("F")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("T"))))
              .addChild(new TransformObject().setDEF("Right").setTranslation(new float[] {0f,-15f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-3f,0f,0f})
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {-2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Six")))
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Colon")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("R")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("I")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("G")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("H")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("T"))))
              .addChild(new TransformObject().setDEF("Up").setTranslation(new float[] {0f,-16f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-3f,0f,0f})
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {-2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Seven")))
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Colon")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("U")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("P"))))
              .addChild(new TransformObject().setDEF("Down").setTranslation(new float[] {0f,-17f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-3f,0f,0f})
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {-2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Eight")))
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Colon")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("D")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("O")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("W")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("N"))))
              .addChild(new TransformObject().setDEF("PGUP").setTranslation(new float[] {0f,-18f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-3f,0f,0f})
                  .addChild(new ShapeObject().setUSE("One")))
                .addChild(new TransformObject().setTranslation(new float[] {-2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Nine")))
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Colon")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("P")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("G")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("U")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("P"))))
              .addChild(new TransformObject().setDEF("PGDN").setTranslation(new float[] {0f,-19f,0f})
                .addChild(new TransformObject().setTranslation(new float[] {-3f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Two")))
                .addChild(new TransformObject().setTranslation(new float[] {-2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Zero")))
                .addChild(new TransformObject().setTranslation(new float[] {-1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("Colon")))
                .addChild(new TransformObject()
                  .addChild(new ShapeObject().setUSE("P")))
                .addChild(new TransformObject().setTranslation(new float[] {1f,0f,0f})
                  .addChild(new ShapeObject().setUSE("G")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("D")))
                .addChild(new TransformObject().setTranslation(new float[] {2f,0f,0f})
                  .addChild(new ShapeObject().setUSE("N")))))))
        .addChild(new ROUTEObject().setFromField("actionKeyPress").setFromNode("SingleKeySensor").setToField("whichChoice").setToNode("ActivationKeyMessageSwitch")))      ;
    return X3D0;
    }
protected class MFString0 {
  protected MFStringObject getArray() {
    return new MFStringObject(new java.lang.String[] {"KeySensorActivationKeySwitchTest.wrl#KeySensor","https://www.web3d.org/x3d/content/examples/Basic/development/KeySensorActivationKeySwitchTest.wrl#KeySensor","KeySensorActivationKeySwitchTest.x3d#KeySensor","https://www.web3d.org/x3d/content/examples/Basic/development/KeySensorActivationKeySwitchTest.x3d#KeySensor"});
  }
}
protected class MFInt321 {
  protected MFInt32Object getArray() {
    return new MFInt32Object(new int[] {0,1,2,-1,0,2,3,-1});
  }
}
protected class MFVec3f2 {
  protected MFVec3fObject getArray() {
    return new MFVec3fObject(new float[] {-0.5f,0.5f,0.5f,-0.5f,-0.5f,0.5f,0.5f,-0.5f,0.5f,0.5f,0.5f,0.5f});
  }
}
}
