from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("abox.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/abox.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("a box")
head1.addMeta(meta6)
X3D0.setHead(head1)
Scene7 = SceneObject()
ProtoDeclare8 = ProtoDeclareObject().setName("anyShape")
ProtoInterface9 = ProtoInterfaceObject()
field10 = fieldObject().setType(fieldObject.TYPE_MFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Shape11 = ShapeObject()
Sphere12 = SphereObject()
Shape11.setGeometry(Sphere12)
field10.addChild(Shape11)
ProtoInterface9.addField(field10)
ProtoDeclare8.setProtoInterface(ProtoInterface9)
ProtoBody13 = ProtoBodyObject()
Transform14 = TransformObject()
IS15 = ISObject()
connect16 = connectObject().setNodeField("children").setProtoField("myShape")
IS15.addConnect(connect16)
Transform14.setIS(IS15)
ProtoBody13.addChild(Transform14)
ProtoDeclare8.setProtoBody(ProtoBody13)
Scene7.addChild(ProtoDeclare8)
ProtoDeclare17 = ProtoDeclareObject().setName("one")
ProtoInterface18 = ProtoInterfaceObject()
field19 = fieldObject().setType(fieldObject.TYPE_MFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Shape20 = ShapeObject()
Cylinder21 = CylinderObject()
Shape20.setGeometry(Cylinder21)
field19.addChild(Shape20)
ProtoInterface18.addField(field19)
ProtoDeclare17.setProtoInterface(ProtoInterface18)
ProtoBody22 = ProtoBodyObject()
Transform23 = TransformObject()
ProtoInstance24 = ProtoInstanceObject().setName("anyShape")
IS25 = ISObject()
connect26 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS25.addConnect(connect26)
ProtoInstance24.setIS(IS25)
Transform23.addChild(ProtoInstance24)
ProtoBody22.addChild(Transform23)
ProtoDeclare17.setProtoBody(ProtoBody22)
Scene7.addChild(ProtoDeclare17)
ProtoInstance27 = ProtoInstanceObject().setName("one")
fieldValue28 = fieldValueObject().setName("myShape")
Shape29 = ShapeObject()
Box30 = BoxObject().setSize([1,1,1])
Shape29.setGeometry(Box30)
fieldValue28.addChild(Shape29)
ProtoInstance27.addFieldValue(fieldValue28)
Scene7.addChild(ProtoInstance27)
X3D0.setScene(Scene7)

X3D0.toFileX3D("../new/json/abox.new.x3d")
