from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("rubik.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/rubik.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("a kind of rubik cube with spheres")
head1.addMeta(meta6)
X3D0.setHead(head1)
Scene7 = SceneObject()
NavigationInfo8 = NavigationInfoObject().setType(["EXAMINE"])
Scene7.addChild(NavigationInfo8)
Viewpoint9 = ViewpointObject().setDescription("Rubiks Cube").setPosition([0,0,12])
Scene7.addChild(Viewpoint9)
ProtoDeclare10 = ProtoDeclareObject().setName("sphere")
ProtoInterface11 = ProtoInterfaceObject()
field12 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("xtranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface11.addField(field12)
ProtoDeclare10.setProtoInterface(ProtoInterface11)
ProtoBody13 = ProtoBodyObject()
Transform14 = TransformObject()
IS15 = ISObject()
connect16 = connectObject().setNodeField("translation").setProtoField("xtranslation")
IS15.addConnect(connect16)
Transform14.setIS(IS15)
Shape17 = ShapeObject()
Sphere18 = SphereObject()
Shape17.setGeometry(Sphere18)
Appearance19 = AppearanceObject()
Material20 = MaterialObject().setDiffuseColor([1,1,1])
Appearance19.setMaterial(Material20)
Shape17.setAppearance(Appearance19)
Transform14.addChild(Shape17)
ProtoBody13.addChild(Transform14)
ProtoDeclare10.setProtoBody(ProtoBody13)
Scene7.addChild(ProtoDeclare10)
ProtoDeclare21 = ProtoDeclareObject().setName("three")
ProtoInterface22 = ProtoInterfaceObject()
field23 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ytranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface22.addField(field23)
ProtoDeclare21.setProtoInterface(ProtoInterface22)
ProtoBody24 = ProtoBodyObject()
Transform25 = TransformObject()
IS26 = ISObject()
connect27 = connectObject().setNodeField("translation").setProtoField("ytranslation")
IS26.addConnect(connect27)
Transform25.setIS(IS26)
ProtoInstance28 = ProtoInstanceObject().setName("sphere")
fieldValue29 = fieldValueObject().setName("xtranslation").setValue("0 0 0")
ProtoInstance28.addFieldValue(fieldValue29)
Transform25.addChild(ProtoInstance28)
ProtoInstance30 = ProtoInstanceObject().setName("sphere")
fieldValue31 = fieldValueObject().setName("xtranslation").setValue("2 0 0")
ProtoInstance30.addFieldValue(fieldValue31)
Transform25.addChild(ProtoInstance30)
ProtoInstance32 = ProtoInstanceObject().setName("sphere")
fieldValue33 = fieldValueObject().setName("xtranslation").setValue("-2 0 0")
ProtoInstance32.addFieldValue(fieldValue33)
Transform25.addChild(ProtoInstance32)
ProtoBody24.addChild(Transform25)
ProtoDeclare21.setProtoBody(ProtoBody24)
Scene7.addChild(ProtoDeclare21)
ProtoDeclare34 = ProtoDeclareObject().setName("nine")
ProtoInterface35 = ProtoInterfaceObject()
field36 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ztranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface35.addField(field36)
ProtoDeclare34.setProtoInterface(ProtoInterface35)
ProtoBody37 = ProtoBodyObject()
Transform38 = TransformObject()
IS39 = ISObject()
connect40 = connectObject().setNodeField("translation").setProtoField("ztranslation")
IS39.addConnect(connect40)
Transform38.setIS(IS39)
ProtoInstance41 = ProtoInstanceObject().setName("three")
fieldValue42 = fieldValueObject().setName("ytranslation").setValue("0 0 0")
ProtoInstance41.addFieldValue(fieldValue42)
Transform38.addChild(ProtoInstance41)
ProtoInstance43 = ProtoInstanceObject().setName("three")
fieldValue44 = fieldValueObject().setName("ytranslation").setValue("0 2 0")
ProtoInstance43.addFieldValue(fieldValue44)
Transform38.addChild(ProtoInstance43)
ProtoInstance45 = ProtoInstanceObject().setName("three")
fieldValue46 = fieldValueObject().setName("ytranslation").setValue("0 -2 0")
ProtoInstance45.addFieldValue(fieldValue46)
Transform38.addChild(ProtoInstance45)
ProtoBody37.addChild(Transform38)
ProtoDeclare34.setProtoBody(ProtoBody37)
Scene7.addChild(ProtoDeclare34)
ProtoDeclare47 = ProtoDeclareObject().setName("twentyseven")
ProtoInterface48 = ProtoInterfaceObject()
field49 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ttranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface48.addField(field49)
ProtoDeclare47.setProtoInterface(ProtoInterface48)
ProtoBody50 = ProtoBodyObject()
Transform51 = TransformObject()
IS52 = ISObject()
connect53 = connectObject().setNodeField("translation").setProtoField("ttranslation")
IS52.addConnect(connect53)
Transform51.setIS(IS52)
ProtoInstance54 = ProtoInstanceObject().setName("nine")
fieldValue55 = fieldValueObject().setName("ztranslation").setValue("0 0 0")
ProtoInstance54.addFieldValue(fieldValue55)
Transform51.addChild(ProtoInstance54)
ProtoInstance56 = ProtoInstanceObject().setName("nine")
fieldValue57 = fieldValueObject().setName("ztranslation").setValue("0 0 2")
ProtoInstance56.addFieldValue(fieldValue57)
Transform51.addChild(ProtoInstance56)
ProtoInstance58 = ProtoInstanceObject().setName("nine")
fieldValue59 = fieldValueObject().setName("ztranslation").setValue("0 0 -2")
ProtoInstance58.addFieldValue(fieldValue59)
Transform51.addChild(ProtoInstance58)
ProtoBody50.addChild(Transform51)
ProtoDeclare47.setProtoBody(ProtoBody50)
Scene7.addChild(ProtoDeclare47)
ProtoInstance60 = ProtoInstanceObject().setName("twentyseven")
fieldValue61 = fieldValueObject().setName("ttranslation").setValue("0 0 0")
ProtoInstance60.addFieldValue(fieldValue61)
Scene7.addChild(ProtoInstance60)
X3D0.setScene(Scene7)

X3D0.toFileX3D("rubik.new.x3d")
