load('X3Dautoclass.js');
var ConfigurationProperties = Packages.org.web3d.x3d.jsail.ConfigurationProperties;
ConfigurationProperties.showDefaultAttributes = false;
ConfigurationProperties.xsltEngine = ConfigurationProperties.XSLT_ENGINE_NATIVE_JAVA;
ConfigurationProperties.deleteIntermediateFiles = false;
ConfigurationProperties.setStripTrailingZeroes(true);
ConfigurationProperties.setStripDefaultAttributes(true);
function doubleToFloat(d) {
    if (Float32Array)
	return new Float32Array(d);
}
      var X3D0 =  new X3D().setProfile("Immersive").setVersion("4.0")
      .setHead(new head()
        .addMeta(new meta().setName("title").setContent("CoordinateAxes.x3d"))
        .addMeta(new meta().setName("creator").setContent("Don Brutzman, Byounghyun Yoo"))
        .addMeta(new meta().setName("created").setContent("14 July 2000"))
        .addMeta(new meta().setName("modified").setContent("20 October 2019"))
        .addMeta(new meta().setName("description").setContent("X Y Z axis arrows and labels in X3D coordinate system. See CoordinateAxesExample for use as an Inline coordinate-system reference frame."))
        .addMeta(new meta().setName("reference").setContent("https://X3dGraphics.com/examples/X3dForWebAuthors/Chapter03Grouping/CoordinateAxes.x3d"))
        .addMeta(new meta().setName("reference").setContent("https://X3dGraphics.com/examples/X3dForWebAuthors/Chapter03Grouping/CoordinateAxesNSEW.x3d"))
        .addMeta(new meta().setName("reference").setContent("https://savage.nps.edu/Savage/Tools/Authoring/CoordinateAxes.x3d"))
        .addMeta(new meta().setName("reference").setContent("https://savage.nps.edu/Savage/Tools/Authoring/CoordinateAxesNSEW.x3d"))
        .addMeta(new meta().setName("identifier").setContent("https://X3dGraphics.com/examples/X3dForWebAuthors/Chapter03Grouping/CoordinateAxes.x3d"))
        .addMeta(new meta().setName("generator").setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit"))
        .addMeta(new meta().setName("license").setContent("../license.html")))
      .setScene(new Scene()
        .addChild(new WorldInfo().setTitle("CoordinateAxes.x3d"))
        .addChild(new Collision().setDEF("DoNotCollideWithVisualizationWidget")
          .addComments(new CommentsBlock("Invoke CoordinateAxes in other scenes as an Inline child inside a scaling Transform node, at the topmost level of the scene graph."))
          .addComments(new CommentsBlock("This NavigationInfo allows examine mode and will be overridden by any parent scene."))
          .addComments(new CommentsBlock("Each arrow goes from +1m to -1m to allow linear scaling to fit a scene"))
          .addComments(new CommentsBlock("Note each label rotates about the scene's vertical Y axis for consistency, enabling local orientation by user"))
          .addChild(new Group()
            .addComments(new CommentsBlock("Vertical Y arrow and label"))
            .addChild(new Group().setDEF("ArrowGreen")
              .addChild(new Shape()
                .setGeometry(new Cylinder().setDEF("ArrowCylinder").setRadius(0.025).setTop(false))
                .setAppearance(new Appearance().setDEF("Green")
                  .setMaterial(new Material().setDiffuseColor(Java.to(doubleToFloat([0.1,0.6,0.1]), Java.type("float[]"))).setEmissiveColor(Java.to(doubleToFloat([0.05,0.2,0.05]), Java.type("float[]"))))))
              .addChild(new Transform().setTranslation(Java.to(doubleToFloat([0,1,0]), Java.type("float[]")))
                .addChild(new Shape()
                  .setGeometry(new Cone().setDEF("ArrowCone").setBottomRadius(0.05).setHeight(0.1))
                  .setAppearance(new Appearance().setUSE("Green")))))
            .addChild(new Transform().setTranslation(Java.to(doubleToFloat([0,1.08,0]), Java.type("float[]")))
              .addChild(new Billboard()
                .addChild(new Shape()
                  .setAppearance(new Appearance().setDEF("LABEL_APPEARANCE")
                    .setMaterial(new Material().setDiffuseColor(Java.to(doubleToFloat([1,1,0.3]), Java.type("float[]"))).setEmissiveColor(Java.to(doubleToFloat([0.33,0.33,0.1]), Java.type("float[]")))))
                  .setGeometry(new Text().setString(Java.to(["Y"], Java.type("java.lang.String[]")))
                    .setFontStyle(new FontStyle().setDEF("LABEL_FONT").setFamily(Java.to(["SANS"], Java.type("java.lang.String[]"))).setJustify(Java.to(["MIDDLE","MIDDLE"], Java.type("java.lang.String[]"))).setSize(0.2)))))))
          .addChild(new Transform().setRotation(Java.to(doubleToFloat([0,0,1,-1.57079]), Java.type("float[]")))
            .addComments(new CommentsBlock("Horizontal X arrow and label"))
            .addChild(new Group()
              .addChild(new Group().setDEF("ArrowRed")
                .addChild(new Shape()
                  .setGeometry(new Cylinder().setUSE("ArrowCylinder"))
                  .setAppearance(new Appearance().setDEF("Red")
                    .setMaterial(new Material().setDiffuseColor(Java.to(doubleToFloat([0.7,0.1,0.1]), Java.type("float[]"))).setEmissiveColor(Java.to(doubleToFloat([0.33,0,0]), Java.type("float[]"))))))
                .addChild(new Transform().setTranslation(Java.to(doubleToFloat([0,1,0]), Java.type("float[]")))
                  .addChild(new Shape()
                    .setGeometry(new Cone().setUSE("ArrowCone"))
                    .setAppearance(new Appearance().setUSE("Red")))))
              .addChild(new Transform().setRotation(Java.to(doubleToFloat([0,0,1,1.57079]), Java.type("float[]"))).setTranslation(Java.to(doubleToFloat([0.072,1.1,0]), Java.type("float[]")))
                .addComments(new CommentsBlock("note label rotated back to original coordinate frame"))
                .addChild(new Billboard()
                  .addChild(new Shape()
                    .setAppearance(new Appearance().setUSE("LABEL_APPEARANCE"))
                    .setGeometry(new Text().setString(Java.to(["X"], Java.type("java.lang.String[]")))
                      .setFontStyle(new FontStyle().setUSE("LABEL_FONT"))))))))
          .addChild(new Transform().setRotation(Java.to(doubleToFloat([1,0,0,1.57079]), Java.type("float[]")))
            .addComments(new CommentsBlock("Perpendicular Z arrow and label, note right-hand rule"))
            .addChild(new Group()
              .addChild(new Group().setDEF("ArrowBlue")
                .addChild(new Shape()
                  .setGeometry(new Cylinder().setUSE("ArrowCylinder"))
                  .setAppearance(new Appearance().setDEF("Blue")
                    .setMaterial(new Material().setDiffuseColor(Java.to(doubleToFloat([0.3,0.3,1]), Java.type("float[]"))).setEmissiveColor(Java.to(doubleToFloat([0.1,0.1,0.33]), Java.type("float[]"))))))
                .addChild(new Transform().setTranslation(Java.to(doubleToFloat([0,1,0]), Java.type("float[]")))
                  .addChild(new Shape()
                    .setGeometry(new Cone().setUSE("ArrowCone"))
                    .setAppearance(new Appearance().setUSE("Blue")))))
              .addChild(new Transform().setRotation(Java.to(doubleToFloat([1,0,0,-1.57079]), Java.type("float[]"))).setTranslation(Java.to(doubleToFloat([0,1.1,0.072]), Java.type("float[]")))
                .addComments(new CommentsBlock("note label rotated back to original coordinate frame"))
                .addChild(new Billboard()
                  .addChild(new Shape()
                    .setAppearance(new Appearance().setUSE("LABEL_APPEARANCE"))
                    .setGeometry(new Text().setString(Java.to(["Z"], Java.type("java.lang.String[]")))
                      .setFontStyle(new FontStyle().setUSE("LABEL_FONT"))))))))))      ;
    X3D0.toFileX3D(".././CoordinateAxes.new.graal.x3d");
    X3D0.toFileJSON(".././CoordinateAxes.new.graal.json");
