###############################################
#
# Now available: developmental python x3d.py package on PyPi for import.
#   This approach greatly simplifies Python X3D deployment and use.
#   https://pypi.org/project/x3d
#
# Installation:
#       pip install x3d
# or
#       python -m pip install x3d
#
# Developer options for loading x3d package:
#
#    from x3d import *  # preferred approach, terser source that avoids x3d.* class prefixes
#
# or
#    import x3d         # traditional way to subclass x3d package, all classes require x3d.* prefix
#                       # but python source is very verbose, for example x3d.Material x3d.Shape etc.
#                       # X3dToPython.xslt stylesheet insertPackagePrefix=true supports this option.

from x3d import *

###############################################

newModel=X3D(profile='Immersive',version='3.0',
  head=head(
    children=[
    meta(content='MyTree.x3d',name='title'),
    meta(content='Random stylized tree generated by the "Semi-Random Tree Generator" java progam',name='description'),
    meta(content='Michael Martin',name='creator'),
    meta(content='15 September 2004',name='created'),
    meta(content='14 January 2014',name='modified'),
    meta(content='tree',name='subject'),
    meta(content='SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/MyTree.x3d',name='identifier'),
    meta(content='../../license.html',name='license')]),
  Scene=Scene(
    children=[
    Transform(
      children=[
      Transform(
        children=[
        Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.4,.3,0))),
            geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
        Transform(translation=(0,1.028294869392318,0),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
            geometry=Sphere(radius=0.2056589738784636))]),
        Transform(rotation=(0,1,0,1.734007540939678),scale=(0.31611167101257454,0.31611167101257454,0.31611167101257454),translation=(0,0.635256567825872,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.7032388599350552))])])]),
        Transform(rotation=(0,1,0,2.6086001641627714),scale=(0.4398986207010769,0.4398986207010769,0.4398986207010769),translation=(0,0.38067759730104817,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5759493746726433))])])]),
        Transform(rotation=(0,1,0,3.6178822758222458),scale=(0.26545888668507805,0.26545888668507805,0.26545888668507805),translation=(0,0.7394285643146725,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.7553248581794555))])])]),
        Transform(rotation=(0,1,0,5.091602782263341),scale=(0.25469961352727105,0.25469961352727105,0.25469961352727105),translation=(0,0.7615559750877994,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.7663885635660189))])])]),
        Transform(rotation=(0,1,0,5.601034040124506),scale=(0.3700616820990582,0.3700616820990582,0.3700616820990582),translation=(0,0.5243035286180924,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6477623403311654))])])]),
        Transform(rotation=(0,1,0,0.7902836030632338),scale=(0.36760093503911595,0.36760093503911595,0.36760093503911595),translation=(0,0.5293642757713141,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6502927139077763))])])]),
        Transform(rotation=(0,1,0,5.31543385959789),scale=(0.4540143647520952,0.4540143647520952,0.4540143647520952),translation=(0,0.3516473029304136,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5614342274873261))])])]),
        Transform(rotation=(0,1,0,0.7314520629021307),scale=(0.49830235872846385,0.49830235872846385,0.49830235872846385),translation=(0,0.26056506896725795,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5158931105057483))])])]),
        Transform(rotation=(0,1,0,4.177538285662819),scale=(0.471468668995274,0.471468668995274,0.471468668995274),translation=(0,0.31575095992626695,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5434860559852527))])])]),
        Transform(rotation=(0,1,0,0.2087072972528232),scale=(0.27133213933515626,0.27133213933515626,0.27133213933515626),translation=(0,0.727349693181232,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12853685867403974,1.028294869392318,0.12853685867403974),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.028294869392318,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.7492854226127352))])])])])])])
) # X3D model complete

###############################################
# Self-test diagnostics
###############################################

if        metaDiagnostics(newModel): # built-in utility method in X3D class
    print(metaDiagnostics(newModel))
print('check  newModel.XML() serialization...')
newModelXML = newModel.XML() # test export method XML() for exceptions
# print(newModelXML) # debug

print ("python x3d.py load successful for MyTree.py")
