###############################################
#
# Now available: developmental python x3d.py package on PyPi for import.
#   This approach greatly simplifies Python X3D deployment and use.
#   https://pypi.org/project/x3d
#
# Installation:
#       pip install x3d
# or
#       python -m pip install x3d
#
# Developer options for loading x3d package:
#
#    from x3d import *  # preferred approach, terser source that avoids x3d.* class prefixes
#
# or
#    import x3d         # traditional way to subclass x3d package, all classes require x3d.* prefix
#                       # but python source is very verbose, for example x3d.Material x3d.Shape etc.
#                       # X3dToPython.xslt stylesheet insertPackagePrefix=true supports this option.

from x3d import *

###############################################

newModel=X3D(profile='Immersive',version='3.0',
  head=head(
    children=[
    meta(content='Tree3.x3d',name='title'),
    meta(content='Random stylized tree generated by the "Semi-Random Tree Generator" java progam',name='description'),
    meta(content='Michael Martin',name='creator'),
    meta(content='14 September 2004',name='created'),
    meta(content='14 January 2014',name='modified'),
    meta(content='SRTG.java',name='reference'),
    meta(content='SRTG.bat',name='reference'),
    meta(content='tree',name='subject'),
    meta(content='SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/Tree3.x3d',name='identifier'),
    meta(content='X3D-Edit 3.2, https://savage.nps.edu/X3D-Edit',name='generator'),
    meta(content='../../license.html',name='license')]),
  Scene=Scene(
    children=[
    Transform(
      children=[
      Transform(
        children=[
        Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.4,.3,0))),
            geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
        Transform(translation=(0,0.9771164048641839,0),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
            geometry=Sphere(radius=0.1954232809728368))]),
        Transform(rotation=(0,1,0,3.5769639949594674),scale=(0.28295176176545017,0.28295176176545017,0.28295176176545017),translation=(0,0.6684418896677425,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9771164048641839,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.7006395966579402))])])]),
        Transform(rotation=(0,1,0,1.7768084584993165),scale=(0.34365554388058217,0.34365554388058217,0.34365554388058217),translation=(0,0.5498125669837495,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9771164048641839,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6413249353159437))])])]),
        Transform(rotation=(0,1,0,5.9442899958945254),scale=(0.30686256643779614,0.30686256643779614,0.30686256643779614),translation=(0,0.6217146106700376,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9771164048641839,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6772759571590878))])])]),
        Transform(rotation=(0,1,0,3.9038086200828244),scale=(0.43579903640031387,0.43579903640031387,0.43579903640031387),translation=(0,0.3697427306987293,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9771164048641839,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5512900171734336))])])]),
        Transform(rotation=(0,1,0,5.161034146283849),scale=(0.3017408696676908,0.3017408696676908,0.3017408696676908),translation=(0,0.6317235985396573,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9771164048641839,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6822804510938976))])])]),
        Transform(rotation=(0,1,0,3.94767850393865),scale=(0.47156115033981394,0.47156115033981394,0.47156115033981394),translation=(0,0.29985523429291405,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9771164048641839,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.516346268970526))])])]),
        Transform(rotation=(0,1,0,0.2767631279334452),scale=(0.30979511918826313,0.30979511918826313,0.30979511918826313),translation=(0,0.6159837198688158,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9771164048641839,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6744105117584769))])])]),
        Transform(rotation=(0,1,0,0.8152647696322589),scale=(0.48772955883086333,0.48772955883086333,0.48772955883086333),translation=(0,0.26825839993861456,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9771164048641839,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5005478517933762))])])]),
        Transform(rotation=(0,1,0,1.874762176003723),scale=(0.43456663545511665,0.43456663545511665,0.43456663545511665),translation=(0,0.372151129060574,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12213955060802299,0.9771164048641839,0.12213955060802299),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9771164048641839,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.552494216354356))])])])])])])
) # X3D model complete

###############################################
# Self-test diagnostics
###############################################

if        metaDiagnostics(newModel): # built-in utility method in X3D class
    print(metaDiagnostics(newModel))
print('check  newModel.XML() serialization...')
newModelXML = newModel.XML() # test export method XML() for exceptions
# print(newModelXML) # debug

print ("python x3d.py load successful for Tree3.py")
