###############################################
#
# Now available: developmental python x3d.py package on PyPi for import.
#   This approach greatly simplifies Python X3D deployment and use.
#   https://pypi.org/project/x3d
#
# Installation:
#       pip install x3d
# or
#       python -m pip install x3d
#
# Developer options for loading x3d package:
#
#    from x3d import *  # preferred approach, terser source that avoids x3d.* class prefixes
#
# or
#    import x3d         # traditional way to subclass x3d package, all classes require x3d.* prefix
#                       # but python source is very verbose, for example x3d.Material x3d.Shape etc.
#                       # X3dToPython.xslt stylesheet insertPackagePrefix=true supports this option.

from x3d import *

###############################################

newModel=X3D(profile='Immersive',version='3.0',
  head=head(
    children=[
    meta(content='Tree1.x3d',name='title'),
    meta(content='Random stylized tree generated by the "Semi-Random Tree Generator" java progam',name='description'),
    meta(content='Michael Martin',name='creator'),
    meta(content='14 September 2004',name='created'),
    meta(content='14 January 2014',name='modified'),
    meta(content='SRTG.java',name='reference'),
    meta(content='SRTG.bat',name='reference'),
    meta(content='tree',name='subject'),
    meta(content='SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/Tree1.x3d',name='identifier'),
    meta(content='X3D-Edit 3.2, https://savage.nps.edu/X3D-Edit',name='generator'),
    meta(content='../../license.html',name='license')]),
  Scene=Scene(
    children=[
    Transform(
      children=[
      Transform(
        children=[
        Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.4,.3,0))),
            geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
        Transform(translation=(0,0.9783586928971199,0),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
            geometry=Sphere(radius=0.195671738579424))]),
        Transform(rotation=(0,1,0,4.872058874845953),scale=(0.2553154585451582,0.2553154585451582,0.2553154585451582),translation=(0,0.7233681695240602,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9783586928971199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.7285685945984501))])])]),
        Transform(rotation=(0,1,0,2.7047066133540465),scale=(0.3897859547605992,0.3897859547605992,0.3897859547605992),translation=(0,0.4602474117029284,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9783586928971199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5970082156878842))])])]),
        Transform(rotation=(0,1,0,3.8162613059379873),scale=(0.2971317863822792,0.2971317863822792,0.2971317863822792),translation=(0,0.6415454338350939,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9783586928971199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6876572267539669))])])]),
        Transform(rotation=(0,1,0,0.1872362052994156),scale=(0.4877499126983201,0.4877499126983201,0.4877499126983201),translation=(0,0.26855963202497424,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9783586928971199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5011643258489071))])])]),
        Transform(rotation=(0,1,0,5.2485976035039545),scale=(0.3679302791258671,0.3679302791258671,0.3679302791258671),translation=(0,0.5030127921956882,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9783586928971199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.618390905934264))])])]),
        Transform(rotation=(0,1,0,0.30342596102400604),scale=(0.39841096726317726,0.39841096726317726,0.39841096726317726),translation=(0,0.44337069978644117,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9783586928971199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5885698597296405))])])]),
        Transform(rotation=(0,1,0,2.040031449905085),scale=(0.4359622962138162,0.4359622962138162,0.4359622962138162),translation=(0,0.3698933615690474,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9783586928971199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5518311906209437))])])]),
        Transform(rotation=(0,1,0,4.203880277681206),scale=(0.48768853342122553,0.48768853342122553,0.48768853342122553),translation=(0,0.26867973392359273,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9783586928971199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5012243767982163))])])]),
        Transform(rotation=(0,1,0,2.3092054191968168),scale=(0.3872605890720833,0.3872605890720833,0.3872605890720833),translation=(0,0.4651888386511356,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12229483661213998,0.9783586928971199,0.12229483661213998),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9783586928971199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5994789291619878))])])])])])])
) # X3D model complete

###############################################
# Self-test diagnostics
###############################################

if        metaDiagnostics(newModel): # built-in utility method in X3D class
    print(metaDiagnostics(newModel))
print('check  newModel.XML() serialization...')
newModelXML = newModel.XML() # test export method XML() for exceptions
# print(newModelXML) # debug

print ("python x3d.py load successful for Tree1.py")
