###############################################
#
# Now available: developmental python x3d.py package on PyPi for import.
#   This approach greatly simplifies Python X3D deployment and use.
#   https://pypi.org/project/x3d
#
# Installation:
#       pip install x3d
# or
#       python -m pip install x3d
#
# Developer options for loading x3d package:
#
#    from x3d import *  # preferred approach, terser source that avoids x3d.* class prefixes
#
# or
#    import x3d         # traditional way to subclass x3d package, all classes require x3d.* prefix
#                       # but python source is very verbose, for example x3d.Material x3d.Shape etc.
#                       # X3dToPython.xslt stylesheet insertPackagePrefix=true supports this option.

from x3d import *

###############################################

newModel=X3D(profile='Immersive',version='3.0',
  head=head(
    children=[
    meta(content='Tree4.x3d',name='title'),
    meta(content='Random stylized tree generated by the "Semi-Random Tree Generator" java progam',name='description'),
    meta(content='Michael Martin',name='creator'),
    meta(content='14 September 2004',name='created'),
    meta(content='14 January 2014',name='modified'),
    meta(content='SRTG.java',name='reference'),
    meta(content='SRTG.bat',name='reference'),
    meta(content='tree',name='subject'),
    meta(content='SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/Tree4.x3d',name='identifier'),
    meta(content='X3D-Edit 3.2, https://savage.nps.edu/X3D-Edit',name='generator'),
    meta(content='../../license.html',name='license')]),
  Scene=Scene(
    children=[
    Transform(
      children=[
      Transform(
        children=[
        Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.4,.3,0))),
            geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
        Transform(translation=(0,0.9786851096696199,0),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
            geometry=Sphere(radius=0.19573702193392398))]),
        Transform(rotation=(0,1,0,4.875550072099067),scale=(0.4176432205472269,0.4176432205472269,0.4176432205472269),translation=(0,0.4058739848789527,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9786851096696199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5699439085655839))])])]),
        Transform(rotation=(0,1,0,2.369962110258042),scale=(0.380718868655793,0.380718868655793,0.380718868655793),translation=(0,0.47814861163964795,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9786851096696199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6060812219459315))])])]),
        Transform(rotation=(0,1,0,2.849293098316633),scale=(0.33125284422248463,0.33125284422248463,0.33125284422248463),translation=(0,0.574971934734513,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9786851096696199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.654492883493364))])])]),
        Transform(rotation=(0,1,0,0.17310564866589123),scale=(0.3710024737882917,0.3710024737882917,0.3710024737882917),translation=(0,0.4971671935926357,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9786851096696199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6155905129224253))])])]),
        Transform(rotation=(0,1,0,1.596569663540951),scale=(0.3067804009039075,0.3067804009039075,0.3067804009039075),translation=(0,0.6228735664807634,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9786851096696199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6784436993664892))])])]),
        Transform(rotation=(0,1,0,1.4107153886503134),scale=(0.4566606022924535,0.4566606022924535,0.4566606022924535),translation=(0,0.3295025238142558,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9786851096696199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5317581780332354))])])]),
        Transform(rotation=(0,1,0,5.96923954115756),scale=(0.39582899968680046,0.39582899968680046,0.39582899968680046),translation=(0,0.44857249114924025,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9786851096696199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5912931617007275))])])]),
        Transform(rotation=(0,1,0,1.0490191412412053),scale=(0.316631618025055,0.316631618025055,0.316631618025055),translation=(0,0.6035910874635845,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9786851096696199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6688024598578997))])])]),
        Transform(rotation=(0,1,0,1.3152496386987953),scale=(0.36714990672215586,0.36714990672215586,0.36714990672215586),translation=(0,0.5047080936358972,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12233563870870248,0.9786851096696199,0.12233563870870248),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,0.9786851096696199,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6193609629440561))])])])])])])
) # X3D model complete

###############################################
# Self-test diagnostics
###############################################

if        metaDiagnostics(newModel): # built-in utility method in X3D class
    print(metaDiagnostics(newModel))
print('check  newModel.XML() serialization...')
newModelXML = newModel.XML() # test export method XML() for exceptions
# print(newModelXML) # debug

print ("python x3d.py load successful for Tree4.py")
