###############################################
#
# Now available: developmental python x3d.py package on PyPi for import.
#   This approach greatly simplifies Python X3D deployment and use.
#   https://pypi.org/project/x3d
#
# Installation:
#       pip install x3d
# or
#       python -m pip install x3d
#
# Developer options for loading x3d package:
#
#    from x3d import *  # preferred approach, terser source that avoids x3d.* class prefixes
#
# or
#    import x3d         # traditional way to subclass x3d package, all classes require x3d.* prefix
#                       # but python source is very verbose, for example x3d.Material x3d.Shape etc.
#                       # X3dToPython.xslt stylesheet insertPackagePrefix=true supports this option.

from x3d import *

###############################################

newModel=X3D(profile='Immersive',version='3.0',
  head=head(
    children=[
    meta(content='Tree2.x3d',name='title'),
    meta(content='Random stylized tree generated by the "Semi-Random Tree Generator" java progam',name='description'),
    meta(content='Michael Martin',name='creator'),
    meta(content='14 September 2004',name='created'),
    meta(content='14 January 2014',name='modified'),
    meta(content='SRTG.java',name='reference'),
    meta(content='SRTG.bat',name='reference'),
    meta(content='tree',name='subject'),
    meta(content='SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/SRTG.java',name='generator'),
    meta(content='https://savage.nps.edu/Savage/Scenarios/TankManeuver/Tree2.x3d',name='identifier'),
    meta(content='X3D-Edit 3.2, https://savage.nps.edu/X3D-Edit',name='generator'),
    meta(content='../../license.html',name='license')]),
  Scene=Scene(
    children=[
    Transform(
      children=[
      Transform(
        children=[
        Transform(scale=(0.12956266229488006,1.0365012983590405,0.12956266229488006),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.4,.3,0))),
            geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
        Transform(translation=(0,1.0365012983590405,0),
          children=[
          Shape(
            appearance=Appearance(
              material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
            geometry=Sphere(radius=0.2073002596718081))]),
        Transform(rotation=(0,1,0,0.008745636413909607),scale=(0.3744755723652558,0.3744755723652558,0.3744755723652558),translation=(0,0.5193377890281355,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12956266229488006,1.0365012983590405,0.12956266229488006),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.0365012983590405,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.648356881398708))])])]),
        Transform(rotation=(0,1,0,4.960575147989419),scale=(0.4360208826079008,0.4360208826079008,0.4360208826079008),translation=(0,0.3917542010793126,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12956266229488006,1.0365012983590405,0.12956266229488006),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.0365012983590405,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5845650874242965))])])]),
        Transform(rotation=(0,1,0,5.327768315118076),scale=(0.3388414725884903,0.3388414725884903,0.3388414725884903),translation=(0,0.5932073703970817,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12956266229488006,1.0365012983590405,0.12956266229488006),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.0365012983590405,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6852916720831811))])])]),
        Transform(rotation=(0,1,0,4.12075927291948),scale=(0.2966148134438341,0.2966148134438341,0.2966148134438341),translation=(0,0.6807433444546832,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12956266229488006,1.0365012983590405,0.12956266229488006),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.0365012983590405,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.7290596591119818))])])]),
        Transform(rotation=(0,1,0,0.15629131609393604),scale=(0.3962153007003254,0.3962153007003254,0.3962153007003254),translation=(0,0.4742712757375907,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12956266229488006,1.0365012983590405,0.12956266229488006),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.0365012983590405,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6258236247534356))])])]),
        Transform(rotation=(0,1,0,2.0810789222231447),scale=(0.36071472865590354,0.36071472865590354,0.36071472865590354),translation=(0,0.5478640537706545,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12956266229488006,1.0365012983590405,0.12956266229488006),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.0365012983590405,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.6626200137699675))])])]),
        Transform(rotation=(0,1,0,4.764799272792372),scale=(0.45924697912607976,0.45924697912607976,0.45924697912607976),translation=(0,0.3436064426855027,0),
          children=[
          Transform(rotation=(1,0,0,.785),
            children=[
            Transform(scale=(0.12956266229488006,1.0365012983590405,0.12956266229488006),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.4,.3,0))),
                geometry=Extrusion(creaseAngle=0.785,crossSection=[(1.00,0.00),(0.92,-0.38),(0.71,-0.71),(0.38,-0.92),(0.00,-1.00),(-0.38,-0.92),(-0.71,-0.71),(-0.92,-0.38),(-1.00,-0.00),(-0.92,0.38),(-0.71,0.71),(-0.38,0.92),(0.00,1.00),(0.38,0.92),(0.71,0.71),(0.92,0.38),(1.00,0.00)],scale=[(1,1),(.75,.75)]))]),
            Transform(translation=(0,1.0365012983590405,0),
              children=[
              Shape(
                appearance=Appearance(
                  material=Material(diffuseColor=(.2,1,.2),specularColor=(.4,.3,0))),
                geometry=Sphere(radius=0.5604912082273916))])])])])])])
) # X3D model complete

###############################################
# Self-test diagnostics
###############################################

if        metaDiagnostics(newModel): # built-in utility method in X3D class
    print(metaDiagnostics(newModel))
print('check  newModel.XML() serialization...')
newModelXML = newModel.XML() # test export method XML() for exceptions
# print(newModelXML) # debug

print ("python x3d.py load successful for Tree2.py")
