load('X3Dautoclass.js');
var ConfigurationProperties = Packages.org.web3d.x3d.jsail.ConfigurationProperties;
ConfigurationProperties.showDefaultAttributes = false;
ConfigurationProperties.xsltEngine = ConfigurationProperties.XSLT_ENGINE_NATIVE_JAVA;
ConfigurationProperties.deleteIntermediateFiles = false;
ConfigurationProperties.setStripTrailingZeroes(true);
function doubleToFloat(d) {
    if (Float32Array)
	return new Float32Array([d])[0];
}
      var X3D0 =  new X3D().setProfile("Interchange").setVersion("3.3")
      .setHead(new head()
        .addMeta(new meta().setName("title").setContent("Bubbles.x3d"))
        .addMeta(new meta().setName("description").setContent("Bubble animation used by Nancy Diving example."))
        .addMeta(new meta().setName("creator").setContent("Etsuko Lippi"))
        .addMeta(new meta().setName("created").setContent("24 January 2001"))
        .addMeta(new meta().setName("modified").setContent("23 May 2020"))
        .addMeta(new meta().setName("identifier").setContent("https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Legacy/Bubbles.x3d"))
        .addMeta(new meta().setName("generator").setContent("X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit"))
        .addMeta(new meta().setName("license").setContent("../license.html")))
      .setScene(new Scene()
        .addChild(new WorldInfo().setTitle("Bubbles.x3d"))
        .addChild(new Transform().setDEF("Bubbles")
          .addChild(new Group().setDEF("Bubble")
            .addChild(new TimeSensor().setDEF("BubbleClock").setCycleInterval(6).setLoop(true))
            .addChild(new PositionInterpolator().setDEF("BubblePath1").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.5),doubleToFloat(0.8),doubleToFloat(0.9),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0),doubleToFloat(0),doubleToFloat(0),doubleToFloat(0.75),doubleToFloat(0.75),doubleToFloat(0.75),doubleToFloat(0.86),doubleToFloat(0.86),doubleToFloat(0.86),doubleToFloat(0.99),doubleToFloat(0.998),doubleToFloat(0.9876),doubleToFloat(1.272),doubleToFloat(1.9044),doubleToFloat(0.9509)], Java.type("float[]"))))
            .addChild(new PositionInterpolator().setDEF("BubblePath2").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.3),doubleToFloat(0.64),doubleToFloat(0.85),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0.1),doubleToFloat(0.1),doubleToFloat(0.1),doubleToFloat(0.2),doubleToFloat(0.4),doubleToFloat(0.25),doubleToFloat(0.3),doubleToFloat(0.5),doubleToFloat(0.46),doubleToFloat(0.75),doubleToFloat(0.5),doubleToFloat(0.575),doubleToFloat(0.038483478),doubleToFloat(1.989),doubleToFloat(1.098373)], Java.type("float[]"))))
            .addChild(new PositionInterpolator().setDEF("BubblePath3").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.1),doubleToFloat(0.45),doubleToFloat(0.7),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0.01),doubleToFloat(0.01),doubleToFloat(0.01),doubleToFloat(0.25),doubleToFloat(0.35),doubleToFloat(0.0045),doubleToFloat(0.55),doubleToFloat(0.6),doubleToFloat(0.0055),doubleToFloat(0.66),doubleToFloat(0.665),doubleToFloat(0.00655),doubleToFloat(1.555),doubleToFloat(1.09043),doubleToFloat(0.005734)], Java.type("float[]"))))
            .addChild(new PositionInterpolator().setDEF("BubblePath4").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.5),doubleToFloat(0.6),doubleToFloat(0.8),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0),doubleToFloat(0),doubleToFloat(0),doubleToFloat(0.5),doubleToFloat(0.5),doubleToFloat(0.005),doubleToFloat(0.6),doubleToFloat(0.6),doubleToFloat(0.006),doubleToFloat(0.75),doubleToFloat(0.75),doubleToFloat(0.0075),doubleToFloat(1.948594),doubleToFloat(1.3983),doubleToFloat(0.009009349)], Java.type("float[]"))))
            .addChild(new PositionInterpolator().setDEF("BubblePath5").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.25),doubleToFloat(0.35),doubleToFloat(0.65),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0),doubleToFloat(0),doubleToFloat(0),doubleToFloat(0.5),doubleToFloat(0.5),doubleToFloat(0.005),doubleToFloat(0.6),doubleToFloat(0.6),doubleToFloat(0.006),doubleToFloat(0.75),doubleToFloat(0.75),doubleToFloat(0.0075),doubleToFloat(1.84444),doubleToFloat(1.22222),doubleToFloat(0.1)], Java.type("float[]"))))
            .addChild(new PositionInterpolator().setDEF("BubblePath6").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.15),doubleToFloat(0.22235),doubleToFloat(0.55565),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0),doubleToFloat(0),doubleToFloat(0),doubleToFloat(0.235),doubleToFloat(0.3455),doubleToFloat(0.0055),doubleToFloat(0.356),doubleToFloat(0.676),doubleToFloat(0.00456),doubleToFloat(0.5675),doubleToFloat(0.75),doubleToFloat(0.0074565),doubleToFloat(1.098),doubleToFloat(1.0343),doubleToFloat(0.14)], Java.type("float[]"))))
            .addChild(new PositionInterpolator().setDEF("BubblePath7").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.2425),doubleToFloat(0.4535),doubleToFloat(0.6775),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0),doubleToFloat(0),doubleToFloat(0),doubleToFloat(0.12345),doubleToFloat(0.2225),doubleToFloat(0.00335),doubleToFloat(0.786),doubleToFloat(0.456),doubleToFloat(0.00666),doubleToFloat(0.74555),doubleToFloat(0.7335),doubleToFloat(0.00234575),doubleToFloat(0.08787),doubleToFloat(1.022),doubleToFloat(0.12)], Java.type("float[]"))))
            .addChild(new PositionInterpolator().setDEF("BubblePath8").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.1125),doubleToFloat(0.5535),doubleToFloat(0.97865),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0),doubleToFloat(0),doubleToFloat(0),doubleToFloat(0.1235),doubleToFloat(0.05),doubleToFloat(0.00125),doubleToFloat(0.5666),doubleToFloat(0.4346),doubleToFloat(0.005556),doubleToFloat(0.8975),doubleToFloat(0.34575),doubleToFloat(0.0098775),doubleToFloat(1.8787),doubleToFloat(1.686),doubleToFloat(0.86)], Java.type("float[]"))))
            .addChild(new PositionInterpolator().setDEF("BubblePath9").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.0025),doubleToFloat(0.035),doubleToFloat(0.65),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0),doubleToFloat(0),doubleToFloat(0),doubleToFloat(0.522),doubleToFloat(0.5445),doubleToFloat(0.0057),doubleToFloat(0.6543),doubleToFloat(0.226),doubleToFloat(0.0055),doubleToFloat(0.45575),doubleToFloat(0.4375),doubleToFloat(0.0067),doubleToFloat(1.8787),doubleToFloat(2),doubleToFloat(0.1545)], Java.type("float[]"))))
            .addChild(new PositionInterpolator().setDEF("BubblePath10").setKey(Java.to([doubleToFloat(0),doubleToFloat(0.00025),doubleToFloat(0.035),doubleToFloat(0.6895),doubleToFloat(1)], Java.type("float[]"))).setKeyValue(Java.to([doubleToFloat(0),doubleToFloat(0),doubleToFloat(0),doubleToFloat(0.8765),doubleToFloat(0.445),doubleToFloat(0.00335),doubleToFloat(0.3336),doubleToFloat(0.4446),doubleToFloat(0.005556),doubleToFloat(0.765),doubleToFloat(0.75),doubleToFloat(0.0075),doubleToFloat(1),doubleToFloat(1),doubleToFloat(0.1)], Java.type("float[]"))))
            .addChild(new Transform()
              .addChild(new Transform().setDEF("bubble1")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.025))))
              .addChild(new Transform().setDEF("bubble2")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.055))))
              .addChild(new Transform().setDEF("bubble3")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.065))))
              .addChild(new Transform().setDEF("bubble4")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.015))))
              .addChild(new Transform().setDEF("bubble5")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.075))))
              .addChild(new Transform().setDEF("bubble6")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.005))))
              .addChild(new Transform().setDEF("bubble7")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.035))))
              .addChild(new Transform().setDEF("bubble8")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.05))))
              .addChild(new Transform().setDEF("bubble9")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.045))))
              .addChild(new Transform().setDEF("bubble10")
                .addChild(new Shape()
                  .setAppearance(new Appearance()
                    .setMaterial(new Material().setDiffuseColor(Java.to([doubleToFloat(1),doubleToFloat(1),doubleToFloat(1)], Java.type("float[]"))).setTransparency(0.8)))
                  .setGeometry(new Sphere().setRadius(0.035))))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath1"))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath2"))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath3"))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath4"))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath5"))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath6"))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath7"))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath8"))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath9"))
              .addChild(new ROUTE().setFromField("fraction_changed").setFromNode("BubbleClock").setToField("set_fraction").setToNode("BubblePath10"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath1").setToField("set_translation").setToNode("bubble1"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath2").setToField("set_translation").setToNode("bubble2"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath3").setToField("set_translation").setToNode("bubble3"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath4").setToField("set_translation").setToNode("bubble4"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath5").setToField("set_translation").setToNode("bubble5"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath6").setToField("set_translation").setToNode("bubble6"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath7").setToField("set_translation").setToNode("bubble7"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath8").setToField("set_translation").setToNode("bubble8"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath9").setToField("set_translation").setToNode("bubble9"))
              .addChild(new ROUTE().setFromField("value_changed").setFromNode("BubblePath10").setToField("set_translation").setToNode("bubble10")))))
        .addChild(new Background().setSkyColor(Java.to([doubleToFloat(0),doubleToFloat(0),doubleToFloat(0.6)], Java.type("float[]")))))      ;
    X3D0.toFileX3D("../personal/bubbles.new.graal.x3d");
    X3D0.toFileJSON("../personal/bubbles.new.graal.json");
