(ns x3dclsail.bumpyfreewrlsliders
  (:import 	(org.web3d.x3d.jsail.Shape AcousticProperties Appearance FillProperties LineProperties Material PhysicalMaterial PointProperties Shape TwoSidedMaterial UnlitMaterial)
	(org.web3d.x3d.jsail.Sound Analyser AudioClip AudioDestination BiquadFilter BufferAudioSource ChannelMerger ChannelSelector ChannelSplitter Convolver Delay DynamicsCompressor Gain ListenerPointSource MicrophoneSource OscillatorSource PeriodicWave Sound SpatialSound StreamAudioDestination StreamAudioSource WaveShaper)
	(org.web3d.x3d.jsail.Networking Anchor Inline LoadSensor)
	(org.web3d.x3d.jsail.Geometry2D Arc2D ArcClose2D Circle2D Disk2D Polyline2D Polypoint2D Rectangle2D TriangleSet2D)
	(org.web3d.x3d.jsail.EnvironmentalEffects Background Fog FogCoordinate LocalFog TextureBackground)
	(org.web3d.x3d.jsail.RigidBodyPhysics BallJoint CollidableOffset CollidableShape CollisionCollection CollisionSensor CollisionSpace Contact DoubleAxisHingeJoint MotorJoint RigidBody RigidBodyCollection SingleAxisHingeJoint SliderJoint UniversalJoint)
	(org.web3d.x3d.jsail.Navigation Billboard Collision LOD NavigationInfo OrthoViewpoint Viewpoint ViewpointGroup)
	(org.web3d.x3d.jsail.VolumeRendering BlendedVolumeStyle BoundaryEnhancementVolumeStyle CartoonVolumeStyle ComposedVolumeStyle EdgeEnhancementVolumeStyle IsoSurfaceVolumeData OpacityMapVolumeStyle ProjectionVolumeStyle SegmentedVolumeData ShadedVolumeStyle SilhouetteEnhancementVolumeStyle ToneMappedVolumeStyle VolumeData)
	(org.web3d.x3d.jsail.EventUtilities BooleanFilter BooleanSequencer BooleanToggle BooleanTrigger IntegerSequencer IntegerTrigger TimeTrigger)
	(org.web3d.x3d.jsail.ParticleSystems BoundedPhysicsModel ConeEmitter ExplosionEmitter ForcePhysicsModel ParticleSystem PointEmitter PolylineEmitter SurfaceEmitter VolumeEmitter WindPhysicsModel)
	(org.web3d.x3d.jsail.Geometry3D Box Cone Cylinder ElevationGrid Extrusion IndexedFaceSet Sphere)
	(org.web3d.x3d.jsail.CADGeometry CADAssembly CADFace CADLayer CADPart IndexedQuadSet QuadSet)
	(org.web3d.x3d.jsail.Rendering ClipPlane Color ColorRGBA Coordinate CoordinateDouble IndexedLineSet IndexedTriangleFanSet IndexedTriangleSet IndexedTriangleStripSet LineSet Normal PointSet TriangleFanSet TriangleSet TriangleStripSet)
	(org.web3d.x3d.jsail.Followers ColorChaser ColorDamper CoordinateChaser CoordinateDamper OrientationChaser OrientationDamper PositionChaser PositionChaser2D PositionDamper PositionDamper2D ScalarChaser ScalarDamper TexCoordChaser2D TexCoordDamper2D)
	(org.web3d.x3d.jsail.Interpolation ColorInterpolator CoordinateInterpolator CoordinateInterpolator2D EaseInEaseOut NormalInterpolator OrientationInterpolator PositionInterpolator PositionInterpolator2D ScalarInterpolator SplinePositionInterpolator SplinePositionInterpolator2D SplineScalarInterpolator SquadOrientationInterpolator)
	(org.web3d.x3d.jsail.CubeMapTexturing ComposedCubeMapTexture GeneratedCubeMapTexture ImageCubeMapTexture)
	(org.web3d.x3d.jsail.Shaders ComposedShader FloatVertexAttribute Matrix3VertexAttribute Matrix4VertexAttribute PackagedShader ProgramShader ShaderPart ShaderProgram)
	(org.web3d.x3d.jsail.Texturing3D ComposedTexture3D ImageTexture3D PixelTexture3D TextureCoordinate3D TextureCoordinate4D TextureTransform3D TextureTransformMatrix3D)
	(org.web3d.x3d.jsail.NURBS Contour2D ContourPolyline2D NurbsCurve NurbsCurve2D NurbsOrientationInterpolator NurbsPatchSurface NurbsPositionInterpolator NurbsSet NurbsSurfaceInterpolator NurbsSweptSurface NurbsSwungSurface NurbsTextureCoordinate NurbsTrimmedSurface)
	(org.web3d.x3d.jsail.PointingDeviceSensor CylinderSensor PlaneSensor SphereSensor TouchSensor)
	(org.web3d.x3d.jsail.Lighting DirectionalLight PointLight SpotLight)
	(org.web3d.x3d.jsail.DIS DISEntityManager DISEntityTypeMapping EspduTransform ReceiverPdu SignalPdu TransmitterPdu)
	(org.web3d.x3d.jsail.Text FontStyle Text)
	(org.web3d.x3d.jsail.Geospatial GeoCoordinate GeoElevationGrid GeoLocation GeoLOD GeoMetadata GeoOrigin GeoPositionInterpolator GeoProximitySensor GeoTouchSensor GeoTransform GeoViewpoint)
	(org.web3d.x3d.jsail.Grouping Group StaticGroup Switch Transform)
	(org.web3d.x3d.jsail.HAnim HAnimDisplacer HAnimHumanoid HAnimJoint HAnimMotion HAnimSegment HAnimSite)
	(org.web3d.x3d.jsail.Texturing ImageTexture MovieTexture MultiTexture MultiTextureCoordinate MultiTextureTransform PixelTexture TextureCoordinate TextureCoordinateGenerator TextureProperties TextureTransform)
	(org.web3d.x3d.jsail.KeyDeviceSensor KeySensor StringSensor)
	(org.web3d.x3d.jsail.Layering Layer LayerSet Viewport)
	(org.web3d.x3d.jsail.Layout Layout LayoutGroup LayoutLayer ScreenFontStyle ScreenGroup)
	(org.web3d.x3d.jsail.Picking LinePickSensor PickableGroup PointPickSensor PrimitivePickSensor VolumePickSensor)
	(org.web3d.x3d.jsail.Core MetadataBoolean MetadataDouble MetadataFloat MetadataInteger MetadataSet MetadataString ProtoInstance WorldInfo component connect ExternProtoDeclare field fieldValue head IS ProtoBody ProtoDeclare ProtoInterface ROUTE Scene unit X3D CommentsBlock)
	(org.web3d.x3d.jsail.EnvironmentalSensor ProximitySensor TransformSensor VisibilitySensor)
	(org.web3d.x3d.jsail.Scripting Script)
	(org.web3d.x3d.jsail.TextureProjection TextureProjector TextureProjectorParallel)
	(org.web3d.x3d.jsail.Time TimeSensor)
	(org.web3d.x3d.jsail.fields SFBool MFBool SFColor MFColor SFColorRGBA MFColorRGBA SFDouble MFDouble SFFloat MFFloat SFImage MFImage SFInt32 MFInt32 SFMatrix3d MFMatrix3d SFMatrix3f MFMatrix3f SFMatrix4d MFMatrix4d SFMatrix4f MFMatrix4f SFNode MFNode SFRotation MFRotation SFString MFString SFTime MFTime SFVec2d MFVec2d SFVec2f MFVec2f SFVec3d MFVec3d SFVec3f MFVec3f SFVec4d MFVec4d SFVec4f MFVec4f)
	(org.web3d.x3d.jsail ConfigurationProperties)
))(def EXPORT org.web3d.x3d.jsail.Networking.EXPORT)
(def IMPORT org.web3d.x3d.jsail.Networking.IMPORT)
(def X3D0 (doto (X3D.)
    (.setProfile "Full")
    (.setVersion "4.0")
    (.setHead (doto (head. )
        (.addComponent (doto (component. )
            (.setName "Scripting")
            (.setLevel 1)
        ))
        (.addComponent (doto (component. )
            (.setName "EnvironmentalEffects")
            (.setLevel 3)
        ))
        (.addComponent (doto (component. )
            (.setName "Shaders")
            (.setLevel 1)
        ))
        (.addComponent (doto (component. )
            (.setName "CubeMapTexturing")
            (.setLevel 1)
        ))
        (.addComponent (doto (component. )
            (.setName "Texturing")
            (.setLevel 1)
        ))
        (.addComponent (doto (component. )
            (.setName "Rendering")
            (.setLevel 1)
        ))
        (.addComponent (doto (component. )
            (.setName "Grouping")
            (.setLevel 3)
        ))
        (.addComponent (doto (component. )
            (.setName "Core")
            (.setLevel 1)
        ))
        (.addComponent (doto (component. )
            (.setName "DIS")
            (.setLevel 2)
        ))
;<component name='Shape' level='4'></component>
;Additional authoring resources for meta-tags: http://www.dublincore.org/documents/dcmi-terms http://www.dublincore.org/documents/dces http://www.w3.org/TR/html4/struct/global.html#h-7.4.4 http://vancouver-webpages.com/META http://vancouver-webpages.com/META/about-mk-metas2.html Additional authoring resources for language codes: ftp://ftp.isi.edu/in-notes/bcp/bcp47.txt http://www.loc.gov/standards/iso639-2/langhome.html http://www.iana.org/numbers.html#L
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "title")
            (.setContent "bumpfreewrlsliders.x3d")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "description")
            (.setContent "*enter description here, short-sentence summaries preferred*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "creator")
            (.setContent "Doug Sanden, Christoph Valentin, John Carlson")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "translator")
            (.setContent "*if manually translating VRML-to-X3D, enter name of person translating here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "created")
            (.setContent "*enter date of initial version here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "translated")
            (.setContent "*enter date of translation here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "modified")
            (.setContent "*enter date of latest revision here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "version")
            (.setContent "*enter version here, if any*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "reference")
            (.setContent "*enter reference citation or relative/online url here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "reference")
            (.setContent "*enter additional url/bibliographic reference information here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "requires")
            (.setContent "*enter reference resource here if required to support function, delivery, or coherence of content*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "rights")
            (.setContent "*enter copyright information here* Example: Copyright (c) Web3D Consortium Inc. 2008, 2024")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "drawing")
            (.setContent "*enter drawing filename/url here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "MovingImage")
            (.setContent "*enter movie filename/url here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "photo")
            (.setContent "*enter photo filename/url here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "subject")
            (.setContent "*enter subject keywords here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "accessRights")
            (.setContent "*enter permission statements or url here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "identifier")
            (.setContent "*enter online Uniform Resource Identifier (URI) or Uniform Resource Locator (URL) address for this file here*")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "generator")
            (.setContent "PSPad, http://www.pspad.com/")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "license")
            (.setContent "license.html")
        ))
    ))
;\"The Flower Review (TPREV)\", a simple MU scene using DIS Sensor Event Distribution, It is assumed the reviewers (users) have a non-X3D voice channel (e.g. TeamSpeak) open for their \"discussion about the teapot\"
    (.setScene (doto (Scene. )
;LayerSet with two layers, navigation happens in layer 1
        (.addLayerSet (doto (LayerSet. )
            (.setActiveLayer 1)
            (.setOrder (int-array [1 2]))
;the first Layer contains the main scenery - \"The Review of the Flower (DIS Multiuser)\"
;the second layer contains the sliders that are moved with the user's display like a HUD (heads up display)
            (.addLayers (doto (Layer. )
                (.setPickable true)
                (.setObjectType (into-array ["ALL"]))
;basic nodes, which might be present in any scene
                (.addChildren (doto (NavigationInfo. )
                    (.setType (into-array ["EXAMINE"]))
                    (.setAvatarSize (float-array [0.25 1.75 0.75]))
                ))
                (.addChildren (doto (DirectionalLight. )
                    (.setAmbientIntensity 0.2)
                    (.setDirection (float-array [0 -1 0]))
                ))
                (.addChildren (doto (DirectionalLight. )
                    (.setAmbientIntensity 0.2)
                    (.setDirection (float-array [-1 -0.1 -1]))
                ))
                (.addChildren (doto (Viewpoint. )
                    (.setDescription "My Overview")
                    (.setFieldOfView 1.570796)
                    (.setPosition (float-array [0 1.75 60]))
                ))
;this group contains the red/green/blue 3D crosshair
                (.addChildren (doto (Group. )
;Arrow X
                    (.addChildren (doto (Transform. )
                        (.setTranslation (float-array [25 0 0]))
                        (.setRotation (float-array [0 0 -1 1.57]))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cylinder. )
                                (.setDEF "Shaft")
                                (.setRadius 0.35)
                                (.setHeight 50.0)
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                    (.setDEF "RED")
                                    (.setDiffuseColor (float-array [1 0 0]))
                                    (.setEmissiveColor (float-array [1 0 0]))
                                ))
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setTranslation (float-array [50 0 0]))
                        (.setRotation (float-array [0 0 -1 1.57]))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cone. )
                                (.setDEF "Tip")
                                (.setBottomRadius 0.8)
                                (.setHeight 3.0)
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                    (.setUSE "RED")
                                ))
                            ))
                        ))
                    ))
;Arrow Y
                    (.addChildren (doto (Transform. )
                        (.setTranslation (float-array [0 25 0]))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cylinder. )
                                (.setUSE "Shaft")
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                    (.setDEF "GREEN")
                                    (.setDiffuseColor (float-array [0 1 0]))
                                    (.setEmissiveColor (float-array [0 1 0]))
                                ))
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setTranslation (float-array [0 50 0]))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cone. )
                                (.setUSE "Tip")
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                    (.setUSE "GREEN")
                                ))
                            ))
                        ))
                    ))
;Arrow Z
                    (.addChildren (doto (Transform. )
                        (.setTranslation (float-array [0 0 25]))
                        (.setRotation (float-array [1 0 0 1.57]))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cylinder. )
                                (.setUSE "Shaft")
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                    (.setDEF "BLUE")
                                    (.setDiffuseColor (float-array [0 0 1]))
                                    (.setEmissiveColor (float-array [0 0 1]))
                                ))
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setTranslation (float-array [0 0 50]))
                        (.setRotation (float-array [1 0 0 1.57]))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cone. )
                                (.setUSE "Tip")
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                    (.setUSE "BLUE")
                                ))
                            ))
                        ))
                    ))
                ))
;the model that is being reviewed by the users of this scene
                (.addChildren (doto (Transform. )
                    (.setDEF "FlowerTransform")
;<Inline DEF=\"Flower\" url='\"bumpyfreewrl.x3d\"' />
;Images courtesy of Paul Debevec's Light Probe Image Gallery
                    (.addChildren (doto (Background. )
                        (.setBackUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_back.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_back.png"]))
                        (.setBottomUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_bottom.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_bottom.png"]))
                        (.setFrontUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_front.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_front.png"]))
                        (.setLeftUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_left.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_left.png"]))
                        (.setRightUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_right.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_right.png"]))
                        (.setTopUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_top.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_top.png"]))
                    ))
                    (.addChild (doto (Shape. )
                        (.setGeometry (doto (Sphere. )
                            (.setRadius 0.01)
                        ))
                        (.setAppearance (doto (Appearance. )
                            (.setMaterial (doto (Material. )
                                (.setDiffuseColor (float-array [0.7 0.7 0.7]))
                                (.setSpecularColor (float-array [0.5 0.5 0.5]))
                            ))
                            (.setTexture (doto (ComposedCubeMapTexture. )
                                (.setDEF "texture")
                                (.setBackTexture (doto (ImageTexture. )
                                    (.setUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_back.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_back.png"]))
                                ))
                                (.setBottomTexture (doto (ImageTexture. )
                                    (.setUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_bottom.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_bottom.png"]))
                                ))
                                (.setFrontTexture (doto (ImageTexture. )
                                    (.setUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_front.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_front.png"]))
                                ))
                                (.setLeftTexture (doto (ImageTexture. )
                                    (.setUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_left.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_left.png"]))
                                ))
                                (.setRightTexture (doto (ImageTexture. )
                                    (.setUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_right.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_right.png"]))
                                ))
                                (.setTopTexture (doto (ImageTexture. )
                                    (.setUrl (into-array ["../resources/images/all_probes/stpeters_cross/stpeters_top.png" "https://coderextreme.net/X3DJSONLD/src/main/resources/images/all_probes/stpeters_cross/stpeters_top.png"]))
                                ))
                            ))
                            (.addShaders (doto (ComposedShader. )
                                (.setDEF "freewrlShader")
                                (.setLanguage "GLSL")
                                (.addField (doto (field. )
                                    (.setName "chromaticDispertion")
                                    (.setAccessType "inputOnly")
                                    (.setType "SFVec3f")
                                    (.setValue "0.98 1 1.033")
                                ))
                                (.addField (doto (field. )
                                    (.setName "fw_textureCoordGenType")
                                    (.setAccessType "inputOnly")
                                    (.setType "SFInt32")
                                    (.setValue "0")
                                ))
                                (.addField (doto (field. )
                                    (.setName "bias")
                                    (.setType "SFFloat")
                                    (.setAccessType "inputOnly")
                                    (.setValue "0.5")
                                ))
                                (.addField (doto (field. )
                                    (.setName "scale")
                                    (.setType "SFFloat")
                                    (.setAccessType "inputOnly")
                                    (.setValue "0.5")
                                ))
                                (.addField (doto (field. )
                                    (.setName "power")
                                    (.setType "SFFloat")
                                    (.setAccessType "inputOnly")
                                    (.setValue "2")
                                ))
                                (.addField (doto (field. )
                                    (.setName "a")
                                    (.setType "SFFloat")
                                    (.setAccessType "inputOutput")
                                    (.setValue "15")
                                ))
                                (.addField (doto (field. )
                                    (.setName "b")
                                    (.setType "SFFloat")
                                    (.setAccessType "inputOutput")
                                    (.setValue "5")
                                ))
                                (.addField (doto (field. )
                                    (.setName "c")
                                    (.setType "SFFloat")
                                    (.setAccessType "inputOutput")
                                    (.setValue "5")
                                ))
                                (.addField (doto (field. )
                                    (.setName "d")
                                    (.setType "SFFloat")
                                    (.setAccessType "inputOutput")
                                    (.setValue "5")
                                ))
                                (.addField (doto (field. )
                                    (.setName "tdelta")
                                    (.setType "SFFloat")
                                    (.setAccessType "inputOutput")
                                    (.setValue "0")
                                ))
                                (.addField (doto (field. )
                                    (.setName "pdelta")
                                    (.setType "SFFloat")
                                    (.setAccessType "inputOutput")
                                    (.setValue "0")
                                ))
                                (.addParts (doto (ShaderPart. )
                                    (.setUrl (into-array ["../shaders/freewrl_flowers_chromatic.vs" "https://coderextreme.net/X3DJSONLD/src/main/shaders/freewrl_flowers_chromatic.vs"]))
                                    (.setType "VERTEX")
                                ))
                                (.addParts (doto (ShaderPart. )
                                    (.setUrl (into-array ["../shaders/freewrl_bubbles.fs" "https://coderextreme.net/X3DJSONLD/src/main/shaders/freewrl_bubbles.fs"]))
                                    (.setType "FRAGMENT")
                                ))
                            ))
                        ))
                    ))
                ))
;DIS multiuser facilities
                (.addChildren (doto (DISEntityManager. )
                    (.setDEF "EntityManager")
                    (.addChildren (doto (DISEntityTypeMapping. )
                        (.setCategory 77)
                        (.setSpecific 1)
                        (.setUrl (into-array ["../data/Leif8Final.x3d" "https://coderextreme.net/X3DJSONLD/src/main/data/Leif8Final.x3d"]))
                    ))
                    (.addChildren (doto (DISEntityTypeMapping. )
                        (.setCategory 77)
                        (.setSpecific 2)
                        (.setUrl (into-array ["../data/Lily8Final.x3d" "https://coderextreme.net/X3DJSONLD/src/main/data/Lily8Final.x3d"]))
                    ))
                    (.addChildren (doto (DISEntityTypeMapping. )
                        (.setCategory 77)
                        (.setSpecific 3)
                        (.setUrl (into-array ["../data/Tufani8Final.x3d" "https://coderextreme.net/X3DJSONLD/src/main/data/Tufani8Final.x3d"]))
                    ))
                    (.addChildren (doto (DISEntityTypeMapping. )
                        (.setCategory 77)
                        (.setSpecific 4)
                        (.setUrl (into-array ["../data/Gramps8Final.x3d" "https://coderextreme.net/X3DJSONLD/src/main/data/Gramps8Final.x3d"]))
                    ))
                ))
                (.addChildren (doto (Collision. )
                    (.setEnabled false)
                    (.setProxy (doto (Group. )
                        (.setDEF "AvatarHolder")
                    ))
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "addedEntities")
                    (.setFromNode "EntityManager")
                    (.setToField "addChildren")
                    (.setToNode "AvatarHolder")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "removedEntities")
                    (.setFromNode "EntityManager")
                    (.setToField "removeChildren")
                    (.setToNode "AvatarHolder")
                ))
            ))
            (.addLayers (doto (LayoutLayer. )
                (.setPickable true)
                (.setObjectType (into-array ["ALL"]))
;positioning the LayoutLayer
;clipping the LayoutLayer
;the content (children) of the LayoutLayer
;first, the slider for scaling the model
                (.addChildren (doto (Transform. )
                    (.setTranslation (float-array [0 0 -3]))
                    (.addChild (doto (Shape. )
                        (.setAppearance (doto (Appearance. )
                            (.setMaterial (doto (Material. )
                                (.setDiffuseColor (float-array [0 0 0]))
                                (.setTransparency 0.7)
                            ))
                        ))
                        (.setGeometry (doto (Box. )
                            (.setSize (float-array [100 100 0.02]))
                        ))
                    ))
                ))
;the plane sensors
                (.addChildren (doto (Transform. )
                    (.setDEF "aSlider")
                    (.setTranslation (float-array [0 0.7 0]))
                    (.addChildren (doto (Transform. )
                        (.setRotation (float-array [0 0 1 1.57]))
                        (.addChild (doto (Shape. )
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 2.5)
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setDEF "aTransform")
                        (.setTranslation (float-array [0 0 0.1]))
                        (.addChildren (doto (PlaneSensor. )
                            (.setDEF "aSensor")
                            (.setMinPosition (float-array [-20 0]))
                            (.setMaxPosition (float-array [20 0]))
                        ))
                        (.addChildren (doto (Transform. )
                            (.setTranslation (float-array [0 0 0]))
                            (.addChildren (doto (TouchSensor. )
                                (.setDEF "aTS")
                            ))
                            (.addChild (doto (Shape. )
                                (.setGeometry (doto (Sphere. )
                                    (.setRadius 0.08)
                                ))
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setDiffuseColor (float-array [1 0 0]))
                                    ))
                                ))
                            ))
                        ))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 0.3)
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setRotation (float-array [0 0 1 1.57]))
                        (.addChild (doto (Shape. )
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 2.5)
                            ))
                        ))
                    ))
                ))
                (.addChildren (doto (Transform. )
                    (.setDEF "bSlider")
                    (.setTranslation (float-array [0 0.4 0]))
                    (.addChildren (doto (Transform. )
                        (.setRotation (float-array [0 0 1 1.57]))
                        (.addChild (doto (Shape. )
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 2.5)
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setDEF "bTransform")
                        (.setTranslation (float-array [0 0 0.1]))
                        (.addChildren (doto (PlaneSensor. )
                            (.setDEF "bSensor")
                            (.setMinPosition (float-array [-20 0]))
                            (.setMaxPosition (float-array [20 0]))
                        ))
                        (.addChildren (doto (Transform. )
                            (.setTranslation (float-array [0 0 0]))
                            (.addChildren (doto (TouchSensor. )
                                (.setDEF "bTS")
                            ))
                            (.addChild (doto (Shape. )
                                (.setGeometry (doto (Sphere. )
                                    (.setRadius 0.08)
                                ))
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setDiffuseColor (float-array [1 0 0]))
                                    ))
                                ))
                            ))
                        ))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 0.3)
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                        ))
                    ))
                ))
                (.addChildren (doto (Transform. )
                    (.setDEF "cSlider")
                    (.setTranslation (float-array [0 0.1 0]))
                    (.addChildren (doto (Transform. )
                        (.setRotation (float-array [0 0 1 1.57]))
                        (.addChild (doto (Shape. )
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 2.5)
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setDEF "cTransform")
                        (.setTranslation (float-array [0 0 0.1]))
                        (.addChildren (doto (PlaneSensor. )
                            (.setDEF "cSensor")
                            (.setMinPosition (float-array [-20 0]))
                            (.setMaxPosition (float-array [20 0]))
                        ))
                        (.addChildren (doto (Transform. )
                            (.setTranslation (float-array [0 0 0]))
                            (.addChildren (doto (TouchSensor. )
                                (.setDEF "cTS")
                            ))
                            (.addChild (doto (Shape. )
                                (.setGeometry (doto (Sphere. )
                                    (.setRadius 0.08)
                                ))
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setDiffuseColor (float-array [1 0 0]))
                                    ))
                                ))
                            ))
                        ))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 0.3)
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                        ))
                    ))
                ))
                (.addChildren (doto (Transform. )
                    (.setDEF "dSlider")
                    (.setTranslation (float-array [0 -0.2 0]))
                    (.addChildren (doto (Transform. )
                        (.setRotation (float-array [0 0 1 1.57]))
                        (.addChild (doto (Shape. )
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 2.5)
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setDEF "dTransform")
                        (.setTranslation (float-array [0 0 0.1]))
                        (.addChildren (doto (PlaneSensor. )
                            (.setDEF "dSensor")
                            (.setMinPosition (float-array [-20 0]))
                            (.setMaxPosition (float-array [20 0]))
                        ))
                        (.addChildren (doto (Transform. )
                            (.setTranslation (float-array [0 0 0]))
                            (.addChildren (doto (TouchSensor. )
                                (.setDEF "dTS")
                            ))
                            (.addChild (doto (Shape. )
                                (.setGeometry (doto (Sphere. )
                                    (.setRadius 0.08)
                                ))
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setDiffuseColor (float-array [1 0 0]))
                                    ))
                                ))
                            ))
                        ))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 0.3)
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                        ))
                    ))
                ))
                (.addChildren (doto (Transform. )
                    (.setDEF "pdeltaSlider")
                    (.setTranslation (float-array [0 -0.5 0]))
                    (.addChildren (doto (Transform. )
                        (.setRotation (float-array [0 0 1 1.57]))
                        (.addChild (doto (Shape. )
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 2.5)
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setDEF "pdeltaTransform")
                        (.setTranslation (float-array [0 0 0.1]))
                        (.addChildren (doto (PlaneSensor. )
                            (.setDEF "pdeltaSensor")
                            (.setMinPosition (float-array [-20 0]))
                            (.setMaxPosition (float-array [20 0]))
                        ))
                        (.addChildren (doto (Transform. )
                            (.setTranslation (float-array [0 0 0]))
                            (.addChildren (doto (TouchSensor. )
                                (.setDEF "pdeltaTS")
                            ))
                            (.addChild (doto (Shape. )
                                (.setGeometry (doto (Sphere. )
                                    (.setRadius 0.08)
                                ))
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setDiffuseColor (float-array [1 0 0]))
                                    ))
                                ))
                            ))
                        ))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 0.3)
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                        ))
                    ))
                ))
                (.addChildren (doto (Transform. )
                    (.setDEF "tdeltaSlider")
                    (.setTranslation (float-array [0 -0.8 0]))
                    (.addChildren (doto (Transform. )
                        (.setRotation (float-array [0 0 1 1.57]))
                        (.addChild (doto (Shape. )
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 2.5)
                            ))
                        ))
                    ))
                    (.addChildren (doto (Transform. )
                        (.setDEF "tdeltaTransform")
                        (.setTranslation (float-array [0 0 0.1]))
                        (.addChildren (doto (PlaneSensor. )
                            (.setDEF "tdeltaSensor")
                            (.setMinPosition (float-array [-20 0]))
                            (.setMaxPosition (float-array [20 0]))
                        ))
                        (.addChildren (doto (Transform. )
                            (.setTranslation (float-array [0 0 0]))
                            (.addChildren (doto (TouchSensor. )
                                (.setDEF "tdeltaTS")
                            ))
                            (.addChild (doto (Shape. )
                                (.setGeometry (doto (Sphere. )
                                    (.setRadius 0.08)
                                ))
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setDiffuseColor (float-array [1 0 0]))
                                    ))
                                ))
                            ))
                        ))
                        (.addChild (doto (Shape. )
                            (.setGeometry (doto (Cylinder. )
                                (.setRadius 0.05)
                                (.setHeight 0.3)
                            ))
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                ))
                            ))
                        ))
                    ))
                ))
                (.addChildren (doto (Script. )
                    (.setDEF "aValueTransformerScript")
                    (.setDirectOutput true)
                    (.setMustEvaluate true)
                    (.addField (doto (field. )
                        (.setName "newTranslation")
                        (.setAccessType "inputOnly")
                        (.setType "SFVec3f")
                        (.setValue "1 1 1")
                    ))
                    (.addField (doto (field. )
                        (.setName "aValue")
                        (.setAccessType "outputOnly")
                        (.setType "SFFloat")
                        (.setValue "1")
                    ))
(.setSourceCode " function newTranslation(Value) { aValue = Value.x * 30; }\\newline")                ))
                (.addChildren (doto (Script. )
                    (.setDEF "bValueTransformerScript")
                    (.setDirectOutput true)
                    (.setMustEvaluate true)
                    (.addField (doto (field. )
                        (.setName "newTranslation")
                        (.setAccessType "inputOnly")
                        (.setType "SFVec3f")
                        (.setValue "1 1 1")
                    ))
                    (.addField (doto (field. )
                        (.setName "bValue")
                        (.setAccessType "outputOnly")
                        (.setType "SFFloat")
                        (.setValue "1")
                    ))
(.setSourceCode " function newTranslation(Value) { bValue = Value.x * 30; }\\newline")                ))
                (.addChildren (doto (Script. )
                    (.setDEF "cValueTransformerScript")
                    (.setDirectOutput true)
                    (.setMustEvaluate true)
                    (.addField (doto (field. )
                        (.setName "newTranslation")
                        (.setAccessType "inputOnly")
                        (.setType "SFVec3f")
                        (.setValue "1 1 1")
                    ))
                    (.addField (doto (field. )
                        (.setName "cValue")
                        (.setAccessType "outputOnly")
                        (.setType "SFFloat")
                        (.setValue "1")
                    ))
(.setSourceCode " function newTranslation(Value) { cValue = Value.x * 5; }\\newline")                ))
                (.addChildren (doto (Script. )
                    (.setDEF "dValueTransformerScript")
                    (.setDirectOutput true)
                    (.setMustEvaluate true)
                    (.addField (doto (field. )
                        (.setName "newTranslation")
                        (.setAccessType "inputOnly")
                        (.setType "SFVec3f")
                        (.setValue "1 1 1")
                    ))
                    (.addField (doto (field. )
                        (.setName "dValue")
                        (.setAccessType "outputOnly")
                        (.setType "SFFloat")
                        (.setValue "1")
                    ))
(.setSourceCode " function newTranslation(Value) { dValue = Value.x * 5; }\\newline")                ))
                (.addChildren (doto (Script. )
                    (.setDEF "pdeltaValueTransformerScript")
                    (.setDirectOutput true)
                    (.setMustEvaluate true)
                    (.addField (doto (field. )
                        (.setName "newTranslation")
                        (.setAccessType "inputOnly")
                        (.setType "SFVec3f")
                        (.setValue "1 1 1")
                    ))
                    (.addField (doto (field. )
                        (.setName "pdeltaValue")
                        (.setAccessType "outputOnly")
                        (.setType "SFFloat")
                        (.setValue "1")
                    ))
(.setSourceCode " function newTranslation(Value) { pdeltaValue = Value.x; }\\newline")                ))
                (.addChildren (doto (Script. )
                    (.setDEF "tdeltaValueTransformerScript")
                    (.setDirectOutput true)
                    (.setMustEvaluate true)
                    (.addField (doto (field. )
                        (.setName "newTranslation")
                        (.setAccessType "inputOnly")
                        (.setType "SFVec3f")
                        (.setValue "1 1 1")
                    ))
                    (.addField (doto (field. )
                        (.setName "tdeltaValue")
                        (.setAccessType "outputOnly")
                        (.setType "SFFloat")
                        (.setValue "1")
                    ))
(.setSourceCode " function newTranslation(Value) { tdeltaValue = Value.x; }\\newline")                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "aSensor")
                    (.setToField "set_translation")
                    (.setToNode "aTransform")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "bSensor")
                    (.setToField "set_translation")
                    (.setToNode "bTransform")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "cSensor")
                    (.setToField "set_translation")
                    (.setToNode "cTransform")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "dSensor")
                    (.setToField "set_translation")
                    (.setToNode "dTransform")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "pdeltaSensor")
                    (.setToField "set_translation")
                    (.setToNode "pdeltaTransform")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "tdeltaSensor")
                    (.setToField "set_translation")
                    (.setToNode "tdeltaTransform")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "aSensor")
                    (.setToField "newTranslation")
                    (.setToNode "aValueTransformerScript")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "bSensor")
                    (.setToField "newTranslation")
                    (.setToNode "bValueTransformerScript")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "cSensor")
                    (.setToField "newTranslation")
                    (.setToNode "cValueTransformerScript")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "dSensor")
                    (.setToField "newTranslation")
                    (.setToNode "dValueTransformerScript")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "pdeltaSensor")
                    (.setToField "newTranslation")
                    (.setToNode "pdeltaValueTransformerScript")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "translation_changed")
                    (.setFromNode "tdeltaSensor")
                    (.setToField "newTranslation")
                    (.setToNode "tdeltaValueTransformerScript")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "aValue")
                    (.setFromNode "aValueTransformerScript")
                    (.setToField "a")
                    (.setToNode "freewrlShader")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "bValue")
                    (.setFromNode "bValueTransformerScript")
                    (.setToField "b")
                    (.setToNode "freewrlShader")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "cValue")
                    (.setFromNode "cValueTransformerScript")
                    (.setToField "c")
                    (.setToNode "freewrlShader")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "dValue")
                    (.setFromNode "dValueTransformerScript")
                    (.setToField "d")
                    (.setToNode "freewrlShader")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "pdeltaValue")
                    (.setFromNode "pdeltaValueTransformerScript")
                    (.setToField "pdelta")
                    (.setToNode "freewrlShader")
                ))
                (.addChildren (doto (ROUTE. )
                    (.setFromField "tdeltaValue")
                    (.setFromNode "tdeltaValueTransformerScript")
                    (.setToField "tdelta")
                    (.setToNode "freewrlShader")
                ))
                (.setLayout (doto (Layout. )
                    (.setAlign (into-array ["RIGHT" "BOTTOM"]))
                    (.setOffset (float-array [0 0]))
                    (.setSize (float-array [0.4 1]))
                ))
                (.setViewport (doto (Viewport. )
                    (.setClipBoundary (float-array [0 1 0 1]))
                ))
            ))
        ))
    ))
))
(.toFileX3D X3D0 ".././bumpyfreewrlsliders.new.clojure.x3d")
(.toFileJSON X3D0 ".././bumpyfreewrlsliders.new.clojure.json")
(defn -main []
(println "Hello from your main function!"))