function HAnimModelFootRight: TX3DRootNode;
var
X3D0: TX3DRootNode;
Group25: TGroupNode;
WorldInfo26: TWorldInfoNode;
HAnimHumanoid27: THAnimHumanoidNode;
MetadataSet28: TMetadataSetNode;
MetadataString29: TMetadataStringNode;
HAnimJoint30: THAnimJointNode;
HAnimJoint31: THAnimJointNode;
HAnimSegment32: THAnimSegmentNode;
Transform33: TTransformNode;
Shape34: TShapeNode;
Sphere35: TSphereNode;
Appearance36: TAppearanceNode;
Material37: TMaterialNode;
Shape38: TShapeNode;
Appearance39: TAppearanceNode;
Material40: TMaterialNode;
IndexedLineSet41: TIndexedLineSetNode;
Coordinate42: TCoordinateNode;
Shape43: TShapeNode;
Appearance44: TAppearanceNode;
Material45: TMaterialNode;
IndexedLineSet46: TIndexedLineSetNode;
Coordinate47: TCoordinateNode;
HAnimJoint48: THAnimJointNode;
HAnimSegment49: THAnimSegmentNode;
Transform50: TTransformNode;
Shape51: TShapeNode;
Shape52: TShapeNode;
Appearance53: TAppearanceNode;
Material54: TMaterialNode;
IndexedLineSet55: TIndexedLineSetNode;
Coordinate56: TCoordinateNode;
Shape57: TShapeNode;
Appearance58: TAppearanceNode;
Material59: TMaterialNode;
IndexedLineSet60: TIndexedLineSetNode;
Coordinate61: TCoordinateNode;
Shape62: TShapeNode;
Appearance63: TAppearanceNode;
Material64: TMaterialNode;
IndexedLineSet65: TIndexedLineSetNode;
Coordinate66: TCoordinateNode;
HAnimJoint67: THAnimJointNode;
HAnimSegment68: THAnimSegmentNode;
Transform69: TTransformNode;
Shape70: TShapeNode;
Shape71: TShapeNode;
Appearance72: TAppearanceNode;
Material73: TMaterialNode;
IndexedLineSet74: TIndexedLineSetNode;
Coordinate75: TCoordinateNode;
HAnimJoint76: THAnimJointNode;
HAnimSegment77: THAnimSegmentNode;
Transform78: TTransformNode;
Shape79: TShapeNode;
Shape80: TShapeNode;
Appearance81: TAppearanceNode;
Material82: TMaterialNode;
IndexedLineSet83: TIndexedLineSetNode;
Coordinate84: TCoordinateNode;
HAnimJoint85: THAnimJointNode;
HAnimSegment86: THAnimSegmentNode;
Transform87: TTransformNode;
Shape88: TShapeNode;
Shape89: TShapeNode;
Appearance90: TAppearanceNode;
Material91: TMaterialNode;
IndexedLineSet92: TIndexedLineSetNode;
Coordinate93: TCoordinateNode;
HAnimJoint94: THAnimJointNode;
HAnimSegment95: THAnimSegmentNode;
Transform96: TTransformNode;
Shape97: TShapeNode;
Shape98: TShapeNode;
Appearance99: TAppearanceNode;
Material100: TMaterialNode;
IndexedLineSet101: TIndexedLineSetNode;
Coordinate102: TCoordinateNode;
HAnimJoint103: THAnimJointNode;
HAnimSegment104: THAnimSegmentNode;
Transform105: TTransformNode;
Shape106: TShapeNode;
Shape107: TShapeNode;
Appearance108: TAppearanceNode;
Material109: TMaterialNode;
IndexedLineSet110: TIndexedLineSetNode;
Coordinate111: TCoordinateNode;
HAnimJoint112: THAnimJointNode;
HAnimSegment113: THAnimSegmentNode;
Transform114: TTransformNode;
Shape115: TShapeNode;
Shape116: TShapeNode;
Appearance117: TAppearanceNode;
Material118: TMaterialNode;
IndexedLineSet119: TIndexedLineSetNode;
Coordinate120: TCoordinateNode;
HAnimJoint121: THAnimJointNode;
HAnimSegment122: THAnimSegmentNode;
Transform123: TTransformNode;
Shape124: TShapeNode;
Shape125: TShapeNode;
Appearance126: TAppearanceNode;
Material127: TMaterialNode;
IndexedLineSet128: TIndexedLineSetNode;
Coordinate129: TCoordinateNode;
HAnimJoint130: THAnimJointNode;
HAnimSegment131: THAnimSegmentNode;
Transform132: TTransformNode;
Shape133: TShapeNode;
Shape134: TShapeNode;
Appearance135: TAppearanceNode;
Material136: TMaterialNode;
IndexedLineSet137: TIndexedLineSetNode;
Coordinate138: TCoordinateNode;
HAnimJoint139: THAnimJointNode;
HAnimSegment140: THAnimSegmentNode;
Transform141: TTransformNode;
Shape142: TShapeNode;
Shape143: TShapeNode;
Appearance144: TAppearanceNode;
Material145: TMaterialNode;
IndexedLineSet146: TIndexedLineSetNode;
Coordinate147: TCoordinateNode;
HAnimJoint148: THAnimJointNode;
HAnimSegment149: THAnimSegmentNode;
Transform150: TTransformNode;
Shape151: TShapeNode;
Shape152: TShapeNode;
Appearance153: TAppearanceNode;
Material154: TMaterialNode;
IndexedLineSet155: TIndexedLineSetNode;
Coordinate156: TCoordinateNode;
HAnimJoint157: THAnimJointNode;
HAnimSegment158: THAnimSegmentNode;
Transform159: TTransformNode;
Shape160: TShapeNode;
Shape161: TShapeNode;
Appearance162: TAppearanceNode;
Material163: TMaterialNode;
IndexedLineSet164: TIndexedLineSetNode;
Coordinate165: TCoordinateNode;
HAnimJoint166: THAnimJointNode;
HAnimSegment167: THAnimSegmentNode;
Transform168: TTransformNode;
Shape169: TShapeNode;
Shape170: TShapeNode;
Appearance171: TAppearanceNode;
Material172: TMaterialNode;
IndexedLineSet173: TIndexedLineSetNode;
Coordinate174: TCoordinateNode;
HAnimJoint175: THAnimJointNode;
HAnimSegment176: THAnimSegmentNode;
Transform177: TTransformNode;
Shape178: TShapeNode;
Shape179: TShapeNode;
Appearance180: TAppearanceNode;
Material181: TMaterialNode;
IndexedLineSet182: TIndexedLineSetNode;
Coordinate183: TCoordinateNode;
HAnimJoint184: THAnimJointNode;
HAnimSegment185: THAnimSegmentNode;
Transform186: TTransformNode;
Shape187: TShapeNode;
Shape188: TShapeNode;
Appearance189: TAppearanceNode;
Material190: TMaterialNode;
IndexedLineSet191: TIndexedLineSetNode;
Coordinate192: TCoordinateNode;
HAnimJoint193: THAnimJointNode;
HAnimSegment194: THAnimSegmentNode;
Transform195: TTransformNode;
Shape196: TShapeNode;
Shape197: TShapeNode;
Appearance198: TAppearanceNode;
Material199: TMaterialNode;
IndexedLineSet200: TIndexedLineSetNode;
Coordinate201: TCoordinateNode;
HAnimJoint202: THAnimJointNode;
HAnimSegment203: THAnimSegmentNode;
Transform204: TTransformNode;
Shape205: TShapeNode;
Shape206: TShapeNode;
Appearance207: TAppearanceNode;
Material208: TMaterialNode;
IndexedLineSet209: TIndexedLineSetNode;
Coordinate210: TCoordinateNode;
Shape211: TShapeNode;
Appearance212: TAppearanceNode;
Material213: TMaterialNode;
IndexedLineSet214: TIndexedLineSetNode;
Coordinate215: TCoordinateNode;
HAnimJoint216: THAnimJointNode;
HAnimSegment217: THAnimSegmentNode;
Transform218: TTransformNode;
Shape219: TShapeNode;
Shape220: TShapeNode;
Appearance221: TAppearanceNode;
Material222: TMaterialNode;
IndexedLineSet223: TIndexedLineSetNode;
Coordinate224: TCoordinateNode;
HAnimJoint225: THAnimJointNode;
HAnimSegment226: THAnimSegmentNode;
Transform227: TTransformNode;
Shape228: TShapeNode;
Shape229: TShapeNode;
Appearance230: TAppearanceNode;
Material231: TMaterialNode;
IndexedLineSet232: TIndexedLineSetNode;
Coordinate233: TCoordinateNode;
HAnimJoint234: THAnimJointNode;
HAnimSegment235: THAnimSegmentNode;
Transform236: TTransformNode;
Shape237: TShapeNode;
Shape238: TShapeNode;
Appearance239: TAppearanceNode;
Material240: TMaterialNode;
IndexedLineSet241: TIndexedLineSetNode;
Coordinate242: TCoordinateNode;
HAnimJoint243: THAnimJointNode;
HAnimSegment244: THAnimSegmentNode;
Transform245: TTransformNode;
Shape246: TShapeNode;
Shape247: TShapeNode;
Appearance248: TAppearanceNode;
Material249: TMaterialNode;
IndexedLineSet250: TIndexedLineSetNode;
Coordinate251: TCoordinateNode;
HAnimJoint252: THAnimJointNode;
HAnimSegment253: THAnimSegmentNode;
Transform254: TTransformNode;
Shape255: TShapeNode;
Shape256: TShapeNode;
Appearance257: TAppearanceNode;
Material258: TMaterialNode;
IndexedLineSet259: TIndexedLineSetNode;
Coordinate260: TCoordinateNode;
HAnimJoint261: THAnimJointNode;
HAnimSegment262: THAnimSegmentNode;
Transform263: TTransformNode;
Shape264: TShapeNode;
Shape265: TShapeNode;
Appearance266: TAppearanceNode;
Material267: TMaterialNode;
IndexedLineSet268: TIndexedLineSetNode;
Coordinate269: TCoordinateNode;
HAnimJoint270: THAnimJointNode;
HAnimSegment271: THAnimSegmentNode;
Transform272: TTransformNode;
Shape273: TShapeNode;
Shape274: TShapeNode;
Appearance275: TAppearanceNode;
Material276: TMaterialNode;
IndexedLineSet277: TIndexedLineSetNode;
Coordinate278: TCoordinateNode;
HAnimJoint279: THAnimJointNode;
HAnimSegment280: THAnimSegmentNode;
Transform281: TTransformNode;
Shape282: TShapeNode;
Shape283: TShapeNode;
Appearance284: TAppearanceNode;
Material285: TMaterialNode;
IndexedLineSet286: TIndexedLineSetNode;
Coordinate287: TCoordinateNode;
HAnimJoint288: THAnimJointNode;
HAnimJoint289: THAnimJointNode;
HAnimJoint290: THAnimJointNode;
HAnimJoint291: THAnimJointNode;
HAnimJoint292: THAnimJointNode;
HAnimJoint293: THAnimJointNode;
HAnimJoint294: THAnimJointNode;
HAnimJoint295: THAnimJointNode;
HAnimJoint296: THAnimJointNode;
HAnimJoint297: THAnimJointNode;
HAnimJoint298: THAnimJointNode;
HAnimJoint299: THAnimJointNode;
HAnimJoint300: THAnimJointNode;
HAnimJoint301: THAnimJointNode;
HAnimJoint302: THAnimJointNode;
HAnimJoint303: THAnimJointNode;
HAnimJoint304: THAnimJointNode;
HAnimJoint305: THAnimJointNode;
HAnimJoint306: THAnimJointNode;
HAnimJoint307: THAnimJointNode;
HAnimJoint308: THAnimJointNode;
HAnimJoint309: THAnimJointNode;
HAnimJoint310: THAnimJointNode;
HAnimJoint311: THAnimJointNode;
HAnimJoint312: THAnimJointNode;
HAnimJoint313: THAnimJointNode;
HAnimJoint314: THAnimJointNode;
HAnimSegment315: THAnimSegmentNode;
HAnimSegment316: THAnimSegmentNode;
HAnimSegment317: THAnimSegmentNode;
HAnimSegment318: THAnimSegmentNode;
HAnimSegment319: THAnimSegmentNode;
HAnimSegment320: THAnimSegmentNode;
HAnimSegment321: THAnimSegmentNode;
HAnimSegment322: THAnimSegmentNode;
HAnimSegment323: THAnimSegmentNode;
HAnimSegment324: THAnimSegmentNode;
HAnimSegment325: THAnimSegmentNode;
HAnimSegment326: THAnimSegmentNode;
HAnimSegment327: THAnimSegmentNode;
HAnimSegment328: THAnimSegmentNode;
HAnimSegment329: THAnimSegmentNode;
HAnimSegment330: THAnimSegmentNode;
HAnimSegment331: THAnimSegmentNode;
HAnimSegment332: THAnimSegmentNode;
HAnimSegment333: THAnimSegmentNode;
HAnimSegment334: THAnimSegmentNode;
HAnimSegment335: THAnimSegmentNode;
HAnimSegment336: THAnimSegmentNode;
HAnimSegment337: THAnimSegmentNode;
HAnimSegment338: THAnimSegmentNode;
HAnimSegment339: THAnimSegmentNode;
HAnimSegment340: THAnimSegmentNode;
begin
X3D0 := TX3DRootNode.Create;
X3D0.Profile := 'Immersive';
X3D0.ForceVersion.Major := 4;
X3D0.ForceVersion.Minor := 0;
X3D0.Components['HAnim'] := 1;
X3D0.Meta['title'] := 'HAnimModelFootRight.x3d';
X3D0.Meta['description'] := 'Right foot, using high-fidelity definitions for HAnim version 2.0';
X3D0.Meta['creator'] := 'Kwan-Hee YOO, Don Brutzman and Joe Williams';
X3D0.Meta['created'] := '26 January 2015';
X3D0.Meta['modified'] := '23 December 2021';
X3D0.Meta['warning'] := 'not yet to scale';
X3D0.Meta['TODO'] := 'Update all values to match HAnim2 A.7 Level of articulation four LOA-4';
X3D0.Meta['TODO'] := 'Add links to figures';
X3D0.Meta['TODO'] := 'Add Viewpoints to enable inspection';
X3D0.Meta['info'] := 'TODO describe how to compute and apply offsets for center values whenever attaching this appendage to a body';
X3D0.Meta['warning'] := 'TODO will X3D HAnim component add a new level to support LOA-4 functionality?';
X3D0.Meta['reference'] := 'https://www.web3d.org/working-groups/humanoid-animation-HAnim';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#TheFeet';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#f-FootJoints';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#Hierarchy4';
X3D0.Meta['reference'] := 'https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-WD2/Part01/components/hanim.html';
X3D0.Meta['subject'] := 'X3D HAnim humanoid animation';
X3D0.Meta['TODO'] := 'Integrate and confirm Segment/Joint names, Viewpoints.';
X3D0.Meta['identifier'] := 'https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Characters/HAnimModelFootRight.x3d';
X3D0.Meta['generator'] := 'X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit';
X3D0.Meta['license'] := '../license.html';
Group25 := TGroupNode.Create;
WorldInfo26 := TWorldInfoNode.Create;
WorldInfo26.Title := 'HAnimModelFootRight.x3d';
{ .AddChildren }
Group25.AddChildren([WorldInfo26]);
HAnimHumanoid27 := THAnimHumanoidNode.Create;
HAnimHumanoid27.NameField := 'Foot_Right';
HAnimHumanoid27.Loa := 4;
HAnimHumanoid27.Version := '2.0';
{ original HAnimHumanoid info='"authorName=Kwan-Hee YOO, Don Brutzman and Joe Williams"' }
MetadataSet28 := TMetadataSetNode.Create;
MetadataSet28.NameField := 'HAnimHumanoid.info';
MetadataSet28.Reference := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/ObjectInterfaces.html#Humanoid';
MetadataString29 := TMetadataStringNode.Create;
MetadataString29.NameField := 'authorName';
MetadataString29.SetValue(['Kwan-Hee YOO, Don Brutzman and Joe Williams']);
{ .SetValue }
MetadataSet28.Value := MetadataString29;
{ .SetMetadata }
HAnimHumanoid27.Metadata := MetadataSet28;
HAnimJoint30 := THAnimJointNode.Create;
HAnimJoint30.NameField := 'humanoid_root';
HAnimJoint30.SetUlimit([0,0,0]);
HAnimJoint30.SetLlimit([0,0,0]);
{ Might consider putting a HAnimSegment here, but that doesn't help with re-use of this foot model }
HAnimJoint31 := THAnimJointNode.Create;
HAnimJoint31.NameField := 'r_talocrural';
HAnimJoint31.Description := 'connection joint of foot to leg above';
HAnimJoint31.SetUlimit([0,0,0]);
HAnimJoint31.SetLlimit([0,0,0]);
HAnimSegment32 := THAnimSegmentNode.Create;
HAnimSegment32.NameField := 'r_talus';
Transform33 := TTransformNode.Create;
Shape34 := TShapeNode.Create;
Sphere35 := TSphereNode.Create;
Sphere35.Radius := 0.025;
{ .SetGeometry }
Shape34.Geometry := Sphere35;
Appearance36 := TAppearanceNode.Create;
Material37 := TMaterialNode.Create;
Material37.DiffuseColor := Vector3(0,0,1);
{ .SetMaterial }
Appearance36.Material := Material37;
{ .SetAppearance }
Shape34.Appearance := Appearance36;
{ .AddChild }
Transform33.AddChildren([Shape34]);
{ .AddChildren }
HAnimSegment32.AddChildren([Transform33]);
Shape38 := TShapeNode.Create;
Appearance39 := TAppearanceNode.Create;
Material40 := TMaterialNode.Create;
Material40.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance39.Material := Material40;
{ .SetAppearance }
Shape38.Appearance := Appearance39;
IndexedLineSet41 := TIndexedLineSetNode.Create;
IndexedLineSet41.SetCoordIndex([0,1]);
Coordinate42 := TCoordinateNode.Create;
Coordinate42.SetPoint([Vector3(0,0,0),Vector3(0,-0.3,0)]);
{ .SetCoord }
IndexedLineSet41.Coord := Coordinate42;
{ .SetGeometry }
Shape38.Geometry := IndexedLineSet41;
{ .AddChildren }
HAnimSegment32.AddChildren([Shape38]);
Shape43 := TShapeNode.Create;
Appearance44 := TAppearanceNode.Create;
Material45 := TMaterialNode.Create;
Material45.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance44.Material := Material45;
{ .SetAppearance }
Shape43.Appearance := Appearance44;
IndexedLineSet46 := TIndexedLineSetNode.Create;
IndexedLineSet46.SetCoordIndex([0,1]);
Coordinate47 := TCoordinateNode.Create;
Coordinate47.SetPoint([Vector3(0,0,0),Vector3(-0.2,0.3,0)]);
{ .SetCoord }
IndexedLineSet46.Coord := Coordinate47;
{ .SetGeometry }
Shape43.Geometry := IndexedLineSet46;
{ .AddChildren }
HAnimSegment32.AddChildren([Shape43]);
{ .AddChildren }
HAnimJoint31.AddChildren([HAnimSegment32]);
{ TCN }
HAnimJoint48 := THAnimJointNode.Create;
HAnimJoint48.NameField := 'r_talocalcaneonavicular';
HAnimJoint48.Center := Vector3(0,-0.3,0);
HAnimJoint48.SetUlimit([0,0,0]);
HAnimJoint48.SetLlimit([0,0,0]);
HAnimSegment49 := THAnimSegmentNode.Create;
HAnimSegment49.NameField := 'r_navicular';
Transform50 := TTransformNode.Create;
Transform50.Translation := Vector3(0,-0.3,0);
Shape51 := TShapeNode.Create;
Shape51 := Shape34;
{ .AddChild }
Transform50.AddChildren([Shape51]);
{ .AddChildren }
HAnimSegment49.AddChildren([Transform50]);
Shape52 := TShapeNode.Create;
Appearance53 := TAppearanceNode.Create;
Material54 := TMaterialNode.Create;
Material54.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance53.Material := Material54;
{ .SetAppearance }
Shape52.Appearance := Appearance53;
IndexedLineSet55 := TIndexedLineSetNode.Create;
IndexedLineSet55.SetCoordIndex([0,1]);
Coordinate56 := TCoordinateNode.Create;
Coordinate56.SetPoint([Vector3(0,-0.3,0),Vector3(0.1,-0.45,0)]);
{ .SetCoord }
IndexedLineSet55.Coord := Coordinate56;
{ .SetGeometry }
Shape52.Geometry := IndexedLineSet55;
{ .AddChildren }
HAnimSegment49.AddChildren([Shape52]);
Shape57 := TShapeNode.Create;
Appearance58 := TAppearanceNode.Create;
Material59 := TMaterialNode.Create;
Material59.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance58.Material := Material59;
{ .SetAppearance }
Shape57.Appearance := Appearance58;
IndexedLineSet60 := TIndexedLineSetNode.Create;
IndexedLineSet60.SetCoordIndex([0,1]);
Coordinate61 := TCoordinateNode.Create;
Coordinate61.SetPoint([Vector3(0,-0.3,0),Vector3(0,-0.45,0)]);
{ .SetCoord }
IndexedLineSet60.Coord := Coordinate61;
{ .SetGeometry }
Shape57.Geometry := IndexedLineSet60;
{ .AddChildren }
HAnimSegment49.AddChildren([Shape57]);
Shape62 := TShapeNode.Create;
Appearance63 := TAppearanceNode.Create;
Material64 := TMaterialNode.Create;
Material64.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance63.Material := Material64;
{ .SetAppearance }
Shape62.Appearance := Appearance63;
IndexedLineSet65 := TIndexedLineSetNode.Create;
IndexedLineSet65.SetCoordIndex([0,1]);
Coordinate66 := TCoordinateNode.Create;
Coordinate66.SetPoint([Vector3(0,-0.3,0),Vector3(-0.1,-0.4,0)]);
{ .SetCoord }
IndexedLineSet65.Coord := Coordinate66;
{ .SetGeometry }
Shape62.Geometry := IndexedLineSet65;
{ .AddChildren }
HAnimSegment49.AddChildren([Shape62]);
{ .AddChildren }
HAnimJoint48.AddChildren([HAnimSegment49]);
{ CN1 }
HAnimJoint67 := THAnimJointNode.Create;
HAnimJoint67.NameField := 'r_cuneonavicular_1';
HAnimJoint67.Center := Vector3(0.1,-0.45,0);
HAnimJoint67.SetUlimit([0,0,0]);
HAnimJoint67.SetLlimit([0,0,0]);
HAnimSegment68 := THAnimSegmentNode.Create;
HAnimSegment68.NameField := 'r_cuneiform_1';
Transform69 := TTransformNode.Create;
Transform69.Translation := Vector3(0.1,-0.45,0);
Shape70 := TShapeNode.Create;
Shape70 := Shape34;
{ .AddChild }
Transform69.AddChildren([Shape70]);
{ .AddChildren }
HAnimSegment68.AddChildren([Transform69]);
Shape71 := TShapeNode.Create;
Appearance72 := TAppearanceNode.Create;
Material73 := TMaterialNode.Create;
Material73.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance72.Material := Material73;
{ .SetAppearance }
Shape71.Appearance := Appearance72;
IndexedLineSet74 := TIndexedLineSetNode.Create;
IndexedLineSet74.SetCoordIndex([0,1]);
Coordinate75 := TCoordinateNode.Create;
Coordinate75.SetPoint([Vector3(0.1,-0.45,0),Vector3(0.1,-0.6,0)]);
{ .SetCoord }
IndexedLineSet74.Coord := Coordinate75;
{ .SetGeometry }
Shape71.Geometry := IndexedLineSet74;
{ .AddChildren }
HAnimSegment68.AddChildren([Shape71]);
{ .AddChildren }
HAnimJoint67.AddChildren([HAnimSegment68]);
HAnimJoint76 := THAnimJointNode.Create;
HAnimJoint76.NameField := 'r_tarsometatarsal_1';
HAnimJoint76.Center := Vector3(0.1,-0.6,0);
HAnimJoint76.SetUlimit([0,0,0]);
HAnimJoint76.SetLlimit([0,0,0]);
HAnimSegment77 := THAnimSegmentNode.Create;
HAnimSegment77.NameField := 'r_metatarsal_1';
Transform78 := TTransformNode.Create;
Transform78.Translation := Vector3(0.1,-0.6,0);
Shape79 := TShapeNode.Create;
Shape79 := Shape34;
{ .AddChild }
Transform78.AddChildren([Shape79]);
{ .AddChildren }
HAnimSegment77.AddChildren([Transform78]);
Shape80 := TShapeNode.Create;
Appearance81 := TAppearanceNode.Create;
Material82 := TMaterialNode.Create;
Material82.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance81.Material := Material82;
{ .SetAppearance }
Shape80.Appearance := Appearance81;
IndexedLineSet83 := TIndexedLineSetNode.Create;
IndexedLineSet83.SetCoordIndex([0,1]);
Coordinate84 := TCoordinateNode.Create;
Coordinate84.SetPoint([Vector3(0.1,-0.6,0),Vector3(0.1,-0.9,0)]);
{ .SetCoord }
IndexedLineSet83.Coord := Coordinate84;
{ .SetGeometry }
Shape80.Geometry := IndexedLineSet83;
{ .AddChildren }
HAnimSegment77.AddChildren([Shape80]);
{ .AddChildren }
HAnimJoint76.AddChildren([HAnimSegment77]);
HAnimJoint85 := THAnimJointNode.Create;
HAnimJoint85.NameField := 'r_metatarsophalangeal_1';
HAnimJoint85.Center := Vector3(0.1,-0.9,0);
HAnimJoint85.SetUlimit([0,0,0]);
HAnimJoint85.SetLlimit([0,0,0]);
HAnimSegment86 := THAnimSegmentNode.Create;
HAnimSegment86.NameField := 'r_tarsal_proximal_phalanx_1';
Transform87 := TTransformNode.Create;
Transform87.Translation := Vector3(0.1,-0.9,0);
Shape88 := TShapeNode.Create;
Shape88 := Shape34;
{ .AddChild }
Transform87.AddChildren([Shape88]);
{ .AddChildren }
HAnimSegment86.AddChildren([Transform87]);
Shape89 := TShapeNode.Create;
Appearance90 := TAppearanceNode.Create;
Material91 := TMaterialNode.Create;
Material91.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance90.Material := Material91;
{ .SetAppearance }
Shape89.Appearance := Appearance90;
IndexedLineSet92 := TIndexedLineSetNode.Create;
IndexedLineSet92.SetCoordIndex([0,1]);
Coordinate93 := TCoordinateNode.Create;
Coordinate93.SetPoint([Vector3(0.1,-0.9,0),Vector3(0.1,-1.05,0)]);
{ .SetCoord }
IndexedLineSet92.Coord := Coordinate93;
{ .SetGeometry }
Shape89.Geometry := IndexedLineSet92;
{ .AddChildren }
HAnimSegment86.AddChildren([Shape89]);
{ .AddChildren }
HAnimJoint85.AddChildren([HAnimSegment86]);
HAnimJoint94 := THAnimJointNode.Create;
HAnimJoint94.NameField := 'r_tarsal_interphalangeal_1';
HAnimJoint94.Center := Vector3(0.1,-1.05,0);
HAnimJoint94.SetUlimit([0,0,0]);
HAnimJoint94.SetLlimit([0,0,0]);
HAnimSegment95 := THAnimSegmentNode.Create;
HAnimSegment95.NameField := 'r_tarsal_distal_phalanx_1';
Transform96 := TTransformNode.Create;
Transform96.Translation := Vector3(0.1,-1.05,0);
Shape97 := TShapeNode.Create;
Shape97 := Shape34;
{ .AddChild }
Transform96.AddChildren([Shape97]);
{ .AddChildren }
HAnimSegment95.AddChildren([Transform96]);
Shape98 := TShapeNode.Create;
Appearance99 := TAppearanceNode.Create;
Material100 := TMaterialNode.Create;
Material100.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance99.Material := Material100;
{ .SetAppearance }
Shape98.Appearance := Appearance99;
IndexedLineSet101 := TIndexedLineSetNode.Create;
IndexedLineSet101.SetCoordIndex([0,1]);
Coordinate102 := TCoordinateNode.Create;
Coordinate102.SetPoint([Vector3(0.1,-1.05,0),Vector3(0.1,-1.1,0)]);
{ .SetCoord }
IndexedLineSet101.Coord := Coordinate102;
{ .SetGeometry }
Shape98.Geometry := IndexedLineSet101;
{ .AddChildren }
HAnimSegment95.AddChildren([Shape98]);
{ .AddChildren }
HAnimJoint94.AddChildren([HAnimSegment95]);
{ .AddChildren }
HAnimJoint85.AddChildren([HAnimJoint94]);
{ .AddChildren }
HAnimJoint76.AddChildren([HAnimJoint85]);
{ .AddChildren }
HAnimJoint67.AddChildren([HAnimJoint76]);
{ .AddChildren }
HAnimJoint48.AddChildren([HAnimJoint67]);
{ CN2 }
HAnimJoint103 := THAnimJointNode.Create;
HAnimJoint103.NameField := 'r_cuneonavicular_2';
HAnimJoint103.Center := Vector3(0,-0.45,0);
HAnimJoint103.SetUlimit([0,0,0]);
HAnimJoint103.SetLlimit([0,0,0]);
HAnimSegment104 := THAnimSegmentNode.Create;
HAnimSegment104.NameField := 'r_cuneiform_2';
Transform105 := TTransformNode.Create;
Transform105.Translation := Vector3(0,-0.45,0);
Shape106 := TShapeNode.Create;
Shape106 := Shape34;
{ .AddChild }
Transform105.AddChildren([Shape106]);
{ .AddChildren }
HAnimSegment104.AddChildren([Transform105]);
Shape107 := TShapeNode.Create;
Appearance108 := TAppearanceNode.Create;
Material109 := TMaterialNode.Create;
Material109.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance108.Material := Material109;
{ .SetAppearance }
Shape107.Appearance := Appearance108;
IndexedLineSet110 := TIndexedLineSetNode.Create;
IndexedLineSet110.SetCoordIndex([0,1]);
Coordinate111 := TCoordinateNode.Create;
Coordinate111.SetPoint([Vector3(0,-0.45,0),Vector3(-0.05,-0.6,0)]);
{ .SetCoord }
IndexedLineSet110.Coord := Coordinate111;
{ .SetGeometry }
Shape107.Geometry := IndexedLineSet110;
{ .AddChildren }
HAnimSegment104.AddChildren([Shape107]);
{ .AddChildren }
HAnimJoint103.AddChildren([HAnimSegment104]);
HAnimJoint112 := THAnimJointNode.Create;
HAnimJoint112.NameField := 'r_tarsometatarsal_2';
HAnimJoint112.Center := Vector3(-0.05,-0.6,0);
HAnimJoint112.SetUlimit([0,0,0]);
HAnimJoint112.SetLlimit([0,0,0]);
HAnimSegment113 := THAnimSegmentNode.Create;
HAnimSegment113.NameField := 'r_metatarsal_2';
Transform114 := TTransformNode.Create;
Transform114.Translation := Vector3(-0.05,-0.6,0);
Shape115 := TShapeNode.Create;
Shape115 := Shape34;
{ .AddChild }
Transform114.AddChildren([Shape115]);
{ .AddChildren }
HAnimSegment113.AddChildren([Transform114]);
Shape116 := TShapeNode.Create;
Appearance117 := TAppearanceNode.Create;
Material118 := TMaterialNode.Create;
Material118.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance117.Material := Material118;
{ .SetAppearance }
Shape116.Appearance := Appearance117;
IndexedLineSet119 := TIndexedLineSetNode.Create;
IndexedLineSet119.SetCoordIndex([0,1]);
Coordinate120 := TCoordinateNode.Create;
Coordinate120.SetPoint([Vector3(-0.05,-0.6,0),Vector3(-0.05,-0.9,0)]);
{ .SetCoord }
IndexedLineSet119.Coord := Coordinate120;
{ .SetGeometry }
Shape116.Geometry := IndexedLineSet119;
{ .AddChildren }
HAnimSegment113.AddChildren([Shape116]);
{ .AddChildren }
HAnimJoint112.AddChildren([HAnimSegment113]);
HAnimJoint121 := THAnimJointNode.Create;
HAnimJoint121.NameField := 'r_metatarsophalangeal_2';
HAnimJoint121.Center := Vector3(-0.05,-0.9,0);
HAnimJoint121.SetUlimit([0,0,0]);
HAnimJoint121.SetLlimit([0,0,0]);
HAnimSegment122 := THAnimSegmentNode.Create;
HAnimSegment122.NameField := 'r_tarsal_proximal_phalanx_2';
Transform123 := TTransformNode.Create;
Transform123.Translation := Vector3(-0.05,-0.9,0);
Shape124 := TShapeNode.Create;
Shape124 := Shape34;
{ .AddChild }
Transform123.AddChildren([Shape124]);
{ .AddChildren }
HAnimSegment122.AddChildren([Transform123]);
Shape125 := TShapeNode.Create;
Appearance126 := TAppearanceNode.Create;
Material127 := TMaterialNode.Create;
Material127.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance126.Material := Material127;
{ .SetAppearance }
Shape125.Appearance := Appearance126;
IndexedLineSet128 := TIndexedLineSetNode.Create;
IndexedLineSet128.SetCoordIndex([0,1]);
Coordinate129 := TCoordinateNode.Create;
Coordinate129.SetPoint([Vector3(-0.05,-0.9,0),Vector3(-0.05,-1.05,0)]);
{ .SetCoord }
IndexedLineSet128.Coord := Coordinate129;
{ .SetGeometry }
Shape125.Geometry := IndexedLineSet128;
{ .AddChildren }
HAnimSegment122.AddChildren([Shape125]);
{ .AddChildren }
HAnimJoint121.AddChildren([HAnimSegment122]);
HAnimJoint130 := THAnimJointNode.Create;
HAnimJoint130.NameField := 'r_tarsal_proximal_interphalangeal_2';
HAnimJoint130.Center := Vector3(-0.05,-1.05,0);
HAnimJoint130.SetUlimit([0,0,0]);
HAnimJoint130.SetLlimit([0,0,0]);
HAnimSegment131 := THAnimSegmentNode.Create;
HAnimSegment131.NameField := 'r_tarsal_middle_phalanx_2';
Transform132 := TTransformNode.Create;
Transform132.Translation := Vector3(-0.05,-1.05,0);
Shape133 := TShapeNode.Create;
Shape133 := Shape34;
{ .AddChild }
Transform132.AddChildren([Shape133]);
{ .AddChildren }
HAnimSegment131.AddChildren([Transform132]);
Shape134 := TShapeNode.Create;
Appearance135 := TAppearanceNode.Create;
Material136 := TMaterialNode.Create;
Material136.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance135.Material := Material136;
{ .SetAppearance }
Shape134.Appearance := Appearance135;
IndexedLineSet137 := TIndexedLineSetNode.Create;
IndexedLineSet137.SetCoordIndex([0,1]);
Coordinate138 := TCoordinateNode.Create;
Coordinate138.SetPoint([Vector3(-0.05,-1.05,0),Vector3(-0.05,-1.12,0)]);
{ .SetCoord }
IndexedLineSet137.Coord := Coordinate138;
{ .SetGeometry }
Shape134.Geometry := IndexedLineSet137;
{ .AddChildren }
HAnimSegment131.AddChildren([Shape134]);
{ .AddChildren }
HAnimJoint130.AddChildren([HAnimSegment131]);
HAnimJoint139 := THAnimJointNode.Create;
HAnimJoint139.NameField := 'r_tarsal_distal_interphalangeal_2';
HAnimJoint139.Center := Vector3(-0.05,-1.12,0);
HAnimJoint139.SetUlimit([0,0,0]);
HAnimJoint139.SetLlimit([0,0,0]);
HAnimSegment140 := THAnimSegmentNode.Create;
HAnimSegment140.NameField := 'r_tarsal_distal_phalanx_2';
Transform141 := TTransformNode.Create;
Transform141.Translation := Vector3(-0.05,-1.12,0);
Shape142 := TShapeNode.Create;
Shape142 := Shape34;
{ .AddChild }
Transform141.AddChildren([Shape142]);
{ .AddChildren }
HAnimSegment140.AddChildren([Transform141]);
Shape143 := TShapeNode.Create;
Appearance144 := TAppearanceNode.Create;
Material145 := TMaterialNode.Create;
Material145.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance144.Material := Material145;
{ .SetAppearance }
Shape143.Appearance := Appearance144;
IndexedLineSet146 := TIndexedLineSetNode.Create;
IndexedLineSet146.SetCoordIndex([0,1]);
Coordinate147 := TCoordinateNode.Create;
Coordinate147.SetPoint([Vector3(-0.05,-1.12,0),Vector3(-0.05,-1.16,0)]);
{ .SetCoord }
IndexedLineSet146.Coord := Coordinate147;
{ .SetGeometry }
Shape143.Geometry := IndexedLineSet146;
{ .AddChildren }
HAnimSegment140.AddChildren([Shape143]);
{ .AddChildren }
HAnimJoint139.AddChildren([HAnimSegment140]);
{ .AddChildren }
HAnimJoint130.AddChildren([HAnimJoint139]);
{ .AddChildren }
HAnimJoint121.AddChildren([HAnimJoint130]);
{ .AddChildren }
HAnimJoint112.AddChildren([HAnimJoint121]);
{ .AddChildren }
HAnimJoint103.AddChildren([HAnimJoint112]);
{ .AddChildren }
HAnimJoint48.AddChildren([HAnimJoint103]);
{ CN3 }
HAnimJoint148 := THAnimJointNode.Create;
HAnimJoint148.NameField := 'r_cuneonavicular_3';
HAnimJoint148.Center := Vector3(-0.1,-0.4,0);
HAnimJoint148.SetUlimit([0,0,0]);
HAnimJoint148.SetLlimit([0,0,0]);
HAnimSegment149 := THAnimSegmentNode.Create;
HAnimSegment149.NameField := 'r_cuneiform_3';
Transform150 := TTransformNode.Create;
Transform150.Translation := Vector3(-0.1,-0.4,0);
Shape151 := TShapeNode.Create;
Shape151 := Shape34;
{ .AddChild }
Transform150.AddChildren([Shape151]);
{ .AddChildren }
HAnimSegment149.AddChildren([Transform150]);
Shape152 := TShapeNode.Create;
Appearance153 := TAppearanceNode.Create;
Material154 := TMaterialNode.Create;
Material154.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance153.Material := Material154;
{ .SetAppearance }
Shape152.Appearance := Appearance153;
IndexedLineSet155 := TIndexedLineSetNode.Create;
IndexedLineSet155.SetCoordIndex([0,1]);
Coordinate156 := TCoordinateNode.Create;
Coordinate156.SetPoint([Vector3(-0.1,-0.4,0),Vector3(-0.15,-0.6,0)]);
{ .SetCoord }
IndexedLineSet155.Coord := Coordinate156;
{ .SetGeometry }
Shape152.Geometry := IndexedLineSet155;
{ .AddChildren }
HAnimSegment149.AddChildren([Shape152]);
{ .AddChildren }
HAnimJoint148.AddChildren([HAnimSegment149]);
HAnimJoint157 := THAnimJointNode.Create;
HAnimJoint157.NameField := 'r_tarsometatarsal_3';
HAnimJoint157.Center := Vector3(-0.15,-0.6,0);
HAnimJoint157.SetUlimit([0,0,0]);
HAnimJoint157.SetLlimit([0,0,0]);
HAnimSegment158 := THAnimSegmentNode.Create;
HAnimSegment158.NameField := 'r_metatarsal_3';
Transform159 := TTransformNode.Create;
Transform159.Translation := Vector3(-0.15,-0.6,0);
Shape160 := TShapeNode.Create;
Shape160 := Shape34;
{ .AddChild }
Transform159.AddChildren([Shape160]);
{ .AddChildren }
HAnimSegment158.AddChildren([Transform159]);
Shape161 := TShapeNode.Create;
Appearance162 := TAppearanceNode.Create;
Material163 := TMaterialNode.Create;
Material163.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance162.Material := Material163;
{ .SetAppearance }
Shape161.Appearance := Appearance162;
IndexedLineSet164 := TIndexedLineSetNode.Create;
IndexedLineSet164.SetCoordIndex([0,1]);
Coordinate165 := TCoordinateNode.Create;
Coordinate165.SetPoint([Vector3(-0.15,-0.6,0),Vector3(-0.15,-0.9,0)]);
{ .SetCoord }
IndexedLineSet164.Coord := Coordinate165;
{ .SetGeometry }
Shape161.Geometry := IndexedLineSet164;
{ .AddChildren }
HAnimSegment158.AddChildren([Shape161]);
{ .AddChildren }
HAnimJoint157.AddChildren([HAnimSegment158]);
HAnimJoint166 := THAnimJointNode.Create;
HAnimJoint166.NameField := 'r_metatarsophalangeal_3';
HAnimJoint166.Center := Vector3(-0.15,-0.9,0);
HAnimJoint166.SetUlimit([0,0,0]);
HAnimJoint166.SetLlimit([0,0,0]);
HAnimSegment167 := THAnimSegmentNode.Create;
HAnimSegment167.NameField := 'r_tarsal_proximal_phalanx_3';
Transform168 := TTransformNode.Create;
Transform168.Translation := Vector3(-0.15,-0.9,0);
Shape169 := TShapeNode.Create;
Shape169 := Shape34;
{ .AddChild }
Transform168.AddChildren([Shape169]);
{ .AddChildren }
HAnimSegment167.AddChildren([Transform168]);
Shape170 := TShapeNode.Create;
Appearance171 := TAppearanceNode.Create;
Material172 := TMaterialNode.Create;
Material172.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance171.Material := Material172;
{ .SetAppearance }
Shape170.Appearance := Appearance171;
IndexedLineSet173 := TIndexedLineSetNode.Create;
IndexedLineSet173.SetCoordIndex([0,1]);
Coordinate174 := TCoordinateNode.Create;
Coordinate174.SetPoint([Vector3(-0.15,-0.9,0),Vector3(-0.15,-1.05,0)]);
{ .SetCoord }
IndexedLineSet173.Coord := Coordinate174;
{ .SetGeometry }
Shape170.Geometry := IndexedLineSet173;
{ .AddChildren }
HAnimSegment167.AddChildren([Shape170]);
{ .AddChildren }
HAnimJoint166.AddChildren([HAnimSegment167]);
HAnimJoint175 := THAnimJointNode.Create;
HAnimJoint175.NameField := 'r_tarsal_proximal_interphalangeal_3';
HAnimJoint175.Center := Vector3(-0.15,-1.05,0);
HAnimJoint175.SetUlimit([0,0,0]);
HAnimJoint175.SetLlimit([0,0,0]);
HAnimSegment176 := THAnimSegmentNode.Create;
HAnimSegment176.NameField := 'r_tarsal_middle_phalanx_3';
Transform177 := TTransformNode.Create;
Transform177.Translation := Vector3(-0.15,-1.05,0);
Shape178 := TShapeNode.Create;
Shape178 := Shape34;
{ .AddChild }
Transform177.AddChildren([Shape178]);
{ .AddChildren }
HAnimSegment176.AddChildren([Transform177]);
Shape179 := TShapeNode.Create;
Appearance180 := TAppearanceNode.Create;
Material181 := TMaterialNode.Create;
Material181.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance180.Material := Material181;
{ .SetAppearance }
Shape179.Appearance := Appearance180;
IndexedLineSet182 := TIndexedLineSetNode.Create;
IndexedLineSet182.SetCoordIndex([0,1]);
Coordinate183 := TCoordinateNode.Create;
Coordinate183.SetPoint([Vector3(-0.15,-1.05,0),Vector3(-0.15,-1.13,0)]);
{ .SetCoord }
IndexedLineSet182.Coord := Coordinate183;
{ .SetGeometry }
Shape179.Geometry := IndexedLineSet182;
{ .AddChildren }
HAnimSegment176.AddChildren([Shape179]);
{ .AddChildren }
HAnimJoint175.AddChildren([HAnimSegment176]);
HAnimJoint184 := THAnimJointNode.Create;
HAnimJoint184.NameField := 'r_tarsal_distal_interphalangeal_3';
HAnimJoint184.Center := Vector3(-0.15,-1.13,0);
HAnimJoint184.SetUlimit([0,0,0]);
HAnimJoint184.SetLlimit([0,0,0]);
HAnimSegment185 := THAnimSegmentNode.Create;
HAnimSegment185.NameField := 'r_tarsal_distal_phalanx_3';
Transform186 := TTransformNode.Create;
Transform186.Translation := Vector3(-0.15,-1.13,0);
Shape187 := TShapeNode.Create;
Shape187 := Shape34;
{ .AddChild }
Transform186.AddChildren([Shape187]);
{ .AddChildren }
HAnimSegment185.AddChildren([Transform186]);
Shape188 := TShapeNode.Create;
Appearance189 := TAppearanceNode.Create;
Material190 := TMaterialNode.Create;
Material190.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance189.Material := Material190;
{ .SetAppearance }
Shape188.Appearance := Appearance189;
IndexedLineSet191 := TIndexedLineSetNode.Create;
IndexedLineSet191.SetCoordIndex([0,1]);
Coordinate192 := TCoordinateNode.Create;
Coordinate192.SetPoint([Vector3(-0.15,-1.13,0),Vector3(-0.15,-1.16,0)]);
{ .SetCoord }
IndexedLineSet191.Coord := Coordinate192;
{ .SetGeometry }
Shape188.Geometry := IndexedLineSet191;
{ .AddChildren }
HAnimSegment185.AddChildren([Shape188]);
{ .AddChildren }
HAnimJoint184.AddChildren([HAnimSegment185]);
{ .AddChildren }
HAnimJoint175.AddChildren([HAnimJoint184]);
{ .AddChildren }
HAnimJoint166.AddChildren([HAnimJoint175]);
{ .AddChildren }
HAnimJoint157.AddChildren([HAnimJoint166]);
{ .AddChildren }
HAnimJoint148.AddChildren([HAnimJoint157]);
{ .AddChildren }
HAnimJoint48.AddChildren([HAnimJoint148]);
{ .AddChildren }
HAnimJoint31.AddChildren([HAnimJoint48]);
{ CC }
HAnimJoint193 := THAnimJointNode.Create;
HAnimJoint193.NameField := 'r_calcaneocuboid';
HAnimJoint193.Center := Vector3(-0.2,0.3,0);
HAnimJoint193.SetUlimit([0,0,0]);
HAnimJoint193.SetLlimit([0,0,0]);
HAnimSegment194 := THAnimSegmentNode.Create;
HAnimSegment194.NameField := 'r_calcaneus';
Transform195 := TTransformNode.Create;
Transform195.Translation := Vector3(-0.2,0.3,0);
Shape196 := TShapeNode.Create;
Shape196 := Shape34;
{ .AddChild }
Transform195.AddChildren([Shape196]);
{ .AddChildren }
HAnimSegment194.AddChildren([Transform195]);
Shape197 := TShapeNode.Create;
Appearance198 := TAppearanceNode.Create;
Material199 := TMaterialNode.Create;
Material199.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance198.Material := Material199;
{ .SetAppearance }
Shape197.Appearance := Appearance198;
IndexedLineSet200 := TIndexedLineSetNode.Create;
IndexedLineSet200.SetCoordIndex([0,1]);
Coordinate201 := TCoordinateNode.Create;
Coordinate201.SetPoint([Vector3(-0.2,0.3,0),Vector3(-0.21,-0.3,0)]);
{ .SetCoord }
IndexedLineSet200.Coord := Coordinate201;
{ .SetGeometry }
Shape197.Geometry := IndexedLineSet200;
{ .AddChildren }
HAnimSegment194.AddChildren([Shape197]);
{ .AddChildren }
HAnimJoint193.AddChildren([HAnimSegment194]);
{ TT }
HAnimJoint202 := THAnimJointNode.Create;
HAnimJoint202.NameField := 'r_transversetarsal';
HAnimJoint202.Center := Vector3(-0.21,-0.3,0);
HAnimJoint202.SetUlimit([0,0,0]);
HAnimJoint202.SetLlimit([0,0,0]);
HAnimSegment203 := THAnimSegmentNode.Create;
HAnimSegment203.NameField := 'r_cuboid';
Transform204 := TTransformNode.Create;
Transform204.Translation := Vector3(-0.21,-0.3,0);
Shape205 := TShapeNode.Create;
Shape205 := Shape34;
{ .AddChild }
Transform204.AddChildren([Shape205]);
{ .AddChildren }
HAnimSegment203.AddChildren([Transform204]);
Shape206 := TShapeNode.Create;
Appearance207 := TAppearanceNode.Create;
Material208 := TMaterialNode.Create;
Material208.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance207.Material := Material208;
{ .SetAppearance }
Shape206.Appearance := Appearance207;
IndexedLineSet209 := TIndexedLineSetNode.Create;
IndexedLineSet209.SetCoordIndex([0,1]);
Coordinate210 := TCoordinateNode.Create;
Coordinate210.SetPoint([Vector3(-0.21,-0.3,0),Vector3(-0.25,-0.58,0)]);
{ .SetCoord }
IndexedLineSet209.Coord := Coordinate210;
{ .SetGeometry }
Shape206.Geometry := IndexedLineSet209;
{ .AddChildren }
HAnimSegment203.AddChildren([Shape206]);
Shape211 := TShapeNode.Create;
Appearance212 := TAppearanceNode.Create;
Material213 := TMaterialNode.Create;
Material213.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance212.Material := Material213;
{ .SetAppearance }
Shape211.Appearance := Appearance212;
IndexedLineSet214 := TIndexedLineSetNode.Create;
IndexedLineSet214.SetCoordIndex([0,1]);
Coordinate215 := TCoordinateNode.Create;
Coordinate215.SetPoint([Vector3(-0.21,-0.3,0),Vector3(-0.33,-0.52,0)]);
{ .SetCoord }
IndexedLineSet214.Coord := Coordinate215;
{ .SetGeometry }
Shape211.Geometry := IndexedLineSet214;
{ .AddChildren }
HAnimSegment203.AddChildren([Shape211]);
{ .AddChildren }
HAnimJoint202.AddChildren([HAnimSegment203]);
{ TMT4 }
HAnimJoint216 := THAnimJointNode.Create;
HAnimJoint216.NameField := 'r_tarsometatarsal_4';
HAnimJoint216.Center := Vector3(-0.25,-0.58,0);
HAnimJoint216.SetUlimit([0,0,0]);
HAnimJoint216.SetLlimit([0,0,0]);
HAnimSegment217 := THAnimSegmentNode.Create;
HAnimSegment217.NameField := 'r_metatarsal_4';
Transform218 := TTransformNode.Create;
Transform218.Translation := Vector3(-0.25,-0.58,0);
Shape219 := TShapeNode.Create;
Shape219 := Shape34;
{ .AddChild }
Transform218.AddChildren([Shape219]);
{ .AddChildren }
HAnimSegment217.AddChildren([Transform218]);
Shape220 := TShapeNode.Create;
Appearance221 := TAppearanceNode.Create;
Material222 := TMaterialNode.Create;
Material222.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance221.Material := Material222;
{ .SetAppearance }
Shape220.Appearance := Appearance221;
IndexedLineSet223 := TIndexedLineSetNode.Create;
IndexedLineSet223.SetCoordIndex([0,1]);
Coordinate224 := TCoordinateNode.Create;
Coordinate224.SetPoint([Vector3(-0.25,-0.58,0),Vector3(-0.25,-0.87,0)]);
{ .SetCoord }
IndexedLineSet223.Coord := Coordinate224;
{ .SetGeometry }
Shape220.Geometry := IndexedLineSet223;
{ .AddChildren }
HAnimSegment217.AddChildren([Shape220]);
{ .AddChildren }
HAnimJoint216.AddChildren([HAnimSegment217]);
HAnimJoint225 := THAnimJointNode.Create;
HAnimJoint225.NameField := 'r_metatarsophalangeal_4';
HAnimJoint225.Center := Vector3(-0.25,-0.87,0);
HAnimJoint225.SetUlimit([0,0,0]);
HAnimJoint225.SetLlimit([0,0,0]);
HAnimSegment226 := THAnimSegmentNode.Create;
HAnimSegment226.NameField := 'r_tarsal_proximal_phalanx_4';
Transform227 := TTransformNode.Create;
Transform227.Translation := Vector3(-0.25,-0.87,0);
Shape228 := TShapeNode.Create;
Shape228 := Shape34;
{ .AddChild }
Transform227.AddChildren([Shape228]);
{ .AddChildren }
HAnimSegment226.AddChildren([Transform227]);
Shape229 := TShapeNode.Create;
Appearance230 := TAppearanceNode.Create;
Material231 := TMaterialNode.Create;
Material231.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance230.Material := Material231;
{ .SetAppearance }
Shape229.Appearance := Appearance230;
IndexedLineSet232 := TIndexedLineSetNode.Create;
IndexedLineSet232.SetCoordIndex([0,1]);
Coordinate233 := TCoordinateNode.Create;
Coordinate233.SetPoint([Vector3(-0.25,-0.87,0),Vector3(-0.25,-1,0)]);
{ .SetCoord }
IndexedLineSet232.Coord := Coordinate233;
{ .SetGeometry }
Shape229.Geometry := IndexedLineSet232;
{ .AddChildren }
HAnimSegment226.AddChildren([Shape229]);
{ .AddChildren }
HAnimJoint225.AddChildren([HAnimSegment226]);
HAnimJoint234 := THAnimJointNode.Create;
HAnimJoint234.NameField := 'r_tarsal_proximal_interphalangeal_4';
HAnimJoint234.Center := Vector3(-0.25,-1,0);
HAnimJoint234.SetUlimit([0,0,0]);
HAnimJoint234.SetLlimit([0,0,0]);
HAnimSegment235 := THAnimSegmentNode.Create;
HAnimSegment235.NameField := 'r_tarsal_middle_phalanx_4';
Transform236 := TTransformNode.Create;
Transform236.Translation := Vector3(-0.25,-1,0);
Shape237 := TShapeNode.Create;
Shape237 := Shape34;
{ .AddChild }
Transform236.AddChildren([Shape237]);
{ .AddChildren }
HAnimSegment235.AddChildren([Transform236]);
Shape238 := TShapeNode.Create;
Appearance239 := TAppearanceNode.Create;
Material240 := TMaterialNode.Create;
Material240.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance239.Material := Material240;
{ .SetAppearance }
Shape238.Appearance := Appearance239;
IndexedLineSet241 := TIndexedLineSetNode.Create;
IndexedLineSet241.SetCoordIndex([0,1]);
Coordinate242 := TCoordinateNode.Create;
Coordinate242.SetPoint([Vector3(-0.25,-1,0),Vector3(-0.25,-1.1,0)]);
{ .SetCoord }
IndexedLineSet241.Coord := Coordinate242;
{ .SetGeometry }
Shape238.Geometry := IndexedLineSet241;
{ .AddChildren }
HAnimSegment235.AddChildren([Shape238]);
{ .AddChildren }
HAnimJoint234.AddChildren([HAnimSegment235]);
HAnimJoint243 := THAnimJointNode.Create;
HAnimJoint243.NameField := 'r_tarsal_distal_interphalangeal_4';
HAnimJoint243.Center := Vector3(-0.25,-1.1,0);
HAnimJoint243.SetUlimit([0,0,0]);
HAnimJoint243.SetLlimit([0,0,0]);
HAnimSegment244 := THAnimSegmentNode.Create;
HAnimSegment244.NameField := 'r_tarsal_distal_phalanx_4';
Transform245 := TTransformNode.Create;
Transform245.Translation := Vector3(-0.25,-1.1,0);
Shape246 := TShapeNode.Create;
Shape246 := Shape34;
{ .AddChild }
Transform245.AddChildren([Shape246]);
{ .AddChildren }
HAnimSegment244.AddChildren([Transform245]);
Shape247 := TShapeNode.Create;
Appearance248 := TAppearanceNode.Create;
Material249 := TMaterialNode.Create;
Material249.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance248.Material := Material249;
{ .SetAppearance }
Shape247.Appearance := Appearance248;
IndexedLineSet250 := TIndexedLineSetNode.Create;
IndexedLineSet250.SetCoordIndex([0,1]);
Coordinate251 := TCoordinateNode.Create;
Coordinate251.SetPoint([Vector3(-0.25,-1.1,0),Vector3(-0.25,-1.15,0)]);
{ .SetCoord }
IndexedLineSet250.Coord := Coordinate251;
{ .SetGeometry }
Shape247.Geometry := IndexedLineSet250;
{ .AddChildren }
HAnimSegment244.AddChildren([Shape247]);
{ .AddChildren }
HAnimJoint243.AddChildren([HAnimSegment244]);
{ .AddChildren }
HAnimJoint234.AddChildren([HAnimJoint243]);
{ .AddChildren }
HAnimJoint225.AddChildren([HAnimJoint234]);
{ .AddChildren }
HAnimJoint216.AddChildren([HAnimJoint225]);
{ .AddChildren }
HAnimJoint202.AddChildren([HAnimJoint216]);
{ TMT5 }
HAnimJoint252 := THAnimJointNode.Create;
HAnimJoint252.NameField := 'r_tarsometatarsal_5';
HAnimJoint252.Center := Vector3(-0.33,-0.52,0);
HAnimJoint252.SetUlimit([0,0,0]);
HAnimJoint252.SetLlimit([0,0,0]);
HAnimSegment253 := THAnimSegmentNode.Create;
HAnimSegment253.NameField := 'r_metatarsal_5';
Transform254 := TTransformNode.Create;
Transform254.Translation := Vector3(-0.33,-0.52,0);
Shape255 := TShapeNode.Create;
Shape255 := Shape34;
{ .AddChild }
Transform254.AddChildren([Shape255]);
{ .AddChildren }
HAnimSegment253.AddChildren([Transform254]);
Shape256 := TShapeNode.Create;
Appearance257 := TAppearanceNode.Create;
Material258 := TMaterialNode.Create;
Material258.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance257.Material := Material258;
{ .SetAppearance }
Shape256.Appearance := Appearance257;
IndexedLineSet259 := TIndexedLineSetNode.Create;
IndexedLineSet259.SetCoordIndex([0,1]);
Coordinate260 := TCoordinateNode.Create;
Coordinate260.SetPoint([Vector3(-0.33,-0.52,0),Vector3(-0.34,-0.8,0)]);
{ .SetCoord }
IndexedLineSet259.Coord := Coordinate260;
{ .SetGeometry }
Shape256.Geometry := IndexedLineSet259;
{ .AddChildren }
HAnimSegment253.AddChildren([Shape256]);
{ .AddChildren }
HAnimJoint252.AddChildren([HAnimSegment253]);
HAnimJoint261 := THAnimJointNode.Create;
HAnimJoint261.NameField := 'r_metatarsophalangeal_5';
HAnimJoint261.Center := Vector3(-0.34,-0.8,0);
HAnimJoint261.SetUlimit([0,0,0]);
HAnimJoint261.SetLlimit([0,0,0]);
HAnimSegment262 := THAnimSegmentNode.Create;
HAnimSegment262.NameField := 'r_tarsal_proximal_phalanx_5';
Transform263 := TTransformNode.Create;
Transform263.Translation := Vector3(-0.34,-0.8,0);
Shape264 := TShapeNode.Create;
Shape264 := Shape34;
{ .AddChild }
Transform263.AddChildren([Shape264]);
{ .AddChildren }
HAnimSegment262.AddChildren([Transform263]);
Shape265 := TShapeNode.Create;
Appearance266 := TAppearanceNode.Create;
Material267 := TMaterialNode.Create;
Material267.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance266.Material := Material267;
{ .SetAppearance }
Shape265.Appearance := Appearance266;
IndexedLineSet268 := TIndexedLineSetNode.Create;
IndexedLineSet268.SetCoordIndex([0,1]);
Coordinate269 := TCoordinateNode.Create;
Coordinate269.SetPoint([Vector3(-0.34,-0.8,0),Vector3(-0.34,-0.95,0)]);
{ .SetCoord }
IndexedLineSet268.Coord := Coordinate269;
{ .SetGeometry }
Shape265.Geometry := IndexedLineSet268;
{ .AddChildren }
HAnimSegment262.AddChildren([Shape265]);
{ .AddChildren }
HAnimJoint261.AddChildren([HAnimSegment262]);
HAnimJoint270 := THAnimJointNode.Create;
HAnimJoint270.NameField := 'r_tarsal_proximal_interphalangeal_5';
HAnimJoint270.Center := Vector3(-0.34,-0.95,0);
HAnimJoint270.SetUlimit([0,0,0]);
HAnimJoint270.SetLlimit([0,0,0]);
HAnimSegment271 := THAnimSegmentNode.Create;
HAnimSegment271.NameField := 'r_tarsal_middle_phalanx_5';
Transform272 := TTransformNode.Create;
Transform272.Translation := Vector3(-0.34,-0.95,0);
Shape273 := TShapeNode.Create;
Shape273 := Shape34;
{ .AddChild }
Transform272.AddChildren([Shape273]);
{ .AddChildren }
HAnimSegment271.AddChildren([Transform272]);
Shape274 := TShapeNode.Create;
Appearance275 := TAppearanceNode.Create;
Material276 := TMaterialNode.Create;
Material276.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance275.Material := Material276;
{ .SetAppearance }
Shape274.Appearance := Appearance275;
IndexedLineSet277 := TIndexedLineSetNode.Create;
IndexedLineSet277.SetCoordIndex([0,1]);
Coordinate278 := TCoordinateNode.Create;
Coordinate278.SetPoint([Vector3(-0.34,-0.95,0),Vector3(-0.34,-1.05,0)]);
{ .SetCoord }
IndexedLineSet277.Coord := Coordinate278;
{ .SetGeometry }
Shape274.Geometry := IndexedLineSet277;
{ .AddChildren }
HAnimSegment271.AddChildren([Shape274]);
{ .AddChildren }
HAnimJoint270.AddChildren([HAnimSegment271]);
HAnimJoint279 := THAnimJointNode.Create;
HAnimJoint279.NameField := 'r_tarsal_distal_interphalangeal_5';
HAnimJoint279.Center := Vector3(-0.34,-1.05,0);
HAnimJoint279.SetUlimit([0,0,0]);
HAnimJoint279.SetLlimit([0,0,0]);
HAnimSegment280 := THAnimSegmentNode.Create;
HAnimSegment280.NameField := 'r_tarsal_distal_phalanx_5';
Transform281 := TTransformNode.Create;
Transform281.Translation := Vector3(-0.34,-1.05,0);
Shape282 := TShapeNode.Create;
Shape282 := Shape34;
{ .AddChild }
Transform281.AddChildren([Shape282]);
{ .AddChildren }
HAnimSegment280.AddChildren([Transform281]);
Shape283 := TShapeNode.Create;
Appearance284 := TAppearanceNode.Create;
Material285 := TMaterialNode.Create;
Material285.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance284.Material := Material285;
{ .SetAppearance }
Shape283.Appearance := Appearance284;
IndexedLineSet286 := TIndexedLineSetNode.Create;
IndexedLineSet286.SetCoordIndex([0,1]);
Coordinate287 := TCoordinateNode.Create;
Coordinate287.SetPoint([Vector3(-0.34,-1.05,0),Vector3(-0.34,-1.08,0)]);
{ .SetCoord }
IndexedLineSet286.Coord := Coordinate287;
{ .SetGeometry }
Shape283.Geometry := IndexedLineSet286;
{ .AddChildren }
HAnimSegment280.AddChildren([Shape283]);
{ .AddChildren }
HAnimJoint279.AddChildren([HAnimSegment280]);
{ .AddChildren }
HAnimJoint270.AddChildren([HAnimJoint279]);
{ .AddChildren }
HAnimJoint261.AddChildren([HAnimJoint270]);
{ .AddChildren }
HAnimJoint252.AddChildren([HAnimJoint261]);
{ .AddChildren }
HAnimJoint202.AddChildren([HAnimJoint252]);
{ .AddChildren }
HAnimJoint193.AddChildren([HAnimJoint202]);
{ .AddChildren }
HAnimJoint31.AddChildren([HAnimJoint193]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimJoint31]);
{ .AddSkeleton }
HAnimHumanoid27.SetSkeleton([HAnimJoint30]);
HAnimJoint288 := THAnimJointNode.Create;
HAnimJoint288 := HAnimJoint30;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint288;
HAnimJoint289 := THAnimJointNode.Create;
HAnimJoint289 := HAnimJoint193;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint289;
HAnimJoint290 := THAnimJointNode.Create;
HAnimJoint290 := HAnimJoint67;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint290;
HAnimJoint291 := THAnimJointNode.Create;
HAnimJoint291 := HAnimJoint103;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint291;
HAnimJoint292 := THAnimJointNode.Create;
HAnimJoint292 := HAnimJoint148;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint292;
HAnimJoint293 := THAnimJointNode.Create;
HAnimJoint293 := HAnimJoint85;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint293;
HAnimJoint294 := THAnimJointNode.Create;
HAnimJoint294 := HAnimJoint121;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint294;
HAnimJoint295 := THAnimJointNode.Create;
HAnimJoint295 := HAnimJoint166;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint295;
HAnimJoint296 := THAnimJointNode.Create;
HAnimJoint296 := HAnimJoint225;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint296;
HAnimJoint297 := THAnimJointNode.Create;
HAnimJoint297 := HAnimJoint261;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint297;
HAnimJoint298 := THAnimJointNode.Create;
HAnimJoint298 := HAnimJoint48;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint298;
HAnimJoint299 := THAnimJointNode.Create;
HAnimJoint299 := HAnimJoint31;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint299;
HAnimJoint300 := THAnimJointNode.Create;
HAnimJoint300 := HAnimJoint139;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint300;
HAnimJoint301 := THAnimJointNode.Create;
HAnimJoint301 := HAnimJoint184;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint301;
HAnimJoint302 := THAnimJointNode.Create;
HAnimJoint302 := HAnimJoint243;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint302;
HAnimJoint303 := THAnimJointNode.Create;
HAnimJoint303 := HAnimJoint279;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint303;
HAnimJoint304 := THAnimJointNode.Create;
HAnimJoint304 := HAnimJoint94;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint304;
HAnimJoint305 := THAnimJointNode.Create;
HAnimJoint305 := HAnimJoint130;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint305;
HAnimJoint306 := THAnimJointNode.Create;
HAnimJoint306 := HAnimJoint175;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint306;
HAnimJoint307 := THAnimJointNode.Create;
HAnimJoint307 := HAnimJoint234;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint307;
HAnimJoint308 := THAnimJointNode.Create;
HAnimJoint308 := HAnimJoint270;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint308;
HAnimJoint309 := THAnimJointNode.Create;
HAnimJoint309 := HAnimJoint76;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint309;
HAnimJoint310 := THAnimJointNode.Create;
HAnimJoint310 := HAnimJoint112;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint310;
HAnimJoint311 := THAnimJointNode.Create;
HAnimJoint311 := HAnimJoint157;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint311;
HAnimJoint312 := THAnimJointNode.Create;
HAnimJoint312 := HAnimJoint216;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint312;
HAnimJoint313 := THAnimJointNode.Create;
HAnimJoint313 := HAnimJoint252;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint313;
HAnimJoint314 := THAnimJointNode.Create;
HAnimJoint314 := HAnimJoint202;
{ .AddJoints }
HAnimHumanoid27.Joints := HAnimJoint314;
HAnimSegment315 := THAnimSegmentNode.Create;
HAnimSegment315 := HAnimSegment194;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment315;
HAnimSegment316 := THAnimSegmentNode.Create;
HAnimSegment316 := HAnimSegment203;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment316;
HAnimSegment317 := THAnimSegmentNode.Create;
HAnimSegment317 := HAnimSegment68;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment317;
HAnimSegment318 := THAnimSegmentNode.Create;
HAnimSegment318 := HAnimSegment104;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment318;
HAnimSegment319 := THAnimSegmentNode.Create;
HAnimSegment319 := HAnimSegment149;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment319;
HAnimSegment320 := THAnimSegmentNode.Create;
HAnimSegment320 := HAnimSegment77;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment320;
HAnimSegment321 := THAnimSegmentNode.Create;
HAnimSegment321 := HAnimSegment113;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment321;
HAnimSegment322 := THAnimSegmentNode.Create;
HAnimSegment322 := HAnimSegment158;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment322;
HAnimSegment323 := THAnimSegmentNode.Create;
HAnimSegment323 := HAnimSegment217;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment323;
HAnimSegment324 := THAnimSegmentNode.Create;
HAnimSegment324 := HAnimSegment253;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment324;
HAnimSegment325 := THAnimSegmentNode.Create;
HAnimSegment325 := HAnimSegment49;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment325;
HAnimSegment326 := THAnimSegmentNode.Create;
HAnimSegment326 := HAnimSegment32;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment326;
HAnimSegment327 := THAnimSegmentNode.Create;
HAnimSegment327 := HAnimSegment95;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment327;
HAnimSegment328 := THAnimSegmentNode.Create;
HAnimSegment328 := HAnimSegment140;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment328;
HAnimSegment329 := THAnimSegmentNode.Create;
HAnimSegment329 := HAnimSegment185;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment329;
HAnimSegment330 := THAnimSegmentNode.Create;
HAnimSegment330 := HAnimSegment244;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment330;
HAnimSegment331 := THAnimSegmentNode.Create;
HAnimSegment331 := HAnimSegment280;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment331;
HAnimSegment332 := THAnimSegmentNode.Create;
HAnimSegment332 := HAnimSegment131;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment332;
HAnimSegment333 := THAnimSegmentNode.Create;
HAnimSegment333 := HAnimSegment176;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment333;
HAnimSegment334 := THAnimSegmentNode.Create;
HAnimSegment334 := HAnimSegment235;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment334;
HAnimSegment335 := THAnimSegmentNode.Create;
HAnimSegment335 := HAnimSegment271;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment335;
HAnimSegment336 := THAnimSegmentNode.Create;
HAnimSegment336 := HAnimSegment86;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment336;
HAnimSegment337 := THAnimSegmentNode.Create;
HAnimSegment337 := HAnimSegment122;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment337;
HAnimSegment338 := THAnimSegmentNode.Create;
HAnimSegment338 := HAnimSegment167;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment338;
HAnimSegment339 := THAnimSegmentNode.Create;
HAnimSegment339 := HAnimSegment226;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment339;
HAnimSegment340 := THAnimSegmentNode.Create;
HAnimSegment340 := HAnimSegment262;
{ .AddSegments }
HAnimHumanoid27.Segments := HAnimSegment340;
{ .AddChildren }
Group25.AddChildren([HAnimHumanoid27]);
{ .AddGroup }
X3D0.AddChildren([Group25]);
Result := X3D0;
end;
