(ns x3dclsail.HAnimModelFootRight
  (:import 	(org.web3d.x3d.jsail.Shape AcousticProperties Appearance FillProperties LineProperties Material PhysicalMaterial PointProperties Shape TwoSidedMaterial UnlitMaterial)
	(org.web3d.x3d.jsail.Sound Analyser AudioClip AudioDestination BiquadFilter BufferAudioSource ChannelMerger ChannelSelector ChannelSplitter Convolver Delay DynamicsCompressor Gain ListenerPointSource MicrophoneSource OscillatorSource PeriodicWave Sound SpatialSound StreamAudioDestination StreamAudioSource WaveShaper)
	(org.web3d.x3d.jsail.Networking Anchor Inline LoadSensor)
	(org.web3d.x3d.jsail.Geometry2D Arc2D ArcClose2D Circle2D Disk2D Polyline2D Polypoint2D Rectangle2D TriangleSet2D)
	(org.web3d.x3d.jsail.EnvironmentalEffects Background Fog FogCoordinate LocalFog TextureBackground)
	(org.web3d.x3d.jsail.RigidBodyPhysics BallJoint CollidableOffset CollidableShape CollisionCollection CollisionSensor CollisionSpace Contact DoubleAxisHingeJoint MotorJoint RigidBody RigidBodyCollection SingleAxisHingeJoint SliderJoint UniversalJoint)
	(org.web3d.x3d.jsail.Navigation Billboard Collision LOD NavigationInfo OrthoViewpoint Viewpoint ViewpointGroup)
	(org.web3d.x3d.jsail.VolumeRendering BlendedVolumeStyle BoundaryEnhancementVolumeStyle CartoonVolumeStyle ComposedVolumeStyle EdgeEnhancementVolumeStyle IsoSurfaceVolumeData OpacityMapVolumeStyle ProjectionVolumeStyle SegmentedVolumeData ShadedVolumeStyle SilhouetteEnhancementVolumeStyle ToneMappedVolumeStyle VolumeData)
	(org.web3d.x3d.jsail.EventUtilities BooleanFilter BooleanSequencer BooleanToggle BooleanTrigger IntegerSequencer IntegerTrigger TimeTrigger)
	(org.web3d.x3d.jsail.ParticleSystems BoundedPhysicsModel ConeEmitter ExplosionEmitter ForcePhysicsModel ParticleSystem PointEmitter PolylineEmitter SurfaceEmitter VolumeEmitter WindPhysicsModel)
	(org.web3d.x3d.jsail.Geometry3D Box Cone Cylinder ElevationGrid Extrusion IndexedFaceSet Sphere)
	(org.web3d.x3d.jsail.CADGeometry CADAssembly CADFace CADLayer CADPart IndexedQuadSet QuadSet)
	(org.web3d.x3d.jsail.Rendering ClipPlane Color ColorRGBA Coordinate CoordinateDouble IndexedLineSet IndexedTriangleFanSet IndexedTriangleSet IndexedTriangleStripSet LineSet Normal PointSet TriangleFanSet TriangleSet TriangleStripSet)
	(org.web3d.x3d.jsail.Followers ColorChaser ColorDamper CoordinateChaser CoordinateDamper OrientationChaser OrientationDamper PositionChaser PositionChaser2D PositionDamper PositionDamper2D ScalarChaser ScalarDamper TexCoordChaser2D TexCoordDamper2D)
	(org.web3d.x3d.jsail.Interpolation ColorInterpolator CoordinateInterpolator CoordinateInterpolator2D EaseInEaseOut NormalInterpolator OrientationInterpolator PositionInterpolator PositionInterpolator2D ScalarInterpolator SplinePositionInterpolator SplinePositionInterpolator2D SplineScalarInterpolator SquadOrientationInterpolator)
	(org.web3d.x3d.jsail.CubeMapTexturing ComposedCubeMapTexture GeneratedCubeMapTexture ImageCubeMapTexture)
	(org.web3d.x3d.jsail.Shaders ComposedShader FloatVertexAttribute Matrix3VertexAttribute Matrix4VertexAttribute PackagedShader ProgramShader ShaderPart ShaderProgram)
	(org.web3d.x3d.jsail.Texturing3D ComposedTexture3D ImageTexture3D PixelTexture3D TextureCoordinate3D TextureCoordinate4D TextureTransform3D TextureTransformMatrix3D)
	(org.web3d.x3d.jsail.NURBS Contour2D ContourPolyline2D NurbsCurve NurbsCurve2D NurbsOrientationInterpolator NurbsPatchSurface NurbsPositionInterpolator NurbsSet NurbsSurfaceInterpolator NurbsSweptSurface NurbsSwungSurface NurbsTextureCoordinate NurbsTrimmedSurface)
	(org.web3d.x3d.jsail.PointingDeviceSensor CylinderSensor PlaneSensor SphereSensor TouchSensor)
	(org.web3d.x3d.jsail.Lighting DirectionalLight PointLight SpotLight)
	(org.web3d.x3d.jsail.DIS DISEntityManager DISEntityTypeMapping EspduTransform ReceiverPdu SignalPdu TransmitterPdu)
	(org.web3d.x3d.jsail.Text FontStyle Text)
	(org.web3d.x3d.jsail.Geospatial GeoCoordinate GeoElevationGrid GeoLocation GeoLOD GeoMetadata GeoOrigin GeoPositionInterpolator GeoProximitySensor GeoTouchSensor GeoTransform GeoViewpoint)
	(org.web3d.x3d.jsail.Grouping Group StaticGroup Switch Transform)
	(org.web3d.x3d.jsail.HAnim HAnimDisplacer HAnimHumanoid HAnimJoint HAnimMotion HAnimSegment HAnimSite)
	(org.web3d.x3d.jsail.Texturing ImageTexture MovieTexture MultiTexture MultiTextureCoordinate MultiTextureTransform PixelTexture TextureCoordinate TextureCoordinateGenerator TextureProperties TextureTransform)
	(org.web3d.x3d.jsail.KeyDeviceSensor KeySensor StringSensor)
	(org.web3d.x3d.jsail.Layering Layer LayerSet Viewport)
	(org.web3d.x3d.jsail.Layout Layout LayoutGroup LayoutLayer ScreenFontStyle ScreenGroup)
	(org.web3d.x3d.jsail.Picking LinePickSensor PickableGroup PointPickSensor PrimitivePickSensor VolumePickSensor)
	(org.web3d.x3d.jsail.Core MetadataBoolean MetadataDouble MetadataFloat MetadataInteger MetadataSet MetadataString ProtoInstance WorldInfo component connect ExternProtoDeclare field fieldValue head IS ProtoBody ProtoDeclare ProtoInterface ROUTE Scene unit X3D CommentsBlock)
	(org.web3d.x3d.jsail.EnvironmentalSensor ProximitySensor TransformSensor VisibilitySensor)
	(org.web3d.x3d.jsail.Scripting Script)
	(org.web3d.x3d.jsail.TextureProjection TextureProjector TextureProjectorParallel)
	(org.web3d.x3d.jsail.Time TimeSensor)
	(org.web3d.x3d.jsail.fields SFBool MFBool SFColor MFColor SFColorRGBA MFColorRGBA SFDouble MFDouble SFFloat MFFloat SFImage MFImage SFInt32 MFInt32 SFMatrix3d MFMatrix3d SFMatrix3f MFMatrix3f SFMatrix4d MFMatrix4d SFMatrix4f MFMatrix4f SFNode MFNode SFRotation MFRotation SFString MFString SFTime MFTime SFVec2d MFVec2d SFVec2f MFVec2f SFVec3d MFVec3d SFVec3f MFVec3f SFVec4d MFVec4d SFVec4f MFVec4f)
	(org.web3d.x3d.jsail ConfigurationProperties)
))(def EXPORT org.web3d.x3d.jsail.Networking.EXPORT)
(def IMPORT org.web3d.x3d.jsail.Networking.IMPORT)
(def X3D0 (doto (X3D.)
    (.setProfile "Immersive")
    (.setVersion "4.0")
    (.setHead (doto (head. )
        (.addComponent (doto (component. )
            (.setName "HAnim")
            (.setLevel 1)
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "title")
            (.setContent "HAnimModelFootRight.x3d")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "description")
            (.setContent "Right foot, using high-fidelity definitions for HAnim version 2.0")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "creator")
            (.setContent "Kwan-Hee YOO, Don Brutzman and Joe Williams")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "created")
            (.setContent "26 January 2015")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "modified")
            (.setContent "23 December 2021")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "warning")
            (.setContent "not yet to scale")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "TODO")
            (.setContent "Update all values to match HAnim2 A.7 Level of articulation four LOA-4")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "TODO")
            (.setContent "Add links to figures")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "TODO")
            (.setContent "Add Viewpoints to enable inspection")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "info")
            (.setContent "TODO describe how to compute and apply offsets for center values whenever attaching this appendage to a body")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "warning")
            (.setContent "TODO will X3D HAnim component add a new level to support LOA-4 functionality?")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "reference")
            (.setContent "https://www.web3d.org/working-groups/humanoid-animation-HAnim")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "reference")
            (.setContent "https://www.web3d.org/documents/specifications/19774/V2.0")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "reference")
            (.setContent "https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#TheFeet")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "reference")
            (.setContent "https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#f-FootJoints")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "reference")
            (.setContent "https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#Hierarchy4")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "reference")
            (.setContent "https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-WD2/Part01/components/hanim.html")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "subject")
            (.setContent "X3D HAnim humanoid animation")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "TODO")
            (.setContent "Integrate and confirm Segment/Joint names, Viewpoints.")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "identifier")
            (.setContent "https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Characters/HAnimModelFootRight.x3d")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "generator")
            (.setContent "X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit")
        ))
        (.addMeta (doto (org.web3d.x3d.jsail.Core.meta. )
            (.setName "license")
            (.setContent "../license.html")
        ))
    ))
    (.setScene (doto (Scene. )
        (.addChildren (doto (WorldInfo. )
            (.setTitle "HAnimModelFootRight.x3d")
        ))
        (.addChildren (doto (HAnimHumanoid. )
            (.setName "Foot_Right")
            (.setDEF "hanim_Foot_Right")
            (.setLoa 4)
            (.setVersion "2.0")
;original HAnimHumanoid info='\"authorName=Kwan-Hee YOO, Don Brutzman and Joe Williams\"'
            (.setMetadata (doto (MetadataSet. )
                (.setName "HAnimHumanoid.info")
                (.setReference "https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/ObjectInterfaces.html#Humanoid")
                (.addValue (doto (MetadataString. )
                    (.setName "authorName")
                    (.setValue (into-array ["Kwan-Hee YOO, Don Brutzman and Joe Williams"]))
                ))
            ))
            (.addSkeleton (doto (HAnimJoint. )
                (.setName "humanoid_root")
                (.setDEF "hanim_humanoid_root")
                (.setUlimit (float-array [0 0 0]))
                (.setLlimit (float-array [0 0 0]))
                (.setContainerFieldOverride "skeleton")
;Might consider putting a HAnimSegment here, but that doesn't help with re-use of this foot model
                (.addChildren (doto (HAnimJoint. )
                    (.setName "r_talocrural")
                    (.setDEF "hanim_r_talocrural")
                    (.setDescription "connection joint of foot to leg above")
                    (.setUlimit (float-array [0 0 0]))
                    (.setLlimit (float-array [0 0 0]))
                    (.addChildren (doto (HAnimSegment. )
                        (.setName "r_talus")
                        (.setDEF "hanim_r_talus")
                        (.addChildren (doto (Transform. )
                            (.addChild (doto (Shape. )
                                (.setDEF "HAnimJointShape")
                                (.setGeometry (doto (Sphere. )
                                    (.setRadius 0.025)
                                ))
                                (.setAppearance (doto (Appearance. )
                                    (.setDEF "HAnimJointAppearance")
                                    (.setMaterial (doto (Material. )
                                        (.setDiffuseColor (float-array [0 0 1]))
                                    ))
                                ))
                            ))
                        ))
                        (.addChildren (doto (Shape. )
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                    (.setEmissiveColor (float-array [1 1 1]))
                                ))
                            ))
                            (.setGeometry (doto (IndexedLineSet. )
                                (.setDEF "TCtoTCN")
                                (.setCoordIndex (int-array [0 1]))
                                (.setCoord (doto (Coordinate. )
                                    (.setPoint (float-array [0 0 0 0 -0.3 0]))
                                ))
                            ))
                        ))
                        (.addChildren (doto (Shape. )
                            (.setAppearance (doto (Appearance. )
                                (.setMaterial (doto (Material. )
                                    (.setEmissiveColor (float-array [1 1 1]))
                                ))
                            ))
                            (.setGeometry (doto (IndexedLineSet. )
                                (.setDEF "TCtoCC")
                                (.setCoordIndex (int-array [0 1]))
                                (.setCoord (doto (Coordinate. )
                                    (.setPoint (float-array [0 0 0 -0.2 0.3 0]))
                                ))
                            ))
                        ))
                    ))
;TCN
                    (.addChildren (doto (HAnimJoint. )
                        (.setName "r_talocalcaneonavicular")
                        (.setDEF "hanim_r_talocalcaneonavicular")
                        (.setCenter (float-array [0 -0.3 0]))
                        (.setUlimit (float-array [0 0 0]))
                        (.setLlimit (float-array [0 0 0]))
                        (.addChildren (doto (HAnimSegment. )
                            (.setName "r_navicular")
                            (.setDEF "hanim_r_navicular")
                            (.addChildren (doto (Transform. )
                                (.setTranslation (float-array [0 -0.3 0]))
                                (.addChild (doto (Shape. )
                                    (.setUSE "HAnimJointShape")
                                ))
                            ))
                            (.addChildren (doto (Shape. )
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setEmissiveColor (float-array [1 1 1]))
                                    ))
                                ))
                                (.setGeometry (doto (IndexedLineSet. )
                                    (.setDEF "TCNtoCN1")
                                    (.setCoordIndex (int-array [0 1]))
                                    (.setCoord (doto (Coordinate. )
                                        (.setPoint (float-array [0 -0.3 0 0.1 -0.45 0]))
                                    ))
                                ))
                            ))
                            (.addChildren (doto (Shape. )
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setEmissiveColor (float-array [1 1 1]))
                                    ))
                                ))
                                (.setGeometry (doto (IndexedLineSet. )
                                    (.setDEF "TCNtoCN2")
                                    (.setCoordIndex (int-array [0 1]))
                                    (.setCoord (doto (Coordinate. )
                                        (.setPoint (float-array [0 -0.3 0 0 -0.45 0]))
                                    ))
                                ))
                            ))
                            (.addChildren (doto (Shape. )
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setEmissiveColor (float-array [1 1 1]))
                                    ))
                                ))
                                (.setGeometry (doto (IndexedLineSet. )
                                    (.setDEF "TCNtoCN3")
                                    (.setCoordIndex (int-array [0 1]))
                                    (.setCoord (doto (Coordinate. )
                                        (.setPoint (float-array [0 -0.3 0 -0.1 -0.4 0]))
                                    ))
                                ))
                            ))
                        ))
;CN1
                        (.addChildren (doto (HAnimJoint. )
                            (.setName "r_cuneonavicular_1")
                            (.setDEF "hanim_r_cuneonavicular_1")
                            (.setCenter (float-array [0.1 -0.45 0]))
                            (.setUlimit (float-array [0 0 0]))
                            (.setLlimit (float-array [0 0 0]))
                            (.addChildren (doto (HAnimSegment. )
                                (.setName "r_cuneiform_1")
                                (.setDEF "hanim_r_cuneiform_1")
                                (.addChildren (doto (Transform. )
                                    (.setTranslation (float-array [0.1 -0.45 0]))
                                    (.addChild (doto (Shape. )
                                        (.setUSE "HAnimJointShape")
                                    ))
                                ))
                                (.addChildren (doto (Shape. )
                                    (.setAppearance (doto (Appearance. )
                                        (.setMaterial (doto (Material. )
                                            (.setEmissiveColor (float-array [1 1 1]))
                                        ))
                                    ))
                                    (.setGeometry (doto (IndexedLineSet. )
                                        (.setDEF "CN1toTMT1")
                                        (.setCoordIndex (int-array [0 1]))
                                        (.setCoord (doto (Coordinate. )
                                            (.setPoint (float-array [0.1 -0.45 0 0.1 -0.6 0]))
                                        ))
                                    ))
                                ))
                            ))
                            (.addChildren (doto (HAnimJoint. )
                                (.setName "r_tarsometatarsal_1")
                                (.setDEF "hanim_r_tarsometatarsal_1")
                                (.setCenter (float-array [0.1 -0.6 0]))
                                (.setUlimit (float-array [0 0 0]))
                                (.setLlimit (float-array [0 0 0]))
                                (.addChildren (doto (HAnimSegment. )
                                    (.setName "r_metatarsal_1")
                                    (.setDEF "hanim_r_metatarsal_1")
                                    (.addChildren (doto (Transform. )
                                        (.setTranslation (float-array [0.1 -0.6 0]))
                                        (.addChild (doto (Shape. )
                                            (.setUSE "HAnimJointShape")
                                        ))
                                    ))
                                    (.addChildren (doto (Shape. )
                                        (.setAppearance (doto (Appearance. )
                                            (.setMaterial (doto (Material. )
                                                (.setEmissiveColor (float-array [1 1 1]))
                                            ))
                                        ))
                                        (.setGeometry (doto (IndexedLineSet. )
                                            (.setDEF "TMT1toMTP1")
                                            (.setCoordIndex (int-array [0 1]))
                                            (.setCoord (doto (Coordinate. )
                                                (.setPoint (float-array [0.1 -0.6 0 0.1 -0.9 0]))
                                            ))
                                        ))
                                    ))
                                ))
                                (.addChildren (doto (HAnimJoint. )
                                    (.setName "r_metatarsophalangeal_1")
                                    (.setDEF "hanim_r_metatarsophalangeal_1")
                                    (.setCenter (float-array [0.1 -0.9 0]))
                                    (.setUlimit (float-array [0 0 0]))
                                    (.setLlimit (float-array [0 0 0]))
                                    (.addChildren (doto (HAnimSegment. )
                                        (.setName "r_tarsal_proximal_phalanx_1")
                                        (.setDEF "hanim_r_tarsal_proximal_phalanx_1")
                                        (.addChildren (doto (Transform. )
                                            (.setTranslation (float-array [0.1 -0.9 0]))
                                            (.addChild (doto (Shape. )
                                                (.setUSE "HAnimJointShape")
                                            ))
                                        ))
                                        (.addChildren (doto (Shape. )
                                            (.setAppearance (doto (Appearance. )
                                                (.setMaterial (doto (Material. )
                                                    (.setEmissiveColor (float-array [1 1 1]))
                                                ))
                                            ))
                                            (.setGeometry (doto (IndexedLineSet. )
                                                (.setDEF "MTP1toIP1")
                                                (.setCoordIndex (int-array [0 1]))
                                                (.setCoord (doto (Coordinate. )
                                                    (.setPoint (float-array [0.1 -0.9 0 0.1 -1.05 0]))
                                                ))
                                            ))
                                        ))
                                    ))
                                    (.addChildren (doto (HAnimJoint. )
                                        (.setName "r_tarsal_interphalangeal_1")
                                        (.setDEF "hanim_r_tarsal_interphalangeal_1")
                                        (.setCenter (float-array [0.1 -1.05 0]))
                                        (.setUlimit (float-array [0 0 0]))
                                        (.setLlimit (float-array [0 0 0]))
                                        (.addChildren (doto (HAnimSegment. )
                                            (.setName "r_tarsal_distal_phalanx_1")
                                            (.setDEF "hanim_r_tarsal_distal_phalanx_1")
                                            (.addChildren (doto (Transform. )
                                                (.setTranslation (float-array [0.1 -1.05 0]))
                                                (.addChild (doto (Shape. )
                                                    (.setUSE "HAnimJointShape")
                                                ))
                                            ))
                                            (.addChildren (doto (Shape. )
                                                (.setAppearance (doto (Appearance. )
                                                    (.setMaterial (doto (Material. )
                                                        (.setEmissiveColor (float-array [1 1 1]))
                                                    ))
                                                ))
                                                (.setGeometry (doto (IndexedLineSet. )
                                                    (.setDEF "tiptoe_r_interphalangeal_")
                                                    (.setCoordIndex (int-array [0 1]))
                                                    (.setCoord (doto (Coordinate. )
                                                        (.setPoint (float-array [0.1 -1.05 0 0.1 -1.1 0]))
                                                    ))
                                                ))
                                            ))
                                        ))
                                    ))
                                ))
                            ))
                        ))
;CN2
                        (.addChildren (doto (HAnimJoint. )
                            (.setName "r_cuneonavicular_2")
                            (.setDEF "hanim_r_cuneonavicular_2")
                            (.setCenter (float-array [0 -0.45 0]))
                            (.setUlimit (float-array [0 0 0]))
                            (.setLlimit (float-array [0 0 0]))
                            (.addChildren (doto (HAnimSegment. )
                                (.setName "r_cuneiform_2")
                                (.setDEF "hanim_r_cuneiform_2")
                                (.addChildren (doto (Transform. )
                                    (.setTranslation (float-array [0 -0.45 0]))
                                    (.addChild (doto (Shape. )
                                        (.setUSE "HAnimJointShape")
                                    ))
                                ))
                                (.addChildren (doto (Shape. )
                                    (.setAppearance (doto (Appearance. )
                                        (.setMaterial (doto (Material. )
                                            (.setEmissiveColor (float-array [1 1 1]))
                                        ))
                                    ))
                                    (.setGeometry (doto (IndexedLineSet. )
                                        (.setDEF "CN2toTMT2")
                                        (.setCoordIndex (int-array [0 1]))
                                        (.setCoord (doto (Coordinate. )
                                            (.setPoint (float-array [0 -0.45 0 -0.05 -0.6 0]))
                                        ))
                                    ))
                                ))
                            ))
                            (.addChildren (doto (HAnimJoint. )
                                (.setName "r_tarsometatarsal_2")
                                (.setDEF "hanim_r_tarsometatarsal_2")
                                (.setCenter (float-array [-0.05 -0.6 0]))
                                (.setUlimit (float-array [0 0 0]))
                                (.setLlimit (float-array [0 0 0]))
                                (.addChildren (doto (HAnimSegment. )
                                    (.setName "r_metatarsal_2")
                                    (.setDEF "hanim_r_metatarsal_2")
                                    (.addChildren (doto (Transform. )
                                        (.setTranslation (float-array [-0.05 -0.6 0]))
                                        (.addChild (doto (Shape. )
                                            (.setUSE "HAnimJointShape")
                                        ))
                                    ))
                                    (.addChildren (doto (Shape. )
                                        (.setAppearance (doto (Appearance. )
                                            (.setMaterial (doto (Material. )
                                                (.setEmissiveColor (float-array [1 1 1]))
                                            ))
                                        ))
                                        (.setGeometry (doto (IndexedLineSet. )
                                            (.setDEF "TMT2toMTP2")
                                            (.setCoordIndex (int-array [0 1]))
                                            (.setCoord (doto (Coordinate. )
                                                (.setPoint (float-array [-0.05 -0.6 0 -0.05 -0.9 0]))
                                            ))
                                        ))
                                    ))
                                ))
                                (.addChildren (doto (HAnimJoint. )
                                    (.setName "r_metatarsophalangeal_2")
                                    (.setDEF "hanim_r_metatarsophalangeal_2")
                                    (.setCenter (float-array [-0.05 -0.9 0]))
                                    (.setUlimit (float-array [0 0 0]))
                                    (.setLlimit (float-array [0 0 0]))
                                    (.addChildren (doto (HAnimSegment. )
                                        (.setName "r_tarsal_proximal_phalanx_2")
                                        (.setDEF "hanim_r_tarsal_proximal_phalanx_2")
                                        (.addChildren (doto (Transform. )
                                            (.setTranslation (float-array [-0.05 -0.9 0]))
                                            (.addChild (doto (Shape. )
                                                (.setUSE "HAnimJointShape")
                                            ))
                                        ))
                                        (.addChildren (doto (Shape. )
                                            (.setAppearance (doto (Appearance. )
                                                (.setMaterial (doto (Material. )
                                                    (.setEmissiveColor (float-array [1 1 1]))
                                                ))
                                            ))
                                            (.setGeometry (doto (IndexedLineSet. )
                                                (.setDEF "MTP2toPIP2")
                                                (.setCoordIndex (int-array [0 1]))
                                                (.setCoord (doto (Coordinate. )
                                                    (.setPoint (float-array [-0.05 -0.9 0 -0.05 -1.05 0]))
                                                ))
                                            ))
                                        ))
                                    ))
                                    (.addChildren (doto (HAnimJoint. )
                                        (.setName "r_tarsal_proximal_interphalangeal_2")
                                        (.setDEF "hanim_r_tarsal_proximal_interphalangeal_2")
                                        (.setCenter (float-array [-0.05 -1.05 0]))
                                        (.setUlimit (float-array [0 0 0]))
                                        (.setLlimit (float-array [0 0 0]))
                                        (.addChildren (doto (HAnimSegment. )
                                            (.setName "r_tarsal_middle_phalanx_2")
                                            (.setDEF "hanim_r_tarsal_middle_phalanx_2")
                                            (.addChildren (doto (Transform. )
                                                (.setTranslation (float-array [-0.05 -1.05 0]))
                                                (.addChild (doto (Shape. )
                                                    (.setUSE "HAnimJointShape")
                                                ))
                                            ))
                                            (.addChildren (doto (Shape. )
                                                (.setAppearance (doto (Appearance. )
                                                    (.setMaterial (doto (Material. )
                                                        (.setEmissiveColor (float-array [1 1 1]))
                                                    ))
                                                ))
                                                (.setGeometry (doto (IndexedLineSet. )
                                                    (.setDEF "PIP2toDIP2")
                                                    (.setCoordIndex (int-array [0 1]))
                                                    (.setCoord (doto (Coordinate. )
                                                        (.setPoint (float-array [-0.05 -1.05 0 -0.05 -1.12 0]))
                                                    ))
                                                ))
                                            ))
                                        ))
                                        (.addChildren (doto (HAnimJoint. )
                                            (.setName "r_tarsal_distal_interphalangeal_2")
                                            (.setDEF "hanim_r_tarsal_distal_interphalangeal_2")
                                            (.setCenter (float-array [-0.05 -1.12 0]))
                                            (.setUlimit (float-array [0 0 0]))
                                            (.setLlimit (float-array [0 0 0]))
                                            (.addChildren (doto (HAnimSegment. )
                                                (.setName "r_tarsal_distal_phalanx_2")
                                                (.setDEF "hanim_r_tarsal_distal_phalanx_2")
                                                (.addChildren (doto (Transform. )
                                                    (.setTranslation (float-array [-0.05 -1.12 0]))
                                                    (.addChild (doto (Shape. )
                                                        (.setUSE "HAnimJointShape")
                                                    ))
                                                ))
                                                (.addChildren (doto (Shape. )
                                                    (.setAppearance (doto (Appearance. )
                                                        (.setMaterial (doto (Material. )
                                                            (.setEmissiveColor (float-array [1 1 1]))
                                                        ))
                                                    ))
                                                    (.setGeometry (doto (IndexedLineSet. )
                                                        (.setDEF "tiptoe_r_tarsal_distal_interphalangeal_2")
                                                        (.setCoordIndex (int-array [0 1]))
                                                        (.setCoord (doto (Coordinate. )
                                                            (.setPoint (float-array [-0.05 -1.12 0 -0.05 -1.16 0]))
                                                        ))
                                                    ))
                                                ))
                                            ))
                                        ))
                                    ))
                                ))
                            ))
                        ))
;CN3
                        (.addChildren (doto (HAnimJoint. )
                            (.setName "r_cuneonavicular_3")
                            (.setDEF "hanim_r_cuneonavicular_3")
                            (.setCenter (float-array [-0.1 -0.4 0]))
                            (.setUlimit (float-array [0 0 0]))
                            (.setLlimit (float-array [0 0 0]))
                            (.addChildren (doto (HAnimSegment. )
                                (.setName "r_cuneiform_3")
                                (.setDEF "hanim_r_cuneiform_3")
                                (.addChildren (doto (Transform. )
                                    (.setTranslation (float-array [-0.1 -0.4 0]))
                                    (.addChild (doto (Shape. )
                                        (.setUSE "HAnimJointShape")
                                    ))
                                ))
                                (.addChildren (doto (Shape. )
                                    (.setAppearance (doto (Appearance. )
                                        (.setMaterial (doto (Material. )
                                            (.setEmissiveColor (float-array [1 1 1]))
                                        ))
                                    ))
                                    (.setGeometry (doto (IndexedLineSet. )
                                        (.setDEF "CN3toTMT3")
                                        (.setCoordIndex (int-array [0 1]))
                                        (.setCoord (doto (Coordinate. )
                                            (.setPoint (float-array [-0.1 -0.4 0 -0.15 -0.6 0]))
                                        ))
                                    ))
                                ))
                            ))
                            (.addChildren (doto (HAnimJoint. )
                                (.setName "r_tarsometatarsal_3")
                                (.setDEF "hanim_r_tarsometatarsal_3")
                                (.setCenter (float-array [-0.15 -0.6 0]))
                                (.setUlimit (float-array [0 0 0]))
                                (.setLlimit (float-array [0 0 0]))
                                (.addChildren (doto (HAnimSegment. )
                                    (.setName "r_metatarsal_3")
                                    (.setDEF "hanim_r_metatarsal_3")
                                    (.addChildren (doto (Transform. )
                                        (.setTranslation (float-array [-0.15 -0.6 0]))
                                        (.addChild (doto (Shape. )
                                            (.setUSE "HAnimJointShape")
                                        ))
                                    ))
                                    (.addChildren (doto (Shape. )
                                        (.setAppearance (doto (Appearance. )
                                            (.setMaterial (doto (Material. )
                                                (.setEmissiveColor (float-array [1 1 1]))
                                            ))
                                        ))
                                        (.setGeometry (doto (IndexedLineSet. )
                                            (.setDEF "TMT3toMTP3")
                                            (.setCoordIndex (int-array [0 1]))
                                            (.setCoord (doto (Coordinate. )
                                                (.setPoint (float-array [-0.15 -0.6 0 -0.15 -0.9 0]))
                                            ))
                                        ))
                                    ))
                                ))
                                (.addChildren (doto (HAnimJoint. )
                                    (.setName "r_metatarsophalangeal_3")
                                    (.setDEF "hanim_r_metatarsophalangeal_3")
                                    (.setCenter (float-array [-0.15 -0.9 0]))
                                    (.setUlimit (float-array [0 0 0]))
                                    (.setLlimit (float-array [0 0 0]))
                                    (.addChildren (doto (HAnimSegment. )
                                        (.setName "r_tarsal_proximal_phalanx_3")
                                        (.setDEF "hanim_r_tarsal_proximal_phalanx_3")
                                        (.addChildren (doto (Transform. )
                                            (.setTranslation (float-array [-0.15 -0.9 0]))
                                            (.addChild (doto (Shape. )
                                                (.setUSE "HAnimJointShape")
                                            ))
                                        ))
                                        (.addChildren (doto (Shape. )
                                            (.setAppearance (doto (Appearance. )
                                                (.setMaterial (doto (Material. )
                                                    (.setEmissiveColor (float-array [1 1 1]))
                                                ))
                                            ))
                                            (.setGeometry (doto (IndexedLineSet. )
                                                (.setDEF "MTP3toPIP3")
                                                (.setCoordIndex (int-array [0 1]))
                                                (.setCoord (doto (Coordinate. )
                                                    (.setPoint (float-array [-0.15 -0.9 0 -0.15 -1.05 0]))
                                                ))
                                            ))
                                        ))
                                    ))
                                    (.addChildren (doto (HAnimJoint. )
                                        (.setName "r_tarsal_proximal_interphalangeal_3")
                                        (.setDEF "hanim_r_tarsal_proximal_interphalangeal_3")
                                        (.setCenter (float-array [-0.15 -1.05 0]))
                                        (.setUlimit (float-array [0 0 0]))
                                        (.setLlimit (float-array [0 0 0]))
                                        (.addChildren (doto (HAnimSegment. )
                                            (.setName "r_tarsal_middle_phalanx_3")
                                            (.setDEF "hanim_r_tarsal_middle_phalanx_3")
                                            (.addChildren (doto (Transform. )
                                                (.setTranslation (float-array [-0.15 -1.05 0]))
                                                (.addChild (doto (Shape. )
                                                    (.setUSE "HAnimJointShape")
                                                ))
                                            ))
                                            (.addChildren (doto (Shape. )
                                                (.setAppearance (doto (Appearance. )
                                                    (.setMaterial (doto (Material. )
                                                        (.setEmissiveColor (float-array [1 1 1]))
                                                    ))
                                                ))
                                                (.setGeometry (doto (IndexedLineSet. )
                                                    (.setDEF "PIP3toDIP3")
                                                    (.setCoordIndex (int-array [0 1]))
                                                    (.setCoord (doto (Coordinate. )
                                                        (.setPoint (float-array [-0.15 -1.05 0 -0.15 -1.13 0]))
                                                    ))
                                                ))
                                            ))
                                        ))
                                        (.addChildren (doto (HAnimJoint. )
                                            (.setName "r_tarsal_distal_interphalangeal_3")
                                            (.setDEF "hanim_r_tarsal_distal_interphalangeal_3")
                                            (.setCenter (float-array [-0.15 -1.13 0]))
                                            (.setUlimit (float-array [0 0 0]))
                                            (.setLlimit (float-array [0 0 0]))
                                            (.addChildren (doto (HAnimSegment. )
                                                (.setName "r_tarsal_distal_phalanx_3")
                                                (.setDEF "hanim_r_tarsal_distal_phalanx_3")
                                                (.addChildren (doto (Transform. )
                                                    (.setTranslation (float-array [-0.15 -1.13 0]))
                                                    (.addChild (doto (Shape. )
                                                        (.setUSE "HAnimJointShape")
                                                    ))
                                                ))
                                                (.addChildren (doto (Shape. )
                                                    (.setAppearance (doto (Appearance. )
                                                        (.setMaterial (doto (Material. )
                                                            (.setEmissiveColor (float-array [1 1 1]))
                                                        ))
                                                    ))
                                                    (.setGeometry (doto (IndexedLineSet. )
                                                        (.setDEF "tiptoe_r_tarsal_distal_interphalangeal_3")
                                                        (.setCoordIndex (int-array [0 1]))
                                                        (.setCoord (doto (Coordinate. )
                                                            (.setPoint (float-array [-0.15 -1.13 0 -0.15 -1.16 0]))
                                                        ))
                                                    ))
                                                ))
                                            ))
                                        ))
                                    ))
                                ))
                            ))
                        ))
                    ))
;CC
                    (.addChildren (doto (HAnimJoint. )
                        (.setName "r_calcaneocuboid")
                        (.setDEF "hanim_r_calcaneocuboid")
                        (.setCenter (float-array [-0.2 0.3 0]))
                        (.setUlimit (float-array [0 0 0]))
                        (.setLlimit (float-array [0 0 0]))
                        (.addChildren (doto (HAnimSegment. )
                            (.setName "r_calcaneus")
                            (.setDEF "hanim_r_calcaneus")
                            (.addChildren (doto (Transform. )
                                (.setTranslation (float-array [-0.2 0.3 0]))
                                (.addChild (doto (Shape. )
                                    (.setUSE "HAnimJointShape")
                                ))
                            ))
                            (.addChildren (doto (Shape. )
                                (.setAppearance (doto (Appearance. )
                                    (.setMaterial (doto (Material. )
                                        (.setEmissiveColor (float-array [1 1 1]))
                                    ))
                                ))
                                (.setGeometry (doto (IndexedLineSet. )
                                    (.setDEF "CCtoTT")
                                    (.setCoordIndex (int-array [0 1]))
                                    (.setCoord (doto (Coordinate. )
                                        (.setPoint (float-array [-0.2 0.3 0 -0.21 -0.3 0]))
                                    ))
                                ))
                            ))
                        ))
;TT
                        (.addChildren (doto (HAnimJoint. )
                            (.setName "r_transversetarsal")
                            (.setDEF "hanim_r_transversetarsal")
                            (.setCenter (float-array [-0.21 -0.3 0]))
                            (.setUlimit (float-array [0 0 0]))
                            (.setLlimit (float-array [0 0 0]))
                            (.addChildren (doto (HAnimSegment. )
                                (.setName "r_cuboid")
                                (.setDEF "hanim_r_cuboid")
                                (.addChildren (doto (Transform. )
                                    (.setTranslation (float-array [-0.21 -0.3 0]))
                                    (.addChild (doto (Shape. )
                                        (.setUSE "HAnimJointShape")
                                    ))
                                ))
                                (.addChildren (doto (Shape. )
                                    (.setAppearance (doto (Appearance. )
                                        (.setMaterial (doto (Material. )
                                            (.setEmissiveColor (float-array [1 1 1]))
                                        ))
                                    ))
                                    (.setGeometry (doto (IndexedLineSet. )
                                        (.setDEF "TTtoTMT4")
                                        (.setCoordIndex (int-array [0 1]))
                                        (.setCoord (doto (Coordinate. )
                                            (.setPoint (float-array [-0.21 -0.3 0 -0.25 -0.58 0]))
                                        ))
                                    ))
                                ))
                                (.addChildren (doto (Shape. )
                                    (.setAppearance (doto (Appearance. )
                                        (.setMaterial (doto (Material. )
                                            (.setEmissiveColor (float-array [1 1 1]))
                                        ))
                                    ))
                                    (.setGeometry (doto (IndexedLineSet. )
                                        (.setDEF "TTtoTMT5")
                                        (.setCoordIndex (int-array [0 1]))
                                        (.setCoord (doto (Coordinate. )
                                            (.setPoint (float-array [-0.21 -0.3 0 -0.33 -0.52 0]))
                                        ))
                                    ))
                                ))
                            ))
;TMT4
                            (.addChildren (doto (HAnimJoint. )
                                (.setName "r_tarsometatarsal_4")
                                (.setDEF "hanim_r_tarsometatarsal_4")
                                (.setCenter (float-array [-0.25 -0.58 0]))
                                (.setUlimit (float-array [0 0 0]))
                                (.setLlimit (float-array [0 0 0]))
                                (.addChildren (doto (HAnimSegment. )
                                    (.setName "r_metatarsal_4")
                                    (.setDEF "hanim_r_metatarsal_4")
                                    (.addChildren (doto (Transform. )
                                        (.setTranslation (float-array [-0.25 -0.58 0]))
                                        (.addChild (doto (Shape. )
                                            (.setUSE "HAnimJointShape")
                                        ))
                                    ))
                                    (.addChildren (doto (Shape. )
                                        (.setAppearance (doto (Appearance. )
                                            (.setMaterial (doto (Material. )
                                                (.setEmissiveColor (float-array [1 1 1]))
                                            ))
                                        ))
                                        (.setGeometry (doto (IndexedLineSet. )
                                            (.setDEF "TMT4toMTP4")
                                            (.setCoordIndex (int-array [0 1]))
                                            (.setCoord (doto (Coordinate. )
                                                (.setPoint (float-array [-0.25 -0.58 0 -0.25 -0.87 0]))
                                            ))
                                        ))
                                    ))
                                ))
                                (.addChildren (doto (HAnimJoint. )
                                    (.setName "r_metatarsophalangeal_4")
                                    (.setDEF "hanim_r_metatarsophalangeal_4")
                                    (.setCenter (float-array [-0.25 -0.87 0]))
                                    (.setUlimit (float-array [0 0 0]))
                                    (.setLlimit (float-array [0 0 0]))
                                    (.addChildren (doto (HAnimSegment. )
                                        (.setName "r_tarsal_proximal_phalanx_4")
                                        (.setDEF "hanim_r_tarsal_proximal_phalanx_4")
                                        (.addChildren (doto (Transform. )
                                            (.setTranslation (float-array [-0.25 -0.87 0]))
                                            (.addChild (doto (Shape. )
                                                (.setUSE "HAnimJointShape")
                                            ))
                                        ))
                                        (.addChildren (doto (Shape. )
                                            (.setAppearance (doto (Appearance. )
                                                (.setMaterial (doto (Material. )
                                                    (.setEmissiveColor (float-array [1 1 1]))
                                                ))
                                            ))
                                            (.setGeometry (doto (IndexedLineSet. )
                                                (.setDEF "MTP4toPIP4")
                                                (.setCoordIndex (int-array [0 1]))
                                                (.setCoord (doto (Coordinate. )
                                                    (.setPoint (float-array [-0.25 -0.87 0 -0.25 -1 0]))
                                                ))
                                            ))
                                        ))
                                    ))
                                    (.addChildren (doto (HAnimJoint. )
                                        (.setName "r_tarsal_proximal_interphalangeal_4")
                                        (.setDEF "hanim_r_tarsal_proximal_interphalangeal_4")
                                        (.setCenter (float-array [-0.25 -1 0]))
                                        (.setUlimit (float-array [0 0 0]))
                                        (.setLlimit (float-array [0 0 0]))
                                        (.addChildren (doto (HAnimSegment. )
                                            (.setName "r_tarsal_middle_phalanx_4")
                                            (.setDEF "hanim_r_tarsal_middle_phalanx_4")
                                            (.addChildren (doto (Transform. )
                                                (.setTranslation (float-array [-0.25 -1 0]))
                                                (.addChild (doto (Shape. )
                                                    (.setUSE "HAnimJointShape")
                                                ))
                                            ))
                                            (.addChildren (doto (Shape. )
                                                (.setAppearance (doto (Appearance. )
                                                    (.setMaterial (doto (Material. )
                                                        (.setEmissiveColor (float-array [1 1 1]))
                                                    ))
                                                ))
                                                (.setGeometry (doto (IndexedLineSet. )
                                                    (.setDEF "PIP4toDIP4")
                                                    (.setCoordIndex (int-array [0 1]))
                                                    (.setCoord (doto (Coordinate. )
                                                        (.setPoint (float-array [-0.25 -1 0 -0.25 -1.1 0]))
                                                    ))
                                                ))
                                            ))
                                        ))
                                        (.addChildren (doto (HAnimJoint. )
                                            (.setName "r_tarsal_distal_interphalangeal_4")
                                            (.setDEF "hanim_r_tarsal_distal_interphalangeal_4")
                                            (.setCenter (float-array [-0.25 -1.1 0]))
                                            (.setUlimit (float-array [0 0 0]))
                                            (.setLlimit (float-array [0 0 0]))
                                            (.addChildren (doto (HAnimSegment. )
                                                (.setName "r_tarsal_distal_phalanx_4")
                                                (.setDEF "hanim_r_tarsal_distal_phalanx_4")
                                                (.addChildren (doto (Transform. )
                                                    (.setTranslation (float-array [-0.25 -1.1 0]))
                                                    (.addChild (doto (Shape. )
                                                        (.setUSE "HAnimJointShape")
                                                    ))
                                                ))
                                                (.addChildren (doto (Shape. )
                                                    (.setAppearance (doto (Appearance. )
                                                        (.setMaterial (doto (Material. )
                                                            (.setEmissiveColor (float-array [1 1 1]))
                                                        ))
                                                    ))
                                                    (.setGeometry (doto (IndexedLineSet. )
                                                        (.setDEF "tiptoe_r_tarsal_distal_interphalangeal_4")
                                                        (.setCoordIndex (int-array [0 1]))
                                                        (.setCoord (doto (Coordinate. )
                                                            (.setPoint (float-array [-0.25 -1.1 0 -0.25 -1.15 0]))
                                                        ))
                                                    ))
                                                ))
                                            ))
                                        ))
                                    ))
                                ))
                            ))
;TMT5
                            (.addChildren (doto (HAnimJoint. )
                                (.setName "r_tarsometatarsal_5")
                                (.setDEF "hanim_r_tarsometatarsal_5")
                                (.setCenter (float-array [-0.33 -0.52 0]))
                                (.setUlimit (float-array [0 0 0]))
                                (.setLlimit (float-array [0 0 0]))
                                (.addChildren (doto (HAnimSegment. )
                                    (.setName "r_metatarsal_5")
                                    (.setDEF "hanim_r_metatarsal_5")
                                    (.addChildren (doto (Transform. )
                                        (.setTranslation (float-array [-0.33 -0.52 0]))
                                        (.addChild (doto (Shape. )
                                            (.setUSE "HAnimJointShape")
                                        ))
                                    ))
                                    (.addChildren (doto (Shape. )
                                        (.setAppearance (doto (Appearance. )
                                            (.setMaterial (doto (Material. )
                                                (.setEmissiveColor (float-array [1 1 1]))
                                            ))
                                        ))
                                        (.setGeometry (doto (IndexedLineSet. )
                                            (.setDEF "TMT5toMTP5")
                                            (.setCoordIndex (int-array [0 1]))
                                            (.setCoord (doto (Coordinate. )
                                                (.setPoint (float-array [-0.33 -0.52 0 -0.34 -0.8 0]))
                                            ))
                                        ))
                                    ))
                                ))
                                (.addChildren (doto (HAnimJoint. )
                                    (.setName "r_metatarsophalangeal_5")
                                    (.setDEF "hanim_r_metatarsophalangeal_5")
                                    (.setCenter (float-array [-0.34 -0.8 0]))
                                    (.setUlimit (float-array [0 0 0]))
                                    (.setLlimit (float-array [0 0 0]))
                                    (.addChildren (doto (HAnimSegment. )
                                        (.setName "r_tarsal_proximal_phalanx_5")
                                        (.setDEF "hanim_r_tarsal_proximal_phalanx_5")
                                        (.addChildren (doto (Transform. )
                                            (.setTranslation (float-array [-0.34 -0.8 0]))
                                            (.addChild (doto (Shape. )
                                                (.setUSE "HAnimJointShape")
                                            ))
                                        ))
                                        (.addChildren (doto (Shape. )
                                            (.setAppearance (doto (Appearance. )
                                                (.setMaterial (doto (Material. )
                                                    (.setEmissiveColor (float-array [1 1 1]))
                                                ))
                                            ))
                                            (.setGeometry (doto (IndexedLineSet. )
                                                (.setDEF "MTP5toPIP5")
                                                (.setCoordIndex (int-array [0 1]))
                                                (.setCoord (doto (Coordinate. )
                                                    (.setPoint (float-array [-0.34 -0.8 0 -0.34 -0.95 0]))
                                                ))
                                            ))
                                        ))
                                    ))
                                    (.addChildren (doto (HAnimJoint. )
                                        (.setName "r_tarsal_proximal_interphalangeal_5")
                                        (.setDEF "hanim_r_tarsal_proximal_interphalangeal_5")
                                        (.setCenter (float-array [-0.34 -0.95 0]))
                                        (.setUlimit (float-array [0 0 0]))
                                        (.setLlimit (float-array [0 0 0]))
                                        (.addChildren (doto (HAnimSegment. )
                                            (.setName "r_tarsal_middle_phalanx_5")
                                            (.setDEF "hanim_r_tarsal_middle_phalanx_5")
                                            (.addChildren (doto (Transform. )
                                                (.setTranslation (float-array [-0.34 -0.95 0]))
                                                (.addChild (doto (Shape. )
                                                    (.setUSE "HAnimJointShape")
                                                ))
                                            ))
                                            (.addChildren (doto (Shape. )
                                                (.setAppearance (doto (Appearance. )
                                                    (.setMaterial (doto (Material. )
                                                        (.setEmissiveColor (float-array [1 1 1]))
                                                    ))
                                                ))
                                                (.setGeometry (doto (IndexedLineSet. )
                                                    (.setDEF "PIP5toDIP5")
                                                    (.setCoordIndex (int-array [0 1]))
                                                    (.setCoord (doto (Coordinate. )
                                                        (.setPoint (float-array [-0.34 -0.95 0 -0.34 -1.05 0]))
                                                    ))
                                                ))
                                            ))
                                        ))
                                        (.addChildren (doto (HAnimJoint. )
                                            (.setName "r_tarsal_distal_interphalangeal_5")
                                            (.setDEF "hanim_r_tarsal_distal_interphalangeal_5")
                                            (.setCenter (float-array [-0.34 -1.05 0]))
                                            (.setUlimit (float-array [0 0 0]))
                                            (.setLlimit (float-array [0 0 0]))
                                            (.addChildren (doto (HAnimSegment. )
                                                (.setName "r_tarsal_distal_phalanx_5")
                                                (.setDEF "hanim_r_tarsal_distal_phalanx_5")
                                                (.addChildren (doto (Transform. )
                                                    (.setTranslation (float-array [-0.34 -1.05 0]))
                                                    (.addChild (doto (Shape. )
                                                        (.setUSE "HAnimJointShape")
                                                    ))
                                                ))
                                                (.addChildren (doto (Shape. )
                                                    (.setAppearance (doto (Appearance. )
                                                        (.setMaterial (doto (Material. )
                                                            (.setEmissiveColor (float-array [1 1 1]))
                                                        ))
                                                    ))
                                                    (.setGeometry (doto (IndexedLineSet. )
                                                        (.setDEF "tiptoe_r_tarsal_distal_interphalangeal_5")
                                                        (.setCoordIndex (int-array [0 1]))
                                                        (.setCoord (doto (Coordinate. )
                                                            (.setPoint (float-array [-0.34 -1.05 0 -0.34 -1.08 0]))
                                                        ))
                                                    ))
                                                ))
                                            ))
                                        ))
                                    ))
                                ))
                            ))
                        ))
                    ))
                ))
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_humanoid_root")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_calcaneocuboid")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_cuneonavicular_1")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_cuneonavicular_2")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_cuneonavicular_3")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_metatarsophalangeal_1")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_metatarsophalangeal_2")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_metatarsophalangeal_3")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_metatarsophalangeal_4")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_metatarsophalangeal_5")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_talocalcaneonavicular")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_talocrural")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsal_distal_interphalangeal_2")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsal_distal_interphalangeal_3")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsal_distal_interphalangeal_4")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsal_distal_interphalangeal_5")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsal_interphalangeal_1")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsal_proximal_interphalangeal_2")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsal_proximal_interphalangeal_3")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsal_proximal_interphalangeal_4")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsal_proximal_interphalangeal_5")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsometatarsal_1")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsometatarsal_2")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsometatarsal_3")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsometatarsal_4")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_tarsometatarsal_5")
            ))
            (.addJoints (doto (HAnimJoint. )
                (.setContainerFieldOverride "joints")
                (.setUSE "hanim_r_transversetarsal")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_calcaneus")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_cuboid")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_cuneiform_1")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_cuneiform_2")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_cuneiform_3")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_metatarsal_1")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_metatarsal_2")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_metatarsal_3")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_metatarsal_4")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_metatarsal_5")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_navicular")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_talus")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_distal_phalanx_1")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_distal_phalanx_2")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_distal_phalanx_3")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_distal_phalanx_4")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_distal_phalanx_5")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_middle_phalanx_2")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_middle_phalanx_3")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_middle_phalanx_4")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_middle_phalanx_5")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_proximal_phalanx_1")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_proximal_phalanx_2")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_proximal_phalanx_3")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_proximal_phalanx_4")
            ))
            (.addSegments (doto (HAnimSegment. )
                (.setContainerFieldOverride "segments")
                (.setUSE "hanim_r_tarsal_proximal_phalanx_5")
            ))
        ))
    ))
))
(.toFileX3D X3D0 ".././HAnimModelFootRight.new.clojure.x3d")
(.toFileJSON X3D0 ".././HAnimModelFootRight.new.clojure.json")
(defn -main []
(println "Hello from your main function!"))