###############################################
#
# Now available: developmental python x3d.py package on PyPi for import.
#   This approach greatly simplifies Python X3D deployment and use.
#   https://pypi.org/project/x3d
#
# Installation:
#       pip install x3d
# or
#       python -m pip install x3d
#
# Developer options for loading x3d package:
#
#    from x3d import *  # preferred approach, terser source that avoids x3d.* class prefixes
#
# or
#    import x3d         # traditional way to subclass x3d package, all classes require x3d.* prefix
#                       # but python source is very verbose, for example x3d.Material x3d.Shape etc.
#                       # X3dToPython.xslt stylesheet insertPackagePrefix=true supports this option.

from x3d import *

###############################################

newModel=X3D(profile='Immersive',version='3.0',
  head=head(
    children=[
    meta(content='default_visibilitysensor.x3d',name='title'),
    meta(content='default-movie.mpg',name='MovingImage'),
    meta(content='http://www.nist.gov/vrml.html',name='reference'),
    meta(content='http://www.itl.nist.gov/div897/ctg/vrml/vrml.html',name='reference'),
    meta(content='http://www.itl.nist.gov/div897/ctg/vrml/members.html',name='creator'),
    meta(content='This file was provided by the National Institute of Standards and Technology, and is part of the X3D Conformance Test Suite, available at http://www.nist.gov/vrml.html The information contained within this file is provided for use in establishing conformance to the ISO VRML97 Specification. Conformance to this test does not imply recommendation or endorsement by the National Institute of Standards and Technology. This software can be redistributed and/or modified freely provided that any derivative works bear some notice that they are derived from it, and any modified versions bear some notice that they have been modified.',name='disclaimer'),
    meta(content='Correct definition and compliance of this conformance scene is maintained by the X3D Working Group, https://www.web3d.org/working-groups/x3d',name='info'),
    meta(content='Michael Kass NIST, Don Brutzman NPS',name='translator'),
    meta(content='21 January 2001',name='translated'),
    meta(content='20 October 2019',name='modified'),
    meta(content='Test default VisibilitySensor properties. A Sphere geometry has an associated VisibilitySensor in front of it, at point 0 0 0. The default ViewPoint is at point 0 0 10, looking down the -Z axis. Because the bounding box, with dimensions 0 0 0 is in direct sight, an isActive event is generated by the enabled VisibilitySensor node. In addition, an enterTime event is generated, which is routed to a TimeSensor node to start an animation of the Sphere geometry. When the user moves to the second viewpoint, behind the bounding box, at point 0 0 -10, an isActive=FALSe event is generated, along with an exitTime event, and the Sphere ceases to change color.',name='description'),
    meta(content='https://www.web3d.org/x3d/content/examples/ConformanceNist/Sensors/VisibilitySensor/default_visibilitysensor.x3d',name='identifier'),
    meta(content='Vrml97ToX3dNist, http://ovrt.nist.gov/v2_x3d.html',name='generator'),
    meta(content='X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit',name='generator'),
    meta(content='../../license.html',name='license')]),
  Scene=Scene(
    children=[
    WorldInfo(title='default_visibilitysensor.x3d'),
    NavigationInfo(type=["EXAMINE","WALK","FLY","ANY"]),
    Viewpoint(description='Front View'),
    Viewpoint(description='Behind VisibilitySensor',position=(0,0,-10)),
    TimeSensor(DEF='TIME',cycleInterval=2,enabled=False,loop=True),
    ColorInterpolator(DEF='INTERP_COLOR',key=[0,0.5,1],keyValue=[(1,0,0),(0,1,0),(0,0,1)]),
    Group(
      children=[
      VisibilitySensor(DEF='VISIB_SENSOR'),
      Transform(DEF='GEOMETRY',translation=(0,0,-20),
        children=[
        Shape(
          appearance=Appearance(
            material=Material(DEF='COLOR',diffuseColor=(1,0,0))),
          geometry=Sphere(radius=2))])]),
    ROUTE(fromField='isActive',fromNode='VISIB_SENSOR',toField='enabled',toNode='TIME'),
    ROUTE(fromField='enterTime',fromNode='VISIB_SENSOR',toField='startTime',toNode='TIME'),
    ROUTE(fromField='fraction_changed',fromNode='TIME',toField='set_fraction',toNode='INTERP_COLOR'),
    ROUTE(fromField='value_changed',fromNode='INTERP_COLOR',toField='diffuseColor',toNode='COLOR'),
    ROUTE(fromField='exitTime',fromNode='VISIB_SENSOR',toField='stopTime',toNode='TIME')])
) # X3D model complete

###############################################
# Self-test diagnostics
###############################################

if        metaDiagnostics(newModel): # built-in utility method in X3D class
    print(metaDiagnostics(newModel))
print('check  newModel.XML() serialization...')
newModelXML = newModel.XML() # test export method XML() for exceptions
# print(newModelXML) # debug

print ("python x3d.py load successful for default_visibilitysensor.py")
