function ArtDecoExamples: TX3DRootNode;
var
X3D0: TX3DRootNode;
Group13: TGroupNode;
WorldInfo14: TWorldInfoNode;
ExternProtoDeclare15: TExternProtoDeclareNode;
ExternProtoDeclare16: TExternProtoDeclareNode;
ExternProtoDeclare17: TExternProtoDeclareNode;
ExternProtoDeclare18: TExternProtoDeclareNode;
ExternProtoDeclare19: TExternProtoDeclareNode;
ExternProtoDeclare20: TExternProtoDeclareNode;
ExternProtoDeclare21: TExternProtoDeclareNode;
ExternProtoDeclare22: TExternProtoDeclareNode;
ExternProtoDeclare23: TExternProtoDeclareNode;
ExternProtoDeclare24: TExternProtoDeclareNode;
ExternProtoDeclare25: TExternProtoDeclareNode;
ExternProtoDeclare26: TExternProtoDeclareNode;
ExternProtoDeclare27: TExternProtoDeclareNode;
ExternProtoDeclare28: TExternProtoDeclareNode;
ExternProtoDeclare29: TExternProtoDeclareNode;
ExternProtoDeclare30: TExternProtoDeclareNode;
ExternProtoDeclare31: TExternProtoDeclareNode;
ExternProtoDeclare32: TExternProtoDeclareNode;
ExternProtoDeclare33: TExternProtoDeclareNode;
ExternProtoDeclare34: TExternProtoDeclareNode;
ExternProtoDeclare35: TExternProtoDeclareNode;
ExternProtoDeclare36: TExternProtoDeclareNode;
ExternProtoDeclare37: TExternProtoDeclareNode;
ExternProtoDeclare38: TExternProtoDeclareNode;
ExternProtoDeclare39: TExternProtoDeclareNode;
ExternProtoDeclare40: TExternProtoDeclareNode;
ExternProtoDeclare41: TExternProtoDeclareNode;
ExternProtoDeclare42: TExternProtoDeclareNode;
ExternProtoDeclare43: TExternProtoDeclareNode;
ExternProtoDeclare44: TExternProtoDeclareNode;
ExternProtoDeclare45: TExternProtoDeclareNode;
ExternProtoDeclare46: TExternProtoDeclareNode;
ExternProtoDeclare47: TExternProtoDeclareNode;
ExternProtoDeclare48: TExternProtoDeclareNode;
ExternProtoDeclare49: TExternProtoDeclareNode;
Group50: TGroupNode;
NavigationInfo51: TNavigationInfoNode;
Viewpoint52: TViewpointNode;
Viewpoint53: TViewpointNode;
Viewpoint54: TViewpointNode;
Viewpoint55: TViewpointNode;
Transform56: TTransformNode;
PositionInterpolator57: TPositionInterpolatorNode;
TimeSensor58: TTimeSensorNode;
Viewpoint59: TViewpointNode;
DirectionalLight60: TDirectionalLightNode;
DirectionalLight61: TDirectionalLightNode;
Anchor62: TAnchorNode;
Transform63: TTransformNode;
Inline64: TInlineNode;
Viewpoint65: TViewpointNode;
Transform66: TTransformNode;
Anchor67: TAnchorNode;
Shape68: TShapeNode;
Appearance69: TAppearanceNode;
ProtoInstance70: TProtoInstanceNode;
Sphere71: TSphereNode;
Transform72: TTransformNode;
Anchor73: TAnchorNode;
Shape74: TShapeNode;
Appearance75: TAppearanceNode;
Material76: TMaterialNode;
Text77: TTextNode;
FontStyle78: TFontStyleNode;
Viewpoint79: TViewpointNode;
Transform80: TTransformNode;
Anchor81: TAnchorNode;
Shape82: TShapeNode;
Appearance83: TAppearanceNode;
ProtoInstance84: TProtoInstanceNode;
Sphere85: TSphereNode;
Transform86: TTransformNode;
Anchor87: TAnchorNode;
Shape88: TShapeNode;
Appearance89: TAppearanceNode;
Material90: TMaterialNode;
Text91: TTextNode;
FontStyle92: TFontStyleNode;
Viewpoint93: TViewpointNode;
Transform94: TTransformNode;
Anchor95: TAnchorNode;
Shape96: TShapeNode;
Appearance97: TAppearanceNode;
ProtoInstance98: TProtoInstanceNode;
Sphere99: TSphereNode;
Transform100: TTransformNode;
Anchor101: TAnchorNode;
Shape102: TShapeNode;
Appearance103: TAppearanceNode;
Material104: TMaterialNode;
Text105: TTextNode;
FontStyle106: TFontStyleNode;
Viewpoint107: TViewpointNode;
Transform108: TTransformNode;
Anchor109: TAnchorNode;
Shape110: TShapeNode;
Appearance111: TAppearanceNode;
ProtoInstance112: TProtoInstanceNode;
Sphere113: TSphereNode;
Transform114: TTransformNode;
Anchor115: TAnchorNode;
Shape116: TShapeNode;
Appearance117: TAppearanceNode;
Material118: TMaterialNode;
Text119: TTextNode;
FontStyle120: TFontStyleNode;
Viewpoint121: TViewpointNode;
Transform122: TTransformNode;
Anchor123: TAnchorNode;
Shape124: TShapeNode;
Appearance125: TAppearanceNode;
ProtoInstance126: TProtoInstanceNode;
Sphere127: TSphereNode;
Transform128: TTransformNode;
Anchor129: TAnchorNode;
Shape130: TShapeNode;
Appearance131: TAppearanceNode;
Material132: TMaterialNode;
Text133: TTextNode;
FontStyle134: TFontStyleNode;
Viewpoint135: TViewpointNode;
Transform136: TTransformNode;
Anchor137: TAnchorNode;
Shape138: TShapeNode;
Appearance139: TAppearanceNode;
ProtoInstance140: TProtoInstanceNode;
Sphere141: TSphereNode;
Transform142: TTransformNode;
Anchor143: TAnchorNode;
Shape144: TShapeNode;
Appearance145: TAppearanceNode;
Material146: TMaterialNode;
Text147: TTextNode;
FontStyle148: TFontStyleNode;
Viewpoint149: TViewpointNode;
Transform150: TTransformNode;
Anchor151: TAnchorNode;
Shape152: TShapeNode;
Appearance153: TAppearanceNode;
ProtoInstance154: TProtoInstanceNode;
Sphere155: TSphereNode;
Transform156: TTransformNode;
Anchor157: TAnchorNode;
Shape158: TShapeNode;
Appearance159: TAppearanceNode;
Material160: TMaterialNode;
Text161: TTextNode;
FontStyle162: TFontStyleNode;
Viewpoint163: TViewpointNode;
Transform164: TTransformNode;
Anchor165: TAnchorNode;
Shape166: TShapeNode;
Appearance167: TAppearanceNode;
ProtoInstance168: TProtoInstanceNode;
Sphere169: TSphereNode;
Transform170: TTransformNode;
Anchor171: TAnchorNode;
Shape172: TShapeNode;
Appearance173: TAppearanceNode;
Material174: TMaterialNode;
Text175: TTextNode;
FontStyle176: TFontStyleNode;
Viewpoint177: TViewpointNode;
Transform178: TTransformNode;
Anchor179: TAnchorNode;
Shape180: TShapeNode;
Appearance181: TAppearanceNode;
ProtoInstance182: TProtoInstanceNode;
Sphere183: TSphereNode;
Transform184: TTransformNode;
Anchor185: TAnchorNode;
Shape186: TShapeNode;
Appearance187: TAppearanceNode;
Material188: TMaterialNode;
Text189: TTextNode;
FontStyle190: TFontStyleNode;
Viewpoint191: TViewpointNode;
Transform192: TTransformNode;
Anchor193: TAnchorNode;
Shape194: TShapeNode;
Appearance195: TAppearanceNode;
ProtoInstance196: TProtoInstanceNode;
Sphere197: TSphereNode;
Transform198: TTransformNode;
Anchor199: TAnchorNode;
Shape200: TShapeNode;
Appearance201: TAppearanceNode;
Material202: TMaterialNode;
Text203: TTextNode;
FontStyle204: TFontStyleNode;
Viewpoint205: TViewpointNode;
Transform206: TTransformNode;
Anchor207: TAnchorNode;
Shape208: TShapeNode;
Appearance209: TAppearanceNode;
ProtoInstance210: TProtoInstanceNode;
Sphere211: TSphereNode;
Transform212: TTransformNode;
Anchor213: TAnchorNode;
Shape214: TShapeNode;
Appearance215: TAppearanceNode;
Material216: TMaterialNode;
Text217: TTextNode;
FontStyle218: TFontStyleNode;
Viewpoint219: TViewpointNode;
Transform220: TTransformNode;
Anchor221: TAnchorNode;
Shape222: TShapeNode;
Appearance223: TAppearanceNode;
ProtoInstance224: TProtoInstanceNode;
Sphere225: TSphereNode;
Transform226: TTransformNode;
Anchor227: TAnchorNode;
Shape228: TShapeNode;
Appearance229: TAppearanceNode;
Material230: TMaterialNode;
Text231: TTextNode;
FontStyle232: TFontStyleNode;
Viewpoint233: TViewpointNode;
Transform234: TTransformNode;
Anchor235: TAnchorNode;
Shape236: TShapeNode;
Appearance237: TAppearanceNode;
ProtoInstance238: TProtoInstanceNode;
Sphere239: TSphereNode;
Transform240: TTransformNode;
Anchor241: TAnchorNode;
Shape242: TShapeNode;
Appearance243: TAppearanceNode;
Material244: TMaterialNode;
Text245: TTextNode;
FontStyle246: TFontStyleNode;
Viewpoint247: TViewpointNode;
Transform248: TTransformNode;
Anchor249: TAnchorNode;
Shape250: TShapeNode;
Appearance251: TAppearanceNode;
ProtoInstance252: TProtoInstanceNode;
Sphere253: TSphereNode;
Transform254: TTransformNode;
Anchor255: TAnchorNode;
Shape256: TShapeNode;
Appearance257: TAppearanceNode;
Material258: TMaterialNode;
Text259: TTextNode;
FontStyle260: TFontStyleNode;
Viewpoint261: TViewpointNode;
Transform262: TTransformNode;
Anchor263: TAnchorNode;
Shape264: TShapeNode;
Appearance265: TAppearanceNode;
ProtoInstance266: TProtoInstanceNode;
Sphere267: TSphereNode;
Transform268: TTransformNode;
Anchor269: TAnchorNode;
Shape270: TShapeNode;
Appearance271: TAppearanceNode;
Material272: TMaterialNode;
Text273: TTextNode;
FontStyle274: TFontStyleNode;
Viewpoint275: TViewpointNode;
Transform276: TTransformNode;
Anchor277: TAnchorNode;
Shape278: TShapeNode;
Appearance279: TAppearanceNode;
ProtoInstance280: TProtoInstanceNode;
Sphere281: TSphereNode;
Transform282: TTransformNode;
Anchor283: TAnchorNode;
Shape284: TShapeNode;
Appearance285: TAppearanceNode;
Material286: TMaterialNode;
Text287: TTextNode;
FontStyle288: TFontStyleNode;
Viewpoint289: TViewpointNode;
Transform290: TTransformNode;
Anchor291: TAnchorNode;
Shape292: TShapeNode;
Appearance293: TAppearanceNode;
ProtoInstance294: TProtoInstanceNode;
Sphere295: TSphereNode;
Transform296: TTransformNode;
Anchor297: TAnchorNode;
Shape298: TShapeNode;
Appearance299: TAppearanceNode;
Material300: TMaterialNode;
Text301: TTextNode;
FontStyle302: TFontStyleNode;
Viewpoint303: TViewpointNode;
Transform304: TTransformNode;
Anchor305: TAnchorNode;
Shape306: TShapeNode;
Appearance307: TAppearanceNode;
ProtoInstance308: TProtoInstanceNode;
Sphere309: TSphereNode;
Transform310: TTransformNode;
Anchor311: TAnchorNode;
Shape312: TShapeNode;
Appearance313: TAppearanceNode;
Material314: TMaterialNode;
Text315: TTextNode;
FontStyle316: TFontStyleNode;
Viewpoint317: TViewpointNode;
Transform318: TTransformNode;
Anchor319: TAnchorNode;
Shape320: TShapeNode;
Appearance321: TAppearanceNode;
ProtoInstance322: TProtoInstanceNode;
Sphere323: TSphereNode;
Transform324: TTransformNode;
Anchor325: TAnchorNode;
Shape326: TShapeNode;
Appearance327: TAppearanceNode;
Material328: TMaterialNode;
Text329: TTextNode;
FontStyle330: TFontStyleNode;
Viewpoint331: TViewpointNode;
Transform332: TTransformNode;
Anchor333: TAnchorNode;
Shape334: TShapeNode;
Appearance335: TAppearanceNode;
ProtoInstance336: TProtoInstanceNode;
Sphere337: TSphereNode;
Transform338: TTransformNode;
Anchor339: TAnchorNode;
Shape340: TShapeNode;
Appearance341: TAppearanceNode;
Material342: TMaterialNode;
Text343: TTextNode;
FontStyle344: TFontStyleNode;
Viewpoint345: TViewpointNode;
Transform346: TTransformNode;
Anchor347: TAnchorNode;
Shape348: TShapeNode;
Appearance349: TAppearanceNode;
ProtoInstance350: TProtoInstanceNode;
Sphere351: TSphereNode;
Transform352: TTransformNode;
Anchor353: TAnchorNode;
Shape354: TShapeNode;
Appearance355: TAppearanceNode;
Material356: TMaterialNode;
Text357: TTextNode;
FontStyle358: TFontStyleNode;
Viewpoint359: TViewpointNode;
Transform360: TTransformNode;
Anchor361: TAnchorNode;
Shape362: TShapeNode;
Appearance363: TAppearanceNode;
ProtoInstance364: TProtoInstanceNode;
Sphere365: TSphereNode;
Transform366: TTransformNode;
Anchor367: TAnchorNode;
Shape368: TShapeNode;
Appearance369: TAppearanceNode;
Material370: TMaterialNode;
Text371: TTextNode;
FontStyle372: TFontStyleNode;
Viewpoint373: TViewpointNode;
Transform374: TTransformNode;
Anchor375: TAnchorNode;
Shape376: TShapeNode;
Appearance377: TAppearanceNode;
ProtoInstance378: TProtoInstanceNode;
Sphere379: TSphereNode;
Transform380: TTransformNode;
Anchor381: TAnchorNode;
Shape382: TShapeNode;
Appearance383: TAppearanceNode;
Material384: TMaterialNode;
Text385: TTextNode;
FontStyle386: TFontStyleNode;
Viewpoint387: TViewpointNode;
Transform388: TTransformNode;
Anchor389: TAnchorNode;
Shape390: TShapeNode;
Appearance391: TAppearanceNode;
ProtoInstance392: TProtoInstanceNode;
Sphere393: TSphereNode;
Transform394: TTransformNode;
Anchor395: TAnchorNode;
Shape396: TShapeNode;
Appearance397: TAppearanceNode;
Material398: TMaterialNode;
Text399: TTextNode;
FontStyle400: TFontStyleNode;
Viewpoint401: TViewpointNode;
Transform402: TTransformNode;
Anchor403: TAnchorNode;
Shape404: TShapeNode;
Appearance405: TAppearanceNode;
ProtoInstance406: TProtoInstanceNode;
Sphere407: TSphereNode;
Transform408: TTransformNode;
Anchor409: TAnchorNode;
Shape410: TShapeNode;
Appearance411: TAppearanceNode;
Material412: TMaterialNode;
Text413: TTextNode;
FontStyle414: TFontStyleNode;
Viewpoint415: TViewpointNode;
Transform416: TTransformNode;
Anchor417: TAnchorNode;
Shape418: TShapeNode;
Appearance419: TAppearanceNode;
ProtoInstance420: TProtoInstanceNode;
Sphere421: TSphereNode;
Transform422: TTransformNode;
Anchor423: TAnchorNode;
Shape424: TShapeNode;
Appearance425: TAppearanceNode;
Material426: TMaterialNode;
Text427: TTextNode;
FontStyle428: TFontStyleNode;
Viewpoint429: TViewpointNode;
Transform430: TTransformNode;
Anchor431: TAnchorNode;
Shape432: TShapeNode;
Appearance433: TAppearanceNode;
ProtoInstance434: TProtoInstanceNode;
Sphere435: TSphereNode;
Transform436: TTransformNode;
Anchor437: TAnchorNode;
Shape438: TShapeNode;
Appearance439: TAppearanceNode;
Material440: TMaterialNode;
Text441: TTextNode;
FontStyle442: TFontStyleNode;
Viewpoint443: TViewpointNode;
Transform444: TTransformNode;
Anchor445: TAnchorNode;
Shape446: TShapeNode;
Appearance447: TAppearanceNode;
ProtoInstance448: TProtoInstanceNode;
Sphere449: TSphereNode;
Transform450: TTransformNode;
Anchor451: TAnchorNode;
Shape452: TShapeNode;
Appearance453: TAppearanceNode;
Material454: TMaterialNode;
Text455: TTextNode;
FontStyle456: TFontStyleNode;
Viewpoint457: TViewpointNode;
Transform458: TTransformNode;
Anchor459: TAnchorNode;
Shape460: TShapeNode;
Appearance461: TAppearanceNode;
ProtoInstance462: TProtoInstanceNode;
Sphere463: TSphereNode;
Transform464: TTransformNode;
Anchor465: TAnchorNode;
Shape466: TShapeNode;
Appearance467: TAppearanceNode;
Material468: TMaterialNode;
Text469: TTextNode;
FontStyle470: TFontStyleNode;
Viewpoint471: TViewpointNode;
Transform472: TTransformNode;
Anchor473: TAnchorNode;
Shape474: TShapeNode;
Appearance475: TAppearanceNode;
ProtoInstance476: TProtoInstanceNode;
Sphere477: TSphereNode;
Transform478: TTransformNode;
Anchor479: TAnchorNode;
Shape480: TShapeNode;
Appearance481: TAppearanceNode;
Material482: TMaterialNode;
Text483: TTextNode;
FontStyle484: TFontStyleNode;
Viewpoint485: TViewpointNode;
Transform486: TTransformNode;
Anchor487: TAnchorNode;
Shape488: TShapeNode;
Appearance489: TAppearanceNode;
ProtoInstance490: TProtoInstanceNode;
Sphere491: TSphereNode;
Transform492: TTransformNode;
Anchor493: TAnchorNode;
Shape494: TShapeNode;
Appearance495: TAppearanceNode;
Material496: TMaterialNode;
Text497: TTextNode;
FontStyle498: TFontStyleNode;
Viewpoint499: TViewpointNode;
Transform500: TTransformNode;
Anchor501: TAnchorNode;
Shape502: TShapeNode;
Appearance503: TAppearanceNode;
ProtoInstance504: TProtoInstanceNode;
Sphere505: TSphereNode;
Transform506: TTransformNode;
Anchor507: TAnchorNode;
Shape508: TShapeNode;
Appearance509: TAppearanceNode;
Material510: TMaterialNode;
Text511: TTextNode;
FontStyle512: TFontStyleNode;
Viewpoint513: TViewpointNode;
Transform514: TTransformNode;
Anchor515: TAnchorNode;
Shape516: TShapeNode;
Appearance517: TAppearanceNode;
ProtoInstance518: TProtoInstanceNode;
Sphere519: TSphereNode;
Transform520: TTransformNode;
Anchor521: TAnchorNode;
Shape522: TShapeNode;
Appearance523: TAppearanceNode;
Material524: TMaterialNode;
Text525: TTextNode;
FontStyle526: TFontStyleNode;
Viewpoint527: TViewpointNode;
Transform528: TTransformNode;
Anchor529: TAnchorNode;
Shape530: TShapeNode;
Appearance531: TAppearanceNode;
ProtoInstance532: TProtoInstanceNode;
Sphere533: TSphereNode;
Transform534: TTransformNode;
Anchor535: TAnchorNode;
Shape536: TShapeNode;
Appearance537: TAppearanceNode;
Material538: TMaterialNode;
Text539: TTextNode;
FontStyle540: TFontStyleNode;
Viewpoint541: TViewpointNode;
Transform542: TTransformNode;
Anchor543: TAnchorNode;
Shape544: TShapeNode;
Appearance545: TAppearanceNode;
ProtoInstance546: TProtoInstanceNode;
Sphere547: TSphereNode;
Transform548: TTransformNode;
Anchor549: TAnchorNode;
Shape550: TShapeNode;
Appearance551: TAppearanceNode;
Material552: TMaterialNode;
Text553: TTextNode;
FontStyle554: TFontStyleNode;
begin
X3D0 := TX3DRootNode.Create;
X3D0.Profile := 'Immersive';
X3D0.ForceVersion.Major := 3;
X3D0.ForceVersion.Minor := 0;
X3D0.Meta['title'] := 'ArtDecoExamples.x3d';
X3D0.Meta['description'] := 'Example ExternProtoDeclare/ProtoInstance usage of X3D/VRML materials, originally converted from SGI's Open Inventor material examples.';
X3D0.Meta['creator'] := 'David Roussel';
X3D0.Meta['translator'] := 'James Harney, Don Brutzman NPS';
X3D0.Meta['created'] := '7 April 2002';
X3D0.Meta['modified'] := '19 January 2025';
X3D0.Meta['reference'] := 'http://vrmlstuff.free.fr/materials';
X3D0.Meta['subject'] := 'Universal Media Material Library';
X3D0.Meta['identifier'] := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoExamples.x3d';
X3D0.Meta['generator'] := 'Vrml97ToX3dNist, http://ovrt.nist.gov/v2_x3d.html';
X3D0.Meta['license'] := '../license.html';
Group13 := TGroupNode.Create;
WorldInfo14 := TWorldInfoNode.Create;
WorldInfo14.Title := 'ArtDecoExamples.x3d';
{ .AddChildren }
Group13.AddChildren([WorldInfo14]);
ExternProtoDeclare15 := TExternProtoDeclareNode.Create;
ExternProtoDeclare15.NameField := 'ArtDeco00';
ExternProtoDeclare15.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare15.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare15.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco00','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco00','ArtDecoPrototypes.wrl#ArtDeco00','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco00']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare15]);
ExternProtoDeclare16 := TExternProtoDeclareNode.Create;
ExternProtoDeclare16.NameField := 'ArtDeco01';
ExternProtoDeclare16.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare16.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare16.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco01','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco01','ArtDecoPrototypes.wrl#ArtDeco01','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco01']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare16]);
ExternProtoDeclare17 := TExternProtoDeclareNode.Create;
ExternProtoDeclare17.NameField := 'ArtDeco02';
ExternProtoDeclare17.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare17.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare17.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco02','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco02','ArtDecoPrototypes.wrl#ArtDeco02','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco02']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare17]);
ExternProtoDeclare18 := TExternProtoDeclareNode.Create;
ExternProtoDeclare18.NameField := 'ArtDeco03';
ExternProtoDeclare18.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare18.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare18.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco03','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco03','ArtDecoPrototypes.wrl#ArtDeco03','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco03']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare18]);
ExternProtoDeclare19 := TExternProtoDeclareNode.Create;
ExternProtoDeclare19.NameField := 'ArtDeco04';
ExternProtoDeclare19.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare19.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare19.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco04','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco04','ArtDecoPrototypes.wrl#ArtDeco04','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco04']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare19]);
ExternProtoDeclare20 := TExternProtoDeclareNode.Create;
ExternProtoDeclare20.NameField := 'ArtDeco05';
ExternProtoDeclare20.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare20.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare20.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco05','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco05','ArtDecoPrototypes.wrl#ArtDeco05','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco05']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare20]);
ExternProtoDeclare21 := TExternProtoDeclareNode.Create;
ExternProtoDeclare21.NameField := 'ArtDeco06';
ExternProtoDeclare21.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare21.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare21.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco06','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco06','ArtDecoPrototypes.wrl#ArtDeco06','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco06']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare21]);
ExternProtoDeclare22 := TExternProtoDeclareNode.Create;
ExternProtoDeclare22.NameField := 'ArtDeco07';
ExternProtoDeclare22.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare22.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare22.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco07','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco07','ArtDecoPrototypes.wrl#ArtDeco07','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco07']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare22]);
ExternProtoDeclare23 := TExternProtoDeclareNode.Create;
ExternProtoDeclare23.NameField := 'ArtDeco08';
ExternProtoDeclare23.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare23.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare23.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco08','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco08','ArtDecoPrototypes.wrl#ArtDeco08','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco08']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare23]);
ExternProtoDeclare24 := TExternProtoDeclareNode.Create;
ExternProtoDeclare24.NameField := 'ArtDeco09';
ExternProtoDeclare24.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare24.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare24.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco09','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco09','ArtDecoPrototypes.wrl#ArtDeco09','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco09']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare24]);
ExternProtoDeclare25 := TExternProtoDeclareNode.Create;
ExternProtoDeclare25.NameField := 'ArtDeco10';
ExternProtoDeclare25.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare25.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare25.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco10','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco10','ArtDecoPrototypes.wrl#ArtDeco10','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco10']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare25]);
ExternProtoDeclare26 := TExternProtoDeclareNode.Create;
ExternProtoDeclare26.NameField := 'ArtDeco11';
ExternProtoDeclare26.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare26.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare26.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco11','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco11','ArtDecoPrototypes.wrl#ArtDeco11','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco11']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare26]);
ExternProtoDeclare27 := TExternProtoDeclareNode.Create;
ExternProtoDeclare27.NameField := 'ArtDeco12';
ExternProtoDeclare27.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare27.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare27.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco12','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco12','ArtDecoPrototypes.wrl#ArtDeco12','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco12']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare27]);
ExternProtoDeclare28 := TExternProtoDeclareNode.Create;
ExternProtoDeclare28.NameField := 'ArtDeco13';
ExternProtoDeclare28.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare28.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare28.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco13','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco13','ArtDecoPrototypes.wrl#ArtDeco13','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco13']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare28]);
ExternProtoDeclare29 := TExternProtoDeclareNode.Create;
ExternProtoDeclare29.NameField := 'ArtDeco14';
ExternProtoDeclare29.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare29.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare29.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco14','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco14','ArtDecoPrototypes.wrl#ArtDeco14','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco14']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare29]);
ExternProtoDeclare30 := TExternProtoDeclareNode.Create;
ExternProtoDeclare30.NameField := 'ArtDeco15';
ExternProtoDeclare30.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare30.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare30.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco15','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco15','ArtDecoPrototypes.wrl#ArtDeco15','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco15']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare30]);
ExternProtoDeclare31 := TExternProtoDeclareNode.Create;
ExternProtoDeclare31.NameField := 'ArtDeco16';
ExternProtoDeclare31.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare31.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare31.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco16','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco16','ArtDecoPrototypes.wrl#ArtDeco16','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco16']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare31]);
ExternProtoDeclare32 := TExternProtoDeclareNode.Create;
ExternProtoDeclare32.NameField := 'ArtDeco17';
ExternProtoDeclare32.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare32.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare32.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco17','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco17','ArtDecoPrototypes.wrl#ArtDeco17','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco17']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare32]);
ExternProtoDeclare33 := TExternProtoDeclareNode.Create;
ExternProtoDeclare33.NameField := 'ArtDeco18';
ExternProtoDeclare33.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare33.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare33.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco18','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco18','ArtDecoPrototypes.wrl#ArtDeco18','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco18']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare33]);
ExternProtoDeclare34 := TExternProtoDeclareNode.Create;
ExternProtoDeclare34.NameField := 'ArtDeco19';
ExternProtoDeclare34.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare34.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare34.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco19','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco19','ArtDecoPrototypes.wrl#ArtDeco19','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco19']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare34]);
ExternProtoDeclare35 := TExternProtoDeclareNode.Create;
ExternProtoDeclare35.NameField := 'ArtDeco20';
ExternProtoDeclare35.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare35.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare35.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco20','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco20','ArtDecoPrototypes.wrl#ArtDeco20','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco20']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare35]);
ExternProtoDeclare36 := TExternProtoDeclareNode.Create;
ExternProtoDeclare36.NameField := 'ArtDeco21';
ExternProtoDeclare36.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare36.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare36.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco21','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco21','ArtDecoPrototypes.wrl#ArtDeco21','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco21']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare36]);
ExternProtoDeclare37 := TExternProtoDeclareNode.Create;
ExternProtoDeclare37.NameField := 'ArtDeco22';
ExternProtoDeclare37.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare37.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare37.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco22','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco22','ArtDecoPrototypes.wrl#ArtDeco22','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco22']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare37]);
ExternProtoDeclare38 := TExternProtoDeclareNode.Create;
ExternProtoDeclare38.NameField := 'ArtDeco23';
ExternProtoDeclare38.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare38.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare38.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco23','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco23','ArtDecoPrototypes.wrl#ArtDeco23','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco23']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare38]);
ExternProtoDeclare39 := TExternProtoDeclareNode.Create;
ExternProtoDeclare39.NameField := 'ArtDeco24';
ExternProtoDeclare39.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare39.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare39.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco24','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco24','ArtDecoPrototypes.wrl#ArtDeco24','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco24']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare39]);
ExternProtoDeclare40 := TExternProtoDeclareNode.Create;
ExternProtoDeclare40.NameField := 'ArtDeco25';
ExternProtoDeclare40.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare40.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare40.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco25','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco25','ArtDecoPrototypes.wrl#ArtDeco25','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco25']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare40]);
ExternProtoDeclare41 := TExternProtoDeclareNode.Create;
ExternProtoDeclare41.NameField := 'ArtDeco26';
ExternProtoDeclare41.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare41.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare41.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco26','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco26','ArtDecoPrototypes.wrl#ArtDeco26','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco26']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare41]);
ExternProtoDeclare42 := TExternProtoDeclareNode.Create;
ExternProtoDeclare42.NameField := 'ArtDeco27';
ExternProtoDeclare42.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare42.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare42.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco27','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco27','ArtDecoPrototypes.wrl#ArtDeco27','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco27']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare42]);
ExternProtoDeclare43 := TExternProtoDeclareNode.Create;
ExternProtoDeclare43.NameField := 'ArtDeco28';
ExternProtoDeclare43.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare43.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare43.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco28','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco28','ArtDecoPrototypes.wrl#ArtDeco28','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco28']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare43]);
ExternProtoDeclare44 := TExternProtoDeclareNode.Create;
ExternProtoDeclare44.NameField := 'ArtDeco29';
ExternProtoDeclare44.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare44.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare44.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco29','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco29','ArtDecoPrototypes.wrl#ArtDeco29','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco29']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare44]);
ExternProtoDeclare45 := TExternProtoDeclareNode.Create;
ExternProtoDeclare45.NameField := 'ArtDeco30';
ExternProtoDeclare45.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare45.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare45.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco30','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco30','ArtDecoPrototypes.wrl#ArtDeco30','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco30']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare45]);
ExternProtoDeclare46 := TExternProtoDeclareNode.Create;
ExternProtoDeclare46.NameField := 'ArtDeco31';
ExternProtoDeclare46.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare46.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare46.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco31','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco31','ArtDecoPrototypes.wrl#ArtDeco31','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco31']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare46]);
ExternProtoDeclare47 := TExternProtoDeclareNode.Create;
ExternProtoDeclare47.NameField := 'ArtDeco32';
ExternProtoDeclare47.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare47.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare47.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco32','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco32','ArtDecoPrototypes.wrl#ArtDeco32','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco32']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare47]);
ExternProtoDeclare48 := TExternProtoDeclareNode.Create;
ExternProtoDeclare48.NameField := 'ArtDeco33';
ExternProtoDeclare48.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare48.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare48.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco33','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco33','ArtDecoPrototypes.wrl#ArtDeco33','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco33']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare48]);
ExternProtoDeclare49 := TExternProtoDeclareNode.Create;
ExternProtoDeclare49.NameField := 'ArtDeco34';
ExternProtoDeclare49.Appinfo := 'UniversalMediaMaterials prototype';
ExternProtoDeclare49.Documentation := 'https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials';
ExternProtoDeclare49.SetUrl(['ArtDecoPrototypes.x3d#ArtDeco34','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.x3d#ArtDeco34','ArtDecoPrototypes.wrl#ArtDeco34','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.wrl#ArtDeco34']);
{ .AddChildren }
Group13.AddChildren([ExternProtoDeclare49]);
Group50 := TGroupNode.Create;
NavigationInfo51 := TNavigationInfoNode.Create;
NavigationInfo51.Headlight := False;
{ .AddChildren }
Group50.AddChildren([NavigationInfo51]);
Viewpoint52 := TViewpointNode.Create;
Viewpoint52.Description := 'Front view';
Viewpoint52.Position := Vector3(0,0,12);
{ .AddChildren }
Group50.AddChildren([Viewpoint52]);
Viewpoint53 := TViewpointNode.Create;
Viewpoint53.Description := 'Low Right';
Viewpoint53.Orientation := Vector4(0.74291,0.30772,0.59447,1.2171);
Viewpoint53.Position := Vector3(6.9282,-6.9282,6.9282);
{ .AddChildren }
Group50.AddChildren([Viewpoint53]);
Viewpoint54 := TViewpointNode.Create;
Viewpoint54.Description := 'Low Left';
Viewpoint54.Orientation := Vector4(0.74291,-0.30772,-0.59447,1.2171);
Viewpoint54.Position := Vector3(-6.9282,-6.9282,6.9282);
{ .AddChildren }
Group50.AddChildren([Viewpoint54]);
Viewpoint55 := TViewpointNode.Create;
Viewpoint55.Description := 'Back view';
Viewpoint55.Orientation := Vector4(0,1,0,3.1416);
Viewpoint55.Position := Vector3(0,0,-12);
{ .AddChildren }
Group50.AddChildren([Viewpoint55]);
Transform56 := TTransformNode.Create;
PositionInterpolator57 := TPositionInterpolatorNode.Create;
PositionInterpolator57.SetKey([0,0.25,0.5,0.75,1]);
PositionInterpolator57.SetKeyValue([Vector3(0,2.5,0),Vector3(0,0,0),Vector3(0,-2.5,0),Vector3(0,0,0),Vector3(0,2.5,0)]);
{ .AddChildren }
Transform56.AddChildren([PositionInterpolator57]);
TimeSensor58 := TTimeSensorNode.Create;
TimeSensor58.CycleInterval := 12;
TimeSensor58.Loop := True;
{ .AddChildren }
Transform56.AddChildren([TimeSensor58]);
Viewpoint59 := TViewpointNode.Create;
Viewpoint59.Description := 'Close Front';
Viewpoint59.Position := Vector3(0,0,6);
{ .AddChildren }
Transform56.AddChildren([Viewpoint59]);
{ .AddChildren }
Group50.AddChildren([Transform56]);
DirectionalLight60 := TDirectionalLightNode.Create;
DirectionalLight60.Direction := Vector3(1,-1,-1);
{ .AddChildren }
Group50.AddChildren([DirectionalLight60]);
DirectionalLight61 := TDirectionalLightNode.Create;
DirectionalLight61.Direction := Vector3(0,1,-0.5);
DirectionalLight61.Intensity := 0.5;
{ .AddChildren }
Group50.AddChildren([DirectionalLight61]);
Anchor62 := TAnchorNode.Create;
Anchor62.Description := 'Return to front view';
Anchor62.SetUrl(['#Front']);
Transform63 := TTransformNode.Create;
Transform63.Translation := Vector3(0,0,-0.5);
Inline64 := TInlineNode.Create;
Inline64.SetUrl(['gridBack.x3d','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/gridBack.x3d','gridBack.wrl','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/gridBack.wrl']);
{ .AddChildren }
Transform63.AddChildren([Inline64]);
{ .AddChildren }
Anchor62.AddChildren([Transform63]);
{ .AddChildren }
Group50.AddChildren([Anchor62]);
Viewpoint65 := TViewpointNode.Create;
Viewpoint65.Description := 'ArtDeco00';
Viewpoint65.Position := Vector3(-3.75,3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint65]);
Transform66 := TTransformNode.Create;
Transform66.Translation := Vector3(-3.75,3.75,0);
Anchor67 := TAnchorNode.Create;
Anchor67.Description := 'ArtDeco00 view';
Anchor67.SetUrl(['#View00']);
Shape68 := TShapeNode.Create;
Appearance69 := TAppearanceNode.Create;
ProtoInstance70 := TProtoInstanceNode.Create;
ProtoInstance70.NameField := 'ArtDeco00';
{ .SetMaterial }
Appearance69.Material := ProtoInstance70;
{ .SetAppearance }
Shape68.Appearance := Appearance69;
Sphere71 := TSphereNode.Create;
Sphere71.Radius := 0.5;
{ .SetGeometry }
Shape68.Geometry := Sphere71;
{ .AddChildren }
Anchor67.AddChildren([Shape68]);
{ .AddChildren }
Transform66.AddChildren([Anchor67]);
Transform72 := TTransformNode.Create;
Transform72.Translation := Vector3(0,0.3,0.5);
Anchor73 := TAnchorNode.Create;
Anchor73.Description := 'ArtDeco00 view source documentation';
Anchor73.SetParameter(['target=_source']);
Anchor73.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco00','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco00']);
Shape74 := TShapeNode.Create;
Appearance75 := TAppearanceNode.Create;
Material76 := TMaterialNode.Create;
Material76.DiffuseColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance75.Material := Material76;
{ .SetAppearance }
Shape74.Appearance := Appearance75;
Text77 := TTextNode.Create;
Text77.SetText(['ArtDeco00']);
FontStyle78 := TFontStyleNode.Create;
FontStyle78.Family := ffSans;
FontStyle78.Justify := fjMiddle;
FontStyle78.JustifyMinor := fjMiddle;
FontStyle78.Size := 0.3;
FontStyle78.Style := 'BOLD';
{ .SetFontStyle }
Text77.FontStyle := FontStyle78;
{ .SetGeometry }
Shape74.Geometry := Text77;
{ .AddChildren }
Anchor73.AddChildren([Shape74]);
{ .AddChildren }
Transform72.AddChildren([Anchor73]);
{ .AddChildren }
Transform66.AddChildren([Transform72]);
{ .AddChildren }
Group50.AddChildren([Transform66]);
Viewpoint79 := TViewpointNode.Create;
Viewpoint79.Description := 'ArtDeco01';
Viewpoint79.Position := Vector3(-2.25,3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint79]);
Transform80 := TTransformNode.Create;
Transform80.Translation := Vector3(-2.25,3.75,0);
Anchor81 := TAnchorNode.Create;
Anchor81.Description := 'ArtDeco01 view';
Anchor81.SetUrl(['#View01']);
Shape82 := TShapeNode.Create;
Appearance83 := TAppearanceNode.Create;
ProtoInstance84 := TProtoInstanceNode.Create;
ProtoInstance84.NameField := 'ArtDeco01';
{ .SetMaterial }
Appearance83.Material := ProtoInstance84;
{ .SetAppearance }
Shape82.Appearance := Appearance83;
Sphere85 := TSphereNode.Create;
Sphere85 := Sphere71;
{ .SetGeometry }
Shape82.Geometry := Sphere85;
{ .AddChildren }
Anchor81.AddChildren([Shape82]);
{ .AddChildren }
Transform80.AddChildren([Anchor81]);
Transform86 := TTransformNode.Create;
Transform86.Translation := Vector3(0,0.3,0.5);
Anchor87 := TAnchorNode.Create;
Anchor87.Description := 'ArtDeco01 view source documentation';
Anchor87.SetParameter(['target=_source']);
Anchor87.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco01','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco01']);
Shape88 := TShapeNode.Create;
Appearance89 := TAppearanceNode.Create;
Material90 := TMaterialNode.Create;
Material90 := Material76;
{ .SetMaterial }
Appearance89.Material := Material90;
{ .SetAppearance }
Shape88.Appearance := Appearance89;
Text91 := TTextNode.Create;
Text91.SetText(['ArtDeco01']);
FontStyle92 := TFontStyleNode.Create;
FontStyle92 := FontStyle78;
{ .SetFontStyle }
Text91.FontStyle := FontStyle92;
{ .SetGeometry }
Shape88.Geometry := Text91;
{ .AddChildren }
Anchor87.AddChildren([Shape88]);
{ .AddChildren }
Transform86.AddChildren([Anchor87]);
{ .AddChildren }
Transform80.AddChildren([Transform86]);
{ .AddChildren }
Group50.AddChildren([Transform80]);
Viewpoint93 := TViewpointNode.Create;
Viewpoint93.Description := 'ArtDeco02';
Viewpoint93.Position := Vector3(-0.75,3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint93]);
Transform94 := TTransformNode.Create;
Transform94.Translation := Vector3(-0.75,3.75,0);
Anchor95 := TAnchorNode.Create;
Anchor95.Description := 'ArtDeco02 view';
Anchor95.SetUrl(['#View02']);
Shape96 := TShapeNode.Create;
Appearance97 := TAppearanceNode.Create;
ProtoInstance98 := TProtoInstanceNode.Create;
ProtoInstance98.NameField := 'ArtDeco02';
{ .SetMaterial }
Appearance97.Material := ProtoInstance98;
{ .SetAppearance }
Shape96.Appearance := Appearance97;
Sphere99 := TSphereNode.Create;
Sphere99 := Sphere71;
{ .SetGeometry }
Shape96.Geometry := Sphere99;
{ .AddChildren }
Anchor95.AddChildren([Shape96]);
{ .AddChildren }
Transform94.AddChildren([Anchor95]);
Transform100 := TTransformNode.Create;
Transform100.Translation := Vector3(0,0.3,0.5);
Anchor101 := TAnchorNode.Create;
Anchor101.Description := 'ArtDeco02 view source documentation';
Anchor101.SetParameter(['target=_source']);
Anchor101.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco02','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco02']);
Shape102 := TShapeNode.Create;
Appearance103 := TAppearanceNode.Create;
Material104 := TMaterialNode.Create;
Material104 := Material76;
{ .SetMaterial }
Appearance103.Material := Material104;
{ .SetAppearance }
Shape102.Appearance := Appearance103;
Text105 := TTextNode.Create;
Text105.SetText(['ArtDeco02']);
FontStyle106 := TFontStyleNode.Create;
FontStyle106 := FontStyle78;
{ .SetFontStyle }
Text105.FontStyle := FontStyle106;
{ .SetGeometry }
Shape102.Geometry := Text105;
{ .AddChildren }
Anchor101.AddChildren([Shape102]);
{ .AddChildren }
Transform100.AddChildren([Anchor101]);
{ .AddChildren }
Transform94.AddChildren([Transform100]);
{ .AddChildren }
Group50.AddChildren([Transform94]);
Viewpoint107 := TViewpointNode.Create;
Viewpoint107.Description := 'ArtDeco03';
Viewpoint107.Position := Vector3(0.75,3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint107]);
Transform108 := TTransformNode.Create;
Transform108.Translation := Vector3(0.75,3.75,0);
Anchor109 := TAnchorNode.Create;
Anchor109.Description := 'ArtDeco03 view';
Anchor109.SetUrl(['#View03']);
Shape110 := TShapeNode.Create;
Appearance111 := TAppearanceNode.Create;
ProtoInstance112 := TProtoInstanceNode.Create;
ProtoInstance112.NameField := 'ArtDeco03';
{ .SetMaterial }
Appearance111.Material := ProtoInstance112;
{ .SetAppearance }
Shape110.Appearance := Appearance111;
Sphere113 := TSphereNode.Create;
Sphere113 := Sphere71;
{ .SetGeometry }
Shape110.Geometry := Sphere113;
{ .AddChildren }
Anchor109.AddChildren([Shape110]);
{ .AddChildren }
Transform108.AddChildren([Anchor109]);
Transform114 := TTransformNode.Create;
Transform114.Translation := Vector3(0,0.3,0.5);
Anchor115 := TAnchorNode.Create;
Anchor115.Description := 'ArtDeco03 view source documentation';
Anchor115.SetParameter(['target=_source']);
Anchor115.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco03','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco03']);
Shape116 := TShapeNode.Create;
Appearance117 := TAppearanceNode.Create;
Material118 := TMaterialNode.Create;
Material118 := Material76;
{ .SetMaterial }
Appearance117.Material := Material118;
{ .SetAppearance }
Shape116.Appearance := Appearance117;
Text119 := TTextNode.Create;
Text119.SetText(['ArtDeco03']);
FontStyle120 := TFontStyleNode.Create;
FontStyle120 := FontStyle78;
{ .SetFontStyle }
Text119.FontStyle := FontStyle120;
{ .SetGeometry }
Shape116.Geometry := Text119;
{ .AddChildren }
Anchor115.AddChildren([Shape116]);
{ .AddChildren }
Transform114.AddChildren([Anchor115]);
{ .AddChildren }
Transform108.AddChildren([Transform114]);
{ .AddChildren }
Group50.AddChildren([Transform108]);
Viewpoint121 := TViewpointNode.Create;
Viewpoint121.Description := 'ArtDeco04';
Viewpoint121.Position := Vector3(2.25,3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint121]);
Transform122 := TTransformNode.Create;
Transform122.Translation := Vector3(2.25,3.75,0);
Anchor123 := TAnchorNode.Create;
Anchor123.Description := 'ArtDeco04 view';
Anchor123.SetUrl(['#View04']);
Shape124 := TShapeNode.Create;
Appearance125 := TAppearanceNode.Create;
ProtoInstance126 := TProtoInstanceNode.Create;
ProtoInstance126.NameField := 'ArtDeco04';
{ .SetMaterial }
Appearance125.Material := ProtoInstance126;
{ .SetAppearance }
Shape124.Appearance := Appearance125;
Sphere127 := TSphereNode.Create;
Sphere127 := Sphere71;
{ .SetGeometry }
Shape124.Geometry := Sphere127;
{ .AddChildren }
Anchor123.AddChildren([Shape124]);
{ .AddChildren }
Transform122.AddChildren([Anchor123]);
Transform128 := TTransformNode.Create;
Transform128.Translation := Vector3(0,0.3,0.5);
Anchor129 := TAnchorNode.Create;
Anchor129.Description := 'ArtDeco04 view source documentation';
Anchor129.SetParameter(['target=_source']);
Anchor129.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco04','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco04']);
Shape130 := TShapeNode.Create;
Appearance131 := TAppearanceNode.Create;
Material132 := TMaterialNode.Create;
Material132 := Material76;
{ .SetMaterial }
Appearance131.Material := Material132;
{ .SetAppearance }
Shape130.Appearance := Appearance131;
Text133 := TTextNode.Create;
Text133.SetText(['ArtDeco04']);
FontStyle134 := TFontStyleNode.Create;
FontStyle134 := FontStyle78;
{ .SetFontStyle }
Text133.FontStyle := FontStyle134;
{ .SetGeometry }
Shape130.Geometry := Text133;
{ .AddChildren }
Anchor129.AddChildren([Shape130]);
{ .AddChildren }
Transform128.AddChildren([Anchor129]);
{ .AddChildren }
Transform122.AddChildren([Transform128]);
{ .AddChildren }
Group50.AddChildren([Transform122]);
Viewpoint135 := TViewpointNode.Create;
Viewpoint135.Description := 'ArtDeco05';
Viewpoint135.Position := Vector3(3.75,3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint135]);
Transform136 := TTransformNode.Create;
Transform136.Translation := Vector3(3.75,3.75,0);
Anchor137 := TAnchorNode.Create;
Anchor137.Description := 'ArtDeco05 view';
Anchor137.SetUrl(['#View05']);
Shape138 := TShapeNode.Create;
Appearance139 := TAppearanceNode.Create;
ProtoInstance140 := TProtoInstanceNode.Create;
ProtoInstance140.NameField := 'ArtDeco05';
{ .SetMaterial }
Appearance139.Material := ProtoInstance140;
{ .SetAppearance }
Shape138.Appearance := Appearance139;
Sphere141 := TSphereNode.Create;
Sphere141 := Sphere71;
{ .SetGeometry }
Shape138.Geometry := Sphere141;
{ .AddChildren }
Anchor137.AddChildren([Shape138]);
{ .AddChildren }
Transform136.AddChildren([Anchor137]);
Transform142 := TTransformNode.Create;
Transform142.Translation := Vector3(0,0.3,0.5);
Anchor143 := TAnchorNode.Create;
Anchor143.Description := 'ArtDeco05 view source documentation';
Anchor143.SetParameter(['target=_source']);
Anchor143.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco05','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco05']);
Shape144 := TShapeNode.Create;
Appearance145 := TAppearanceNode.Create;
Material146 := TMaterialNode.Create;
Material146 := Material76;
{ .SetMaterial }
Appearance145.Material := Material146;
{ .SetAppearance }
Shape144.Appearance := Appearance145;
Text147 := TTextNode.Create;
Text147.SetText(['ArtDeco05']);
FontStyle148 := TFontStyleNode.Create;
FontStyle148 := FontStyle78;
{ .SetFontStyle }
Text147.FontStyle := FontStyle148;
{ .SetGeometry }
Shape144.Geometry := Text147;
{ .AddChildren }
Anchor143.AddChildren([Shape144]);
{ .AddChildren }
Transform142.AddChildren([Anchor143]);
{ .AddChildren }
Transform136.AddChildren([Transform142]);
{ .AddChildren }
Group50.AddChildren([Transform136]);
Viewpoint149 := TViewpointNode.Create;
Viewpoint149.Description := 'ArtDeco06';
Viewpoint149.Position := Vector3(-3.75,2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint149]);
Transform150 := TTransformNode.Create;
Transform150.Translation := Vector3(-3.75,2.25,0);
Anchor151 := TAnchorNode.Create;
Anchor151.Description := 'ArtDeco06 view';
Anchor151.SetUrl(['#View06']);
Shape152 := TShapeNode.Create;
Appearance153 := TAppearanceNode.Create;
ProtoInstance154 := TProtoInstanceNode.Create;
ProtoInstance154.NameField := 'ArtDeco06';
{ .SetMaterial }
Appearance153.Material := ProtoInstance154;
{ .SetAppearance }
Shape152.Appearance := Appearance153;
Sphere155 := TSphereNode.Create;
Sphere155 := Sphere71;
{ .SetGeometry }
Shape152.Geometry := Sphere155;
{ .AddChildren }
Anchor151.AddChildren([Shape152]);
{ .AddChildren }
Transform150.AddChildren([Anchor151]);
Transform156 := TTransformNode.Create;
Transform156.Translation := Vector3(0,0.3,0.5);
Anchor157 := TAnchorNode.Create;
Anchor157.Description := 'ArtDeco06 view source documentation';
Anchor157.SetParameter(['target=_source']);
Anchor157.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco06','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco06']);
Shape158 := TShapeNode.Create;
Appearance159 := TAppearanceNode.Create;
Material160 := TMaterialNode.Create;
Material160 := Material76;
{ .SetMaterial }
Appearance159.Material := Material160;
{ .SetAppearance }
Shape158.Appearance := Appearance159;
Text161 := TTextNode.Create;
Text161.SetText(['ArtDeco06']);
FontStyle162 := TFontStyleNode.Create;
FontStyle162 := FontStyle78;
{ .SetFontStyle }
Text161.FontStyle := FontStyle162;
{ .SetGeometry }
Shape158.Geometry := Text161;
{ .AddChildren }
Anchor157.AddChildren([Shape158]);
{ .AddChildren }
Transform156.AddChildren([Anchor157]);
{ .AddChildren }
Transform150.AddChildren([Transform156]);
{ .AddChildren }
Group50.AddChildren([Transform150]);
Viewpoint163 := TViewpointNode.Create;
Viewpoint163.Description := 'ArtDeco07';
Viewpoint163.Position := Vector3(-2.25,2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint163]);
Transform164 := TTransformNode.Create;
Transform164.Translation := Vector3(-2.25,2.25,0);
Anchor165 := TAnchorNode.Create;
Anchor165.Description := 'ArtDeco07 view';
Anchor165.SetUrl(['#View07']);
Shape166 := TShapeNode.Create;
Appearance167 := TAppearanceNode.Create;
ProtoInstance168 := TProtoInstanceNode.Create;
ProtoInstance168.NameField := 'ArtDeco07';
{ .SetMaterial }
Appearance167.Material := ProtoInstance168;
{ .SetAppearance }
Shape166.Appearance := Appearance167;
Sphere169 := TSphereNode.Create;
Sphere169 := Sphere71;
{ .SetGeometry }
Shape166.Geometry := Sphere169;
{ .AddChildren }
Anchor165.AddChildren([Shape166]);
{ .AddChildren }
Transform164.AddChildren([Anchor165]);
Transform170 := TTransformNode.Create;
Transform170.Translation := Vector3(0,0.3,0.5);
Anchor171 := TAnchorNode.Create;
Anchor171.Description := 'ArtDeco07 view source documentation';
Anchor171.SetParameter(['target=_source']);
Anchor171.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco07','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco07']);
Shape172 := TShapeNode.Create;
Appearance173 := TAppearanceNode.Create;
Material174 := TMaterialNode.Create;
Material174 := Material76;
{ .SetMaterial }
Appearance173.Material := Material174;
{ .SetAppearance }
Shape172.Appearance := Appearance173;
Text175 := TTextNode.Create;
Text175.SetText(['ArtDeco07']);
FontStyle176 := TFontStyleNode.Create;
FontStyle176 := FontStyle78;
{ .SetFontStyle }
Text175.FontStyle := FontStyle176;
{ .SetGeometry }
Shape172.Geometry := Text175;
{ .AddChildren }
Anchor171.AddChildren([Shape172]);
{ .AddChildren }
Transform170.AddChildren([Anchor171]);
{ .AddChildren }
Transform164.AddChildren([Transform170]);
{ .AddChildren }
Group50.AddChildren([Transform164]);
Viewpoint177 := TViewpointNode.Create;
Viewpoint177.Description := 'ArtDeco08';
Viewpoint177.Position := Vector3(-0.75,2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint177]);
Transform178 := TTransformNode.Create;
Transform178.Translation := Vector3(-0.75,2.25,0);
Anchor179 := TAnchorNode.Create;
Anchor179.Description := 'ArtDeco08 view';
Anchor179.SetUrl(['#View08']);
Shape180 := TShapeNode.Create;
Appearance181 := TAppearanceNode.Create;
ProtoInstance182 := TProtoInstanceNode.Create;
ProtoInstance182.NameField := 'ArtDeco08';
{ .SetMaterial }
Appearance181.Material := ProtoInstance182;
{ .SetAppearance }
Shape180.Appearance := Appearance181;
Sphere183 := TSphereNode.Create;
Sphere183 := Sphere71;
{ .SetGeometry }
Shape180.Geometry := Sphere183;
{ .AddChildren }
Anchor179.AddChildren([Shape180]);
{ .AddChildren }
Transform178.AddChildren([Anchor179]);
Transform184 := TTransformNode.Create;
Transform184.Translation := Vector3(0,0.3,0.5);
Anchor185 := TAnchorNode.Create;
Anchor185.Description := 'ArtDeco08 view source documentation';
Anchor185.SetParameter(['target=_source']);
Anchor185.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco08','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco08']);
Shape186 := TShapeNode.Create;
Appearance187 := TAppearanceNode.Create;
Material188 := TMaterialNode.Create;
Material188 := Material76;
{ .SetMaterial }
Appearance187.Material := Material188;
{ .SetAppearance }
Shape186.Appearance := Appearance187;
Text189 := TTextNode.Create;
Text189.SetText(['ArtDeco08']);
FontStyle190 := TFontStyleNode.Create;
FontStyle190 := FontStyle78;
{ .SetFontStyle }
Text189.FontStyle := FontStyle190;
{ .SetGeometry }
Shape186.Geometry := Text189;
{ .AddChildren }
Anchor185.AddChildren([Shape186]);
{ .AddChildren }
Transform184.AddChildren([Anchor185]);
{ .AddChildren }
Transform178.AddChildren([Transform184]);
{ .AddChildren }
Group50.AddChildren([Transform178]);
Viewpoint191 := TViewpointNode.Create;
Viewpoint191.Description := 'ArtDeco09';
Viewpoint191.Position := Vector3(0.75,2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint191]);
Transform192 := TTransformNode.Create;
Transform192.Translation := Vector3(0.75,2.25,0);
Anchor193 := TAnchorNode.Create;
Anchor193.Description := 'ArtDeco09 view';
Anchor193.SetUrl(['#View09']);
Shape194 := TShapeNode.Create;
Appearance195 := TAppearanceNode.Create;
ProtoInstance196 := TProtoInstanceNode.Create;
ProtoInstance196.NameField := 'ArtDeco09';
{ .SetMaterial }
Appearance195.Material := ProtoInstance196;
{ .SetAppearance }
Shape194.Appearance := Appearance195;
Sphere197 := TSphereNode.Create;
Sphere197 := Sphere71;
{ .SetGeometry }
Shape194.Geometry := Sphere197;
{ .AddChildren }
Anchor193.AddChildren([Shape194]);
{ .AddChildren }
Transform192.AddChildren([Anchor193]);
Transform198 := TTransformNode.Create;
Transform198.Translation := Vector3(0,0.3,0.5);
Anchor199 := TAnchorNode.Create;
Anchor199.Description := 'ArtDeco09 view source documentation';
Anchor199.SetParameter(['target=_source']);
Anchor199.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco09','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco09']);
Shape200 := TShapeNode.Create;
Appearance201 := TAppearanceNode.Create;
Material202 := TMaterialNode.Create;
Material202 := Material76;
{ .SetMaterial }
Appearance201.Material := Material202;
{ .SetAppearance }
Shape200.Appearance := Appearance201;
Text203 := TTextNode.Create;
Text203.SetText(['ArtDeco09']);
FontStyle204 := TFontStyleNode.Create;
FontStyle204 := FontStyle78;
{ .SetFontStyle }
Text203.FontStyle := FontStyle204;
{ .SetGeometry }
Shape200.Geometry := Text203;
{ .AddChildren }
Anchor199.AddChildren([Shape200]);
{ .AddChildren }
Transform198.AddChildren([Anchor199]);
{ .AddChildren }
Transform192.AddChildren([Transform198]);
{ .AddChildren }
Group50.AddChildren([Transform192]);
Viewpoint205 := TViewpointNode.Create;
Viewpoint205.Description := 'ArtDeco10';
Viewpoint205.Position := Vector3(2.25,2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint205]);
Transform206 := TTransformNode.Create;
Transform206.Translation := Vector3(2.25,2.25,0);
Anchor207 := TAnchorNode.Create;
Anchor207.Description := 'ArtDeco10 view';
Anchor207.SetUrl(['#View10']);
Shape208 := TShapeNode.Create;
Appearance209 := TAppearanceNode.Create;
ProtoInstance210 := TProtoInstanceNode.Create;
ProtoInstance210.NameField := 'ArtDeco10';
{ .SetMaterial }
Appearance209.Material := ProtoInstance210;
{ .SetAppearance }
Shape208.Appearance := Appearance209;
Sphere211 := TSphereNode.Create;
Sphere211 := Sphere71;
{ .SetGeometry }
Shape208.Geometry := Sphere211;
{ .AddChildren }
Anchor207.AddChildren([Shape208]);
{ .AddChildren }
Transform206.AddChildren([Anchor207]);
Transform212 := TTransformNode.Create;
Transform212.Translation := Vector3(0,0.3,0.5);
Anchor213 := TAnchorNode.Create;
Anchor213.Description := 'ArtDeco10 view source documentation';
Anchor213.SetParameter(['target=_source']);
Anchor213.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco10','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco10']);
Shape214 := TShapeNode.Create;
Appearance215 := TAppearanceNode.Create;
Material216 := TMaterialNode.Create;
Material216 := Material76;
{ .SetMaterial }
Appearance215.Material := Material216;
{ .SetAppearance }
Shape214.Appearance := Appearance215;
Text217 := TTextNode.Create;
Text217.SetText(['ArtDeco10']);
FontStyle218 := TFontStyleNode.Create;
FontStyle218 := FontStyle78;
{ .SetFontStyle }
Text217.FontStyle := FontStyle218;
{ .SetGeometry }
Shape214.Geometry := Text217;
{ .AddChildren }
Anchor213.AddChildren([Shape214]);
{ .AddChildren }
Transform212.AddChildren([Anchor213]);
{ .AddChildren }
Transform206.AddChildren([Transform212]);
{ .AddChildren }
Group50.AddChildren([Transform206]);
Viewpoint219 := TViewpointNode.Create;
Viewpoint219.Description := 'ArtDeco11';
Viewpoint219.Position := Vector3(3.75,2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint219]);
Transform220 := TTransformNode.Create;
Transform220.Translation := Vector3(3.75,2.25,0);
Anchor221 := TAnchorNode.Create;
Anchor221.Description := 'ArtDeco11 view';
Anchor221.SetUrl(['#View11']);
Shape222 := TShapeNode.Create;
Appearance223 := TAppearanceNode.Create;
ProtoInstance224 := TProtoInstanceNode.Create;
ProtoInstance224.NameField := 'ArtDeco11';
{ .SetMaterial }
Appearance223.Material := ProtoInstance224;
{ .SetAppearance }
Shape222.Appearance := Appearance223;
Sphere225 := TSphereNode.Create;
Sphere225 := Sphere71;
{ .SetGeometry }
Shape222.Geometry := Sphere225;
{ .AddChildren }
Anchor221.AddChildren([Shape222]);
{ .AddChildren }
Transform220.AddChildren([Anchor221]);
Transform226 := TTransformNode.Create;
Transform226.Translation := Vector3(0,0.3,0.5);
Anchor227 := TAnchorNode.Create;
Anchor227.Description := 'ArtDeco11 view source documentation';
Anchor227.SetParameter(['target=_source']);
Anchor227.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco11','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco11']);
Shape228 := TShapeNode.Create;
Appearance229 := TAppearanceNode.Create;
Material230 := TMaterialNode.Create;
Material230 := Material76;
{ .SetMaterial }
Appearance229.Material := Material230;
{ .SetAppearance }
Shape228.Appearance := Appearance229;
Text231 := TTextNode.Create;
Text231.SetText(['ArtDeco11']);
FontStyle232 := TFontStyleNode.Create;
FontStyle232 := FontStyle78;
{ .SetFontStyle }
Text231.FontStyle := FontStyle232;
{ .SetGeometry }
Shape228.Geometry := Text231;
{ .AddChildren }
Anchor227.AddChildren([Shape228]);
{ .AddChildren }
Transform226.AddChildren([Anchor227]);
{ .AddChildren }
Transform220.AddChildren([Transform226]);
{ .AddChildren }
Group50.AddChildren([Transform220]);
Viewpoint233 := TViewpointNode.Create;
Viewpoint233.Description := 'ArtDeco12';
Viewpoint233.Position := Vector3(-3.75,0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint233]);
Transform234 := TTransformNode.Create;
Transform234.Translation := Vector3(-3.75,0.75,0);
Anchor235 := TAnchorNode.Create;
Anchor235.Description := 'ArtDeco12 view';
Anchor235.SetUrl(['#View12']);
Shape236 := TShapeNode.Create;
Appearance237 := TAppearanceNode.Create;
ProtoInstance238 := TProtoInstanceNode.Create;
ProtoInstance238.NameField := 'ArtDeco12';
{ .SetMaterial }
Appearance237.Material := ProtoInstance238;
{ .SetAppearance }
Shape236.Appearance := Appearance237;
Sphere239 := TSphereNode.Create;
Sphere239 := Sphere71;
{ .SetGeometry }
Shape236.Geometry := Sphere239;
{ .AddChildren }
Anchor235.AddChildren([Shape236]);
{ .AddChildren }
Transform234.AddChildren([Anchor235]);
Transform240 := TTransformNode.Create;
Transform240.Translation := Vector3(0,0.3,0.5);
Anchor241 := TAnchorNode.Create;
Anchor241.Description := 'ArtDeco12 view source documentation';
Anchor241.SetParameter(['target=_source']);
Anchor241.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco12','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco12']);
Shape242 := TShapeNode.Create;
Appearance243 := TAppearanceNode.Create;
Material244 := TMaterialNode.Create;
Material244 := Material76;
{ .SetMaterial }
Appearance243.Material := Material244;
{ .SetAppearance }
Shape242.Appearance := Appearance243;
Text245 := TTextNode.Create;
Text245.SetText(['ArtDeco12']);
FontStyle246 := TFontStyleNode.Create;
FontStyle246 := FontStyle78;
{ .SetFontStyle }
Text245.FontStyle := FontStyle246;
{ .SetGeometry }
Shape242.Geometry := Text245;
{ .AddChildren }
Anchor241.AddChildren([Shape242]);
{ .AddChildren }
Transform240.AddChildren([Anchor241]);
{ .AddChildren }
Transform234.AddChildren([Transform240]);
{ .AddChildren }
Group50.AddChildren([Transform234]);
Viewpoint247 := TViewpointNode.Create;
Viewpoint247.Description := 'ArtDeco13';
Viewpoint247.Position := Vector3(-2.25,0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint247]);
Transform248 := TTransformNode.Create;
Transform248.Translation := Vector3(-2.25,0.75,0);
Anchor249 := TAnchorNode.Create;
Anchor249.Description := 'ArtDeco13 view';
Anchor249.SetUrl(['#View13']);
Shape250 := TShapeNode.Create;
Appearance251 := TAppearanceNode.Create;
ProtoInstance252 := TProtoInstanceNode.Create;
ProtoInstance252.NameField := 'ArtDeco13';
{ .SetMaterial }
Appearance251.Material := ProtoInstance252;
{ .SetAppearance }
Shape250.Appearance := Appearance251;
Sphere253 := TSphereNode.Create;
Sphere253 := Sphere71;
{ .SetGeometry }
Shape250.Geometry := Sphere253;
{ .AddChildren }
Anchor249.AddChildren([Shape250]);
{ .AddChildren }
Transform248.AddChildren([Anchor249]);
Transform254 := TTransformNode.Create;
Transform254.Translation := Vector3(0,0.3,0.5);
Anchor255 := TAnchorNode.Create;
Anchor255.Description := 'ArtDeco13 view source documentation';
Anchor255.SetParameter(['target=_source']);
Anchor255.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco3','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco13']);
Shape256 := TShapeNode.Create;
Appearance257 := TAppearanceNode.Create;
Material258 := TMaterialNode.Create;
Material258 := Material76;
{ .SetMaterial }
Appearance257.Material := Material258;
{ .SetAppearance }
Shape256.Appearance := Appearance257;
Text259 := TTextNode.Create;
Text259.SetText(['ArtDeco13']);
FontStyle260 := TFontStyleNode.Create;
FontStyle260 := FontStyle78;
{ .SetFontStyle }
Text259.FontStyle := FontStyle260;
{ .SetGeometry }
Shape256.Geometry := Text259;
{ .AddChildren }
Anchor255.AddChildren([Shape256]);
{ .AddChildren }
Transform254.AddChildren([Anchor255]);
{ .AddChildren }
Transform248.AddChildren([Transform254]);
{ .AddChildren }
Group50.AddChildren([Transform248]);
Viewpoint261 := TViewpointNode.Create;
Viewpoint261.Description := 'ArtDeco14';
Viewpoint261.Position := Vector3(-0.75,0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint261]);
Transform262 := TTransformNode.Create;
Transform262.Translation := Vector3(-0.75,0.75,0);
Anchor263 := TAnchorNode.Create;
Anchor263.Description := 'ArtDeco14 view';
Anchor263.SetUrl(['#View14']);
Shape264 := TShapeNode.Create;
Appearance265 := TAppearanceNode.Create;
ProtoInstance266 := TProtoInstanceNode.Create;
ProtoInstance266.NameField := 'ArtDeco14';
{ .SetMaterial }
Appearance265.Material := ProtoInstance266;
{ .SetAppearance }
Shape264.Appearance := Appearance265;
Sphere267 := TSphereNode.Create;
Sphere267 := Sphere71;
{ .SetGeometry }
Shape264.Geometry := Sphere267;
{ .AddChildren }
Anchor263.AddChildren([Shape264]);
{ .AddChildren }
Transform262.AddChildren([Anchor263]);
Transform268 := TTransformNode.Create;
Transform268.Translation := Vector3(0,0.3,0.5);
Anchor269 := TAnchorNode.Create;
Anchor269.Description := 'ArtDeco14 view source documentation';
Anchor269.SetParameter(['target=_source']);
Anchor269.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco4','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco14']);
Shape270 := TShapeNode.Create;
Appearance271 := TAppearanceNode.Create;
Material272 := TMaterialNode.Create;
Material272 := Material76;
{ .SetMaterial }
Appearance271.Material := Material272;
{ .SetAppearance }
Shape270.Appearance := Appearance271;
Text273 := TTextNode.Create;
Text273.SetText(['ArtDeco14']);
FontStyle274 := TFontStyleNode.Create;
FontStyle274 := FontStyle78;
{ .SetFontStyle }
Text273.FontStyle := FontStyle274;
{ .SetGeometry }
Shape270.Geometry := Text273;
{ .AddChildren }
Anchor269.AddChildren([Shape270]);
{ .AddChildren }
Transform268.AddChildren([Anchor269]);
{ .AddChildren }
Transform262.AddChildren([Transform268]);
{ .AddChildren }
Group50.AddChildren([Transform262]);
Viewpoint275 := TViewpointNode.Create;
Viewpoint275.Description := 'ArtDeco15';
Viewpoint275.Position := Vector3(0.75,0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint275]);
Transform276 := TTransformNode.Create;
Transform276.Translation := Vector3(0.75,0.75,0);
Anchor277 := TAnchorNode.Create;
Anchor277.Description := 'ArtDeco15 view';
Anchor277.SetUrl(['#View15']);
Shape278 := TShapeNode.Create;
Appearance279 := TAppearanceNode.Create;
ProtoInstance280 := TProtoInstanceNode.Create;
ProtoInstance280.NameField := 'ArtDeco15';
{ .SetMaterial }
Appearance279.Material := ProtoInstance280;
{ .SetAppearance }
Shape278.Appearance := Appearance279;
Sphere281 := TSphereNode.Create;
Sphere281 := Sphere71;
{ .SetGeometry }
Shape278.Geometry := Sphere281;
{ .AddChildren }
Anchor277.AddChildren([Shape278]);
{ .AddChildren }
Transform276.AddChildren([Anchor277]);
Transform282 := TTransformNode.Create;
Transform282.Translation := Vector3(0,0.3,0.5);
Anchor283 := TAnchorNode.Create;
Anchor283.Description := 'ArtDeco15 view source documentation';
Anchor283.SetParameter(['target=_source']);
Anchor283.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco5','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco15']);
Shape284 := TShapeNode.Create;
Appearance285 := TAppearanceNode.Create;
Material286 := TMaterialNode.Create;
Material286 := Material76;
{ .SetMaterial }
Appearance285.Material := Material286;
{ .SetAppearance }
Shape284.Appearance := Appearance285;
Text287 := TTextNode.Create;
Text287.SetText(['ArtDeco15']);
FontStyle288 := TFontStyleNode.Create;
FontStyle288 := FontStyle78;
{ .SetFontStyle }
Text287.FontStyle := FontStyle288;
{ .SetGeometry }
Shape284.Geometry := Text287;
{ .AddChildren }
Anchor283.AddChildren([Shape284]);
{ .AddChildren }
Transform282.AddChildren([Anchor283]);
{ .AddChildren }
Transform276.AddChildren([Transform282]);
{ .AddChildren }
Group50.AddChildren([Transform276]);
Viewpoint289 := TViewpointNode.Create;
Viewpoint289.Description := 'ArtDeco16';
Viewpoint289.Position := Vector3(2.25,0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint289]);
Transform290 := TTransformNode.Create;
Transform290.Translation := Vector3(2.25,0.75,0);
Anchor291 := TAnchorNode.Create;
Anchor291.Description := 'ArtDeco16 view';
Anchor291.SetUrl(['#View16']);
Shape292 := TShapeNode.Create;
Appearance293 := TAppearanceNode.Create;
ProtoInstance294 := TProtoInstanceNode.Create;
ProtoInstance294.NameField := 'ArtDeco16';
{ .SetMaterial }
Appearance293.Material := ProtoInstance294;
{ .SetAppearance }
Shape292.Appearance := Appearance293;
Sphere295 := TSphereNode.Create;
Sphere295 := Sphere71;
{ .SetGeometry }
Shape292.Geometry := Sphere295;
{ .AddChildren }
Anchor291.AddChildren([Shape292]);
{ .AddChildren }
Transform290.AddChildren([Anchor291]);
Transform296 := TTransformNode.Create;
Transform296.Translation := Vector3(0,0.3,0.5);
Anchor297 := TAnchorNode.Create;
Anchor297.Description := 'ArtDeco16 view source documentation';
Anchor297.SetParameter(['target=_source']);
Anchor297.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco16','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco16']);
Shape298 := TShapeNode.Create;
Appearance299 := TAppearanceNode.Create;
Material300 := TMaterialNode.Create;
Material300 := Material76;
{ .SetMaterial }
Appearance299.Material := Material300;
{ .SetAppearance }
Shape298.Appearance := Appearance299;
Text301 := TTextNode.Create;
Text301.SetText(['ArtDeco16']);
FontStyle302 := TFontStyleNode.Create;
FontStyle302 := FontStyle78;
{ .SetFontStyle }
Text301.FontStyle := FontStyle302;
{ .SetGeometry }
Shape298.Geometry := Text301;
{ .AddChildren }
Anchor297.AddChildren([Shape298]);
{ .AddChildren }
Transform296.AddChildren([Anchor297]);
{ .AddChildren }
Transform290.AddChildren([Transform296]);
{ .AddChildren }
Group50.AddChildren([Transform290]);
Viewpoint303 := TViewpointNode.Create;
Viewpoint303.Description := 'ArtDeco17';
Viewpoint303.Position := Vector3(3.75,0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint303]);
Transform304 := TTransformNode.Create;
Transform304.Translation := Vector3(3.75,0.75,0);
Anchor305 := TAnchorNode.Create;
Anchor305.Description := 'ArtDeco17 view';
Anchor305.SetUrl(['#View17']);
Shape306 := TShapeNode.Create;
Appearance307 := TAppearanceNode.Create;
ProtoInstance308 := TProtoInstanceNode.Create;
ProtoInstance308.NameField := 'ArtDeco17';
{ .SetMaterial }
Appearance307.Material := ProtoInstance308;
{ .SetAppearance }
Shape306.Appearance := Appearance307;
Sphere309 := TSphereNode.Create;
Sphere309 := Sphere71;
{ .SetGeometry }
Shape306.Geometry := Sphere309;
{ .AddChildren }
Anchor305.AddChildren([Shape306]);
{ .AddChildren }
Transform304.AddChildren([Anchor305]);
Transform310 := TTransformNode.Create;
Transform310.Translation := Vector3(0,0.3,0.5);
Anchor311 := TAnchorNode.Create;
Anchor311.Description := 'ArtDeco17 view source documentation';
Anchor311.SetParameter(['target=_source']);
Anchor311.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco7','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco17']);
Shape312 := TShapeNode.Create;
Appearance313 := TAppearanceNode.Create;
Material314 := TMaterialNode.Create;
Material314 := Material76;
{ .SetMaterial }
Appearance313.Material := Material314;
{ .SetAppearance }
Shape312.Appearance := Appearance313;
Text315 := TTextNode.Create;
Text315.SetText(['ArtDeco17']);
FontStyle316 := TFontStyleNode.Create;
FontStyle316 := FontStyle78;
{ .SetFontStyle }
Text315.FontStyle := FontStyle316;
{ .SetGeometry }
Shape312.Geometry := Text315;
{ .AddChildren }
Anchor311.AddChildren([Shape312]);
{ .AddChildren }
Transform310.AddChildren([Anchor311]);
{ .AddChildren }
Transform304.AddChildren([Transform310]);
{ .AddChildren }
Group50.AddChildren([Transform304]);
Viewpoint317 := TViewpointNode.Create;
Viewpoint317.Description := 'ArtDeco18';
Viewpoint317.Position := Vector3(-3.75,-0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint317]);
Transform318 := TTransformNode.Create;
Transform318.Translation := Vector3(-3.75,-0.75,0);
Anchor319 := TAnchorNode.Create;
Anchor319.Description := 'ArtDeco18 view';
Anchor319.SetUrl(['#View18']);
Shape320 := TShapeNode.Create;
Appearance321 := TAppearanceNode.Create;
ProtoInstance322 := TProtoInstanceNode.Create;
ProtoInstance322.NameField := 'ArtDeco18';
{ .SetMaterial }
Appearance321.Material := ProtoInstance322;
{ .SetAppearance }
Shape320.Appearance := Appearance321;
Sphere323 := TSphereNode.Create;
Sphere323 := Sphere71;
{ .SetGeometry }
Shape320.Geometry := Sphere323;
{ .AddChildren }
Anchor319.AddChildren([Shape320]);
{ .AddChildren }
Transform318.AddChildren([Anchor319]);
Transform324 := TTransformNode.Create;
Transform324.Translation := Vector3(0,0.3,0.5);
Anchor325 := TAnchorNode.Create;
Anchor325.Description := 'ArtDeco18 view source documentation';
Anchor325.SetParameter(['target=_source']);
Anchor325.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco18','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco18']);
Shape326 := TShapeNode.Create;
Appearance327 := TAppearanceNode.Create;
Material328 := TMaterialNode.Create;
Material328 := Material76;
{ .SetMaterial }
Appearance327.Material := Material328;
{ .SetAppearance }
Shape326.Appearance := Appearance327;
Text329 := TTextNode.Create;
Text329.SetText(['ArtDeco18']);
FontStyle330 := TFontStyleNode.Create;
FontStyle330 := FontStyle78;
{ .SetFontStyle }
Text329.FontStyle := FontStyle330;
{ .SetGeometry }
Shape326.Geometry := Text329;
{ .AddChildren }
Anchor325.AddChildren([Shape326]);
{ .AddChildren }
Transform324.AddChildren([Anchor325]);
{ .AddChildren }
Transform318.AddChildren([Transform324]);
{ .AddChildren }
Group50.AddChildren([Transform318]);
Viewpoint331 := TViewpointNode.Create;
Viewpoint331.Description := 'ArtDeco19';
Viewpoint331.Position := Vector3(-2.25,-0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint331]);
Transform332 := TTransformNode.Create;
Transform332.Translation := Vector3(-2.25,-0.75,0);
Anchor333 := TAnchorNode.Create;
Anchor333.Description := 'ArtDeco19 view';
Anchor333.SetUrl(['#View19']);
Shape334 := TShapeNode.Create;
Appearance335 := TAppearanceNode.Create;
ProtoInstance336 := TProtoInstanceNode.Create;
ProtoInstance336.NameField := 'ArtDeco19';
{ .SetMaterial }
Appearance335.Material := ProtoInstance336;
{ .SetAppearance }
Shape334.Appearance := Appearance335;
Sphere337 := TSphereNode.Create;
Sphere337 := Sphere71;
{ .SetGeometry }
Shape334.Geometry := Sphere337;
{ .AddChildren }
Anchor333.AddChildren([Shape334]);
{ .AddChildren }
Transform332.AddChildren([Anchor333]);
Transform338 := TTransformNode.Create;
Transform338.Translation := Vector3(0,0.3,0.5);
Anchor339 := TAnchorNode.Create;
Anchor339.Description := 'ArtDeco19 view source documentation';
Anchor339.SetParameter(['target=_source']);
Anchor339.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco9','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco19']);
Shape340 := TShapeNode.Create;
Appearance341 := TAppearanceNode.Create;
Material342 := TMaterialNode.Create;
Material342 := Material76;
{ .SetMaterial }
Appearance341.Material := Material342;
{ .SetAppearance }
Shape340.Appearance := Appearance341;
Text343 := TTextNode.Create;
Text343.SetText(['ArtDeco19']);
FontStyle344 := TFontStyleNode.Create;
FontStyle344 := FontStyle78;
{ .SetFontStyle }
Text343.FontStyle := FontStyle344;
{ .SetGeometry }
Shape340.Geometry := Text343;
{ .AddChildren }
Anchor339.AddChildren([Shape340]);
{ .AddChildren }
Transform338.AddChildren([Anchor339]);
{ .AddChildren }
Transform332.AddChildren([Transform338]);
{ .AddChildren }
Group50.AddChildren([Transform332]);
Viewpoint345 := TViewpointNode.Create;
Viewpoint345.Description := 'ArtDeco20';
Viewpoint345.Position := Vector3(-0.75,-0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint345]);
Transform346 := TTransformNode.Create;
Transform346.Translation := Vector3(-0.75,-0.75,0);
Anchor347 := TAnchorNode.Create;
Anchor347.Description := 'ArtDeco20 view';
Anchor347.SetUrl(['#View20']);
Shape348 := TShapeNode.Create;
Appearance349 := TAppearanceNode.Create;
ProtoInstance350 := TProtoInstanceNode.Create;
ProtoInstance350.NameField := 'ArtDeco20';
{ .SetMaterial }
Appearance349.Material := ProtoInstance350;
{ .SetAppearance }
Shape348.Appearance := Appearance349;
Sphere351 := TSphereNode.Create;
Sphere351 := Sphere71;
{ .SetGeometry }
Shape348.Geometry := Sphere351;
{ .AddChildren }
Anchor347.AddChildren([Shape348]);
{ .AddChildren }
Transform346.AddChildren([Anchor347]);
Transform352 := TTransformNode.Create;
Transform352.Translation := Vector3(0,0.3,0.5);
Anchor353 := TAnchorNode.Create;
Anchor353.Description := 'ArtDeco20 view source documentation';
Anchor353.SetParameter(['target=_source']);
Anchor353.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco20','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco20']);
Shape354 := TShapeNode.Create;
Appearance355 := TAppearanceNode.Create;
Material356 := TMaterialNode.Create;
Material356 := Material76;
{ .SetMaterial }
Appearance355.Material := Material356;
{ .SetAppearance }
Shape354.Appearance := Appearance355;
Text357 := TTextNode.Create;
Text357.SetText(['ArtDeco20']);
FontStyle358 := TFontStyleNode.Create;
FontStyle358 := FontStyle78;
{ .SetFontStyle }
Text357.FontStyle := FontStyle358;
{ .SetGeometry }
Shape354.Geometry := Text357;
{ .AddChildren }
Anchor353.AddChildren([Shape354]);
{ .AddChildren }
Transform352.AddChildren([Anchor353]);
{ .AddChildren }
Transform346.AddChildren([Transform352]);
{ .AddChildren }
Group50.AddChildren([Transform346]);
Viewpoint359 := TViewpointNode.Create;
Viewpoint359.Description := 'ArtDeco21';
Viewpoint359.Position := Vector3(0.75,-0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint359]);
Transform360 := TTransformNode.Create;
Transform360.Translation := Vector3(0.75,-0.75,0);
Anchor361 := TAnchorNode.Create;
Anchor361.Description := 'ArtDeco21 view';
Anchor361.SetUrl(['#View21']);
Shape362 := TShapeNode.Create;
Appearance363 := TAppearanceNode.Create;
ProtoInstance364 := TProtoInstanceNode.Create;
ProtoInstance364.NameField := 'ArtDeco21';
{ .SetMaterial }
Appearance363.Material := ProtoInstance364;
{ .SetAppearance }
Shape362.Appearance := Appearance363;
Sphere365 := TSphereNode.Create;
Sphere365 := Sphere71;
{ .SetGeometry }
Shape362.Geometry := Sphere365;
{ .AddChildren }
Anchor361.AddChildren([Shape362]);
{ .AddChildren }
Transform360.AddChildren([Anchor361]);
Transform366 := TTransformNode.Create;
Transform366.Translation := Vector3(0,0.3,0.5);
Anchor367 := TAnchorNode.Create;
Anchor367.Description := 'ArtDeco21 view source documentation';
Anchor367.SetParameter(['target=_source']);
Anchor367.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco21','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco21']);
Shape368 := TShapeNode.Create;
Appearance369 := TAppearanceNode.Create;
Material370 := TMaterialNode.Create;
Material370 := Material76;
{ .SetMaterial }
Appearance369.Material := Material370;
{ .SetAppearance }
Shape368.Appearance := Appearance369;
Text371 := TTextNode.Create;
Text371.SetText(['ArtDeco21']);
FontStyle372 := TFontStyleNode.Create;
FontStyle372 := FontStyle78;
{ .SetFontStyle }
Text371.FontStyle := FontStyle372;
{ .SetGeometry }
Shape368.Geometry := Text371;
{ .AddChildren }
Anchor367.AddChildren([Shape368]);
{ .AddChildren }
Transform366.AddChildren([Anchor367]);
{ .AddChildren }
Transform360.AddChildren([Transform366]);
{ .AddChildren }
Group50.AddChildren([Transform360]);
Viewpoint373 := TViewpointNode.Create;
Viewpoint373.Description := 'ArtDeco22';
Viewpoint373.Position := Vector3(2.25,-0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint373]);
Transform374 := TTransformNode.Create;
Transform374.Translation := Vector3(2.25,-0.75,0);
Anchor375 := TAnchorNode.Create;
Anchor375.Description := 'ArtDeco22 view';
Anchor375.SetUrl(['#View22']);
Shape376 := TShapeNode.Create;
Appearance377 := TAppearanceNode.Create;
ProtoInstance378 := TProtoInstanceNode.Create;
ProtoInstance378.NameField := 'ArtDeco22';
{ .SetMaterial }
Appearance377.Material := ProtoInstance378;
{ .SetAppearance }
Shape376.Appearance := Appearance377;
Sphere379 := TSphereNode.Create;
Sphere379 := Sphere71;
{ .SetGeometry }
Shape376.Geometry := Sphere379;
{ .AddChildren }
Anchor375.AddChildren([Shape376]);
{ .AddChildren }
Transform374.AddChildren([Anchor375]);
Transform380 := TTransformNode.Create;
Transform380.Translation := Vector3(0,0.3,0.5);
Anchor381 := TAnchorNode.Create;
Anchor381.Description := 'ArtDeco22 view source documentation';
Anchor381.SetParameter(['target=_source']);
Anchor381.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco22','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco22']);
Shape382 := TShapeNode.Create;
Appearance383 := TAppearanceNode.Create;
Material384 := TMaterialNode.Create;
Material384 := Material76;
{ .SetMaterial }
Appearance383.Material := Material384;
{ .SetAppearance }
Shape382.Appearance := Appearance383;
Text385 := TTextNode.Create;
Text385.SetText(['ArtDeco22']);
FontStyle386 := TFontStyleNode.Create;
FontStyle386 := FontStyle78;
{ .SetFontStyle }
Text385.FontStyle := FontStyle386;
{ .SetGeometry }
Shape382.Geometry := Text385;
{ .AddChildren }
Anchor381.AddChildren([Shape382]);
{ .AddChildren }
Transform380.AddChildren([Anchor381]);
{ .AddChildren }
Transform374.AddChildren([Transform380]);
{ .AddChildren }
Group50.AddChildren([Transform374]);
Viewpoint387 := TViewpointNode.Create;
Viewpoint387.Description := 'ArtDeco23';
Viewpoint387.Position := Vector3(3.75,-0.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint387]);
Transform388 := TTransformNode.Create;
Transform388.Translation := Vector3(3.75,-0.75,0);
Anchor389 := TAnchorNode.Create;
Anchor389.Description := 'ArtDeco23 view';
Anchor389.SetUrl(['#View23']);
Shape390 := TShapeNode.Create;
Appearance391 := TAppearanceNode.Create;
ProtoInstance392 := TProtoInstanceNode.Create;
ProtoInstance392.NameField := 'ArtDeco23';
{ .SetMaterial }
Appearance391.Material := ProtoInstance392;
{ .SetAppearance }
Shape390.Appearance := Appearance391;
Sphere393 := TSphereNode.Create;
Sphere393 := Sphere71;
{ .SetGeometry }
Shape390.Geometry := Sphere393;
{ .AddChildren }
Anchor389.AddChildren([Shape390]);
{ .AddChildren }
Transform388.AddChildren([Anchor389]);
Transform394 := TTransformNode.Create;
Transform394.Translation := Vector3(0,0.3,0.5);
Anchor395 := TAnchorNode.Create;
Anchor395.Description := 'ArtDeco23 view source documentation';
Anchor395.SetParameter(['target=_source']);
Anchor395.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco23','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco23']);
Shape396 := TShapeNode.Create;
Appearance397 := TAppearanceNode.Create;
Material398 := TMaterialNode.Create;
Material398 := Material76;
{ .SetMaterial }
Appearance397.Material := Material398;
{ .SetAppearance }
Shape396.Appearance := Appearance397;
Text399 := TTextNode.Create;
Text399.SetText(['ArtDeco23']);
FontStyle400 := TFontStyleNode.Create;
FontStyle400 := FontStyle78;
{ .SetFontStyle }
Text399.FontStyle := FontStyle400;
{ .SetGeometry }
Shape396.Geometry := Text399;
{ .AddChildren }
Anchor395.AddChildren([Shape396]);
{ .AddChildren }
Transform394.AddChildren([Anchor395]);
{ .AddChildren }
Transform388.AddChildren([Transform394]);
{ .AddChildren }
Group50.AddChildren([Transform388]);
Viewpoint401 := TViewpointNode.Create;
Viewpoint401.Description := 'ArtDeco24';
Viewpoint401.Position := Vector3(-3.75,-2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint401]);
Transform402 := TTransformNode.Create;
Transform402.Translation := Vector3(-3.75,-2.25,0);
Anchor403 := TAnchorNode.Create;
Anchor403.Description := 'ArtDeco24 view';
Anchor403.SetUrl(['#View24']);
Shape404 := TShapeNode.Create;
Appearance405 := TAppearanceNode.Create;
ProtoInstance406 := TProtoInstanceNode.Create;
ProtoInstance406.NameField := 'ArtDeco24';
{ .SetMaterial }
Appearance405.Material := ProtoInstance406;
{ .SetAppearance }
Shape404.Appearance := Appearance405;
Sphere407 := TSphereNode.Create;
Sphere407 := Sphere71;
{ .SetGeometry }
Shape404.Geometry := Sphere407;
{ .AddChildren }
Anchor403.AddChildren([Shape404]);
{ .AddChildren }
Transform402.AddChildren([Anchor403]);
Transform408 := TTransformNode.Create;
Transform408.Translation := Vector3(0,0.3,0.5);
Anchor409 := TAnchorNode.Create;
Anchor409.Description := 'ArtDeco24 view source documentation';
Anchor409.SetParameter(['target=_source']);
Anchor409.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco24','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco24']);
Shape410 := TShapeNode.Create;
Appearance411 := TAppearanceNode.Create;
Material412 := TMaterialNode.Create;
Material412 := Material76;
{ .SetMaterial }
Appearance411.Material := Material412;
{ .SetAppearance }
Shape410.Appearance := Appearance411;
Text413 := TTextNode.Create;
Text413.SetText(['ArtDeco24']);
FontStyle414 := TFontStyleNode.Create;
FontStyle414 := FontStyle78;
{ .SetFontStyle }
Text413.FontStyle := FontStyle414;
{ .SetGeometry }
Shape410.Geometry := Text413;
{ .AddChildren }
Anchor409.AddChildren([Shape410]);
{ .AddChildren }
Transform408.AddChildren([Anchor409]);
{ .AddChildren }
Transform402.AddChildren([Transform408]);
{ .AddChildren }
Group50.AddChildren([Transform402]);
Viewpoint415 := TViewpointNode.Create;
Viewpoint415.Description := 'ArtDeco25';
Viewpoint415.Position := Vector3(-2.25,-2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint415]);
Transform416 := TTransformNode.Create;
Transform416.Translation := Vector3(-2.25,-2.25,0);
Anchor417 := TAnchorNode.Create;
Anchor417.Description := 'ArtDeco25 view';
Anchor417.SetUrl(['#View25']);
Shape418 := TShapeNode.Create;
Appearance419 := TAppearanceNode.Create;
ProtoInstance420 := TProtoInstanceNode.Create;
ProtoInstance420.NameField := 'ArtDeco25';
{ .SetMaterial }
Appearance419.Material := ProtoInstance420;
{ .SetAppearance }
Shape418.Appearance := Appearance419;
Sphere421 := TSphereNode.Create;
Sphere421 := Sphere71;
{ .SetGeometry }
Shape418.Geometry := Sphere421;
{ .AddChildren }
Anchor417.AddChildren([Shape418]);
{ .AddChildren }
Transform416.AddChildren([Anchor417]);
Transform422 := TTransformNode.Create;
Transform422.Translation := Vector3(0,0.3,0.5);
Anchor423 := TAnchorNode.Create;
Anchor423.Description := 'ArtDeco25 view source documentation';
Anchor423.SetParameter(['target=_source']);
Anchor423.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco25','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco25']);
Shape424 := TShapeNode.Create;
Appearance425 := TAppearanceNode.Create;
Material426 := TMaterialNode.Create;
Material426 := Material76;
{ .SetMaterial }
Appearance425.Material := Material426;
{ .SetAppearance }
Shape424.Appearance := Appearance425;
Text427 := TTextNode.Create;
Text427.SetText(['ArtDeco25']);
FontStyle428 := TFontStyleNode.Create;
FontStyle428 := FontStyle78;
{ .SetFontStyle }
Text427.FontStyle := FontStyle428;
{ .SetGeometry }
Shape424.Geometry := Text427;
{ .AddChildren }
Anchor423.AddChildren([Shape424]);
{ .AddChildren }
Transform422.AddChildren([Anchor423]);
{ .AddChildren }
Transform416.AddChildren([Transform422]);
{ .AddChildren }
Group50.AddChildren([Transform416]);
Viewpoint429 := TViewpointNode.Create;
Viewpoint429.Description := 'ArtDeco26';
Viewpoint429.Position := Vector3(-0.75,-2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint429]);
Transform430 := TTransformNode.Create;
Transform430.Translation := Vector3(-0.75,-2.25,0);
Anchor431 := TAnchorNode.Create;
Anchor431.Description := 'ArtDeco26 view';
Anchor431.SetUrl(['#View26']);
Shape432 := TShapeNode.Create;
Appearance433 := TAppearanceNode.Create;
ProtoInstance434 := TProtoInstanceNode.Create;
ProtoInstance434.NameField := 'ArtDeco26';
{ .SetMaterial }
Appearance433.Material := ProtoInstance434;
{ .SetAppearance }
Shape432.Appearance := Appearance433;
Sphere435 := TSphereNode.Create;
Sphere435 := Sphere71;
{ .SetGeometry }
Shape432.Geometry := Sphere435;
{ .AddChildren }
Anchor431.AddChildren([Shape432]);
{ .AddChildren }
Transform430.AddChildren([Anchor431]);
Transform436 := TTransformNode.Create;
Transform436.Translation := Vector3(0,0.3,0.5);
Anchor437 := TAnchorNode.Create;
Anchor437.Description := 'ArtDeco26 view source documentation';
Anchor437.SetParameter(['target=_source']);
Anchor437.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco26','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco26']);
Shape438 := TShapeNode.Create;
Appearance439 := TAppearanceNode.Create;
Material440 := TMaterialNode.Create;
Material440 := Material76;
{ .SetMaterial }
Appearance439.Material := Material440;
{ .SetAppearance }
Shape438.Appearance := Appearance439;
Text441 := TTextNode.Create;
Text441.SetText(['ArtDeco26']);
FontStyle442 := TFontStyleNode.Create;
FontStyle442 := FontStyle78;
{ .SetFontStyle }
Text441.FontStyle := FontStyle442;
{ .SetGeometry }
Shape438.Geometry := Text441;
{ .AddChildren }
Anchor437.AddChildren([Shape438]);
{ .AddChildren }
Transform436.AddChildren([Anchor437]);
{ .AddChildren }
Transform430.AddChildren([Transform436]);
{ .AddChildren }
Group50.AddChildren([Transform430]);
Viewpoint443 := TViewpointNode.Create;
Viewpoint443.Description := 'ArtDeco27';
Viewpoint443.Position := Vector3(0.75,-2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint443]);
Transform444 := TTransformNode.Create;
Transform444.Translation := Vector3(0.75,-2.25,0);
Anchor445 := TAnchorNode.Create;
Anchor445.Description := 'ArtDeco27 view';
Anchor445.SetUrl(['#View27']);
Shape446 := TShapeNode.Create;
Appearance447 := TAppearanceNode.Create;
ProtoInstance448 := TProtoInstanceNode.Create;
ProtoInstance448.NameField := 'ArtDeco27';
{ .SetMaterial }
Appearance447.Material := ProtoInstance448;
{ .SetAppearance }
Shape446.Appearance := Appearance447;
Sphere449 := TSphereNode.Create;
Sphere449 := Sphere71;
{ .SetGeometry }
Shape446.Geometry := Sphere449;
{ .AddChildren }
Anchor445.AddChildren([Shape446]);
{ .AddChildren }
Transform444.AddChildren([Anchor445]);
Transform450 := TTransformNode.Create;
Transform450.Translation := Vector3(0,0.3,0.5);
Anchor451 := TAnchorNode.Create;
Anchor451.Description := 'ArtDeco27 view source documentation';
Anchor451.SetParameter(['target=_source']);
Anchor451.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco27','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco27']);
Shape452 := TShapeNode.Create;
Appearance453 := TAppearanceNode.Create;
Material454 := TMaterialNode.Create;
Material454 := Material76;
{ .SetMaterial }
Appearance453.Material := Material454;
{ .SetAppearance }
Shape452.Appearance := Appearance453;
Text455 := TTextNode.Create;
Text455.SetText(['ArtDeco27']);
FontStyle456 := TFontStyleNode.Create;
FontStyle456 := FontStyle78;
{ .SetFontStyle }
Text455.FontStyle := FontStyle456;
{ .SetGeometry }
Shape452.Geometry := Text455;
{ .AddChildren }
Anchor451.AddChildren([Shape452]);
{ .AddChildren }
Transform450.AddChildren([Anchor451]);
{ .AddChildren }
Transform444.AddChildren([Transform450]);
{ .AddChildren }
Group50.AddChildren([Transform444]);
Viewpoint457 := TViewpointNode.Create;
Viewpoint457.Description := 'ArtDeco28';
Viewpoint457.Position := Vector3(2.25,-2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint457]);
Transform458 := TTransformNode.Create;
Transform458.Translation := Vector3(2.25,-2.25,0);
Anchor459 := TAnchorNode.Create;
Anchor459.Description := 'ArtDeco28 view';
Anchor459.SetUrl(['#View28']);
Shape460 := TShapeNode.Create;
Appearance461 := TAppearanceNode.Create;
ProtoInstance462 := TProtoInstanceNode.Create;
ProtoInstance462.NameField := 'ArtDeco28';
{ .SetMaterial }
Appearance461.Material := ProtoInstance462;
{ .SetAppearance }
Shape460.Appearance := Appearance461;
Sphere463 := TSphereNode.Create;
Sphere463 := Sphere71;
{ .SetGeometry }
Shape460.Geometry := Sphere463;
{ .AddChildren }
Anchor459.AddChildren([Shape460]);
{ .AddChildren }
Transform458.AddChildren([Anchor459]);
Transform464 := TTransformNode.Create;
Transform464.Translation := Vector3(0,0.3,0.5);
Anchor465 := TAnchorNode.Create;
Anchor465.Description := 'ArtDeco28 view source documentation';
Anchor465.SetParameter(['target=_source']);
Anchor465.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco28','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco28']);
Shape466 := TShapeNode.Create;
Appearance467 := TAppearanceNode.Create;
Material468 := TMaterialNode.Create;
Material468 := Material76;
{ .SetMaterial }
Appearance467.Material := Material468;
{ .SetAppearance }
Shape466.Appearance := Appearance467;
Text469 := TTextNode.Create;
Text469.SetText(['ArtDeco28']);
FontStyle470 := TFontStyleNode.Create;
FontStyle470 := FontStyle78;
{ .SetFontStyle }
Text469.FontStyle := FontStyle470;
{ .SetGeometry }
Shape466.Geometry := Text469;
{ .AddChildren }
Anchor465.AddChildren([Shape466]);
{ .AddChildren }
Transform464.AddChildren([Anchor465]);
{ .AddChildren }
Transform458.AddChildren([Transform464]);
{ .AddChildren }
Group50.AddChildren([Transform458]);
Viewpoint471 := TViewpointNode.Create;
Viewpoint471.Description := 'ArtDeco29';
Viewpoint471.Position := Vector3(3.75,-2.25,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint471]);
Transform472 := TTransformNode.Create;
Transform472.Translation := Vector3(3.75,-2.25,0);
Anchor473 := TAnchorNode.Create;
Anchor473.Description := 'ArtDeco29 view';
Anchor473.SetUrl(['#View29']);
Shape474 := TShapeNode.Create;
Appearance475 := TAppearanceNode.Create;
ProtoInstance476 := TProtoInstanceNode.Create;
ProtoInstance476.NameField := 'ArtDeco29';
{ .SetMaterial }
Appearance475.Material := ProtoInstance476;
{ .SetAppearance }
Shape474.Appearance := Appearance475;
Sphere477 := TSphereNode.Create;
Sphere477 := Sphere71;
{ .SetGeometry }
Shape474.Geometry := Sphere477;
{ .AddChildren }
Anchor473.AddChildren([Shape474]);
{ .AddChildren }
Transform472.AddChildren([Anchor473]);
Transform478 := TTransformNode.Create;
Transform478.Translation := Vector3(0,0.3,0.5);
Anchor479 := TAnchorNode.Create;
Anchor479.Description := 'ArtDeco29 view source documentation';
Anchor479.SetParameter(['target=_source']);
Anchor479.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco29','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco29']);
Shape480 := TShapeNode.Create;
Appearance481 := TAppearanceNode.Create;
Material482 := TMaterialNode.Create;
Material482 := Material76;
{ .SetMaterial }
Appearance481.Material := Material482;
{ .SetAppearance }
Shape480.Appearance := Appearance481;
Text483 := TTextNode.Create;
Text483.SetText(['ArtDeco29']);
FontStyle484 := TFontStyleNode.Create;
FontStyle484 := FontStyle78;
{ .SetFontStyle }
Text483.FontStyle := FontStyle484;
{ .SetGeometry }
Shape480.Geometry := Text483;
{ .AddChildren }
Anchor479.AddChildren([Shape480]);
{ .AddChildren }
Transform478.AddChildren([Anchor479]);
{ .AddChildren }
Transform472.AddChildren([Transform478]);
{ .AddChildren }
Group50.AddChildren([Transform472]);
Viewpoint485 := TViewpointNode.Create;
Viewpoint485.Description := 'ArtDeco30';
Viewpoint485.Position := Vector3(-3.75,-3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint485]);
Transform486 := TTransformNode.Create;
Transform486.Translation := Vector3(-3.75,-3.75,0);
Anchor487 := TAnchorNode.Create;
Anchor487.Description := 'ArtDeco30 view';
Anchor487.SetUrl(['#View30']);
Shape488 := TShapeNode.Create;
Appearance489 := TAppearanceNode.Create;
ProtoInstance490 := TProtoInstanceNode.Create;
ProtoInstance490.NameField := 'ArtDeco30';
{ .SetMaterial }
Appearance489.Material := ProtoInstance490;
{ .SetAppearance }
Shape488.Appearance := Appearance489;
Sphere491 := TSphereNode.Create;
Sphere491 := Sphere71;
{ .SetGeometry }
Shape488.Geometry := Sphere491;
{ .AddChildren }
Anchor487.AddChildren([Shape488]);
{ .AddChildren }
Transform486.AddChildren([Anchor487]);
Transform492 := TTransformNode.Create;
Transform492.Translation := Vector3(0,0.3,0.5);
Anchor493 := TAnchorNode.Create;
Anchor493.Description := 'ArtDeco30 view source documentation';
Anchor493.SetParameter(['target=_source']);
Anchor493.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco30','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco30']);
Shape494 := TShapeNode.Create;
Appearance495 := TAppearanceNode.Create;
Material496 := TMaterialNode.Create;
Material496 := Material76;
{ .SetMaterial }
Appearance495.Material := Material496;
{ .SetAppearance }
Shape494.Appearance := Appearance495;
Text497 := TTextNode.Create;
Text497.SetText(['ArtDeco30']);
FontStyle498 := TFontStyleNode.Create;
FontStyle498 := FontStyle78;
{ .SetFontStyle }
Text497.FontStyle := FontStyle498;
{ .SetGeometry }
Shape494.Geometry := Text497;
{ .AddChildren }
Anchor493.AddChildren([Shape494]);
{ .AddChildren }
Transform492.AddChildren([Anchor493]);
{ .AddChildren }
Transform486.AddChildren([Transform492]);
{ .AddChildren }
Group50.AddChildren([Transform486]);
Viewpoint499 := TViewpointNode.Create;
Viewpoint499.Description := 'ArtDeco31';
Viewpoint499.Position := Vector3(-2.25,-3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint499]);
Transform500 := TTransformNode.Create;
Transform500.Translation := Vector3(-2.25,-3.75,0);
Anchor501 := TAnchorNode.Create;
Anchor501.Description := 'ArtDeco31 view';
Anchor501.SetUrl(['#View31']);
Shape502 := TShapeNode.Create;
Appearance503 := TAppearanceNode.Create;
ProtoInstance504 := TProtoInstanceNode.Create;
ProtoInstance504.NameField := 'ArtDeco31';
{ .SetMaterial }
Appearance503.Material := ProtoInstance504;
{ .SetAppearance }
Shape502.Appearance := Appearance503;
Sphere505 := TSphereNode.Create;
Sphere505 := Sphere71;
{ .SetGeometry }
Shape502.Geometry := Sphere505;
{ .AddChildren }
Anchor501.AddChildren([Shape502]);
{ .AddChildren }
Transform500.AddChildren([Anchor501]);
Transform506 := TTransformNode.Create;
Transform506.Translation := Vector3(0,0.3,0.5);
Anchor507 := TAnchorNode.Create;
Anchor507.Description := 'ArtDeco31 view source documentation';
Anchor507.SetParameter(['target=_source']);
Anchor507.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco31','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco31']);
Shape508 := TShapeNode.Create;
Appearance509 := TAppearanceNode.Create;
Material510 := TMaterialNode.Create;
Material510 := Material76;
{ .SetMaterial }
Appearance509.Material := Material510;
{ .SetAppearance }
Shape508.Appearance := Appearance509;
Text511 := TTextNode.Create;
Text511.SetText(['ArtDeco31']);
FontStyle512 := TFontStyleNode.Create;
FontStyle512 := FontStyle78;
{ .SetFontStyle }
Text511.FontStyle := FontStyle512;
{ .SetGeometry }
Shape508.Geometry := Text511;
{ .AddChildren }
Anchor507.AddChildren([Shape508]);
{ .AddChildren }
Transform506.AddChildren([Anchor507]);
{ .AddChildren }
Transform500.AddChildren([Transform506]);
{ .AddChildren }
Group50.AddChildren([Transform500]);
Viewpoint513 := TViewpointNode.Create;
Viewpoint513.Description := 'ArtDeco32';
Viewpoint513.Position := Vector3(-0.75,-3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint513]);
Transform514 := TTransformNode.Create;
Transform514.Translation := Vector3(-0.75,-3.75,0);
Anchor515 := TAnchorNode.Create;
Anchor515.Description := 'ArtDeco32 view';
Anchor515.SetUrl(['#View32']);
Shape516 := TShapeNode.Create;
Appearance517 := TAppearanceNode.Create;
ProtoInstance518 := TProtoInstanceNode.Create;
ProtoInstance518.NameField := 'ArtDeco32';
{ .SetMaterial }
Appearance517.Material := ProtoInstance518;
{ .SetAppearance }
Shape516.Appearance := Appearance517;
Sphere519 := TSphereNode.Create;
Sphere519 := Sphere71;
{ .SetGeometry }
Shape516.Geometry := Sphere519;
{ .AddChildren }
Anchor515.AddChildren([Shape516]);
{ .AddChildren }
Transform514.AddChildren([Anchor515]);
Transform520 := TTransformNode.Create;
Transform520.Translation := Vector3(0,0.3,0.5);
Anchor521 := TAnchorNode.Create;
Anchor521.Description := 'ArtDeco32 view source documentation';
Anchor521.SetParameter(['target=_source']);
Anchor521.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco32','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco32']);
Shape522 := TShapeNode.Create;
Appearance523 := TAppearanceNode.Create;
Material524 := TMaterialNode.Create;
Material524 := Material76;
{ .SetMaterial }
Appearance523.Material := Material524;
{ .SetAppearance }
Shape522.Appearance := Appearance523;
Text525 := TTextNode.Create;
Text525.SetText(['ArtDeco32']);
FontStyle526 := TFontStyleNode.Create;
FontStyle526 := FontStyle78;
{ .SetFontStyle }
Text525.FontStyle := FontStyle526;
{ .SetGeometry }
Shape522.Geometry := Text525;
{ .AddChildren }
Anchor521.AddChildren([Shape522]);
{ .AddChildren }
Transform520.AddChildren([Anchor521]);
{ .AddChildren }
Transform514.AddChildren([Transform520]);
{ .AddChildren }
Group50.AddChildren([Transform514]);
Viewpoint527 := TViewpointNode.Create;
Viewpoint527.Description := 'ArtDeco33';
Viewpoint527.Position := Vector3(0.75,-3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint527]);
Transform528 := TTransformNode.Create;
Transform528.Translation := Vector3(0.75,-3.75,0);
Anchor529 := TAnchorNode.Create;
Anchor529.Description := 'ArtDeco33 view';
Anchor529.SetUrl(['#View33']);
Shape530 := TShapeNode.Create;
Appearance531 := TAppearanceNode.Create;
ProtoInstance532 := TProtoInstanceNode.Create;
ProtoInstance532.NameField := 'ArtDeco33';
{ .SetMaterial }
Appearance531.Material := ProtoInstance532;
{ .SetAppearance }
Shape530.Appearance := Appearance531;
Sphere533 := TSphereNode.Create;
Sphere533 := Sphere71;
{ .SetGeometry }
Shape530.Geometry := Sphere533;
{ .AddChildren }
Anchor529.AddChildren([Shape530]);
{ .AddChildren }
Transform528.AddChildren([Anchor529]);
Transform534 := TTransformNode.Create;
Transform534.Translation := Vector3(0,0.3,0.5);
Anchor535 := TAnchorNode.Create;
Anchor535.Description := 'ArtDeco33 view source documentation';
Anchor535.SetParameter(['target=_source']);
Anchor535.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco33','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco33']);
Shape536 := TShapeNode.Create;
Appearance537 := TAppearanceNode.Create;
Material538 := TMaterialNode.Create;
Material538 := Material76;
{ .SetMaterial }
Appearance537.Material := Material538;
{ .SetAppearance }
Shape536.Appearance := Appearance537;
Text539 := TTextNode.Create;
Text539.SetText(['ArtDeco33']);
FontStyle540 := TFontStyleNode.Create;
FontStyle540 := FontStyle78;
{ .SetFontStyle }
Text539.FontStyle := FontStyle540;
{ .SetGeometry }
Shape536.Geometry := Text539;
{ .AddChildren }
Anchor535.AddChildren([Shape536]);
{ .AddChildren }
Transform534.AddChildren([Anchor535]);
{ .AddChildren }
Transform528.AddChildren([Transform534]);
{ .AddChildren }
Group50.AddChildren([Transform528]);
Viewpoint541 := TViewpointNode.Create;
Viewpoint541.Description := 'ArtDeco34';
Viewpoint541.Position := Vector3(2.25,-3.75,3);
{ .AddChildren }
Group50.AddChildren([Viewpoint541]);
Transform542 := TTransformNode.Create;
Transform542.Translation := Vector3(2.25,-3.75,0);
Anchor543 := TAnchorNode.Create;
Anchor543.Description := 'ArtDeco34 view';
Anchor543.SetUrl(['#View34']);
Shape544 := TShapeNode.Create;
Appearance545 := TAppearanceNode.Create;
ProtoInstance546 := TProtoInstanceNode.Create;
ProtoInstance546.NameField := 'ArtDeco34';
{ .SetMaterial }
Appearance545.Material := ProtoInstance546;
{ .SetAppearance }
Shape544.Appearance := Appearance545;
Sphere547 := TSphereNode.Create;
Sphere547 := Sphere71;
{ .SetGeometry }
Shape544.Geometry := Sphere547;
{ .AddChildren }
Anchor543.AddChildren([Shape544]);
{ .AddChildren }
Transform542.AddChildren([Anchor543]);
Transform548 := TTransformNode.Create;
Transform548.Translation := Vector3(0,0.3,0.5);
Anchor549 := TAnchorNode.Create;
Anchor549.Description := 'ArtDeco34 view source documentation';
Anchor549.SetParameter(['target=_source']);
Anchor549.SetUrl(['ArtDecoPrototypes.html#ProtoDeclare_ArtDeco34','https://www.web3d.org/x3d/content/examples/Basic/UniversalMediaMaterials/ArtDecoPrototypes.html#ProtoDeclare_ArtDeco34']);
Shape550 := TShapeNode.Create;
Appearance551 := TAppearanceNode.Create;
Material552 := TMaterialNode.Create;
Material552 := Material76;
{ .SetMaterial }
Appearance551.Material := Material552;
{ .SetAppearance }
Shape550.Appearance := Appearance551;
Text553 := TTextNode.Create;
Text553.SetText(['ArtDeco34']);
FontStyle554 := TFontStyleNode.Create;
FontStyle554 := FontStyle78;
{ .SetFontStyle }
Text553.FontStyle := FontStyle554;
{ .SetGeometry }
Shape550.Geometry := Text553;
{ .AddChildren }
Anchor549.AddChildren([Shape550]);
{ .AddChildren }
Transform548.AddChildren([Anchor549]);
{ .AddChildren }
Transform542.AddChildren([Transform548]);
{ .AddChildren }
Group50.AddChildren([Transform542]);
{ .AddChildren }
Group13.AddChildren([Group50]);
Group13.AddRoute(TimeSensor58.EventFraction_changed, PositionInterpolator57.EventSet_fraction);
{ .AddX3DRoute }
Group13.AddRoute(PositionInterpolator57.EventValue_changed, Transform56.FdTranslation);
{ .AddX3DRoute }
{ .AddGroup }
X3D0.AddChildren([Group13]);
Result := X3D0;
end;
