function HAnimModelHandRight: TX3DRootNode;
var
X3D0: TX3DRootNode;
Group24: TGroupNode;
WorldInfo25: TWorldInfoNode;
HAnimHumanoid26: THAnimHumanoidNode;
MetadataSet27: TMetadataSetNode;
MetadataString28: TMetadataStringNode;
HAnimJoint29: THAnimJointNode;
HAnimJoint30: THAnimJointNode;
HAnimSegment31: THAnimSegmentNode;
Transform32: TTransformNode;
Shape33: TShapeNode;
Sphere34: TSphereNode;
Appearance35: TAppearanceNode;
Material36: TMaterialNode;
Shape37: TShapeNode;
Appearance38: TAppearanceNode;
Material39: TMaterialNode;
IndexedLineSet40: TIndexedLineSetNode;
Coordinate41: TCoordinateNode;
Shape42: TShapeNode;
Appearance43: TAppearanceNode;
Material44: TMaterialNode;
IndexedLineSet45: TIndexedLineSetNode;
Coordinate46: TCoordinateNode;
Shape47: TShapeNode;
Appearance48: TAppearanceNode;
Material49: TMaterialNode;
IndexedLineSet50: TIndexedLineSetNode;
Coordinate51: TCoordinateNode;
HAnimJoint52: THAnimJointNode;
HAnimSegment53: THAnimSegmentNode;
Transform54: TTransformNode;
Shape55: TShapeNode;
Sphere56: TSphereNode;
Appearance57: TAppearanceNode;
Material58: TMaterialNode;
Shape59: TShapeNode;
Appearance60: TAppearanceNode;
Material61: TMaterialNode;
IndexedLineSet62: TIndexedLineSetNode;
Coordinate63: TCoordinateNode;
HAnimJoint64: THAnimJointNode;
HAnimSegment65: THAnimSegmentNode;
Transform66: TTransformNode;
Shape67: TShapeNode;
Shape68: TShapeNode;
Appearance69: TAppearanceNode;
Material70: TMaterialNode;
IndexedLineSet71: TIndexedLineSetNode;
Coordinate72: TCoordinateNode;
HAnimJoint73: THAnimJointNode;
HAnimSegment74: THAnimSegmentNode;
Transform75: TTransformNode;
Shape76: TShapeNode;
Shape77: TShapeNode;
Appearance78: TAppearanceNode;
Material79: TMaterialNode;
IndexedLineSet80: TIndexedLineSetNode;
Coordinate81: TCoordinateNode;
HAnimJoint82: THAnimJointNode;
HAnimSegment83: THAnimSegmentNode;
Transform84: TTransformNode;
Shape85: TShapeNode;
Shape86: TShapeNode;
Appearance87: TAppearanceNode;
Material88: TMaterialNode;
IndexedLineSet89: TIndexedLineSetNode;
Coordinate90: TCoordinateNode;
HAnimJoint91: THAnimJointNode;
HAnimSegment92: THAnimSegmentNode;
Transform93: TTransformNode;
Shape94: TShapeNode;
Shape95: TShapeNode;
Appearance96: TAppearanceNode;
Material97: TMaterialNode;
IndexedLineSet98: TIndexedLineSetNode;
Coordinate99: TCoordinateNode;
HAnimJoint100: THAnimJointNode;
HAnimSegment101: THAnimSegmentNode;
Transform102: TTransformNode;
Shape103: TShapeNode;
Shape104: TShapeNode;
Appearance105: TAppearanceNode;
Material106: TMaterialNode;
IndexedLineSet107: TIndexedLineSetNode;
Coordinate108: TCoordinateNode;
HAnimJoint109: THAnimJointNode;
HAnimSegment110: THAnimSegmentNode;
Transform111: TTransformNode;
Shape112: TShapeNode;
Shape113: TShapeNode;
Appearance114: TAppearanceNode;
Material115: TMaterialNode;
IndexedLineSet116: TIndexedLineSetNode;
Coordinate117: TCoordinateNode;
HAnimJoint118: THAnimJointNode;
HAnimSegment119: THAnimSegmentNode;
Transform120: TTransformNode;
Shape121: TShapeNode;
Shape122: TShapeNode;
Appearance123: TAppearanceNode;
Material124: TMaterialNode;
IndexedLineSet125: TIndexedLineSetNode;
Coordinate126: TCoordinateNode;
HAnimJoint127: THAnimJointNode;
HAnimSegment128: THAnimSegmentNode;
Transform129: TTransformNode;
Shape130: TShapeNode;
Shape131: TShapeNode;
Appearance132: TAppearanceNode;
Material133: TMaterialNode;
IndexedLineSet134: TIndexedLineSetNode;
Coordinate135: TCoordinateNode;
HAnimJoint136: THAnimJointNode;
HAnimSegment137: THAnimSegmentNode;
Transform138: TTransformNode;
Shape139: TShapeNode;
Shape140: TShapeNode;
Appearance141: TAppearanceNode;
Material142: TMaterialNode;
IndexedLineSet143: TIndexedLineSetNode;
Coordinate144: TCoordinateNode;
HAnimJoint145: THAnimJointNode;
HAnimSegment146: THAnimSegmentNode;
Transform147: TTransformNode;
Shape148: TShapeNode;
Shape149: TShapeNode;
Appearance150: TAppearanceNode;
Material151: TMaterialNode;
IndexedLineSet152: TIndexedLineSetNode;
Coordinate153: TCoordinateNode;
HAnimJoint154: THAnimJointNode;
HAnimSegment155: THAnimSegmentNode;
Transform156: TTransformNode;
Shape157: TShapeNode;
Shape158: TShapeNode;
Appearance159: TAppearanceNode;
Material160: TMaterialNode;
IndexedLineSet161: TIndexedLineSetNode;
Coordinate162: TCoordinateNode;
HAnimJoint163: THAnimJointNode;
HAnimSegment164: THAnimSegmentNode;
Transform165: TTransformNode;
Shape166: TShapeNode;
Shape167: TShapeNode;
Appearance168: TAppearanceNode;
Material169: TMaterialNode;
IndexedLineSet170: TIndexedLineSetNode;
Coordinate171: TCoordinateNode;
HAnimJoint172: THAnimJointNode;
HAnimSegment173: THAnimSegmentNode;
Transform174: TTransformNode;
Shape175: TShapeNode;
Shape176: TShapeNode;
Appearance177: TAppearanceNode;
Material178: TMaterialNode;
IndexedLineSet179: TIndexedLineSetNode;
Coordinate180: TCoordinateNode;
HAnimJoint181: THAnimJointNode;
HAnimSegment182: THAnimSegmentNode;
Transform183: TTransformNode;
Shape184: TShapeNode;
Shape185: TShapeNode;
Appearance186: TAppearanceNode;
Material187: TMaterialNode;
IndexedLineSet188: TIndexedLineSetNode;
Coordinate189: TCoordinateNode;
Shape190: TShapeNode;
Appearance191: TAppearanceNode;
Material192: TMaterialNode;
IndexedLineSet193: TIndexedLineSetNode;
Coordinate194: TCoordinateNode;
HAnimJoint195: THAnimJointNode;
HAnimSegment196: THAnimSegmentNode;
Transform197: TTransformNode;
Shape198: TShapeNode;
Shape199: TShapeNode;
Appearance200: TAppearanceNode;
Material201: TMaterialNode;
IndexedLineSet202: TIndexedLineSetNode;
Coordinate203: TCoordinateNode;
HAnimJoint204: THAnimJointNode;
HAnimSegment205: THAnimSegmentNode;
Transform206: TTransformNode;
Shape207: TShapeNode;
Shape208: TShapeNode;
Appearance209: TAppearanceNode;
Material210: TMaterialNode;
IndexedLineSet211: TIndexedLineSetNode;
Coordinate212: TCoordinateNode;
HAnimJoint213: THAnimJointNode;
HAnimSegment214: THAnimSegmentNode;
Transform215: TTransformNode;
Shape216: TShapeNode;
Shape217: TShapeNode;
Appearance218: TAppearanceNode;
Material219: TMaterialNode;
IndexedLineSet220: TIndexedLineSetNode;
Coordinate221: TCoordinateNode;
HAnimJoint222: THAnimJointNode;
HAnimSegment223: THAnimSegmentNode;
Transform224: TTransformNode;
Shape225: TShapeNode;
Shape226: TShapeNode;
Appearance227: TAppearanceNode;
Material228: TMaterialNode;
IndexedLineSet229: TIndexedLineSetNode;
Coordinate230: TCoordinateNode;
HAnimJoint231: THAnimJointNode;
HAnimSegment232: THAnimSegmentNode;
Transform233: TTransformNode;
Shape234: TShapeNode;
Shape235: TShapeNode;
Appearance236: TAppearanceNode;
Material237: TMaterialNode;
IndexedLineSet238: TIndexedLineSetNode;
Coordinate239: TCoordinateNode;
HAnimJoint240: THAnimJointNode;
HAnimSegment241: THAnimSegmentNode;
Transform242: TTransformNode;
Shape243: TShapeNode;
Shape244: TShapeNode;
Appearance245: TAppearanceNode;
Material246: TMaterialNode;
IndexedLineSet247: TIndexedLineSetNode;
Coordinate248: TCoordinateNode;
HAnimJoint249: THAnimJointNode;
HAnimSegment250: THAnimSegmentNode;
Transform251: TTransformNode;
Shape252: TShapeNode;
Shape253: TShapeNode;
Appearance254: TAppearanceNode;
Material255: TMaterialNode;
IndexedLineSet256: TIndexedLineSetNode;
Coordinate257: TCoordinateNode;
HAnimJoint258: THAnimJointNode;
HAnimSegment259: THAnimSegmentNode;
Transform260: TTransformNode;
Shape261: TShapeNode;
Shape262: TShapeNode;
Appearance263: TAppearanceNode;
Material264: TMaterialNode;
IndexedLineSet265: TIndexedLineSetNode;
Coordinate266: TCoordinateNode;
HAnimJoint267: THAnimJointNode;
HAnimJoint268: THAnimJointNode;
HAnimJoint269: THAnimJointNode;
HAnimJoint270: THAnimJointNode;
HAnimJoint271: THAnimJointNode;
HAnimJoint272: THAnimJointNode;
HAnimJoint273: THAnimJointNode;
HAnimJoint274: THAnimJointNode;
HAnimJoint275: THAnimJointNode;
HAnimJoint276: THAnimJointNode;
HAnimJoint277: THAnimJointNode;
HAnimJoint278: THAnimJointNode;
HAnimJoint279: THAnimJointNode;
HAnimJoint280: THAnimJointNode;
HAnimJoint281: THAnimJointNode;
HAnimJoint282: THAnimJointNode;
HAnimJoint283: THAnimJointNode;
HAnimJoint284: THAnimJointNode;
HAnimJoint285: THAnimJointNode;
HAnimJoint286: THAnimJointNode;
HAnimJoint287: THAnimJointNode;
HAnimJoint288: THAnimJointNode;
HAnimJoint289: THAnimJointNode;
HAnimJoint290: THAnimJointNode;
HAnimJoint291: THAnimJointNode;
begin
X3D0 := TX3DRootNode.Create;
X3D0.Profile := 'Immersive';
X3D0.ForceVersion.Major := 4;
X3D0.ForceVersion.Minor := 0;
X3D0.Components['HAnim'] := 1;
X3D0.Meta['title'] := 'HAnimModelHandRight.x3d';
X3D0.Meta['description'] := 'Right hand using high-fidelity definitions for HAnim version 2.0';
X3D0.Meta['creator'] := 'Kwan-Hee YOO, Don Brutzman and Joe Williams';
X3D0.Meta['created'] := '26 January 2015';
X3D0.Meta['modified'] := '23 December 2021';
X3D0.Meta['TODO'] := 'fix visible geometry for thumb and index finger, midcarpal_1 and midcarpal_2';
X3D0.Meta['Image'] := 'HAnimModelHandRightSegmentVisualizationError.png';
X3D0.Meta['error'] := 'not yet to scale, also relatively flat';
X3D0.Meta['warning'] := 'TODO will X3D HAnim component add a new level to support LOA-4 functionality?';
X3D0.Meta['info'] := 'TODO describe how to compute and apply offsets for center values whenever attaching this appendage to a body';
X3D0.Meta['reference'] := 'https://www.web3d.org/working-groups/humanoid-animation-HAnim';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#TheHands';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#f-HandJoints';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#Hierarchy4';
X3D0.Meta['reference'] := 'https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-WD2/Part01/components/hanim.html';
X3D0.Meta['subject'] := 'X3D HAnim humanoid animation';
X3D0.Meta['TODO'] := 'Integrate and confirm Segment/Joint names, Viewpoints.';
X3D0.Meta['identifier'] := 'https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Characters/HAnimModelHandRight.x3d';
X3D0.Meta['generator'] := 'X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit';
X3D0.Meta['license'] := '../license.html';
Group24 := TGroupNode.Create;
WorldInfo25 := TWorldInfoNode.Create;
WorldInfo25.Title := 'HAnimModelHandRight.x3d';
{ .AddChildren }
Group24.AddChildren([WorldInfo25]);
HAnimHumanoid26 := THAnimHumanoidNode.Create;
HAnimHumanoid26.NameField := 'Hand_Right';
HAnimHumanoid26.Loa := 4;
HAnimHumanoid26.Version := '2.0';
{ original HAnimHumanoid info='"authorName=Kwan-Hee YOO, Don Brutzman and Joe Williams"' }
MetadataSet27 := TMetadataSetNode.Create;
MetadataSet27.NameField := 'HAnimHumanoid.info';
MetadataSet27.Reference := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/ObjectInterfaces.html#Humanoid';
MetadataString28 := TMetadataStringNode.Create;
MetadataString28.NameField := 'authorName';
MetadataString28.SetValue(['Kwan-Hee YOO, Don Brutzman and Joe Williams']);
{ .SetValue }
MetadataSet27.Value := MetadataString28;
{ .SetMetadata }
HAnimHumanoid26.Metadata := MetadataSet27;
HAnimJoint29 := THAnimJointNode.Create;
HAnimJoint29.NameField := 'humanoid_root';
HAnimJoint29.SetUlimit([0,0,0]);
HAnimJoint29.SetLlimit([0,0,0]);
{ Might consider putting a HAnimSegment here, but that doesn't help with re-use of this hand model }
HAnimJoint30 := THAnimJointNode.Create;
HAnimJoint30.NameField := 'r_radiocarpal';
HAnimJoint30.Description := 'connection joint of hand to leg above';
HAnimJoint30.SetUlimit([0,0,0]);
HAnimJoint30.SetLlimit([0,0,0]);
HAnimSegment31 := THAnimSegmentNode.Create;
HAnimSegment31.NameField := 'r_carpal';
Transform32 := TTransformNode.Create;
Shape33 := TShapeNode.Create;
Sphere34 := TSphereNode.Create;
Sphere34.Radius := 0.025;
{ .SetGeometry }
Shape33.Geometry := Sphere34;
Appearance35 := TAppearanceNode.Create;
Material36 := TMaterialNode.Create;
Material36.DiffuseColor := Vector3(0,0,1);
{ .SetMaterial }
Appearance35.Material := Material36;
{ .SetAppearance }
Shape33.Appearance := Appearance35;
{ .AddChild }
Transform32.AddChildren([Shape33]);
{ .AddChildren }
HAnimSegment31.AddChildren([Transform32]);
Shape37 := TShapeNode.Create;
Appearance38 := TAppearanceNode.Create;
Material39 := TMaterialNode.Create;
Material39.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance38.Material := Material39;
{ .SetAppearance }
Shape37.Appearance := Appearance38;
IndexedLineSet40 := TIndexedLineSetNode.Create;
IndexedLineSet40.SetCoordIndex([0,1]);
Coordinate41 := TCoordinateNode.Create;
Coordinate41.SetPoint([Vector3(0,0,0),Vector3(-0.1,0.1,0)]);
{ .SetCoord }
IndexedLineSet40.Coord := Coordinate41;
{ .SetGeometry }
Shape37.Geometry := IndexedLineSet40;
{ .AddChildren }
HAnimSegment31.AddChildren([Shape37]);
Shape42 := TShapeNode.Create;
Appearance43 := TAppearanceNode.Create;
Material44 := TMaterialNode.Create;
Material44.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance43.Material := Material44;
{ .SetAppearance }
Shape42.Appearance := Appearance43;
IndexedLineSet45 := TIndexedLineSetNode.Create;
IndexedLineSet45.SetCoordIndex([0,1]);
Coordinate46 := TCoordinateNode.Create;
Coordinate46.SetPoint([Vector3(0,0,0),Vector3(0,0.07,0)]);
{ .SetCoord }
IndexedLineSet45.Coord := Coordinate46;
{ .SetGeometry }
Shape42.Geometry := IndexedLineSet45;
{ .AddChildren }
HAnimSegment31.AddChildren([Shape42]);
Shape47 := TShapeNode.Create;
Appearance48 := TAppearanceNode.Create;
Material49 := TMaterialNode.Create;
Material49.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance48.Material := Material49;
{ .SetAppearance }
Shape47.Appearance := Appearance48;
IndexedLineSet50 := TIndexedLineSetNode.Create;
IndexedLineSet50.SetCoordIndex([0,1]);
Coordinate51 := TCoordinateNode.Create;
Coordinate51.SetPoint([Vector3(0,0,0),Vector3(0.1,0.1,0)]);
{ .SetCoord }
IndexedLineSet50.Coord := Coordinate51;
{ .SetGeometry }
Shape47.Geometry := IndexedLineSet50;
{ .AddChildren }
HAnimSegment31.AddChildren([Shape47]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimSegment31]);
{ MC1 }
HAnimJoint52 := THAnimJointNode.Create;
HAnimJoint52.NameField := 'r_midcarpal_1';
HAnimJoint52.Center := Vector3(-0.14,0.09,0);
HAnimJoint52.SetUlimit([0,0,0]);
HAnimJoint52.SetLlimit([0,0,0]);
HAnimSegment53 := THAnimSegmentNode.Create;
HAnimSegment53.NameField := 'r_trapezium';
Transform54 := TTransformNode.Create;
Transform54.Translation := Vector3(-0.14,0.09,0);
Shape55 := TShapeNode.Create;
Sphere56 := TSphereNode.Create;
Sphere56.Radius := 0.025;
{ .SetGeometry }
Shape55.Geometry := Sphere56;
Appearance57 := TAppearanceNode.Create;
Material58 := TMaterialNode.Create;
Material58.DiffuseColor := Vector3(1,0,0);
{ .SetMaterial }
Appearance57.Material := Material58;
{ .SetAppearance }
Shape55.Appearance := Appearance57;
{ .AddChild }
Transform54.AddChildren([Shape55]);
{ .AddChildren }
HAnimSegment53.AddChildren([Transform54]);
Shape59 := TShapeNode.Create;
Appearance60 := TAppearanceNode.Create;
Material61 := TMaterialNode.Create;
Material61.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance60.Material := Material61;
{ .SetAppearance }
Shape59.Appearance := Appearance60;
IndexedLineSet62 := TIndexedLineSetNode.Create;
IndexedLineSet62.SetCoordIndex([0,1]);
Coordinate63 := TCoordinateNode.Create;
Coordinate63.SetPoint([Vector3(-0.1,0.1,0),Vector3(-0.2,0.15,0)]);
{ .SetCoord }
IndexedLineSet62.Coord := Coordinate63;
{ .SetGeometry }
Shape59.Geometry := IndexedLineSet62;
{ .AddChildren }
HAnimSegment53.AddChildren([Shape59]);
{ .AddChildren }
HAnimJoint52.AddChildren([HAnimSegment53]);
{ thumb finger }
HAnimJoint64 := THAnimJointNode.Create;
HAnimJoint64.NameField := 'r_carpometacarpal_1';
HAnimJoint64.Center := Vector3(-0.2,0.15,0);
HAnimJoint64.SetUlimit([0,0,0]);
HAnimJoint64.SetLlimit([0,0,0]);
HAnimSegment65 := THAnimSegmentNode.Create;
HAnimSegment65.NameField := 'r_metacarpal_1';
Transform66 := TTransformNode.Create;
Transform66.Translation := Vector3(-0.2,0.15,0);
Shape67 := TShapeNode.Create;
Shape67 := Shape33;
{ .AddChild }
Transform66.AddChildren([Shape67]);
{ .AddChildren }
HAnimSegment65.AddChildren([Transform66]);
Shape68 := TShapeNode.Create;
Appearance69 := TAppearanceNode.Create;
Material70 := TMaterialNode.Create;
Material70.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance69.Material := Material70;
{ .SetAppearance }
Shape68.Appearance := Appearance69;
IndexedLineSet71 := TIndexedLineSetNode.Create;
IndexedLineSet71.SetCoordIndex([0,1]);
Coordinate72 := TCoordinateNode.Create;
Coordinate72.SetPoint([Vector3(-0.2,0.15,0),Vector3(-0.3,0.3,0)]);
{ .SetCoord }
IndexedLineSet71.Coord := Coordinate72;
{ .SetGeometry }
Shape68.Geometry := IndexedLineSet71;
{ .AddChildren }
HAnimSegment65.AddChildren([Shape68]);
{ .AddChildren }
HAnimJoint64.AddChildren([HAnimSegment65]);
HAnimJoint73 := THAnimJointNode.Create;
HAnimJoint73.NameField := 'r_metacarpophalangeal_1';
HAnimJoint73.Center := Vector3(-0.3,0.3,0);
HAnimJoint73.SetUlimit([0,0,0]);
HAnimJoint73.SetLlimit([0,0,0]);
HAnimSegment74 := THAnimSegmentNode.Create;
HAnimSegment74.NameField := 'r_carpal_proximal_phalanx_1';
Transform75 := TTransformNode.Create;
Transform75.Translation := Vector3(-0.3,0.3,0);
Shape76 := TShapeNode.Create;
Shape76 := Shape33;
{ .AddChild }
Transform75.AddChildren([Shape76]);
{ .AddChildren }
HAnimSegment74.AddChildren([Transform75]);
Shape77 := TShapeNode.Create;
Appearance78 := TAppearanceNode.Create;
Material79 := TMaterialNode.Create;
Material79.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance78.Material := Material79;
{ .SetAppearance }
Shape77.Appearance := Appearance78;
IndexedLineSet80 := TIndexedLineSetNode.Create;
IndexedLineSet80.SetCoordIndex([0,1]);
Coordinate81 := TCoordinateNode.Create;
Coordinate81.SetPoint([Vector3(-0.3,0.3,0),Vector3(-0.35,0.4,0)]);
{ .SetCoord }
IndexedLineSet80.Coord := Coordinate81;
{ .SetGeometry }
Shape77.Geometry := IndexedLineSet80;
{ .AddChildren }
HAnimSegment74.AddChildren([Shape77]);
{ .AddChildren }
HAnimJoint73.AddChildren([HAnimSegment74]);
HAnimJoint82 := THAnimJointNode.Create;
HAnimJoint82.NameField := 'r_carpal_interphalangeal_1';
HAnimJoint82.Center := Vector3(-0.35,0.4,0);
HAnimJoint82.SetUlimit([0,0,0]);
HAnimJoint82.SetLlimit([0,0,0]);
HAnimSegment83 := THAnimSegmentNode.Create;
HAnimSegment83.NameField := 'r_carpal_distal_phalanx_1';
Transform84 := TTransformNode.Create;
Transform84.Translation := Vector3(-0.35,0.4,0);
Shape85 := TShapeNode.Create;
Shape85 := Shape33;
{ .AddChild }
Transform84.AddChildren([Shape85]);
{ .AddChildren }
HAnimSegment83.AddChildren([Transform84]);
Shape86 := TShapeNode.Create;
Appearance87 := TAppearanceNode.Create;
Material88 := TMaterialNode.Create;
Material88.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance87.Material := Material88;
{ .SetAppearance }
Shape86.Appearance := Appearance87;
IndexedLineSet89 := TIndexedLineSetNode.Create;
IndexedLineSet89.SetCoordIndex([0,1]);
Coordinate90 := TCoordinateNode.Create;
Coordinate90.SetPoint([Vector3(-0.35,0.4,0),Vector3(-0.36,0.45,0)]);
{ .SetCoord }
IndexedLineSet89.Coord := Coordinate90;
{ .SetGeometry }
Shape86.Geometry := IndexedLineSet89;
{ .AddChildren }
HAnimSegment83.AddChildren([Shape86]);
{ .AddChildren }
HAnimJoint82.AddChildren([HAnimSegment83]);
{ .AddChildren }
HAnimJoint73.AddChildren([HAnimJoint82]);
{ .AddChildren }
HAnimJoint64.AddChildren([HAnimJoint73]);
{ .AddChildren }
HAnimJoint52.AddChildren([HAnimJoint64]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimJoint52]);
{ MC2 }
HAnimJoint91 := THAnimJointNode.Create;
HAnimJoint91.NameField := 'r_midcarpal_2';
HAnimJoint91.Center := Vector3(-0.07,0.07,0);
HAnimJoint91.SetUlimit([0,0,0]);
HAnimJoint91.SetLlimit([0,0,0]);
HAnimSegment92 := THAnimSegmentNode.Create;
HAnimSegment92.NameField := 'r_trapezoid';
Transform93 := TTransformNode.Create;
Transform93.Translation := Vector3(-0.07,0.07,0);
Shape94 := TShapeNode.Create;
Shape94 := Shape55;
{ .AddChild }
Transform93.AddChildren([Shape94]);
{ .AddChildren }
HAnimSegment92.AddChildren([Transform93]);
Shape95 := TShapeNode.Create;
Appearance96 := TAppearanceNode.Create;
Material97 := TMaterialNode.Create;
Material97.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance96.Material := Material97;
{ .SetAppearance }
Shape95.Appearance := Appearance96;
IndexedLineSet98 := TIndexedLineSetNode.Create;
IndexedLineSet98.SetCoordIndex([0,1]);
Coordinate99 := TCoordinateNode.Create;
Coordinate99.SetPoint([Vector3(-0.1,0.1,0),Vector3(-0.1,0.2,0)]);
{ .SetCoord }
IndexedLineSet98.Coord := Coordinate99;
{ .SetGeometry }
Shape95.Geometry := IndexedLineSet98;
{ .AddChildren }
HAnimSegment92.AddChildren([Shape95]);
{ .AddChildren }
HAnimJoint91.AddChildren([HAnimSegment92]);
{ index finger }
HAnimJoint100 := THAnimJointNode.Create;
HAnimJoint100.NameField := 'r_carpometacarpal_2';
HAnimJoint100.Center := Vector3(-0.1,0.2,0);
HAnimJoint100.SetUlimit([0,0,0]);
HAnimJoint100.SetLlimit([0,0,0]);
HAnimSegment101 := THAnimSegmentNode.Create;
HAnimSegment101.NameField := 'r_metacarpal_2';
Transform102 := TTransformNode.Create;
Transform102.Translation := Vector3(-0.1,0.2,0);
Shape103 := TShapeNode.Create;
Shape103 := Shape33;
{ .AddChild }
Transform102.AddChildren([Shape103]);
{ .AddChildren }
HAnimSegment101.AddChildren([Transform102]);
Shape104 := TShapeNode.Create;
Appearance105 := TAppearanceNode.Create;
Material106 := TMaterialNode.Create;
Material106.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance105.Material := Material106;
{ .SetAppearance }
Shape104.Appearance := Appearance105;
IndexedLineSet107 := TIndexedLineSetNode.Create;
IndexedLineSet107.SetCoordIndex([0,1]);
Coordinate108 := TCoordinateNode.Create;
Coordinate108.SetPoint([Vector3(-0.1,0.2,0),Vector3(-0.15,0.5,0)]);
{ .SetCoord }
IndexedLineSet107.Coord := Coordinate108;
{ .SetGeometry }
Shape104.Geometry := IndexedLineSet107;
{ .AddChildren }
HAnimSegment101.AddChildren([Shape104]);
{ .AddChildren }
HAnimJoint100.AddChildren([HAnimSegment101]);
HAnimJoint109 := THAnimJointNode.Create;
HAnimJoint109.NameField := 'r_metacarpophalangeal_2';
HAnimJoint109.Center := Vector3(-0.15,0.5,0);
HAnimJoint109.SetUlimit([0,0,0]);
HAnimJoint109.SetLlimit([0,0,0]);
HAnimSegment110 := THAnimSegmentNode.Create;
HAnimSegment110.NameField := 'r_carpal_proximal_phalanx_2';
Transform111 := TTransformNode.Create;
Transform111.Translation := Vector3(-0.15,0.5,0);
Shape112 := TShapeNode.Create;
Shape112 := Shape33;
{ .AddChild }
Transform111.AddChildren([Shape112]);
{ .AddChildren }
HAnimSegment110.AddChildren([Transform111]);
Shape113 := TShapeNode.Create;
Appearance114 := TAppearanceNode.Create;
Material115 := TMaterialNode.Create;
Material115.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance114.Material := Material115;
{ .SetAppearance }
Shape113.Appearance := Appearance114;
IndexedLineSet116 := TIndexedLineSetNode.Create;
IndexedLineSet116.SetCoordIndex([0,1]);
Coordinate117 := TCoordinateNode.Create;
Coordinate117.SetPoint([Vector3(-0.15,0.5,0),Vector3(-0.2,0.7,0)]);
{ .SetCoord }
IndexedLineSet116.Coord := Coordinate117;
{ .SetGeometry }
Shape113.Geometry := IndexedLineSet116;
{ .AddChildren }
HAnimSegment110.AddChildren([Shape113]);
{ .AddChildren }
HAnimJoint109.AddChildren([HAnimSegment110]);
HAnimJoint118 := THAnimJointNode.Create;
HAnimJoint118.NameField := 'r_carpal_proximal_interphalangeal_2';
HAnimJoint118.Center := Vector3(-0.2,0.7,0);
HAnimJoint118.SetUlimit([0,0,0]);
HAnimJoint118.SetLlimit([0,0,0]);
HAnimSegment119 := THAnimSegmentNode.Create;
HAnimSegment119.NameField := 'r_carpal_middle_phalanx_2';
Transform120 := TTransformNode.Create;
Transform120.Translation := Vector3(-0.2,0.7,0);
Shape121 := TShapeNode.Create;
Shape121 := Shape33;
{ .AddChild }
Transform120.AddChildren([Shape121]);
{ .AddChildren }
HAnimSegment119.AddChildren([Transform120]);
Shape122 := TShapeNode.Create;
Appearance123 := TAppearanceNode.Create;
Material124 := TMaterialNode.Create;
Material124.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance123.Material := Material124;
{ .SetAppearance }
Shape122.Appearance := Appearance123;
IndexedLineSet125 := TIndexedLineSetNode.Create;
IndexedLineSet125.SetCoordIndex([0,1]);
Coordinate126 := TCoordinateNode.Create;
Coordinate126.SetPoint([Vector3(-0.2,0.7,0),Vector3(-0.24,0.87,0)]);
{ .SetCoord }
IndexedLineSet125.Coord := Coordinate126;
{ .SetGeometry }
Shape122.Geometry := IndexedLineSet125;
{ .AddChildren }
HAnimSegment119.AddChildren([Shape122]);
{ .AddChildren }
HAnimJoint118.AddChildren([HAnimSegment119]);
HAnimJoint127 := THAnimJointNode.Create;
HAnimJoint127.NameField := 'r_carpal_distal_interphalangeal_2';
HAnimJoint127.Center := Vector3(-0.24,0.87,0);
HAnimJoint127.SetUlimit([0,0,0]);
HAnimJoint127.SetLlimit([0,0,0]);
HAnimSegment128 := THAnimSegmentNode.Create;
HAnimSegment128.NameField := 'r_carpal_distal_phalanx_2';
Transform129 := TTransformNode.Create;
Transform129.Translation := Vector3(-0.24,0.87,0);
Shape130 := TShapeNode.Create;
Shape130 := Shape33;
{ .AddChild }
Transform129.AddChildren([Shape130]);
{ .AddChildren }
HAnimSegment128.AddChildren([Transform129]);
Shape131 := TShapeNode.Create;
Appearance132 := TAppearanceNode.Create;
Material133 := TMaterialNode.Create;
Material133.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance132.Material := Material133;
{ .SetAppearance }
Shape131.Appearance := Appearance132;
IndexedLineSet134 := TIndexedLineSetNode.Create;
IndexedLineSet134.SetCoordIndex([0,1]);
Coordinate135 := TCoordinateNode.Create;
Coordinate135.SetPoint([Vector3(-0.24,0.87,0),Vector3(-0.26,0.93,0)]);
{ .SetCoord }
IndexedLineSet134.Coord := Coordinate135;
{ .SetGeometry }
Shape131.Geometry := IndexedLineSet134;
{ .AddChildren }
HAnimSegment128.AddChildren([Shape131]);
{ .AddChildren }
HAnimJoint127.AddChildren([HAnimSegment128]);
{ .AddChildren }
HAnimJoint118.AddChildren([HAnimJoint127]);
{ .AddChildren }
HAnimJoint109.AddChildren([HAnimJoint118]);
{ .AddChildren }
HAnimJoint100.AddChildren([HAnimJoint109]);
{ .AddChildren }
HAnimJoint91.AddChildren([HAnimJoint100]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimJoint91]);
{ MC3 }
HAnimJoint136 := THAnimJointNode.Create;
HAnimJoint136.NameField := 'r_midcarpal_3';
HAnimJoint136.Center := Vector3(0,0.07,0);
HAnimJoint136.SetUlimit([0,0,0]);
HAnimJoint136.SetLlimit([0,0,0]);
HAnimSegment137 := THAnimSegmentNode.Create;
HAnimSegment137.NameField := 'r_capitate';
Transform138 := TTransformNode.Create;
Transform138.Translation := Vector3(0,0.07,0);
Shape139 := TShapeNode.Create;
Shape139 := Shape55;
{ .AddChild }
Transform138.AddChildren([Shape139]);
{ .AddChildren }
HAnimSegment137.AddChildren([Transform138]);
Shape140 := TShapeNode.Create;
Appearance141 := TAppearanceNode.Create;
Material142 := TMaterialNode.Create;
Material142.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance141.Material := Material142;
{ .SetAppearance }
Shape140.Appearance := Appearance141;
IndexedLineSet143 := TIndexedLineSetNode.Create;
IndexedLineSet143.SetCoordIndex([0,1]);
Coordinate144 := TCoordinateNode.Create;
Coordinate144.SetPoint([Vector3(0,0.07,0),Vector3(0,0.2,0)]);
{ .SetCoord }
IndexedLineSet143.Coord := Coordinate144;
{ .SetGeometry }
Shape140.Geometry := IndexedLineSet143;
{ .AddChildren }
HAnimSegment137.AddChildren([Shape140]);
{ .AddChildren }
HAnimJoint136.AddChildren([HAnimSegment137]);
{ Middle fingle }
HAnimJoint145 := THAnimJointNode.Create;
HAnimJoint145.NameField := 'r_carpometacarpal_3';
HAnimJoint145.Center := Vector3(0,0.2,0);
HAnimJoint145.SetUlimit([0,0,0]);
HAnimJoint145.SetLlimit([0,0,0]);
HAnimSegment146 := THAnimSegmentNode.Create;
HAnimSegment146.NameField := 'r_metacarpal_3';
Transform147 := TTransformNode.Create;
Transform147.Translation := Vector3(0,0.2,0);
Shape148 := TShapeNode.Create;
Shape148 := Shape33;
{ .AddChild }
Transform147.AddChildren([Shape148]);
{ .AddChildren }
HAnimSegment146.AddChildren([Transform147]);
Shape149 := TShapeNode.Create;
Appearance150 := TAppearanceNode.Create;
Material151 := TMaterialNode.Create;
Material151.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance150.Material := Material151;
{ .SetAppearance }
Shape149.Appearance := Appearance150;
IndexedLineSet152 := TIndexedLineSetNode.Create;
IndexedLineSet152.SetCoordIndex([0,1]);
Coordinate153 := TCoordinateNode.Create;
Coordinate153.SetPoint([Vector3(0,0.2,0),Vector3(-0.03,0.5,0)]);
{ .SetCoord }
IndexedLineSet152.Coord := Coordinate153;
{ .SetGeometry }
Shape149.Geometry := IndexedLineSet152;
{ .AddChildren }
HAnimSegment146.AddChildren([Shape149]);
{ .AddChildren }
HAnimJoint145.AddChildren([HAnimSegment146]);
HAnimJoint154 := THAnimJointNode.Create;
HAnimJoint154.NameField := 'r_metacarpophalangeal_3';
HAnimJoint154.Center := Vector3(-0.03,0.5,0);
HAnimJoint154.SetUlimit([0,0,0]);
HAnimJoint154.SetLlimit([0,0,0]);
HAnimSegment155 := THAnimSegmentNode.Create;
HAnimSegment155.NameField := 'r_carpal_proximal_phalanx_3';
Transform156 := TTransformNode.Create;
Transform156.Translation := Vector3(-0.03,0.5,0);
Shape157 := TShapeNode.Create;
Shape157 := Shape33;
{ .AddChild }
Transform156.AddChildren([Shape157]);
{ .AddChildren }
HAnimSegment155.AddChildren([Transform156]);
Shape158 := TShapeNode.Create;
Appearance159 := TAppearanceNode.Create;
Material160 := TMaterialNode.Create;
Material160.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance159.Material := Material160;
{ .SetAppearance }
Shape158.Appearance := Appearance159;
IndexedLineSet161 := TIndexedLineSetNode.Create;
IndexedLineSet161.SetCoordIndex([0,1]);
Coordinate162 := TCoordinateNode.Create;
Coordinate162.SetPoint([Vector3(-0.03,0.5,0),Vector3(-0.05,0.75,0)]);
{ .SetCoord }
IndexedLineSet161.Coord := Coordinate162;
{ .SetGeometry }
Shape158.Geometry := IndexedLineSet161;
{ .AddChildren }
HAnimSegment155.AddChildren([Shape158]);
{ .AddChildren }
HAnimJoint154.AddChildren([HAnimSegment155]);
HAnimJoint163 := THAnimJointNode.Create;
HAnimJoint163.NameField := 'r_carpal_proximal_interphalangeal_3';
HAnimJoint163.Center := Vector3(-0.05,0.75,0);
HAnimJoint163.SetUlimit([0,0,0]);
HAnimJoint163.SetLlimit([0,0,0]);
HAnimSegment164 := THAnimSegmentNode.Create;
HAnimSegment164.NameField := 'r_carpal_middle_phalanx_3';
Transform165 := TTransformNode.Create;
Transform165.Translation := Vector3(-0.05,0.75,0);
Shape166 := TShapeNode.Create;
Shape166 := Shape33;
{ .AddChild }
Transform165.AddChildren([Shape166]);
{ .AddChildren }
HAnimSegment164.AddChildren([Transform165]);
Shape167 := TShapeNode.Create;
Appearance168 := TAppearanceNode.Create;
Material169 := TMaterialNode.Create;
Material169.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance168.Material := Material169;
{ .SetAppearance }
Shape167.Appearance := Appearance168;
IndexedLineSet170 := TIndexedLineSetNode.Create;
IndexedLineSet170.SetCoordIndex([0,1]);
Coordinate171 := TCoordinateNode.Create;
Coordinate171.SetPoint([Vector3(-0.05,0.75,0),Vector3(-0.08,0.96,0)]);
{ .SetCoord }
IndexedLineSet170.Coord := Coordinate171;
{ .SetGeometry }
Shape167.Geometry := IndexedLineSet170;
{ .AddChildren }
HAnimSegment164.AddChildren([Shape167]);
{ .AddChildren }
HAnimJoint163.AddChildren([HAnimSegment164]);
HAnimJoint172 := THAnimJointNode.Create;
HAnimJoint172.NameField := 'r_carpal_distal_interphalangeal_3';
HAnimJoint172.Center := Vector3(-0.08,0.96,0);
HAnimJoint172.SetUlimit([0,0,0]);
HAnimJoint172.SetLlimit([0,0,0]);
HAnimSegment173 := THAnimSegmentNode.Create;
HAnimSegment173.NameField := 'r_carpal_distal_phalanx_3';
Transform174 := TTransformNode.Create;
Transform174.Translation := Vector3(-0.08,0.96,0);
Shape175 := TShapeNode.Create;
Shape175 := Shape33;
{ .AddChild }
Transform174.AddChildren([Shape175]);
{ .AddChildren }
HAnimSegment173.AddChildren([Transform174]);
Shape176 := TShapeNode.Create;
Appearance177 := TAppearanceNode.Create;
Material178 := TMaterialNode.Create;
Material178.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance177.Material := Material178;
{ .SetAppearance }
Shape176.Appearance := Appearance177;
IndexedLineSet179 := TIndexedLineSetNode.Create;
IndexedLineSet179.SetCoordIndex([0,1]);
Coordinate180 := TCoordinateNode.Create;
Coordinate180.SetPoint([Vector3(-0.08,0.96,0),Vector3(-0.09,1.05,0)]);
{ .SetCoord }
IndexedLineSet179.Coord := Coordinate180;
{ .SetGeometry }
Shape176.Geometry := IndexedLineSet179;
{ .AddChildren }
HAnimSegment173.AddChildren([Shape176]);
{ .AddChildren }
HAnimJoint172.AddChildren([HAnimSegment173]);
{ .AddChildren }
HAnimJoint163.AddChildren([HAnimJoint172]);
{ .AddChildren }
HAnimJoint154.AddChildren([HAnimJoint163]);
{ .AddChildren }
HAnimJoint145.AddChildren([HAnimJoint154]);
{ .AddChildren }
HAnimJoint136.AddChildren([HAnimJoint145]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimJoint136]);
{ MC4_5 }
HAnimJoint181 := THAnimJointNode.Create;
HAnimJoint181.NameField := 'r_midcarpal_4_5';
HAnimJoint181.Center := Vector3(0.1,0.1,0);
HAnimJoint181.SetUlimit([0,0,0]);
HAnimJoint181.SetLlimit([0,0,0]);
HAnimSegment182 := THAnimSegmentNode.Create;
HAnimSegment182.NameField := 'r_hamate';
Transform183 := TTransformNode.Create;
Transform183.Translation := Vector3(0.1,0.1,0);
Shape184 := TShapeNode.Create;
Shape184 := Shape55;
{ .AddChild }
Transform183.AddChildren([Shape184]);
{ .AddChildren }
HAnimSegment182.AddChildren([Transform183]);
Shape185 := TShapeNode.Create;
Appearance186 := TAppearanceNode.Create;
Material187 := TMaterialNode.Create;
Material187.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance186.Material := Material187;
{ .SetAppearance }
Shape185.Appearance := Appearance186;
IndexedLineSet188 := TIndexedLineSetNode.Create;
IndexedLineSet188.SetCoordIndex([0,1]);
Coordinate189 := TCoordinateNode.Create;
Coordinate189.SetPoint([Vector3(0.1,0.1,0),Vector3(0.1,0.2,0)]);
{ .SetCoord }
IndexedLineSet188.Coord := Coordinate189;
{ .SetGeometry }
Shape185.Geometry := IndexedLineSet188;
{ .AddChildren }
HAnimSegment182.AddChildren([Shape185]);
Shape190 := TShapeNode.Create;
Appearance191 := TAppearanceNode.Create;
Material192 := TMaterialNode.Create;
Material192.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance191.Material := Material192;
{ .SetAppearance }
Shape190.Appearance := Appearance191;
IndexedLineSet193 := TIndexedLineSetNode.Create;
IndexedLineSet193.SetCoordIndex([0,1]);
Coordinate194 := TCoordinateNode.Create;
Coordinate194.SetPoint([Vector3(0.1,0.1,0),Vector3(0.15,0.17,0)]);
{ .SetCoord }
IndexedLineSet193.Coord := Coordinate194;
{ .SetGeometry }
Shape190.Geometry := IndexedLineSet193;
{ .AddChildren }
HAnimSegment182.AddChildren([Shape190]);
{ .AddChildren }
HAnimJoint181.AddChildren([HAnimSegment182]);
{ ring finger }
HAnimJoint195 := THAnimJointNode.Create;
HAnimJoint195.NameField := 'r_carpometacarpal_4';
HAnimJoint195.Center := Vector3(0.1,0.2,0);
HAnimJoint195.SetUlimit([0,0,0]);
HAnimJoint195.SetLlimit([0,0,0]);
HAnimSegment196 := THAnimSegmentNode.Create;
HAnimSegment196.NameField := 'r_metacarpal_4';
Transform197 := TTransformNode.Create;
Transform197.Translation := Vector3(0.1,0.2,0);
Shape198 := TShapeNode.Create;
Shape198 := Shape33;
{ .AddChild }
Transform197.AddChildren([Shape198]);
{ .AddChildren }
HAnimSegment196.AddChildren([Transform197]);
Shape199 := TShapeNode.Create;
Appearance200 := TAppearanceNode.Create;
Material201 := TMaterialNode.Create;
Material201.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance200.Material := Material201;
{ .SetAppearance }
Shape199.Appearance := Appearance200;
IndexedLineSet202 := TIndexedLineSetNode.Create;
IndexedLineSet202.SetCoordIndex([0,1]);
Coordinate203 := TCoordinateNode.Create;
Coordinate203.SetPoint([Vector3(0.1,0.2,0),Vector3(0.1,0.47,0)]);
{ .SetCoord }
IndexedLineSet202.Coord := Coordinate203;
{ .SetGeometry }
Shape199.Geometry := IndexedLineSet202;
{ .AddChildren }
HAnimSegment196.AddChildren([Shape199]);
{ .AddChildren }
HAnimJoint195.AddChildren([HAnimSegment196]);
HAnimJoint204 := THAnimJointNode.Create;
HAnimJoint204.NameField := 'r_metacarpophalangeal_4';
HAnimJoint204.Center := Vector3(0.1,0.47,0);
HAnimJoint204.SetUlimit([0,0,0]);
HAnimJoint204.SetLlimit([0,0,0]);
HAnimSegment205 := THAnimSegmentNode.Create;
HAnimSegment205.NameField := 'r_carpal_proximal_phalanx_4';
Transform206 := TTransformNode.Create;
Transform206.Translation := Vector3(0.1,0.47,0);
Shape207 := TShapeNode.Create;
Shape207 := Shape33;
{ .AddChild }
Transform206.AddChildren([Shape207]);
{ .AddChildren }
HAnimSegment205.AddChildren([Transform206]);
Shape208 := TShapeNode.Create;
Appearance209 := TAppearanceNode.Create;
Material210 := TMaterialNode.Create;
Material210.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance209.Material := Material210;
{ .SetAppearance }
Shape208.Appearance := Appearance209;
IndexedLineSet211 := TIndexedLineSetNode.Create;
IndexedLineSet211.SetCoordIndex([0,1]);
Coordinate212 := TCoordinateNode.Create;
Coordinate212.SetPoint([Vector3(0.1,0.47,0),Vector3(0.1,0.7,0)]);
{ .SetCoord }
IndexedLineSet211.Coord := Coordinate212;
{ .SetGeometry }
Shape208.Geometry := IndexedLineSet211;
{ .AddChildren }
HAnimSegment205.AddChildren([Shape208]);
{ .AddChildren }
HAnimJoint204.AddChildren([HAnimSegment205]);
HAnimJoint213 := THAnimJointNode.Create;
HAnimJoint213.NameField := 'r_carpal_proximal_interphalangeal_4';
HAnimJoint213.Center := Vector3(0.1,0.7,0);
HAnimJoint213.SetUlimit([0,0,0]);
HAnimJoint213.SetLlimit([0,0,0]);
HAnimSegment214 := THAnimSegmentNode.Create;
HAnimSegment214.NameField := 'r_carpal_middle_phalanx_4';
Transform215 := TTransformNode.Create;
Transform215.Translation := Vector3(0.1,0.7,0);
Shape216 := TShapeNode.Create;
Shape216 := Shape33;
{ .AddChild }
Transform215.AddChildren([Shape216]);
{ .AddChildren }
HAnimSegment214.AddChildren([Transform215]);
Shape217 := TShapeNode.Create;
Appearance218 := TAppearanceNode.Create;
Material219 := TMaterialNode.Create;
Material219.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance218.Material := Material219;
{ .SetAppearance }
Shape217.Appearance := Appearance218;
IndexedLineSet220 := TIndexedLineSetNode.Create;
IndexedLineSet220.SetCoordIndex([0,1]);
Coordinate221 := TCoordinateNode.Create;
Coordinate221.SetPoint([Vector3(0.1,0.7,0),Vector3(0.1,0.93,0)]);
{ .SetCoord }
IndexedLineSet220.Coord := Coordinate221;
{ .SetGeometry }
Shape217.Geometry := IndexedLineSet220;
{ .AddChildren }
HAnimSegment214.AddChildren([Shape217]);
{ .AddChildren }
HAnimJoint213.AddChildren([HAnimSegment214]);
HAnimJoint222 := THAnimJointNode.Create;
HAnimJoint222.NameField := 'r_carpal_distal_interphalangeal_4';
HAnimJoint222.Center := Vector3(0.1,0.93,0);
HAnimJoint222.SetUlimit([0,0,0]);
HAnimJoint222.SetLlimit([0,0,0]);
HAnimSegment223 := THAnimSegmentNode.Create;
HAnimSegment223.NameField := 'r_carpal_distal_phalanx_4';
Transform224 := TTransformNode.Create;
Transform224.Translation := Vector3(0.1,0.93,0);
Shape225 := TShapeNode.Create;
Shape225 := Shape33;
{ .AddChild }
Transform224.AddChildren([Shape225]);
{ .AddChildren }
HAnimSegment223.AddChildren([Transform224]);
Shape226 := TShapeNode.Create;
Appearance227 := TAppearanceNode.Create;
Material228 := TMaterialNode.Create;
Material228.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance227.Material := Material228;
{ .SetAppearance }
Shape226.Appearance := Appearance227;
IndexedLineSet229 := TIndexedLineSetNode.Create;
IndexedLineSet229.SetCoordIndex([0,1]);
Coordinate230 := TCoordinateNode.Create;
Coordinate230.SetPoint([Vector3(0.1,0.93,0),Vector3(0.1,1,0)]);
{ .SetCoord }
IndexedLineSet229.Coord := Coordinate230;
{ .SetGeometry }
Shape226.Geometry := IndexedLineSet229;
{ .AddChildren }
HAnimSegment223.AddChildren([Shape226]);
{ .AddChildren }
HAnimJoint222.AddChildren([HAnimSegment223]);
{ .AddChildren }
HAnimJoint213.AddChildren([HAnimJoint222]);
{ .AddChildren }
HAnimJoint204.AddChildren([HAnimJoint213]);
{ .AddChildren }
HAnimJoint195.AddChildren([HAnimJoint204]);
{ .AddChildren }
HAnimJoint181.AddChildren([HAnimJoint195]);
{ pinky finger }
HAnimJoint231 := THAnimJointNode.Create;
HAnimJoint231.NameField := 'r_carpometacarpal_5';
HAnimJoint231.Center := Vector3(0.15,0.17,0);
HAnimJoint231.SetUlimit([0,0,0]);
HAnimJoint231.SetLlimit([0,0,0]);
HAnimSegment232 := THAnimSegmentNode.Create;
HAnimSegment232.NameField := 'r_metacarpal_5';
Transform233 := TTransformNode.Create;
Transform233.Translation := Vector3(0.15,0.17,0);
Shape234 := TShapeNode.Create;
Shape234 := Shape33;
{ .AddChild }
Transform233.AddChildren([Shape234]);
{ .AddChildren }
HAnimSegment232.AddChildren([Transform233]);
Shape235 := TShapeNode.Create;
Appearance236 := TAppearanceNode.Create;
Material237 := TMaterialNode.Create;
Material237.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance236.Material := Material237;
{ .SetAppearance }
Shape235.Appearance := Appearance236;
IndexedLineSet238 := TIndexedLineSetNode.Create;
IndexedLineSet238.SetCoordIndex([0,1]);
Coordinate239 := TCoordinateNode.Create;
Coordinate239.SetPoint([Vector3(0.15,0.17,0),Vector3(0.2,0.4,0)]);
{ .SetCoord }
IndexedLineSet238.Coord := Coordinate239;
{ .SetGeometry }
Shape235.Geometry := IndexedLineSet238;
{ .AddChildren }
HAnimSegment232.AddChildren([Shape235]);
{ .AddChildren }
HAnimJoint231.AddChildren([HAnimSegment232]);
HAnimJoint240 := THAnimJointNode.Create;
HAnimJoint240.NameField := 'r_metacarpophalangeal_5';
HAnimJoint240.Center := Vector3(0.2,0.4,0);
HAnimJoint240.SetUlimit([0,0,0]);
HAnimJoint240.SetLlimit([0,0,0]);
HAnimSegment241 := THAnimSegmentNode.Create;
HAnimSegment241.NameField := 'r_carpal_proximal_phalanx_5';
Transform242 := TTransformNode.Create;
Transform242.Translation := Vector3(0.2,0.4,0);
Shape243 := TShapeNode.Create;
Shape243 := Shape33;
{ .AddChild }
Transform242.AddChildren([Shape243]);
{ .AddChildren }
HAnimSegment241.AddChildren([Transform242]);
Shape244 := TShapeNode.Create;
Appearance245 := TAppearanceNode.Create;
Material246 := TMaterialNode.Create;
Material246.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance245.Material := Material246;
{ .SetAppearance }
Shape244.Appearance := Appearance245;
IndexedLineSet247 := TIndexedLineSetNode.Create;
IndexedLineSet247.SetCoordIndex([0,1]);
Coordinate248 := TCoordinateNode.Create;
Coordinate248.SetPoint([Vector3(0.2,0.4,0),Vector3(0.23,0.63,0)]);
{ .SetCoord }
IndexedLineSet247.Coord := Coordinate248;
{ .SetGeometry }
Shape244.Geometry := IndexedLineSet247;
{ .AddChildren }
HAnimSegment241.AddChildren([Shape244]);
{ .AddChildren }
HAnimJoint240.AddChildren([HAnimSegment241]);
HAnimJoint249 := THAnimJointNode.Create;
HAnimJoint249.NameField := 'r_carpal_proximal_interphalangeal_5';
HAnimJoint249.Center := Vector3(0.23,0.63,0);
HAnimJoint249.SetUlimit([0,0,0]);
HAnimJoint249.SetLlimit([0,0,0]);
HAnimSegment250 := THAnimSegmentNode.Create;
HAnimSegment250.NameField := 'r_carpal_middle_phalanx_5';
Transform251 := TTransformNode.Create;
Transform251.Translation := Vector3(0.23,0.63,0);
Shape252 := TShapeNode.Create;
Shape252 := Shape33;
{ .AddChild }
Transform251.AddChildren([Shape252]);
{ .AddChildren }
HAnimSegment250.AddChildren([Transform251]);
Shape253 := TShapeNode.Create;
Appearance254 := TAppearanceNode.Create;
Material255 := TMaterialNode.Create;
Material255.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance254.Material := Material255;
{ .SetAppearance }
Shape253.Appearance := Appearance254;
IndexedLineSet256 := TIndexedLineSetNode.Create;
IndexedLineSet256.SetCoordIndex([0,1]);
Coordinate257 := TCoordinateNode.Create;
Coordinate257.SetPoint([Vector3(0.23,0.63,0),Vector3(0.25,0.79,0)]);
{ .SetCoord }
IndexedLineSet256.Coord := Coordinate257;
{ .SetGeometry }
Shape253.Geometry := IndexedLineSet256;
{ .AddChildren }
HAnimSegment250.AddChildren([Shape253]);
{ .AddChildren }
HAnimJoint249.AddChildren([HAnimSegment250]);
HAnimJoint258 := THAnimJointNode.Create;
HAnimJoint258.NameField := 'r_carpal_distal_interphalangeal_5';
HAnimJoint258.Center := Vector3(0.25,0.79,0);
HAnimJoint258.SetUlimit([0,0,0]);
HAnimJoint258.SetLlimit([0,0,0]);
HAnimSegment259 := THAnimSegmentNode.Create;
HAnimSegment259.NameField := 'r_carpal_distal_phalanx_5';
Transform260 := TTransformNode.Create;
Transform260.Translation := Vector3(0.25,0.79,0);
Shape261 := TShapeNode.Create;
Shape261 := Shape33;
{ .AddChild }
Transform260.AddChildren([Shape261]);
{ .AddChildren }
HAnimSegment259.AddChildren([Transform260]);
Shape262 := TShapeNode.Create;
Appearance263 := TAppearanceNode.Create;
Material264 := TMaterialNode.Create;
Material264.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance263.Material := Material264;
{ .SetAppearance }
Shape262.Appearance := Appearance263;
IndexedLineSet265 := TIndexedLineSetNode.Create;
IndexedLineSet265.SetCoordIndex([0,1]);
Coordinate266 := TCoordinateNode.Create;
Coordinate266.SetPoint([Vector3(0.25,0.79,0),Vector3(0.26,0.85,0)]);
{ .SetCoord }
IndexedLineSet265.Coord := Coordinate266;
{ .SetGeometry }
Shape262.Geometry := IndexedLineSet265;
{ .AddChildren }
HAnimSegment259.AddChildren([Shape262]);
{ .AddChildren }
HAnimJoint258.AddChildren([HAnimSegment259]);
{ .AddChildren }
HAnimJoint249.AddChildren([HAnimJoint258]);
{ .AddChildren }
HAnimJoint240.AddChildren([HAnimJoint249]);
{ .AddChildren }
HAnimJoint231.AddChildren([HAnimJoint240]);
{ .AddChildren }
HAnimJoint181.AddChildren([HAnimJoint231]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimJoint181]);
{ .AddChildren }
HAnimJoint29.AddChildren([HAnimJoint30]);
{ .AddSkeleton }
HAnimHumanoid26.SetSkeleton([HAnimJoint29]);
HAnimJoint267 := THAnimJointNode.Create;
HAnimJoint267 := HAnimJoint29;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint267;
HAnimJoint268 := THAnimJointNode.Create;
HAnimJoint268 := HAnimJoint127;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint268;
HAnimJoint269 := THAnimJointNode.Create;
HAnimJoint269 := HAnimJoint172;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint269;
HAnimJoint270 := THAnimJointNode.Create;
HAnimJoint270 := HAnimJoint222;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint270;
HAnimJoint271 := THAnimJointNode.Create;
HAnimJoint271 := HAnimJoint258;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint271;
HAnimJoint272 := THAnimJointNode.Create;
HAnimJoint272 := HAnimJoint82;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint272;
HAnimJoint273 := THAnimJointNode.Create;
HAnimJoint273 := HAnimJoint118;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint273;
HAnimJoint274 := THAnimJointNode.Create;
HAnimJoint274 := HAnimJoint163;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint274;
HAnimJoint275 := THAnimJointNode.Create;
HAnimJoint275 := HAnimJoint213;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint275;
HAnimJoint276 := THAnimJointNode.Create;
HAnimJoint276 := HAnimJoint249;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint276;
HAnimJoint277 := THAnimJointNode.Create;
HAnimJoint277 := HAnimJoint64;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint277;
HAnimJoint278 := THAnimJointNode.Create;
HAnimJoint278 := HAnimJoint100;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint278;
HAnimJoint279 := THAnimJointNode.Create;
HAnimJoint279 := HAnimJoint145;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint279;
HAnimJoint280 := THAnimJointNode.Create;
HAnimJoint280 := HAnimJoint195;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint280;
HAnimJoint281 := THAnimJointNode.Create;
HAnimJoint281 := HAnimJoint231;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint281;
HAnimJoint282 := THAnimJointNode.Create;
HAnimJoint282 := HAnimJoint73;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint282;
HAnimJoint283 := THAnimJointNode.Create;
HAnimJoint283 := HAnimJoint109;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint283;
HAnimJoint284 := THAnimJointNode.Create;
HAnimJoint284 := HAnimJoint154;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint284;
HAnimJoint285 := THAnimJointNode.Create;
HAnimJoint285 := HAnimJoint204;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint285;
HAnimJoint286 := THAnimJointNode.Create;
HAnimJoint286 := HAnimJoint240;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint286;
HAnimJoint287 := THAnimJointNode.Create;
HAnimJoint287 := HAnimJoint52;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint287;
HAnimJoint288 := THAnimJointNode.Create;
HAnimJoint288 := HAnimJoint91;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint288;
HAnimJoint289 := THAnimJointNode.Create;
HAnimJoint289 := HAnimJoint136;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint289;
HAnimJoint290 := THAnimJointNode.Create;
HAnimJoint290 := HAnimJoint181;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint290;
HAnimJoint291 := THAnimJointNode.Create;
HAnimJoint291 := HAnimJoint30;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint291;
{ .AddChildren }
Group24.AddChildren([HAnimHumanoid26]);
{ .AddGroup }
X3D0.AddChildren([Group24]);
Result := X3D0;
end;
