function HAnimModelFootLeft: TX3DRootNode;
var
X3D0: TX3DRootNode;
Group22: TGroupNode;
WorldInfo23: TWorldInfoNode;
HAnimHumanoid24: THAnimHumanoidNode;
MetadataSet25: TMetadataSetNode;
MetadataString26: TMetadataStringNode;
HAnimJoint27: THAnimJointNode;
HAnimJoint28: THAnimJointNode;
HAnimSegment29: THAnimSegmentNode;
Transform30: TTransformNode;
Shape31: TShapeNode;
Sphere32: TSphereNode;
Appearance33: TAppearanceNode;
Material34: TMaterialNode;
Shape35: TShapeNode;
Appearance36: TAppearanceNode;
Material37: TMaterialNode;
IndexedLineSet38: TIndexedLineSetNode;
Coordinate39: TCoordinateNode;
Shape40: TShapeNode;
Appearance41: TAppearanceNode;
Material42: TMaterialNode;
IndexedLineSet43: TIndexedLineSetNode;
Coordinate44: TCoordinateNode;
HAnimJoint45: THAnimJointNode;
HAnimSegment46: THAnimSegmentNode;
Transform47: TTransformNode;
Shape48: TShapeNode;
Shape49: TShapeNode;
Appearance50: TAppearanceNode;
Material51: TMaterialNode;
IndexedLineSet52: TIndexedLineSetNode;
Coordinate53: TCoordinateNode;
Shape54: TShapeNode;
Appearance55: TAppearanceNode;
Material56: TMaterialNode;
IndexedLineSet57: TIndexedLineSetNode;
Coordinate58: TCoordinateNode;
Shape59: TShapeNode;
Appearance60: TAppearanceNode;
Material61: TMaterialNode;
IndexedLineSet62: TIndexedLineSetNode;
Coordinate63: TCoordinateNode;
HAnimJoint64: THAnimJointNode;
HAnimSegment65: THAnimSegmentNode;
Transform66: TTransformNode;
Shape67: TShapeNode;
Shape68: TShapeNode;
Appearance69: TAppearanceNode;
Material70: TMaterialNode;
IndexedLineSet71: TIndexedLineSetNode;
Coordinate72: TCoordinateNode;
HAnimJoint73: THAnimJointNode;
HAnimSegment74: THAnimSegmentNode;
Transform75: TTransformNode;
Shape76: TShapeNode;
Shape77: TShapeNode;
Appearance78: TAppearanceNode;
Material79: TMaterialNode;
IndexedLineSet80: TIndexedLineSetNode;
Coordinate81: TCoordinateNode;
HAnimJoint82: THAnimJointNode;
HAnimSegment83: THAnimSegmentNode;
Transform84: TTransformNode;
Shape85: TShapeNode;
Shape86: TShapeNode;
Appearance87: TAppearanceNode;
Material88: TMaterialNode;
IndexedLineSet89: TIndexedLineSetNode;
Coordinate90: TCoordinateNode;
HAnimJoint91: THAnimJointNode;
HAnimSegment92: THAnimSegmentNode;
Transform93: TTransformNode;
Shape94: TShapeNode;
Shape95: TShapeNode;
Appearance96: TAppearanceNode;
Material97: TMaterialNode;
IndexedLineSet98: TIndexedLineSetNode;
Coordinate99: TCoordinateNode;
HAnimJoint100: THAnimJointNode;
HAnimSegment101: THAnimSegmentNode;
Transform102: TTransformNode;
Shape103: TShapeNode;
Shape104: TShapeNode;
Appearance105: TAppearanceNode;
Material106: TMaterialNode;
IndexedLineSet107: TIndexedLineSetNode;
Coordinate108: TCoordinateNode;
HAnimJoint109: THAnimJointNode;
HAnimSegment110: THAnimSegmentNode;
Transform111: TTransformNode;
Shape112: TShapeNode;
Shape113: TShapeNode;
Appearance114: TAppearanceNode;
Material115: TMaterialNode;
IndexedLineSet116: TIndexedLineSetNode;
Coordinate117: TCoordinateNode;
HAnimJoint118: THAnimJointNode;
HAnimSegment119: THAnimSegmentNode;
Transform120: TTransformNode;
Shape121: TShapeNode;
Shape122: TShapeNode;
Appearance123: TAppearanceNode;
Material124: TMaterialNode;
IndexedLineSet125: TIndexedLineSetNode;
Coordinate126: TCoordinateNode;
HAnimJoint127: THAnimJointNode;
HAnimSegment128: THAnimSegmentNode;
Transform129: TTransformNode;
Shape130: TShapeNode;
Shape131: TShapeNode;
Appearance132: TAppearanceNode;
Material133: TMaterialNode;
IndexedLineSet134: TIndexedLineSetNode;
Coordinate135: TCoordinateNode;
HAnimJoint136: THAnimJointNode;
HAnimSegment137: THAnimSegmentNode;
Transform138: TTransformNode;
Shape139: TShapeNode;
Shape140: TShapeNode;
Appearance141: TAppearanceNode;
Material142: TMaterialNode;
IndexedLineSet143: TIndexedLineSetNode;
Coordinate144: TCoordinateNode;
HAnimJoint145: THAnimJointNode;
HAnimSegment146: THAnimSegmentNode;
Transform147: TTransformNode;
Shape148: TShapeNode;
Shape149: TShapeNode;
Appearance150: TAppearanceNode;
Material151: TMaterialNode;
IndexedLineSet152: TIndexedLineSetNode;
Coordinate153: TCoordinateNode;
HAnimJoint154: THAnimJointNode;
HAnimSegment155: THAnimSegmentNode;
Transform156: TTransformNode;
Shape157: TShapeNode;
Shape158: TShapeNode;
Appearance159: TAppearanceNode;
Material160: TMaterialNode;
IndexedLineSet161: TIndexedLineSetNode;
Coordinate162: TCoordinateNode;
HAnimJoint163: THAnimJointNode;
HAnimSegment164: THAnimSegmentNode;
Transform165: TTransformNode;
Shape166: TShapeNode;
Shape167: TShapeNode;
Appearance168: TAppearanceNode;
Material169: TMaterialNode;
IndexedLineSet170: TIndexedLineSetNode;
Coordinate171: TCoordinateNode;
HAnimJoint172: THAnimJointNode;
HAnimSegment173: THAnimSegmentNode;
Transform174: TTransformNode;
Shape175: TShapeNode;
Shape176: TShapeNode;
Appearance177: TAppearanceNode;
Material178: TMaterialNode;
IndexedLineSet179: TIndexedLineSetNode;
Coordinate180: TCoordinateNode;
HAnimJoint181: THAnimJointNode;
HAnimSegment182: THAnimSegmentNode;
Transform183: TTransformNode;
Shape184: TShapeNode;
Shape185: TShapeNode;
Appearance186: TAppearanceNode;
Material187: TMaterialNode;
IndexedLineSet188: TIndexedLineSetNode;
Coordinate189: TCoordinateNode;
HAnimJoint190: THAnimJointNode;
HAnimSegment191: THAnimSegmentNode;
Transform192: TTransformNode;
Shape193: TShapeNode;
Shape194: TShapeNode;
Appearance195: TAppearanceNode;
Material196: TMaterialNode;
IndexedLineSet197: TIndexedLineSetNode;
Coordinate198: TCoordinateNode;
HAnimJoint199: THAnimJointNode;
HAnimSegment200: THAnimSegmentNode;
Transform201: TTransformNode;
Shape202: TShapeNode;
Shape203: TShapeNode;
Appearance204: TAppearanceNode;
Material205: TMaterialNode;
IndexedLineSet206: TIndexedLineSetNode;
Coordinate207: TCoordinateNode;
Shape208: TShapeNode;
Appearance209: TAppearanceNode;
Material210: TMaterialNode;
IndexedLineSet211: TIndexedLineSetNode;
Coordinate212: TCoordinateNode;
HAnimJoint213: THAnimJointNode;
HAnimSegment214: THAnimSegmentNode;
Transform215: TTransformNode;
Shape216: TShapeNode;
Shape217: TShapeNode;
Appearance218: TAppearanceNode;
Material219: TMaterialNode;
IndexedLineSet220: TIndexedLineSetNode;
Coordinate221: TCoordinateNode;
HAnimJoint222: THAnimJointNode;
HAnimSegment223: THAnimSegmentNode;
Transform224: TTransformNode;
Shape225: TShapeNode;
Shape226: TShapeNode;
Appearance227: TAppearanceNode;
Material228: TMaterialNode;
IndexedLineSet229: TIndexedLineSetNode;
Coordinate230: TCoordinateNode;
HAnimJoint231: THAnimJointNode;
HAnimSegment232: THAnimSegmentNode;
Transform233: TTransformNode;
Shape234: TShapeNode;
Shape235: TShapeNode;
Appearance236: TAppearanceNode;
Material237: TMaterialNode;
IndexedLineSet238: TIndexedLineSetNode;
Coordinate239: TCoordinateNode;
HAnimJoint240: THAnimJointNode;
HAnimSegment241: THAnimSegmentNode;
Transform242: TTransformNode;
Shape243: TShapeNode;
Shape244: TShapeNode;
Appearance245: TAppearanceNode;
Material246: TMaterialNode;
IndexedLineSet247: TIndexedLineSetNode;
Coordinate248: TCoordinateNode;
HAnimJoint249: THAnimJointNode;
HAnimSegment250: THAnimSegmentNode;
Transform251: TTransformNode;
Shape252: TShapeNode;
Shape253: TShapeNode;
Appearance254: TAppearanceNode;
Material255: TMaterialNode;
IndexedLineSet256: TIndexedLineSetNode;
Coordinate257: TCoordinateNode;
HAnimJoint258: THAnimJointNode;
HAnimSegment259: THAnimSegmentNode;
Transform260: TTransformNode;
Shape261: TShapeNode;
Shape262: TShapeNode;
Appearance263: TAppearanceNode;
Material264: TMaterialNode;
IndexedLineSet265: TIndexedLineSetNode;
Coordinate266: TCoordinateNode;
HAnimJoint267: THAnimJointNode;
HAnimSegment268: THAnimSegmentNode;
Transform269: TTransformNode;
Shape270: TShapeNode;
Shape271: TShapeNode;
Appearance272: TAppearanceNode;
Material273: TMaterialNode;
IndexedLineSet274: TIndexedLineSetNode;
Coordinate275: TCoordinateNode;
HAnimJoint276: THAnimJointNode;
HAnimSegment277: THAnimSegmentNode;
Transform278: TTransformNode;
Shape279: TShapeNode;
Shape280: TShapeNode;
Appearance281: TAppearanceNode;
Material282: TMaterialNode;
IndexedLineSet283: TIndexedLineSetNode;
Coordinate284: TCoordinateNode;
HAnimJoint285: THAnimJointNode;
HAnimJoint286: THAnimJointNode;
HAnimJoint287: THAnimJointNode;
HAnimJoint288: THAnimJointNode;
HAnimJoint289: THAnimJointNode;
HAnimJoint290: THAnimJointNode;
HAnimJoint291: THAnimJointNode;
HAnimJoint292: THAnimJointNode;
HAnimJoint293: THAnimJointNode;
HAnimJoint294: THAnimJointNode;
HAnimJoint295: THAnimJointNode;
HAnimJoint296: THAnimJointNode;
HAnimJoint297: THAnimJointNode;
HAnimJoint298: THAnimJointNode;
HAnimJoint299: THAnimJointNode;
HAnimJoint300: THAnimJointNode;
HAnimJoint301: THAnimJointNode;
HAnimJoint302: THAnimJointNode;
HAnimJoint303: THAnimJointNode;
HAnimJoint304: THAnimJointNode;
HAnimJoint305: THAnimJointNode;
HAnimJoint306: THAnimJointNode;
HAnimJoint307: THAnimJointNode;
HAnimJoint308: THAnimJointNode;
HAnimJoint309: THAnimJointNode;
HAnimJoint310: THAnimJointNode;
HAnimJoint311: THAnimJointNode;
begin
X3D0 := TX3DRootNode.Create;
X3D0.Profile := 'Immersive';
X3D0.ForceVersion.Major := 4;
X3D0.ForceVersion.Minor := 0;
X3D0.Components['HAnim'] := 1;
X3D0.Meta['title'] := 'HAnimModelFootLeft.x3d';
X3D0.Meta['description'] := 'Left foot, using high-fidelity definitions for HAnim version 2.0';
X3D0.Meta['creator'] := 'Kwan-Hee YOO, Don Brutzman and Joe Williams';
X3D0.Meta['created'] := '26 January 2015';
X3D0.Meta['modified'] := '23 December 2021';
X3D0.Meta['warning'] := 'not yet to scale';
X3D0.Meta['warning'] := 'TODO will X3D HAnim component add a new level to support LOA-4 functionality?';
X3D0.Meta['info'] := 'TODO describe how to compute and apply offsets for center values whenever attaching this appendage to a body';
X3D0.Meta['reference'] := 'https://www.web3d.org/working-groups/humanoid-animation-HAnim';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#TheFeet';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#f-FootJoints';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#Hierarchy4';
X3D0.Meta['reference'] := 'https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-WD2/Part01/components/hanim.html';
X3D0.Meta['subject'] := 'X3D HAnim humanoid animation';
X3D0.Meta['TODO'] := 'Integrate and confirm Segment/Joint names, Viewpoints.';
X3D0.Meta['identifier'] := 'https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Characters/HAnimModelFootLeft.x3d';
X3D0.Meta['generator'] := 'X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit';
X3D0.Meta['license'] := '../license.html';
Group22 := TGroupNode.Create;
WorldInfo23 := TWorldInfoNode.Create;
WorldInfo23.Title := 'HAnimModelFootLeft.x3d';
{ .AddChildren }
Group22.AddChildren([WorldInfo23]);
HAnimHumanoid24 := THAnimHumanoidNode.Create;
HAnimHumanoid24.NameField := 'Foot_Left';
HAnimHumanoid24.Loa := 4;
HAnimHumanoid24.Version := '2.0';
{ original HAnimHumanoid info='"authorName=Kwan-Hee YOO, Don Brutzman and Joe Williams"' }
MetadataSet25 := TMetadataSetNode.Create;
MetadataSet25.NameField := 'HAnimHumanoid.info';
MetadataSet25.Reference := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/ObjectInterfaces.html#Humanoid';
MetadataString26 := TMetadataStringNode.Create;
MetadataString26.NameField := 'authorName';
MetadataString26.SetValue(['Kwan-Hee YOO, Don Brutzman and Joe Williams']);
{ .SetValue }
MetadataSet25.Value := MetadataString26;
{ .SetMetadata }
HAnimHumanoid24.Metadata := MetadataSet25;
HAnimJoint27 := THAnimJointNode.Create;
HAnimJoint27.NameField := 'humanoid_root';
HAnimJoint27.SetUlimit([0,0,0]);
HAnimJoint27.SetLlimit([0,0,0]);
{ Might consider putting a HAnimSegment here, but that doesn't help with re-use of this foot model }
HAnimJoint28 := THAnimJointNode.Create;
HAnimJoint28.NameField := 'l_talocrural';
HAnimJoint28.Description := 'connection joint of foot to leg above';
HAnimJoint28.SetUlimit([0,0,0]);
HAnimJoint28.SetLlimit([0,0,0]);
HAnimSegment29 := THAnimSegmentNode.Create;
HAnimSegment29.NameField := 'l_talus';
Transform30 := TTransformNode.Create;
Shape31 := TShapeNode.Create;
Sphere32 := TSphereNode.Create;
Sphere32.Radius := 0.025;
{ .SetGeometry }
Shape31.Geometry := Sphere32;
Appearance33 := TAppearanceNode.Create;
Material34 := TMaterialNode.Create;
Material34.DiffuseColor := Vector3(0,0,1);
{ .SetMaterial }
Appearance33.Material := Material34;
{ .SetAppearance }
Shape31.Appearance := Appearance33;
{ .AddChild }
Transform30.AddChildren([Shape31]);
{ .AddChildren }
HAnimSegment29.AddChildren([Transform30]);
Shape35 := TShapeNode.Create;
Appearance36 := TAppearanceNode.Create;
Material37 := TMaterialNode.Create;
Material37.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance36.Material := Material37;
{ .SetAppearance }
Shape35.Appearance := Appearance36;
IndexedLineSet38 := TIndexedLineSetNode.Create;
IndexedLineSet38.SetCoordIndex([0,1]);
Coordinate39 := TCoordinateNode.Create;
Coordinate39.SetPoint([Vector3(0,0,0),Vector3(0,-0.3,0)]);
{ .SetCoord }
IndexedLineSet38.Coord := Coordinate39;
{ .SetGeometry }
Shape35.Geometry := IndexedLineSet38;
{ .AddChildren }
HAnimSegment29.AddChildren([Shape35]);
Shape40 := TShapeNode.Create;
Appearance41 := TAppearanceNode.Create;
Material42 := TMaterialNode.Create;
Material42.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance41.Material := Material42;
{ .SetAppearance }
Shape40.Appearance := Appearance41;
IndexedLineSet43 := TIndexedLineSetNode.Create;
IndexedLineSet43.SetCoordIndex([0,1]);
Coordinate44 := TCoordinateNode.Create;
Coordinate44.SetPoint([Vector3(0,0,0),Vector3(0.2,0.3,0)]);
{ .SetCoord }
IndexedLineSet43.Coord := Coordinate44;
{ .SetGeometry }
Shape40.Geometry := IndexedLineSet43;
{ .AddChildren }
HAnimSegment29.AddChildren([Shape40]);
{ .AddChildren }
HAnimJoint28.AddChildren([HAnimSegment29]);
{ TCN }
HAnimJoint45 := THAnimJointNode.Create;
HAnimJoint45.NameField := 'l_talocalcaneonavicular';
HAnimJoint45.Center := Vector3(0,-0.3,0);
HAnimJoint45.SetUlimit([0,0,0]);
HAnimJoint45.SetLlimit([0,0,0]);
HAnimSegment46 := THAnimSegmentNode.Create;
HAnimSegment46.NameField := 'l_navicular';
Transform47 := TTransformNode.Create;
Transform47.Translation := Vector3(0,-0.3,0);
Shape48 := TShapeNode.Create;
Shape48 := Shape31;
{ .AddChild }
Transform47.AddChildren([Shape48]);
{ .AddChildren }
HAnimSegment46.AddChildren([Transform47]);
Shape49 := TShapeNode.Create;
Appearance50 := TAppearanceNode.Create;
Material51 := TMaterialNode.Create;
Material51.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance50.Material := Material51;
{ .SetAppearance }
Shape49.Appearance := Appearance50;
IndexedLineSet52 := TIndexedLineSetNode.Create;
IndexedLineSet52.SetCoordIndex([0,1]);
Coordinate53 := TCoordinateNode.Create;
Coordinate53.SetPoint([Vector3(0,-0.3,0),Vector3(-0.1,-0.45,0)]);
{ .SetCoord }
IndexedLineSet52.Coord := Coordinate53;
{ .SetGeometry }
Shape49.Geometry := IndexedLineSet52;
{ .AddChildren }
HAnimSegment46.AddChildren([Shape49]);
Shape54 := TShapeNode.Create;
Appearance55 := TAppearanceNode.Create;
Material56 := TMaterialNode.Create;
Material56.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance55.Material := Material56;
{ .SetAppearance }
Shape54.Appearance := Appearance55;
IndexedLineSet57 := TIndexedLineSetNode.Create;
IndexedLineSet57.SetCoordIndex([0,1]);
Coordinate58 := TCoordinateNode.Create;
Coordinate58.SetPoint([Vector3(0,-0.3,0),Vector3(0,-0.45,0)]);
{ .SetCoord }
IndexedLineSet57.Coord := Coordinate58;
{ .SetGeometry }
Shape54.Geometry := IndexedLineSet57;
{ .AddChildren }
HAnimSegment46.AddChildren([Shape54]);
Shape59 := TShapeNode.Create;
Appearance60 := TAppearanceNode.Create;
Material61 := TMaterialNode.Create;
Material61.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance60.Material := Material61;
{ .SetAppearance }
Shape59.Appearance := Appearance60;
IndexedLineSet62 := TIndexedLineSetNode.Create;
IndexedLineSet62.SetCoordIndex([0,1]);
Coordinate63 := TCoordinateNode.Create;
Coordinate63.SetPoint([Vector3(0,-0.3,0),Vector3(0.1,-0.4,0)]);
{ .SetCoord }
IndexedLineSet62.Coord := Coordinate63;
{ .SetGeometry }
Shape59.Geometry := IndexedLineSet62;
{ .AddChildren }
HAnimSegment46.AddChildren([Shape59]);
{ .AddChildren }
HAnimJoint45.AddChildren([HAnimSegment46]);
{ CN1 }
HAnimJoint64 := THAnimJointNode.Create;
HAnimJoint64.NameField := 'l_cuneonavicular_1';
HAnimJoint64.Center := Vector3(-0.1,-0.45,0);
HAnimJoint64.SetUlimit([0,0,0]);
HAnimJoint64.SetLlimit([0,0,0]);
HAnimSegment65 := THAnimSegmentNode.Create;
HAnimSegment65.NameField := 'l_cuneiform_1';
Transform66 := TTransformNode.Create;
Transform66.Translation := Vector3(-0.1,-0.45,0);
Shape67 := TShapeNode.Create;
Shape67 := Shape31;
{ .AddChild }
Transform66.AddChildren([Shape67]);
{ .AddChildren }
HAnimSegment65.AddChildren([Transform66]);
Shape68 := TShapeNode.Create;
Appearance69 := TAppearanceNode.Create;
Material70 := TMaterialNode.Create;
Material70.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance69.Material := Material70;
{ .SetAppearance }
Shape68.Appearance := Appearance69;
IndexedLineSet71 := TIndexedLineSetNode.Create;
IndexedLineSet71.SetCoordIndex([0,1]);
Coordinate72 := TCoordinateNode.Create;
Coordinate72.SetPoint([Vector3(-0.1,-0.45,0),Vector3(-0.1,-0.6,0)]);
{ .SetCoord }
IndexedLineSet71.Coord := Coordinate72;
{ .SetGeometry }
Shape68.Geometry := IndexedLineSet71;
{ .AddChildren }
HAnimSegment65.AddChildren([Shape68]);
{ .AddChildren }
HAnimJoint64.AddChildren([HAnimSegment65]);
HAnimJoint73 := THAnimJointNode.Create;
HAnimJoint73.NameField := 'l_tarsometatarsal_1';
HAnimJoint73.Center := Vector3(-0.1,-0.6,0);
HAnimJoint73.SetUlimit([0,0,0]);
HAnimJoint73.SetLlimit([0,0,0]);
HAnimSegment74 := THAnimSegmentNode.Create;
HAnimSegment74.NameField := 'l_metatarsal_1';
Transform75 := TTransformNode.Create;
Transform75.Translation := Vector3(-0.1,-0.6,0);
Shape76 := TShapeNode.Create;
Shape76 := Shape31;
{ .AddChild }
Transform75.AddChildren([Shape76]);
{ .AddChildren }
HAnimSegment74.AddChildren([Transform75]);
Shape77 := TShapeNode.Create;
Appearance78 := TAppearanceNode.Create;
Material79 := TMaterialNode.Create;
Material79.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance78.Material := Material79;
{ .SetAppearance }
Shape77.Appearance := Appearance78;
IndexedLineSet80 := TIndexedLineSetNode.Create;
IndexedLineSet80.SetCoordIndex([0,1]);
Coordinate81 := TCoordinateNode.Create;
Coordinate81.SetPoint([Vector3(-0.1,-0.6,0),Vector3(-0.1,-0.9,0)]);
{ .SetCoord }
IndexedLineSet80.Coord := Coordinate81;
{ .SetGeometry }
Shape77.Geometry := IndexedLineSet80;
{ .AddChildren }
HAnimSegment74.AddChildren([Shape77]);
{ .AddChildren }
HAnimJoint73.AddChildren([HAnimSegment74]);
HAnimJoint82 := THAnimJointNode.Create;
HAnimJoint82.NameField := 'l_metatarsophalangeal_1';
HAnimJoint82.Center := Vector3(-0.1,-0.9,0);
HAnimJoint82.SetUlimit([0,0,0]);
HAnimJoint82.SetLlimit([0,0,0]);
HAnimSegment83 := THAnimSegmentNode.Create;
HAnimSegment83.NameField := 'l_tarsal_proximal_phalanx_1';
Transform84 := TTransformNode.Create;
Transform84.Translation := Vector3(-0.1,-0.9,0);
Shape85 := TShapeNode.Create;
Shape85 := Shape31;
{ .AddChild }
Transform84.AddChildren([Shape85]);
{ .AddChildren }
HAnimSegment83.AddChildren([Transform84]);
Shape86 := TShapeNode.Create;
Appearance87 := TAppearanceNode.Create;
Material88 := TMaterialNode.Create;
Material88.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance87.Material := Material88;
{ .SetAppearance }
Shape86.Appearance := Appearance87;
IndexedLineSet89 := TIndexedLineSetNode.Create;
IndexedLineSet89.SetCoordIndex([0,1]);
Coordinate90 := TCoordinateNode.Create;
Coordinate90.SetPoint([Vector3(-0.1,-0.9,0),Vector3(-0.1,-1.05,0)]);
{ .SetCoord }
IndexedLineSet89.Coord := Coordinate90;
{ .SetGeometry }
Shape86.Geometry := IndexedLineSet89;
{ .AddChildren }
HAnimSegment83.AddChildren([Shape86]);
{ .AddChildren }
HAnimJoint82.AddChildren([HAnimSegment83]);
HAnimJoint91 := THAnimJointNode.Create;
HAnimJoint91.NameField := 'l_tarsal_interphalangeal_1';
HAnimJoint91.Center := Vector3(-0.1,-1.05,0);
HAnimJoint91.SetUlimit([0,0,0]);
HAnimJoint91.SetLlimit([0,0,0]);
HAnimSegment92 := THAnimSegmentNode.Create;
HAnimSegment92.NameField := 'l_tarsal_distal_phalanx_1';
Transform93 := TTransformNode.Create;
Transform93.Translation := Vector3(-0.1,-1.05,0);
Shape94 := TShapeNode.Create;
Shape94 := Shape31;
{ .AddChild }
Transform93.AddChildren([Shape94]);
{ .AddChildren }
HAnimSegment92.AddChildren([Transform93]);
Shape95 := TShapeNode.Create;
Appearance96 := TAppearanceNode.Create;
Material97 := TMaterialNode.Create;
Material97.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance96.Material := Material97;
{ .SetAppearance }
Shape95.Appearance := Appearance96;
IndexedLineSet98 := TIndexedLineSetNode.Create;
IndexedLineSet98.SetCoordIndex([0,1]);
Coordinate99 := TCoordinateNode.Create;
Coordinate99.SetPoint([Vector3(-0.1,-1.05,0),Vector3(-0.1,-1.1,0)]);
{ .SetCoord }
IndexedLineSet98.Coord := Coordinate99;
{ .SetGeometry }
Shape95.Geometry := IndexedLineSet98;
{ .AddChildren }
HAnimSegment92.AddChildren([Shape95]);
{ .AddChildren }
HAnimJoint91.AddChildren([HAnimSegment92]);
{ .AddChildren }
HAnimJoint82.AddChildren([HAnimJoint91]);
{ .AddChildren }
HAnimJoint73.AddChildren([HAnimJoint82]);
{ .AddChildren }
HAnimJoint64.AddChildren([HAnimJoint73]);
{ .AddChildren }
HAnimJoint45.AddChildren([HAnimJoint64]);
{ CN2 }
HAnimJoint100 := THAnimJointNode.Create;
HAnimJoint100.NameField := 'l_cuneonavicular_2';
HAnimJoint100.Center := Vector3(0,-0.45,0);
HAnimJoint100.SetUlimit([0,0,0]);
HAnimJoint100.SetLlimit([0,0,0]);
HAnimSegment101 := THAnimSegmentNode.Create;
HAnimSegment101.NameField := 'l_cuneiform_2';
Transform102 := TTransformNode.Create;
Transform102.Translation := Vector3(0,-0.45,0);
Shape103 := TShapeNode.Create;
Shape103 := Shape31;
{ .AddChild }
Transform102.AddChildren([Shape103]);
{ .AddChildren }
HAnimSegment101.AddChildren([Transform102]);
Shape104 := TShapeNode.Create;
Appearance105 := TAppearanceNode.Create;
Material106 := TMaterialNode.Create;
Material106.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance105.Material := Material106;
{ .SetAppearance }
Shape104.Appearance := Appearance105;
IndexedLineSet107 := TIndexedLineSetNode.Create;
IndexedLineSet107.SetCoordIndex([0,1]);
Coordinate108 := TCoordinateNode.Create;
Coordinate108.SetPoint([Vector3(0,-0.45,0),Vector3(0.05,-0.6,0)]);
{ .SetCoord }
IndexedLineSet107.Coord := Coordinate108;
{ .SetGeometry }
Shape104.Geometry := IndexedLineSet107;
{ .AddChildren }
HAnimSegment101.AddChildren([Shape104]);
{ .AddChildren }
HAnimJoint100.AddChildren([HAnimSegment101]);
HAnimJoint109 := THAnimJointNode.Create;
HAnimJoint109.NameField := 'l_tarsometatarsal_2';
HAnimJoint109.Center := Vector3(0.05,-0.6,0);
HAnimJoint109.SetUlimit([0,0,0]);
HAnimJoint109.SetLlimit([0,0,0]);
HAnimSegment110 := THAnimSegmentNode.Create;
HAnimSegment110.NameField := 'l_metatarsal_2';
Transform111 := TTransformNode.Create;
Transform111.Translation := Vector3(0.05,-0.6,0);
Shape112 := TShapeNode.Create;
Shape112 := Shape31;
{ .AddChild }
Transform111.AddChildren([Shape112]);
{ .AddChildren }
HAnimSegment110.AddChildren([Transform111]);
Shape113 := TShapeNode.Create;
Appearance114 := TAppearanceNode.Create;
Material115 := TMaterialNode.Create;
Material115.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance114.Material := Material115;
{ .SetAppearance }
Shape113.Appearance := Appearance114;
IndexedLineSet116 := TIndexedLineSetNode.Create;
IndexedLineSet116.SetCoordIndex([0,1]);
Coordinate117 := TCoordinateNode.Create;
Coordinate117.SetPoint([Vector3(0.05,-0.6,0),Vector3(0.05,-0.9,0)]);
{ .SetCoord }
IndexedLineSet116.Coord := Coordinate117;
{ .SetGeometry }
Shape113.Geometry := IndexedLineSet116;
{ .AddChildren }
HAnimSegment110.AddChildren([Shape113]);
{ .AddChildren }
HAnimJoint109.AddChildren([HAnimSegment110]);
HAnimJoint118 := THAnimJointNode.Create;
HAnimJoint118.NameField := 'l_metatarsophalangeal_2';
HAnimJoint118.Center := Vector3(0.05,-0.9,0);
HAnimJoint118.SetUlimit([0,0,0]);
HAnimJoint118.SetLlimit([0,0,0]);
HAnimSegment119 := THAnimSegmentNode.Create;
HAnimSegment119.NameField := 'l_tarsal_proximal_phalanx_2';
Transform120 := TTransformNode.Create;
Transform120.Translation := Vector3(0.05,-0.9,0);
Shape121 := TShapeNode.Create;
Shape121 := Shape31;
{ .AddChild }
Transform120.AddChildren([Shape121]);
{ .AddChildren }
HAnimSegment119.AddChildren([Transform120]);
Shape122 := TShapeNode.Create;
Appearance123 := TAppearanceNode.Create;
Material124 := TMaterialNode.Create;
Material124.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance123.Material := Material124;
{ .SetAppearance }
Shape122.Appearance := Appearance123;
IndexedLineSet125 := TIndexedLineSetNode.Create;
IndexedLineSet125.SetCoordIndex([0,1]);
Coordinate126 := TCoordinateNode.Create;
Coordinate126.SetPoint([Vector3(0.05,-0.9,0),Vector3(0.05,-1.05,0)]);
{ .SetCoord }
IndexedLineSet125.Coord := Coordinate126;
{ .SetGeometry }
Shape122.Geometry := IndexedLineSet125;
{ .AddChildren }
HAnimSegment119.AddChildren([Shape122]);
{ .AddChildren }
HAnimJoint118.AddChildren([HAnimSegment119]);
HAnimJoint127 := THAnimJointNode.Create;
HAnimJoint127.NameField := 'l_tarsal_proximal_interphalangeal_2';
HAnimJoint127.Center := Vector3(0.05,-1.05,0);
HAnimJoint127.SetUlimit([0,0,0]);
HAnimJoint127.SetLlimit([0,0,0]);
HAnimSegment128 := THAnimSegmentNode.Create;
HAnimSegment128.NameField := 'l_tarsal_middle_phalanx_2';
Transform129 := TTransformNode.Create;
Transform129.Translation := Vector3(0.05,-1.05,0);
Shape130 := TShapeNode.Create;
Shape130 := Shape31;
{ .AddChild }
Transform129.AddChildren([Shape130]);
{ .AddChildren }
HAnimSegment128.AddChildren([Transform129]);
Shape131 := TShapeNode.Create;
Appearance132 := TAppearanceNode.Create;
Material133 := TMaterialNode.Create;
Material133.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance132.Material := Material133;
{ .SetAppearance }
Shape131.Appearance := Appearance132;
IndexedLineSet134 := TIndexedLineSetNode.Create;
IndexedLineSet134.SetCoordIndex([0,1]);
Coordinate135 := TCoordinateNode.Create;
Coordinate135.SetPoint([Vector3(0.05,-1.05,0),Vector3(0.05,-1.12,0)]);
{ .SetCoord }
IndexedLineSet134.Coord := Coordinate135;
{ .SetGeometry }
Shape131.Geometry := IndexedLineSet134;
{ .AddChildren }
HAnimSegment128.AddChildren([Shape131]);
{ .AddChildren }
HAnimJoint127.AddChildren([HAnimSegment128]);
HAnimJoint136 := THAnimJointNode.Create;
HAnimJoint136.NameField := 'l_tarsal_distal_interphalangeal_2';
HAnimJoint136.Center := Vector3(0.05,-1.12,0);
HAnimJoint136.SetUlimit([0,0,0]);
HAnimJoint136.SetLlimit([0,0,0]);
HAnimSegment137 := THAnimSegmentNode.Create;
HAnimSegment137.NameField := 'l_tarsal_distal_phalanx_2';
Transform138 := TTransformNode.Create;
Transform138.Translation := Vector3(0.05,-1.12,0);
Shape139 := TShapeNode.Create;
Shape139 := Shape31;
{ .AddChild }
Transform138.AddChildren([Shape139]);
{ .AddChildren }
HAnimSegment137.AddChildren([Transform138]);
Shape140 := TShapeNode.Create;
Appearance141 := TAppearanceNode.Create;
Material142 := TMaterialNode.Create;
Material142.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance141.Material := Material142;
{ .SetAppearance }
Shape140.Appearance := Appearance141;
IndexedLineSet143 := TIndexedLineSetNode.Create;
IndexedLineSet143.SetCoordIndex([0,1]);
Coordinate144 := TCoordinateNode.Create;
Coordinate144.SetPoint([Vector3(0.05,-1.12,0),Vector3(0.05,-1.16,0)]);
{ .SetCoord }
IndexedLineSet143.Coord := Coordinate144;
{ .SetGeometry }
Shape140.Geometry := IndexedLineSet143;
{ .AddChildren }
HAnimSegment137.AddChildren([Shape140]);
{ .AddChildren }
HAnimJoint136.AddChildren([HAnimSegment137]);
{ .AddChildren }
HAnimJoint127.AddChildren([HAnimJoint136]);
{ .AddChildren }
HAnimJoint118.AddChildren([HAnimJoint127]);
{ .AddChildren }
HAnimJoint109.AddChildren([HAnimJoint118]);
{ .AddChildren }
HAnimJoint100.AddChildren([HAnimJoint109]);
{ .AddChildren }
HAnimJoint45.AddChildren([HAnimJoint100]);
{ CN3 }
HAnimJoint145 := THAnimJointNode.Create;
HAnimJoint145.NameField := 'l_cuneonavicular_3';
HAnimJoint145.Center := Vector3(0.1,-0.4,0);
HAnimJoint145.SetUlimit([0,0,0]);
HAnimJoint145.SetLlimit([0,0,0]);
HAnimSegment146 := THAnimSegmentNode.Create;
HAnimSegment146.NameField := 'l_cuneiform_3';
Transform147 := TTransformNode.Create;
Transform147.Translation := Vector3(0.1,-0.4,0);
Shape148 := TShapeNode.Create;
Shape148 := Shape31;
{ .AddChild }
Transform147.AddChildren([Shape148]);
{ .AddChildren }
HAnimSegment146.AddChildren([Transform147]);
Shape149 := TShapeNode.Create;
Appearance150 := TAppearanceNode.Create;
Material151 := TMaterialNode.Create;
Material151.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance150.Material := Material151;
{ .SetAppearance }
Shape149.Appearance := Appearance150;
IndexedLineSet152 := TIndexedLineSetNode.Create;
IndexedLineSet152.SetCoordIndex([0,1]);
Coordinate153 := TCoordinateNode.Create;
Coordinate153.SetPoint([Vector3(0.1,-0.4,0),Vector3(0.15,-0.6,0)]);
{ .SetCoord }
IndexedLineSet152.Coord := Coordinate153;
{ .SetGeometry }
Shape149.Geometry := IndexedLineSet152;
{ .AddChildren }
HAnimSegment146.AddChildren([Shape149]);
{ .AddChildren }
HAnimJoint145.AddChildren([HAnimSegment146]);
HAnimJoint154 := THAnimJointNode.Create;
HAnimJoint154.NameField := 'l_tarsometatarsal_3';
HAnimJoint154.Center := Vector3(0.15,-0.6,0);
HAnimJoint154.SetUlimit([0,0,0]);
HAnimJoint154.SetLlimit([0,0,0]);
HAnimSegment155 := THAnimSegmentNode.Create;
HAnimSegment155.NameField := 'l_metatarsal_3';
Transform156 := TTransformNode.Create;
Transform156.Translation := Vector3(0.15,-0.6,0);
Shape157 := TShapeNode.Create;
Shape157 := Shape31;
{ .AddChild }
Transform156.AddChildren([Shape157]);
{ .AddChildren }
HAnimSegment155.AddChildren([Transform156]);
Shape158 := TShapeNode.Create;
Appearance159 := TAppearanceNode.Create;
Material160 := TMaterialNode.Create;
Material160.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance159.Material := Material160;
{ .SetAppearance }
Shape158.Appearance := Appearance159;
IndexedLineSet161 := TIndexedLineSetNode.Create;
IndexedLineSet161.SetCoordIndex([0,1]);
Coordinate162 := TCoordinateNode.Create;
Coordinate162.SetPoint([Vector3(0.15,-0.6,0),Vector3(0.15,-0.9,0)]);
{ .SetCoord }
IndexedLineSet161.Coord := Coordinate162;
{ .SetGeometry }
Shape158.Geometry := IndexedLineSet161;
{ .AddChildren }
HAnimSegment155.AddChildren([Shape158]);
{ .AddChildren }
HAnimJoint154.AddChildren([HAnimSegment155]);
HAnimJoint163 := THAnimJointNode.Create;
HAnimJoint163.NameField := 'l_metatarsophalangeal_3';
HAnimJoint163.Center := Vector3(0.15,-0.9,0);
HAnimJoint163.SetUlimit([0,0,0]);
HAnimJoint163.SetLlimit([0,0,0]);
HAnimSegment164 := THAnimSegmentNode.Create;
HAnimSegment164.NameField := 'l_tarsal_proximal_phalanx_3';
Transform165 := TTransformNode.Create;
Transform165.Translation := Vector3(0.15,-0.9,0);
Shape166 := TShapeNode.Create;
Shape166 := Shape31;
{ .AddChild }
Transform165.AddChildren([Shape166]);
{ .AddChildren }
HAnimSegment164.AddChildren([Transform165]);
Shape167 := TShapeNode.Create;
Appearance168 := TAppearanceNode.Create;
Material169 := TMaterialNode.Create;
Material169.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance168.Material := Material169;
{ .SetAppearance }
Shape167.Appearance := Appearance168;
IndexedLineSet170 := TIndexedLineSetNode.Create;
IndexedLineSet170.SetCoordIndex([0,1]);
Coordinate171 := TCoordinateNode.Create;
Coordinate171.SetPoint([Vector3(0.15,-0.9,0),Vector3(0.15,-1.05,0)]);
{ .SetCoord }
IndexedLineSet170.Coord := Coordinate171;
{ .SetGeometry }
Shape167.Geometry := IndexedLineSet170;
{ .AddChildren }
HAnimSegment164.AddChildren([Shape167]);
{ .AddChildren }
HAnimJoint163.AddChildren([HAnimSegment164]);
HAnimJoint172 := THAnimJointNode.Create;
HAnimJoint172.NameField := 'l_tarsal_proximal_interphalangeal_3';
HAnimJoint172.Center := Vector3(0.15,-1.05,0);
HAnimJoint172.SetUlimit([0,0,0]);
HAnimJoint172.SetLlimit([0,0,0]);
HAnimSegment173 := THAnimSegmentNode.Create;
HAnimSegment173.NameField := 'l_tarsal_middle_phalanx_3';
Transform174 := TTransformNode.Create;
Transform174.Translation := Vector3(0.15,-1.05,0);
Shape175 := TShapeNode.Create;
Shape175 := Shape31;
{ .AddChild }
Transform174.AddChildren([Shape175]);
{ .AddChildren }
HAnimSegment173.AddChildren([Transform174]);
Shape176 := TShapeNode.Create;
Appearance177 := TAppearanceNode.Create;
Material178 := TMaterialNode.Create;
Material178.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance177.Material := Material178;
{ .SetAppearance }
Shape176.Appearance := Appearance177;
IndexedLineSet179 := TIndexedLineSetNode.Create;
IndexedLineSet179.SetCoordIndex([0,1]);
Coordinate180 := TCoordinateNode.Create;
Coordinate180.SetPoint([Vector3(0.15,-1.05,0),Vector3(0.15,-1.13,0)]);
{ .SetCoord }
IndexedLineSet179.Coord := Coordinate180;
{ .SetGeometry }
Shape176.Geometry := IndexedLineSet179;
{ .AddChildren }
HAnimSegment173.AddChildren([Shape176]);
{ .AddChildren }
HAnimJoint172.AddChildren([HAnimSegment173]);
HAnimJoint181 := THAnimJointNode.Create;
HAnimJoint181.NameField := 'l_tarsal_distal_interphalangeal_3';
HAnimJoint181.Center := Vector3(0.15,-1.13,0);
HAnimJoint181.SetUlimit([0,0,0]);
HAnimJoint181.SetLlimit([0,0,0]);
HAnimSegment182 := THAnimSegmentNode.Create;
HAnimSegment182.NameField := 'l_tarsal_distal_phalanx_3';
Transform183 := TTransformNode.Create;
Transform183.Translation := Vector3(0.15,-1.13,0);
Shape184 := TShapeNode.Create;
Shape184 := Shape31;
{ .AddChild }
Transform183.AddChildren([Shape184]);
{ .AddChildren }
HAnimSegment182.AddChildren([Transform183]);
Shape185 := TShapeNode.Create;
Appearance186 := TAppearanceNode.Create;
Material187 := TMaterialNode.Create;
Material187.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance186.Material := Material187;
{ .SetAppearance }
Shape185.Appearance := Appearance186;
IndexedLineSet188 := TIndexedLineSetNode.Create;
IndexedLineSet188.SetCoordIndex([0,1]);
Coordinate189 := TCoordinateNode.Create;
Coordinate189.SetPoint([Vector3(0.15,-1.13,0),Vector3(0.15,-1.16,0)]);
{ .SetCoord }
IndexedLineSet188.Coord := Coordinate189;
{ .SetGeometry }
Shape185.Geometry := IndexedLineSet188;
{ .AddChildren }
HAnimSegment182.AddChildren([Shape185]);
{ .AddChildren }
HAnimJoint181.AddChildren([HAnimSegment182]);
{ .AddChildren }
HAnimJoint172.AddChildren([HAnimJoint181]);
{ .AddChildren }
HAnimJoint163.AddChildren([HAnimJoint172]);
{ .AddChildren }
HAnimJoint154.AddChildren([HAnimJoint163]);
{ .AddChildren }
HAnimJoint145.AddChildren([HAnimJoint154]);
{ .AddChildren }
HAnimJoint45.AddChildren([HAnimJoint145]);
{ .AddChildren }
HAnimJoint28.AddChildren([HAnimJoint45]);
{ CC }
HAnimJoint190 := THAnimJointNode.Create;
HAnimJoint190.NameField := 'l_calcaneocuboid';
HAnimJoint190.Center := Vector3(0.2,0.3,0);
HAnimJoint190.SetUlimit([0,0,0]);
HAnimJoint190.SetLlimit([0,0,0]);
HAnimSegment191 := THAnimSegmentNode.Create;
HAnimSegment191.NameField := 'l_calcaneus';
Transform192 := TTransformNode.Create;
Transform192.Translation := Vector3(0.2,0.3,0);
Shape193 := TShapeNode.Create;
Shape193 := Shape31;
{ .AddChild }
Transform192.AddChildren([Shape193]);
{ .AddChildren }
HAnimSegment191.AddChildren([Transform192]);
Shape194 := TShapeNode.Create;
Appearance195 := TAppearanceNode.Create;
Material196 := TMaterialNode.Create;
Material196.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance195.Material := Material196;
{ .SetAppearance }
Shape194.Appearance := Appearance195;
IndexedLineSet197 := TIndexedLineSetNode.Create;
IndexedLineSet197.SetCoordIndex([0,1]);
Coordinate198 := TCoordinateNode.Create;
Coordinate198.SetPoint([Vector3(0.2,0.3,0),Vector3(0.21,-0.3,0)]);
{ .SetCoord }
IndexedLineSet197.Coord := Coordinate198;
{ .SetGeometry }
Shape194.Geometry := IndexedLineSet197;
{ .AddChildren }
HAnimSegment191.AddChildren([Shape194]);
{ .AddChildren }
HAnimJoint190.AddChildren([HAnimSegment191]);
{ TT }
HAnimJoint199 := THAnimJointNode.Create;
HAnimJoint199.NameField := 'l_transversetarsal';
HAnimJoint199.Center := Vector3(0.21,-0.3,0);
HAnimJoint199.SetUlimit([0,0,0]);
HAnimJoint199.SetLlimit([0,0,0]);
HAnimSegment200 := THAnimSegmentNode.Create;
HAnimSegment200.NameField := 'l_cuboid';
Transform201 := TTransformNode.Create;
Transform201.Translation := Vector3(0.21,-0.3,0);
Shape202 := TShapeNode.Create;
Shape202 := Shape31;
{ .AddChild }
Transform201.AddChildren([Shape202]);
{ .AddChildren }
HAnimSegment200.AddChildren([Transform201]);
Shape203 := TShapeNode.Create;
Appearance204 := TAppearanceNode.Create;
Material205 := TMaterialNode.Create;
Material205.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance204.Material := Material205;
{ .SetAppearance }
Shape203.Appearance := Appearance204;
IndexedLineSet206 := TIndexedLineSetNode.Create;
IndexedLineSet206.SetCoordIndex([0,1]);
Coordinate207 := TCoordinateNode.Create;
Coordinate207.SetPoint([Vector3(0.21,-0.3,0),Vector3(0.25,-0.58,0)]);
{ .SetCoord }
IndexedLineSet206.Coord := Coordinate207;
{ .SetGeometry }
Shape203.Geometry := IndexedLineSet206;
{ .AddChildren }
HAnimSegment200.AddChildren([Shape203]);
Shape208 := TShapeNode.Create;
Appearance209 := TAppearanceNode.Create;
Material210 := TMaterialNode.Create;
Material210.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance209.Material := Material210;
{ .SetAppearance }
Shape208.Appearance := Appearance209;
IndexedLineSet211 := TIndexedLineSetNode.Create;
IndexedLineSet211.SetCoordIndex([0,1]);
Coordinate212 := TCoordinateNode.Create;
Coordinate212.SetPoint([Vector3(0.21,-0.3,0),Vector3(0.33,-0.52,0)]);
{ .SetCoord }
IndexedLineSet211.Coord := Coordinate212;
{ .SetGeometry }
Shape208.Geometry := IndexedLineSet211;
{ .AddChildren }
HAnimSegment200.AddChildren([Shape208]);
{ .AddChildren }
HAnimJoint199.AddChildren([HAnimSegment200]);
{ TMT4 }
HAnimJoint213 := THAnimJointNode.Create;
HAnimJoint213.NameField := 'l_tarsometatarsal_4';
HAnimJoint213.Center := Vector3(0.25,-0.58,0);
HAnimJoint213.SetUlimit([0,0,0]);
HAnimJoint213.SetLlimit([0,0,0]);
HAnimSegment214 := THAnimSegmentNode.Create;
HAnimSegment214.NameField := 'l_metatarsal_4';
Transform215 := TTransformNode.Create;
Transform215.Translation := Vector3(0.25,-0.58,0);
Shape216 := TShapeNode.Create;
Shape216 := Shape31;
{ .AddChild }
Transform215.AddChildren([Shape216]);
{ .AddChildren }
HAnimSegment214.AddChildren([Transform215]);
Shape217 := TShapeNode.Create;
Appearance218 := TAppearanceNode.Create;
Material219 := TMaterialNode.Create;
Material219.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance218.Material := Material219;
{ .SetAppearance }
Shape217.Appearance := Appearance218;
IndexedLineSet220 := TIndexedLineSetNode.Create;
IndexedLineSet220.SetCoordIndex([0,1]);
Coordinate221 := TCoordinateNode.Create;
Coordinate221.SetPoint([Vector3(0.25,-0.58,0),Vector3(0.25,-0.87,0)]);
{ .SetCoord }
IndexedLineSet220.Coord := Coordinate221;
{ .SetGeometry }
Shape217.Geometry := IndexedLineSet220;
{ .AddChildren }
HAnimSegment214.AddChildren([Shape217]);
{ .AddChildren }
HAnimJoint213.AddChildren([HAnimSegment214]);
HAnimJoint222 := THAnimJointNode.Create;
HAnimJoint222.NameField := 'l_metatarsophalangeal_4';
HAnimJoint222.Center := Vector3(0.25,-0.87,0);
HAnimJoint222.SetUlimit([0,0,0]);
HAnimJoint222.SetLlimit([0,0,0]);
HAnimSegment223 := THAnimSegmentNode.Create;
HAnimSegment223.NameField := 'l_tarsal_proximal_phalanx_4';
Transform224 := TTransformNode.Create;
Transform224.Translation := Vector3(0.25,-0.87,0);
Shape225 := TShapeNode.Create;
Shape225 := Shape31;
{ .AddChild }
Transform224.AddChildren([Shape225]);
{ .AddChildren }
HAnimSegment223.AddChildren([Transform224]);
Shape226 := TShapeNode.Create;
Appearance227 := TAppearanceNode.Create;
Material228 := TMaterialNode.Create;
Material228.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance227.Material := Material228;
{ .SetAppearance }
Shape226.Appearance := Appearance227;
IndexedLineSet229 := TIndexedLineSetNode.Create;
IndexedLineSet229.SetCoordIndex([0,1]);
Coordinate230 := TCoordinateNode.Create;
Coordinate230.SetPoint([Vector3(0.25,-0.87,0),Vector3(0.25,-1,0)]);
{ .SetCoord }
IndexedLineSet229.Coord := Coordinate230;
{ .SetGeometry }
Shape226.Geometry := IndexedLineSet229;
{ .AddChildren }
HAnimSegment223.AddChildren([Shape226]);
{ .AddChildren }
HAnimJoint222.AddChildren([HAnimSegment223]);
HAnimJoint231 := THAnimJointNode.Create;
HAnimJoint231.NameField := 'l_tarsal_proximal_interphalangeal_4';
HAnimJoint231.Center := Vector3(0.25,-1,0);
HAnimJoint231.SetUlimit([0,0,0]);
HAnimJoint231.SetLlimit([0,0,0]);
HAnimSegment232 := THAnimSegmentNode.Create;
HAnimSegment232.NameField := 'l_tarsal_middle_phalanx_4';
Transform233 := TTransformNode.Create;
Transform233.Translation := Vector3(0.25,-1,0);
Shape234 := TShapeNode.Create;
Shape234 := Shape31;
{ .AddChild }
Transform233.AddChildren([Shape234]);
{ .AddChildren }
HAnimSegment232.AddChildren([Transform233]);
Shape235 := TShapeNode.Create;
Appearance236 := TAppearanceNode.Create;
Material237 := TMaterialNode.Create;
Material237.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance236.Material := Material237;
{ .SetAppearance }
Shape235.Appearance := Appearance236;
IndexedLineSet238 := TIndexedLineSetNode.Create;
IndexedLineSet238.SetCoordIndex([0,1]);
Coordinate239 := TCoordinateNode.Create;
Coordinate239.SetPoint([Vector3(0.25,-1,0),Vector3(0.25,-1.1,0)]);
{ .SetCoord }
IndexedLineSet238.Coord := Coordinate239;
{ .SetGeometry }
Shape235.Geometry := IndexedLineSet238;
{ .AddChildren }
HAnimSegment232.AddChildren([Shape235]);
{ .AddChildren }
HAnimJoint231.AddChildren([HAnimSegment232]);
HAnimJoint240 := THAnimJointNode.Create;
HAnimJoint240.NameField := 'l_tarsal_distal_interphalangeal_4';
HAnimJoint240.Center := Vector3(0.25,-1.1,0);
HAnimJoint240.SetUlimit([0,0,0]);
HAnimJoint240.SetLlimit([0,0,0]);
HAnimSegment241 := THAnimSegmentNode.Create;
HAnimSegment241.NameField := 'l_tarsal_distal_phalanx_4';
Transform242 := TTransformNode.Create;
Transform242.Translation := Vector3(0.25,-1.1,0);
Shape243 := TShapeNode.Create;
Shape243 := Shape31;
{ .AddChild }
Transform242.AddChildren([Shape243]);
{ .AddChildren }
HAnimSegment241.AddChildren([Transform242]);
Shape244 := TShapeNode.Create;
Appearance245 := TAppearanceNode.Create;
Material246 := TMaterialNode.Create;
Material246.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance245.Material := Material246;
{ .SetAppearance }
Shape244.Appearance := Appearance245;
IndexedLineSet247 := TIndexedLineSetNode.Create;
IndexedLineSet247.SetCoordIndex([0,1]);
Coordinate248 := TCoordinateNode.Create;
Coordinate248.SetPoint([Vector3(0.25,-1.1,0),Vector3(0.25,-1.15,0)]);
{ .SetCoord }
IndexedLineSet247.Coord := Coordinate248;
{ .SetGeometry }
Shape244.Geometry := IndexedLineSet247;
{ .AddChildren }
HAnimSegment241.AddChildren([Shape244]);
{ .AddChildren }
HAnimJoint240.AddChildren([HAnimSegment241]);
{ .AddChildren }
HAnimJoint231.AddChildren([HAnimJoint240]);
{ .AddChildren }
HAnimJoint222.AddChildren([HAnimJoint231]);
{ .AddChildren }
HAnimJoint213.AddChildren([HAnimJoint222]);
{ .AddChildren }
HAnimJoint199.AddChildren([HAnimJoint213]);
{ TMT5 }
HAnimJoint249 := THAnimJointNode.Create;
HAnimJoint249.NameField := 'l_tarsometatarsal_5';
HAnimJoint249.Center := Vector3(0.33,-0.52,0);
HAnimJoint249.SetUlimit([0,0,0]);
HAnimJoint249.SetLlimit([0,0,0]);
HAnimSegment250 := THAnimSegmentNode.Create;
HAnimSegment250.NameField := 'l_metatarsal_5';
Transform251 := TTransformNode.Create;
Transform251.Translation := Vector3(0.33,-0.52,0);
Shape252 := TShapeNode.Create;
Shape252 := Shape31;
{ .AddChild }
Transform251.AddChildren([Shape252]);
{ .AddChildren }
HAnimSegment250.AddChildren([Transform251]);
Shape253 := TShapeNode.Create;
Appearance254 := TAppearanceNode.Create;
Material255 := TMaterialNode.Create;
Material255.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance254.Material := Material255;
{ .SetAppearance }
Shape253.Appearance := Appearance254;
IndexedLineSet256 := TIndexedLineSetNode.Create;
IndexedLineSet256.SetCoordIndex([0,1]);
Coordinate257 := TCoordinateNode.Create;
Coordinate257.SetPoint([Vector3(0.33,-0.52,0),Vector3(0.34,-0.8,0)]);
{ .SetCoord }
IndexedLineSet256.Coord := Coordinate257;
{ .SetGeometry }
Shape253.Geometry := IndexedLineSet256;
{ .AddChildren }
HAnimSegment250.AddChildren([Shape253]);
{ .AddChildren }
HAnimJoint249.AddChildren([HAnimSegment250]);
HAnimJoint258 := THAnimJointNode.Create;
HAnimJoint258.NameField := 'l_metatarsophalangeal_5';
HAnimJoint258.Center := Vector3(0.34,-0.8,0);
HAnimJoint258.SetUlimit([0,0,0]);
HAnimJoint258.SetLlimit([0,0,0]);
HAnimSegment259 := THAnimSegmentNode.Create;
HAnimSegment259.NameField := 'l_tarsal_proximal_phalanx_5';
Transform260 := TTransformNode.Create;
Transform260.Translation := Vector3(0.34,-0.8,0);
Shape261 := TShapeNode.Create;
Shape261 := Shape31;
{ .AddChild }
Transform260.AddChildren([Shape261]);
{ .AddChildren }
HAnimSegment259.AddChildren([Transform260]);
Shape262 := TShapeNode.Create;
Appearance263 := TAppearanceNode.Create;
Material264 := TMaterialNode.Create;
Material264.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance263.Material := Material264;
{ .SetAppearance }
Shape262.Appearance := Appearance263;
IndexedLineSet265 := TIndexedLineSetNode.Create;
IndexedLineSet265.SetCoordIndex([0,1]);
Coordinate266 := TCoordinateNode.Create;
Coordinate266.SetPoint([Vector3(0.34,-0.8,0),Vector3(0.34,-0.95,0)]);
{ .SetCoord }
IndexedLineSet265.Coord := Coordinate266;
{ .SetGeometry }
Shape262.Geometry := IndexedLineSet265;
{ .AddChildren }
HAnimSegment259.AddChildren([Shape262]);
{ .AddChildren }
HAnimJoint258.AddChildren([HAnimSegment259]);
HAnimJoint267 := THAnimJointNode.Create;
HAnimJoint267.NameField := 'l_tarsal_proximal_interphalangeal_5';
HAnimJoint267.Center := Vector3(0.34,-0.95,0);
HAnimJoint267.SetUlimit([0,0,0]);
HAnimJoint267.SetLlimit([0,0,0]);
HAnimSegment268 := THAnimSegmentNode.Create;
HAnimSegment268.NameField := 'l_tarsal_middle_phalanx_5';
Transform269 := TTransformNode.Create;
Transform269.Translation := Vector3(0.34,-0.95,0);
Shape270 := TShapeNode.Create;
Shape270 := Shape31;
{ .AddChild }
Transform269.AddChildren([Shape270]);
{ .AddChildren }
HAnimSegment268.AddChildren([Transform269]);
Shape271 := TShapeNode.Create;
Appearance272 := TAppearanceNode.Create;
Material273 := TMaterialNode.Create;
Material273.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance272.Material := Material273;
{ .SetAppearance }
Shape271.Appearance := Appearance272;
IndexedLineSet274 := TIndexedLineSetNode.Create;
IndexedLineSet274.SetCoordIndex([0,1]);
Coordinate275 := TCoordinateNode.Create;
Coordinate275.SetPoint([Vector3(0.34,-0.95,0),Vector3(0.34,-1.05,0)]);
{ .SetCoord }
IndexedLineSet274.Coord := Coordinate275;
{ .SetGeometry }
Shape271.Geometry := IndexedLineSet274;
{ .AddChildren }
HAnimSegment268.AddChildren([Shape271]);
{ .AddChildren }
HAnimJoint267.AddChildren([HAnimSegment268]);
HAnimJoint276 := THAnimJointNode.Create;
HAnimJoint276.NameField := 'l_tarsal_distal_interphalangeal_5';
HAnimJoint276.Center := Vector3(0.34,-1.05,0);
HAnimJoint276.SetUlimit([0,0,0]);
HAnimJoint276.SetLlimit([0,0,0]);
HAnimSegment277 := THAnimSegmentNode.Create;
HAnimSegment277.NameField := 'l_tarsal_distal_phalanx_5';
Transform278 := TTransformNode.Create;
Transform278.Translation := Vector3(0.34,-1.05,0);
Shape279 := TShapeNode.Create;
Shape279 := Shape31;
{ .AddChild }
Transform278.AddChildren([Shape279]);
{ .AddChildren }
HAnimSegment277.AddChildren([Transform278]);
Shape280 := TShapeNode.Create;
Appearance281 := TAppearanceNode.Create;
Material282 := TMaterialNode.Create;
Material282.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance281.Material := Material282;
{ .SetAppearance }
Shape280.Appearance := Appearance281;
IndexedLineSet283 := TIndexedLineSetNode.Create;
IndexedLineSet283.SetCoordIndex([0,1]);
Coordinate284 := TCoordinateNode.Create;
Coordinate284.SetPoint([Vector3(0.34,-1.05,0),Vector3(0.34,-1.08,0)]);
{ .SetCoord }
IndexedLineSet283.Coord := Coordinate284;
{ .SetGeometry }
Shape280.Geometry := IndexedLineSet283;
{ .AddChildren }
HAnimSegment277.AddChildren([Shape280]);
{ .AddChildren }
HAnimJoint276.AddChildren([HAnimSegment277]);
{ .AddChildren }
HAnimJoint267.AddChildren([HAnimJoint276]);
{ .AddChildren }
HAnimJoint258.AddChildren([HAnimJoint267]);
{ .AddChildren }
HAnimJoint249.AddChildren([HAnimJoint258]);
{ .AddChildren }
HAnimJoint199.AddChildren([HAnimJoint249]);
{ .AddChildren }
HAnimJoint190.AddChildren([HAnimJoint199]);
{ .AddChildren }
HAnimJoint28.AddChildren([HAnimJoint190]);
{ .AddChildren }
HAnimJoint27.AddChildren([HAnimJoint28]);
{ .AddSkeleton }
HAnimHumanoid24.SetSkeleton([HAnimJoint27]);
HAnimJoint285 := THAnimJointNode.Create;
HAnimJoint285 := HAnimJoint27;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint285;
HAnimJoint286 := THAnimJointNode.Create;
HAnimJoint286 := HAnimJoint190;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint286;
HAnimJoint287 := THAnimJointNode.Create;
HAnimJoint287 := HAnimJoint64;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint287;
HAnimJoint288 := THAnimJointNode.Create;
HAnimJoint288 := HAnimJoint100;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint288;
HAnimJoint289 := THAnimJointNode.Create;
HAnimJoint289 := HAnimJoint145;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint289;
HAnimJoint290 := THAnimJointNode.Create;
HAnimJoint290 := HAnimJoint82;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint290;
HAnimJoint291 := THAnimJointNode.Create;
HAnimJoint291 := HAnimJoint118;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint291;
HAnimJoint292 := THAnimJointNode.Create;
HAnimJoint292 := HAnimJoint163;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint292;
HAnimJoint293 := THAnimJointNode.Create;
HAnimJoint293 := HAnimJoint222;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint293;
HAnimJoint294 := THAnimJointNode.Create;
HAnimJoint294 := HAnimJoint258;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint294;
HAnimJoint295 := THAnimJointNode.Create;
HAnimJoint295 := HAnimJoint45;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint295;
HAnimJoint296 := THAnimJointNode.Create;
HAnimJoint296 := HAnimJoint28;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint296;
HAnimJoint297 := THAnimJointNode.Create;
HAnimJoint297 := HAnimJoint136;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint297;
HAnimJoint298 := THAnimJointNode.Create;
HAnimJoint298 := HAnimJoint181;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint298;
HAnimJoint299 := THAnimJointNode.Create;
HAnimJoint299 := HAnimJoint240;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint299;
HAnimJoint300 := THAnimJointNode.Create;
HAnimJoint300 := HAnimJoint276;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint300;
HAnimJoint301 := THAnimJointNode.Create;
HAnimJoint301 := HAnimJoint91;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint301;
HAnimJoint302 := THAnimJointNode.Create;
HAnimJoint302 := HAnimJoint127;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint302;
HAnimJoint303 := THAnimJointNode.Create;
HAnimJoint303 := HAnimJoint172;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint303;
HAnimJoint304 := THAnimJointNode.Create;
HAnimJoint304 := HAnimJoint231;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint304;
HAnimJoint305 := THAnimJointNode.Create;
HAnimJoint305 := HAnimJoint267;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint305;
HAnimJoint306 := THAnimJointNode.Create;
HAnimJoint306 := HAnimJoint73;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint306;
HAnimJoint307 := THAnimJointNode.Create;
HAnimJoint307 := HAnimJoint109;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint307;
HAnimJoint308 := THAnimJointNode.Create;
HAnimJoint308 := HAnimJoint154;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint308;
HAnimJoint309 := THAnimJointNode.Create;
HAnimJoint309 := HAnimJoint213;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint309;
HAnimJoint310 := THAnimJointNode.Create;
HAnimJoint310 := HAnimJoint249;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint310;
HAnimJoint311 := THAnimJointNode.Create;
HAnimJoint311 := HAnimJoint199;
{ .AddJoints }
HAnimHumanoid24.Joints := HAnimJoint311;
{ .AddChildren }
Group22.AddChildren([HAnimHumanoid24]);
{ .AddGroup }
X3D0.AddChildren([Group22]);
Result := X3D0;
end;
