function HAnimPosePrototype: TX3DRootNode;
var
X3D0: TX3DRootNode;
Group42: TGroupNode;
WorldInfo43: TWorldInfoNode;
Background44: TBackgroundNode;
NavigationInfo45: TNavigationInfoNode;
Group46: TGroupNode;
Inline47: TInlineNode;
IMPORT48: TIMPORTNode;
LoadSensor49: TLoadSensorNode;
Inline50: TInlineNode;
ProtoDeclare51: TProtoDeclareNode;
ProtoInterface52: TProtoInterfaceNode;
field53: TfieldNode;
field54: TfieldNode;
field55: TfieldNode;
field56: TfieldNode;
field57: TfieldNode;
field58: TfieldNode;
field59: TfieldNode;
field60: TfieldNode;
field61: TfieldNode;
field62: TfieldNode;
field63: TfieldNode;
field64: TfieldNode;
field65: TfieldNode;
field66: TfieldNode;
field67: TfieldNode;
ProtoBody68: TProtoBodyNode;
TimeSensor69: TTimeSensorNode;
IS70: TISNode;
connect71: TconnectNode;
connect72: TconnectNode;
connect73: TconnectNode;
connect74: TconnectNode;
connect75: TconnectNode;
TimeSensor76: TTimeSensorNode;
IS77: TISNode;
connect78: TconnectNode;
connect79: TconnectNode;
connect80: TconnectNode;
Group81: TGroupNode;
Group82: TGroupNode;
Script83: TScriptNode;
field84: TfieldNode;
field85: TfieldNode;
field86: TfieldNode;
field87: TfieldNode;
field88: TfieldNode;
field89: TfieldNode;
field90: TfieldNode;
field91: TfieldNode;
field92: TfieldNode;
field93: TfieldNode;
field94: TfieldNode;
field95: TfieldNode;
field96: TfieldNode;
field97: TfieldNode;
field98: TfieldNode;
field99: TfieldNode;
IS100: TISNode;
connect101: TconnectNode;
connect102: TconnectNode;
connect103: TconnectNode;
connect104: TconnectNode;
connect105: TconnectNode;
connect106: TconnectNode;
connect107: TconnectNode;
connect108: TconnectNode;
connect109: TconnectNode;
connect110: TconnectNode;
connect111: TconnectNode;
connect112: TconnectNode;
connect113: TconnectNode;
Viewpoint114: TViewpointNode;
ProtoInstance115: TProtoInstanceNode;
fieldValue116: TfieldValueNode;
fieldValue117: TfieldValueNode;
fieldValue118: TfieldValueNode;
HAnimHumanoid119: THAnimHumanoidNode;
fieldValue120: TfieldValueNode;
fieldValue121: TfieldValueNode;
fieldValue122: TfieldValueNode;
HAnimJoint123: THAnimJointNode;
HAnimJoint124: THAnimJointNode;
fieldValue125: TfieldValueNode;
ProtoInstance126: TProtoInstanceNode;
fieldValue127: TfieldValueNode;
fieldValue128: TfieldValueNode;
fieldValue129: TfieldValueNode;
HAnimHumanoid130: THAnimHumanoidNode;
fieldValue131: TfieldValueNode;
fieldValue132: TfieldValueNode;
fieldValue133: TfieldValueNode;
HAnimJoint134: THAnimJointNode;
HAnimJoint135: THAnimJointNode;
fieldValue136: TfieldValueNode;
fieldValue137: TfieldValueNode;
ProtoInstance138: TProtoInstanceNode;
fieldValue139: TfieldValueNode;
fieldValue140: TfieldValueNode;
fieldValue141: TfieldValueNode;
HAnimHumanoid142: THAnimHumanoidNode;
fieldValue143: TfieldValueNode;
fieldValue144: TfieldValueNode;
fieldValue145: TfieldValueNode;
HAnimJoint146: THAnimJointNode;
HAnimJoint147: THAnimJointNode;
HAnimJoint148: THAnimJointNode;
HAnimJoint149: THAnimJointNode;
HAnimJoint150: THAnimJointNode;
HAnimJoint151: THAnimJointNode;
HAnimJoint152: THAnimJointNode;
HAnimJoint153: THAnimJointNode;
HAnimJoint154: THAnimJointNode;
HAnimJoint155: THAnimJointNode;
HAnimJoint156: THAnimJointNode;
HAnimJoint157: THAnimJointNode;
HAnimJoint158: THAnimJointNode;
HAnimJoint159: THAnimJointNode;
HAnimJoint160: THAnimJointNode;
HAnimJoint161: THAnimJointNode;
fieldValue162: TfieldValueNode;
fieldValue163: TfieldValueNode;
ProtoInstance164: TProtoInstanceNode;
fieldValue165: TfieldValueNode;
fieldValue166: TfieldValueNode;
fieldValue167: TfieldValueNode;
HAnimHumanoid168: THAnimHumanoidNode;
fieldValue169: TfieldValueNode;
fieldValue170: TfieldValueNode;
fieldValue171: TfieldValueNode;
fieldValue172: TfieldValueNode;
fieldValue173: TfieldValueNode;
ProtoInstance174: TProtoInstanceNode;
fieldValue175: TfieldValueNode;
fieldValue176: TfieldValueNode;
fieldValue177: TfieldValueNode;
fieldValue178: TfieldValueNode;
fieldValue179: TfieldValueNode;
ProtoInstance180: TProtoInstanceNode;
fieldValue181: TfieldValueNode;
fieldValue182: TfieldValueNode;
fieldValue183: TfieldValueNode;
HAnimHumanoid184: THAnimHumanoidNode;
fieldValue185: TfieldValueNode;
fieldValue186: TfieldValueNode;
fieldValue187: TfieldValueNode;
HAnimJoint188: THAnimJointNode;
fieldValue189: TfieldValueNode;
fieldValue190: TfieldValueNode;
ProtoInstance191: TProtoInstanceNode;
fieldValue192: TfieldValueNode;
fieldValue193: TfieldValueNode;
fieldValue194: TfieldValueNode;
HAnimHumanoid195: THAnimHumanoidNode;
fieldValue196: TfieldValueNode;
fieldValue197: TfieldValueNode;
fieldValue198: TfieldValueNode;
HAnimJoint199: THAnimJointNode;
fieldValue200: TfieldValueNode;
fieldValue201: TfieldValueNode;
Group202: TGroupNode;
Transform203: TTransformNode;
Shape204: TShapeNode;
Text205: TTextNode;
FontStyle206: TFontStyleNode;
Appearance207: TAppearanceNode;
Material208: TMaterialNode;
Transform209: TTransformNode;
Shape210: TShapeNode;
Text211: TTextNode;
FontStyle212: TFontStyleNode;
Appearance213: TAppearanceNode;
Shape214: TShapeNode;
Appearance215: TAppearanceNode;
Material216: TMaterialNode;
Box217: TBoxNode;
TouchSensor218: TTouchSensorNode;
Transform220: TTransformNode;
Shape221: TShapeNode;
Text222: TTextNode;
FontStyle223: TFontStyleNode;
Appearance224: TAppearanceNode;
Shape225: TShapeNode;
Appearance226: TAppearanceNode;
Box227: TBoxNode;
TouchSensor228: TTouchSensorNode;
Transform230: TTransformNode;
Shape231: TShapeNode;
Text232: TTextNode;
FontStyle233: TFontStyleNode;
Appearance234: TAppearanceNode;
Shape235: TShapeNode;
Appearance236: TAppearanceNode;
Box237: TBoxNode;
TouchSensor238: TTouchSensorNode;
Transform240: TTransformNode;
Shape241: TShapeNode;
Text242: TTextNode;
FontStyle243: TFontStyleNode;
Appearance244: TAppearanceNode;
Shape245: TShapeNode;
Appearance246: TAppearanceNode;
Box247: TBoxNode;
TouchSensor248: TTouchSensorNode;
Transform250: TTransformNode;
Shape251: TShapeNode;
Text252: TTextNode;
FontStyle253: TFontStyleNode;
Appearance254: TAppearanceNode;
Shape255: TShapeNode;
Appearance256: TAppearanceNode;
Box257: TBoxNode;
TouchSensor258: TTouchSensorNode;
Transform260: TTransformNode;
Shape261: TShapeNode;
Text262: TTextNode;
FontStyle263: TFontStyleNode;
Appearance264: TAppearanceNode;
Shape265: TShapeNode;
Appearance266: TAppearanceNode;
Box267: TBoxNode;
TouchSensor268: TTouchSensorNode;
Transform270: TTransformNode;
Shape271: TShapeNode;
Text272: TTextNode;
FontStyle273: TFontStyleNode;
Appearance274: TAppearanceNode;
Material275: TMaterialNode;
Shape276: TShapeNode;
Appearance277: TAppearanceNode;
Box278: TBoxNode;
TouchSensor279: TTouchSensorNode;
TimeSensor280: TTimeSensorNode;
ScalarInterpolator281: TScalarInterpolatorNode;
Transform285: TTransformNode;
Shape286: TShapeNode;
Text287: TTextNode;
FontStyle288: TFontStyleNode;
Appearance289: TAppearanceNode;
Shape290: TShapeNode;
Appearance291: TAppearanceNode;
Box292: TBoxNode;
TouchSensor293: TTouchSensorNode;
Group295: TGroupNode;
begin
X3D0 := TX3DRootNode.Create;
X3D0.Profile := 'Full';
X3D0.ForceVersion.Major := 4;
X3D0.ForceVersion.Minor := 0;
X3D0.Meta['title'] := 'HAnimPosePrototype.x3d';
X3D0.Meta['description'] := 'Define an experimental new node to simply capture a single pose for an HAnimHumanoid model. Expected usage is to allow HAnimHumanoid to contain multiple Pose nodes which can be activated and composed.';
X3D0.Meta['info'] := 'This model also takes advantage of Inline/IMPORT capabilities (equivalent to USE node) and thus avoids fully copying a large, complex HAnimHumanoid model. Multiple HAnimHumanoid models have been tested satisfactorily, for HAnim version 1 (X3d 3) AND HAnim version 2 (X3D 4).';
X3D0.Meta['created'] := '2 October 2025';
X3D0.Meta['modified'] := '14 December 2025';
X3D0.Meta['creator'] := 'Don Brutzman';
X3D0.Meta['creator'] := 'Joe Williams';
X3D0.Meta['contributor'] := 'Holger Seelig for X_ITE, Sunrize on Windows, scripting guidance, and Inline IMPORT functionality as node-reference equivalent to USE';
X3D0.Meta['reference'] := 'HAnimPosePrototype.console.txt';
X3D0.Meta['MovingImage'] := 'demonstration video https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Poses/HAnimPosePrototypeDemoVideo.mp4';
X3D0.Meta['Image'] := 'HAnimPoseExampleTouchDown.png';
X3D0.Meta['Image'] := 'HAnimPoseExampleTouchDownFaceLeftAPose.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleBoxMan1.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleBoxMan2.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleJoeKick.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleJoeSkeletonSkinSite.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter01Jin.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter02Chul.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter03Hyun.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter04Young.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter05Ju.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter06Ga.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter07No.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter08Da.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter09Ru.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter10Mi.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter11Min.png';
X3D0.Meta['Image'] := 'images/HAnimPoseExampleKoreanCharacter12Sun.png';
X3D0.Meta['specificationSection'] := 'HAnim Architecture volume 1 version 2.1 draft, clause 6 Object interfaces, section 6.4 Pose';
X3D0.Meta['specificationUrl'] := 'https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19774/ISO-IEC19774-1/ISO-IEC19774-1v2.1/ISO-IEC19774-1v2.1-WD/Architecture/ObjectInterfaces.html#Pose';
X3D0.Meta['specificationSection'] := 'HAnim Architecture volume 1 version 2.1 draft, clause 4 Concepts, section 4.8.2 Modelling of human-like HAnim figures';
X3D0.Meta['specificationUrl'] := 'https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19774/ISO-IEC19774-1/ISO-IEC19774-1v2.1/ISO-IEC19774-1v2.1-WD/Architecture/concepts.html#ModellingHumanLikeHAnimFigures';
X3D0.Meta['specificationSection'] := 'HAnim Architecture volume 1 version 2.1 draft, clause 4 Concepts, section 4.8.3 Poses';
X3D0.Meta['specificationUrl'] := 'https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19774/ISO-IEC19774-1/ISO-IEC19774-1v2.1/ISO-IEC19774-1v2.1-WD/Architecture/concepts.html#Poses';
X3D0.Meta['reference'] := 'Direct scene manipulations with Javascript, https://doc.instantreality.org/tutorial/direct-scene-manipulations-with-javascript';
X3D0.Meta['reference'] := 'earlier version of this prototype: originals/HAnimPosePreliminary.x3d';
X3D0.Meta['generator'] := 'X3D-Edit 4.0, https://www.web3d.org/x3d/tools/X3D-Edit';
X3D0.Meta['generator'] := 'Sunrize X3D Editor V1.11.1, https://create3000.github.io/sunrize';
X3D0.Meta['identifier'] := 'https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Poses/HAnimPosePrototype.x3d';
X3D0.Meta['license'] := 'https://www.web3d.org/x3d/content/examples/license.html';
Group42 := TGroupNode.Create;
WorldInfo43 := TWorldInfoNode.Create;
WorldInfo43.SetInfo(['Design to illustrate a potential HAnimPose node']);
WorldInfo43.Title := 'HAnimPosePrototype.x3d';
{ .AddChildren }
Group42.AddChildren([WorldInfo43]);
Background44 := TBackgroundNode.Create;
Background44.SetSkyColor([Vector3(0.8,0.8,1)]);
{ .AddChildren }
Group42.AddChildren([Background44]);
NavigationInfo45 := TNavigationInfoNode.Create;
{ .AddChildren }
Group42.AddChildren([NavigationInfo45]);
Group46 := TGroupNode.Create;
{ Multiple HAnimHumanoid Inline/IMPORT models are available to support testing: Characters/ JinLOA1 JinLOA2 JinLOA3 JinLOA4 ../Skin/JoeKick ../Skin/JoeSkeletonSkinSite ../Skin/BoxMan1 ../Skin/BoxMan2 }
{ Also tested satisfactorily: KoreanCharacter01Jin KoreanCharacter02Chul KoreanCharacter03Hyun KoreanCharacter04Young KoreanCharacter05Ju KoreanCharacter06Ga KoreanCharacter07No KoreanCharacter08Da KoreanCharacter09Ru KoreanCharacter10Mi KoreanCharacter11Min KoreanCharacter12Sun }
Inline47 := TInlineNode.Create;
Inline47.Description := 'remote HAnimHumanoid for IMPORT';
Inline47.SetUrl(['../Skin/BoxMan2.x3d','https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Skin/BoxMan2.x3d']);
{ .AddChildren }
Group46.AddChildren([Inline47]);
{ Note that the following importedDEF must match the EXPORT name found in remote file }
IMPORT48 := TIMPORTNode.Create;
IMPORT48.AS := 'HumanoidImported';
IMPORT48.ImportedDEF := 'BoxMan2';
IMPORT48.InlineDEF := 'HumanoidInline';
{ .AddChildren }
Group46.AddChildren([IMPORT48]);
LoadSensor49 := TLoadSensorNode.Create;
LoadSensor49.TimeOut := 2;
Inline50 := TInlineNode.Create;
Inline50 := Inline47;
{ .AddChildren }
LoadSensor49.AddChildren([Inline50]);
{ .AddChildren }
Group46.AddChildren([LoadSensor49]);
{ .AddChildren }
Group42.AddChildren([Group46]);
ProtoDeclare51 := TProtoDeclareNode.Create;
ProtoDeclare51.NameField := 'HAnimPose';
ProtoDeclare51.Appinfo := 'Experimental node to assign joint values to a humanoid and assume a pose. Assumes that baseline HAnimHumanoid configuration must be I pose, which can be achieved by resetting every HAnimJoint to default values.';
ProtoInterface52 := TProtoInterfaceNode.Create;
field53 := TfieldNode.Create;
field53.NameField := 'parentHAnimHumanoid';
field53.AccessType := 'inputOutput';
field53.Appinfo := 'HAnimHumanoid for this Pose to act upon';
field53.Type := 'SFNode';
{ HAnimHumanoid initialization node goes here, this field is only used in the prototype implementation }
{ .AddField }
ProtoInterface52.Field := field53;
field54 := TfieldNode.Create;
field54.NameField := 'name';
field54.AccessType := 'inputOutput';
field54.Appinfo := 'name of this pose';
field54.Type := 'SFString';
field54.Value := 'newPoseName';
{ .AddField }
ProtoInterface52.Field := field54;
field55 := TfieldNode.Create;
field55.NameField := 'children';
field55.AccessType := 'inputOutput';
field55.Appinfo := 'joint values to apply to HAnimHumanoid';
field55.Type := 'MFNode';
{ initializating Joint nodes (if any) go here }
{ .AddField }
ProtoInterface52.Field := field55;
field56 := TfieldNode.Create;
field56.NameField := 'description';
field56.AccessType := 'inputOutput';
field56.Appinfo := 'explanation of purpose';
field56.Type := 'SFString';
{ .AddField }
ProtoInterface52.Field := field56;
field57 := TfieldNode.Create;
field57.NameField := 'enabled';
field57.AccessType := 'inputOutput';
field57.Appinfo := 'default value true';
field57.Type := 'SFBool';
field57.Value := 'true';
{ .AddField }
ProtoInterface52.Field := field57;
field58 := TfieldNode.Create;
field58.NameField := 'loa';
field58.AccessType := 'initializeOnly';
field58.Appinfo := 'default is no loa';
field58.Type := 'SFInt32';
field58.Value := '-1';
{ .AddField }
ProtoInterface52.Field := field58;
field59 := TfieldNode.Create;
field59.NameField := 'transitionDuration';
field59.AccessType := 'inputOutput';
field59.Appinfo := 'how many seconds to achieve the pose';
field59.Type := 'SFTime';
field59.Value := '0';
{ .AddField }
ProtoInterface52.Field := field59;
field60 := TfieldNode.Create;
field60.NameField := 'metadata';
field60.AccessType := 'inputOutput';
field60.Appinfo := 'single Metadata* node';
field60.Type := 'SFNode';
{ .AddField }
ProtoInterface52.Field := field60;
field61 := TfieldNode.Create;
field61.NameField := 'isActive';
field61.AccessType := 'outputOnly';
field61.Appinfo := 'event indicating when pose transition is active';
field61.Type := 'SFBool';
{ .AddField }
ProtoInterface52.Field := field61;
field62 := TfieldNode.Create;
field62.NameField := 'commencePose';
field62.AccessType := 'inputOnly';
field62.Appinfo := 'this event tells the HAnimPose node to fully transition, equivalent to set_fraction=1';
field62.Type := 'SFBool';
{ .AddField }
ProtoInterface52.Field := field62;
field63 := TfieldNode.Create;
field63.NameField := 'resetAllJoints';
field63.AccessType := 'inputOnly';
field63.Appinfo := 'reset the skeleton to I pose with all joints zeroed';
field63.Type := 'SFBool';
{ .AddField }
ProtoInterface52.Field := field63;
field64 := TfieldNode.Create;
field64.NameField := 'set_fraction';
field64.AccessType := 'inputOnly';
field64.Appinfo := 'allows transition to proceed incrementally from fraction [0..10';
field64.Type := 'SFFloat';
{ .AddField }
ProtoInterface52.Field := field64;
field65 := TfieldNode.Create;
field65.NameField := 'set_startTime';
field65.AccessType := 'inputOnly';
field65.Appinfo := 'starts the animation clock';
field65.Type := 'SFTime';
{ .AddField }
ProtoInterface52.Field := field65;
field66 := TfieldNode.Create;
field66.NameField := 'isLoaded';
field66.AccessType := 'inputOnly';
field66.Appinfo := 'possible notification from LoadSensor if using HAnimHumanoid Inline/IMPORT AS/USE';
field66.Type := 'SFBool';
{ .AddField }
ProtoInterface52.Field := field66;
field67 := TfieldNode.Create;
field67.NameField := 'traceEnabled';
field67.AccessType := 'inputOutput';
field67.Appinfo := 'debug trace to Browser output console this is a local prototype field';
field67.Type := 'SFBool';
field67.Value := 'true';
{ .AddField }
ProtoInterface52.Field := field67;
{ .SetProtoInterface }
ProtoDeclare51.ProtoInterface := ProtoInterface52;
ProtoBody68 := TProtoBodyNode.Create;
TimeSensor69 := TTimeSensorNode.Create;
TimeSensor69.Description := 'control timing of pose animation when triggered';
IS70 := TISNode.Create;
connect71 := TconnectNode.Create;
connect71.NodeField := 'enabled';
connect71.ProtoField := 'enabled';
{ .AddConnect }
IS70.Connect := connect71;
connect72 := TconnectNode.Create;
connect72.NodeField := 'cycleInterval';
connect72.ProtoField := 'transitionDuration';
{ .AddConnect }
IS70.Connect := connect72;
connect73 := TconnectNode.Create;
connect73.NodeField := 'isActive';
connect73.ProtoField := 'isActive';
{ .AddConnect }
IS70.Connect := connect73;
connect74 := TconnectNode.Create;
connect74.NodeField := 'startTime';
connect74.ProtoField := 'set_startTime';
{ .AddConnect }
IS70.Connect := connect74;
connect75 := TconnectNode.Create;
connect75.NodeField := 'metadata';
connect75.ProtoField := 'metadata';
{ .AddConnect }
IS70.Connect := connect75;
{ .SetIS }
TimeSensor69.IS := IS70;
{ .AddChildren }
ProtoBody68.AddChildren([TimeSensor69]);
TimeSensor76 := TTimeSensorNode.Create;
TimeSensor76.Description := 'control timing of skeleton reset to \"A\" pose when triggered';
IS77 := TISNode.Create;
connect78 := TconnectNode.Create;
connect78.NodeField := 'enabled';
connect78.ProtoField := 'enabled';
{ .AddConnect }
IS77.Connect := connect78;
connect79 := TconnectNode.Create;
connect79.NodeField := 'cycleInterval';
connect79.ProtoField := 'transitionDuration';
{ .AddConnect }
IS77.Connect := connect79;
connect80 := TconnectNode.Create;
connect80.NodeField := 'startTime';
connect80.ProtoField := 'set_startTime';
{ .AddConnect }
IS77.Connect := connect80;
{ no need to report isActive since that would be duplicative }
{ .SetIS }
TimeSensor76.IS := IS77;
{ .AddChildren }
ProtoBody68.AddChildren([TimeSensor76]);
Group81 := TGroupNode.Create;
{ interpolators generated by prototype script appear here at runtime }
{ .AddChildren }
ProtoBody68.AddChildren([Group81]);
Group82 := TGroupNode.Create;
{ interpolators generated by prototype script appear here at runtime }
{ .AddChildren }
ProtoBody68.AddChildren([Group82]);
Script83 := TScriptNode.Create;
Script83.DirectOutput := True;
Script83.SetUrl(['HAnimPosePrototypeScript.js','https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Poses/HAnimPosePrototypeScript.js']);
field84 := TfieldNode.Create;
field84.NameField := 'parentHAnimHumanoid';
field84.AccessType := 'inputOutput';
field84.Appinfo := 'Humanoid for this Pose to act upon';
field84.Type := 'SFNode';
{ initialization node (if any) goes here }
{ .AddField }
Script83.Field := field84;
field85 := TfieldNode.Create;
field85.NameField := 'name';
field85.AccessType := 'inputOutput';
field85.Appinfo := 'name of this pose';
field85.Type := 'SFString';
{ .AddField }
Script83.Field := field85;
field86 := TfieldNode.Create;
field86.NameField := 'loa';
field86.AccessType := 'initializeOnly';
field86.Appinfo := 'default is no loa';
field86.Type := 'SFInt32';
{ .AddField }
Script83.Field := field86;
field87 := TfieldNode.Create;
field87.NameField := 'description';
field87.AccessType := 'inputOutput';
field87.Appinfo := 'explanation of purpose';
field87.Type := 'SFString';
{ .AddField }
Script83.Field := field87;
field88 := TfieldNode.Create;
field88.NameField := 'enabled';
field88.AccessType := 'inputOutput';
field88.Appinfo := 'default value true';
field88.Type := 'SFBool';
{ .AddField }
Script83.Field := field88;
field89 := TfieldNode.Create;
field89.NameField := 'resetAllJoints';
field89.AccessType := 'inputOnly';
field89.Appinfo := 'reset the skeleton to I pose with all joints zeroed';
field89.Type := 'SFBool';
{ .AddField }
Script83.Field := field89;
field90 := TfieldNode.Create;
field90.NameField := 'children';
field90.AccessType := 'inputOutput';
field90.Appinfo := 'joint values to apply to HAnimHumanoid';
field90.Type := 'MFNode';
{ initializating Joint nodes (if any) go here }
{ .AddField }
Script83.Field := field90;
field91 := TfieldNode.Create;
field91.NameField := 'transitionDuration';
field91.AccessType := 'inputOutput';
field91.Appinfo := 'how many seconds to achieve the pose';
field91.Type := 'SFTime';
{ .AddField }
Script83.Field := field91;
field92 := TfieldNode.Create;
field92.NameField := 'commencePose';
field92.AccessType := 'inputOnly';
field92.Appinfo := 'this event tells the HAnimPose node to fully transition, equivalent to set_fraction=1';
field92.Type := 'SFBool';
{ .AddField }
Script83.Field := field92;
field93 := TfieldNode.Create;
field93.NameField := 'set_fraction';
field93.AccessType := 'inputOnly';
field93.Appinfo := 'allows transition to proceed incrementally from fraction [0..10';
field93.Type := 'SFFloat';
{ .AddField }
Script83.Field := field93;
field94 := TfieldNode.Create;
field94.NameField := 'set_startTime';
field94.AccessType := 'inputOnly';
field94.Appinfo := 'starts the animation clock';
field94.Type := 'SFTime';
{ .AddField }
Script83.Field := field94;
field95 := TfieldNode.Create;
field95.NameField := 'isLoaded';
field95.AccessType := 'inputOnly';
field95.Appinfo := 'possible notification from LoadSensor if using HAnimHumanoid Inline/IMPORT AS/USE';
field95.Type := 'SFBool';
{ .AddField }
Script83.Field := field95;
field96 := TfieldNode.Create;
field96.NameField := 'traceEnabled';
field96.AccessType := 'inputOutput';
field96.Appinfo := 'debug trace to Browser output console';
field96.Type := 'SFBool';
{ .AddField }
Script83.Field := field96;
field97 := TfieldNode.Create;
field97.NameField := 'numberPoseJoints';
field97.AccessType := 'initializeOnly';
field97.Appinfo := 'number of joints found in children field';
field97.Type := 'SFInt32';
field97.Value := '0';
{ .AddField }
Script83.Field := field97;
field98 := TfieldNode.Create;
field98.NameField := 'numberSkeletonJoints';
field98.AccessType := 'initializeOnly';
field98.Appinfo := 'number of joints found in Humanoid';
field98.Type := 'SFInt32';
field98.Value := '0';
{ .AddField }
Script83.Field := field98;
field99 := TfieldNode.Create;
field99.NameField := 'jointOrientationInterpolators';
field99.AccessType := 'initializeOnly';
field99.Appinfo := 'OrientationInterpolator node array matching number of children';
field99.Type := 'MFNode';
{ initializating Joint nodes (if any) go here }
{ .AddField }
Script83.Field := field99;
IS100 := TISNode.Create;
connect101 := TconnectNode.Create;
connect101.NodeField := 'parentHAnimHumanoid';
connect101.ProtoField := 'parentHAnimHumanoid';
{ .AddConnect }
IS100.Connect := connect101;
connect102 := TconnectNode.Create;
connect102.NodeField := 'name';
connect102.ProtoField := 'name';
{ .AddConnect }
IS100.Connect := connect102;
connect103 := TconnectNode.Create;
connect103.NodeField := 'loa';
connect103.ProtoField := 'loa';
{ .AddConnect }
IS100.Connect := connect103;
connect104 := TconnectNode.Create;
connect104.NodeField := 'description';
connect104.ProtoField := 'description';
{ .AddConnect }
IS100.Connect := connect104;
connect105 := TconnectNode.Create;
connect105.NodeField := 'enabled';
connect105.ProtoField := 'enabled';
{ .AddConnect }
IS100.Connect := connect105;
connect106 := TconnectNode.Create;
connect106.NodeField := 'resetAllJoints';
connect106.ProtoField := 'resetAllJoints';
{ .AddConnect }
IS100.Connect := connect106;
connect107 := TconnectNode.Create;
connect107.NodeField := 'children';
connect107.ProtoField := 'children';
{ .AddConnect }
IS100.Connect := connect107;
connect108 := TconnectNode.Create;
connect108.NodeField := 'transitionDuration';
connect108.ProtoField := 'transitionDuration';
{ .AddConnect }
IS100.Connect := connect108;
connect109 := TconnectNode.Create;
connect109.NodeField := 'commencePose';
connect109.ProtoField := 'commencePose';
{ .AddConnect }
IS100.Connect := connect109;
connect110 := TconnectNode.Create;
connect110.NodeField := 'set_fraction';
connect110.ProtoField := 'set_fraction';
{ .AddConnect }
IS100.Connect := connect110;
connect111 := TconnectNode.Create;
connect111.NodeField := 'set_startTime';
connect111.ProtoField := 'set_startTime';
{ .AddConnect }
IS100.Connect := connect111;
connect112 := TconnectNode.Create;
connect112.NodeField := 'isLoaded';
connect112.ProtoField := 'isLoaded';
{ .AddConnect }
IS100.Connect := connect112;
connect113 := TconnectNode.Create;
connect113.NodeField := 'traceEnabled';
connect113.ProtoField := 'traceEnabled';
{ .AddConnect }
IS100.Connect := connect113;
{ .SetIS }
Script83.IS := IS100;
{ .AddChildren }
ProtoBody68.AddChildren([Script83]);
{ .SetProtoBody }
ProtoDeclare51.ProtoBody := ProtoBody68;
{ .AddChildren }
Group42.AddChildren([ProtoDeclare51]);
Viewpoint114 := TViewpointNode.Create;
Viewpoint114.Description := 'HAnimPose for HumanoidInline IMPORT model';
Viewpoint114.Position := Vector3(0,1,4);
{ .AddChildren }
Group42.AddChildren([Viewpoint114]);
{ no longer required: including full model <HAnimHumanoid DEF='hanim_JinLOA1' loa='2' name='JinLOA1' scale='0.0225 0.0225 0.0225'> etc... }
ProtoInstance115 := TProtoInstanceNode.Create;
ProtoInstance115.NameField := 'HAnimPose';
fieldValue116 := TfieldValueNode.Create;
fieldValue116.NameField := 'name';
fieldValue116.Value := 'T';
{ .AddFieldValue }
ProtoInstance115.FieldValue := fieldValue116;
fieldValue117 := TfieldValueNode.Create;
fieldValue117.NameField := 'enabled';
fieldValue117.Value := 'true';
{ .AddFieldValue }
ProtoInstance115.FieldValue := fieldValue117;
fieldValue118 := TfieldValueNode.Create;
fieldValue118.NameField := 'parentHAnimHumanoid';
{ HumanoidImported for Inline/IMPORT (or else USE='hanim_JinLOA1' if copy of original HAnimHumanoid is embedded in this model) }
{ debug test case for incorrect node type: <HAnimJoint DEF="ErrorDiagnosticsTest" USE='HumanoidImported'/> }
HAnimHumanoid119 := THAnimHumanoidNode.Create;
HAnimHumanoid119 := HAnimHumanoid119;
{ .AddChildren }
fieldValue118.AddChildren([HAnimHumanoid119]);
{ .AddFieldValue }
ProtoInstance115.FieldValue := fieldValue118;
fieldValue120 := TfieldValueNode.Create;
fieldValue120.NameField := 'loa';
fieldValue120.Value := '1';
{ .AddFieldValue }
ProtoInstance115.FieldValue := fieldValue120;
fieldValue121 := TfieldValueNode.Create;
fieldValue121.NameField := 'description';
fieldValue121.Value := 'arms stretched outward and level similar to letter T';
{ .AddFieldValue }
ProtoInstance115.FieldValue := fieldValue121;
fieldValue122 := TfieldValueNode.Create;
fieldValue122.NameField := 'children';
HAnimJoint123 := THAnimJointNode.Create;
HAnimJoint123.NameField := 'l_shoulder';
HAnimJoint123.Description := 'left shoulder';
HAnimJoint123.Rotation := Vector4(0,0,1,1.57);
HAnimJoint123.SetUlimit([0,0,0]);
HAnimJoint123.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue122.AddChildren([HAnimJoint123]);
HAnimJoint124 := THAnimJointNode.Create;
HAnimJoint124.NameField := 'r_shoulder';
HAnimJoint124.Description := 'right shoulder';
HAnimJoint124.Rotation := Vector4(0,0,-1,1.57);
HAnimJoint124.SetUlimit([0,0,0]);
HAnimJoint124.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue122.AddChildren([HAnimJoint124]);
{ test case for illegal child triggers validation reports without problem: HAnimSegment DEF='TestCase' description='confirm type checking' name='specialTestCase'/ }
{ .AddFieldValue }
ProtoInstance115.FieldValue := fieldValue122;
fieldValue125 := TfieldValueNode.Create;
fieldValue125.NameField := 'transitionDuration';
fieldValue125.Value := '1.3';
{ .AddFieldValue }
ProtoInstance115.FieldValue := fieldValue125;
{ .AddChildren }
Group42.AddChildren([ProtoInstance115]);
ProtoInstance126 := TProtoInstanceNode.Create;
ProtoInstance126.NameField := 'HAnimPose';
fieldValue127 := TfieldValueNode.Create;
fieldValue127.NameField := 'name';
fieldValue127.Value := 'A';
{ .AddFieldValue }
ProtoInstance126.FieldValue := fieldValue127;
fieldValue128 := TfieldValueNode.Create;
fieldValue128.NameField := 'enabled';
fieldValue128.Value := 'true';
{ .AddFieldValue }
ProtoInstance126.FieldValue := fieldValue128;
fieldValue129 := TfieldValueNode.Create;
fieldValue129.NameField := 'parentHAnimHumanoid';
{ HumanoidImported for Inline/IMPORT (or else USE='hanim_JinLOA1' if copy of original HAnimHumanoid is embedded in this model) }
HAnimHumanoid130 := THAnimHumanoidNode.Create;
HAnimHumanoid130 := HAnimHumanoid119;
{ .AddChildren }
fieldValue129.AddChildren([HAnimHumanoid130]);
{ .AddFieldValue }
ProtoInstance126.FieldValue := fieldValue129;
fieldValue131 := TfieldValueNode.Create;
fieldValue131.NameField := 'loa';
fieldValue131.Value := '1';
{ .AddFieldValue }
ProtoInstance126.FieldValue := fieldValue131;
fieldValue132 := TfieldValueNode.Create;
fieldValue132.NameField := 'description';
fieldValue132.Value := 'arms stretched outward and downward similar to letter A';
{ .AddFieldValue }
ProtoInstance126.FieldValue := fieldValue132;
fieldValue133 := TfieldValueNode.Create;
fieldValue133.NameField := 'children';
HAnimJoint134 := THAnimJointNode.Create;
HAnimJoint134.NameField := 'l_shoulder';
HAnimJoint134.Description := 'left shoulder';
HAnimJoint134.Rotation := Vector4(0,0,1,0.5);
HAnimJoint134.SetUlimit([0,0,0]);
HAnimJoint134.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue133.AddChildren([HAnimJoint134]);
HAnimJoint135 := THAnimJointNode.Create;
HAnimJoint135.NameField := 'r_shoulder';
HAnimJoint135.Description := 'right shoulder';
HAnimJoint135.Rotation := Vector4(0,0,-1,0.5);
HAnimJoint135.SetUlimit([0,0,0]);
HAnimJoint135.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue133.AddChildren([HAnimJoint135]);
{ .AddFieldValue }
ProtoInstance126.FieldValue := fieldValue133;
fieldValue136 := TfieldValueNode.Create;
fieldValue136.NameField := 'transitionDuration';
fieldValue136.Value := '1.2';
{ .AddFieldValue }
ProtoInstance126.FieldValue := fieldValue136;
fieldValue137 := TfieldValueNode.Create;
fieldValue137.NameField := 'traceEnabled';
fieldValue137.Value := 'true';
{ .AddFieldValue }
ProtoInstance126.FieldValue := fieldValue137;
{ .AddChildren }
Group42.AddChildren([ProtoInstance126]);
ProtoInstance138 := TProtoInstanceNode.Create;
ProtoInstance138.NameField := 'HAnimPose';
{ thanks Joe }
fieldValue139 := TfieldValueNode.Create;
fieldValue139.NameField := 'name';
fieldValue139.Value := 'TouchDown';
{ .AddFieldValue }
ProtoInstance138.FieldValue := fieldValue139;
fieldValue140 := TfieldValueNode.Create;
fieldValue140.NameField := 'enabled';
fieldValue140.Value := 'true';
{ .AddFieldValue }
ProtoInstance138.FieldValue := fieldValue140;
fieldValue141 := TfieldValueNode.Create;
fieldValue141.NameField := 'parentHAnimHumanoid';
{ HumanoidImported for Inline/IMPORT (or else USE='hanim_JinLOA1' if copy of original HAnimHumanoid is embedded in this model) }
HAnimHumanoid142 := THAnimHumanoidNode.Create;
HAnimHumanoid142 := HAnimHumanoid119;
{ .AddChildren }
fieldValue141.AddChildren([HAnimHumanoid142]);
{ .AddFieldValue }
ProtoInstance138.FieldValue := fieldValue141;
fieldValue143 := TfieldValueNode.Create;
fieldValue143.NameField := 'loa';
fieldValue143.Value := '1';
{ .AddFieldValue }
ProtoInstance138.FieldValue := fieldValue143;
fieldValue144 := TfieldValueNode.Create;
fieldValue144.NameField := 'description';
fieldValue144.Value := 'arms and legs stretched outward providing a TouchDown gesture';
{ .AddFieldValue }
ProtoInstance138.FieldValue := fieldValue144;
fieldValue145 := TfieldValueNode.Create;
fieldValue145.NameField := 'children';
HAnimJoint146 := THAnimJointNode.Create;
HAnimJoint146.NameField := 'humanoid_root';
HAnimJoint146.Rotation := Vector4(0,1,0,-0.698132);
HAnimJoint146.SetUlimit([0,0,0]);
HAnimJoint146.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint146]);
HAnimJoint147 := THAnimJointNode.Create;
HAnimJoint147.NameField := 'l_hip';
HAnimJoint147.Rotation := Vector4(-1,1,1,1);
HAnimJoint147.SetUlimit([0,0,0]);
HAnimJoint147.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint147]);
HAnimJoint148 := THAnimJointNode.Create;
HAnimJoint148.NameField := 'l_knee';
HAnimJoint148.Rotation := Vector4(1,0,0,1);
HAnimJoint148.SetUlimit([0,0,0]);
HAnimJoint148.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint148]);
HAnimJoint149 := THAnimJointNode.Create;
HAnimJoint149.NameField := 'l_talocrural';
HAnimJoint149.Rotation := Vector4(-0.2,0,0.1,0.225);
HAnimJoint149.SetUlimit([0,0,0]);
HAnimJoint149.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint149]);
HAnimJoint150 := THAnimJointNode.Create;
HAnimJoint150.NameField := 'r_hip';
HAnimJoint150.Rotation := Vector4(-1,-1,-1,1);
HAnimJoint150.SetUlimit([0,0,0]);
HAnimJoint150.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint150]);
HAnimJoint151 := THAnimJointNode.Create;
HAnimJoint151.NameField := 'r_knee';
HAnimJoint151.Rotation := Vector4(1,0,0,1);
HAnimJoint151.SetUlimit([0,0,0]);
HAnimJoint151.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint151]);
HAnimJoint152 := THAnimJointNode.Create;
HAnimJoint152.NameField := 'r_talocrural';
HAnimJoint152.Rotation := Vector4(-0.2,0,0.1,0.25);
HAnimJoint152.SetUlimit([0,0,0]);
HAnimJoint152.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint152]);
HAnimJoint153 := THAnimJointNode.Create;
HAnimJoint153.NameField := 'vl5';
HAnimJoint153.Rotation := Vector4(0,0,0.01,0.2);
HAnimJoint153.SetUlimit([0,0,0]);
HAnimJoint153.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint153]);
HAnimJoint154 := THAnimJointNode.Create;
HAnimJoint154.NameField := 'vt10';
HAnimJoint154.Rotation := Vector4(0,0,0.01,0.1);
HAnimJoint154.SetUlimit([0,0,0]);
HAnimJoint154.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint154]);
HAnimJoint155 := THAnimJointNode.Create;
HAnimJoint155.NameField := 'vc4';
HAnimJoint155.Rotation := Vector4(0,0,-0.01,0.15);
HAnimJoint155.SetUlimit([0,0,0]);
HAnimJoint155.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint155]);
HAnimJoint156 := THAnimJointNode.Create;
HAnimJoint156.NameField := 'l_shoulder';
HAnimJoint156.Rotation := Vector4(-1,0.5,1,2);
HAnimJoint156.SetUlimit([0,0,0]);
HAnimJoint156.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint156]);
HAnimJoint157 := THAnimJointNode.Create;
HAnimJoint157.NameField := 'l_elbow';
HAnimJoint157.Rotation := Vector4(-1,0,0,1);
HAnimJoint157.SetUlimit([0,0,0]);
HAnimJoint157.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint157]);
HAnimJoint158 := THAnimJointNode.Create;
HAnimJoint158.NameField := 'l_radiocarpal';
HAnimJoint158.SetUlimit([0,0,0]);
HAnimJoint158.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint158]);
HAnimJoint159 := THAnimJointNode.Create;
HAnimJoint159.NameField := 'r_shoulder';
HAnimJoint159.Rotation := Vector4(-1,-0.5,-1,2.6);
HAnimJoint159.SetUlimit([0,0,0]);
HAnimJoint159.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint159]);
HAnimJoint160 := THAnimJointNode.Create;
HAnimJoint160.NameField := 'r_elbow';
HAnimJoint160.Rotation := Vector4(-1,0,0,1);
HAnimJoint160.SetUlimit([0,0,0]);
HAnimJoint160.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint160]);
HAnimJoint161 := THAnimJointNode.Create;
HAnimJoint161.NameField := 'r_radiocarpal';
HAnimJoint161.SetUlimit([0,0,0]);
HAnimJoint161.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue145.AddChildren([HAnimJoint161]);
{ .AddFieldValue }
ProtoInstance138.FieldValue := fieldValue145;
fieldValue162 := TfieldValueNode.Create;
fieldValue162.NameField := 'transitionDuration';
fieldValue162.Value := '1.2';
{ .AddFieldValue }
ProtoInstance138.FieldValue := fieldValue162;
fieldValue163 := TfieldValueNode.Create;
fieldValue163.NameField := 'traceEnabled';
fieldValue163.Value := 'true';
{ .AddFieldValue }
ProtoInstance138.FieldValue := fieldValue163;
{ .AddChildren }
Group42.AddChildren([ProtoInstance138]);
ProtoInstance164 := TProtoInstanceNode.Create;
ProtoInstance164.NameField := 'HAnimPose';
fieldValue165 := TfieldValueNode.Create;
fieldValue165.NameField := 'name';
fieldValue165.Value := 'I';
{ .AddFieldValue }
ProtoInstance164.FieldValue := fieldValue165;
fieldValue166 := TfieldValueNode.Create;
fieldValue166.NameField := 'enabled';
fieldValue166.Value := 'true';
{ .AddFieldValue }
ProtoInstance164.FieldValue := fieldValue166;
fieldValue167 := TfieldValueNode.Create;
fieldValue167.NameField := 'parentHAnimHumanoid';
{ HumanoidImported for Inline/IMPORT (or else USE='hanim_JinLOA1' if copy of original HAnimHumanoid is embedded in this model) }
HAnimHumanoid168 := THAnimHumanoidNode.Create;
HAnimHumanoid168 := HAnimHumanoid119;
{ .AddChildren }
fieldValue167.AddChildren([HAnimHumanoid168]);
{ .AddFieldValue }
ProtoInstance164.FieldValue := fieldValue167;
fieldValue169 := TfieldValueNode.Create;
fieldValue169.NameField := 'loa';
fieldValue169.Value := '1';
{ .AddFieldValue }
ProtoInstance164.FieldValue := fieldValue169;
fieldValue170 := TfieldValueNode.Create;
fieldValue170.NameField := 'description';
fieldValue170.Value := 'arms and legs straight down default binding pose for baseline Humanoid';
{ .AddFieldValue }
ProtoInstance164.FieldValue := fieldValue170;
fieldValue171 := TfieldValueNode.Create;
fieldValue171.NameField := 'children';
{ not defining any children equals the default "I" pose }
{ .AddFieldValue }
ProtoInstance164.FieldValue := fieldValue171;
fieldValue172 := TfieldValueNode.Create;
fieldValue172.NameField := 'transitionDuration';
fieldValue172.Value := '1.5';
{ .AddFieldValue }
ProtoInstance164.FieldValue := fieldValue172;
fieldValue173 := TfieldValueNode.Create;
fieldValue173.NameField := 'traceEnabled';
fieldValue173.Value := 'true';
{ .AddFieldValue }
ProtoInstance164.FieldValue := fieldValue173;
{ .AddChildren }
Group42.AddChildren([ProtoInstance164]);
ProtoInstance174 := TProtoInstanceNode.Create;
ProtoInstance174.NameField := 'HAnimPose';
fieldValue175 := TfieldValueNode.Create;
fieldValue175.NameField := 'name';
fieldValue175.Value := 'H';
{ .AddFieldValue }
ProtoInstance174.FieldValue := fieldValue175;
fieldValue176 := TfieldValueNode.Create;
fieldValue176.NameField := 'enabled';
fieldValue176.Value := 'false';
{ .AddFieldValue }
ProtoInstance174.FieldValue := fieldValue176;
fieldValue177 := TfieldValueNode.Create;
fieldValue177.NameField := 'description';
fieldValue177.Value := 'TODO experimental pose not yet implemented';
{ .AddFieldValue }
ProtoInstance174.FieldValue := fieldValue177;
fieldValue178 := TfieldValueNode.Create;
fieldValue178.NameField := 'transitionDuration';
fieldValue178.Value := '1.4';
{ .AddFieldValue }
ProtoInstance174.FieldValue := fieldValue178;
fieldValue179 := TfieldValueNode.Create;
fieldValue179.NameField := 'traceEnabled';
fieldValue179.Value := 'true';
{ .AddFieldValue }
ProtoInstance174.FieldValue := fieldValue179;
{ <fieldValue name='loa' value='1'/> }
{ .AddChildren }
Group42.AddChildren([ProtoInstance174]);
ProtoInstance180 := TProtoInstanceNode.Create;
ProtoInstance180.NameField := 'HAnimPose';
fieldValue181 := TfieldValueNode.Create;
fieldValue181.NameField := 'name';
fieldValue181.Value := 'FaceLeft';
{ .AddFieldValue }
ProtoInstance180.FieldValue := fieldValue181;
fieldValue182 := TfieldValueNode.Create;
fieldValue182.NameField := 'enabled';
fieldValue182.Value := 'true';
{ .AddFieldValue }
ProtoInstance180.FieldValue := fieldValue182;
fieldValue183 := TfieldValueNode.Create;
fieldValue183.NameField := 'parentHAnimHumanoid';
{ HumanoidImported for Inline/IMPORT (or else USE='hanim_JinLOA1' if copy of original HAnimHumanoid is embedded in this model) }
HAnimHumanoid184 := THAnimHumanoidNode.Create;
HAnimHumanoid184 := HAnimHumanoid119;
{ .AddChildren }
fieldValue183.AddChildren([HAnimHumanoid184]);
{ .AddFieldValue }
ProtoInstance180.FieldValue := fieldValue183;
fieldValue185 := TfieldValueNode.Create;
fieldValue185.NameField := 'loa';
fieldValue185.Value := '0';
{ .AddFieldValue }
ProtoInstance180.FieldValue := fieldValue185;
fieldValue186 := TfieldValueNode.Create;
fieldValue186.NameField := 'description';
fieldValue186.Value := 'Only modify humanoid_root Joint node to face left';
{ .AddFieldValue }
ProtoInstance180.FieldValue := fieldValue186;
fieldValue187 := TfieldValueNode.Create;
fieldValue187.NameField := 'children';
HAnimJoint188 := THAnimJointNode.Create;
HAnimJoint188.NameField := 'humanoid_root';
HAnimJoint188.Description := 'Only rotate the model';
HAnimJoint188.Rotation := Vector4(0,1,0,1.570796);
HAnimJoint188.SetUlimit([0,0,0]);
HAnimJoint188.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue187.AddChildren([HAnimJoint188]);
{ .AddFieldValue }
ProtoInstance180.FieldValue := fieldValue187;
fieldValue189 := TfieldValueNode.Create;
fieldValue189.NameField := 'transitionDuration';
fieldValue189.Value := '1.1';
{ .AddFieldValue }
ProtoInstance180.FieldValue := fieldValue189;
fieldValue190 := TfieldValueNode.Create;
fieldValue190.NameField := 'traceEnabled';
fieldValue190.Value := 'true';
{ .AddFieldValue }
ProtoInstance180.FieldValue := fieldValue190;
{ .AddChildren }
Group42.AddChildren([ProtoInstance180]);
ProtoInstance191 := TProtoInstanceNode.Create;
ProtoInstance191.NameField := 'HAnimPose';
fieldValue192 := TfieldValueNode.Create;
fieldValue192.NameField := 'name';
fieldValue192.Value := 'FaceRight';
{ .AddFieldValue }
ProtoInstance191.FieldValue := fieldValue192;
fieldValue193 := TfieldValueNode.Create;
fieldValue193.NameField := 'enabled';
fieldValue193.Value := 'true';
{ .AddFieldValue }
ProtoInstance191.FieldValue := fieldValue193;
fieldValue194 := TfieldValueNode.Create;
fieldValue194.NameField := 'parentHAnimHumanoid';
{ HumanoidImported for Inline/IMPORT (or else USE='hanim_JinLOA1' if copy of original HAnimHumanoid is embedded in this model) }
HAnimHumanoid195 := THAnimHumanoidNode.Create;
HAnimHumanoid195 := HAnimHumanoid119;
{ .AddChildren }
fieldValue194.AddChildren([HAnimHumanoid195]);
{ .AddFieldValue }
ProtoInstance191.FieldValue := fieldValue194;
fieldValue196 := TfieldValueNode.Create;
fieldValue196.NameField := 'loa';
fieldValue196.Value := '0';
{ .AddFieldValue }
ProtoInstance191.FieldValue := fieldValue196;
fieldValue197 := TfieldValueNode.Create;
fieldValue197.NameField := 'description';
fieldValue197.Value := 'Only modify humanoid_root Joint node to face right';
{ .AddFieldValue }
ProtoInstance191.FieldValue := fieldValue197;
fieldValue198 := TfieldValueNode.Create;
fieldValue198.NameField := 'children';
HAnimJoint199 := THAnimJointNode.Create;
HAnimJoint199.NameField := 'humanoid_root';
HAnimJoint199.Description := 'Only rotate the model';
HAnimJoint199.Rotation := Vector4(0,1,0,-1.570796);
HAnimJoint199.SetUlimit([0,0,0]);
HAnimJoint199.SetLlimit([0,0,0]);
{ .AddChildren }
fieldValue198.AddChildren([HAnimJoint199]);
{ .AddFieldValue }
ProtoInstance191.FieldValue := fieldValue198;
fieldValue200 := TfieldValueNode.Create;
fieldValue200.NameField := 'transitionDuration';
fieldValue200.Value := '1.1';
{ .AddFieldValue }
ProtoInstance191.FieldValue := fieldValue200;
fieldValue201 := TfieldValueNode.Create;
fieldValue201.NameField := 'traceEnabled';
fieldValue201.Value := 'true';
{ .AddFieldValue }
ProtoInstance191.FieldValue := fieldValue201;
{ .AddChildren }
Group42.AddChildren([ProtoInstance191]);
Group202 := TGroupNode.Create;
Transform203 := TTransformNode.Create;
Transform203.Translation := Vector3(0,2,0);
Shape204 := TShapeNode.Create;
Text205 := TTextNode.Create;
Text205.SetText(['HAnimPosePrototype example implementation']);
FontStyle206 := TFontStyleNode.Create;
FontStyle206.Family := ffSans;
FontStyle206.Justify := fjMiddle;
FontStyle206.JustifyMinor := fjMiddle;
FontStyle206.Size := 0.15;
FontStyle206.Style := 'BOLD';
{ .SetFontStyle }
Text205.FontStyle := FontStyle206;
{ .SetGeometry }
Shape204.Geometry := Text205;
Appearance207 := TAppearanceNode.Create;
Material208 := TMaterialNode.Create;
Material208.DiffuseColor := Vector3(0.1,0.5,0.3);
{ .SetMaterial }
Appearance207.Material := Material208;
{ .SetAppearance }
Shape204.Appearance := Appearance207;
{ .AddChild }
Transform203.AddChildren([Shape204]);
{ .AddChildren }
Group202.AddChildren([Transform203]);
Transform209 := TTransformNode.Create;
Transform209.Translation := Vector3(-1.5,1.5,0);
Shape210 := TShapeNode.Create;
Text211 := TTextNode.Create;
Text211.SetText(['\"T\" Pose']);
FontStyle212 := TFontStyleNode.Create;
FontStyle212.Family := ffSans;
FontStyle212.Justify := fjMiddle;
FontStyle212.JustifyMinor := fjMiddle;
FontStyle212.Size := 0.1;
FontStyle212.Style := 'BOLD';
{ .SetFontStyle }
Text211.FontStyle := FontStyle212;
{ .SetGeometry }
Shape210.Geometry := Text211;
Appearance213 := TAppearanceNode.Create;
Appearance213 := Appearance207;
{ .SetAppearance }
Shape210.Appearance := Appearance213;
{ .AddChild }
Transform209.AddChildren([Shape210]);
Shape214 := TShapeNode.Create;
Appearance215 := TAppearanceNode.Create;
Material216 := TMaterialNode.Create;
Material216.Transparency := 0.8;
{ .SetMaterial }
Appearance215.Material := Material216;
{ .SetAppearance }
Shape214.Appearance := Appearance215;
Box217 := TBoxNode.Create;
Box217.Size := Vector3(0.45,0.2,0.001);
{ .SetGeometry }
Shape214.Geometry := Box217;
{ .AddChild }
Transform209.AddChildren([Shape214]);
TouchSensor218 := TTouchSensorNode.Create;
TouchSensor218.Description := 'select to move shoulders to \"T\" pose, leave other joints unchanged';
{ .AddChildren }
Transform209.AddChildren([TouchSensor218]);
Transform209.AddRoute(TouchSensor218.FdIsactive, ProtoInstance115.FdCommencepose);
{ .AddX3DRoute }
{ .AddChildren }
Group202.AddChildren([Transform209]);
Transform220 := TTransformNode.Create;
Transform220.Translation := Vector3(-1.5,1,0);
Shape221 := TShapeNode.Create;
Text222 := TTextNode.Create;
Text222.SetText(['\"A\" Pose']);
FontStyle223 := TFontStyleNode.Create;
FontStyle223 := FontStyle212;
{ .SetFontStyle }
Text222.FontStyle := FontStyle223;
{ .SetGeometry }
Shape221.Geometry := Text222;
Appearance224 := TAppearanceNode.Create;
Appearance224 := Appearance207;
{ .SetAppearance }
Shape221.Appearance := Appearance224;
{ .AddChild }
Transform220.AddChildren([Shape221]);
Shape225 := TShapeNode.Create;
{ Selectable Text transparent Box for easy user selection }
Appearance226 := TAppearanceNode.Create;
Appearance226 := Appearance215;
{ .SetAppearance }
Shape225.Appearance := Appearance226;
Box227 := TBoxNode.Create;
Box227.Size := Vector3(0.45,0.2,0.001);
{ .SetGeometry }
Shape225.Geometry := Box227;
{ .AddChild }
Transform220.AddChildren([Shape225]);
TouchSensor228 := TTouchSensorNode.Create;
TouchSensor228.Description := 'select to move shoulders to \"A\" pose, leave other joints unchanged';
{ .AddChildren }
Transform220.AddChildren([TouchSensor228]);
Transform220.AddRoute(TouchSensor228.FdIsactive, ProtoInstance126.FdCommencepose);
{ .AddX3DRoute }
{ .AddChildren }
Group202.AddChildren([Transform220]);
Transform230 := TTransformNode.Create;
Transform230.Translation := Vector3(-1.5,0.5,0);
Shape231 := TShapeNode.Create;
Text232 := TTextNode.Create;
Text232.SetText(['TouchDown Pose']);
FontStyle233 := TFontStyleNode.Create;
FontStyle233 := FontStyle212;
{ .SetFontStyle }
Text232.FontStyle := FontStyle233;
{ .SetGeometry }
Shape231.Geometry := Text232;
Appearance234 := TAppearanceNode.Create;
Appearance234 := Appearance207;
{ .SetAppearance }
Shape231.Appearance := Appearance234;
{ .AddChild }
Transform230.AddChildren([Shape231]);
Shape235 := TShapeNode.Create;
{ Selectable Text transparent Box for easy user selection }
Appearance236 := TAppearanceNode.Create;
Appearance236 := Appearance215;
{ .SetAppearance }
Shape235.Appearance := Appearance236;
Box237 := TBoxNode.Create;
Box237.Size := Vector3(0.85,0.2,0.001);
{ .SetGeometry }
Shape235.Geometry := Box237;
{ .AddChild }
Transform230.AddChildren([Shape235]);
TouchSensor238 := TTouchSensorNode.Create;
TouchSensor238.Description := 'select to transition all joints to TouchDown pose';
{ .AddChildren }
Transform230.AddChildren([TouchSensor238]);
Transform230.AddRoute(TouchSensor238.FdIsactive, ProtoInstance138.FdCommencepose);
{ .AddX3DRoute }
{ .AddChildren }
Group202.AddChildren([Transform230]);
Transform240 := TTransformNode.Create;
Transform240.Translation := Vector3(-1.5,0,0);
Shape241 := TShapeNode.Create;
Text242 := TTextNode.Create;
Text242.SetText(['\"I\" Pose']);
FontStyle243 := TFontStyleNode.Create;
FontStyle243 := FontStyle212;
{ .SetFontStyle }
Text242.FontStyle := FontStyle243;
{ .SetGeometry }
Shape241.Geometry := Text242;
Appearance244 := TAppearanceNode.Create;
Appearance244 := Appearance207;
{ .SetAppearance }
Shape241.Appearance := Appearance244;
{ .AddChild }
Transform240.AddChildren([Shape241]);
Shape245 := TShapeNode.Create;
{ Selectable Text transparent Box for easy user selection }
Appearance246 := TAppearanceNode.Create;
Appearance246 := Appearance215;
{ .SetAppearance }
Shape245.Appearance := Appearance246;
Box247 := TBoxNode.Create;
Box247.Size := Vector3(0.45,0.2,0.001);
{ .SetGeometry }
Shape245.Geometry := Box247;
{ .AddChild }
Transform240.AddChildren([Shape245]);
TouchSensor248 := TTouchSensorNode.Create;
TouchSensor248.Description := 'select to transition all joints to \"I\" pose';
{ .AddChildren }
Transform240.AddChildren([TouchSensor248]);
Transform240.AddRoute(TouchSensor248.FdIsactive, ProtoInstance164.FdCommencepose);
{ .AddX3DRoute }
{ .AddChildren }
Group202.AddChildren([Transform240]);
Transform250 := TTransformNode.Create;
Transform250.Translation := Vector3(1.5,1.5,0);
Shape251 := TShapeNode.Create;
Text252 := TTextNode.Create;
Text252.SetText(['Face Left Pose']);
FontStyle253 := TFontStyleNode.Create;
FontStyle253 := FontStyle212;
{ .SetFontStyle }
Text252.FontStyle := FontStyle253;
{ .SetGeometry }
Shape251.Geometry := Text252;
Appearance254 := TAppearanceNode.Create;
Appearance254 := Appearance207;
{ .SetAppearance }
Shape251.Appearance := Appearance254;
{ .AddChild }
Transform250.AddChildren([Shape251]);
Shape255 := TShapeNode.Create;
Appearance256 := TAppearanceNode.Create;
Appearance256 := Appearance215;
{ .SetAppearance }
Shape255.Appearance := Appearance256;
Box257 := TBoxNode.Create;
Box257.Size := Vector3(0.9,0.2,0.001);
{ .SetGeometry }
Shape255.Geometry := Box257;
{ .AddChild }
Transform250.AddChildren([Shape255]);
TouchSensor258 := TTouchSensorNode.Create;
TouchSensor258.Description := 'select to rotate body and Face Left, leave other joints unchanged';
{ .AddChildren }
Transform250.AddChildren([TouchSensor258]);
Transform250.AddRoute(TouchSensor258.FdIsactive, ProtoInstance180.FdCommencepose);
{ .AddX3DRoute }
{ .AddChildren }
Group202.AddChildren([Transform250]);
Transform260 := TTransformNode.Create;
Transform260.Translation := Vector3(1.5,1,0);
Shape261 := TShapeNode.Create;
Text262 := TTextNode.Create;
Text262.SetText(['Face Right Pose']);
FontStyle263 := TFontStyleNode.Create;
FontStyle263 := FontStyle212;
{ .SetFontStyle }
Text262.FontStyle := FontStyle263;
{ .SetGeometry }
Shape261.Geometry := Text262;
Appearance264 := TAppearanceNode.Create;
Appearance264 := Appearance207;
{ .SetAppearance }
Shape261.Appearance := Appearance264;
{ .AddChild }
Transform260.AddChildren([Shape261]);
Shape265 := TShapeNode.Create;
{ Selectable Text transparent Box for easy user selection }
Appearance266 := TAppearanceNode.Create;
Appearance266 := Appearance215;
{ .SetAppearance }
Shape265.Appearance := Appearance266;
Box267 := TBoxNode.Create;
Box267.Size := Vector3(0.9,0.2,0.001);
{ .SetGeometry }
Shape265.Geometry := Box267;
{ .AddChild }
Transform260.AddChildren([Shape265]);
TouchSensor268 := TTouchSensorNode.Create;
TouchSensor268.Description := 'select to rotate body and Face Right, leave other joints unchanged';
{ .AddChildren }
Transform260.AddChildren([TouchSensor268]);
Transform260.AddRoute(TouchSensor268.FdIsactive, ProtoInstance191.FdCommencepose);
{ .AddX3DRoute }
{ .AddChildren }
Group202.AddChildren([Transform260]);
Transform270 := TTransformNode.Create;
Transform270.Translation := Vector3(1.5,0.5,0);
Shape271 := TShapeNode.Create;
Text272 := TTextNode.Create;
Text272.SetText(['Direct animation','to, from \"I\" Pose']);
FontStyle273 := TFontStyleNode.Create;
FontStyle273 := FontStyle212;
{ .SetFontStyle }
Text272.FontStyle := FontStyle273;
{ .SetGeometry }
Shape271.Geometry := Text272;
Appearance274 := TAppearanceNode.Create;
Material275 := TMaterialNode.Create;
Material275.DiffuseColor := Vector3(0.1,0.2,0.3);
{ .SetMaterial }
Appearance274.Material := Material275;
{ .SetAppearance }
Shape271.Appearance := Appearance274;
{ .AddChild }
Transform270.AddChildren([Shape271]);
Shape276 := TShapeNode.Create;
{ Selectable Text transparent Box for easy user selection }
Appearance277 := TAppearanceNode.Create;
Appearance277 := Appearance215;
{ .SetAppearance }
Shape276.Appearance := Appearance277;
Box278 := TBoxNode.Create;
Box278.Size := Vector3(0.9,0.25,0.001);
{ .SetGeometry }
Shape276.Geometry := Box278;
{ .AddChild }
Transform270.AddChildren([Shape276]);
TouchSensor279 := TTouchSensorNode.Create;
TouchSensor279.Description := 'select to animate current pose to \"I\" pose, then back to original pose, using TimeSensor events';
{ .AddChildren }
Transform270.AddChildren([TouchSensor279]);
{ cycleInterval=4 also hard-coded in script execution message }
TimeSensor280 := TTimeSensorNode.Create;
TimeSensor280.CycleInterval := 4;
TimeSensor280.Description := 'directly animate several poses';
{ .AddChildren }
Transform270.AddChildren([TimeSensor280]);
ScalarInterpolator281 := TScalarInterpolatorNode.Create;
ScalarInterpolator281.SetKey([0,0.05,0.45,0.55,0.95,1]);
ScalarInterpolator281.SetKeyValue([0,0,1,1,0,0]);
{ .AddChildren }
Transform270.AddChildren([ScalarInterpolator281]);
Transform270.AddRoute(TouchSensor279.EventTouchtime, TimeSensor280.FdStarttime);
{ .AddX3DRoute }
Transform270.AddRoute(TimeSensor280.EventFraction_changed, ScalarInterpolator281.EventSet_fraction);
{ .AddX3DRoute }
Transform270.AddRoute(ScalarInterpolator281.EventValue_changed, ProtoInstance164.EventSet_fraction);
{ .AddX3DRoute }
{ .AddChildren }
Group202.AddChildren([Transform270]);
Transform285 := TTransformNode.Create;
Transform285.Translation := Vector3(1.5,0,0);
Shape286 := TShapeNode.Create;
Text287 := TTextNode.Create;
Text287.SetText(['Reset All Joints','to Default \"I\" Pose']);
FontStyle288 := TFontStyleNode.Create;
FontStyle288 := FontStyle212;
{ .SetFontStyle }
Text287.FontStyle := FontStyle288;
{ .SetGeometry }
Shape286.Geometry := Text287;
Appearance289 := TAppearanceNode.Create;
Appearance289 := Appearance274;
{ .SetAppearance }
Shape286.Appearance := Appearance289;
{ .AddChild }
Transform285.AddChildren([Shape286]);
Shape290 := TShapeNode.Create;
{ Selectable Text transparent Box for easy user selection }
Appearance291 := TAppearanceNode.Create;
Appearance291 := Appearance215;
{ .SetAppearance }
Shape290.Appearance := Appearance291;
Box292 := TBoxNode.Create;
Box292.Size := Vector3(0.9,0.25,0.001);
{ .SetGeometry }
Shape290.Geometry := Box292;
{ .AddChild }
Transform285.AddChildren([Shape290]);
TouchSensor293 := TTouchSensorNode.Create;
TouchSensor293.Description := 'select to immediately Rezero All Joints (to default \"I\" Pose) by sending resetAllJoints event';
{ .AddChildren }
Transform285.AddChildren([TouchSensor293]);
Transform285.AddRoute(TouchSensor293.FdIsactive, ProtoInstance180.FdResetalljoints);
{ .AddX3DRoute }
{ .AddChildren }
Group202.AddChildren([Transform285]);
{ .AddChildren }
Group42.AddChildren([Group202]);
Group295 := TGroupNode.Create;
Group295.AddRoute(LoadSensor49.FdIsloaded, ProtoInstance126.FdIsloaded);
{ .SetX3DRoute }
Group295.AddRoute(LoadSensor49.FdIsloaded, ProtoInstance174.FdIsloaded);
{ .AddX3DRoute }
Group295.AddRoute(LoadSensor49.FdIsloaded, ProtoInstance164.FdIsloaded);
{ .AddX3DRoute }
Group295.AddRoute(LoadSensor49.FdIsloaded, ProtoInstance115.FdIsloaded);
{ .AddX3DRoute }
Group295.AddRoute(LoadSensor49.FdIsloaded, ProtoInstance180.FdIsloaded);
{ .AddX3DRoute }
Group295.AddRoute(LoadSensor49.FdIsloaded, ProtoInstance191.FdIsloaded);
{ .AddX3DRoute }
Group295.AddRoute(LoadSensor49.FdIsloaded, ProtoInstance138.FdIsloaded);
{ .AddX3DRoute }
{ .AddChildren }
Group42.AddChildren([Group295]);
{ .AddGroup }
X3D0.AddChildren([Group42]);
Result := X3D0;
end;
