function HAnimModelHandLeft: TX3DRootNode;
var
X3D0: TX3DRootNode;
Group24: TGroupNode;
WorldInfo25: TWorldInfoNode;
HAnimHumanoid26: THAnimHumanoidNode;
MetadataSet27: TMetadataSetNode;
MetadataString28: TMetadataStringNode;
HAnimJoint29: THAnimJointNode;
HAnimJoint30: THAnimJointNode;
HAnimSegment31: THAnimSegmentNode;
Transform32: TTransformNode;
Shape33: TShapeNode;
Sphere34: TSphereNode;
Appearance35: TAppearanceNode;
Material36: TMaterialNode;
Shape37: TShapeNode;
Appearance38: TAppearanceNode;
Material39: TMaterialNode;
IndexedLineSet40: TIndexedLineSetNode;
Coordinate41: TCoordinateNode;
Shape42: TShapeNode;
Appearance43: TAppearanceNode;
Material44: TMaterialNode;
IndexedLineSet45: TIndexedLineSetNode;
Coordinate46: TCoordinateNode;
Shape47: TShapeNode;
Appearance48: TAppearanceNode;
Material49: TMaterialNode;
IndexedLineSet50: TIndexedLineSetNode;
Coordinate51: TCoordinateNode;
HAnimJoint52: THAnimJointNode;
HAnimSegment53: THAnimSegmentNode;
Transform54: TTransformNode;
Shape55: TShapeNode;
Sphere56: TSphereNode;
Appearance57: TAppearanceNode;
Material58: TMaterialNode;
Shape59: TShapeNode;
Appearance60: TAppearanceNode;
Material61: TMaterialNode;
IndexedLineSet62: TIndexedLineSetNode;
Coordinate63: TCoordinateNode;
Shape64: TShapeNode;
Appearance65: TAppearanceNode;
Material66: TMaterialNode;
IndexedLineSet67: TIndexedLineSetNode;
Coordinate68: TCoordinateNode;
HAnimJoint69: THAnimJointNode;
HAnimSegment70: THAnimSegmentNode;
Transform71: TTransformNode;
Shape72: TShapeNode;
Shape73: TShapeNode;
Appearance74: TAppearanceNode;
Material75: TMaterialNode;
IndexedLineSet76: TIndexedLineSetNode;
Coordinate77: TCoordinateNode;
HAnimJoint78: THAnimJointNode;
HAnimSegment79: THAnimSegmentNode;
Transform80: TTransformNode;
Shape81: TShapeNode;
Shape82: TShapeNode;
Appearance83: TAppearanceNode;
Material84: TMaterialNode;
IndexedLineSet85: TIndexedLineSetNode;
Coordinate86: TCoordinateNode;
HAnimJoint87: THAnimJointNode;
HAnimSegment88: THAnimSegmentNode;
Transform89: TTransformNode;
Shape90: TShapeNode;
Shape91: TShapeNode;
Appearance92: TAppearanceNode;
Material93: TMaterialNode;
IndexedLineSet94: TIndexedLineSetNode;
Coordinate95: TCoordinateNode;
HAnimJoint96: THAnimJointNode;
HAnimSegment97: THAnimSegmentNode;
Transform98: TTransformNode;
Shape99: TShapeNode;
Shape100: TShapeNode;
Appearance101: TAppearanceNode;
Material102: TMaterialNode;
IndexedLineSet103: TIndexedLineSetNode;
Coordinate104: TCoordinateNode;
HAnimJoint105: THAnimJointNode;
HAnimSegment106: THAnimSegmentNode;
Transform107: TTransformNode;
Shape108: TShapeNode;
Shape109: TShapeNode;
Appearance110: TAppearanceNode;
Material111: TMaterialNode;
IndexedLineSet112: TIndexedLineSetNode;
Coordinate113: TCoordinateNode;
HAnimJoint114: THAnimJointNode;
HAnimSegment115: THAnimSegmentNode;
Transform116: TTransformNode;
Shape117: TShapeNode;
Shape118: TShapeNode;
Appearance119: TAppearanceNode;
Material120: TMaterialNode;
IndexedLineSet121: TIndexedLineSetNode;
Coordinate122: TCoordinateNode;
HAnimJoint123: THAnimJointNode;
HAnimSegment124: THAnimSegmentNode;
Transform125: TTransformNode;
Shape126: TShapeNode;
Shape127: TShapeNode;
Appearance128: TAppearanceNode;
Material129: TMaterialNode;
IndexedLineSet130: TIndexedLineSetNode;
Coordinate131: TCoordinateNode;
HAnimJoint132: THAnimJointNode;
HAnimSegment133: THAnimSegmentNode;
Transform134: TTransformNode;
Shape135: TShapeNode;
Shape136: TShapeNode;
Appearance137: TAppearanceNode;
Material138: TMaterialNode;
IndexedLineSet139: TIndexedLineSetNode;
Coordinate140: TCoordinateNode;
HAnimJoint141: THAnimJointNode;
HAnimSegment142: THAnimSegmentNode;
Transform143: TTransformNode;
Shape144: TShapeNode;
Shape145: TShapeNode;
Appearance146: TAppearanceNode;
Material147: TMaterialNode;
IndexedLineSet148: TIndexedLineSetNode;
Coordinate149: TCoordinateNode;
HAnimJoint150: THAnimJointNode;
HAnimSegment151: THAnimSegmentNode;
Transform152: TTransformNode;
Shape153: TShapeNode;
Shape154: TShapeNode;
Appearance155: TAppearanceNode;
Material156: TMaterialNode;
IndexedLineSet157: TIndexedLineSetNode;
Coordinate158: TCoordinateNode;
HAnimJoint159: THAnimJointNode;
HAnimSegment160: THAnimSegmentNode;
Transform161: TTransformNode;
Shape162: TShapeNode;
Shape163: TShapeNode;
Appearance164: TAppearanceNode;
Material165: TMaterialNode;
IndexedLineSet166: TIndexedLineSetNode;
Coordinate167: TCoordinateNode;
HAnimJoint168: THAnimJointNode;
HAnimSegment169: THAnimSegmentNode;
Transform170: TTransformNode;
Shape171: TShapeNode;
Shape172: TShapeNode;
Appearance173: TAppearanceNode;
Material174: TMaterialNode;
IndexedLineSet175: TIndexedLineSetNode;
Coordinate176: TCoordinateNode;
HAnimJoint177: THAnimJointNode;
HAnimSegment178: THAnimSegmentNode;
Transform179: TTransformNode;
Shape180: TShapeNode;
Shape181: TShapeNode;
Appearance182: TAppearanceNode;
Material183: TMaterialNode;
IndexedLineSet184: TIndexedLineSetNode;
Coordinate185: TCoordinateNode;
HAnimJoint186: THAnimJointNode;
HAnimSegment187: THAnimSegmentNode;
Transform188: TTransformNode;
Shape189: TShapeNode;
Shape190: TShapeNode;
Appearance191: TAppearanceNode;
Material192: TMaterialNode;
IndexedLineSet193: TIndexedLineSetNode;
Coordinate194: TCoordinateNode;
Shape195: TShapeNode;
Appearance196: TAppearanceNode;
Material197: TMaterialNode;
IndexedLineSet198: TIndexedLineSetNode;
Coordinate199: TCoordinateNode;
HAnimJoint200: THAnimJointNode;
HAnimSegment201: THAnimSegmentNode;
Transform202: TTransformNode;
Shape203: TShapeNode;
Shape204: TShapeNode;
Appearance205: TAppearanceNode;
Material206: TMaterialNode;
IndexedLineSet207: TIndexedLineSetNode;
Coordinate208: TCoordinateNode;
HAnimJoint209: THAnimJointNode;
HAnimSegment210: THAnimSegmentNode;
Transform211: TTransformNode;
Shape212: TShapeNode;
Shape213: TShapeNode;
Appearance214: TAppearanceNode;
Material215: TMaterialNode;
IndexedLineSet216: TIndexedLineSetNode;
Coordinate217: TCoordinateNode;
HAnimJoint218: THAnimJointNode;
HAnimSegment219: THAnimSegmentNode;
Transform220: TTransformNode;
Shape221: TShapeNode;
Shape222: TShapeNode;
Appearance223: TAppearanceNode;
Material224: TMaterialNode;
IndexedLineSet225: TIndexedLineSetNode;
Coordinate226: TCoordinateNode;
HAnimJoint227: THAnimJointNode;
HAnimSegment228: THAnimSegmentNode;
Transform229: TTransformNode;
Shape230: TShapeNode;
Shape231: TShapeNode;
Appearance232: TAppearanceNode;
Material233: TMaterialNode;
IndexedLineSet234: TIndexedLineSetNode;
Coordinate235: TCoordinateNode;
HAnimJoint236: THAnimJointNode;
HAnimSegment237: THAnimSegmentNode;
Transform238: TTransformNode;
Shape239: TShapeNode;
Shape240: TShapeNode;
Appearance241: TAppearanceNode;
Material242: TMaterialNode;
IndexedLineSet243: TIndexedLineSetNode;
Coordinate244: TCoordinateNode;
HAnimJoint245: THAnimJointNode;
HAnimSegment246: THAnimSegmentNode;
Transform247: TTransformNode;
Shape248: TShapeNode;
Shape249: TShapeNode;
Appearance250: TAppearanceNode;
Material251: TMaterialNode;
IndexedLineSet252: TIndexedLineSetNode;
Coordinate253: TCoordinateNode;
HAnimJoint254: THAnimJointNode;
HAnimSegment255: THAnimSegmentNode;
Transform256: TTransformNode;
Shape257: TShapeNode;
Shape258: TShapeNode;
Appearance259: TAppearanceNode;
Material260: TMaterialNode;
IndexedLineSet261: TIndexedLineSetNode;
Coordinate262: TCoordinateNode;
HAnimJoint263: THAnimJointNode;
HAnimSegment264: THAnimSegmentNode;
Transform265: TTransformNode;
Shape266: TShapeNode;
Shape267: TShapeNode;
Appearance268: TAppearanceNode;
Material269: TMaterialNode;
IndexedLineSet270: TIndexedLineSetNode;
Coordinate271: TCoordinateNode;
HAnimJoint272: THAnimJointNode;
HAnimJoint273: THAnimJointNode;
HAnimJoint274: THAnimJointNode;
HAnimJoint275: THAnimJointNode;
HAnimJoint276: THAnimJointNode;
HAnimJoint277: THAnimJointNode;
HAnimJoint278: THAnimJointNode;
HAnimJoint279: THAnimJointNode;
HAnimJoint280: THAnimJointNode;
HAnimJoint281: THAnimJointNode;
HAnimJoint282: THAnimJointNode;
HAnimJoint283: THAnimJointNode;
HAnimJoint284: THAnimJointNode;
HAnimJoint285: THAnimJointNode;
HAnimJoint286: THAnimJointNode;
HAnimJoint287: THAnimJointNode;
HAnimJoint288: THAnimJointNode;
HAnimJoint289: THAnimJointNode;
HAnimJoint290: THAnimJointNode;
HAnimJoint291: THAnimJointNode;
HAnimJoint292: THAnimJointNode;
HAnimJoint293: THAnimJointNode;
HAnimJoint294: THAnimJointNode;
HAnimJoint295: THAnimJointNode;
HAnimJoint296: THAnimJointNode;
HAnimSegment297: THAnimSegmentNode;
HAnimSegment298: THAnimSegmentNode;
HAnimSegment299: THAnimSegmentNode;
HAnimSegment300: THAnimSegmentNode;
HAnimSegment301: THAnimSegmentNode;
HAnimSegment302: THAnimSegmentNode;
HAnimSegment303: THAnimSegmentNode;
HAnimSegment304: THAnimSegmentNode;
HAnimSegment305: THAnimSegmentNode;
HAnimSegment306: THAnimSegmentNode;
HAnimSegment307: THAnimSegmentNode;
HAnimSegment308: THAnimSegmentNode;
HAnimSegment309: THAnimSegmentNode;
HAnimSegment310: THAnimSegmentNode;
HAnimSegment311: THAnimSegmentNode;
HAnimSegment312: THAnimSegmentNode;
HAnimSegment313: THAnimSegmentNode;
HAnimSegment314: THAnimSegmentNode;
HAnimSegment315: THAnimSegmentNode;
HAnimSegment316: THAnimSegmentNode;
HAnimSegment317: THAnimSegmentNode;
HAnimSegment318: THAnimSegmentNode;
HAnimSegment319: THAnimSegmentNode;
HAnimSegment320: THAnimSegmentNode;
begin
X3D0 := TX3DRootNode.Create;
X3D0.Profile := 'Immersive';
X3D0.ForceVersion.Major := 4;
X3D0.ForceVersion.Minor := 0;
X3D0.Components['HAnim'] := 1;
X3D0.Meta['title'] := 'HAnimModelHandLeft.x3d';
X3D0.Meta['description'] := 'Left hand, using high-fidelity definitions for HAnim version 2.0';
X3D0.Meta['creator'] := 'Kwan-Hee YOO, Don Brutzman and Joe Williams';
X3D0.Meta['created'] := '26 January 2015';
X3D0.Meta['modified'] := '23 December 2021';
X3D0.Meta['TODO'] := 'fix visible geometry for thumb and index finger, midcarpal_1 and midcarpal_2';
X3D0.Meta['Image'] := 'HAnimModelHandRightSegmentVisualizationError.png';
X3D0.Meta['error'] := 'not yet to scale, also relatively flat';
X3D0.Meta['warning'] := 'TODO will X3D HAnim component add a new level to support LOA-4 functionality?';
X3D0.Meta['info'] := 'TODO describe how to compute and apply offsets for center values whenever attaching this appendage to a body';
X3D0.Meta['reference'] := 'https://www.web3d.org/working-groups/humanoid-animation-HAnim';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#TheHands';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#f-HandJoints';
X3D0.Meta['reference'] := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/concepts.html#Hierarchy4';
X3D0.Meta['reference'] := 'https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-WD2/Part01/components/hanim.html';
X3D0.Meta['subject'] := 'X3D HAnim humanoid animation';
X3D0.Meta['TODO'] := 'Integrate and confirm Segment/Joint names, Viewpoints.';
X3D0.Meta['identifier'] := 'https://www.web3d.org/x3d/content/examples/HumanoidAnimation/Characters/HAnimModelHandLeft.x3d';
X3D0.Meta['generator'] := 'X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit';
X3D0.Meta['license'] := '../license.html';
Group24 := TGroupNode.Create;
WorldInfo25 := TWorldInfoNode.Create;
WorldInfo25.Title := 'HAnimModelHandLeft.x3d';
{ .AddChildren }
Group24.AddChildren([WorldInfo25]);
HAnimHumanoid26 := THAnimHumanoidNode.Create;
HAnimHumanoid26.NameField := 'Hand_Left';
HAnimHumanoid26.Loa := 4;
HAnimHumanoid26.Version := '2.0';
{ original HAnimHumanoid info='"authorName=Kwan-Hee YOO, Don Brutzman and Joe Williams"' }
MetadataSet27 := TMetadataSetNode.Create;
MetadataSet27.NameField := 'HAnimHumanoid.info';
MetadataSet27.Reference := 'https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/ObjectInterfaces.html#Humanoid';
MetadataString28 := TMetadataStringNode.Create;
MetadataString28.NameField := 'authorName';
MetadataString28.SetValue(['Kwan-Hee YOO, Don Brutzman and Joe Williams']);
{ .SetValue }
MetadataSet27.Value := MetadataString28;
{ .SetMetadata }
HAnimHumanoid26.Metadata := MetadataSet27;
HAnimJoint29 := THAnimJointNode.Create;
HAnimJoint29.NameField := 'humanoid_root';
HAnimJoint29.SetUlimit([0,0,0]);
HAnimJoint29.SetLlimit([0,0,0]);
{ Might consider putting a HAnimSegment here, but that doesn't help with re-use of this hand model }
HAnimJoint30 := THAnimJointNode.Create;
HAnimJoint30.NameField := 'l_radiocarpal';
HAnimJoint30.Description := 'connection joint of hand to leg above';
HAnimJoint30.SetUlimit([0,0,0]);
HAnimJoint30.SetLlimit([0,0,0]);
HAnimSegment31 := THAnimSegmentNode.Create;
HAnimSegment31.NameField := 'l_carpal';
Transform32 := TTransformNode.Create;
Shape33 := TShapeNode.Create;
Sphere34 := TSphereNode.Create;
Sphere34.Radius := 0.025;
{ .SetGeometry }
Shape33.Geometry := Sphere34;
Appearance35 := TAppearanceNode.Create;
Material36 := TMaterialNode.Create;
Material36.DiffuseColor := Vector3(0,0,1);
{ .SetMaterial }
Appearance35.Material := Material36;
{ .SetAppearance }
Shape33.Appearance := Appearance35;
{ .AddChild }
Transform32.AddChildren([Shape33]);
{ .AddChildren }
HAnimSegment31.AddChildren([Transform32]);
Shape37 := TShapeNode.Create;
Appearance38 := TAppearanceNode.Create;
Material39 := TMaterialNode.Create;
Material39.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance38.Material := Material39;
{ .SetAppearance }
Shape37.Appearance := Appearance38;
IndexedLineSet40 := TIndexedLineSetNode.Create;
IndexedLineSet40.SetCoordIndex([0,1]);
Coordinate41 := TCoordinateNode.Create;
Coordinate41.SetPoint([Vector3(0,0,0),Vector3(0.1,0.1,0)]);
{ .SetCoord }
IndexedLineSet40.Coord := Coordinate41;
{ .SetGeometry }
Shape37.Geometry := IndexedLineSet40;
{ .AddChildren }
HAnimSegment31.AddChildren([Shape37]);
Shape42 := TShapeNode.Create;
Appearance43 := TAppearanceNode.Create;
Material44 := TMaterialNode.Create;
Material44.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance43.Material := Material44;
{ .SetAppearance }
Shape42.Appearance := Appearance43;
IndexedLineSet45 := TIndexedLineSetNode.Create;
IndexedLineSet45.SetCoordIndex([0,1]);
Coordinate46 := TCoordinateNode.Create;
Coordinate46.SetPoint([Vector3(0,0,0),Vector3(0,0.07,0)]);
{ .SetCoord }
IndexedLineSet45.Coord := Coordinate46;
{ .SetGeometry }
Shape42.Geometry := IndexedLineSet45;
{ .AddChildren }
HAnimSegment31.AddChildren([Shape42]);
Shape47 := TShapeNode.Create;
Appearance48 := TAppearanceNode.Create;
Material49 := TMaterialNode.Create;
Material49.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance48.Material := Material49;
{ .SetAppearance }
Shape47.Appearance := Appearance48;
IndexedLineSet50 := TIndexedLineSetNode.Create;
IndexedLineSet50.SetCoordIndex([0,1]);
Coordinate51 := TCoordinateNode.Create;
Coordinate51.SetPoint([Vector3(0,0,0),Vector3(-0.1,0.1,0)]);
{ .SetCoord }
IndexedLineSet50.Coord := Coordinate51;
{ .SetGeometry }
Shape47.Geometry := IndexedLineSet50;
{ .AddChildren }
HAnimSegment31.AddChildren([Shape47]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimSegment31]);
{ MC1 }
HAnimJoint52 := THAnimJointNode.Create;
HAnimJoint52.NameField := 'l_midcarpal_1';
HAnimJoint52.Center := Vector3(0.14,0.09,0);
HAnimJoint52.SetUlimit([0,0,0]);
HAnimJoint52.SetLlimit([0,0,0]);
HAnimSegment53 := THAnimSegmentNode.Create;
HAnimSegment53.NameField := 'l_trapezium';
Transform54 := TTransformNode.Create;
Transform54.Translation := Vector3(0.14,0.09,0);
Shape55 := TShapeNode.Create;
Sphere56 := TSphereNode.Create;
Sphere56.Radius := 0.025;
{ .SetGeometry }
Shape55.Geometry := Sphere56;
Appearance57 := TAppearanceNode.Create;
Material58 := TMaterialNode.Create;
Material58.DiffuseColor := Vector3(1,0,0);
{ .SetMaterial }
Appearance57.Material := Material58;
{ .SetAppearance }
Shape55.Appearance := Appearance57;
{ .AddChild }
Transform54.AddChildren([Shape55]);
{ .AddChildren }
HAnimSegment53.AddChildren([Transform54]);
Shape59 := TShapeNode.Create;
Appearance60 := TAppearanceNode.Create;
Material61 := TMaterialNode.Create;
Material61.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance60.Material := Material61;
{ .SetAppearance }
Shape59.Appearance := Appearance60;
IndexedLineSet62 := TIndexedLineSetNode.Create;
IndexedLineSet62.SetCoordIndex([0,1]);
Coordinate63 := TCoordinateNode.Create;
Coordinate63.SetPoint([Vector3(0.1,0.1,0),Vector3(0.2,0.15,0)]);
{ .SetCoord }
IndexedLineSet62.Coord := Coordinate63;
{ .SetGeometry }
Shape59.Geometry := IndexedLineSet62;
{ .AddChildren }
HAnimSegment53.AddChildren([Shape59]);
Shape64 := TShapeNode.Create;
Appearance65 := TAppearanceNode.Create;
Material66 := TMaterialNode.Create;
Material66.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance65.Material := Material66;
{ .SetAppearance }
Shape64.Appearance := Appearance65;
IndexedLineSet67 := TIndexedLineSetNode.Create;
IndexedLineSet67.SetCoordIndex([0,1]);
Coordinate68 := TCoordinateNode.Create;
Coordinate68.SetPoint([Vector3(0.1,0.1,0),Vector3(0.1,0.2,0)]);
{ .SetCoord }
IndexedLineSet67.Coord := Coordinate68;
{ .SetGeometry }
Shape64.Geometry := IndexedLineSet67;
{ .AddChildren }
HAnimSegment53.AddChildren([Shape64]);
{ .AddChildren }
HAnimJoint52.AddChildren([HAnimSegment53]);
{ thumb finger }
HAnimJoint69 := THAnimJointNode.Create;
HAnimJoint69.NameField := 'l_carpometacarpal_1';
HAnimJoint69.Center := Vector3(0.2,0.15,0);
HAnimJoint69.SetUlimit([0,0,0]);
HAnimJoint69.SetLlimit([0,0,0]);
HAnimSegment70 := THAnimSegmentNode.Create;
HAnimSegment70.NameField := 'l_metacarpal_1';
Transform71 := TTransformNode.Create;
Transform71.Translation := Vector3(0.2,0.15,0);
Shape72 := TShapeNode.Create;
Shape72 := Shape33;
{ .AddChild }
Transform71.AddChildren([Shape72]);
{ .AddChildren }
HAnimSegment70.AddChildren([Transform71]);
Shape73 := TShapeNode.Create;
Appearance74 := TAppearanceNode.Create;
Material75 := TMaterialNode.Create;
Material75.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance74.Material := Material75;
{ .SetAppearance }
Shape73.Appearance := Appearance74;
IndexedLineSet76 := TIndexedLineSetNode.Create;
IndexedLineSet76.SetCoordIndex([0,1]);
Coordinate77 := TCoordinateNode.Create;
Coordinate77.SetPoint([Vector3(0.2,0.15,0),Vector3(0.3,0.3,0)]);
{ .SetCoord }
IndexedLineSet76.Coord := Coordinate77;
{ .SetGeometry }
Shape73.Geometry := IndexedLineSet76;
{ .AddChildren }
HAnimSegment70.AddChildren([Shape73]);
{ .AddChildren }
HAnimJoint69.AddChildren([HAnimSegment70]);
HAnimJoint78 := THAnimJointNode.Create;
HAnimJoint78.NameField := 'l_metacarpophalangeal_1';
HAnimJoint78.Center := Vector3(0.3,0.3,0);
HAnimJoint78.SetUlimit([0,0,0]);
HAnimJoint78.SetLlimit([0,0,0]);
HAnimSegment79 := THAnimSegmentNode.Create;
HAnimSegment79.NameField := 'l_carpal_proximal_phalanx_1';
Transform80 := TTransformNode.Create;
Transform80.Translation := Vector3(0.3,0.3,0);
Shape81 := TShapeNode.Create;
Shape81 := Shape33;
{ .AddChild }
Transform80.AddChildren([Shape81]);
{ .AddChildren }
HAnimSegment79.AddChildren([Transform80]);
Shape82 := TShapeNode.Create;
Appearance83 := TAppearanceNode.Create;
Material84 := TMaterialNode.Create;
Material84.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance83.Material := Material84;
{ .SetAppearance }
Shape82.Appearance := Appearance83;
IndexedLineSet85 := TIndexedLineSetNode.Create;
IndexedLineSet85.SetCoordIndex([0,1]);
Coordinate86 := TCoordinateNode.Create;
Coordinate86.SetPoint([Vector3(0.3,0.3,0),Vector3(0.35,0.4,0)]);
{ .SetCoord }
IndexedLineSet85.Coord := Coordinate86;
{ .SetGeometry }
Shape82.Geometry := IndexedLineSet85;
{ .AddChildren }
HAnimSegment79.AddChildren([Shape82]);
{ .AddChildren }
HAnimJoint78.AddChildren([HAnimSegment79]);
HAnimJoint87 := THAnimJointNode.Create;
HAnimJoint87.NameField := 'l_carpal_interphalangeal_1';
HAnimJoint87.Center := Vector3(0.35,0.4,0);
HAnimJoint87.SetUlimit([0,0,0]);
HAnimJoint87.SetLlimit([0,0,0]);
HAnimSegment88 := THAnimSegmentNode.Create;
HAnimSegment88.NameField := 'l_carpal_distal_phalanx_1';
Transform89 := TTransformNode.Create;
Transform89.Translation := Vector3(0.35,0.4,0);
Shape90 := TShapeNode.Create;
Shape90 := Shape33;
{ .AddChild }
Transform89.AddChildren([Shape90]);
{ .AddChildren }
HAnimSegment88.AddChildren([Transform89]);
Shape91 := TShapeNode.Create;
Appearance92 := TAppearanceNode.Create;
Material93 := TMaterialNode.Create;
Material93.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance92.Material := Material93;
{ .SetAppearance }
Shape91.Appearance := Appearance92;
IndexedLineSet94 := TIndexedLineSetNode.Create;
IndexedLineSet94.SetCoordIndex([0,1]);
Coordinate95 := TCoordinateNode.Create;
Coordinate95.SetPoint([Vector3(0.35,0.4,0),Vector3(0.36,0.45,0)]);
{ .SetCoord }
IndexedLineSet94.Coord := Coordinate95;
{ .SetGeometry }
Shape91.Geometry := IndexedLineSet94;
{ .AddChildren }
HAnimSegment88.AddChildren([Shape91]);
{ .AddChildren }
HAnimJoint87.AddChildren([HAnimSegment88]);
{ .AddChildren }
HAnimJoint78.AddChildren([HAnimJoint87]);
{ .AddChildren }
HAnimJoint69.AddChildren([HAnimJoint78]);
{ .AddChildren }
HAnimJoint52.AddChildren([HAnimJoint69]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimJoint52]);
{ MC2 }
HAnimJoint96 := THAnimJointNode.Create;
HAnimJoint96.NameField := 'l_midcarpal_2';
HAnimJoint96.Center := Vector3(0.07,0.07,0);
HAnimJoint96.SetUlimit([0,0,0]);
HAnimJoint96.SetLlimit([0,0,0]);
HAnimSegment97 := THAnimSegmentNode.Create;
HAnimSegment97.NameField := 'l_trapezoid';
Transform98 := TTransformNode.Create;
Transform98.Translation := Vector3(0.07,0.07,0);
Shape99 := TShapeNode.Create;
Shape99 := Shape55;
{ .AddChild }
Transform98.AddChildren([Shape99]);
{ .AddChildren }
HAnimSegment97.AddChildren([Transform98]);
Shape100 := TShapeNode.Create;
Appearance101 := TAppearanceNode.Create;
Material102 := TMaterialNode.Create;
Material102.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance101.Material := Material102;
{ .SetAppearance }
Shape100.Appearance := Appearance101;
IndexedLineSet103 := TIndexedLineSetNode.Create;
IndexedLineSet103.SetCoordIndex([0,1]);
Coordinate104 := TCoordinateNode.Create;
Coordinate104.SetPoint([Vector3(-0.1,0.1,0),Vector3(-0.1,0.2,0)]);
{ .SetCoord }
IndexedLineSet103.Coord := Coordinate104;
{ .SetGeometry }
Shape100.Geometry := IndexedLineSet103;
{ .AddChildren }
HAnimSegment97.AddChildren([Shape100]);
{ .AddChildren }
HAnimJoint96.AddChildren([HAnimSegment97]);
{ index finger }
HAnimJoint105 := THAnimJointNode.Create;
HAnimJoint105.NameField := 'l_carpometacarpal_2';
HAnimJoint105.Center := Vector3(0.1,0.2,0);
HAnimJoint105.SetUlimit([0,0,0]);
HAnimJoint105.SetLlimit([0,0,0]);
HAnimSegment106 := THAnimSegmentNode.Create;
HAnimSegment106.NameField := 'l_metacarpal_2';
Transform107 := TTransformNode.Create;
Transform107.Translation := Vector3(0.1,0.2,0);
Shape108 := TShapeNode.Create;
Shape108 := Shape33;
{ .AddChild }
Transform107.AddChildren([Shape108]);
{ .AddChildren }
HAnimSegment106.AddChildren([Transform107]);
Shape109 := TShapeNode.Create;
Appearance110 := TAppearanceNode.Create;
Material111 := TMaterialNode.Create;
Material111.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance110.Material := Material111;
{ .SetAppearance }
Shape109.Appearance := Appearance110;
IndexedLineSet112 := TIndexedLineSetNode.Create;
IndexedLineSet112.SetCoordIndex([0,1]);
Coordinate113 := TCoordinateNode.Create;
Coordinate113.SetPoint([Vector3(0.1,0.2,0),Vector3(0.15,0.5,0)]);
{ .SetCoord }
IndexedLineSet112.Coord := Coordinate113;
{ .SetGeometry }
Shape109.Geometry := IndexedLineSet112;
{ .AddChildren }
HAnimSegment106.AddChildren([Shape109]);
{ .AddChildren }
HAnimJoint105.AddChildren([HAnimSegment106]);
HAnimJoint114 := THAnimJointNode.Create;
HAnimJoint114.NameField := 'l_metacarpophalangeal_2';
HAnimJoint114.Center := Vector3(0.15,0.5,0);
HAnimJoint114.SetUlimit([0,0,0]);
HAnimJoint114.SetLlimit([0,0,0]);
HAnimSegment115 := THAnimSegmentNode.Create;
HAnimSegment115.NameField := 'l_carpal_proximal_phalanx_2';
Transform116 := TTransformNode.Create;
Transform116.Translation := Vector3(0.15,0.5,0);
Shape117 := TShapeNode.Create;
Shape117 := Shape33;
{ .AddChild }
Transform116.AddChildren([Shape117]);
{ .AddChildren }
HAnimSegment115.AddChildren([Transform116]);
Shape118 := TShapeNode.Create;
Appearance119 := TAppearanceNode.Create;
Material120 := TMaterialNode.Create;
Material120.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance119.Material := Material120;
{ .SetAppearance }
Shape118.Appearance := Appearance119;
IndexedLineSet121 := TIndexedLineSetNode.Create;
IndexedLineSet121.SetCoordIndex([0,1]);
Coordinate122 := TCoordinateNode.Create;
Coordinate122.SetPoint([Vector3(0.15,0.5,0),Vector3(0.2,0.7,0)]);
{ .SetCoord }
IndexedLineSet121.Coord := Coordinate122;
{ .SetGeometry }
Shape118.Geometry := IndexedLineSet121;
{ .AddChildren }
HAnimSegment115.AddChildren([Shape118]);
{ .AddChildren }
HAnimJoint114.AddChildren([HAnimSegment115]);
HAnimJoint123 := THAnimJointNode.Create;
HAnimJoint123.NameField := 'l_carpal_proximal_interphalangeal_2';
HAnimJoint123.Center := Vector3(0.2,0.7,0);
HAnimJoint123.SetUlimit([0,0,0]);
HAnimJoint123.SetLlimit([0,0,0]);
HAnimSegment124 := THAnimSegmentNode.Create;
HAnimSegment124.NameField := 'l_carpal_middle_phalanx_2';
Transform125 := TTransformNode.Create;
Transform125.Translation := Vector3(0.2,0.7,0);
Shape126 := TShapeNode.Create;
Shape126 := Shape33;
{ .AddChild }
Transform125.AddChildren([Shape126]);
{ .AddChildren }
HAnimSegment124.AddChildren([Transform125]);
Shape127 := TShapeNode.Create;
Appearance128 := TAppearanceNode.Create;
Material129 := TMaterialNode.Create;
Material129.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance128.Material := Material129;
{ .SetAppearance }
Shape127.Appearance := Appearance128;
IndexedLineSet130 := TIndexedLineSetNode.Create;
IndexedLineSet130.SetCoordIndex([0,1]);
Coordinate131 := TCoordinateNode.Create;
Coordinate131.SetPoint([Vector3(0.2,0.7,0),Vector3(0.24,0.87,0)]);
{ .SetCoord }
IndexedLineSet130.Coord := Coordinate131;
{ .SetGeometry }
Shape127.Geometry := IndexedLineSet130;
{ .AddChildren }
HAnimSegment124.AddChildren([Shape127]);
{ .AddChildren }
HAnimJoint123.AddChildren([HAnimSegment124]);
HAnimJoint132 := THAnimJointNode.Create;
HAnimJoint132.NameField := 'l_carpal_distal_interphalangeal_2';
HAnimJoint132.Center := Vector3(0.24,0.87,0);
HAnimJoint132.SetUlimit([0,0,0]);
HAnimJoint132.SetLlimit([0,0,0]);
HAnimSegment133 := THAnimSegmentNode.Create;
HAnimSegment133.NameField := 'l_carpal_distal_phalanx_2';
Transform134 := TTransformNode.Create;
Transform134.Translation := Vector3(0.24,0.87,0);
Shape135 := TShapeNode.Create;
Shape135 := Shape33;
{ .AddChild }
Transform134.AddChildren([Shape135]);
{ .AddChildren }
HAnimSegment133.AddChildren([Transform134]);
Shape136 := TShapeNode.Create;
Appearance137 := TAppearanceNode.Create;
Material138 := TMaterialNode.Create;
Material138.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance137.Material := Material138;
{ .SetAppearance }
Shape136.Appearance := Appearance137;
IndexedLineSet139 := TIndexedLineSetNode.Create;
IndexedLineSet139.SetCoordIndex([0,1]);
Coordinate140 := TCoordinateNode.Create;
Coordinate140.SetPoint([Vector3(0.24,0.87,0),Vector3(0.26,0.93,0)]);
{ .SetCoord }
IndexedLineSet139.Coord := Coordinate140;
{ .SetGeometry }
Shape136.Geometry := IndexedLineSet139;
{ .AddChildren }
HAnimSegment133.AddChildren([Shape136]);
{ .AddChildren }
HAnimJoint132.AddChildren([HAnimSegment133]);
{ .AddChildren }
HAnimJoint123.AddChildren([HAnimJoint132]);
{ .AddChildren }
HAnimJoint114.AddChildren([HAnimJoint123]);
{ .AddChildren }
HAnimJoint105.AddChildren([HAnimJoint114]);
{ .AddChildren }
HAnimJoint96.AddChildren([HAnimJoint105]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimJoint96]);
{ MC3 }
HAnimJoint141 := THAnimJointNode.Create;
HAnimJoint141.NameField := 'l_midcarpal_3';
HAnimJoint141.Center := Vector3(0,0.07,0);
HAnimJoint141.SetUlimit([0,0,0]);
HAnimJoint141.SetLlimit([0,0,0]);
HAnimSegment142 := THAnimSegmentNode.Create;
HAnimSegment142.NameField := 'l_capitate';
Transform143 := TTransformNode.Create;
Transform143.Translation := Vector3(0,0.07,0);
Shape144 := TShapeNode.Create;
Shape144 := Shape55;
{ .AddChild }
Transform143.AddChildren([Shape144]);
{ .AddChildren }
HAnimSegment142.AddChildren([Transform143]);
Shape145 := TShapeNode.Create;
Appearance146 := TAppearanceNode.Create;
Material147 := TMaterialNode.Create;
Material147.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance146.Material := Material147;
{ .SetAppearance }
Shape145.Appearance := Appearance146;
IndexedLineSet148 := TIndexedLineSetNode.Create;
IndexedLineSet148.SetCoordIndex([0,1]);
Coordinate149 := TCoordinateNode.Create;
Coordinate149.SetPoint([Vector3(0,0.07,0),Vector3(0,0.2,0)]);
{ .SetCoord }
IndexedLineSet148.Coord := Coordinate149;
{ .SetGeometry }
Shape145.Geometry := IndexedLineSet148;
{ .AddChildren }
HAnimSegment142.AddChildren([Shape145]);
{ .AddChildren }
HAnimJoint141.AddChildren([HAnimSegment142]);
{ Middle fingle }
HAnimJoint150 := THAnimJointNode.Create;
HAnimJoint150.NameField := 'l_carpometacarpal_3';
HAnimJoint150.Center := Vector3(0,0.2,0);
HAnimJoint150.SetUlimit([0,0,0]);
HAnimJoint150.SetLlimit([0,0,0]);
HAnimSegment151 := THAnimSegmentNode.Create;
HAnimSegment151.NameField := 'l_metacarpal_3';
Transform152 := TTransformNode.Create;
Transform152.Translation := Vector3(0,0.2,0);
Shape153 := TShapeNode.Create;
Shape153 := Shape33;
{ .AddChild }
Transform152.AddChildren([Shape153]);
{ .AddChildren }
HAnimSegment151.AddChildren([Transform152]);
Shape154 := TShapeNode.Create;
Appearance155 := TAppearanceNode.Create;
Material156 := TMaterialNode.Create;
Material156.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance155.Material := Material156;
{ .SetAppearance }
Shape154.Appearance := Appearance155;
IndexedLineSet157 := TIndexedLineSetNode.Create;
IndexedLineSet157.SetCoordIndex([0,1]);
Coordinate158 := TCoordinateNode.Create;
Coordinate158.SetPoint([Vector3(0,0.2,0),Vector3(0.03,0.5,0)]);
{ .SetCoord }
IndexedLineSet157.Coord := Coordinate158;
{ .SetGeometry }
Shape154.Geometry := IndexedLineSet157;
{ .AddChildren }
HAnimSegment151.AddChildren([Shape154]);
{ .AddChildren }
HAnimJoint150.AddChildren([HAnimSegment151]);
HAnimJoint159 := THAnimJointNode.Create;
HAnimJoint159.NameField := 'l_metacarpophalangeal_3';
HAnimJoint159.Center := Vector3(0.03,0.5,0);
HAnimJoint159.SetUlimit([0,0,0]);
HAnimJoint159.SetLlimit([0,0,0]);
HAnimSegment160 := THAnimSegmentNode.Create;
HAnimSegment160.NameField := 'l_carpal_proximal_phalanx_3';
Transform161 := TTransformNode.Create;
Transform161.Translation := Vector3(0.03,0.5,0);
Shape162 := TShapeNode.Create;
Shape162 := Shape33;
{ .AddChild }
Transform161.AddChildren([Shape162]);
{ .AddChildren }
HAnimSegment160.AddChildren([Transform161]);
Shape163 := TShapeNode.Create;
Appearance164 := TAppearanceNode.Create;
Material165 := TMaterialNode.Create;
Material165.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance164.Material := Material165;
{ .SetAppearance }
Shape163.Appearance := Appearance164;
IndexedLineSet166 := TIndexedLineSetNode.Create;
IndexedLineSet166.SetCoordIndex([0,1]);
Coordinate167 := TCoordinateNode.Create;
Coordinate167.SetPoint([Vector3(0.03,0.5,0),Vector3(0.05,0.75,0)]);
{ .SetCoord }
IndexedLineSet166.Coord := Coordinate167;
{ .SetGeometry }
Shape163.Geometry := IndexedLineSet166;
{ .AddChildren }
HAnimSegment160.AddChildren([Shape163]);
{ .AddChildren }
HAnimJoint159.AddChildren([HAnimSegment160]);
HAnimJoint168 := THAnimJointNode.Create;
HAnimJoint168.NameField := 'l_carpal_proximal_interphalangeal_3';
HAnimJoint168.Center := Vector3(0.05,0.75,0);
HAnimJoint168.SetUlimit([0,0,0]);
HAnimJoint168.SetLlimit([0,0,0]);
HAnimSegment169 := THAnimSegmentNode.Create;
HAnimSegment169.NameField := 'l_carpal_middle_phalanx_3';
Transform170 := TTransformNode.Create;
Transform170.Translation := Vector3(0.05,0.75,0);
Shape171 := TShapeNode.Create;
Shape171 := Shape33;
{ .AddChild }
Transform170.AddChildren([Shape171]);
{ .AddChildren }
HAnimSegment169.AddChildren([Transform170]);
Shape172 := TShapeNode.Create;
Appearance173 := TAppearanceNode.Create;
Material174 := TMaterialNode.Create;
Material174.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance173.Material := Material174;
{ .SetAppearance }
Shape172.Appearance := Appearance173;
IndexedLineSet175 := TIndexedLineSetNode.Create;
IndexedLineSet175.SetCoordIndex([0,1]);
Coordinate176 := TCoordinateNode.Create;
Coordinate176.SetPoint([Vector3(0.05,0.75,0),Vector3(0.08,0.96,0)]);
{ .SetCoord }
IndexedLineSet175.Coord := Coordinate176;
{ .SetGeometry }
Shape172.Geometry := IndexedLineSet175;
{ .AddChildren }
HAnimSegment169.AddChildren([Shape172]);
{ .AddChildren }
HAnimJoint168.AddChildren([HAnimSegment169]);
HAnimJoint177 := THAnimJointNode.Create;
HAnimJoint177.NameField := 'l_carpal_distal_interphalangeal_3';
HAnimJoint177.Center := Vector3(0.08,0.96,0);
HAnimJoint177.SetUlimit([0,0,0]);
HAnimJoint177.SetLlimit([0,0,0]);
HAnimSegment178 := THAnimSegmentNode.Create;
HAnimSegment178.NameField := 'l_carpal_distal_phalanx_3';
Transform179 := TTransformNode.Create;
Transform179.Translation := Vector3(0.08,0.96,0);
Shape180 := TShapeNode.Create;
Shape180 := Shape33;
{ .AddChild }
Transform179.AddChildren([Shape180]);
{ .AddChildren }
HAnimSegment178.AddChildren([Transform179]);
Shape181 := TShapeNode.Create;
Appearance182 := TAppearanceNode.Create;
Material183 := TMaterialNode.Create;
Material183.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance182.Material := Material183;
{ .SetAppearance }
Shape181.Appearance := Appearance182;
IndexedLineSet184 := TIndexedLineSetNode.Create;
IndexedLineSet184.SetCoordIndex([0,1]);
Coordinate185 := TCoordinateNode.Create;
Coordinate185.SetPoint([Vector3(0.08,0.96,0),Vector3(0.09,1.05,0)]);
{ .SetCoord }
IndexedLineSet184.Coord := Coordinate185;
{ .SetGeometry }
Shape181.Geometry := IndexedLineSet184;
{ .AddChildren }
HAnimSegment178.AddChildren([Shape181]);
{ .AddChildren }
HAnimJoint177.AddChildren([HAnimSegment178]);
{ .AddChildren }
HAnimJoint168.AddChildren([HAnimJoint177]);
{ .AddChildren }
HAnimJoint159.AddChildren([HAnimJoint168]);
{ .AddChildren }
HAnimJoint150.AddChildren([HAnimJoint159]);
{ .AddChildren }
HAnimJoint141.AddChildren([HAnimJoint150]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimJoint141]);
{ MC45 }
HAnimJoint186 := THAnimJointNode.Create;
HAnimJoint186.NameField := 'l_midcarpal_4_5';
HAnimJoint186.Center := Vector3(-0.1,0.1,0);
HAnimJoint186.SetUlimit([0,0,0]);
HAnimJoint186.SetLlimit([0,0,0]);
HAnimSegment187 := THAnimSegmentNode.Create;
HAnimSegment187.NameField := 'l_hamate';
Transform188 := TTransformNode.Create;
Transform188.Translation := Vector3(-0.1,0.1,0);
Shape189 := TShapeNode.Create;
Shape189 := Shape55;
{ .AddChild }
Transform188.AddChildren([Shape189]);
{ .AddChildren }
HAnimSegment187.AddChildren([Transform188]);
Shape190 := TShapeNode.Create;
Appearance191 := TAppearanceNode.Create;
Material192 := TMaterialNode.Create;
Material192.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance191.Material := Material192;
{ .SetAppearance }
Shape190.Appearance := Appearance191;
IndexedLineSet193 := TIndexedLineSetNode.Create;
IndexedLineSet193.SetCoordIndex([0,1]);
Coordinate194 := TCoordinateNode.Create;
Coordinate194.SetPoint([Vector3(-0.1,0.1,0),Vector3(-0.1,0.2,0)]);
{ .SetCoord }
IndexedLineSet193.Coord := Coordinate194;
{ .SetGeometry }
Shape190.Geometry := IndexedLineSet193;
{ .AddChildren }
HAnimSegment187.AddChildren([Shape190]);
Shape195 := TShapeNode.Create;
Appearance196 := TAppearanceNode.Create;
Material197 := TMaterialNode.Create;
Material197.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance196.Material := Material197;
{ .SetAppearance }
Shape195.Appearance := Appearance196;
IndexedLineSet198 := TIndexedLineSetNode.Create;
IndexedLineSet198.SetCoordIndex([0,1]);
Coordinate199 := TCoordinateNode.Create;
Coordinate199.SetPoint([Vector3(-0.1,0.1,0),Vector3(-0.15,0.17,0)]);
{ .SetCoord }
IndexedLineSet198.Coord := Coordinate199;
{ .SetGeometry }
Shape195.Geometry := IndexedLineSet198;
{ .AddChildren }
HAnimSegment187.AddChildren([Shape195]);
{ .AddChildren }
HAnimJoint186.AddChildren([HAnimSegment187]);
{ ring finger }
HAnimJoint200 := THAnimJointNode.Create;
HAnimJoint200.NameField := 'l_carpometacarpal_4';
HAnimJoint200.Center := Vector3(-0.1,0.2,0);
HAnimJoint200.SetUlimit([0,0,0]);
HAnimJoint200.SetLlimit([0,0,0]);
HAnimSegment201 := THAnimSegmentNode.Create;
HAnimSegment201.NameField := 'l_metacarpal_4';
Transform202 := TTransformNode.Create;
Transform202.Translation := Vector3(-0.1,0.2,0);
Shape203 := TShapeNode.Create;
Shape203 := Shape33;
{ .AddChild }
Transform202.AddChildren([Shape203]);
{ .AddChildren }
HAnimSegment201.AddChildren([Transform202]);
Shape204 := TShapeNode.Create;
Appearance205 := TAppearanceNode.Create;
Material206 := TMaterialNode.Create;
Material206.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance205.Material := Material206;
{ .SetAppearance }
Shape204.Appearance := Appearance205;
IndexedLineSet207 := TIndexedLineSetNode.Create;
IndexedLineSet207.SetCoordIndex([0,1]);
Coordinate208 := TCoordinateNode.Create;
Coordinate208.SetPoint([Vector3(-0.1,0.2,0),Vector3(-0.1,0.47,0)]);
{ .SetCoord }
IndexedLineSet207.Coord := Coordinate208;
{ .SetGeometry }
Shape204.Geometry := IndexedLineSet207;
{ .AddChildren }
HAnimSegment201.AddChildren([Shape204]);
{ .AddChildren }
HAnimJoint200.AddChildren([HAnimSegment201]);
HAnimJoint209 := THAnimJointNode.Create;
HAnimJoint209.NameField := 'l_metacarpophalangeal_4';
HAnimJoint209.Center := Vector3(-0.1,0.47,0);
HAnimJoint209.SetUlimit([0,0,0]);
HAnimJoint209.SetLlimit([0,0,0]);
HAnimSegment210 := THAnimSegmentNode.Create;
HAnimSegment210.NameField := 'l_carpal_proximal_phalanx_4';
Transform211 := TTransformNode.Create;
Transform211.Translation := Vector3(-0.1,0.47,0);
Shape212 := TShapeNode.Create;
Shape212 := Shape33;
{ .AddChild }
Transform211.AddChildren([Shape212]);
{ .AddChildren }
HAnimSegment210.AddChildren([Transform211]);
Shape213 := TShapeNode.Create;
Appearance214 := TAppearanceNode.Create;
Material215 := TMaterialNode.Create;
Material215.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance214.Material := Material215;
{ .SetAppearance }
Shape213.Appearance := Appearance214;
IndexedLineSet216 := TIndexedLineSetNode.Create;
IndexedLineSet216.SetCoordIndex([0,1]);
Coordinate217 := TCoordinateNode.Create;
Coordinate217.SetPoint([Vector3(-0.1,0.47,0),Vector3(-0.1,0.7,0)]);
{ .SetCoord }
IndexedLineSet216.Coord := Coordinate217;
{ .SetGeometry }
Shape213.Geometry := IndexedLineSet216;
{ .AddChildren }
HAnimSegment210.AddChildren([Shape213]);
{ .AddChildren }
HAnimJoint209.AddChildren([HAnimSegment210]);
HAnimJoint218 := THAnimJointNode.Create;
HAnimJoint218.NameField := 'l_carpal_proximal_interphalangeal_4';
HAnimJoint218.Center := Vector3(-0.1,0.7,0);
HAnimJoint218.SetUlimit([0,0,0]);
HAnimJoint218.SetLlimit([0,0,0]);
HAnimSegment219 := THAnimSegmentNode.Create;
HAnimSegment219.NameField := 'l_carpal_middle_phalanx_4';
Transform220 := TTransformNode.Create;
Transform220.Translation := Vector3(-0.1,0.7,0);
Shape221 := TShapeNode.Create;
Shape221 := Shape33;
{ .AddChild }
Transform220.AddChildren([Shape221]);
{ .AddChildren }
HAnimSegment219.AddChildren([Transform220]);
Shape222 := TShapeNode.Create;
Appearance223 := TAppearanceNode.Create;
Material224 := TMaterialNode.Create;
Material224.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance223.Material := Material224;
{ .SetAppearance }
Shape222.Appearance := Appearance223;
IndexedLineSet225 := TIndexedLineSetNode.Create;
IndexedLineSet225.SetCoordIndex([0,1]);
Coordinate226 := TCoordinateNode.Create;
Coordinate226.SetPoint([Vector3(-0.1,0.7,0),Vector3(-0.1,0.93,0)]);
{ .SetCoord }
IndexedLineSet225.Coord := Coordinate226;
{ .SetGeometry }
Shape222.Geometry := IndexedLineSet225;
{ .AddChildren }
HAnimSegment219.AddChildren([Shape222]);
{ .AddChildren }
HAnimJoint218.AddChildren([HAnimSegment219]);
HAnimJoint227 := THAnimJointNode.Create;
HAnimJoint227.NameField := 'l_carpal_distal_interphalangeal_4';
HAnimJoint227.Center := Vector3(-0.1,0.93,0);
HAnimJoint227.SetUlimit([0,0,0]);
HAnimJoint227.SetLlimit([0,0,0]);
HAnimSegment228 := THAnimSegmentNode.Create;
HAnimSegment228.NameField := 'l_carpal_distal_phalanx_4';
Transform229 := TTransformNode.Create;
Transform229.Translation := Vector3(-0.1,0.93,0);
Shape230 := TShapeNode.Create;
Shape230 := Shape33;
{ .AddChild }
Transform229.AddChildren([Shape230]);
{ .AddChildren }
HAnimSegment228.AddChildren([Transform229]);
Shape231 := TShapeNode.Create;
Appearance232 := TAppearanceNode.Create;
Material233 := TMaterialNode.Create;
Material233.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance232.Material := Material233;
{ .SetAppearance }
Shape231.Appearance := Appearance232;
IndexedLineSet234 := TIndexedLineSetNode.Create;
IndexedLineSet234.SetCoordIndex([0,1]);
Coordinate235 := TCoordinateNode.Create;
Coordinate235.SetPoint([Vector3(-0.1,0.93,0),Vector3(-0.1,1,0)]);
{ .SetCoord }
IndexedLineSet234.Coord := Coordinate235;
{ .SetGeometry }
Shape231.Geometry := IndexedLineSet234;
{ .AddChildren }
HAnimSegment228.AddChildren([Shape231]);
{ .AddChildren }
HAnimJoint227.AddChildren([HAnimSegment228]);
{ .AddChildren }
HAnimJoint218.AddChildren([HAnimJoint227]);
{ .AddChildren }
HAnimJoint209.AddChildren([HAnimJoint218]);
{ .AddChildren }
HAnimJoint200.AddChildren([HAnimJoint209]);
{ .AddChildren }
HAnimJoint186.AddChildren([HAnimJoint200]);
{ pinky finger }
HAnimJoint236 := THAnimJointNode.Create;
HAnimJoint236.NameField := 'l_carpometacarpal_5';
HAnimJoint236.Center := Vector3(-0.15,0.17,0);
HAnimJoint236.SetUlimit([0,0,0]);
HAnimJoint236.SetLlimit([0,0,0]);
HAnimSegment237 := THAnimSegmentNode.Create;
HAnimSegment237.NameField := 'l_metacarpal_5';
Transform238 := TTransformNode.Create;
Transform238.Translation := Vector3(-0.15,0.17,0);
Shape239 := TShapeNode.Create;
Shape239 := Shape33;
{ .AddChild }
Transform238.AddChildren([Shape239]);
{ .AddChildren }
HAnimSegment237.AddChildren([Transform238]);
Shape240 := TShapeNode.Create;
Appearance241 := TAppearanceNode.Create;
Material242 := TMaterialNode.Create;
Material242.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance241.Material := Material242;
{ .SetAppearance }
Shape240.Appearance := Appearance241;
IndexedLineSet243 := TIndexedLineSetNode.Create;
IndexedLineSet243.SetCoordIndex([0,1]);
Coordinate244 := TCoordinateNode.Create;
Coordinate244.SetPoint([Vector3(-0.15,0.17,0),Vector3(-0.2,0.4,0)]);
{ .SetCoord }
IndexedLineSet243.Coord := Coordinate244;
{ .SetGeometry }
Shape240.Geometry := IndexedLineSet243;
{ .AddChildren }
HAnimSegment237.AddChildren([Shape240]);
{ .AddChildren }
HAnimJoint236.AddChildren([HAnimSegment237]);
HAnimJoint245 := THAnimJointNode.Create;
HAnimJoint245.NameField := 'l_metacarpophalangeal_5';
HAnimJoint245.Center := Vector3(-0.2,0.4,0);
HAnimJoint245.SetUlimit([0,0,0]);
HAnimJoint245.SetLlimit([0,0,0]);
HAnimSegment246 := THAnimSegmentNode.Create;
HAnimSegment246.NameField := 'l_carpal_proximal_phalanx_5';
Transform247 := TTransformNode.Create;
Transform247.Translation := Vector3(-0.2,0.4,0);
Shape248 := TShapeNode.Create;
Shape248 := Shape33;
{ .AddChild }
Transform247.AddChildren([Shape248]);
{ .AddChildren }
HAnimSegment246.AddChildren([Transform247]);
Shape249 := TShapeNode.Create;
Appearance250 := TAppearanceNode.Create;
Material251 := TMaterialNode.Create;
Material251.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance250.Material := Material251;
{ .SetAppearance }
Shape249.Appearance := Appearance250;
IndexedLineSet252 := TIndexedLineSetNode.Create;
IndexedLineSet252.SetCoordIndex([0,1]);
Coordinate253 := TCoordinateNode.Create;
Coordinate253.SetPoint([Vector3(-0.2,0.4,0),Vector3(-0.23,0.63,0)]);
{ .SetCoord }
IndexedLineSet252.Coord := Coordinate253;
{ .SetGeometry }
Shape249.Geometry := IndexedLineSet252;
{ .AddChildren }
HAnimSegment246.AddChildren([Shape249]);
{ .AddChildren }
HAnimJoint245.AddChildren([HAnimSegment246]);
HAnimJoint254 := THAnimJointNode.Create;
HAnimJoint254.NameField := 'l_carpal_proximal_interphalangeal_5';
HAnimJoint254.Center := Vector3(-0.23,0.63,0);
HAnimJoint254.SetUlimit([0,0,0]);
HAnimJoint254.SetLlimit([0,0,0]);
HAnimSegment255 := THAnimSegmentNode.Create;
HAnimSegment255.NameField := 'l_carpal_middle_phalanx_5';
Transform256 := TTransformNode.Create;
Transform256.Translation := Vector3(-0.23,0.63,0);
Shape257 := TShapeNode.Create;
Shape257 := Shape33;
{ .AddChild }
Transform256.AddChildren([Shape257]);
{ .AddChildren }
HAnimSegment255.AddChildren([Transform256]);
Shape258 := TShapeNode.Create;
Appearance259 := TAppearanceNode.Create;
Material260 := TMaterialNode.Create;
Material260.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance259.Material := Material260;
{ .SetAppearance }
Shape258.Appearance := Appearance259;
IndexedLineSet261 := TIndexedLineSetNode.Create;
IndexedLineSet261.SetCoordIndex([0,1]);
Coordinate262 := TCoordinateNode.Create;
Coordinate262.SetPoint([Vector3(-0.23,0.63,0),Vector3(-0.25,0.79,0)]);
{ .SetCoord }
IndexedLineSet261.Coord := Coordinate262;
{ .SetGeometry }
Shape258.Geometry := IndexedLineSet261;
{ .AddChildren }
HAnimSegment255.AddChildren([Shape258]);
{ .AddChildren }
HAnimJoint254.AddChildren([HAnimSegment255]);
HAnimJoint263 := THAnimJointNode.Create;
HAnimJoint263.NameField := 'l_carpal_distal_interphalangeal_5';
HAnimJoint263.Center := Vector3(-0.25,0.79,0);
HAnimJoint263.SetUlimit([0,0,0]);
HAnimJoint263.SetLlimit([0,0,0]);
HAnimSegment264 := THAnimSegmentNode.Create;
HAnimSegment264.NameField := 'l_carpal_distal_phalanx_5';
Transform265 := TTransformNode.Create;
Transform265.Translation := Vector3(-0.25,0.79,0);
Shape266 := TShapeNode.Create;
Shape266 := Shape33;
{ .AddChild }
Transform265.AddChildren([Shape266]);
{ .AddChildren }
HAnimSegment264.AddChildren([Transform265]);
Shape267 := TShapeNode.Create;
Appearance268 := TAppearanceNode.Create;
Material269 := TMaterialNode.Create;
Material269.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance268.Material := Material269;
{ .SetAppearance }
Shape267.Appearance := Appearance268;
IndexedLineSet270 := TIndexedLineSetNode.Create;
IndexedLineSet270.SetCoordIndex([0,1]);
Coordinate271 := TCoordinateNode.Create;
Coordinate271.SetPoint([Vector3(-0.25,0.79,0),Vector3(-0.26,0.85,0)]);
{ .SetCoord }
IndexedLineSet270.Coord := Coordinate271;
{ .SetGeometry }
Shape267.Geometry := IndexedLineSet270;
{ .AddChildren }
HAnimSegment264.AddChildren([Shape267]);
{ .AddChildren }
HAnimJoint263.AddChildren([HAnimSegment264]);
{ .AddChildren }
HAnimJoint254.AddChildren([HAnimJoint263]);
{ .AddChildren }
HAnimJoint245.AddChildren([HAnimJoint254]);
{ .AddChildren }
HAnimJoint236.AddChildren([HAnimJoint245]);
{ .AddChildren }
HAnimJoint186.AddChildren([HAnimJoint236]);
{ .AddChildren }
HAnimJoint30.AddChildren([HAnimJoint186]);
{ .AddChildren }
HAnimJoint29.AddChildren([HAnimJoint30]);
{ .AddSkeleton }
HAnimHumanoid26.SetSkeleton([HAnimJoint29]);
HAnimJoint272 := THAnimJointNode.Create;
HAnimJoint272 := HAnimJoint29;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint272;
HAnimJoint273 := THAnimJointNode.Create;
HAnimJoint273 := HAnimJoint132;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint273;
HAnimJoint274 := THAnimJointNode.Create;
HAnimJoint274 := HAnimJoint177;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint274;
HAnimJoint275 := THAnimJointNode.Create;
HAnimJoint275 := HAnimJoint227;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint275;
HAnimJoint276 := THAnimJointNode.Create;
HAnimJoint276 := HAnimJoint263;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint276;
HAnimJoint277 := THAnimJointNode.Create;
HAnimJoint277 := HAnimJoint87;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint277;
HAnimJoint278 := THAnimJointNode.Create;
HAnimJoint278 := HAnimJoint123;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint278;
HAnimJoint279 := THAnimJointNode.Create;
HAnimJoint279 := HAnimJoint168;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint279;
HAnimJoint280 := THAnimJointNode.Create;
HAnimJoint280 := HAnimJoint218;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint280;
HAnimJoint281 := THAnimJointNode.Create;
HAnimJoint281 := HAnimJoint254;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint281;
HAnimJoint282 := THAnimJointNode.Create;
HAnimJoint282 := HAnimJoint69;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint282;
HAnimJoint283 := THAnimJointNode.Create;
HAnimJoint283 := HAnimJoint105;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint283;
HAnimJoint284 := THAnimJointNode.Create;
HAnimJoint284 := HAnimJoint150;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint284;
HAnimJoint285 := THAnimJointNode.Create;
HAnimJoint285 := HAnimJoint200;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint285;
HAnimJoint286 := THAnimJointNode.Create;
HAnimJoint286 := HAnimJoint236;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint286;
HAnimJoint287 := THAnimJointNode.Create;
HAnimJoint287 := HAnimJoint78;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint287;
HAnimJoint288 := THAnimJointNode.Create;
HAnimJoint288 := HAnimJoint114;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint288;
HAnimJoint289 := THAnimJointNode.Create;
HAnimJoint289 := HAnimJoint159;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint289;
HAnimJoint290 := THAnimJointNode.Create;
HAnimJoint290 := HAnimJoint209;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint290;
HAnimJoint291 := THAnimJointNode.Create;
HAnimJoint291 := HAnimJoint245;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint291;
HAnimJoint292 := THAnimJointNode.Create;
HAnimJoint292 := HAnimJoint52;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint292;
HAnimJoint293 := THAnimJointNode.Create;
HAnimJoint293 := HAnimJoint96;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint293;
HAnimJoint294 := THAnimJointNode.Create;
HAnimJoint294 := HAnimJoint141;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint294;
HAnimJoint295 := THAnimJointNode.Create;
HAnimJoint295 := HAnimJoint186;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint295;
HAnimJoint296 := THAnimJointNode.Create;
HAnimJoint296 := HAnimJoint30;
{ .AddJoints }
HAnimHumanoid26.Joints := HAnimJoint296;
HAnimSegment297 := THAnimSegmentNode.Create;
HAnimSegment297 := HAnimSegment142;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment297;
HAnimSegment298 := THAnimSegmentNode.Create;
HAnimSegment298 := HAnimSegment31;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment298;
HAnimSegment299 := THAnimSegmentNode.Create;
HAnimSegment299 := HAnimSegment88;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment299;
HAnimSegment300 := THAnimSegmentNode.Create;
HAnimSegment300 := HAnimSegment133;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment300;
HAnimSegment301 := THAnimSegmentNode.Create;
HAnimSegment301 := HAnimSegment178;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment301;
HAnimSegment302 := THAnimSegmentNode.Create;
HAnimSegment302 := HAnimSegment228;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment302;
HAnimSegment303 := THAnimSegmentNode.Create;
HAnimSegment303 := HAnimSegment264;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment303;
HAnimSegment304 := THAnimSegmentNode.Create;
HAnimSegment304 := HAnimSegment124;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment304;
HAnimSegment305 := THAnimSegmentNode.Create;
HAnimSegment305 := HAnimSegment169;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment305;
HAnimSegment306 := THAnimSegmentNode.Create;
HAnimSegment306 := HAnimSegment219;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment306;
HAnimSegment307 := THAnimSegmentNode.Create;
HAnimSegment307 := HAnimSegment255;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment307;
HAnimSegment308 := THAnimSegmentNode.Create;
HAnimSegment308 := HAnimSegment79;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment308;
HAnimSegment309 := THAnimSegmentNode.Create;
HAnimSegment309 := HAnimSegment115;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment309;
HAnimSegment310 := THAnimSegmentNode.Create;
HAnimSegment310 := HAnimSegment160;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment310;
HAnimSegment311 := THAnimSegmentNode.Create;
HAnimSegment311 := HAnimSegment210;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment311;
HAnimSegment312 := THAnimSegmentNode.Create;
HAnimSegment312 := HAnimSegment246;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment312;
HAnimSegment313 := THAnimSegmentNode.Create;
HAnimSegment313 := HAnimSegment187;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment313;
HAnimSegment314 := THAnimSegmentNode.Create;
HAnimSegment314 := HAnimSegment70;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment314;
HAnimSegment315 := THAnimSegmentNode.Create;
HAnimSegment315 := HAnimSegment106;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment315;
HAnimSegment316 := THAnimSegmentNode.Create;
HAnimSegment316 := HAnimSegment151;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment316;
HAnimSegment317 := THAnimSegmentNode.Create;
HAnimSegment317 := HAnimSegment201;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment317;
HAnimSegment318 := THAnimSegmentNode.Create;
HAnimSegment318 := HAnimSegment237;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment318;
HAnimSegment319 := THAnimSegmentNode.Create;
HAnimSegment319 := HAnimSegment53;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment319;
HAnimSegment320 := THAnimSegmentNode.Create;
HAnimSegment320 := HAnimSegment97;
{ .AddSegments }
HAnimHumanoid26.Segments := HAnimSegment320;
{ .AddChildren }
Group24.AddChildren([HAnimHumanoid26]);
{ .AddGroup }
X3D0.AddChildren([Group24]);
Result := X3D0;
end;
