function Oxytocin: TX3DRootNode;
var
X3D0: TX3DRootNode;
Group19: TGroupNode;
ProtoDeclare20: TProtoDeclareNode;
ProtoInterface21: TProtoInterfaceNode;
field22: TfieldNode;
field23: TfieldNode;
ProtoBody24: TProtoBodyNode;
Group25: TGroupNode;
Transform26: TTransformNode;
IS27: TISNode;
connect28: TconnectNode;
Shape29: TShapeNode;
Appearance30: TAppearanceNode;
Material31: TMaterialNode;
IS32: TISNode;
connect33: TconnectNode;
Sphere34: TSphereNode;
Shape35: TShapeNode;
Appearance36: TAppearanceNode;
Material37: TMaterialNode;
Text38: TTextNode;
FontStyle39: TFontStyleNode;
ProtoDeclare40: TProtoDeclareNode;
ProtoInterface41: TProtoInterfaceNode;
field42: TfieldNode;
field43: TfieldNode;
ProtoBody44: TProtoBodyNode;
Group45: TGroupNode;
Transform46: TTransformNode;
IS47: TISNode;
connect48: TconnectNode;
Shape49: TShapeNode;
Appearance50: TAppearanceNode;
Material51: TMaterialNode;
IS52: TISNode;
connect53: TconnectNode;
Sphere54: TSphereNode;
Shape55: TShapeNode;
Appearance56: TAppearanceNode;
Material57: TMaterialNode;
Text58: TTextNode;
FontStyle59: TFontStyleNode;
ProtoDeclare60: TProtoDeclareNode;
ProtoInterface61: TProtoInterfaceNode;
field62: TfieldNode;
field63: TfieldNode;
ProtoBody64: TProtoBodyNode;
Group65: TGroupNode;
Transform66: TTransformNode;
IS67: TISNode;
connect68: TconnectNode;
Shape69: TShapeNode;
Appearance70: TAppearanceNode;
Material71: TMaterialNode;
IS72: TISNode;
connect73: TconnectNode;
Sphere74: TSphereNode;
Shape75: TShapeNode;
Appearance76: TAppearanceNode;
Material77: TMaterialNode;
Text78: TTextNode;
FontStyle79: TFontStyleNode;
ProtoDeclare80: TProtoDeclareNode;
ProtoInterface81: TProtoInterfaceNode;
field82: TfieldNode;
field83: TfieldNode;
ProtoBody84: TProtoBodyNode;
Group85: TGroupNode;
Transform86: TTransformNode;
IS87: TISNode;
connect88: TconnectNode;
Shape89: TShapeNode;
Appearance90: TAppearanceNode;
Material91: TMaterialNode;
IS92: TISNode;
connect93: TconnectNode;
Sphere94: TSphereNode;
Shape95: TShapeNode;
Appearance96: TAppearanceNode;
Material97: TMaterialNode;
Text98: TTextNode;
FontStyle99: TFontStyleNode;
ProtoDeclare100: TProtoDeclareNode;
ProtoInterface101: TProtoInterfaceNode;
field102: TfieldNode;
field103: TfieldNode;
ProtoBody104: TProtoBodyNode;
Group105: TGroupNode;
Transform106: TTransformNode;
IS107: TISNode;
connect108: TconnectNode;
Shape109: TShapeNode;
Appearance110: TAppearanceNode;
Material111: TMaterialNode;
IS112: TISNode;
connect113: TconnectNode;
Sphere114: TSphereNode;
Shape115: TShapeNode;
Appearance116: TAppearanceNode;
Material117: TMaterialNode;
Text118: TTextNode;
FontStyle119: TFontStyleNode;
ProtoDeclare120: TProtoDeclareNode;
ProtoInterface121: TProtoInterfaceNode;
field122: TfieldNode;
field123: TfieldNode;
ProtoBody124: TProtoBodyNode;
Group125: TGroupNode;
Transform126: TTransformNode;
IS127: TISNode;
connect128: TconnectNode;
Shape129: TShapeNode;
Appearance130: TAppearanceNode;
Material131: TMaterialNode;
IS132: TISNode;
connect133: TconnectNode;
Sphere134: TSphereNode;
Shape135: TShapeNode;
Appearance136: TAppearanceNode;
Material137: TMaterialNode;
Text138: TTextNode;
FontStyle139: TFontStyleNode;
ProtoDeclare140: TProtoDeclareNode;
ProtoInterface141: TProtoInterfaceNode;
field142: TfieldNode;
field143: TfieldNode;
ProtoBody144: TProtoBodyNode;
Group145: TGroupNode;
Transform146: TTransformNode;
IS147: TISNode;
connect148: TconnectNode;
Shape149: TShapeNode;
Appearance150: TAppearanceNode;
Material151: TMaterialNode;
IS152: TISNode;
connect153: TconnectNode;
Sphere154: TSphereNode;
Shape155: TShapeNode;
Appearance156: TAppearanceNode;
Material157: TMaterialNode;
Text158: TTextNode;
FontStyle159: TFontStyleNode;
ProtoDeclare160: TProtoDeclareNode;
ProtoInterface161: TProtoInterfaceNode;
field162: TfieldNode;
field163: TfieldNode;
ProtoBody164: TProtoBodyNode;
Group165: TGroupNode;
Transform166: TTransformNode;
IS167: TISNode;
connect168: TconnectNode;
Shape169: TShapeNode;
Appearance170: TAppearanceNode;
Material171: TMaterialNode;
IS172: TISNode;
connect173: TconnectNode;
Sphere174: TSphereNode;
Shape175: TShapeNode;
Appearance176: TAppearanceNode;
Material177: TMaterialNode;
Text178: TTextNode;
FontStyle179: TFontStyleNode;
ProtoDeclare180: TProtoDeclareNode;
ProtoInterface181: TProtoInterfaceNode;
field182: TfieldNode;
field183: TfieldNode;
ProtoBody184: TProtoBodyNode;
Group185: TGroupNode;
Transform186: TTransformNode;
IS187: TISNode;
connect188: TconnectNode;
Shape189: TShapeNode;
Appearance190: TAppearanceNode;
Material191: TMaterialNode;
IS192: TISNode;
connect193: TconnectNode;
Sphere194: TSphereNode;
Shape195: TShapeNode;
Appearance196: TAppearanceNode;
Material197: TMaterialNode;
Text198: TTextNode;
FontStyle199: TFontStyleNode;
ProtoDeclare200: TProtoDeclareNode;
ProtoInterface201: TProtoInterfaceNode;
field202: TfieldNode;
field203: TfieldNode;
ProtoBody204: TProtoBodyNode;
Group205: TGroupNode;
Transform206: TTransformNode;
IS207: TISNode;
connect208: TconnectNode;
Shape209: TShapeNode;
Appearance210: TAppearanceNode;
Material211: TMaterialNode;
IS212: TISNode;
connect213: TconnectNode;
Sphere214: TSphereNode;
Shape215: TShapeNode;
Appearance216: TAppearanceNode;
Material217: TMaterialNode;
Text218: TTextNode;
FontStyle219: TFontStyleNode;
ProtoDeclare220: TProtoDeclareNode;
ProtoInterface221: TProtoInterfaceNode;
field222: TfieldNode;
field223: TfieldNode;
ProtoBody224: TProtoBodyNode;
Group225: TGroupNode;
Transform226: TTransformNode;
IS227: TISNode;
connect228: TconnectNode;
Shape229: TShapeNode;
Appearance230: TAppearanceNode;
Material231: TMaterialNode;
IS232: TISNode;
connect233: TconnectNode;
Sphere234: TSphereNode;
Shape235: TShapeNode;
Appearance236: TAppearanceNode;
Material237: TMaterialNode;
Text238: TTextNode;
FontStyle239: TFontStyleNode;
ProtoDeclare240: TProtoDeclareNode;
ProtoInterface241: TProtoInterfaceNode;
field242: TfieldNode;
field243: TfieldNode;
ProtoBody244: TProtoBodyNode;
Group245: TGroupNode;
Transform246: TTransformNode;
IS247: TISNode;
connect248: TconnectNode;
Shape249: TShapeNode;
Appearance250: TAppearanceNode;
Material251: TMaterialNode;
IS252: TISNode;
connect253: TconnectNode;
Sphere254: TSphereNode;
Shape255: TShapeNode;
Appearance256: TAppearanceNode;
Material257: TMaterialNode;
Text258: TTextNode;
FontStyle259: TFontStyleNode;
ProtoDeclare260: TProtoDeclareNode;
ProtoInterface261: TProtoInterfaceNode;
field262: TfieldNode;
ProtoBody263: TProtoBodyNode;
Group264: TGroupNode;
Shape265: TShapeNode;
Appearance266: TAppearanceNode;
Material267: TMaterialNode;
IndexedLineSet268: TIndexedLineSetNode;
Coordinate269: TCoordinateNode;
IS270: TISNode;
connect271: TconnectNode;
ProtoDeclare272: TProtoDeclareNode;
ProtoInterface273: TProtoInterfaceNode;
field274: TfieldNode;
ProtoBody275: TProtoBodyNode;
Transform276: TTransformNode;
Group277: TGroupNode;
Transform278: TTransformNode;
Shape279: TShapeNode;
Appearance280: TAppearanceNode;
Material281: TMaterialNode;
Text282: TTextNode;
IS283: TISNode;
connect284: TconnectNode;
FontStyle285: TFontStyleNode;
ProtoDeclare286: TProtoDeclareNode;
ProtoInterface287: TProtoInterfaceNode;
field288: TfieldNode;
ProtoBody289: TProtoBodyNode;
Transform290: TTransformNode;
Group291: TGroupNode;
Transform292: TTransformNode;
Shape293: TShapeNode;
Appearance294: TAppearanceNode;
Material295: TMaterialNode;
Text296: TTextNode;
IS297: TISNode;
connect298: TconnectNode;
FontStyle299: TFontStyleNode;
ProtoDeclare300: TProtoDeclareNode;
ProtoInterface301: TProtoInterfaceNode;
field302: TfieldNode;
ProtoBody303: TProtoBodyNode;
Transform304: TTransformNode;
Group305: TGroupNode;
Transform306: TTransformNode;
Shape307: TShapeNode;
Appearance308: TAppearanceNode;
Material309: TMaterialNode;
Text310: TTextNode;
IS311: TISNode;
connect312: TconnectNode;
FontStyle313: TFontStyleNode;
Background314: TBackgroundNode;
PointLight315: TPointLightNode;
NavigationInfo316: TNavigationInfoNode;
Viewpoint317: TViewpointNode;
Transform318: TTransformNode;
Transform319: TTransformNode;
Viewpoint320: TViewpointNode;
ProtoInstance321: TProtoInstanceNode;
fieldValue322: TfieldValueNode;
Group323: TGroupNode;
Transform324: TTransformNode;
ProtoInstance325: TProtoInstanceNode;
fieldValue326: TfieldValueNode;
Transform327: TTransformNode;
ProtoInstance328: TProtoInstanceNode;
fieldValue329: TfieldValueNode;
Transform330: TTransformNode;
ProtoInstance331: TProtoInstanceNode;
fieldValue332: TfieldValueNode;
Transform333: TTransformNode;
ProtoInstance334: TProtoInstanceNode;
fieldValue335: TfieldValueNode;
Transform336: TTransformNode;
ProtoInstance337: TProtoInstanceNode;
fieldValue338: TfieldValueNode;
Transform339: TTransformNode;
ProtoInstance340: TProtoInstanceNode;
fieldValue341: TfieldValueNode;
Transform342: TTransformNode;
ProtoInstance343: TProtoInstanceNode;
fieldValue344: TfieldValueNode;
Transform345: TTransformNode;
ProtoInstance346: TProtoInstanceNode;
fieldValue347: TfieldValueNode;
Transform348: TTransformNode;
ProtoInstance349: TProtoInstanceNode;
fieldValue350: TfieldValueNode;
Transform351: TTransformNode;
ProtoInstance352: TProtoInstanceNode;
fieldValue353: TfieldValueNode;
Transform354: TTransformNode;
ProtoInstance355: TProtoInstanceNode;
fieldValue356: TfieldValueNode;
Transform357: TTransformNode;
ProtoInstance358: TProtoInstanceNode;
fieldValue359: TfieldValueNode;
Transform360: TTransformNode;
ProtoInstance361: TProtoInstanceNode;
fieldValue362: TfieldValueNode;
Transform363: TTransformNode;
ProtoInstance364: TProtoInstanceNode;
fieldValue365: TfieldValueNode;
Transform366: TTransformNode;
ProtoInstance367: TProtoInstanceNode;
fieldValue368: TfieldValueNode;
Transform369: TTransformNode;
ProtoInstance370: TProtoInstanceNode;
fieldValue371: TfieldValueNode;
Transform372: TTransformNode;
ProtoInstance373: TProtoInstanceNode;
fieldValue374: TfieldValueNode;
Transform375: TTransformNode;
ProtoInstance376: TProtoInstanceNode;
fieldValue377: TfieldValueNode;
Transform378: TTransformNode;
ProtoInstance379: TProtoInstanceNode;
fieldValue380: TfieldValueNode;
Transform381: TTransformNode;
ProtoInstance382: TProtoInstanceNode;
fieldValue383: TfieldValueNode;
Transform384: TTransformNode;
ProtoInstance385: TProtoInstanceNode;
fieldValue386: TfieldValueNode;
Transform387: TTransformNode;
ProtoInstance388: TProtoInstanceNode;
fieldValue389: TfieldValueNode;
Transform390: TTransformNode;
ProtoInstance391: TProtoInstanceNode;
fieldValue392: TfieldValueNode;
Transform393: TTransformNode;
ProtoInstance394: TProtoInstanceNode;
fieldValue395: TfieldValueNode;
Transform396: TTransformNode;
ProtoInstance397: TProtoInstanceNode;
fieldValue398: TfieldValueNode;
Transform399: TTransformNode;
ProtoInstance400: TProtoInstanceNode;
fieldValue401: TfieldValueNode;
Transform402: TTransformNode;
ProtoInstance403: TProtoInstanceNode;
fieldValue404: TfieldValueNode;
Transform405: TTransformNode;
ProtoInstance406: TProtoInstanceNode;
fieldValue407: TfieldValueNode;
Transform408: TTransformNode;
ProtoInstance409: TProtoInstanceNode;
fieldValue410: TfieldValueNode;
Transform411: TTransformNode;
ProtoInstance412: TProtoInstanceNode;
fieldValue413: TfieldValueNode;
Transform414: TTransformNode;
ProtoInstance415: TProtoInstanceNode;
fieldValue416: TfieldValueNode;
Transform417: TTransformNode;
ProtoInstance418: TProtoInstanceNode;
fieldValue419: TfieldValueNode;
Transform420: TTransformNode;
ProtoInstance421: TProtoInstanceNode;
fieldValue422: TfieldValueNode;
Transform423: TTransformNode;
ProtoInstance424: TProtoInstanceNode;
fieldValue425: TfieldValueNode;
Transform426: TTransformNode;
ProtoInstance427: TProtoInstanceNode;
fieldValue428: TfieldValueNode;
Transform429: TTransformNode;
ProtoInstance430: TProtoInstanceNode;
fieldValue431: TfieldValueNode;
Transform432: TTransformNode;
ProtoInstance433: TProtoInstanceNode;
fieldValue434: TfieldValueNode;
Transform435: TTransformNode;
ProtoInstance436: TProtoInstanceNode;
fieldValue437: TfieldValueNode;
Transform438: TTransformNode;
ProtoInstance439: TProtoInstanceNode;
fieldValue440: TfieldValueNode;
Transform441: TTransformNode;
ProtoInstance442: TProtoInstanceNode;
fieldValue443: TfieldValueNode;
Transform444: TTransformNode;
ProtoInstance445: TProtoInstanceNode;
fieldValue446: TfieldValueNode;
Transform447: TTransformNode;
ProtoInstance448: TProtoInstanceNode;
fieldValue449: TfieldValueNode;
Transform450: TTransformNode;
ProtoInstance451: TProtoInstanceNode;
fieldValue452: TfieldValueNode;
Transform453: TTransformNode;
ProtoInstance454: TProtoInstanceNode;
fieldValue455: TfieldValueNode;
Transform456: TTransformNode;
ProtoInstance457: TProtoInstanceNode;
fieldValue458: TfieldValueNode;
Transform459: TTransformNode;
ProtoInstance460: TProtoInstanceNode;
fieldValue461: TfieldValueNode;
Transform462: TTransformNode;
ProtoInstance463: TProtoInstanceNode;
fieldValue464: TfieldValueNode;
Transform465: TTransformNode;
ProtoInstance466: TProtoInstanceNode;
fieldValue467: TfieldValueNode;
Transform468: TTransformNode;
ProtoInstance469: TProtoInstanceNode;
fieldValue470: TfieldValueNode;
Transform471: TTransformNode;
ProtoInstance472: TProtoInstanceNode;
fieldValue473: TfieldValueNode;
Transform474: TTransformNode;
ProtoInstance475: TProtoInstanceNode;
fieldValue476: TfieldValueNode;
Transform477: TTransformNode;
ProtoInstance478: TProtoInstanceNode;
fieldValue479: TfieldValueNode;
Transform480: TTransformNode;
ProtoInstance481: TProtoInstanceNode;
fieldValue482: TfieldValueNode;
Transform483: TTransformNode;
ProtoInstance484: TProtoInstanceNode;
fieldValue485: TfieldValueNode;
Transform486: TTransformNode;
ProtoInstance487: TProtoInstanceNode;
fieldValue488: TfieldValueNode;
Transform489: TTransformNode;
ProtoInstance490: TProtoInstanceNode;
fieldValue491: TfieldValueNode;
Transform492: TTransformNode;
ProtoInstance493: TProtoInstanceNode;
fieldValue494: TfieldValueNode;
Transform495: TTransformNode;
ProtoInstance496: TProtoInstanceNode;
fieldValue497: TfieldValueNode;
Transform498: TTransformNode;
ProtoInstance499: TProtoInstanceNode;
fieldValue500: TfieldValueNode;
Transform501: TTransformNode;
ProtoInstance502: TProtoInstanceNode;
fieldValue503: TfieldValueNode;
Transform504: TTransformNode;
ProtoInstance505: TProtoInstanceNode;
fieldValue506: TfieldValueNode;
Transform507: TTransformNode;
ProtoInstance508: TProtoInstanceNode;
fieldValue509: TfieldValueNode;
Transform510: TTransformNode;
ProtoInstance511: TProtoInstanceNode;
fieldValue512: TfieldValueNode;
Transform513: TTransformNode;
ProtoInstance514: TProtoInstanceNode;
fieldValue515: TfieldValueNode;
Transform516: TTransformNode;
ProtoInstance517: TProtoInstanceNode;
fieldValue518: TfieldValueNode;
Transform519: TTransformNode;
ProtoInstance520: TProtoInstanceNode;
fieldValue521: TfieldValueNode;
Transform522: TTransformNode;
ProtoInstance523: TProtoInstanceNode;
fieldValue524: TfieldValueNode;
Transform525: TTransformNode;
ProtoInstance526: TProtoInstanceNode;
fieldValue527: TfieldValueNode;
Transform528: TTransformNode;
ProtoInstance529: TProtoInstanceNode;
fieldValue530: TfieldValueNode;
Group531: TGroupNode;
ProtoInstance532: TProtoInstanceNode;
fieldValue533: TfieldValueNode;
ProtoInstance534: TProtoInstanceNode;
fieldValue535: TfieldValueNode;
ProtoInstance536: TProtoInstanceNode;
fieldValue537: TfieldValueNode;
ProtoInstance538: TProtoInstanceNode;
fieldValue539: TfieldValueNode;
ProtoInstance540: TProtoInstanceNode;
fieldValue541: TfieldValueNode;
ProtoInstance542: TProtoInstanceNode;
fieldValue543: TfieldValueNode;
ProtoInstance544: TProtoInstanceNode;
fieldValue545: TfieldValueNode;
ProtoInstance546: TProtoInstanceNode;
fieldValue547: TfieldValueNode;
ProtoInstance548: TProtoInstanceNode;
fieldValue549: TfieldValueNode;
ProtoInstance550: TProtoInstanceNode;
fieldValue551: TfieldValueNode;
ProtoInstance552: TProtoInstanceNode;
fieldValue553: TfieldValueNode;
ProtoInstance554: TProtoInstanceNode;
fieldValue555: TfieldValueNode;
ProtoInstance556: TProtoInstanceNode;
fieldValue557: TfieldValueNode;
ProtoInstance558: TProtoInstanceNode;
fieldValue559: TfieldValueNode;
ProtoInstance560: TProtoInstanceNode;
fieldValue561: TfieldValueNode;
ProtoInstance562: TProtoInstanceNode;
fieldValue563: TfieldValueNode;
ProtoInstance564: TProtoInstanceNode;
fieldValue565: TfieldValueNode;
ProtoInstance566: TProtoInstanceNode;
fieldValue567: TfieldValueNode;
ProtoInstance568: TProtoInstanceNode;
fieldValue569: TfieldValueNode;
ProtoInstance570: TProtoInstanceNode;
fieldValue571: TfieldValueNode;
ProtoInstance572: TProtoInstanceNode;
fieldValue573: TfieldValueNode;
ProtoInstance574: TProtoInstanceNode;
fieldValue575: TfieldValueNode;
ProtoInstance576: TProtoInstanceNode;
fieldValue577: TfieldValueNode;
ProtoInstance578: TProtoInstanceNode;
fieldValue579: TfieldValueNode;
ProtoInstance580: TProtoInstanceNode;
fieldValue581: TfieldValueNode;
ProtoInstance582: TProtoInstanceNode;
fieldValue583: TfieldValueNode;
ProtoInstance584: TProtoInstanceNode;
fieldValue585: TfieldValueNode;
ProtoInstance586: TProtoInstanceNode;
fieldValue587: TfieldValueNode;
ProtoInstance588: TProtoInstanceNode;
fieldValue589: TfieldValueNode;
ProtoInstance590: TProtoInstanceNode;
fieldValue591: TfieldValueNode;
ProtoInstance592: TProtoInstanceNode;
fieldValue593: TfieldValueNode;
ProtoInstance594: TProtoInstanceNode;
fieldValue595: TfieldValueNode;
ProtoInstance596: TProtoInstanceNode;
fieldValue597: TfieldValueNode;
ProtoInstance598: TProtoInstanceNode;
fieldValue599: TfieldValueNode;
ProtoInstance600: TProtoInstanceNode;
fieldValue601: TfieldValueNode;
ProtoInstance602: TProtoInstanceNode;
fieldValue603: TfieldValueNode;
ProtoInstance604: TProtoInstanceNode;
fieldValue605: TfieldValueNode;
ProtoInstance606: TProtoInstanceNode;
fieldValue607: TfieldValueNode;
ProtoInstance608: TProtoInstanceNode;
fieldValue609: TfieldValueNode;
ProtoInstance610: TProtoInstanceNode;
fieldValue611: TfieldValueNode;
ProtoInstance612: TProtoInstanceNode;
fieldValue613: TfieldValueNode;
ProtoInstance614: TProtoInstanceNode;
fieldValue615: TfieldValueNode;
ProtoInstance616: TProtoInstanceNode;
fieldValue617: TfieldValueNode;
ProtoInstance618: TProtoInstanceNode;
fieldValue619: TfieldValueNode;
ProtoInstance620: TProtoInstanceNode;
fieldValue621: TfieldValueNode;
ProtoInstance622: TProtoInstanceNode;
fieldValue623: TfieldValueNode;
ProtoInstance624: TProtoInstanceNode;
fieldValue625: TfieldValueNode;
ProtoInstance626: TProtoInstanceNode;
fieldValue627: TfieldValueNode;
ProtoInstance628: TProtoInstanceNode;
fieldValue629: TfieldValueNode;
ProtoInstance630: TProtoInstanceNode;
fieldValue631: TfieldValueNode;
ProtoInstance632: TProtoInstanceNode;
fieldValue633: TfieldValueNode;
ProtoInstance634: TProtoInstanceNode;
fieldValue635: TfieldValueNode;
ProtoInstance636: TProtoInstanceNode;
fieldValue637: TfieldValueNode;
ProtoInstance638: TProtoInstanceNode;
fieldValue639: TfieldValueNode;
ProtoInstance640: TProtoInstanceNode;
fieldValue641: TfieldValueNode;
ProtoInstance642: TProtoInstanceNode;
fieldValue643: TfieldValueNode;
ProtoInstance644: TProtoInstanceNode;
fieldValue645: TfieldValueNode;
ProtoInstance646: TProtoInstanceNode;
fieldValue647: TfieldValueNode;
ProtoInstance648: TProtoInstanceNode;
fieldValue649: TfieldValueNode;
ProtoInstance650: TProtoInstanceNode;
fieldValue651: TfieldValueNode;
ProtoInstance652: TProtoInstanceNode;
fieldValue653: TfieldValueNode;
ProtoInstance654: TProtoInstanceNode;
fieldValue655: TfieldValueNode;
ProtoInstance656: TProtoInstanceNode;
fieldValue657: TfieldValueNode;
ProtoInstance658: TProtoInstanceNode;
fieldValue659: TfieldValueNode;
ProtoInstance660: TProtoInstanceNode;
fieldValue661: TfieldValueNode;
ProtoInstance662: TProtoInstanceNode;
fieldValue663: TfieldValueNode;
ProtoInstance664: TProtoInstanceNode;
fieldValue665: TfieldValueNode;
ProtoInstance666: TProtoInstanceNode;
fieldValue667: TfieldValueNode;
ProtoInstance668: TProtoInstanceNode;
fieldValue669: TfieldValueNode;
ProtoInstance670: TProtoInstanceNode;
fieldValue671: TfieldValueNode;
ProtoInstance672: TProtoInstanceNode;
fieldValue673: TfieldValueNode;
ProtoInstance674: TProtoInstanceNode;
fieldValue675: TfieldValueNode;
ProtoInstance676: TProtoInstanceNode;
fieldValue677: TfieldValueNode;
ProtoInstance678: TProtoInstanceNode;
fieldValue679: TfieldValueNode;
ProtoInstance680: TProtoInstanceNode;
fieldValue681: TfieldValueNode;
ProtoInstance682: TProtoInstanceNode;
fieldValue683: TfieldValueNode;
ProtoInstance684: TProtoInstanceNode;
fieldValue685: TfieldValueNode;
ProtoInstance686: TProtoInstanceNode;
fieldValue687: TfieldValueNode;
ProtoInstance688: TProtoInstanceNode;
fieldValue689: TfieldValueNode;
ProtoInstance690: TProtoInstanceNode;
fieldValue691: TfieldValueNode;
ProtoInstance692: TProtoInstanceNode;
fieldValue693: TfieldValueNode;
ProtoInstance694: TProtoInstanceNode;
fieldValue695: TfieldValueNode;
ProtoInstance696: TProtoInstanceNode;
fieldValue697: TfieldValueNode;
ProtoInstance698: TProtoInstanceNode;
fieldValue699: TfieldValueNode;
ProtoInstance700: TProtoInstanceNode;
fieldValue701: TfieldValueNode;
begin
X3D0 := TX3DRootNode.Create;
X3D0.Profile := 'Immersive';
X3D0.ForceVersion.Major := 4;
X3D0.ForceVersion.Minor := 0;
X3D0.Meta['title'] := 'Oxytocin.x3d';
X3D0.Meta['description'] := 'Autogenerated version of Oxytocin.x3d scene produced from Oxytocin.xml Chemical Markup Language (CML) version 1.0 source file.';
X3D0.Meta['creator'] := 'Nicholas F. Polys';
X3D0.Meta['translator'] := 'Don Brutzman';
X3D0.Meta['created'] := '24 November 2005';
X3D0.Meta['translated'] := '2 JAN 2025';
X3D0.Meta['modified'] := '2 JAN 2025';
X3D0.Meta['reference'] := 'Oxytocin.xml';
X3D0.Meta['reference'] := 'CML sources https://www.xml-cml.org';
X3D0.Meta['reference'] := 'Wikipedia https://en.wikipedia.org/wiki/Chemical_Markup_Language';
X3D0.Meta['reference'] := 'JUMBO Chemical Format Conversion Tool';
X3D0.Meta['reference'] := 'https://webbook.nist.gov/chemistry';
X3D0.Meta['reference'] := 'Polys.StylesheetTransformationsInteractiveVisualization.Web3d2003Symposium.pdf';
X3D0.Meta['reference'] := 'Originally Published in Proceedings of Web3D 2003, ACM Press';
X3D0.Meta['generator'] := 'CmlToX3d.xslt';
X3D0.Meta['identifier'] := 'https://www.web3d.org/x3d/content/examples/Basic/ChemicalMarkupLanguage/Oxytocin.x3d';
X3D0.Meta['license'] := '../license.html';
Group19 := TGroupNode.Create;
ProtoDeclare20 := TProtoDeclareNode.Create;
ProtoDeclare20.NameField := 'Carbon';
ProtoInterface21 := TProtoInterfaceNode.Create;
field22 := TfieldNode.Create;
field22.NameField := 'position';
field22.AccessType := 'inputOutput';
field22.Type := 'SFVec3f';
field22.Value := '0 0 0';
{ .AddField }
ProtoInterface21.Field := field22;
field23 := TfieldNode.Create;
field23.NameField := 'materialTransparency';
field23.AccessType := 'inputOutput';
field23.Type := 'SFFloat';
field23.Value := '0.6';
{ .AddField }
ProtoInterface21.Field := field23;
{ .SetProtoInterface }
ProtoDeclare20.ProtoInterface := ProtoInterface21;
ProtoBody24 := TProtoBodyNode.Create;
Group25 := TGroupNode.Create;
Transform26 := TTransformNode.Create;
IS27 := TISNode.Create;
connect28 := TconnectNode.Create;
connect28.NodeField := 'translation';
connect28.ProtoField := 'position';
{ .AddConnect }
IS27.Connect := connect28;
{ .SetIS }
Transform26.IS := IS27;
Shape29 := TShapeNode.Create;
Appearance30 := TAppearanceNode.Create;
Material31 := TMaterialNode.Create;
Material31.DiffuseColor := Vector3(0,0,0);
Material31.Shininess := 0.8;
Material31.SpecularColor := Vector3(0.29,0.3,0.29);
IS32 := TISNode.Create;
connect33 := TconnectNode.Create;
connect33.NodeField := 'transparency';
connect33.ProtoField := 'materialTransparency';
{ .AddConnect }
IS32.Connect := connect33;
{ .SetIS }
Material31.IS := IS32;
{ .SetMaterial }
Appearance30.Material := Material31;
{ .SetAppearance }
Shape29.Appearance := Appearance30;
Sphere34 := TSphereNode.Create;
Sphere34.Radius := 0.77;
{ .SetGeometry }
Shape29.Geometry := Sphere34;
{ .AddChild }
Transform26.AddChildren([Shape29]);
Shape35 := TShapeNode.Create;
Appearance36 := TAppearanceNode.Create;
Material37 := TMaterialNode.Create;
Material37.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance36.Material := Material37;
{ .SetAppearance }
Shape35.Appearance := Appearance36;
Text38 := TTextNode.Create;
Text38.SetText(['C']);
FontStyle39 := TFontStyleNode.Create;
FontStyle39.Size := 0.8;
{ .SetFontStyle }
Text38.FontStyle := FontStyle39;
{ .SetGeometry }
Shape35.Geometry := Text38;
{ .AddChild }
Transform26.AddChildren([Shape35]);
{ .AddChildren }
Group25.AddChildren([Transform26]);
{ .AddChildren }
ProtoBody24.AddChildren([Group25]);
{ .SetProtoBody }
ProtoDeclare20.ProtoBody := ProtoBody24;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare20]);
ProtoDeclare40 := TProtoDeclareNode.Create;
ProtoDeclare40.NameField := 'Hydrogen';
ProtoInterface41 := TProtoInterfaceNode.Create;
field42 := TfieldNode.Create;
field42.NameField := 'position';
field42.AccessType := 'inputOutput';
field42.Type := 'SFVec3f';
field42.Value := '0 0 0';
{ .AddField }
ProtoInterface41.Field := field42;
field43 := TfieldNode.Create;
field43.NameField := 'materialTransparency';
field43.AccessType := 'inputOutput';
field43.Type := 'SFFloat';
field43.Value := '0.6';
{ .AddField }
ProtoInterface41.Field := field43;
{ .SetProtoInterface }
ProtoDeclare40.ProtoInterface := ProtoInterface41;
ProtoBody44 := TProtoBodyNode.Create;
Group45 := TGroupNode.Create;
Transform46 := TTransformNode.Create;
IS47 := TISNode.Create;
connect48 := TconnectNode.Create;
connect48.NodeField := 'translation';
connect48.ProtoField := 'position';
{ .AddConnect }
IS47.Connect := connect48;
{ .SetIS }
Transform46.IS := IS47;
Shape49 := TShapeNode.Create;
Appearance50 := TAppearanceNode.Create;
Material51 := TMaterialNode.Create;
Material51.AmbientIntensity := 0.0933;
Material51.DiffuseColor := Vector3(0.38,0.38,0.42);
Material51.Shininess := 0.5;
Material51.SpecularColor := Vector3(0.53,0.53,0.53);
IS52 := TISNode.Create;
connect53 := TconnectNode.Create;
connect53.NodeField := 'transparency';
connect53.ProtoField := 'materialTransparency';
{ .AddConnect }
IS52.Connect := connect53;
{ .SetIS }
Material51.IS := IS52;
{ .SetMaterial }
Appearance50.Material := Material51;
{ .SetAppearance }
Shape49.Appearance := Appearance50;
Sphere54 := TSphereNode.Create;
Sphere54.Radius := 0.32;
{ .SetGeometry }
Shape49.Geometry := Sphere54;
{ .AddChild }
Transform46.AddChildren([Shape49]);
Shape55 := TShapeNode.Create;
Appearance56 := TAppearanceNode.Create;
Material57 := TMaterialNode.Create;
Material57.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance56.Material := Material57;
{ .SetAppearance }
Shape55.Appearance := Appearance56;
Text58 := TTextNode.Create;
Text58.SetText(['H']);
FontStyle59 := TFontStyleNode.Create;
FontStyle59.Size := 0.4;
{ .SetFontStyle }
Text58.FontStyle := FontStyle59;
{ .SetGeometry }
Shape55.Geometry := Text58;
{ .AddChild }
Transform46.AddChildren([Shape55]);
{ .AddChildren }
Group45.AddChildren([Transform46]);
{ .AddChildren }
ProtoBody44.AddChildren([Group45]);
{ .SetProtoBody }
ProtoDeclare40.ProtoBody := ProtoBody44;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare40]);
ProtoDeclare60 := TProtoDeclareNode.Create;
ProtoDeclare60.NameField := 'Nitrogen';
ProtoInterface61 := TProtoInterfaceNode.Create;
field62 := TfieldNode.Create;
field62.NameField := 'position';
field62.AccessType := 'inputOutput';
field62.Type := 'SFVec3f';
field62.Value := '0 0 0';
{ .AddField }
ProtoInterface61.Field := field62;
field63 := TfieldNode.Create;
field63.NameField := 'materialTransparency';
field63.AccessType := 'inputOutput';
field63.Type := 'SFFloat';
field63.Value := '0.6';
{ .AddField }
ProtoInterface61.Field := field63;
{ .SetProtoInterface }
ProtoDeclare60.ProtoInterface := ProtoInterface61;
ProtoBody64 := TProtoBodyNode.Create;
Group65 := TGroupNode.Create;
Transform66 := TTransformNode.Create;
IS67 := TISNode.Create;
connect68 := TconnectNode.Create;
connect68.NodeField := 'translation';
connect68.ProtoField := 'position';
{ .AddConnect }
IS67.Connect := connect68;
{ .SetIS }
Transform66.IS := IS67;
Shape69 := TShapeNode.Create;
Appearance70 := TAppearanceNode.Create;
Material71 := TMaterialNode.Create;
Material71.DiffuseColor := Vector3(0,0,0.72);
Material71.EmissiveColor := Vector3(0,0,0.13);
Material71.SpecularColor := Vector3(0.5,0.5,0.5);
IS72 := TISNode.Create;
connect73 := TconnectNode.Create;
connect73.NodeField := 'transparency';
connect73.ProtoField := 'materialTransparency';
{ .AddConnect }
IS72.Connect := connect73;
{ .SetIS }
Material71.IS := IS72;
{ .SetMaterial }
Appearance70.Material := Material71;
{ .SetAppearance }
Shape69.Appearance := Appearance70;
Sphere74 := TSphereNode.Create;
Sphere74.Radius := 0.75;
{ .SetGeometry }
Shape69.Geometry := Sphere74;
{ .AddChild }
Transform66.AddChildren([Shape69]);
Shape75 := TShapeNode.Create;
Appearance76 := TAppearanceNode.Create;
Material77 := TMaterialNode.Create;
Material77.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance76.Material := Material77;
{ .SetAppearance }
Shape75.Appearance := Appearance76;
Text78 := TTextNode.Create;
Text78.SetText(['N']);
FontStyle79 := TFontStyleNode.Create;
FontStyle79.Size := 0.8;
{ .SetFontStyle }
Text78.FontStyle := FontStyle79;
{ .SetGeometry }
Shape75.Geometry := Text78;
{ .AddChild }
Transform66.AddChildren([Shape75]);
{ .AddChildren }
Group65.AddChildren([Transform66]);
{ .AddChildren }
ProtoBody64.AddChildren([Group65]);
{ .SetProtoBody }
ProtoDeclare60.ProtoBody := ProtoBody64;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare60]);
ProtoDeclare80 := TProtoDeclareNode.Create;
ProtoDeclare80.NameField := 'Oxygen';
ProtoInterface81 := TProtoInterfaceNode.Create;
field82 := TfieldNode.Create;
field82.NameField := 'position';
field82.AccessType := 'inputOutput';
field82.Type := 'SFVec3f';
field82.Value := '0 0 0';
{ .AddField }
ProtoInterface81.Field := field82;
field83 := TfieldNode.Create;
field83.NameField := 'materialTransparency';
field83.AccessType := 'inputOutput';
field83.Type := 'SFFloat';
field83.Value := '0.6';
{ .AddField }
ProtoInterface81.Field := field83;
{ .SetProtoInterface }
ProtoDeclare80.ProtoInterface := ProtoInterface81;
ProtoBody84 := TProtoBodyNode.Create;
Group85 := TGroupNode.Create;
Transform86 := TTransformNode.Create;
IS87 := TISNode.Create;
connect88 := TconnectNode.Create;
connect88.NodeField := 'translation';
connect88.ProtoField := 'position';
{ .AddConnect }
IS87.Connect := connect88;
{ .SetIS }
Transform86.IS := IS87;
Shape89 := TShapeNode.Create;
Appearance90 := TAppearanceNode.Create;
Material91 := TMaterialNode.Create;
Material91.AmbientIntensity := 0.487;
Material91.DiffuseColor := Vector3(0.54,0.05,0.25);
Material91.Shininess := 0.2;
Material91.SpecularColor := Vector3(0.81,0.77,0.75);
IS92 := TISNode.Create;
connect93 := TconnectNode.Create;
connect93.NodeField := 'transparency';
connect93.ProtoField := 'materialTransparency';
{ .AddConnect }
IS92.Connect := connect93;
{ .SetIS }
Material91.IS := IS92;
{ .SetMaterial }
Appearance90.Material := Material91;
{ .SetAppearance }
Shape89.Appearance := Appearance90;
Sphere94 := TSphereNode.Create;
Sphere94.Radius := 0.73;
{ .SetGeometry }
Shape89.Geometry := Sphere94;
{ .AddChild }
Transform86.AddChildren([Shape89]);
Shape95 := TShapeNode.Create;
Appearance96 := TAppearanceNode.Create;
Material97 := TMaterialNode.Create;
Material97.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance96.Material := Material97;
{ .SetAppearance }
Shape95.Appearance := Appearance96;
Text98 := TTextNode.Create;
Text98.SetText(['O']);
FontStyle99 := TFontStyleNode.Create;
FontStyle99.Size := 0.8;
{ .SetFontStyle }
Text98.FontStyle := FontStyle99;
{ .SetGeometry }
Shape95.Geometry := Text98;
{ .AddChild }
Transform86.AddChildren([Shape95]);
{ .AddChildren }
Group85.AddChildren([Transform86]);
{ .AddChildren }
ProtoBody84.AddChildren([Group85]);
{ .SetProtoBody }
ProtoDeclare80.ProtoBody := ProtoBody84;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare80]);
ProtoDeclare100 := TProtoDeclareNode.Create;
ProtoDeclare100.NameField := 'Fluorine';
ProtoInterface101 := TProtoInterfaceNode.Create;
field102 := TfieldNode.Create;
field102.NameField := 'position';
field102.AccessType := 'inputOutput';
field102.Type := 'SFVec3f';
field102.Value := '0 0 0';
{ .AddField }
ProtoInterface101.Field := field102;
field103 := TfieldNode.Create;
field103.NameField := 'materialTransparency';
field103.AccessType := 'inputOutput';
field103.Type := 'SFFloat';
field103.Value := '0.6';
{ .AddField }
ProtoInterface101.Field := field103;
{ .SetProtoInterface }
ProtoDeclare100.ProtoInterface := ProtoInterface101;
ProtoBody104 := TProtoBodyNode.Create;
Group105 := TGroupNode.Create;
Transform106 := TTransformNode.Create;
IS107 := TISNode.Create;
connect108 := TconnectNode.Create;
connect108.NodeField := 'translation';
connect108.ProtoField := 'position';
{ .AddConnect }
IS107.Connect := connect108;
{ .SetIS }
Transform106.IS := IS107;
Shape109 := TShapeNode.Create;
Appearance110 := TAppearanceNode.Create;
Material111 := TMaterialNode.Create;
Material111.DiffuseColor := Vector3(1,0.48,0.79);
Material111.EmissiveColor := Vector3(0.09,0.04,0.07);
IS112 := TISNode.Create;
connect113 := TconnectNode.Create;
connect113.NodeField := 'transparency';
connect113.ProtoField := 'materialTransparency';
{ .AddConnect }
IS112.Connect := connect113;
{ .SetIS }
Material111.IS := IS112;
{ .SetMaterial }
Appearance110.Material := Material111;
{ .SetAppearance }
Shape109.Appearance := Appearance110;
Sphere114 := TSphereNode.Create;
Sphere114.Radius := 0.72;
{ .SetGeometry }
Shape109.Geometry := Sphere114;
{ .AddChild }
Transform106.AddChildren([Shape109]);
Shape115 := TShapeNode.Create;
Appearance116 := TAppearanceNode.Create;
Material117 := TMaterialNode.Create;
Material117.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance116.Material := Material117;
{ .SetAppearance }
Shape115.Appearance := Appearance116;
Text118 := TTextNode.Create;
Text118.SetText(['F']);
FontStyle119 := TFontStyleNode.Create;
FontStyle119.Size := 0.8;
{ .SetFontStyle }
Text118.FontStyle := FontStyle119;
{ .SetGeometry }
Shape115.Geometry := Text118;
{ .AddChild }
Transform106.AddChildren([Shape115]);
{ .AddChildren }
Group105.AddChildren([Transform106]);
{ .AddChildren }
ProtoBody104.AddChildren([Group105]);
{ .SetProtoBody }
ProtoDeclare100.ProtoBody := ProtoBody104;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare100]);
ProtoDeclare120 := TProtoDeclareNode.Create;
ProtoDeclare120.NameField := 'Silicon';
ProtoInterface121 := TProtoInterfaceNode.Create;
field122 := TfieldNode.Create;
field122.NameField := 'position';
field122.AccessType := 'inputOutput';
field122.Type := 'SFVec3f';
field122.Value := '0 0 0';
{ .AddField }
ProtoInterface121.Field := field122;
field123 := TfieldNode.Create;
field123.NameField := 'materialTransparency';
field123.AccessType := 'inputOutput';
field123.Type := 'SFFloat';
field123.Value := '0.6';
{ .AddField }
ProtoInterface121.Field := field123;
{ .SetProtoInterface }
ProtoDeclare120.ProtoInterface := ProtoInterface121;
ProtoBody124 := TProtoBodyNode.Create;
Group125 := TGroupNode.Create;
Transform126 := TTransformNode.Create;
IS127 := TISNode.Create;
connect128 := TconnectNode.Create;
connect128.NodeField := 'translation';
connect128.ProtoField := 'position';
{ .AddConnect }
IS127.Connect := connect128;
{ .SetIS }
Transform126.IS := IS127;
Shape129 := TShapeNode.Create;
Appearance130 := TAppearanceNode.Create;
Material131 := TMaterialNode.Create;
Material131.DiffuseColor := Vector3(0.8,0.8,0.8);
IS132 := TISNode.Create;
connect133 := TconnectNode.Create;
connect133.NodeField := 'transparency';
connect133.ProtoField := 'materialTransparency';
{ .AddConnect }
IS132.Connect := connect133;
{ .SetIS }
Material131.IS := IS132;
{ .SetMaterial }
Appearance130.Material := Material131;
{ .SetAppearance }
Shape129.Appearance := Appearance130;
Sphere134 := TSphereNode.Create;
Sphere134.Radius := 1.18;
{ .SetGeometry }
Shape129.Geometry := Sphere134;
{ .AddChild }
Transform126.AddChildren([Shape129]);
Shape135 := TShapeNode.Create;
Appearance136 := TAppearanceNode.Create;
Material137 := TMaterialNode.Create;
Material137.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance136.Material := Material137;
{ .SetAppearance }
Shape135.Appearance := Appearance136;
Text138 := TTextNode.Create;
Text138.SetText(['Si']);
FontStyle139 := TFontStyleNode.Create;
FontStyle139.Size := 0.8;
{ .SetFontStyle }
Text138.FontStyle := FontStyle139;
{ .SetGeometry }
Shape135.Geometry := Text138;
{ .AddChild }
Transform126.AddChildren([Shape135]);
{ .AddChildren }
Group125.AddChildren([Transform126]);
{ .AddChildren }
ProtoBody124.AddChildren([Group125]);
{ .SetProtoBody }
ProtoDeclare120.ProtoBody := ProtoBody124;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare120]);
ProtoDeclare140 := TProtoDeclareNode.Create;
ProtoDeclare140.NameField := 'Phosphorus';
ProtoInterface141 := TProtoInterfaceNode.Create;
field142 := TfieldNode.Create;
field142.NameField := 'position';
field142.AccessType := 'inputOutput';
field142.Type := 'SFVec3f';
field142.Value := '0 0 0';
{ .AddField }
ProtoInterface141.Field := field142;
field143 := TfieldNode.Create;
field143.NameField := 'materialTransparency';
field143.AccessType := 'inputOutput';
field143.Type := 'SFFloat';
field143.Value := '0.6';
{ .AddField }
ProtoInterface141.Field := field143;
{ .SetProtoInterface }
ProtoDeclare140.ProtoInterface := ProtoInterface141;
ProtoBody144 := TProtoBodyNode.Create;
Group145 := TGroupNode.Create;
Transform146 := TTransformNode.Create;
IS147 := TISNode.Create;
connect148 := TconnectNode.Create;
connect148.NodeField := 'translation';
connect148.ProtoField := 'position';
{ .AddConnect }
IS147.Connect := connect148;
{ .SetIS }
Transform146.IS := IS147;
Shape149 := TShapeNode.Create;
Appearance150 := TAppearanceNode.Create;
Material151 := TMaterialNode.Create;
Material151.AmbientIntensity := 0.11;
Material151.DiffuseColor := Vector3(0.9,0.41,0);
Material151.EmissiveColor := Vector3(0.1,0.04,0);
Material151.Shininess := 0.8;
Material151.SpecularColor := Vector3(0.1,0.1,0.1);
IS152 := TISNode.Create;
connect153 := TconnectNode.Create;
connect153.NodeField := 'transparency';
connect153.ProtoField := 'materialTransparency';
{ .AddConnect }
IS152.Connect := connect153;
{ .SetIS }
Material151.IS := IS152;
{ .SetMaterial }
Appearance150.Material := Material151;
{ .SetAppearance }
Shape149.Appearance := Appearance150;
Sphere154 := TSphereNode.Create;
Sphere154.Radius := 1.1;
{ .SetGeometry }
Shape149.Geometry := Sphere154;
{ .AddChild }
Transform146.AddChildren([Shape149]);
Shape155 := TShapeNode.Create;
Appearance156 := TAppearanceNode.Create;
Material157 := TMaterialNode.Create;
Material157.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance156.Material := Material157;
{ .SetAppearance }
Shape155.Appearance := Appearance156;
Text158 := TTextNode.Create;
Text158.SetText(['P']);
FontStyle159 := TFontStyleNode.Create;
FontStyle159.Size := 0.8;
{ .SetFontStyle }
Text158.FontStyle := FontStyle159;
{ .SetGeometry }
Shape155.Geometry := Text158;
{ .AddChild }
Transform146.AddChildren([Shape155]);
{ .AddChildren }
Group145.AddChildren([Transform146]);
{ .AddChildren }
ProtoBody144.AddChildren([Group145]);
{ .SetProtoBody }
ProtoDeclare140.ProtoBody := ProtoBody144;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare140]);
ProtoDeclare160 := TProtoDeclareNode.Create;
ProtoDeclare160.NameField := 'Sulphur';
ProtoInterface161 := TProtoInterfaceNode.Create;
field162 := TfieldNode.Create;
field162.NameField := 'position';
field162.AccessType := 'inputOutput';
field162.Type := 'SFVec3f';
field162.Value := '0 0 0';
{ .AddField }
ProtoInterface161.Field := field162;
field163 := TfieldNode.Create;
field163.NameField := 'materialTransparency';
field163.AccessType := 'inputOutput';
field163.Type := 'SFFloat';
field163.Value := '0.6';
{ .AddField }
ProtoInterface161.Field := field163;
{ .SetProtoInterface }
ProtoDeclare160.ProtoInterface := ProtoInterface161;
ProtoBody164 := TProtoBodyNode.Create;
Group165 := TGroupNode.Create;
Transform166 := TTransformNode.Create;
IS167 := TISNode.Create;
connect168 := TconnectNode.Create;
connect168.NodeField := 'translation';
connect168.ProtoField := 'position';
{ .AddConnect }
IS167.Connect := connect168;
{ .SetIS }
Transform166.IS := IS167;
Shape169 := TShapeNode.Create;
Appearance170 := TAppearanceNode.Create;
Material171 := TMaterialNode.Create;
Material171.AmbientIntensity := 0.0467;
Material171.DiffuseColor := Vector3(0.25,0.39,0.25);
Material171.EmissiveColor := Vector3(0.05,0.08,0.05);
Material171.Shininess := 0.6;
Material171.SpecularColor := Vector3(0.11,0.12,0.08);
IS172 := TISNode.Create;
connect173 := TconnectNode.Create;
connect173.NodeField := 'transparency';
connect173.ProtoField := 'materialTransparency';
{ .AddConnect }
IS172.Connect := connect173;
{ .SetIS }
Material171.IS := IS172;
{ .SetMaterial }
Appearance170.Material := Material171;
{ .SetAppearance }
Shape169.Appearance := Appearance170;
Sphere174 := TSphereNode.Create;
Sphere174.Radius := 1.3;
{ .SetGeometry }
Shape169.Geometry := Sphere174;
{ .AddChild }
Transform166.AddChildren([Shape169]);
Shape175 := TShapeNode.Create;
Appearance176 := TAppearanceNode.Create;
Material177 := TMaterialNode.Create;
Material177.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance176.Material := Material177;
{ .SetAppearance }
Shape175.Appearance := Appearance176;
Text178 := TTextNode.Create;
Text178.SetText(['S']);
FontStyle179 := TFontStyleNode.Create;
FontStyle179.Size := 0.8;
{ .SetFontStyle }
Text178.FontStyle := FontStyle179;
{ .SetGeometry }
Shape175.Geometry := Text178;
{ .AddChild }
Transform166.AddChildren([Shape175]);
{ .AddChildren }
Group165.AddChildren([Transform166]);
{ .AddChildren }
ProtoBody164.AddChildren([Group165]);
{ .SetProtoBody }
ProtoDeclare160.ProtoBody := ProtoBody164;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare160]);
ProtoDeclare180 := TProtoDeclareNode.Create;
ProtoDeclare180.NameField := 'Chlorine';
ProtoInterface181 := TProtoInterfaceNode.Create;
field182 := TfieldNode.Create;
field182.NameField := 'position';
field182.AccessType := 'inputOutput';
field182.Type := 'SFVec3f';
field182.Value := '0 0 0';
{ .AddField }
ProtoInterface181.Field := field182;
field183 := TfieldNode.Create;
field183.NameField := 'materialTransparency';
field183.AccessType := 'inputOutput';
field183.Type := 'SFFloat';
field183.Value := '0.6';
{ .AddField }
ProtoInterface181.Field := field183;
{ .SetProtoInterface }
ProtoDeclare180.ProtoInterface := ProtoInterface181;
ProtoBody184 := TProtoBodyNode.Create;
Group185 := TGroupNode.Create;
Transform186 := TTransformNode.Create;
IS187 := TISNode.Create;
connect188 := TconnectNode.Create;
connect188.NodeField := 'translation';
connect188.ProtoField := 'position';
{ .AddConnect }
IS187.Connect := connect188;
{ .SetIS }
Transform186.IS := IS187;
Shape189 := TShapeNode.Create;
Appearance190 := TAppearanceNode.Create;
Material191 := TMaterialNode.Create;
Material191.DiffuseColor := Vector3(0.28,0.7,0);
Material191.EmissiveColor := Vector3(0.06,0.15,0);
Material191.Shininess := 0.8;
Material191.SpecularColor := Vector3(0.5,0.5,0.5);
IS192 := TISNode.Create;
connect193 := TconnectNode.Create;
connect193.NodeField := 'transparency';
connect193.ProtoField := 'materialTransparency';
{ .AddConnect }
IS192.Connect := connect193;
{ .SetIS }
Material191.IS := IS192;
{ .SetMaterial }
Appearance190.Material := Material191;
{ .SetAppearance }
Shape189.Appearance := Appearance190;
Sphere194 := TSphereNode.Create;
Sphere194.Radius := 1.01;
{ .SetGeometry }
Shape189.Geometry := Sphere194;
{ .AddChild }
Transform186.AddChildren([Shape189]);
Shape195 := TShapeNode.Create;
Appearance196 := TAppearanceNode.Create;
Material197 := TMaterialNode.Create;
Material197.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance196.Material := Material197;
{ .SetAppearance }
Shape195.Appearance := Appearance196;
Text198 := TTextNode.Create;
Text198.SetText(['Cl']);
FontStyle199 := TFontStyleNode.Create;
FontStyle199.Size := 0.8;
{ .SetFontStyle }
Text198.FontStyle := FontStyle199;
{ .SetGeometry }
Shape195.Geometry := Text198;
{ .AddChild }
Transform186.AddChildren([Shape195]);
{ .AddChildren }
Group185.AddChildren([Transform186]);
{ .AddChildren }
ProtoBody184.AddChildren([Group185]);
{ .SetProtoBody }
ProtoDeclare180.ProtoBody := ProtoBody184;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare180]);
ProtoDeclare200 := TProtoDeclareNode.Create;
ProtoDeclare200.NameField := 'Bromine';
ProtoInterface201 := TProtoInterfaceNode.Create;
field202 := TfieldNode.Create;
field202.NameField := 'position';
field202.AccessType := 'inputOutput';
field202.Type := 'SFVec3f';
field202.Value := '0 0 0';
{ .AddField }
ProtoInterface201.Field := field202;
field203 := TfieldNode.Create;
field203.NameField := 'materialTransparency';
field203.AccessType := 'inputOutput';
field203.Type := 'SFFloat';
field203.Value := '0.6';
{ .AddField }
ProtoInterface201.Field := field203;
{ .SetProtoInterface }
ProtoDeclare200.ProtoInterface := ProtoInterface201;
ProtoBody204 := TProtoBodyNode.Create;
Group205 := TGroupNode.Create;
Transform206 := TTransformNode.Create;
IS207 := TISNode.Create;
connect208 := TconnectNode.Create;
connect208.NodeField := 'translation';
connect208.ProtoField := 'position';
{ .AddConnect }
IS207.Connect := connect208;
{ .SetIS }
Transform206.IS := IS207;
Shape209 := TShapeNode.Create;
Appearance210 := TAppearanceNode.Create;
Material211 := TMaterialNode.Create;
Material211.AmbientIntensity := 0.0833;
Material211.DiffuseColor := Vector3(0.5,0.3,0.19);
Material211.EmissiveColor := Vector3(0.12,0.13,0.08);
Material211.Shininess := 0.17;
Material211.SpecularColor := Vector3(0.08,0.08,0.05);
IS212 := TISNode.Create;
connect213 := TconnectNode.Create;
connect213.NodeField := 'transparency';
connect213.ProtoField := 'materialTransparency';
{ .AddConnect }
IS212.Connect := connect213;
{ .SetIS }
Material211.IS := IS212;
{ .SetMaterial }
Appearance210.Material := Material211;
{ .SetAppearance }
Shape209.Appearance := Appearance210;
Sphere214 := TSphereNode.Create;
Sphere214.Radius := 1.14;
{ .SetGeometry }
Shape209.Geometry := Sphere214;
{ .AddChild }
Transform206.AddChildren([Shape209]);
Shape215 := TShapeNode.Create;
Appearance216 := TAppearanceNode.Create;
Material217 := TMaterialNode.Create;
Material217.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance216.Material := Material217;
{ .SetAppearance }
Shape215.Appearance := Appearance216;
Text218 := TTextNode.Create;
Text218.SetText(['Br']);
FontStyle219 := TFontStyleNode.Create;
FontStyle219.Size := 0.8;
{ .SetFontStyle }
Text218.FontStyle := FontStyle219;
{ .SetGeometry }
Shape215.Geometry := Text218;
{ .AddChild }
Transform206.AddChildren([Shape215]);
{ .AddChildren }
Group205.AddChildren([Transform206]);
{ .AddChildren }
ProtoBody204.AddChildren([Group205]);
{ .SetProtoBody }
ProtoDeclare200.ProtoBody := ProtoBody204;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare200]);
ProtoDeclare220 := TProtoDeclareNode.Create;
ProtoDeclare220.NameField := 'Iodine';
ProtoInterface221 := TProtoInterfaceNode.Create;
field222 := TfieldNode.Create;
field222.NameField := 'position';
field222.AccessType := 'inputOutput';
field222.Type := 'SFVec3f';
field222.Value := '0 0 0';
{ .AddField }
ProtoInterface221.Field := field222;
field223 := TfieldNode.Create;
field223.NameField := 'materialTransparency';
field223.AccessType := 'inputOutput';
field223.Type := 'SFFloat';
field223.Value := '0.6';
{ .AddField }
ProtoInterface221.Field := field223;
{ .SetProtoInterface }
ProtoDeclare220.ProtoInterface := ProtoInterface221;
ProtoBody224 := TProtoBodyNode.Create;
Group225 := TGroupNode.Create;
Transform226 := TTransformNode.Create;
IS227 := TISNode.Create;
connect228 := TconnectNode.Create;
connect228.NodeField := 'translation';
connect228.ProtoField := 'position';
{ .AddConnect }
IS227.Connect := connect228;
{ .SetIS }
Transform226.IS := IS227;
Shape229 := TShapeNode.Create;
Appearance230 := TAppearanceNode.Create;
Material231 := TMaterialNode.Create;
Material231.DiffuseColor := Vector3(0.56,0.37,0.74);
Material231.EmissiveColor := Vector3(0.15,0.1,0.2);
Material231.Shininess := 0.09;
Material231.SpecularColor := Vector3(0.12,0.12,0.12);
IS232 := TISNode.Create;
connect233 := TconnectNode.Create;
connect233.NodeField := 'transparency';
connect233.ProtoField := 'materialTransparency';
{ .AddConnect }
IS232.Connect := connect233;
{ .SetIS }
Material231.IS := IS232;
{ .SetMaterial }
Appearance230.Material := Material231;
{ .SetAppearance }
Shape229.Appearance := Appearance230;
Sphere234 := TSphereNode.Create;
Sphere234.Radius := 1.33;
{ .SetGeometry }
Shape229.Geometry := Sphere234;
{ .AddChild }
Transform226.AddChildren([Shape229]);
Shape235 := TShapeNode.Create;
Appearance236 := TAppearanceNode.Create;
Material237 := TMaterialNode.Create;
Material237.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance236.Material := Material237;
{ .SetAppearance }
Shape235.Appearance := Appearance236;
Text238 := TTextNode.Create;
Text238.SetText(['I']);
FontStyle239 := TFontStyleNode.Create;
FontStyle239.Size := 0.8;
{ .SetFontStyle }
Text238.FontStyle := FontStyle239;
{ .SetGeometry }
Shape235.Geometry := Text238;
{ .AddChild }
Transform226.AddChildren([Shape235]);
{ .AddChildren }
Group225.AddChildren([Transform226]);
{ .AddChildren }
ProtoBody224.AddChildren([Group225]);
{ .SetProtoBody }
ProtoDeclare220.ProtoBody := ProtoBody224;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare220]);
ProtoDeclare240 := TProtoDeclareNode.Create;
ProtoDeclare240.NameField := 'unknown';
ProtoInterface241 := TProtoInterfaceNode.Create;
field242 := TfieldNode.Create;
field242.NameField := 'position';
field242.AccessType := 'inputOutput';
field242.Type := 'SFVec3f';
field242.Value := '0 0 0';
{ .AddField }
ProtoInterface241.Field := field242;
field243 := TfieldNode.Create;
field243.NameField := 'materialTransparency';
field243.AccessType := 'inputOutput';
field243.Type := 'SFFloat';
field243.Value := '0.6';
{ .AddField }
ProtoInterface241.Field := field243;
{ .SetProtoInterface }
ProtoDeclare240.ProtoInterface := ProtoInterface241;
ProtoBody244 := TProtoBodyNode.Create;
Group245 := TGroupNode.Create;
Transform246 := TTransformNode.Create;
IS247 := TISNode.Create;
connect248 := TconnectNode.Create;
connect248.NodeField := 'translation';
connect248.ProtoField := 'position';
{ .AddConnect }
IS247.Connect := connect248;
{ .SetIS }
Transform246.IS := IS247;
Shape249 := TShapeNode.Create;
Appearance250 := TAppearanceNode.Create;
Material251 := TMaterialNode.Create;
Material251.DiffuseColor := Vector3(1,1,1);
Material251.EmissiveColor := Vector3(0.15,0.1,0.2);
Material251.Shininess := 0.09;
Material251.SpecularColor := Vector3(0.12,0.12,0.12);
IS252 := TISNode.Create;
connect253 := TconnectNode.Create;
connect253.NodeField := 'transparency';
connect253.ProtoField := 'materialTransparency';
{ .AddConnect }
IS252.Connect := connect253;
{ .SetIS }
Material251.IS := IS252;
{ .SetMaterial }
Appearance250.Material := Material251;
{ .SetAppearance }
Shape249.Appearance := Appearance250;
Sphere254 := TSphereNode.Create;
Sphere254.Radius := 1.001;
{ .SetGeometry }
Shape249.Geometry := Sphere254;
{ .AddChild }
Transform246.AddChildren([Shape249]);
Shape255 := TShapeNode.Create;
Appearance256 := TAppearanceNode.Create;
Material257 := TMaterialNode.Create;
Material257.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance256.Material := Material257;
{ .SetAppearance }
Shape255.Appearance := Appearance256;
Text258 := TTextNode.Create;
Text258.SetText(['?']);
FontStyle259 := TFontStyleNode.Create;
FontStyle259.Size := 0.8;
{ .SetFontStyle }
Text258.FontStyle := FontStyle259;
{ .SetGeometry }
Shape255.Geometry := Text258;
{ .AddChild }
Transform246.AddChildren([Shape255]);
{ .AddChildren }
Group245.AddChildren([Transform246]);
{ .AddChildren }
ProtoBody244.AddChildren([Group245]);
{ .SetProtoBody }
ProtoDeclare240.ProtoBody := ProtoBody244;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare240]);
ProtoDeclare260 := TProtoDeclareNode.Create;
ProtoDeclare260.NameField := 'line';
ProtoInterface261 := TProtoInterfaceNode.Create;
field262 := TfieldNode.Create;
field262.NameField := 'bond_set';
field262.AccessType := 'inputOutput';
field262.Type := 'MFVec3f';
field262.Value := '-1 0 0 1 0 0';
{ .AddField }
ProtoInterface261.Field := field262;
{ .SetProtoInterface }
ProtoDeclare260.ProtoInterface := ProtoInterface261;
ProtoBody263 := TProtoBodyNode.Create;
Group264 := TGroupNode.Create;
Shape265 := TShapeNode.Create;
Appearance266 := TAppearanceNode.Create;
Material267 := TMaterialNode.Create;
Material267.DiffuseColor := Vector3(1,1,1);
Material267.EmissiveColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance266.Material := Material267;
{ .SetAppearance }
Shape265.Appearance := Appearance266;
IndexedLineSet268 := TIndexedLineSetNode.Create;
IndexedLineSet268.SetCoordIndex([0,1,-1]);
Coordinate269 := TCoordinateNode.Create;
IS270 := TISNode.Create;
connect271 := TconnectNode.Create;
connect271.NodeField := 'point';
connect271.ProtoField := 'bond_set';
{ .AddConnect }
IS270.Connect := connect271;
{ .SetIS }
Coordinate269.IS := IS270;
{ .SetCoord }
IndexedLineSet268.Coord := Coordinate269;
{ .SetGeometry }
Shape265.Geometry := IndexedLineSet268;
{ .AddChildren }
Group264.AddChildren([Shape265]);
{ .AddChildren }
ProtoBody263.AddChildren([Group264]);
{ .SetProtoBody }
ProtoDeclare260.ProtoBody := ProtoBody263;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare260]);
ProtoDeclare272 := TProtoDeclareNode.Create;
ProtoDeclare272.NameField := 'title_text';
ProtoInterface273 := TProtoInterfaceNode.Create;
field274 := TfieldNode.Create;
field274.NameField := 'txt';
field274.AccessType := 'inputOutput';
field274.Type := 'MFString';
{ .AddField }
ProtoInterface273.Field := field274;
{ .SetProtoInterface }
ProtoDeclare272.ProtoInterface := ProtoInterface273;
ProtoBody275 := TProtoBodyNode.Create;
Transform276 := TTransformNode.Create;
Group277 := TGroupNode.Create;
Transform278 := TTransformNode.Create;
Shape279 := TShapeNode.Create;
Appearance280 := TAppearanceNode.Create;
Material281 := TMaterialNode.Create;
Material281.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance280.Material := Material281;
{ .SetAppearance }
Shape279.Appearance := Appearance280;
Text282 := TTextNode.Create;
IS283 := TISNode.Create;
connect284 := TconnectNode.Create;
connect284.NodeField := 'string';
connect284.ProtoField := 'txt';
{ .AddConnect }
IS283.Connect := connect284;
{ .SetIS }
Text282.IS := IS283;
FontStyle285 := TFontStyleNode.Create;
{ .SetFontStyle }
Text282.FontStyle := FontStyle285;
{ .SetGeometry }
Shape279.Geometry := Text282;
{ .AddChild }
Transform278.AddChildren([Shape279]);
{ .AddChildren }
Group277.AddChildren([Transform278]);
{ .AddChildren }
Transform276.AddChildren([Group277]);
{ .AddChildren }
ProtoBody275.AddChildren([Transform276]);
{ .SetProtoBody }
ProtoDeclare272.ProtoBody := ProtoBody275;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare272]);
ProtoDeclare286 := TProtoDeclareNode.Create;
ProtoDeclare286.NameField := 'ano1_text';
ProtoInterface287 := TProtoInterfaceNode.Create;
field288 := TfieldNode.Create;
field288.NameField := 'txt';
field288.AccessType := 'inputOutput';
field288.Type := 'MFString';
{ .AddField }
ProtoInterface287.Field := field288;
{ .SetProtoInterface }
ProtoDeclare286.ProtoInterface := ProtoInterface287;
ProtoBody289 := TProtoBodyNode.Create;
Transform290 := TTransformNode.Create;
Group291 := TGroupNode.Create;
Transform292 := TTransformNode.Create;
Shape293 := TShapeNode.Create;
Appearance294 := TAppearanceNode.Create;
Material295 := TMaterialNode.Create;
Material295.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance294.Material := Material295;
{ .SetAppearance }
Shape293.Appearance := Appearance294;
Text296 := TTextNode.Create;
IS297 := TISNode.Create;
connect298 := TconnectNode.Create;
connect298.NodeField := 'string';
connect298.ProtoField := 'txt';
{ .AddConnect }
IS297.Connect := connect298;
{ .SetIS }
Text296.IS := IS297;
FontStyle299 := TFontStyleNode.Create;
FontStyle299.Size := 0.8;
{ .SetFontStyle }
Text296.FontStyle := FontStyle299;
{ .SetGeometry }
Shape293.Geometry := Text296;
{ .AddChild }
Transform292.AddChildren([Shape293]);
{ .AddChildren }
Group291.AddChildren([Transform292]);
{ .AddChildren }
Transform290.AddChildren([Group291]);
{ .AddChildren }
ProtoBody289.AddChildren([Transform290]);
{ .SetProtoBody }
ProtoDeclare286.ProtoBody := ProtoBody289;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare286]);
ProtoDeclare300 := TProtoDeclareNode.Create;
ProtoDeclare300.NameField := 'ano2_text';
ProtoInterface301 := TProtoInterfaceNode.Create;
field302 := TfieldNode.Create;
field302.NameField := 'txt';
field302.AccessType := 'inputOutput';
field302.Type := 'MFString';
{ .AddField }
ProtoInterface301.Field := field302;
{ .SetProtoInterface }
ProtoDeclare300.ProtoInterface := ProtoInterface301;
ProtoBody303 := TProtoBodyNode.Create;
Transform304 := TTransformNode.Create;
Group305 := TGroupNode.Create;
Transform306 := TTransformNode.Create;
Shape307 := TShapeNode.Create;
Appearance308 := TAppearanceNode.Create;
Material309 := TMaterialNode.Create;
Material309.DiffuseColor := Vector3(0.9,0.9,0.9);
{ .SetMaterial }
Appearance308.Material := Material309;
{ .SetAppearance }
Shape307.Appearance := Appearance308;
Text310 := TTextNode.Create;
IS311 := TISNode.Create;
connect312 := TconnectNode.Create;
connect312.NodeField := 'string';
connect312.ProtoField := 'txt';
{ .AddConnect }
IS311.Connect := connect312;
{ .SetIS }
Text310.IS := IS311;
FontStyle313 := TFontStyleNode.Create;
FontStyle313.Size := 0.6;
{ .SetFontStyle }
Text310.FontStyle := FontStyle313;
{ .SetGeometry }
Shape307.Geometry := Text310;
{ .AddChild }
Transform306.AddChildren([Shape307]);
{ .AddChildren }
Group305.AddChildren([Transform306]);
{ .AddChildren }
Transform304.AddChildren([Group305]);
{ .AddChildren }
ProtoBody303.AddChildren([Transform304]);
{ .SetProtoBody }
ProtoDeclare300.ProtoBody := ProtoBody303;
{ .AddChildren }
Group19.AddChildren([ProtoDeclare300]);
Background314 := TBackgroundNode.Create;
Background314.SetGroundAngle([1.309,1.570796]);
Background314.SetGroundColor([Vector3(0,0.5,0.7),Vector3(0,0.4,0.7),Vector3(0.6,0.5,0.7)]);
Background314.SetSkyAngle([1.309,1.570796]);
Background314.SetSkyColor([Vector3(0,0.5,0.8),Vector3(0,0.6,0.7),Vector3(0.6,0.6,0.7)]);
{ .AddChildren }
Group19.AddChildren([Background314]);
PointLight315 := TPointLightNode.Create;
PointLight315.AmbientIntensity := 1;
PointLight315.Location := Vector3(0,0,5);
PointLight315.Radius := 30;
{ .AddChildren }
Group19.AddChildren([PointLight315]);
NavigationInfo316 := TNavigationInfoNode.Create;
NavigationInfo316.SetType(['EXAMINE','FLY','ANY']);
{ .AddChildren }
Group19.AddChildren([NavigationInfo316]);
Viewpoint317 := TViewpointNode.Create;
Viewpoint317.Description := 'Inspect Oxytocin';
Viewpoint317.Position := Vector3(0,2,20);
{ .AddChildren }
Group19.AddChildren([Viewpoint317]);
{ Copyright by the U.S. Sec. Commerce on behalf of U.S.A. All rights reserved. }
{ type="3D" <date day="23" month="11" year="1995"/> }
Transform318 := TTransformNode.Create;
Transform318.Translation := Vector3(-8,2,-4);
Transform319 := TTransformNode.Create;
Transform319.Translation := Vector3(0,6,0);
Viewpoint320 := TViewpointNode.Create;
Viewpoint320.Description := 'title billboard';
Viewpoint320.Position := Vector3(6,-2,10);
{ .AddChildren }
Transform319.AddChildren([Viewpoint320]);
ProtoInstance321 := TProtoInstanceNode.Create;
ProtoInstance321.NameField := 'title_text';
fieldValue322 := TfieldValueNode.Create;
fieldValue322.NameField := 'txt';
fieldValue322.Value := '\"Oxytocin: \"';
{ .AddFieldValue }
ProtoInstance321.FieldValue := fieldValue322;
{ .AddChildren }
Transform319.AddChildren([ProtoInstance321]);
{ .AddChildren }
Transform318.AddChildren([Transform319]);
{ .AddChildren }
Group19.AddChildren([Transform318]);
Group323 := TGroupNode.Create;
Transform324 := TTransformNode.Create;
ProtoInstance325 := TProtoInstanceNode.Create;
ProtoInstance325.NameField := 'Nitrogen';
fieldValue326 := TfieldValueNode.Create;
fieldValue326.NameField := 'position';
fieldValue326.Value := '-2.0514 1.8507 0';
{ .AddFieldValue }
ProtoInstance325.FieldValue := fieldValue326;
{ .AddChildren }
Transform324.AddChildren([ProtoInstance325]);
{ .AddChildren }
Group323.AddChildren([Transform324]);
Transform327 := TTransformNode.Create;
ProtoInstance328 := TProtoInstanceNode.Create;
ProtoInstance328.NameField := 'Carbon';
fieldValue329 := TfieldValueNode.Create;
fieldValue329.NameField := 'position';
fieldValue329.Value := '-3.601 1.9845 0';
{ .AddFieldValue }
ProtoInstance328.FieldValue := fieldValue329;
{ .AddChildren }
Transform327.AddChildren([ProtoInstance328]);
{ .AddChildren }
Group323.AddChildren([Transform327]);
Transform330 := TTransformNode.Create;
ProtoInstance331 := TProtoInstanceNode.Create;
ProtoInstance331.NameField := 'Carbon';
fieldValue332 := TfieldValueNode.Create;
fieldValue332.NameField := 'position';
fieldValue332.Value := '-1.2821 0.4905 0';
{ .AddFieldValue }
ProtoInstance331.FieldValue := fieldValue332;
{ .AddChildren }
Transform330.AddChildren([ProtoInstance331]);
{ .AddChildren }
Group323.AddChildren([Transform330]);
Transform333 := TTransformNode.Create;
ProtoInstance334 := TProtoInstanceNode.Create;
ProtoInstance334.NameField := 'Carbon';
fieldValue335 := TfieldValueNode.Create;
fieldValue335.NameField := 'position';
fieldValue335.Value := '-1.4159 3.2554 0';
{ .AddFieldValue }
ProtoInstance334.FieldValue := fieldValue335;
{ .AddChildren }
Transform333.AddChildren([ProtoInstance334]);
{ .AddChildren }
Group323.AddChildren([Transform333]);
Transform336 := TTransformNode.Create;
ProtoInstance337 := TProtoInstanceNode.Create;
ProtoInstance337.NameField := 'Carbon';
fieldValue338 := TfieldValueNode.Create;
fieldValue338.NameField := 'position';
fieldValue338.Value := '-4.649 0.8473 0';
{ .AddFieldValue }
ProtoInstance337.FieldValue := fieldValue338;
{ .AddChildren }
Transform336.AddChildren([ProtoInstance337]);
{ .AddChildren }
Group323.AddChildren([Transform336]);
Transform339 := TTransformNode.Create;
ProtoInstance340 := TProtoInstanceNode.Create;
ProtoInstance340.NameField := 'Carbon';
fieldValue341 := TfieldValueNode.Create;
fieldValue341.NameField := 'position';
fieldValue341.Value := '-3.9355 3.5341 0';
{ .AddFieldValue }
ProtoInstance340.FieldValue := fieldValue341;
{ .AddChildren }
Transform339.AddChildren([ProtoInstance340]);
{ .AddChildren }
Group323.AddChildren([Transform339]);
Transform342 := TTransformNode.Create;
ProtoInstance343 := TProtoInstanceNode.Create;
ProtoInstance343.NameField := 'Carbon';
fieldValue344 := TfieldValueNode.Create;
fieldValue344.NameField := 'position';
fieldValue344.Value := '0.2341 0.4905 0';
{ .AddFieldValue }
ProtoInstance343.FieldValue := fieldValue344;
{ .AddChildren }
Transform342.AddChildren([ProtoInstance343]);
{ .AddChildren }
Group323.AddChildren([Transform342]);
Transform345 := TTransformNode.Create;
ProtoInstance346 := TProtoInstanceNode.Create;
ProtoInstance346.NameField := 'Oxygen';
fieldValue347 := TfieldValueNode.Create;
fieldValue347.NameField := 'position';
fieldValue347.Value := '-2.0514 -0.8362 0';
{ .AddFieldValue }
ProtoInstance346.FieldValue := fieldValue347;
{ .AddChildren }
Transform345.AddChildren([ProtoInstance346]);
{ .AddChildren }
Group323.AddChildren([Transform345]);
Transform348 := TTransformNode.Create;
ProtoInstance349 := TProtoInstanceNode.Create;
ProtoInstance349.NameField := 'Carbon';
fieldValue350 := TfieldValueNode.Create;
fieldValue350.NameField := 'position';
fieldValue350.Value := '-2.5753 4.3034 0';
{ .AddFieldValue }
ProtoInstance349.FieldValue := fieldValue350;
{ .AddChildren }
Transform348.AddChildren([ProtoInstance349]);
{ .AddChildren }
Group323.AddChildren([Transform348]);
Transform351 := TTransformNode.Create;
ProtoInstance352 := TProtoInstanceNode.Create;
ProtoInstance352.NameField := 'Nitrogen';
fieldValue353 := TfieldValueNode.Create;
fieldValue353.NameField := 'position';
fieldValue353.Value := '-6.1764 1.1595 0';
{ .AddFieldValue }
ProtoInstance352.FieldValue := fieldValue353;
{ .AddChildren }
Transform351.AddChildren([ProtoInstance352]);
{ .AddChildren }
Group323.AddChildren([Transform351]);
Transform354 := TTransformNode.Create;
ProtoInstance355 := TProtoInstanceNode.Create;
ProtoInstance355.NameField := 'Oxygen';
fieldValue356 := TfieldValueNode.Create;
fieldValue356.NameField := 'position';
fieldValue356.Value := '-4.1585 -0.6132 0';
{ .AddFieldValue }
ProtoInstance355.FieldValue := fieldValue356;
{ .AddChildren }
Transform354.AddChildren([ProtoInstance355]);
{ .AddChildren }
Group323.AddChildren([Transform354]);
Transform357 := TTransformNode.Create;
ProtoInstance358 := TProtoInstanceNode.Create;
ProtoInstance358.NameField := 'Nitrogen';
fieldValue359 := TfieldValueNode.Create;
fieldValue359.NameField := 'position';
fieldValue359.Value := '0.4905 2.0402 0';
{ .AddFieldValue }
ProtoInstance358.FieldValue := fieldValue359;
{ .AddChildren }
Transform357.AddChildren([ProtoInstance358]);
{ .AddChildren }
Group323.AddChildren([Transform357]);
Transform360 := TTransformNode.Create;
ProtoInstance361 := TProtoInstanceNode.Create;
ProtoInstance361.NameField := 'Carbon';
fieldValue362 := TfieldValueNode.Create;
fieldValue362.NameField := 'position';
fieldValue362.Value := '0.4905 -1.0257 0';
{ .AddFieldValue }
ProtoInstance361.FieldValue := fieldValue362;
{ .AddChildren }
Transform360.AddChildren([ProtoInstance361]);
{ .AddChildren }
Group323.AddChildren([Transform360]);
Transform363 := TTransformNode.Create;
ProtoInstance364 := TProtoInstanceNode.Create;
ProtoInstance364.NameField := 'Carbon';
fieldValue365 := TfieldValueNode.Create;
fieldValue365.NameField := 'position';
fieldValue365.Value := '-7.2243 0.0223 0';
{ .AddFieldValue }
ProtoInstance364.FieldValue := fieldValue365;
{ .AddChildren }
Transform363.AddChildren([ProtoInstance364]);
{ .AddChildren }
Group323.AddChildren([Transform363]);
Transform366 := TTransformNode.Create;
ProtoInstance367 := TProtoInstanceNode.Create;
ProtoInstance367.NameField := 'Carbon';
fieldValue368 := TfieldValueNode.Create;
fieldValue368.NameField := 'position';
fieldValue368.Value := '1.2041 3.3892 0';
{ .AddFieldValue }
ProtoInstance367.FieldValue := fieldValue368;
{ .AddChildren }
Transform366.AddChildren([ProtoInstance367]);
{ .AddChildren }
Group323.AddChildren([Transform366]);
Transform369 := TTransformNode.Create;
ProtoInstance370 := TProtoInstanceNode.Create;
ProtoInstance370.NameField := 'Sulphur';
fieldValue371 := TfieldValueNode.Create;
fieldValue371.NameField := 'position';
fieldValue371.Value := '1.1706 -2.4081 0';
{ .AddFieldValue }
ProtoInstance370.FieldValue := fieldValue371;
{ .AddChildren }
Transform369.AddChildren([ProtoInstance370]);
{ .AddChildren }
Group323.AddChildren([Transform369]);
Transform372 := TTransformNode.Create;
ProtoInstance373 := TProtoInstanceNode.Create;
ProtoInstance373.NameField := 'Carbon';
fieldValue374 := TfieldValueNode.Create;
fieldValue374.NameField := 'position';
fieldValue374.Value := '-8.7071 0.3568 0';
{ .AddFieldValue }
ProtoInstance373.FieldValue := fieldValue374;
{ .AddChildren }
Transform372.AddChildren([ProtoInstance373]);
{ .AddChildren }
Group323.AddChildren([Transform372]);
Transform375 := TTransformNode.Create;
ProtoInstance376 := TProtoInstanceNode.Create;
ProtoInstance376.NameField := 'Carbon';
fieldValue377 := TfieldValueNode.Create;
fieldValue377.NameField := 'position';
fieldValue377.Value := '-6.7226 -1.4382 0';
{ .AddFieldValue }
ProtoInstance376.FieldValue := fieldValue377;
{ .AddChildren }
Transform375.AddChildren([ProtoInstance376]);
{ .AddChildren }
Group323.AddChildren([Transform375]);
Transform378 := TTransformNode.Create;
ProtoInstance379 := TProtoInstanceNode.Create;
ProtoInstance379.NameField := 'Carbon';
fieldValue380 := TfieldValueNode.Create;
fieldValue380.NameField := 'position';
fieldValue380.Value := '2.3078 4.4929 0';
{ .AddFieldValue }
ProtoInstance379.FieldValue := fieldValue380;
{ .AddChildren }
Transform378.AddChildren([ProtoInstance379]);
{ .AddChildren }
Group323.AddChildren([Transform378]);
Transform381 := TTransformNode.Create;
ProtoInstance382 := TProtoInstanceNode.Create;
ProtoInstance382.NameField := 'Oxygen';
fieldValue383 := TfieldValueNode.Create;
fieldValue383.NameField := 'position';
fieldValue383.Value := '-0.0446 4.3368 0';
{ .AddFieldValue }
ProtoInstance382.FieldValue := fieldValue383;
{ .AddChildren }
Transform381.AddChildren([ProtoInstance382]);
{ .AddChildren }
Group323.AddChildren([Transform381]);
Transform384 := TTransformNode.Create;
ProtoInstance385 := TProtoInstanceNode.Create;
ProtoInstance385.NameField := 'Sulphur';
fieldValue386 := TfieldValueNode.Create;
fieldValue386.NameField := 'position';
fieldValue386.Value := '2.2855 -3.5118 0';
{ .AddFieldValue }
ProtoInstance385.FieldValue := fieldValue386;
{ .AddChildren }
Transform384.AddChildren([ProtoInstance385]);
{ .AddChildren }
Group323.AddChildren([Transform384]);
Transform387 := TTransformNode.Create;
ProtoInstance388 := TProtoInstanceNode.Create;
ProtoInstance388.NameField := 'Nitrogen';
fieldValue389 := TfieldValueNode.Create;
fieldValue389.NameField := 'position';
fieldValue389.Value := '-9.7662 -0.7804 0';
{ .AddFieldValue }
ProtoInstance388.FieldValue := fieldValue389;
{ .AddChildren }
Transform387.AddChildren([ProtoInstance388]);
{ .AddChildren }
Group323.AddChildren([Transform387]);
Transform390 := TTransformNode.Create;
ProtoInstance391 := TProtoInstanceNode.Create;
ProtoInstance391.NameField := 'Oxygen';
fieldValue392 := TfieldValueNode.Create;
fieldValue392.NameField := 'position';
fieldValue392.Value := '-9.2088 1.8507 0';
{ .AddFieldValue }
ProtoInstance391.FieldValue := fieldValue392;
{ .AddChildren }
Transform390.AddChildren([ProtoInstance391]);
{ .AddChildren }
Group323.AddChildren([Transform390]);
Transform393 := TTransformNode.Create;
ProtoInstance394 := TProtoInstanceNode.Create;
ProtoInstance394.NameField := 'Carbon';
fieldValue395 := TfieldValueNode.Create;
fieldValue395.NameField := 'position';
fieldValue395.Value := '-7.7483 -2.5753 0';
{ .AddFieldValue }
ProtoInstance394.FieldValue := fieldValue395;
{ .AddChildren }
Transform393.AddChildren([ProtoInstance394]);
{ .AddChildren }
Group323.AddChildren([Transform393]);
Transform396 := TTransformNode.Create;
ProtoInstance397 := TProtoInstanceNode.Create;
ProtoInstance397.NameField := 'Nitrogen';
fieldValue398 := TfieldValueNode.Create;
fieldValue398.NameField := 'position';
fieldValue398.Value := '3.6902 5.1841 0';
{ .AddFieldValue }
ProtoInstance397.FieldValue := fieldValue398;
{ .AddChildren }
Transform396.AddChildren([ProtoInstance397]);
{ .AddChildren }
Group323.AddChildren([Transform396]);
Transform399 := TTransformNode.Create;
ProtoInstance400 := TProtoInstanceNode.Create;
ProtoInstance400.NameField := 'Carbon';
fieldValue401 := TfieldValueNode.Create;
fieldValue401.NameField := 'position';
fieldValue401.Value := '1.3936 5.7416 0';
{ .AddFieldValue }
ProtoInstance400.FieldValue := fieldValue401;
{ .AddChildren }
Transform399.AddChildren([ProtoInstance400]);
{ .AddChildren }
Group323.AddChildren([Transform399]);
Transform402 := TTransformNode.Create;
ProtoInstance403 := TProtoInstanceNode.Create;
ProtoInstance403.NameField := 'Carbon';
fieldValue404 := TfieldValueNode.Create;
fieldValue404.NameField := 'position';
fieldValue404.Value := '3.6568 -4.2253 0';
{ .AddFieldValue }
ProtoInstance403.FieldValue := fieldValue404;
{ .AddChildren }
Transform402.AddChildren([ProtoInstance403]);
{ .AddChildren }
Group323.AddChildren([Transform402]);
Transform405 := TTransformNode.Create;
ProtoInstance406 := TProtoInstanceNode.Create;
ProtoInstance406.NameField := 'Carbon';
fieldValue407 := TfieldValueNode.Create;
fieldValue407.NameField := 'position';
fieldValue407.Value := '-11.2825 -0.4459 0';
{ .AddFieldValue }
ProtoInstance406.FieldValue := fieldValue407;
{ .AddChildren }
Transform405.AddChildren([ProtoInstance406]);
{ .AddChildren }
Group323.AddChildren([Transform405]);
Transform408 := TTransformNode.Create;
ProtoInstance409 := TProtoInstanceNode.Create;
ProtoInstance409.NameField := 'Carbon';
fieldValue410 := TfieldValueNode.Create;
fieldValue410.NameField := 'position';
fieldValue410.Value := '-7.2243 -4.0693 0';
{ .AddFieldValue }
ProtoInstance409.FieldValue := fieldValue410;
{ .AddChildren }
Transform408.AddChildren([ProtoInstance409]);
{ .AddChildren }
Group323.AddChildren([Transform408]);
Transform411 := TTransformNode.Create;
ProtoInstance412 := TProtoInstanceNode.Create;
ProtoInstance412.NameField := 'Carbon';
fieldValue413 := TfieldValueNode.Create;
fieldValue413.NameField := 'position';
fieldValue413.Value := '-8.7963 -2.4081 0';
{ .AddFieldValue }
ProtoInstance412.FieldValue := fieldValue413;
{ .AddChildren }
Transform411.AddChildren([ProtoInstance412]);
{ .AddChildren }
Group323.AddChildren([Transform411]);
Transform414 := TTransformNode.Create;
ProtoInstance415 := TProtoInstanceNode.Create;
ProtoInstance415.NameField := 'Carbon';
fieldValue416 := TfieldValueNode.Create;
fieldValue416.NameField := 'position';
fieldValue416.Value := '5.2064 5.4405 0';
{ .AddFieldValue }
ProtoInstance415.FieldValue := fieldValue416;
{ .AddChildren }
Transform414.AddChildren([ProtoInstance415]);
{ .AddChildren }
Group323.AddChildren([Transform414]);
Transform417 := TTransformNode.Create;
ProtoInstance418 := TProtoInstanceNode.Create;
ProtoInstance418.NameField := 'Carbon';
fieldValue419 := TfieldValueNode.Create;
fieldValue419.NameField := 'position';
fieldValue419.Value := '2.0291 7.1797 0';
{ .AddFieldValue }
ProtoInstance418.FieldValue := fieldValue419;
{ .AddChildren }
Transform417.AddChildren([ProtoInstance418]);
{ .AddChildren }
Group323.AddChildren([Transform417]);
Transform420 := TTransformNode.Create;
ProtoInstance421 := TProtoInstanceNode.Create;
ProtoInstance421.NameField := 'Carbon';
fieldValue422 := TfieldValueNode.Create;
fieldValue422.NameField := 'position';
fieldValue422.Value := '5.1841 -4.4818 0';
{ .AddFieldValue }
ProtoInstance421.FieldValue := fieldValue422;
{ .AddChildren }
Transform420.AddChildren([ProtoInstance421]);
{ .AddChildren }
Group323.AddChildren([Transform420]);
Transform423 := TTransformNode.Create;
ProtoInstance424 := TProtoInstanceNode.Create;
ProtoInstance424.NameField := 'Carbon';
fieldValue425 := TfieldValueNode.Create;
fieldValue425.NameField := 'position';
fieldValue425.Value := '-12.3304 -1.6054 0';
{ .AddFieldValue }
ProtoInstance424.FieldValue := fieldValue425;
{ .AddChildren }
Transform423.AddChildren([ProtoInstance424]);
{ .AddChildren }
Group323.AddChildren([Transform423]);
Transform426 := TTransformNode.Create;
ProtoInstance427 := TProtoInstanceNode.Create;
ProtoInstance427.NameField := 'Carbon';
fieldValue428 := TfieldValueNode.Create;
fieldValue428.NameField := 'position';
fieldValue428.Value := '6.7561 5.1841 0';
{ .AddFieldValue }
ProtoInstance427.FieldValue := fieldValue428;
{ .AddChildren }
Transform426.AddChildren([ProtoInstance427]);
{ .AddChildren }
Group323.AddChildren([Transform426]);
Transform429 := TTransformNode.Create;
ProtoInstance430 := TProtoInstanceNode.Create;
ProtoInstance430.NameField := 'Oxygen';
fieldValue431 := TfieldValueNode.Create;
fieldValue431.NameField := 'position';
fieldValue431.Value := '5.2399 6.9791 0';
{ .AddFieldValue }
ProtoInstance430.FieldValue := fieldValue431;
{ .AddChildren }
Transform429.AddChildren([ProtoInstance430]);
{ .AddChildren }
Group323.AddChildren([Transform429]);
Transform432 := TTransformNode.Create;
ProtoInstance433 := TProtoInstanceNode.Create;
ProtoInstance433.NameField := 'Nitrogen';
fieldValue434 := TfieldValueNode.Create;
fieldValue434.NameField := 'position';
fieldValue434.Value := '1.126 8.4507 0';
{ .AddFieldValue }
ProtoInstance433.FieldValue := fieldValue434;
{ .AddChildren }
Transform432.AddChildren([ProtoInstance433]);
{ .AddChildren }
Group323.AddChildren([Transform432]);
Transform435 := TTransformNode.Create;
ProtoInstance436 := TProtoInstanceNode.Create;
ProtoInstance436.NameField := 'Oxygen';
fieldValue437 := TfieldValueNode.Create;
fieldValue437.NameField := 'position';
fieldValue437.Value := '3.5787 7.3135 0';
{ .AddFieldValue }
ProtoInstance436.FieldValue := fieldValue437;
{ .AddChildren }
Transform435.AddChildren([ProtoInstance436]);
{ .AddChildren }
Group323.AddChildren([Transform435]);
Transform438 := TTransformNode.Create;
ProtoInstance439 := TProtoInstanceNode.Create;
ProtoInstance439.NameField := 'Carbon';
fieldValue440 := TfieldValueNode.Create;
fieldValue440.NameField := 'position';
fieldValue440.Value := '6.7226 -4.2253 0';
{ .AddFieldValue }
ProtoInstance439.FieldValue := fieldValue440;
{ .AddChildren }
Transform438.AddChildren([ProtoInstance439]);
{ .AddChildren }
Group323.AddChildren([Transform438]);
Transform441 := TTransformNode.Create;
ProtoInstance442 := TProtoInstanceNode.Create;
ProtoInstance442.NameField := 'Nitrogen';
fieldValue443 := TfieldValueNode.Create;
fieldValue443.NameField := 'position';
fieldValue443.Value := '5.1841 -6.0203 0';
{ .AddFieldValue }
ProtoInstance442.FieldValue := fieldValue443;
{ .AddChildren }
Transform441.AddChildren([ProtoInstance442]);
{ .AddChildren }
Group323.AddChildren([Transform441]);
Transform444 := TTransformNode.Create;
ProtoInstance445 := TProtoInstanceNode.Create;
ProtoInstance445.NameField := 'Nitrogen';
fieldValue446 := TfieldValueNode.Create;
fieldValue446.NameField := 'position';
fieldValue446.Value := '-13.8466 -1.2709 0';
{ .AddFieldValue }
ProtoInstance445.FieldValue := fieldValue446;
{ .AddChildren }
Transform444.AddChildren([ProtoInstance445]);
{ .AddChildren }
Group323.AddChildren([Transform444]);
Transform447 := TTransformNode.Create;
ProtoInstance448 := TProtoInstanceNode.Create;
ProtoInstance448.NameField := 'Oxygen';
fieldValue449 := TfieldValueNode.Create;
fieldValue449.NameField := 'position';
fieldValue449.Value := '-11.8622 -3.0659 0';
{ .AddFieldValue }
ProtoInstance448.FieldValue := fieldValue449;
{ .AddChildren }
Transform447.AddChildren([ProtoInstance448]);
{ .AddChildren }
Group323.AddChildren([Transform447]);
Transform450 := TTransformNode.Create;
ProtoInstance451 := TProtoInstanceNode.Create;
ProtoInstance451.NameField := 'Nitrogen';
fieldValue452 := TfieldValueNode.Create;
fieldValue452.NameField := 'position';
fieldValue452.Value := '8.1385 4.4706 0';
{ .AddFieldValue }
ProtoInstance451.FieldValue := fieldValue452;
{ .AddChildren }
Transform450.AddChildren([ProtoInstance451]);
{ .AddChildren }
Group323.AddChildren([Transform450]);
Transform453 := TTransformNode.Create;
ProtoInstance454 := TProtoInstanceNode.Create;
ProtoInstance454.NameField := 'Carbon';
fieldValue455 := TfieldValueNode.Create;
fieldValue455.NameField := 'position';
fieldValue455.Value := '7.2243 6.6781 0';
{ .AddFieldValue }
ProtoInstance454.FieldValue := fieldValue455;
{ .AddChildren }
Transform453.AddChildren([ProtoInstance454]);
{ .AddChildren }
Group323.AddChildren([Transform453]);
Transform456 := TTransformNode.Create;
ProtoInstance457 := TProtoInstanceNode.Create;
ProtoInstance457.NameField := 'Nitrogen';
fieldValue458 := TfieldValueNode.Create;
fieldValue458.NameField := 'position';
fieldValue458.Value := '8.1051 -3.5341 0';
{ .AddFieldValue }
ProtoInstance457.FieldValue := fieldValue458;
{ .AddChildren }
Transform456.AddChildren([ProtoInstance457]);
{ .AddChildren }
Group323.AddChildren([Transform456]);
Transform459 := TTransformNode.Create;
ProtoInstance460 := TProtoInstanceNode.Create;
ProtoInstance460.NameField := 'Oxygen';
fieldValue461 := TfieldValueNode.Create;
fieldValue461.NameField := 'position';
fieldValue461.Value := '7.202 -5.7193 0';
{ .AddFieldValue }
ProtoInstance460.FieldValue := fieldValue461;
{ .AddChildren }
Transform459.AddChildren([ProtoInstance460]);
{ .AddChildren }
Group323.AddChildren([Transform459]);
Transform462 := TTransformNode.Create;
ProtoInstance463 := TProtoInstanceNode.Create;
ProtoInstance463.NameField := 'Carbon';
fieldValue464 := TfieldValueNode.Create;
fieldValue464.NameField := 'position';
fieldValue464.Value := '9.2422 3.3669 0';
{ .AddFieldValue }
ProtoInstance463.FieldValue := fieldValue464;
{ .AddChildren }
Transform462.AddChildren([ProtoInstance463]);
{ .AddChildren }
Group323.AddChildren([Transform462]);
Transform465 := TTransformNode.Create;
ProtoInstance466 := TProtoInstanceNode.Create;
ProtoInstance466.NameField := 'Carbon';
fieldValue467 := TfieldValueNode.Create;
fieldValue467.NameField := 'position';
fieldValue467.Value := '8.7406 6.9791 0';
{ .AddFieldValue }
ProtoInstance466.FieldValue := fieldValue467;
{ .AddChildren }
Transform465.AddChildren([ProtoInstance466]);
{ .AddChildren }
Group323.AddChildren([Transform465]);
Transform468 := TTransformNode.Create;
ProtoInstance469 := TProtoInstanceNode.Create;
ProtoInstance469.NameField := 'Carbon';
fieldValue470 := TfieldValueNode.Create;
fieldValue470.NameField := 'position';
fieldValue470.Value := '9.2088 -2.4304 0';
{ .AddFieldValue }
ProtoInstance469.FieldValue := fieldValue470;
{ .AddChildren }
Transform468.AddChildren([ProtoInstance469]);
{ .AddChildren }
Group323.AddChildren([Transform468]);
Transform471 := TTransformNode.Create;
ProtoInstance472 := TProtoInstanceNode.Create;
ProtoInstance472.NameField := 'Carbon';
fieldValue473 := TfieldValueNode.Create;
fieldValue473.NameField := 'position';
fieldValue473.Value := '9.9335 1.9845 0';
{ .AddFieldValue }
ProtoInstance472.FieldValue := fieldValue473;
{ .AddChildren }
Transform471.AddChildren([ProtoInstance472]);
{ .AddChildren }
Group323.AddChildren([Transform471]);
Transform474 := TTransformNode.Create;
ProtoInstance475 := TProtoInstanceNode.Create;
ProtoInstance475.NameField := 'Oxygen';
fieldValue476 := TfieldValueNode.Create;
fieldValue476.NameField := 'position';
fieldValue476.Value := '10.4797 4.3034 0';
{ .AddFieldValue }
ProtoInstance475.FieldValue := fieldValue476;
{ .AddChildren }
Transform474.AddChildren([ProtoInstance475]);
{ .AddChildren }
Group323.AddChildren([Transform474]);
Transform477 := TTransformNode.Create;
ProtoInstance478 := TProtoInstanceNode.Create;
ProtoInstance478.NameField := 'Carbon';
fieldValue479 := TfieldValueNode.Create;
fieldValue479.NameField := 'position';
fieldValue479.Value := '9.2422 8.4507 0';
{ .AddFieldValue }
ProtoInstance478.FieldValue := fieldValue479;
{ .AddChildren }
Transform477.AddChildren([ProtoInstance478]);
{ .AddChildren }
Group323.AddChildren([Transform477]);
Transform480 := TTransformNode.Create;
ProtoInstance481 := TProtoInstanceNode.Create;
ProtoInstance481.NameField := 'Carbon';
fieldValue482 := TfieldValueNode.Create;
fieldValue482.NameField := 'position';
fieldValue482.Value := '10.4797 -3.3446 0';
{ .AddFieldValue }
ProtoInstance481.FieldValue := fieldValue482;
{ .AddChildren }
Transform480.AddChildren([ProtoInstance481]);
{ .AddChildren }
Group323.AddChildren([Transform480]);
Transform483 := TTransformNode.Create;
ProtoInstance484 := TProtoInstanceNode.Create;
ProtoInstance484.NameField := 'Carbon';
fieldValue485 := TfieldValueNode.Create;
fieldValue485.NameField := 'position';
fieldValue485.Value := '9.9335 -1.0591 0';
{ .AddFieldValue }
ProtoInstance484.FieldValue := fieldValue485;
{ .AddChildren }
Transform483.AddChildren([ProtoInstance484]);
{ .AddChildren }
Group323.AddChildren([Transform483]);
Transform486 := TTransformNode.Create;
ProtoInstance487 := TProtoInstanceNode.Create;
ProtoInstance487.NameField := 'Nitrogen';
fieldValue488 := TfieldValueNode.Create;
fieldValue488.NameField := 'position';
fieldValue488.Value := '10.1787 0.4682 0';
{ .AddFieldValue }
ProtoInstance487.FieldValue := fieldValue488;
{ .AddChildren }
Transform486.AddChildren([ProtoInstance487]);
{ .AddChildren }
Group323.AddChildren([Transform486]);
Transform489 := TTransformNode.Create;
ProtoInstance490 := TProtoInstanceNode.Create;
ProtoInstance490.NameField := 'Carbon';
fieldValue491 := TfieldValueNode.Create;
fieldValue491.NameField := 'position';
fieldValue491.Value := '11.4274 2.4862 0';
{ .AddFieldValue }
ProtoInstance490.FieldValue := fieldValue491;
{ .AddChildren }
Transform489.AddChildren([ProtoInstance490]);
{ .AddChildren }
Group323.AddChildren([Transform489]);
Transform492 := TTransformNode.Create;
ProtoInstance493 := TProtoInstanceNode.Create;
ProtoInstance493.NameField := 'Nitrogen';
fieldValue494 := TfieldValueNode.Create;
fieldValue494.NameField := 'position';
fieldValue494.Value := '10.7585 8.774 0';
{ .AddFieldValue }
ProtoInstance493.FieldValue := fieldValue494;
{ .AddChildren }
Transform492.AddChildren([ProtoInstance493]);
{ .AddChildren }
Group323.AddChildren([Transform492]);
Transform495 := TTransformNode.Create;
ProtoInstance496 := TProtoInstanceNode.Create;
ProtoInstance496.NameField := 'Oxygen';
fieldValue497 := TfieldValueNode.Create;
fieldValue497.NameField := 'position';
fieldValue497.Value := '8.2166 9.6324 0';
{ .AddFieldValue }
ProtoInstance496.FieldValue := fieldValue497;
{ .AddChildren }
Transform495.AddChildren([ProtoInstance496]);
{ .AddChildren }
Group323.AddChildren([Transform495]);
Transform498 := TTransformNode.Create;
ProtoInstance499 := TProtoInstanceNode.Create;
ProtoInstance499.NameField := 'Carbon';
fieldValue500 := TfieldValueNode.Create;
fieldValue500.NameField := 'position';
fieldValue500.Value := '10.3237 -4.8943 0';
{ .AddFieldValue }
ProtoInstance499.FieldValue := fieldValue500;
{ .AddChildren }
Transform498.AddChildren([ProtoInstance499]);
{ .AddChildren }
Group323.AddChildren([Transform498]);
Transform501 := TTransformNode.Create;
ProtoInstance502 := TProtoInstanceNode.Create;
ProtoInstance502.NameField := 'Oxygen';
fieldValue503 := TfieldValueNode.Create;
fieldValue503.NameField := 'position';
fieldValue503.Value := '11.4274 -1.5274 0';
{ .AddFieldValue }
ProtoInstance502.FieldValue := fieldValue503;
{ .AddChildren }
Transform501.AddChildren([ProtoInstance502]);
{ .AddChildren }
Group323.AddChildren([Transform501]);
Transform504 := TTransformNode.Create;
ProtoInstance505 := TProtoInstanceNode.Create;
ProtoInstance505.NameField := 'Carbon';
fieldValue506 := TfieldValueNode.Create;
fieldValue506.NameField := 'position';
fieldValue506.Value := '12.5534 1.427 0';
{ .AddFieldValue }
ProtoInstance505.FieldValue := fieldValue506;
{ .AddChildren }
Transform504.AddChildren([ProtoInstance505]);
{ .AddChildren }
Group323.AddChildren([Transform504]);
Transform507 := TTransformNode.Create;
ProtoInstance508 := TProtoInstanceNode.Create;
ProtoInstance508.NameField := 'Carbon';
fieldValue509 := TfieldValueNode.Create;
fieldValue509.NameField := 'position';
fieldValue509.Value := '11.7507 4.0024 0';
{ .AddFieldValue }
ProtoInstance508.FieldValue := fieldValue509;
{ .AddChildren }
Transform507.AddChildren([ProtoInstance508]);
{ .AddChildren }
Group323.AddChildren([Transform507]);
Transform510 := TTransformNode.Create;
ProtoInstance511 := TProtoInstanceNode.Create;
ProtoInstance511.NameField := 'Carbon';
fieldValue512 := TfieldValueNode.Create;
fieldValue512.NameField := 'position';
fieldValue512.Value := '8.8855 -5.5297 0';
{ .AddFieldValue }
ProtoInstance511.FieldValue := fieldValue512;
{ .AddChildren }
Transform510.AddChildren([ProtoInstance511]);
{ .AddChildren }
Group323.AddChildren([Transform510]);
Transform513 := TTransformNode.Create;
ProtoInstance514 := TProtoInstanceNode.Create;
ProtoInstance514.NameField := 'Carbon';
fieldValue515 := TfieldValueNode.Create;
fieldValue515.NameField := 'position';
fieldValue515.Value := '11.5612 -5.8085 0';
{ .AddFieldValue }
ProtoInstance514.FieldValue := fieldValue515;
{ .AddChildren }
Transform513.AddChildren([ProtoInstance514]);
{ .AddChildren }
Group323.AddChildren([Transform513]);
Transform516 := TTransformNode.Create;
ProtoInstance517 := TProtoInstanceNode.Create;
ProtoInstance517.NameField := 'Carbon';
fieldValue518 := TfieldValueNode.Create;
fieldValue518.NameField := 'position';
fieldValue518.Value := '14.0473 1.9064 0';
{ .AddFieldValue }
ProtoInstance517.FieldValue := fieldValue518;
{ .AddChildren }
Transform516.AddChildren([ProtoInstance517]);
{ .AddChildren }
Group323.AddChildren([Transform516]);
Transform519 := TTransformNode.Create;
ProtoInstance520 := TProtoInstanceNode.Create;
ProtoInstance520.NameField := 'Carbon';
fieldValue521 := TfieldValueNode.Create;
fieldValue521.NameField := 'position';
fieldValue521.Value := '8.7183 -7.0794 0';
{ .AddFieldValue }
ProtoInstance520.FieldValue := fieldValue521;
{ .AddChildren }
Transform519.AddChildren([ProtoInstance520]);
{ .AddChildren }
Group323.AddChildren([Transform519]);
Transform522 := TTransformNode.Create;
ProtoInstance523 := TProtoInstanceNode.Create;
ProtoInstance523.NameField := 'Carbon';
fieldValue524 := TfieldValueNode.Create;
fieldValue524.NameField := 'position';
fieldValue524.Value := '11.3939 -7.347 0';
{ .AddFieldValue }
ProtoInstance523.FieldValue := fieldValue524;
{ .AddChildren }
Transform522.AddChildren([ProtoInstance523]);
{ .AddChildren }
Group323.AddChildren([Transform522]);
Transform525 := TTransformNode.Create;
ProtoInstance526 := TProtoInstanceNode.Create;
ProtoInstance526.NameField := 'Carbon';
fieldValue527 := TfieldValueNode.Create;
fieldValue527.NameField := 'position';
fieldValue527.Value := '9.9892 -7.9824 0';
{ .AddFieldValue }
ProtoInstance526.FieldValue := fieldValue527;
{ .AddChildren }
Transform525.AddChildren([ProtoInstance526]);
{ .AddChildren }
Group323.AddChildren([Transform525]);
Transform528 := TTransformNode.Create;
ProtoInstance529 := TProtoInstanceNode.Create;
ProtoInstance529.NameField := 'Oxygen';
fieldValue530 := TfieldValueNode.Create;
fieldValue530.NameField := 'position';
fieldValue530.Value := '9.7885 -9.5321 0';
{ .AddFieldValue }
ProtoInstance529.FieldValue := fieldValue530;
{ .AddChildren }
Transform528.AddChildren([ProtoInstance529]);
{ .AddChildren }
Group323.AddChildren([Transform528]);
{ .AddChildren }
Group19.AddChildren([Group323]);
Group531 := TGroupNode.Create;
ProtoInstance532 := TProtoInstanceNode.Create;
ProtoInstance532.NameField := 'line';
fieldValue533 := TfieldValueNode.Create;
fieldValue533.NameField := 'bond_set';
fieldValue533.Value := '-2.0514 1.8507 0 -3.601 1.9845 0';
{ .AddFieldValue }
ProtoInstance532.FieldValue := fieldValue533;
{ .AddChildren }
Group531.AddChildren([ProtoInstance532]);
ProtoInstance534 := TProtoInstanceNode.Create;
ProtoInstance534.NameField := 'line';
fieldValue535 := TfieldValueNode.Create;
fieldValue535.NameField := 'bond_set';
fieldValue535.Value := '-2.0514 1.8507 0 -1.2821 0.4905 0';
{ .AddFieldValue }
ProtoInstance534.FieldValue := fieldValue535;
{ .AddChildren }
Group531.AddChildren([ProtoInstance534]);
ProtoInstance536 := TProtoInstanceNode.Create;
ProtoInstance536.NameField := 'line';
fieldValue537 := TfieldValueNode.Create;
fieldValue537.NameField := 'bond_set';
fieldValue537.Value := '-2.0514 1.8507 0 -1.4159 3.2554 0';
{ .AddFieldValue }
ProtoInstance536.FieldValue := fieldValue537;
{ .AddChildren }
Group531.AddChildren([ProtoInstance536]);
ProtoInstance538 := TProtoInstanceNode.Create;
ProtoInstance538.NameField := 'line';
fieldValue539 := TfieldValueNode.Create;
fieldValue539.NameField := 'bond_set';
fieldValue539.Value := '-3.601 1.9845 0 -4.649 0.8473 0';
{ .AddFieldValue }
ProtoInstance538.FieldValue := fieldValue539;
{ .AddChildren }
Group531.AddChildren([ProtoInstance538]);
ProtoInstance540 := TProtoInstanceNode.Create;
ProtoInstance540.NameField := 'line';
fieldValue541 := TfieldValueNode.Create;
fieldValue541.NameField := 'bond_set';
fieldValue541.Value := '-3.601 1.9845 0 -3.9355 3.5341 0';
{ .AddFieldValue }
ProtoInstance540.FieldValue := fieldValue541;
{ .AddChildren }
Group531.AddChildren([ProtoInstance540]);
ProtoInstance542 := TProtoInstanceNode.Create;
ProtoInstance542.NameField := 'line';
fieldValue543 := TfieldValueNode.Create;
fieldValue543.NameField := 'bond_set';
fieldValue543.Value := '-1.2821 0.4905 0 0.2341 0.4905 0';
{ .AddFieldValue }
ProtoInstance542.FieldValue := fieldValue543;
{ .AddChildren }
Group531.AddChildren([ProtoInstance542]);
ProtoInstance544 := TProtoInstanceNode.Create;
ProtoInstance544.NameField := 'line';
fieldValue545 := TfieldValueNode.Create;
fieldValue545.NameField := 'bond_set';
fieldValue545.Value := '-1.3021 0.4905 0 -2.0714 -0.8362 0';
{ .AddFieldValue }
ProtoInstance544.FieldValue := fieldValue545;
{ .AddChildren }
Group531.AddChildren([ProtoInstance544]);
ProtoInstance546 := TProtoInstanceNode.Create;
ProtoInstance546.NameField := 'line';
fieldValue547 := TfieldValueNode.Create;
fieldValue547.NameField := 'bond_set';
fieldValue547.Value := '-1.2621 0.4905 0 -2.0314 -0.8362 0';
{ .AddFieldValue }
ProtoInstance546.FieldValue := fieldValue547;
{ .AddChildren }
Group531.AddChildren([ProtoInstance546]);
ProtoInstance548 := TProtoInstanceNode.Create;
ProtoInstance548.NameField := 'line';
fieldValue549 := TfieldValueNode.Create;
fieldValue549.NameField := 'bond_set';
fieldValue549.Value := '-1.4159 3.2554 0 -2.5753 4.3034 0';
{ .AddFieldValue }
ProtoInstance548.FieldValue := fieldValue549;
{ .AddChildren }
Group531.AddChildren([ProtoInstance548]);
ProtoInstance550 := TProtoInstanceNode.Create;
ProtoInstance550.NameField := 'line';
fieldValue551 := TfieldValueNode.Create;
fieldValue551.NameField := 'bond_set';
fieldValue551.Value := '-4.649 0.8473 0 -6.1764 1.1595 0';
{ .AddFieldValue }
ProtoInstance550.FieldValue := fieldValue551;
{ .AddChildren }
Group531.AddChildren([ProtoInstance550]);
ProtoInstance552 := TProtoInstanceNode.Create;
ProtoInstance552.NameField := 'line';
fieldValue553 := TfieldValueNode.Create;
fieldValue553.NameField := 'bond_set';
fieldValue553.Value := '-4.669 0.8473 0 -4.1785 -0.6132 0';
{ .AddFieldValue }
ProtoInstance552.FieldValue := fieldValue553;
{ .AddChildren }
Group531.AddChildren([ProtoInstance552]);
ProtoInstance554 := TProtoInstanceNode.Create;
ProtoInstance554.NameField := 'line';
fieldValue555 := TfieldValueNode.Create;
fieldValue555.NameField := 'bond_set';
fieldValue555.Value := '-4.6290000000000004 0.8473 0 -4.1385000000000005 -0.6132 0';
{ .AddFieldValue }
ProtoInstance554.FieldValue := fieldValue555;
{ .AddChildren }
Group531.AddChildren([ProtoInstance554]);
ProtoInstance556 := TProtoInstanceNode.Create;
ProtoInstance556.NameField := 'line';
fieldValue557 := TfieldValueNode.Create;
fieldValue557.NameField := 'bond_set';
fieldValue557.Value := '0.2341 0.4905 0 0.4905 2.0402 0';
{ .AddFieldValue }
ProtoInstance556.FieldValue := fieldValue557;
{ .AddChildren }
Group531.AddChildren([ProtoInstance556]);
ProtoInstance558 := TProtoInstanceNode.Create;
ProtoInstance558.NameField := 'line';
fieldValue559 := TfieldValueNode.Create;
fieldValue559.NameField := 'bond_set';
fieldValue559.Value := '0.2341 0.4905 0 0.4905 -1.0257 0';
{ .AddFieldValue }
ProtoInstance558.FieldValue := fieldValue559;
{ .AddChildren }
Group531.AddChildren([ProtoInstance558]);
ProtoInstance560 := TProtoInstanceNode.Create;
ProtoInstance560.NameField := 'line';
fieldValue561 := TfieldValueNode.Create;
fieldValue561.NameField := 'bond_set';
fieldValue561.Value := '-6.1764 1.1595 0 -7.2243 0.0223 0';
{ .AddFieldValue }
ProtoInstance560.FieldValue := fieldValue561;
{ .AddChildren }
Group531.AddChildren([ProtoInstance560]);
ProtoInstance562 := TProtoInstanceNode.Create;
ProtoInstance562.NameField := 'line';
fieldValue563 := TfieldValueNode.Create;
fieldValue563.NameField := 'bond_set';
fieldValue563.Value := '0.4905 2.0402 0 1.2041 3.3892 0';
{ .AddFieldValue }
ProtoInstance562.FieldValue := fieldValue563;
{ .AddChildren }
Group531.AddChildren([ProtoInstance562]);
ProtoInstance564 := TProtoInstanceNode.Create;
ProtoInstance564.NameField := 'line';
fieldValue565 := TfieldValueNode.Create;
fieldValue565.NameField := 'bond_set';
fieldValue565.Value := '0.4905 -1.0257 0 1.1706 -2.4081 0';
{ .AddFieldValue }
ProtoInstance564.FieldValue := fieldValue565;
{ .AddChildren }
Group531.AddChildren([ProtoInstance564]);
ProtoInstance566 := TProtoInstanceNode.Create;
ProtoInstance566.NameField := 'line';
fieldValue567 := TfieldValueNode.Create;
fieldValue567.NameField := 'bond_set';
fieldValue567.Value := '-7.2243 0.0223 0 -8.7071 0.3568 0';
{ .AddFieldValue }
ProtoInstance566.FieldValue := fieldValue567;
{ .AddChildren }
Group531.AddChildren([ProtoInstance566]);
ProtoInstance568 := TProtoInstanceNode.Create;
ProtoInstance568.NameField := 'line';
fieldValue569 := TfieldValueNode.Create;
fieldValue569.NameField := 'bond_set';
fieldValue569.Value := '-7.2243 0.0223 0 -6.7226 -1.4382 0';
{ .AddFieldValue }
ProtoInstance568.FieldValue := fieldValue569;
{ .AddChildren }
Group531.AddChildren([ProtoInstance568]);
ProtoInstance570 := TProtoInstanceNode.Create;
ProtoInstance570.NameField := 'line';
fieldValue571 := TfieldValueNode.Create;
fieldValue571.NameField := 'bond_set';
fieldValue571.Value := '1.2041 3.3892 0 2.3078 4.4929 0';
{ .AddFieldValue }
ProtoInstance570.FieldValue := fieldValue571;
{ .AddChildren }
Group531.AddChildren([ProtoInstance570]);
ProtoInstance572 := TProtoInstanceNode.Create;
ProtoInstance572.NameField := 'line';
fieldValue573 := TfieldValueNode.Create;
fieldValue573.NameField := 'bond_set';
fieldValue573.Value := '1.1841 3.3892 0 -0.0646 4.3368 0';
{ .AddFieldValue }
ProtoInstance572.FieldValue := fieldValue573;
{ .AddChildren }
Group531.AddChildren([ProtoInstance572]);
ProtoInstance574 := TProtoInstanceNode.Create;
ProtoInstance574.NameField := 'line';
fieldValue575 := TfieldValueNode.Create;
fieldValue575.NameField := 'bond_set';
fieldValue575.Value := '1.2241 3.3892 0 -0.0246 4.3368 0';
{ .AddFieldValue }
ProtoInstance574.FieldValue := fieldValue575;
{ .AddChildren }
Group531.AddChildren([ProtoInstance574]);
ProtoInstance576 := TProtoInstanceNode.Create;
ProtoInstance576.NameField := 'line';
fieldValue577 := TfieldValueNode.Create;
fieldValue577.NameField := 'bond_set';
fieldValue577.Value := '1.1706 -2.4081 0 2.2855 -3.5118 0';
{ .AddFieldValue }
ProtoInstance576.FieldValue := fieldValue577;
{ .AddChildren }
Group531.AddChildren([ProtoInstance576]);
ProtoInstance578 := TProtoInstanceNode.Create;
ProtoInstance578.NameField := 'line';
fieldValue579 := TfieldValueNode.Create;
fieldValue579.NameField := 'bond_set';
fieldValue579.Value := '-8.7071 0.3568 0 -9.7662 -0.7804 0';
{ .AddFieldValue }
ProtoInstance578.FieldValue := fieldValue579;
{ .AddChildren }
Group531.AddChildren([ProtoInstance578]);
ProtoInstance580 := TProtoInstanceNode.Create;
ProtoInstance580.NameField := 'line';
fieldValue581 := TfieldValueNode.Create;
fieldValue581.NameField := 'bond_set';
fieldValue581.Value := '-8.7271 0.3568 0 -9.2288 1.8507 0';
{ .AddFieldValue }
ProtoInstance580.FieldValue := fieldValue581;
{ .AddChildren }
Group531.AddChildren([ProtoInstance580]);
ProtoInstance582 := TProtoInstanceNode.Create;
ProtoInstance582.NameField := 'line';
fieldValue583 := TfieldValueNode.Create;
fieldValue583.NameField := 'bond_set';
fieldValue583.Value := '-8.687100000000001 0.3568 0 -9.1888 1.8507 0';
{ .AddFieldValue }
ProtoInstance582.FieldValue := fieldValue583;
{ .AddChildren }
Group531.AddChildren([ProtoInstance582]);
ProtoInstance584 := TProtoInstanceNode.Create;
ProtoInstance584.NameField := 'line';
fieldValue585 := TfieldValueNode.Create;
fieldValue585.NameField := 'bond_set';
fieldValue585.Value := '-6.7226 -1.4382 0 -7.7483 -2.5753 0';
{ .AddFieldValue }
ProtoInstance584.FieldValue := fieldValue585;
{ .AddChildren }
Group531.AddChildren([ProtoInstance584]);
ProtoInstance586 := TProtoInstanceNode.Create;
ProtoInstance586.NameField := 'line';
fieldValue587 := TfieldValueNode.Create;
fieldValue587.NameField := 'bond_set';
fieldValue587.Value := '2.3078 4.4929 0 3.6902 5.1841 0';
{ .AddFieldValue }
ProtoInstance586.FieldValue := fieldValue587;
{ .AddChildren }
Group531.AddChildren([ProtoInstance586]);
ProtoInstance588 := TProtoInstanceNode.Create;
ProtoInstance588.NameField := 'line';
fieldValue589 := TfieldValueNode.Create;
fieldValue589.NameField := 'bond_set';
fieldValue589.Value := '2.3078 4.4929 0 1.3936 5.7416 0';
{ .AddFieldValue }
ProtoInstance588.FieldValue := fieldValue589;
{ .AddChildren }
Group531.AddChildren([ProtoInstance588]);
ProtoInstance590 := TProtoInstanceNode.Create;
ProtoInstance590.NameField := 'line';
fieldValue591 := TfieldValueNode.Create;
fieldValue591.NameField := 'bond_set';
fieldValue591.Value := '2.2855 -3.5118 0 3.6568 -4.2253 0';
{ .AddFieldValue }
ProtoInstance590.FieldValue := fieldValue591;
{ .AddChildren }
Group531.AddChildren([ProtoInstance590]);
ProtoInstance592 := TProtoInstanceNode.Create;
ProtoInstance592.NameField := 'line';
fieldValue593 := TfieldValueNode.Create;
fieldValue593.NameField := 'bond_set';
fieldValue593.Value := '-9.7662 -0.7804 0 -11.2825 -0.4459 0';
{ .AddFieldValue }
ProtoInstance592.FieldValue := fieldValue593;
{ .AddChildren }
Group531.AddChildren([ProtoInstance592]);
ProtoInstance594 := TProtoInstanceNode.Create;
ProtoInstance594.NameField := 'line';
fieldValue595 := TfieldValueNode.Create;
fieldValue595.NameField := 'bond_set';
fieldValue595.Value := '-7.7483 -2.5753 0 -7.2243 -4.0693 0';
{ .AddFieldValue }
ProtoInstance594.FieldValue := fieldValue595;
{ .AddChildren }
Group531.AddChildren([ProtoInstance594]);
ProtoInstance596 := TProtoInstanceNode.Create;
ProtoInstance596.NameField := 'line';
fieldValue597 := TfieldValueNode.Create;
fieldValue597.NameField := 'bond_set';
fieldValue597.Value := '-7.7483 -2.5753 0 -8.7963 -2.4081 0';
{ .AddFieldValue }
ProtoInstance596.FieldValue := fieldValue597;
{ .AddChildren }
Group531.AddChildren([ProtoInstance596]);
ProtoInstance598 := TProtoInstanceNode.Create;
ProtoInstance598.NameField := 'line';
fieldValue599 := TfieldValueNode.Create;
fieldValue599.NameField := 'bond_set';
fieldValue599.Value := '3.6902 5.1841 0 5.2064 5.4405 0';
{ .AddFieldValue }
ProtoInstance598.FieldValue := fieldValue599;
{ .AddChildren }
Group531.AddChildren([ProtoInstance598]);
ProtoInstance600 := TProtoInstanceNode.Create;
ProtoInstance600.NameField := 'line';
fieldValue601 := TfieldValueNode.Create;
fieldValue601.NameField := 'bond_set';
fieldValue601.Value := '1.3936 5.7416 0 2.0291 7.1797 0';
{ .AddFieldValue }
ProtoInstance600.FieldValue := fieldValue601;
{ .AddChildren }
Group531.AddChildren([ProtoInstance600]);
ProtoInstance602 := TProtoInstanceNode.Create;
ProtoInstance602.NameField := 'line';
fieldValue603 := TfieldValueNode.Create;
fieldValue603.NameField := 'bond_set';
fieldValue603.Value := '3.6568 -4.2253 0 5.1841 -4.4818 0';
{ .AddFieldValue }
ProtoInstance602.FieldValue := fieldValue603;
{ .AddChildren }
Group531.AddChildren([ProtoInstance602]);
ProtoInstance604 := TProtoInstanceNode.Create;
ProtoInstance604.NameField := 'line';
fieldValue605 := TfieldValueNode.Create;
fieldValue605.NameField := 'bond_set';
fieldValue605.Value := '-11.2825 -0.4459 0 -12.3304 -1.6054 0';
{ .AddFieldValue }
ProtoInstance604.FieldValue := fieldValue605;
{ .AddChildren }
Group531.AddChildren([ProtoInstance604]);
ProtoInstance606 := TProtoInstanceNode.Create;
ProtoInstance606.NameField := 'line';
fieldValue607 := TfieldValueNode.Create;
fieldValue607.NameField := 'bond_set';
fieldValue607.Value := '5.2064 5.4405 0 6.7561 5.1841 0';
{ .AddFieldValue }
ProtoInstance606.FieldValue := fieldValue607;
{ .AddChildren }
Group531.AddChildren([ProtoInstance606]);
ProtoInstance608 := TProtoInstanceNode.Create;
ProtoInstance608.NameField := 'line';
fieldValue609 := TfieldValueNode.Create;
fieldValue609.NameField := 'bond_set';
fieldValue609.Value := '5.186400000000001 5.4405 0 5.2199 6.9791 0';
{ .AddFieldValue }
ProtoInstance608.FieldValue := fieldValue609;
{ .AddChildren }
Group531.AddChildren([ProtoInstance608]);
ProtoInstance610 := TProtoInstanceNode.Create;
ProtoInstance610.NameField := 'line';
fieldValue611 := TfieldValueNode.Create;
fieldValue611.NameField := 'bond_set';
fieldValue611.Value := '5.2264 5.4405 0 5.259899999999999 6.9791 0';
{ .AddFieldValue }
ProtoInstance610.FieldValue := fieldValue611;
{ .AddChildren }
Group531.AddChildren([ProtoInstance610]);
ProtoInstance612 := TProtoInstanceNode.Create;
ProtoInstance612.NameField := 'line';
fieldValue613 := TfieldValueNode.Create;
fieldValue613.NameField := 'bond_set';
fieldValue613.Value := '2.0291 7.1797 0 1.126 8.4507 0';
{ .AddFieldValue }
ProtoInstance612.FieldValue := fieldValue613;
{ .AddChildren }
Group531.AddChildren([ProtoInstance612]);
ProtoInstance614 := TProtoInstanceNode.Create;
ProtoInstance614.NameField := 'line';
fieldValue615 := TfieldValueNode.Create;
fieldValue615.NameField := 'bond_set';
fieldValue615.Value := '2.0091 7.1797 0 3.5587 7.3135 0';
{ .AddFieldValue }
ProtoInstance614.FieldValue := fieldValue615;
{ .AddChildren }
Group531.AddChildren([ProtoInstance614]);
ProtoInstance616 := TProtoInstanceNode.Create;
ProtoInstance616.NameField := 'line';
fieldValue617 := TfieldValueNode.Create;
fieldValue617.NameField := 'bond_set';
fieldValue617.Value := '2.0491 7.1797 0 3.5987 7.3135 0';
{ .AddFieldValue }
ProtoInstance616.FieldValue := fieldValue617;
{ .AddChildren }
Group531.AddChildren([ProtoInstance616]);
ProtoInstance618 := TProtoInstanceNode.Create;
ProtoInstance618.NameField := 'line';
fieldValue619 := TfieldValueNode.Create;
fieldValue619.NameField := 'bond_set';
fieldValue619.Value := '5.1841 -4.4818 0 6.7226 -4.2253 0';
{ .AddFieldValue }
ProtoInstance618.FieldValue := fieldValue619;
{ .AddChildren }
Group531.AddChildren([ProtoInstance618]);
ProtoInstance620 := TProtoInstanceNode.Create;
ProtoInstance620.NameField := 'line';
fieldValue621 := TfieldValueNode.Create;
fieldValue621.NameField := 'bond_set';
fieldValue621.Value := '5.1841 -4.4818 0 5.1841 -6.0203 0';
{ .AddFieldValue }
ProtoInstance620.FieldValue := fieldValue621;
{ .AddChildren }
Group531.AddChildren([ProtoInstance620]);
ProtoInstance622 := TProtoInstanceNode.Create;
ProtoInstance622.NameField := 'line';
fieldValue623 := TfieldValueNode.Create;
fieldValue623.NameField := 'bond_set';
fieldValue623.Value := '-12.3304 -1.6054 0 -13.8466 -1.2709 0';
{ .AddFieldValue }
ProtoInstance622.FieldValue := fieldValue623;
{ .AddChildren }
Group531.AddChildren([ProtoInstance622]);
ProtoInstance624 := TProtoInstanceNode.Create;
ProtoInstance624.NameField := 'line';
fieldValue625 := TfieldValueNode.Create;
fieldValue625.NameField := 'bond_set';
fieldValue625.Value := '-12.350399999999999 -1.6054 0 -11.8822 -3.0659 0';
{ .AddFieldValue }
ProtoInstance624.FieldValue := fieldValue625;
{ .AddChildren }
Group531.AddChildren([ProtoInstance624]);
ProtoInstance626 := TProtoInstanceNode.Create;
ProtoInstance626.NameField := 'line';
fieldValue627 := TfieldValueNode.Create;
fieldValue627.NameField := 'bond_set';
fieldValue627.Value := '-12.3104 -1.6054 0 -11.8422 -3.0659 0';
{ .AddFieldValue }
ProtoInstance626.FieldValue := fieldValue627;
{ .AddChildren }
Group531.AddChildren([ProtoInstance626]);
ProtoInstance628 := TProtoInstanceNode.Create;
ProtoInstance628.NameField := 'line';
fieldValue629 := TfieldValueNode.Create;
fieldValue629.NameField := 'bond_set';
fieldValue629.Value := '6.7561 5.1841 0 8.1385 4.4706 0';
{ .AddFieldValue }
ProtoInstance628.FieldValue := fieldValue629;
{ .AddChildren }
Group531.AddChildren([ProtoInstance628]);
ProtoInstance630 := TProtoInstanceNode.Create;
ProtoInstance630.NameField := 'line';
fieldValue631 := TfieldValueNode.Create;
fieldValue631.NameField := 'bond_set';
fieldValue631.Value := '6.7561 5.1841 0 7.2243 6.6781 0';
{ .AddFieldValue }
ProtoInstance630.FieldValue := fieldValue631;
{ .AddChildren }
Group531.AddChildren([ProtoInstance630]);
ProtoInstance632 := TProtoInstanceNode.Create;
ProtoInstance632.NameField := 'line';
fieldValue633 := TfieldValueNode.Create;
fieldValue633.NameField := 'bond_set';
fieldValue633.Value := '6.7226 -4.2253 0 8.1051 -3.5341 0';
{ .AddFieldValue }
ProtoInstance632.FieldValue := fieldValue633;
{ .AddChildren }
Group531.AddChildren([ProtoInstance632]);
ProtoInstance634 := TProtoInstanceNode.Create;
ProtoInstance634.NameField := 'line';
fieldValue635 := TfieldValueNode.Create;
fieldValue635.NameField := 'bond_set';
fieldValue635.Value := '6.7026 -4.2253 0 7.182 -5.7193 0';
{ .AddFieldValue }
ProtoInstance634.FieldValue := fieldValue635;
{ .AddChildren }
Group531.AddChildren([ProtoInstance634]);
ProtoInstance636 := TProtoInstanceNode.Create;
ProtoInstance636.NameField := 'line';
fieldValue637 := TfieldValueNode.Create;
fieldValue637.NameField := 'bond_set';
fieldValue637.Value := '6.7425999999999995 -4.2253 0 7.2219999999999995 -5.7193 0';
{ .AddFieldValue }
ProtoInstance636.FieldValue := fieldValue637;
{ .AddChildren }
Group531.AddChildren([ProtoInstance636]);
ProtoInstance638 := TProtoInstanceNode.Create;
ProtoInstance638.NameField := 'line';
fieldValue639 := TfieldValueNode.Create;
fieldValue639.NameField := 'bond_set';
fieldValue639.Value := '8.1385 4.4706 0 9.2422 3.3669 0';
{ .AddFieldValue }
ProtoInstance638.FieldValue := fieldValue639;
{ .AddChildren }
Group531.AddChildren([ProtoInstance638]);
ProtoInstance640 := TProtoInstanceNode.Create;
ProtoInstance640.NameField := 'line';
fieldValue641 := TfieldValueNode.Create;
fieldValue641.NameField := 'bond_set';
fieldValue641.Value := '7.2243 6.6781 0 8.7406 6.9791 0';
{ .AddFieldValue }
ProtoInstance640.FieldValue := fieldValue641;
{ .AddChildren }
Group531.AddChildren([ProtoInstance640]);
ProtoInstance642 := TProtoInstanceNode.Create;
ProtoInstance642.NameField := 'line';
fieldValue643 := TfieldValueNode.Create;
fieldValue643.NameField := 'bond_set';
fieldValue643.Value := '8.1051 -3.5341 0 9.2088 -2.4304 0';
{ .AddFieldValue }
ProtoInstance642.FieldValue := fieldValue643;
{ .AddChildren }
Group531.AddChildren([ProtoInstance642]);
ProtoInstance644 := TProtoInstanceNode.Create;
ProtoInstance644.NameField := 'line';
fieldValue645 := TfieldValueNode.Create;
fieldValue645.NameField := 'bond_set';
fieldValue645.Value := '9.2422 3.3669 0 9.9335 1.9845 0';
{ .AddFieldValue }
ProtoInstance644.FieldValue := fieldValue645;
{ .AddChildren }
Group531.AddChildren([ProtoInstance644]);
ProtoInstance646 := TProtoInstanceNode.Create;
ProtoInstance646.NameField := 'line';
fieldValue647 := TfieldValueNode.Create;
fieldValue647.NameField := 'bond_set';
fieldValue647.Value := '9.2222 3.3669 0 10.4597 4.3034 0';
{ .AddFieldValue }
ProtoInstance646.FieldValue := fieldValue647;
{ .AddChildren }
Group531.AddChildren([ProtoInstance646]);
ProtoInstance648 := TProtoInstanceNode.Create;
ProtoInstance648.NameField := 'line';
fieldValue649 := TfieldValueNode.Create;
fieldValue649.NameField := 'bond_set';
fieldValue649.Value := '9.2622 3.3669 0 10.499699999999999 4.3034 0';
{ .AddFieldValue }
ProtoInstance648.FieldValue := fieldValue649;
{ .AddChildren }
Group531.AddChildren([ProtoInstance648]);
ProtoInstance650 := TProtoInstanceNode.Create;
ProtoInstance650.NameField := 'line';
fieldValue651 := TfieldValueNode.Create;
fieldValue651.NameField := 'bond_set';
fieldValue651.Value := '8.7406 6.9791 0 9.2422 8.4507 0';
{ .AddFieldValue }
ProtoInstance650.FieldValue := fieldValue651;
{ .AddChildren }
Group531.AddChildren([ProtoInstance650]);
ProtoInstance652 := TProtoInstanceNode.Create;
ProtoInstance652.NameField := 'line';
fieldValue653 := TfieldValueNode.Create;
fieldValue653.NameField := 'bond_set';
fieldValue653.Value := '9.2088 -2.4304 0 10.4797 -3.3446 0';
{ .AddFieldValue }
ProtoInstance652.FieldValue := fieldValue653;
{ .AddChildren }
Group531.AddChildren([ProtoInstance652]);
ProtoInstance654 := TProtoInstanceNode.Create;
ProtoInstance654.NameField := 'line';
fieldValue655 := TfieldValueNode.Create;
fieldValue655.NameField := 'bond_set';
fieldValue655.Value := '9.2088 -2.4304 0 9.9335 -1.0591 0';
{ .AddFieldValue }
ProtoInstance654.FieldValue := fieldValue655;
{ .AddChildren }
Group531.AddChildren([ProtoInstance654]);
ProtoInstance656 := TProtoInstanceNode.Create;
ProtoInstance656.NameField := 'line';
fieldValue657 := TfieldValueNode.Create;
fieldValue657.NameField := 'bond_set';
fieldValue657.Value := '9.9335 1.9845 0 10.1787 0.4682 0';
{ .AddFieldValue }
ProtoInstance656.FieldValue := fieldValue657;
{ .AddChildren }
Group531.AddChildren([ProtoInstance656]);
ProtoInstance658 := TProtoInstanceNode.Create;
ProtoInstance658.NameField := 'line';
fieldValue659 := TfieldValueNode.Create;
fieldValue659.NameField := 'bond_set';
fieldValue659.Value := '9.9335 1.9845 0 11.4274 2.4862 0';
{ .AddFieldValue }
ProtoInstance658.FieldValue := fieldValue659;
{ .AddChildren }
Group531.AddChildren([ProtoInstance658]);
ProtoInstance660 := TProtoInstanceNode.Create;
ProtoInstance660.NameField := 'line';
fieldValue661 := TfieldValueNode.Create;
fieldValue661.NameField := 'bond_set';
fieldValue661.Value := '9.2422 8.4507 0 10.7585 8.774 0';
{ .AddFieldValue }
ProtoInstance660.FieldValue := fieldValue661;
{ .AddChildren }
Group531.AddChildren([ProtoInstance660]);
ProtoInstance662 := TProtoInstanceNode.Create;
ProtoInstance662.NameField := 'line';
fieldValue663 := TfieldValueNode.Create;
fieldValue663.NameField := 'bond_set';
fieldValue663.Value := '9.2222 8.4507 0 8.1966 9.6324 0';
{ .AddFieldValue }
ProtoInstance662.FieldValue := fieldValue663;
{ .AddChildren }
Group531.AddChildren([ProtoInstance662]);
ProtoInstance664 := TProtoInstanceNode.Create;
ProtoInstance664.NameField := 'line';
fieldValue665 := TfieldValueNode.Create;
fieldValue665.NameField := 'bond_set';
fieldValue665.Value := '9.2622 8.4507 0 8.2366 9.6324 0';
{ .AddFieldValue }
ProtoInstance664.FieldValue := fieldValue665;
{ .AddChildren }
Group531.AddChildren([ProtoInstance664]);
ProtoInstance666 := TProtoInstanceNode.Create;
ProtoInstance666.NameField := 'line';
fieldValue667 := TfieldValueNode.Create;
fieldValue667.NameField := 'bond_set';
fieldValue667.Value := '10.4797 -3.3446 0 10.3237 -4.8943 0';
{ .AddFieldValue }
ProtoInstance666.FieldValue := fieldValue667;
{ .AddChildren }
Group531.AddChildren([ProtoInstance666]);
ProtoInstance668 := TProtoInstanceNode.Create;
ProtoInstance668.NameField := 'line';
fieldValue669 := TfieldValueNode.Create;
fieldValue669.NameField := 'bond_set';
fieldValue669.Value := '9.9135 -1.0591 0 11.4074 -1.5274 0';
{ .AddFieldValue }
ProtoInstance668.FieldValue := fieldValue669;
{ .AddChildren }
Group531.AddChildren([ProtoInstance668]);
ProtoInstance670 := TProtoInstanceNode.Create;
ProtoInstance670.NameField := 'line';
fieldValue671 := TfieldValueNode.Create;
fieldValue671.NameField := 'bond_set';
fieldValue671.Value := '9.9535 -1.0591 0 11.4474 -1.5274 0';
{ .AddFieldValue }
ProtoInstance670.FieldValue := fieldValue671;
{ .AddChildren }
Group531.AddChildren([ProtoInstance670]);
ProtoInstance672 := TProtoInstanceNode.Create;
ProtoInstance672.NameField := 'line';
fieldValue673 := TfieldValueNode.Create;
fieldValue673.NameField := 'bond_set';
fieldValue673.Value := '11.4274 2.4862 0 12.5534 1.427 0';
{ .AddFieldValue }
ProtoInstance672.FieldValue := fieldValue673;
{ .AddChildren }
Group531.AddChildren([ProtoInstance672]);
ProtoInstance674 := TProtoInstanceNode.Create;
ProtoInstance674.NameField := 'line';
fieldValue675 := TfieldValueNode.Create;
fieldValue675.NameField := 'bond_set';
fieldValue675.Value := '11.4274 2.4862 0 11.7507 4.0024 0';
{ .AddFieldValue }
ProtoInstance674.FieldValue := fieldValue675;
{ .AddChildren }
Group531.AddChildren([ProtoInstance674]);
ProtoInstance676 := TProtoInstanceNode.Create;
ProtoInstance676.NameField := 'line';
fieldValue677 := TfieldValueNode.Create;
fieldValue677.NameField := 'bond_set';
fieldValue677.Value := '10.3237 -4.8943 0 8.8855 -5.5297 0';
{ .AddFieldValue }
ProtoInstance676.FieldValue := fieldValue677;
{ .AddChildren }
Group531.AddChildren([ProtoInstance676]);
ProtoInstance678 := TProtoInstanceNode.Create;
ProtoInstance678.NameField := 'line';
fieldValue679 := TfieldValueNode.Create;
fieldValue679.NameField := 'bond_set';
fieldValue679.Value := '10.303700000000001 -4.8943 0 11.5412 -5.8085 0';
{ .AddFieldValue }
ProtoInstance678.FieldValue := fieldValue679;
{ .AddChildren }
Group531.AddChildren([ProtoInstance678]);
ProtoInstance680 := TProtoInstanceNode.Create;
ProtoInstance680.NameField := 'line';
fieldValue681 := TfieldValueNode.Create;
fieldValue681.NameField := 'bond_set';
fieldValue681.Value := '10.3437 -4.8943 0 11.581199999999999 -5.8085 0';
{ .AddFieldValue }
ProtoInstance680.FieldValue := fieldValue681;
{ .AddChildren }
Group531.AddChildren([ProtoInstance680]);
ProtoInstance682 := TProtoInstanceNode.Create;
ProtoInstance682.NameField := 'line';
fieldValue683 := TfieldValueNode.Create;
fieldValue683.NameField := 'bond_set';
fieldValue683.Value := '12.5534 1.427 0 14.0473 1.9064 0';
{ .AddFieldValue }
ProtoInstance682.FieldValue := fieldValue683;
{ .AddChildren }
Group531.AddChildren([ProtoInstance682]);
ProtoInstance684 := TProtoInstanceNode.Create;
ProtoInstance684.NameField := 'line';
fieldValue685 := TfieldValueNode.Create;
fieldValue685.NameField := 'bond_set';
fieldValue685.Value := '8.8655 -5.5297 0 8.6983 -7.0794 0';
{ .AddFieldValue }
ProtoInstance684.FieldValue := fieldValue685;
{ .AddChildren }
Group531.AddChildren([ProtoInstance684]);
ProtoInstance686 := TProtoInstanceNode.Create;
ProtoInstance686.NameField := 'line';
fieldValue687 := TfieldValueNode.Create;
fieldValue687.NameField := 'bond_set';
fieldValue687.Value := '8.9055 -5.5297 0 8.738299999999999 -7.0794 0';
{ .AddFieldValue }
ProtoInstance686.FieldValue := fieldValue687;
{ .AddChildren }
Group531.AddChildren([ProtoInstance686]);
ProtoInstance688 := TProtoInstanceNode.Create;
ProtoInstance688.NameField := 'line';
fieldValue689 := TfieldValueNode.Create;
fieldValue689.NameField := 'bond_set';
fieldValue689.Value := '11.5612 -5.8085 0 11.3939 -7.347 0';
{ .AddFieldValue }
ProtoInstance688.FieldValue := fieldValue689;
{ .AddChildren }
Group531.AddChildren([ProtoInstance688]);
ProtoInstance690 := TProtoInstanceNode.Create;
ProtoInstance690.NameField := 'line';
fieldValue691 := TfieldValueNode.Create;
fieldValue691.NameField := 'bond_set';
fieldValue691.Value := '8.7183 -7.0794 0 9.9892 -7.9824 0';
{ .AddFieldValue }
ProtoInstance690.FieldValue := fieldValue691;
{ .AddChildren }
Group531.AddChildren([ProtoInstance690]);
ProtoInstance692 := TProtoInstanceNode.Create;
ProtoInstance692.NameField := 'line';
fieldValue693 := TfieldValueNode.Create;
fieldValue693.NameField := 'bond_set';
fieldValue693.Value := '9.9892 -7.9824 0 9.7885 -9.5321 0';
{ .AddFieldValue }
ProtoInstance692.FieldValue := fieldValue693;
{ .AddChildren }
Group531.AddChildren([ProtoInstance692]);
ProtoInstance694 := TProtoInstanceNode.Create;
ProtoInstance694.NameField := 'line';
fieldValue695 := TfieldValueNode.Create;
fieldValue695.NameField := 'bond_set';
fieldValue695.Value := '-3.9355 3.5341 0 -2.5753 4.3034 0';
{ .AddFieldValue }
ProtoInstance694.FieldValue := fieldValue695;
{ .AddChildren }
Group531.AddChildren([ProtoInstance694]);
ProtoInstance696 := TProtoInstanceNode.Create;
ProtoInstance696.NameField := 'line';
fieldValue697 := TfieldValueNode.Create;
fieldValue697.NameField := 'bond_set';
fieldValue697.Value := '9.9335 -1.0591 0 10.1787 0.4682 0';
{ .AddFieldValue }
ProtoInstance696.FieldValue := fieldValue697;
{ .AddChildren }
Group531.AddChildren([ProtoInstance696]);
ProtoInstance698 := TProtoInstanceNode.Create;
ProtoInstance698.NameField := 'line';
fieldValue699 := TfieldValueNode.Create;
fieldValue699.NameField := 'bond_set';
fieldValue699.Value := '11.3739 -7.347 0 9.9692 -7.9824 0';
{ .AddFieldValue }
ProtoInstance698.FieldValue := fieldValue699;
{ .AddChildren }
Group531.AddChildren([ProtoInstance698]);
ProtoInstance700 := TProtoInstanceNode.Create;
ProtoInstance700.NameField := 'line';
fieldValue701 := TfieldValueNode.Create;
fieldValue701.NameField := 'bond_set';
fieldValue701.Value := '11.4139 -7.347 0 10.0092 -7.9824 0';
{ .AddFieldValue }
ProtoInstance700.FieldValue := fieldValue701;
{ .AddChildren }
Group531.AddChildren([ProtoInstance700]);
{ .AddChildren }
Group19.AddChildren([Group531]);
{ .AddGroup }
X3D0.AddChildren([Group19]);
Result := X3D0;
end;
