function Trebuchet: TX3DRootNode;
var
X3D0: TX3DRootNode;
Group17: TGroupNode;
WorldInfo18: TWorldInfoNode;
Background19: TBackgroundNode;
Sound20: TSoundNode;
AudioClip21: TAudioClipNode;
Shape22: TShapeNode;
Box23: TBoxNode;
Appearance24: TAppearanceNode;
ImageTexture25: TImageTextureNode;
Transform26: TTransformNode;
Shape27: TShapeNode;
Appearance28: TAppearanceNode;
Material29: TMaterialNode;
Text30: TTextNode;
FontStyle31: TFontStyleNode;
Transform32: TTransformNode;
Switch33: TSwitchNode;
Group34: TGroupNode;
Shape35: TShapeNode;
Appearance36: TAppearanceNode;
Text37: TTextNode;
Group38: TGroupNode;
Shape39: TShapeNode;
Appearance40: TAppearanceNode;
Text41: TTextNode;
Group42: TGroupNode;
Shape43: TShapeNode;
Appearance44: TAppearanceNode;
Text45: TTextNode;
Group46: TGroupNode;
Shape47: TShapeNode;
Appearance48: TAppearanceNode;
Text49: TTextNode;
TouchSensor50: TTouchSensorNode;
Transform51: TTransformNode;
Shape52: TShapeNode;
Box53: TBoxNode;
Appearance54: TAppearanceNode;
Material55: TMaterialNode;
Transform56: TTransformNode;
Transform57: TTransformNode;
Billboard58: TBillboardNode;
Shape59: TShapeNode;
Appearance60: TAppearanceNode;
Material61: TMaterialNode;
Text62: TTextNode;
FontStyle63: TFontStyleNode;
Transform64: TTransformNode;
Shape65: TShapeNode;
Box66: TBoxNode;
Appearance67: TAppearanceNode;
Material68: TMaterialNode;
Switch69: TSwitchNode;
Group70: TGroupNode;
Sound71: TSoundNode;
AudioClip72: TAudioClipNode;
Group73: TGroupNode;
Sound74: TSoundNode;
AudioClip75: TAudioClipNode;
TouchSensor76: TTouchSensorNode;
Transform77: TTransformNode;
Switch78: TSwitchNode;
Group79: TGroupNode;
Shape80: TShapeNode;
Appearance81: TAppearanceNode;
Text82: TTextNode;
FontStyle83: TFontStyleNode;
Sound84: TSoundNode;
AudioClip85: TAudioClipNode;
Group86: TGroupNode;
Shape87: TShapeNode;
Appearance88: TAppearanceNode;
Text89: TTextNode;
FontStyle90: TFontStyleNode;
Sound91: TSoundNode;
AudioClip92: TAudioClipNode;
Group93: TGroupNode;
Shape94: TShapeNode;
Appearance95: TAppearanceNode;
Text96: TTextNode;
FontStyle97: TFontStyleNode;
Sound98: TSoundNode;
AudioClip99: TAudioClipNode;
Transform100: TTransformNode;
Transform101: TTransformNode;
Transform102: TTransformNode;
Transform103: TTransformNode;
Transform104: TTransformNode;
Shape105: TShapeNode;
Box106: TBoxNode;
Appearance107: TAppearanceNode;
ImageTexture108: TImageTextureNode;
Transform109: TTransformNode;
Shape110: TShapeNode;
Transform111: TTransformNode;
Shape112: TShapeNode;
Transform113: TTransformNode;
Shape114: TShapeNode;
Transform115: TTransformNode;
Shape116: TShapeNode;
Transform117: TTransformNode;
Transform118: TTransformNode;
Shape119: TShapeNode;
Transform120: TTransformNode;
Shape121: TShapeNode;
Box122: TBoxNode;
Appearance123: TAppearanceNode;
Transform124: TTransformNode;
Transform125: TTransformNode;
Shape126: TShapeNode;
Extrusion127: TExtrusionNode;
Appearance128: TAppearanceNode;
Transform129: TTransformNode;
Transform130: TTransformNode;
Shape131: TShapeNode;
Box132: TBoxNode;
Appearance133: TAppearanceNode;
Transform134: TTransformNode;
Shape135: TShapeNode;
Box136: TBoxNode;
Appearance137: TAppearanceNode;
Transform138: TTransformNode;
Shape139: TShapeNode;
Appearance140: TAppearanceNode;
Material141: TMaterialNode;
Extrusion142: TExtrusionNode;
Transform143: TTransformNode;
Shape144: TShapeNode;
Appearance145: TAppearanceNode;
ImageTexture146: TImageTextureNode;
Sphere147: TSphereNode;
Transform148: TTransformNode;
Shape149: TShapeNode;
Cylinder150: TCylinderNode;
Appearance151: TAppearanceNode;
Material152: TMaterialNode;
Transform153: TTransformNode;
Shape154: TShapeNode;
Transform155: TTransformNode;
Shape156: TShapeNode;
Sphere157: TSphereNode;
Appearance158: TAppearanceNode;
Transform159: TTransformNode;
Transform160: TTransformNode;
Shape161: TShapeNode;
Appearance162: TAppearanceNode;
Extrusion163: TExtrusionNode;
Transform164: TTransformNode;
Transform165: TTransformNode;
Shape166: TShapeNode;
Transform167: TTransformNode;
Shape168: TShapeNode;
Sphere169: TSphereNode;
Appearance170: TAppearanceNode;
Transform171: TTransformNode;
Transform172: TTransformNode;
Transform173: TTransformNode;
Shape174: TShapeNode;
Appearance175: TAppearanceNode;
Extrusion176: TExtrusionNode;
Shape177: TShapeNode;
Appearance178: TAppearanceNode;
Extrusion179: TExtrusionNode;
Transform180: TTransformNode;
Transform181: TTransformNode;
Transform182: TTransformNode;
Transform183: TTransformNode;
Transform184: TTransformNode;
Shape185: TShapeNode;
Appearance186: TAppearanceNode;
Material187: TMaterialNode;
Extrusion188: TExtrusionNode;
Transform189: TTransformNode;
Shape190: TShapeNode;
Transform191: TTransformNode;
Shape192: TShapeNode;
Appearance193: TAppearanceNode;
Sphere194: TSphereNode;
Transform195: TTransformNode;
Shape196: TShapeNode;
Transform197: TTransformNode;
Shape198: TShapeNode;
Transform199: TTransformNode;
Shape200: TShapeNode;
Appearance201: TAppearanceNode;
Sphere202: TSphereNode;
Transform203: TTransformNode;
Shape204: TShapeNode;
Extrusion205: TExtrusionNode;
Appearance206: TAppearanceNode;
TouchSensor207: TTouchSensorNode;
Transform208: TTransformNode;
Switch209: TSwitchNode;
Group210: TGroupNode;
Transform211: TTransformNode;
Shape212: TShapeNode;
Sphere213: TSphereNode;
Appearance214: TAppearanceNode;
Material215: TMaterialNode;
Group216: TGroupNode;
Transform217: TTransformNode;
Inline218: TInlineNode;
Group219: TGroupNode;
Transform220: TTransformNode;
Inline221: TInlineNode;
Transform222: TTransformNode;
Shape223: TShapeNode;
Cylinder224: TCylinderNode;
Appearance225: TAppearanceNode;
Material226: TMaterialNode;
Transform227: TTransformNode;
Transform228: TTransformNode;
Shape229: TShapeNode;
Box230: TBoxNode;
Appearance231: TAppearanceNode;
Transform232: TTransformNode;
Shape233: TShapeNode;
Box234: TBoxNode;
Appearance235: TAppearanceNode;
Transform236: TTransformNode;
Shape237: TShapeNode;
Cylinder238: TCylinderNode;
Appearance239: TAppearanceNode;
Material240: TMaterialNode;
Transform241: TTransformNode;
Shape242: TShapeNode;
Cylinder243: TCylinderNode;
Appearance244: TAppearanceNode;
Material245: TMaterialNode;
Transform246: TTransformNode;
Transform247: TTransformNode;
Shape248: TShapeNode;
Transform249: TTransformNode;
Shape250: TShapeNode;
Cylinder251: TCylinderNode;
Appearance252: TAppearanceNode;
Material253: TMaterialNode;
Transform254: TTransformNode;
Transform255: TTransformNode;
Transform256: TTransformNode;
Transform257: TTransformNode;
Transform258: TTransformNode;
Shape259: TShapeNode;
Transform260: TTransformNode;
Transform261: TTransformNode;
Transform262: TTransformNode;
Transform263: TTransformNode;
Transform264: TTransformNode;
Transform265: TTransformNode;
Transform266: TTransformNode;
Transform267: TTransformNode;
Shape268: TShapeNode;
Transform269: TTransformNode;
Transform270: TTransformNode;
Transform271: TTransformNode;
Shape272: TShapeNode;
Box273: TBoxNode;
Appearance274: TAppearanceNode;
Transform275: TTransformNode;
Shape276: TShapeNode;
Cylinder277: TCylinderNode;
Appearance278: TAppearanceNode;
Shape279: TShapeNode;
Sphere280: TSphereNode;
Appearance281: TAppearanceNode;
Transform282: TTransformNode;
Shape283: TShapeNode;
Sphere284: TSphereNode;
Appearance285: TAppearanceNode;
Transform286: TTransformNode;
Shape287: TShapeNode;
Shape288: TShapeNode;
Transform289: TTransformNode;
Shape290: TShapeNode;
Transform291: TTransformNode;
Shape292: TShapeNode;
Transform293: TTransformNode;
Shape294: TShapeNode;
Shape295: TShapeNode;
Transform296: TTransformNode;
Shape297: TShapeNode;
Transform298: TTransformNode;
Shape299: TShapeNode;
Shape300: TShapeNode;
Transform301: TTransformNode;
Shape302: TShapeNode;
Transform303: TTransformNode;
Transform304: TTransformNode;
Viewpoint305: TViewpointNode;
Transform306: TTransformNode;
Transform307: TTransformNode;
TouchSensor308: TTouchSensorNode;
Switch309: TSwitchNode;
Transform310: TTransformNode;
Shape311: TShapeNode;
Box312: TBoxNode;
Appearance313: TAppearanceNode;
Material314: TMaterialNode;
Transform315: TTransformNode;
TouchSensor316: TTouchSensorNode;
Switch317: TSwitchNode;
Transform318: TTransformNode;
Shape319: TShapeNode;
Box320: TBoxNode;
Appearance321: TAppearanceNode;
Material322: TMaterialNode;
Transform323: TTransformNode;
Switch324: TSwitchNode;
Transform325: TTransformNode;
Viewpoint326: TViewpointNode;
Transform327: TTransformNode;
Transform328: TTransformNode;
Viewpoint329: TViewpointNode;
Transform330: TTransformNode;
Transform331: TTransformNode;
Viewpoint332: TViewpointNode;
Script333: TScriptNode;
field334: TfieldNode;
field335: TfieldNode;
field336: TfieldNode;
Script337: TScriptNode;
field338: TfieldNode;
field339: TfieldNode;
field340: TfieldNode;
Script341: TScriptNode;
field342: TfieldNode;
field343: TfieldNode;
Script344: TScriptNode;
field345: TfieldNode;
field346: TfieldNode;
field347: TfieldNode;
field348: TfieldNode;
field349: TfieldNode;
field350: TfieldNode;
field351: TfieldNode;
TimeSensor352: TTimeSensorNode;
PositionInterpolator353: TPositionInterpolatorNode;
OrientationInterpolator354: TOrientationInterpolatorNode;
PositionInterpolator355: TPositionInterpolatorNode;
OrientationInterpolator356: TOrientationInterpolatorNode;
PositionInterpolator357: TPositionInterpolatorNode;
begin
X3D0 := TX3DRootNode.Create;
X3D0.Profile := 'Immersive';
X3D0.ForceVersion.Major := 4;
X3D0.ForceVersion.Minor := 0;
X3D0.Meta['title'] := 'Trebuchet.x3d';
X3D0.Meta['description'] := 'Working model of a 14th century Trebuchet Catapult.';
X3D0.Meta['creator'] := 'LT Joe Roth';
X3D0.Meta['created'] := '20 June 2001';
X3D0.Meta['modified'] := '20 October 2019';
X3D0.Meta['version'] := '7.8';
X3D0.Meta['identifier'] := 'https://www.web3d.org/x3d/content/examples/Basic/StudentProjects/Trebuchet.x3d';
X3D0.Meta['reference'] := 'http://trebuchet.com';
X3D0.Meta['reference'] := 'http://members.home.net/dimona';
X3D0.Meta['subject'] := 'trebuchet catapult Monty Python';
X3D0.Meta['reference'] := 'Permission granted for use of the VRML chicken I own a copy of Monty Python and the Holy Grail I have requested permission to use for non profit use. No response received. I will use the sound clips under \"Fair Use\" clause of the DMCA';
X3D0.Meta['reference'] := 'https://www.web3d.org/WorkingGroups/media/textures/nature/leaves_5.jpg.htm';
X3D0.Meta['reference'] := 'http://www.revemonde.net/UniversalMedia/textures/nature/leaves_5.jpg.htm';
X3D0.Meta['generator'] := 'X3D-Edit 3.3, https://savage.nps.edu/X3D-Edit';
X3D0.Meta['license'] := '../license.html';
Group17 := TGroupNode.Create;
WorldInfo18 := TWorldInfoNode.Create;
WorldInfo18.Title := 'Trebuchet.x3d';
{ .AddChildren }
Group17.AddChildren([WorldInfo18]);
Background19 := TBackgroundNode.Create;
Background19.SetBackUrl(['https://www.web3d.org/WorkingGroups/media/textures/panoramas/meadow_2_back.jpg']);
Background19.SetBottomUrl(['https://www.web3d.org/WorkingGroups/media/textures/panoramas/meadow_2_bottom.jpg']);
Background19.SetFrontUrl(['https://www.web3d.org/WorkingGroups/media/textures/panoramas/meadow_2_front.jpg']);
Background19.SetGroundAngle([1.309,1.570796]);
Background19.SetGroundColor([Vector3(0.1,0.1,0),Vector3(0.4,0.25,0.2),Vector3(0.6,0.6,0.6)]);
Background19.SetLeftUrl(['https://www.web3d.org/WorkingGroups/media/textures/panoramas/meadow_2_left.jpg']);
Background19.SetRightUrl(['https://www.web3d.org/WorkingGroups/media/textures/panoramas/meadow_2_right.jpg']);
Background19.SetSkyAngle([1.309,1.57079]);
Background19.SetSkyColor([Vector3(0,0.2,0.7),Vector3(0,0.5,1),Vector3(1,1,1)]);
Background19.SetTopUrl(['https://www.web3d.org/WorkingGroups/media/textures/panoramas/meadow_2_top.jpg']);
{ .AddChildren }
Group17.AddChildren([Background19]);
Sound20 := TSoundNode.Create;
Sound20.MaxBack := 1000;
Sound20.MaxFront := 1000;
AudioClip21 := TAudioClipNode.Create;
AudioClip21.Description := 'HolyGrail';
AudioClip21.Loop := True;
AudioClip21.SetUrl(['holygral.mp3','http://www.nps.navy.mil/code32/vrml/holygral.mp3']);
{ .SetSource }
Sound20.Source := AudioClip21;
{ .AddChildren }
Group17.AddChildren([Sound20]);
Shape22 := TShapeNode.Create;
Box23 := TBoxNode.Create;
Box23.Size := Vector3(10000,1,10000);
{ .SetGeometry }
Shape22.Geometry := Box23;
Appearance24 := TAppearanceNode.Create;
ImageTexture25 := TImageTextureNode.Create;
ImageTexture25.SetUrl(['grass.jpg','https://www.web3d.org/x3d/content/examples/Basic/StudentProjects/grass.jpg']);
{ .SetTexture }
Appearance24.Texture := ImageTexture25;
{ .SetAppearance }
Shape22.Appearance := Appearance24;
{ .AddChildren }
Group17.AddChildren([Shape22]);
Transform26 := TTransformNode.Create;
Transform26.Rotation := Vector4(0,1,0,1.57);
Transform26.Scale := Vector3(0.5,0.5,0.5);
Transform26.Translation := Vector3(10.5,6.5,4.5);
Shape27 := TShapeNode.Create;
Appearance28 := TAppearanceNode.Create;
Material29 := TMaterialNode.Create;
Material29.DiffuseColor := Vector3(1,0,0);
Material29.EmissiveColor := Vector3(1,1,0);
{ .SetMaterial }
Appearance28.Material := Material29;
{ .SetAppearance }
Shape27.Appearance := Appearance28;
Text30 := TTextNode.Create;
Text30.SetText(['Click Sling to Select Projectile']);
FontStyle31 := TFontStyleNode.Create;
{ .SetFontStyle }
Text30.FontStyle := FontStyle31;
{ .SetGeometry }
Shape27.Geometry := Text30;
{ .AddChild }
Transform26.AddChildren([Shape27]);
{ .AddChildren }
Group17.AddChildren([Transform26]);
Transform32 := TTransformNode.Create;
Transform32.Rotation := Vector4(0,1,0,1.57);
Transform32.Scale := Vector3(0.5,0.5,0.5);
Transform32.Translation := Vector3(11,5.5,6);
Switch33 := TSwitchNode.Create;
Switch33.WhichChoice := 0;
Group34 := TGroupNode.Create;
Shape35 := TShapeNode.Create;
Appearance36 := TAppearanceNode.Create;
Appearance36 := Appearance28;
{ .SetAppearance }
Shape35.Appearance := Appearance36;
Text37 := TTextNode.Create;
Text37.SetText(['Click Here to Change Counter Weight (50 lbs)']);
{ .SetGeometry }
Shape35.Geometry := Text37;
{ .AddChildren }
Group34.AddChildren([Shape35]);
{ .AddChildren }
Switch33.AddChildren([Group34]);
Group38 := TGroupNode.Create;
Shape39 := TShapeNode.Create;
Appearance40 := TAppearanceNode.Create;
Appearance40 := Appearance28;
{ .SetAppearance }
Shape39.Appearance := Appearance40;
Text41 := TTextNode.Create;
Text41.SetText(['Click Here to Change Counter Weight (500 lbs)']);
{ .SetGeometry }
Shape39.Geometry := Text41;
{ .AddChildren }
Group38.AddChildren([Shape39]);
{ .AddChildren }
Switch33.AddChildren([Group38]);
Group42 := TGroupNode.Create;
Shape43 := TShapeNode.Create;
Appearance44 := TAppearanceNode.Create;
Appearance44 := Appearance28;
{ .SetAppearance }
Shape43.Appearance := Appearance44;
Text45 := TTextNode.Create;
Text45.SetText(['Click Here to Change Counter Weight (1000 lbs)']);
{ .SetGeometry }
Shape43.Geometry := Text45;
{ .AddChildren }
Group42.AddChildren([Shape43]);
{ .AddChildren }
Switch33.AddChildren([Group42]);
Group46 := TGroupNode.Create;
Shape47 := TShapeNode.Create;
Appearance48 := TAppearanceNode.Create;
Appearance48 := Appearance28;
{ .SetAppearance }
Shape47.Appearance := Appearance48;
Text49 := TTextNode.Create;
Text49.SetText(['Click Here to Change Counter Weight (10000 lbs)']);
{ .SetGeometry }
Shape47.Geometry := Text49;
{ .AddChildren }
Group46.AddChildren([Shape47]);
{ .AddChildren }
Switch33.AddChildren([Group46]);
{ .AddChildren }
Transform32.AddChildren([Switch33]);
TouchSensor50 := TTouchSensorNode.Create;
TouchSensor50.Description := 'weight selector';
{ .AddChildren }
Transform32.AddChildren([TouchSensor50]);
Transform51 := TTransformNode.Create;
Transform51.Translation := Vector3(8,0,0);
Shape52 := TShapeNode.Create;
Box53 := TBoxNode.Create;
Box53.Size := Vector3(20,1,1);
{ .SetGeometry }
Shape52.Geometry := Box53;
Appearance54 := TAppearanceNode.Create;
Material55 := TMaterialNode.Create;
Material55.Transparency := 1;
{ .SetMaterial }
Appearance54.Material := Material55;
{ .SetAppearance }
Shape52.Appearance := Appearance54;
{ .AddChild }
Transform51.AddChildren([Shape52]);
{ .AddChildren }
Transform32.AddChildren([Transform51]);
{ .AddChildren }
Group17.AddChildren([Transform32]);
Transform56 := TTransformNode.Create;
Transform56.Rotation := Vector4(0,1,0,1.57);
Transform56.Translation := Vector3(10,0.5,4.5);
Transform57 := TTransformNode.Create;
Transform57.Translation := Vector3(0,2,5);
Billboard58 := TBillboardNode.Create;
Shape59 := TShapeNode.Create;
Appearance60 := TAppearanceNode.Create;
Material61 := TMaterialNode.Create;
Material61.DiffuseColor := Vector3(1,0,0);
{ .SetMaterial }
Appearance60.Material := Material61;
{ .SetAppearance }
Shape59.Appearance := Appearance60;
Text62 := TTextNode.Create;
Text62.SetText(['LAUNCH']);
FontStyle63 := TFontStyleNode.Create;
{ .SetFontStyle }
Text62.FontStyle := FontStyle63;
{ .SetGeometry }
Shape59.Geometry := Text62;
{ .AddChildren }
Billboard58.AddChildren([Shape59]);
Transform64 := TTransformNode.Create;
Transform64.Translation := Vector3(2,0.3,0);
Shape65 := TShapeNode.Create;
Box66 := TBoxNode.Create;
Box66.Size := Vector3(5,1,1);
{ .SetGeometry }
Shape65.Geometry := Box66;
Appearance67 := TAppearanceNode.Create;
Material68 := TMaterialNode.Create;
Material68.Transparency := 1;
{ .SetMaterial }
Appearance67.Material := Material68;
{ .SetAppearance }
Shape65.Appearance := Appearance67;
{ .AddChild }
Transform64.AddChildren([Shape65]);
{ .AddChildren }
Billboard58.AddChildren([Transform64]);
Switch69 := TSwitchNode.Create;
Switch69.WhichChoice := -1;
Group70 := TGroupNode.Create;
Sound71 := TSoundNode.Create;
Sound71.MaxBack := 1000;
Sound71.MaxFront := 1000;
AudioClip72 := TAudioClipNode.Create;
AudioClip72.Description := 'PigDogSound';
AudioClip72.SetUrl(['pigdog.wav','http://www.nps.navy.mil/code32/vrml/pigdog.wav']);
{ .SetSource }
Sound71.Source := AudioClip72;
{ .AddChildren }
Group70.AddChildren([Sound71]);
{ .AddChildren }
Switch69.AddChildren([Group70]);
Group73 := TGroupNode.Create;
Sound74 := TSoundNode.Create;
Sound74.MaxBack := 1000;
Sound74.MaxFront := 1000;
AudioClip75 := TAudioClipNode.Create;
AudioClip75.Description := 'MonkSound';
AudioClip75.SetUrl(['monks.wav','http://www.nps.navy.mil/code32/vrml/monks.wav']);
{ .SetSource }
Sound74.Source := AudioClip75;
{ .AddChildren }
Group73.AddChildren([Sound74]);
{ .AddChildren }
Switch69.AddChildren([Group73]);
{ .AddChildren }
Billboard58.AddChildren([Switch69]);
{ .AddChildren }
Transform57.AddChildren([Billboard58]);
TouchSensor76 := TTouchSensorNode.Create;
TouchSensor76.Description := 'launch!';
{ .AddChildren }
Transform57.AddChildren([TouchSensor76]);
{ .AddChildren }
Transform56.AddChildren([Transform57]);
Transform77 := TTransformNode.Create;
Switch78 := TSwitchNode.Create;
Switch78.WhichChoice := 0;
Group79 := TGroupNode.Create;
Shape80 := TShapeNode.Create;
Appearance81 := TAppearanceNode.Create;
Appearance81 := Appearance28;
{ .SetAppearance }
Shape80.Appearance := Appearance81;
Text82 := TTextNode.Create;
Text82.SetText(['Bowling Ball (10 lbs)']);
FontStyle83 := TFontStyleNode.Create;
FontStyle83.Size := 0.5;
{ .SetFontStyle }
Text82.FontStyle := FontStyle83;
{ .SetGeometry }
Shape80.Geometry := Text82;
{ .AddChildren }
Group79.AddChildren([Shape80]);
Sound84 := TSoundNode.Create;
Sound84.MaxBack := 1000;
Sound84.MaxFront := 1000;
Sound84.Priority := 1;
AudioClip85 := TAudioClipNode.Create;
AudioClip85.Description := 'HolyHandGrenadeSound';
AudioClip85.SetUrl(['grenade.wav','http://www.nps.navy.mil/code32/vrml/grenade.wav']);
{ .SetSource }
Sound84.Source := AudioClip85;
{ .AddChildren }
Group79.AddChildren([Sound84]);
{ .AddChildren }
Switch78.AddChildren([Group79]);
Group86 := TGroupNode.Create;
Shape87 := TShapeNode.Create;
Appearance88 := TAppearanceNode.Create;
Appearance88 := Appearance28;
{ .SetAppearance }
Shape87.Appearance := Appearance88;
Text89 := TTextNode.Create;
Text89.SetText(['Cow (1000 lbs)']);
FontStyle90 := TFontStyleNode.Create;
FontStyle90.Size := 0.5;
{ .SetFontStyle }
Text89.FontStyle := FontStyle90;
{ .SetGeometry }
Shape87.Geometry := Text89;
{ .AddChildren }
Group86.AddChildren([Shape87]);
Sound91 := TSoundNode.Create;
Sound91.MaxBack := 1000;
Sound91.MaxFront := 1000;
AudioClip92 := TAudioClipNode.Create;
AudioClip92.Description := 'CowSound';
AudioClip92.SetUrl(['lavache.wav','http://www.nps.navy.mil/code32/vrml/lavache.wav']);
{ .SetSource }
Sound91.Source := AudioClip92;
{ .AddChildren }
Group86.AddChildren([Sound91]);
{ .AddChildren }
Switch78.AddChildren([Group86]);
Group93 := TGroupNode.Create;
Shape94 := TShapeNode.Create;
Appearance95 := TAppearanceNode.Create;
Appearance95 := Appearance28;
{ .SetAppearance }
Shape94.Appearance := Appearance95;
Text96 := TTextNode.Create;
Text96.SetText(['Chicken (5 lbs)']);
FontStyle97 := TFontStyleNode.Create;
FontStyle97.Size := 0.5;
{ .SetFontStyle }
Text96.FontStyle := FontStyle97;
{ .SetGeometry }
Shape94.Geometry := Text96;
{ .AddChildren }
Group93.AddChildren([Shape94]);
Sound98 := TSoundNode.Create;
Sound98.MaxBack := 1000;
Sound98.MaxFront := 1000;
Sound98.Priority := 1;
AudioClip99 := TAudioClipNode.Create;
AudioClip99.Description := 'HamsterSound';
AudioClip99.SetUrl(['hamster.wav','http://www.nps.navy.mil/code32/vrml/hamster.wav']);
{ .SetSource }
Sound98.Source := AudioClip99;
{ .AddChildren }
Group93.AddChildren([Sound98]);
{ .AddChildren }
Switch78.AddChildren([Group93]);
{ .AddChildren }
Transform77.AddChildren([Switch78]);
{ .AddChildren }
Transform56.AddChildren([Transform77]);
{ .AddChildren }
Group17.AddChildren([Transform56]);
Transform100 := TTransformNode.Create;
Transform100.Rotation := Vector4(0,1,0,-1.67);
Transform101 := TTransformNode.Create;
Transform101.Translation := Vector3(5,5,15);
Transform102 := TTransformNode.Create;
Transform102.Translation := Vector3(-2.5,-4.5,-2);
Transform103 := TTransformNode.Create;
Transform103 := Transform57;
{ .AddChildren }
Transform102.AddChildren([Transform103]);
{ .AddChildren }
Transform101.AddChildren([Transform102]);
{ .AddChildren }
Transform100.AddChildren([Transform101]);
{ .AddChildren }
Group17.AddChildren([Transform100]);
Transform104 := TTransformNode.Create;
Transform104.Translation := Vector3(0,3,0);
Shape105 := TShapeNode.Create;
Box106 := TBoxNode.Create;
Box106.Size := Vector3(25,1,1);
{ .SetGeometry }
Shape105.Geometry := Box106;
Appearance107 := TAppearanceNode.Create;
ImageTexture108 := TImageTextureNode.Create;
ImageTexture108.SetUrl(['wood.gif','https://www.web3d.org/x3d/content/examples/Basic/StudentProjects/wood.gif']);
{ .SetTexture }
Appearance107.Texture := ImageTexture108;
{ .SetAppearance }
Shape105.Appearance := Appearance107;
{ .AddChild }
Transform104.AddChildren([Shape105]);
Transform109 := TTransformNode.Create;
Transform109.Rotation := Vector4(0,0,1,1);
Transform109.Translation := Vector3(-5,10,0);
Shape110 := TShapeNode.Create;
Shape110 := Shape105;
{ .AddChild }
Transform109.AddChildren([Shape110]);
{ .AddChildren }
Transform104.AddChildren([Transform109]);
Transform111 := TTransformNode.Create;
Transform111.Rotation := Vector4(0,0,1,-1);
Transform111.Translation := Vector3(5,10,0);
Shape112 := TShapeNode.Create;
Shape112 := Shape105;
{ .AddChild }
Transform111.AddChildren([Shape112]);
{ .AddChildren }
Transform104.AddChildren([Transform111]);
Transform113 := TTransformNode.Create;
Transform113.Rotation := Vector4(0,0,1,1.57);
Transform113.Scale := Vector3(0.9,1,1);
Transform113.Translation := Vector3(0,11,0);
Shape114 := TShapeNode.Create;
Shape114 := Shape105;
{ .AddChild }
Transform113.AddChildren([Shape114]);
{ Main Verticle Support }
{ .AddChildren }
Transform104.AddChildren([Transform113]);
Transform115 := TTransformNode.Create;
Transform115.Scale := Vector3(0.4,1,1);
Transform115.Translation := Vector3(0,10,0);
Shape116 := TShapeNode.Create;
Shape116 := Shape105;
{ .AddChild }
Transform115.AddChildren([Shape116]);
{ .AddChildren }
Transform104.AddChildren([Transform115]);
Transform117 := TTransformNode.Create;
Transform117.Rotation := Vector4(0,0,1,1.57);
Transform117.Scale := Vector3(0.6,1,1);
Transform117.Translation := Vector3(0,5,10);
Transform118 := TTransformNode.Create;
Transform118.Rotation := Vector4(0,1,0,0.4);
Shape119 := TShapeNode.Create;
Shape119 := Shape105;
{ .AddChild }
Transform118.AddChildren([Shape119]);
{ .AddChildren }
Transform117.AddChildren([Transform118]);
{ .AddChildren }
Transform104.AddChildren([Transform117]);
Transform120 := TTransformNode.Create;
Transform120.Translation := Vector3(0,18.2,-0.3);
Shape121 := TShapeNode.Create;
Box122 := TBoxNode.Create;
Box122.Size := Vector3(5,5,0.5);
{ .SetGeometry }
Shape121.Geometry := Box122;
Appearance123 := TAppearanceNode.Create;
Appearance123 := Appearance107;
{ .SetAppearance }
Shape121.Appearance := Appearance123;
{ .AddChild }
Transform120.AddChildren([Shape121]);
{ .AddChildren }
Transform104.AddChildren([Transform120]);
Transform124 := TTransformNode.Create;
Transform124.Rotation := Vector4(1,0,0,-1.57);
Transform124.Translation := Vector3(0,0.6,2.5);
Transform125 := TTransformNode.Create;
Transform125.Rotation := Vector4(0,0,1,1.57);
Shape126 := TShapeNode.Create;
Extrusion127 := TExtrusionNode.Create;
Extrusion127.BeginCap := False;
Extrusion127.SetCrossSection([Vector2(1,-0.38),Vector2(0.92,-0.38),Vector2(0.71,-0.71),Vector2(0.38,-0.92),Vector2(0,-1),Vector2(-0.38,-0.92),Vector2(-0.71,-0.71),Vector2(-0.92,-0.38),Vector2(-1,-0.38),Vector2(-1,-1.1),Vector2(1,-1.1),Vector2(1,-0.38)]);
Extrusion127.EndCap := False;
Extrusion127.Solid := False;
Extrusion127.SetSpine([Vector3(0,6,0),Vector3(0,-11,0)]);
{ .SetGeometry }
Shape126.Geometry := Extrusion127;
Appearance128 := TAppearanceNode.Create;
Appearance128 := Appearance107;
{ .SetAppearance }
Shape126.Appearance := Appearance128;
{ .AddChild }
Transform125.AddChildren([Shape126]);
{ .AddChildren }
Transform124.AddChildren([Transform125]);
{ .AddChildren }
Transform104.AddChildren([Transform124]);
Transform129 := TTransformNode.Create;
Transform129.Center := Vector3(7,0,0);
Transform129.Rotation := Vector4(0,0,1,0.82);
Transform129.Scale := Vector3(0.9,1,1);
Transform129.Translation := Vector3(-7,18,2.5);
Transform130 := TTransformNode.Create;
Shape131 := TShapeNode.Create;
Box132 := TBoxNode.Create;
Box132.Size := Vector3(35,1,1);
{ .SetGeometry }
Shape131.Geometry := Box132;
Appearance133 := TAppearanceNode.Create;
Appearance133 := Appearance107;
{ .SetAppearance }
Shape131.Appearance := Appearance133;
{ .AddChild }
Transform130.AddChildren([Shape131]);
Transform134 := TTransformNode.Create;
Transform134.Translation := Vector3(7,0,0);
Shape135 := TShapeNode.Create;
Box136 := TBoxNode.Create;
Box136.Size := Vector3(8,2,2);
{ .SetGeometry }
Shape135.Geometry := Box136;
Appearance137 := TAppearanceNode.Create;
Appearance137 := Appearance107;
{ .SetAppearance }
Shape135.Appearance := Appearance137;
{ .AddChild }
Transform134.AddChildren([Shape135]);
{ .AddChildren }
Transform130.AddChildren([Transform134]);
{ .AddChildren }
Transform129.AddChildren([Transform130]);
Transform138 := TTransformNode.Create;
Transform138.Rotation := Vector4(1,0,0,1.57);
Transform138.Scale := Vector3(0.2,0.2,0.2);
Transform138.Translation := Vector3(-15,-1,0);
Shape139 := TShapeNode.Create;
Appearance140 := TAppearanceNode.Create;
Material141 := TMaterialNode.Create;
Material141.SpecularColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance140.Material := Material141;
{ .SetAppearance }
Shape139.Appearance := Appearance140;
Extrusion142 := TExtrusionNode.Create;
Extrusion142.BeginCap := False;
Extrusion142.Convex := False;
Extrusion142.CreaseAngle := 1.57;
Extrusion142.SetCrossSection([Vector2(0.9,0),Vector2(0.81,-0.34),Vector2(0.63,-0.63),Vector2(0.34,-0.83),Vector2(0,-0.9),Vector2(-0.34,-0.81),Vector2(-0.63,-0.63),Vector2(-0.81,-0.34),Vector2(-0.9,0),Vector2(-0.81,0.34),Vector2(-0.63,0.63),Vector2(-0.34,0.81),Vector2(0,0.9),Vector2(0.38,0.81),Vector2(0.63,0.63),Vector2(0.81,0.34),Vector2(0.9,0)]);
Extrusion142.EndCap := False;
Extrusion142.SetSpine([Vector3(2,0,0),Vector3(1.85,0,0.77),Vector3(1.41,0,1.41),Vector3(0.77,0,1.85),Vector3(0,0,2),Vector3(-0.77,0,1.85),Vector3(-1.41,0,1.41),Vector3(-1.85,0,0.77),Vector3(-2,0,0),Vector3(-1.85,0,-0.77),Vector3(-1.41,0,-1.41),Vector3(-0.77,0,-1.85),Vector3(0,0,-2),Vector3(0.77,0,-1.85),Vector3(1.41,0,-1.41),Vector3(1.85,0,-0.77),Vector3(2,0,0)]);
{ .SetGeometry }
Shape139.Geometry := Extrusion142;
{ .AddChild }
Transform138.AddChildren([Shape139]);
Transform143 := TTransformNode.Create;
Transform143.Translation := Vector3(1,0,2);
Shape144 := TShapeNode.Create;
Appearance145 := TAppearanceNode.Create;
ImageTexture146 := TImageTextureNode.Create;
ImageTexture146 := ImageTexture108;
{ .SetTexture }
Appearance145.Texture := ImageTexture146;
{ .SetAppearance }
Shape144.Appearance := Appearance145;
Sphere147 := TSphereNode.Create;
Sphere147.Radius := 1.5;
{ .SetGeometry }
Shape144.Geometry := Sphere147;
{ .AddChild }
Transform143.AddChildren([Shape144]);
{ knott }
{ .AddChildren }
Transform138.AddChildren([Transform143]);
{ .AddChildren }
Transform129.AddChildren([Transform138]);
{ The Unicorn }
Transform148 := TTransformNode.Create;
Transform148.Rotation := Vector4(0,0,1,1.2);
Transform148.Scale := Vector3(0.2,0.2,0.2);
Transform148.Translation := Vector3(-18.3,0.3,0);
Shape149 := TShapeNode.Create;
Cylinder150 := TCylinderNode.Create;
Cylinder150.Height := 10;
{ .SetGeometry }
Shape149.Geometry := Cylinder150;
Appearance151 := TAppearanceNode.Create;
Material152 := TMaterialNode.Create;
Material152.SpecularColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance151.Material := Material152;
{ .SetAppearance }
Shape149.Appearance := Appearance151;
{ .AddChild }
Transform148.AddChildren([Shape149]);
Transform153 := TTransformNode.Create;
Transform153.Translation := Vector3(0,-2.5,0);
{ The Unicorn }
Shape154 := TShapeNode.Create;
Shape154 := Shape139;
{ .AddChild }
Transform153.AddChildren([Shape154]);
Transform155 := TTransformNode.Create;
Transform155.Translation := Vector3(-2,0,0);
Shape156 := TShapeNode.Create;
Sphere157 := TSphereNode.Create;
Sphere157.Radius := 1.5;
{ .SetGeometry }
Shape156.Geometry := Sphere157;
Appearance158 := TAppearanceNode.Create;
Appearance158 := Appearance145;
{ .SetAppearance }
Shape156.Appearance := Appearance158;
{ .AddChild }
Transform155.AddChildren([Shape156]);
{ Knott }
{ .AddChildren }
Transform153.AddChildren([Transform155]);
{ .AddChildren }
Transform148.AddChildren([Transform153]);
Transform159 := TTransformNode.Create;
Transform159.Rotation := Vector4(0,0,1,1.2);
Transform159.Translation := Vector3(15,55,-11);
Transform160 := TTransformNode.Create;
Transform160.Scale := Vector3(5,5,5);
Shape161 := TShapeNode.Create;
Appearance162 := TAppearanceNode.Create;
Appearance162 := Appearance145;
{ .SetAppearance }
Shape161.Appearance := Appearance162;
Extrusion163 := TExtrusionNode.Create;
Extrusion163.BeginCap := False;
Extrusion163.CreaseAngle := 0.76;
Extrusion163.SetCrossSection([Vector2(0.1,0),Vector2(0.092,-0.038),Vector2(0.071,-0.071),Vector2(0.038,-0.092),Vector2(0,-0.1),Vector2(-0.038,-0.092),Vector2(-0.071,-0.071),Vector2(-0.092,-0.038),Vector2(-0.1,0),Vector2(-0.092,0.038),Vector2(-0.071,0.071),Vector2(-0.038,0.092),Vector2(0,0.1),Vector2(0.038,0.092),Vector2(0.071,0.071),Vector2(0.092,0.038),Vector2(0.1,0)]);
Extrusion163.EndCap := False;
Extrusion163.Solid := False;
Extrusion163.SetSpine([Vector3(-15.2,1.4,2.2),Vector3(-12,-0.8,2.2)]);
{ .SetGeometry }
Shape161.Geometry := Extrusion163;
{ .AddChild }
Transform160.AddChildren([Shape161]);
{ .AddChildren }
Transform159.AddChildren([Transform160]);
{ .AddChildren }
Transform148.AddChildren([Transform159]);
{ .AddChildren }
Transform129.AddChildren([Transform148]);
Transform164 := TTransformNode.Create;
Transform164.Rotation := Vector4(1,0,0,-1.7);
Transform164.Translation := Vector3(-17,-4.5,0);
Transform165 := TTransformNode.Create;
Transform165.Scale := Vector3(0.2,0.2,0.2);
{ Knot }
Shape166 := TShapeNode.Create;
Shape166 := Shape139;
{ .AddChild }
Transform165.AddChildren([Shape166]);
Transform167 := TTransformNode.Create;
Transform167.Translation := Vector3(-1,0,1.7);
Shape168 := TShapeNode.Create;
Sphere169 := TSphereNode.Create;
Sphere169.Radius := 1.5;
{ .SetGeometry }
Shape168.Geometry := Sphere169;
Appearance170 := TAppearanceNode.Create;
Appearance170 := Appearance145;
{ .SetAppearance }
Shape168.Appearance := Appearance170;
{ .AddChild }
Transform167.AddChildren([Shape168]);
{ .AddChildren }
Transform165.AddChildren([Transform167]);
{ .AddChildren }
Transform164.AddChildren([Transform165]);
{ .AddChildren }
Transform129.AddChildren([Transform164]);
Transform171 := TTransformNode.Create;
Transform172 := TTransformNode.Create;
Transform173 := TTransformNode.Create;
Transform173.Rotation := Vector4(0,0,1,-0.82);
Transform173.Translation := Vector3(7,-26,-2.5);
Shape174 := TShapeNode.Create;
Appearance175 := TAppearanceNode.Create;
Appearance175 := Appearance145;
{ .SetAppearance }
Shape174.Appearance := Appearance175;
Extrusion176 := TExtrusionNode.Create;
Extrusion176.BeginCap := False;
Extrusion176.CreaseAngle := 0.76;
Extrusion176.SetCrossSection([Vector2(0.1,0),Vector2(0.092,-0.038),Vector2(0.071,-0.071),Vector2(0.038,-0.092),Vector2(0,-0.1),Vector2(-0.038,-0.092),Vector2(-0.071,-0.071),Vector2(-0.092,-0.038),Vector2(-0.1,0),Vector2(-0.092,0.038),Vector2(-0.071,0.071),Vector2(-0.038,0.092),Vector2(0,0.1),Vector2(0.038,0.092),Vector2(0.071,0.071),Vector2(0.092,0.038),Vector2(0.1,0)]);
Extrusion176.EndCap := False;
Extrusion176.Solid := False;
Extrusion176.SetSpine([Vector3(-33,0.9,2.5),Vector3(-18.5,1.9,2.55)]);
{ .SetGeometry }
Shape174.Geometry := Extrusion176;
{ .AddChild }
Transform173.AddChildren([Shape174]);
Shape177 := TShapeNode.Create;
Appearance178 := TAppearanceNode.Create;
Appearance178 := Appearance145;
{ .SetAppearance }
Shape177.Appearance := Appearance178;
Extrusion179 := TExtrusionNode.Create;
Extrusion179.BeginCap := False;
Extrusion179.CreaseAngle := 0.76;
Extrusion179.SetCrossSection([Vector2(0.1,0),Vector2(0.092,-0.038),Vector2(0.071,-0.071),Vector2(0.038,-0.092),Vector2(0,-0.1),Vector2(-0.038,-0.092),Vector2(-0.071,-0.071),Vector2(-0.092,-0.038),Vector2(-0.1,0),Vector2(-0.092,0.038),Vector2(-0.071,0.071),Vector2(-0.038,0.092),Vector2(0,0.1),Vector2(0.038,0.092),Vector2(0.071,0.071),Vector2(0.092,0.038),Vector2(0.1,0)]);
Extrusion179.EndCap := False;
Extrusion179.Solid := False;
Extrusion179.SetSpine([Vector3(-35.7,-0.8,2.5),Vector3(-18.8,-0.8,2.55)]);
{ .SetGeometry }
Shape177.Geometry := Extrusion179;
{ .AddChild }
Transform173.AddChildren([Shape177]);
{ .AddChildren }
Transform172.AddChildren([Transform173]);
{ .AddChildren }
Transform171.AddChildren([Transform172]);
Transform180 := TTransformNode.Create;
Transform180.Rotation := Vector4(0,0,1,-0.82);
Transform180.Translation := Vector3(-4,-15.3,0);
Transform181 := TTransformNode.Create;
Transform182 := TTransformNode.Create;
Transform182.Rotation := Vector4(0,1,0,-1.57);
Transform182.Scale := Vector3(1,1.3,1);
Transform182.Translation := Vector3(0.5,0,-1);
Transform183 := TTransformNode.Create;
Transform183.Rotation := Vector4(0,0,1,1.57);
Transform184 := TTransformNode.Create;
Transform184.Scale := Vector3(0.3,0.3,0.3);
Shape185 := TShapeNode.Create;
Appearance186 := TAppearanceNode.Create;
Material187 := TMaterialNode.Create;
Material187.Transparency := 0.5;
{ .SetMaterial }
Appearance186.Material := Material187;
{ .SetAppearance }
Shape185.Appearance := Appearance186;
Extrusion188 := TExtrusionNode.Create;
Extrusion188.SetCrossSection([Vector2(0,0),Vector2(0,5),Vector2(0.5,7),Vector2(1,8),Vector2(2,9),Vector2(3,11),Vector2(3.5,11.2),Vector2(4,11),Vector2(5,9),Vector2(6,8),Vector2(6.5,7),Vector2(6.7,5),Vector2(6.7,0),Vector2(0,0)]);
Extrusion188.SetSpine([Vector3(0,0,0),Vector3(0.1,0,0)]);
{ .SetGeometry }
Shape185.Geometry := Extrusion188;
{ .AddChild }
Transform184.AddChildren([Shape185]);
Transform189 := TTransformNode.Create;
Transform189.Scale := Vector3(0.3,0.3,0.3);
Transform189.Translation := Vector3(0,-3.5,11.5);
Shape190 := TShapeNode.Create;
Shape190 := Shape139;
{ .AddChild }
Transform189.AddChildren([Shape190]);
Transform191 := TTransformNode.Create;
Transform191.Translation := Vector3(0,0,2);
Shape192 := TShapeNode.Create;
Appearance193 := TAppearanceNode.Create;
Appearance193 := Appearance145;
{ .SetAppearance }
Shape192.Appearance := Appearance193;
Sphere194 := TSphereNode.Create;
Sphere194.Radius := 1.5;
{ .SetGeometry }
Shape192.Geometry := Sphere194;
{ .AddChild }
Transform191.AddChildren([Shape192]);
{ .AddChildren }
Transform189.AddChildren([Transform191]);
{ .AddChildren }
Transform184.AddChildren([Transform189]);
{ .AddChildren }
Transform183.AddChildren([Transform184]);
Transform195 := TTransformNode.Create;
Transform195.Scale := Vector3(0.3,0.3,0.3);
Transform195.Translation := Vector3(2,0,0);
Shape196 := TShapeNode.Create;
Shape196 := Shape185;
{ .AddChild }
Transform195.AddChildren([Shape196]);
Transform197 := TTransformNode.Create;
Transform197.Scale := Vector3(0.3,0.3,0.3);
Transform197.Translation := Vector3(0,-3.5,11.3);
Shape198 := TShapeNode.Create;
Shape198 := Shape139;
{ .AddChild }
Transform197.AddChildren([Shape198]);
Transform199 := TTransformNode.Create;
Transform199.Translation := Vector3(0,0,2);
Shape200 := TShapeNode.Create;
Appearance201 := TAppearanceNode.Create;
Appearance201 := Appearance145;
{ .SetAppearance }
Shape200.Appearance := Appearance201;
Sphere202 := TSphereNode.Create;
Sphere202.Radius := 1.5;
{ .SetGeometry }
Shape200.Geometry := Sphere202;
{ .AddChild }
Transform199.AddChildren([Shape200]);
{ .AddChildren }
Transform197.AddChildren([Transform199]);
{ .AddChildren }
Transform195.AddChildren([Transform197]);
{ .AddChildren }
Transform183.AddChildren([Transform195]);
Transform203 := TTransformNode.Create;
Transform203.Translation := Vector3(1,-1,0);
Shape204 := TShapeNode.Create;
Extrusion205 := TExtrusionNode.Create;
Extrusion205.BeginCap := False;
Extrusion205.CreaseAngle := 0.785;
Extrusion205.SetCrossSection([Vector2(1,0),Vector2(0.92,-0.38),Vector2(0.71,-0.71),Vector2(0.38,-0.92),Vector2(0,-1),Vector2(-0.38,-0.92),Vector2(-0.71,-0.71),Vector2(-0.92,-0.38),Vector2(-1,0)]);
Extrusion205.EndCap := False;
Extrusion205.Solid := False;
Extrusion205.SetSpine([Vector3(0,-1,0),Vector3(0,1,0)]);
{ .SetGeometry }
Shape204.Geometry := Extrusion205;
Appearance206 := TAppearanceNode.Create;
Appearance206 := Appearance186;
{ .SetAppearance }
Shape204.Appearance := Appearance206;
{ .AddChild }
Transform203.AddChildren([Shape204]);
{ .AddChildren }
Transform183.AddChildren([Transform203]);
{ .AddChildren }
Transform182.AddChildren([Transform183]);
TouchSensor207 := TTouchSensorNode.Create;
TouchSensor207.Description := 'launcher choice';
{ .AddChildren }
Transform182.AddChildren([TouchSensor207]);
{ .AddChildren }
Transform181.AddChildren([Transform182]);
Transform208 := TTransformNode.Create;
Transform208.Scale := Vector3(0.01,0.01,0.01);
Switch209 := TSwitchNode.Create;
Switch209.WhichChoice := 0;
Group210 := TGroupNode.Create;
Transform211 := TTransformNode.Create;
Transform211.Translation := Vector3(0,0.7,0);
Shape212 := TShapeNode.Create;
Sphere213 := TSphereNode.Create;
Sphere213.Radius := 0.7;
{ .SetGeometry }
Shape212.Geometry := Sphere213;
Appearance214 := TAppearanceNode.Create;
Material215 := TMaterialNode.Create;
Material215.DiffuseColor := Vector3(0,0,0);
Material215.SpecularColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance214.Material := Material215;
{ .SetAppearance }
Shape212.Appearance := Appearance214;
{ .AddChild }
Transform211.AddChildren([Shape212]);
{ .AddChildren }
Group210.AddChildren([Transform211]);
{ .AddChildren }
Switch209.AddChildren([Group210]);
Group216 := TGroupNode.Create;
Transform217 := TTransformNode.Create;
Inline218 := TInlineNode.Create;
Inline218.SetUrl(['cow.wrl','http://www.uoguelph.ca/~dchiu/cow.wrl']);
{ .AddChildren }
Transform217.AddChildren([Inline218]);
{ .AddChildren }
Group216.AddChildren([Transform217]);
{ .AddChildren }
Switch209.AddChildren([Group216]);
Group219 := TGroupNode.Create;
Transform220 := TTransformNode.Create;
Transform220.Rotation := Vector4(0,1,0,1.57);
Transform220.Scale := Vector3(0.4,0.4,0.4);
Transform220.Translation := Vector3(0,0.7,0);
Inline221 := TInlineNode.Create;
Inline221.SetUrl(['vrml_ginger.wrl','http://home.inreach.com/ntamura/vrml/vrml_ginger.wrl']);
{ .AddChildren }
Transform220.AddChildren([Inline221]);
{ .AddChildren }
Group219.AddChildren([Transform220]);
{ .AddChildren }
Switch209.AddChildren([Group219]);
{ .AddChildren }
Transform208.AddChildren([Switch209]);
{ .AddChildren }
Transform181.AddChildren([Transform208]);
{ .AddChildren }
Transform180.AddChildren([Transform181]);
{ .AddChildren }
Transform171.AddChildren([Transform180]);
{ .AddChildren }
Transform129.AddChildren([Transform171]);
{ .AddChildren }
Transform104.AddChildren([Transform129]);
Transform222 := TTransformNode.Create;
Transform222.Rotation := Vector4(1,0,0,1.57);
Transform222.Translation := Vector3(0,18,2.5);
Shape223 := TShapeNode.Create;
Cylinder224 := TCylinderNode.Create;
Cylinder224.Height := 8;
Cylinder224.Radius := 0.4;
{ .SetGeometry }
Shape223.Geometry := Cylinder224;
Appearance225 := TAppearanceNode.Create;
Material226 := TMaterialNode.Create;
Material226.DiffuseColor := Vector3(0,0,0);
Material226.SpecularColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance225.Material := Material226;
{ .SetAppearance }
Shape223.Appearance := Appearance225;
{ .AddChild }
Transform222.AddChildren([Shape223]);
{ Top Pivot }
{ .AddChildren }
Transform104.AddChildren([Transform222]);
Transform227 := TTransformNode.Create;
Transform228 := TTransformNode.Create;
Transform228.Translation := Vector3(4,18,1.8);
Shape229 := TShapeNode.Create;
Box230 := TBoxNode.Create;
Box230.Size := Vector3(1,10,0.5);
{ .SetGeometry }
Shape229.Geometry := Box230;
Appearance231 := TAppearanceNode.Create;
Appearance231 := Appearance107;
{ .SetAppearance }
Shape229.Appearance := Appearance231;
{ .AddChild }
Transform228.AddChildren([Shape229]);
{ .AddChildren }
Transform227.AddChildren([Transform228]);
Transform232 := TTransformNode.Create;
Transform232.Translation := Vector3(4,18,3.2);
Shape233 := TShapeNode.Create;
Box234 := TBoxNode.Create;
Box234.Size := Vector3(1,10,0.5);
{ .SetGeometry }
Shape233.Geometry := Box234;
Appearance235 := TAppearanceNode.Create;
Appearance235 := Appearance107;
{ .SetAppearance }
Shape233.Appearance := Appearance235;
{ .AddChild }
Transform232.AddChildren([Shape233]);
{ .AddChildren }
Transform227.AddChildren([Transform232]);
Transform236 := TTransformNode.Create;
Transform236.Translation := Vector3(4,14,2.5);
{ CounterWeight }
Shape237 := TShapeNode.Create;
Cylinder238 := TCylinderNode.Create;
Cylinder238.Height := 4;
Cylinder238.Radius := 1.5;
{ .SetGeometry }
Shape237.Geometry := Cylinder238;
Appearance239 := TAppearanceNode.Create;
Material240 := TMaterialNode.Create;
Material240.DiffuseColor := Vector3(0,0,0);
Material240.SpecularColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance239.Material := Material240;
{ .SetAppearance }
Shape237.Appearance := Appearance239;
{ .AddChild }
Transform236.AddChildren([Shape237]);
{ .AddChildren }
Transform227.AddChildren([Transform236]);
Transform241 := TTransformNode.Create;
Transform241.Rotation := Vector4(1,0,0,1.57);
Transform241.Translation := Vector3(4,22,2.5);
Shape242 := TShapeNode.Create;
Cylinder243 := TCylinderNode.Create;
Cylinder243.Height := 2.5;
Cylinder243.Radius := 0.3;
{ .SetGeometry }
Shape242.Geometry := Cylinder243;
Appearance244 := TAppearanceNode.Create;
Material245 := TMaterialNode.Create;
Material245.DiffuseColor := Vector3(0,0,0);
Material245.SpecularColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance244.Material := Material245;
{ .SetAppearance }
Shape242.Appearance := Appearance244;
{ .AddChild }
Transform241.AddChildren([Shape242]);
{ .AddChildren }
Transform227.AddChildren([Transform241]);
{ .AddChildren }
Transform104.AddChildren([Transform227]);
Transform246 := TTransformNode.Create;
Transform246.Rotation := Vector4(0,0,1,1.57);
Transform246.Scale := Vector3(0.2,0.2,0.2);
Transform246.Translation := Vector3(-11.5,-1,2);
Transform247 := TTransformNode.Create;
Transform247.Rotation := Vector4(1,0,0,1.57);
Shape248 := TShapeNode.Create;
Shape248 := Shape139;
{ .AddChild }
Transform247.AddChildren([Shape248]);
Transform249 := TTransformNode.Create;
Transform249.Rotation := Vector4(1,0,0,-1.57);
Transform249.Translation := Vector3(0,0,7);
Shape250 := TShapeNode.Create;
Cylinder251 := TCylinderNode.Create;
Cylinder251.Height := 10;
Cylinder251.Radius := 0.7;
{ .SetGeometry }
Shape250.Geometry := Cylinder251;
Appearance252 := TAppearanceNode.Create;
Material253 := TMaterialNode.Create;
Material253.SpecularColor := Vector3(1,1,1);
{ .SetMaterial }
Appearance252.Material := Material253;
{ .SetAppearance }
Shape250.Appearance := Appearance252;
{ .AddChild }
Transform249.AddChildren([Shape250]);
{ .AddChildren }
Transform247.AddChildren([Transform249]);
{ .AddChildren }
Transform246.AddChildren([Transform247]);
Transform254 := TTransformNode.Create;
Transform254.Translation := Vector3(0,0,7);
Transform255 := TTransformNode.Create;
Transform255 := Transform247;
{ .AddChildren }
Transform254.AddChildren([Transform255]);
{ .AddChildren }
Transform246.AddChildren([Transform254]);
{ Release Pin }
Transform256 := TTransformNode.Create;
Transform256.Rotation := Vector4(1,0,0,-1.57);
Transform256.Translation := Vector3(0,0,-3);
Transform257 := TTransformNode.Create;
Transform257 := Transform247;
{ .AddChildren }
Transform256.AddChildren([Transform257]);
{ .AddChildren }
Transform246.AddChildren([Transform256]);
{ .AddChildren }
Transform104.AddChildren([Transform246]);
Transform258 := TTransformNode.Create;
Transform258.Translation := Vector3(0,0,5);
Shape259 := TShapeNode.Create;
Shape259 := Shape105;
{ .AddChild }
Transform258.AddChildren([Shape259]);
Transform260 := TTransformNode.Create;
Transform260 := Transform109;
{ .AddChildren }
Transform258.AddChildren([Transform260]);
Transform261 := TTransformNode.Create;
Transform261 := Transform111;
{ .AddChildren }
Transform258.AddChildren([Transform261]);
Transform262 := TTransformNode.Create;
Transform262 := Transform113;
{ .AddChildren }
Transform258.AddChildren([Transform262]);
Transform263 := TTransformNode.Create;
Transform263 := Transform115;
{ .AddChildren }
Transform258.AddChildren([Transform263]);
Transform264 := TTransformNode.Create;
Transform264.Rotation := Vector4(0,1,0,1.57);
Transform264.Scale := Vector3(0.6,1,1);
Transform264.Translation := Vector3(0,-11,-2.5);
Transform265 := TTransformNode.Create;
Transform265 := Transform115;
{ .AddChildren }
Transform264.AddChildren([Transform265]);
{ .AddChildren }
Transform258.AddChildren([Transform264]);
Transform266 := TTransformNode.Create;
Transform266.Rotation := Vector4(0,0,1,-1.57);
Transform266.Scale := Vector3(0.6,1,1);
Transform266.Translation := Vector3(0,5,-10);
Transform267 := TTransformNode.Create;
Transform267.Rotation := Vector4(0,1,0,0.4);
Shape268 := TShapeNode.Create;
Shape268 := Shape105;
{ .AddChild }
Transform267.AddChildren([Shape268]);
{ .AddChildren }
Transform266.AddChildren([Transform267]);
{ .AddChildren }
Transform258.AddChildren([Transform266]);
Transform269 := TTransformNode.Create;
Transform269.Translation := Vector3(0,0,0.6);
Transform270 := TTransformNode.Create;
Transform270 := Transform120;
{ .AddChildren }
Transform269.AddChildren([Transform270]);
{ .AddChildren }
Transform258.AddChildren([Transform269]);
{ .AddChildren }
Transform104.AddChildren([Transform258]);
Transform271 := TTransformNode.Create;
Transform271.Translation := Vector3(10,-1,2.5);
Shape272 := TShapeNode.Create;
Box273 := TBoxNode.Create;
Box273.Size := Vector3(1,1,8);
{ .SetGeometry }
Shape272.Geometry := Box273;
Appearance274 := TAppearanceNode.Create;
Appearance274 := Appearance107;
{ .SetAppearance }
Shape272.Appearance := Appearance274;
{ .AddChild }
Transform271.AddChildren([Shape272]);
Transform275 := TTransformNode.Create;
Transform275.Rotation := Vector4(1,0,0,1.57);
Transform275.Translation := Vector3(0,0,4.5);
Shape276 := TShapeNode.Create;
Cylinder277 := TCylinderNode.Create;
Cylinder277.Radius := 2;
{ .SetGeometry }
Shape276.Geometry := Cylinder277;
Appearance278 := TAppearanceNode.Create;
Appearance278 := Appearance107;
{ .SetAppearance }
Shape276.Appearance := Appearance278;
{ .AddChild }
Transform275.AddChildren([Shape276]);
Shape279 := TShapeNode.Create;
Sphere280 := TSphereNode.Create;
Sphere280.Radius := 1.5;
{ .SetGeometry }
Shape279.Geometry := Sphere280;
Appearance281 := TAppearanceNode.Create;
Appearance281 := Appearance214;
{ .SetAppearance }
Shape279.Appearance := Appearance281;
{ .AddChild }
Transform275.AddChildren([Shape279]);
Transform282 := TTransformNode.Create;
Transform282.Translation := Vector3(0,0.55,0);
Shape283 := TShapeNode.Create;
Sphere284 := TSphereNode.Create;
Sphere284.Radius := 1.5;
{ .SetGeometry }
Shape283.Geometry := Sphere284;
Appearance285 := TAppearanceNode.Create;
Appearance285 := Appearance214;
{ .SetAppearance }
Shape283.Appearance := Appearance285;
{ .AddChild }
Transform282.AddChildren([Shape283]);
{ .AddChildren }
Transform275.AddChildren([Transform282]);
{ .AddChildren }
Transform271.AddChildren([Transform275]);
Transform286 := TTransformNode.Create;
Transform286.Rotation := Vector4(1,0,0,1.57);
Transform286.Translation := Vector3(0,0,-4.5);
Shape287 := TShapeNode.Create;
Shape287 := Shape276;
{ .AddChild }
Transform286.AddChildren([Shape287]);
Shape288 := TShapeNode.Create;
Shape288 := Shape279;
{ .AddChild }
Transform286.AddChildren([Shape288]);
Transform289 := TTransformNode.Create;
Transform289.Translation := Vector3(0,-0.55,0);
Shape290 := TShapeNode.Create;
Shape290 := Shape283;
{ .AddChild }
Transform289.AddChildren([Shape290]);
{ .AddChildren }
Transform286.AddChildren([Transform289]);
{ .AddChildren }
Transform271.AddChildren([Transform286]);
{ .AddChildren }
Transform104.AddChildren([Transform271]);
Transform291 := TTransformNode.Create;
Transform291.Translation := Vector3(-10,-1,2.5);
Shape292 := TShapeNode.Create;
Shape292 := Shape272;
{ .AddChild }
Transform291.AddChildren([Shape292]);
Transform293 := TTransformNode.Create;
Transform293.Rotation := Vector4(1,0,0,1.57);
Transform293.Translation := Vector3(0,0,4.5);
Shape294 := TShapeNode.Create;
Shape294 := Shape276;
{ .AddChild }
Transform293.AddChildren([Shape294]);
Shape295 := TShapeNode.Create;
Shape295 := Shape279;
{ .AddChild }
Transform293.AddChildren([Shape295]);
Transform296 := TTransformNode.Create;
Transform296.Translation := Vector3(0,0.55,0);
Shape297 := TShapeNode.Create;
Shape297 := Shape283;
{ .AddChild }
Transform296.AddChildren([Shape297]);
{ .AddChildren }
Transform293.AddChildren([Transform296]);
{ .AddChildren }
Transform291.AddChildren([Transform293]);
Transform298 := TTransformNode.Create;
Transform298.Rotation := Vector4(1,0,0,1.57);
Transform298.Translation := Vector3(0,0,-4.5);
Shape299 := TShapeNode.Create;
Shape299 := Shape276;
{ .AddChild }
Transform298.AddChildren([Shape299]);
Shape300 := TShapeNode.Create;
Shape300 := Shape279;
{ .AddChild }
Transform298.AddChildren([Shape300]);
Transform301 := TTransformNode.Create;
Transform301.Translation := Vector3(0,-0.55,0);
Shape302 := TShapeNode.Create;
Shape302 := Shape283;
{ .AddChild }
Transform301.AddChildren([Shape302]);
{ .AddChildren }
Transform298.AddChildren([Transform301]);
{ .AddChildren }
Transform291.AddChildren([Transform298]);
Transform303 := TTransformNode.Create;
Transform303.Rotation := Vector4(0,1,0,-0.6);
Transform303.Translation := Vector3(0,100,400);
Transform304 := TTransformNode.Create;
Transform304.Translation := Vector3(1,3,0);
Viewpoint305 := TViewpointNode.Create;
Viewpoint305.Description := 'Side';
{ .AddChildren }
Transform304.AddChildren([Viewpoint305]);
{ .AddChildren }
Transform303.AddChildren([Transform304]);
Transform306 := TTransformNode.Create;
Transform306 := Transform57;
{ .AddChildren }
Transform303.AddChildren([Transform306]);
Transform307 := TTransformNode.Create;
TouchSensor308 := TTouchSensorNode.Create;
TouchSensor308 := TouchSensor207;
{ .AddChildren }
Transform307.AddChildren([TouchSensor308]);
Switch309 := TSwitchNode.Create;
Switch309 := Switch78;
{ .AddChildren }
Transform307.AddChildren([Switch309]);
Transform310 := TTransformNode.Create;
Transform310.Translation := Vector3(2.5,0,0);
Shape311 := TShapeNode.Create;
Box312 := TBoxNode.Create;
Box312.Size := Vector3(5,0.5,0.5);
{ .SetGeometry }
Shape311.Geometry := Box312;
Appearance313 := TAppearanceNode.Create;
Material314 := TMaterialNode.Create;
Material314.Transparency := 1;
{ .SetMaterial }
Appearance313.Material := Material314;
{ .SetAppearance }
Shape311.Appearance := Appearance313;
{ .AddChild }
Transform310.AddChildren([Shape311]);
{ .AddChildren }
Transform307.AddChildren([Transform310]);
{ .AddChildren }
Transform303.AddChildren([Transform307]);
Transform315 := TTransformNode.Create;
Transform315.Scale := Vector3(0.5,0.5,0.5);
Transform315.Translation := Vector3(0,-1,0);
TouchSensor316 := TTouchSensorNode.Create;
TouchSensor316 := TouchSensor50;
{ .AddChildren }
Transform315.AddChildren([TouchSensor316]);
Switch317 := TSwitchNode.Create;
Switch317 := Switch33;
{ .AddChildren }
Transform315.AddChildren([Switch317]);
Transform318 := TTransformNode.Create;
Transform318.Translation := Vector3(8,0,0);
Shape319 := TShapeNode.Create;
Box320 := TBoxNode.Create;
Box320.Size := Vector3(17,1,0.5);
{ .SetGeometry }
Shape319.Geometry := Box320;
Appearance321 := TAppearanceNode.Create;
Material322 := TMaterialNode.Create;
Material322.Transparency := 1;
{ .SetMaterial }
Appearance321.Material := Material322;
{ .SetAppearance }
Shape319.Appearance := Appearance321;
{ .AddChild }
Transform318.AddChildren([Shape319]);
{ .AddChildren }
Transform315.AddChildren([Transform318]);
{ .AddChildren }
Transform303.AddChildren([Transform315]);
{ .AddChildren }
Transform291.AddChildren([Transform303]);
Transform323 := TTransformNode.Create;
Transform323.Translation := Vector3(14.25,1.25,0);
Switch324 := TSwitchNode.Create;
Switch324 := Switch209;
{ .AddChildren }
Transform323.AddChildren([Switch324]);
Transform325 := TTransformNode.Create;
Transform325.Rotation := Vector4(0,1,0,1.57);
Transform325.Translation := Vector3(0,1,0);
Viewpoint326 := TViewpointNode.Create;
Viewpoint326.Description := 'Projectile Cam';
Viewpoint326.Position := Vector3(0,0,15);
{ .AddChildren }
Transform325.AddChildren([Viewpoint326]);
{ .AddChildren }
Transform323.AddChildren([Transform325]);
{ .AddChildren }
Transform291.AddChildren([Transform323]);
Transform327 := TTransformNode.Create;
Transform327.Translation := Vector3(20,2,0);
Transform328 := TTransformNode.Create;
Transform328.Rotation := Vector4(0,1,0,1.57);
Viewpoint329 := TViewpointNode.Create;
Viewpoint329.Description := 'Fore';
{ .AddChildren }
Transform328.AddChildren([Viewpoint329]);
{ .AddChildren }
Transform327.AddChildren([Transform328]);
{ .AddChildren }
Transform291.AddChildren([Transform327]);
Transform330 := TTransformNode.Create;
Transform330.Translation := Vector3(-8,4,0);
Transform331 := TTransformNode.Create;
Transform331.Rotation := Vector4(0,1,0,-1.57);
Viewpoint332 := TViewpointNode.Create;
Viewpoint332.Description := 'Aft';
{ .AddChildren }
Transform331.AddChildren([Viewpoint332]);
{ .AddChildren }
Transform330.AddChildren([Transform331]);
{ .AddChildren }
Transform291.AddChildren([Transform330]);
Script333 := TScriptNode.Create;
field334 := TfieldNode.Create;
field334.NameField := 'set_boolean';
field334.AccessType := 'inputOnly';
field334.Type := 'SFBool';
{ .AddField }
Script333.Field := field334;
field335 := TfieldNode.Create;
field335.NameField := 'whichchoice';
field335.AccessType := 'outputOnly';
field335.Type := 'SFInt32';
{ .AddField }
Script333.Field := field335;
field336 := TfieldNode.Create;
field336.NameField := 'CounterWeight';
field336.AccessType := 'outputOnly';
field336.Type := 'SFFloat';
{ .AddField }
Script333.Field := field336;

Script333.SetSourceCode('''ecmascript:\n"+
"\n"+
"\n"+
"function initialize ()\n"+
"{\n"+
"	whichchoice =0;\n"+
"	CounterWeight=100;\n"+
"}\n"+
"\n"+
"function set_boolean ( boolean_input, eventTime)\n"+
"{\n"+
"\n"+
"	if ( boolean_input== false ) { return; } // ignore the unclick\n"+
"        whichchoice = whichchoice +1;\n"+
"	if (whichchoice == 0)CounterWeight=50.00;\n"+
"	if (whichchoice == 1)CounterWeight=500.00;\n"+
"	if (whichchoice == 2)CounterWeight=1000.00;\n"+
"	if (whichchoice == 3)CounterWeight=10000.00;\n"+
"        if ( whichchoice ==4 ) { whichchoice = 0; CounterWeight=50; }\n"+
"\n"+
"\n"+
"        Browser.println ('CounterWeight ='+CounterWeight);\n"+
"}''');
{ .AddChildren }
Transform291.AddChildren([Script333]);
Script337 := TScriptNode.Create;
field338 := TfieldNode.Create;
field338.NameField := 'set_boolean';
field338.AccessType := 'inputOnly';
field338.Type := 'SFBool';
{ .AddField }
Script337.Field := field338;
field339 := TfieldNode.Create;
field339.NameField := 'whichchoice';
field339.AccessType := 'outputOnly';
field339.Type := 'SFInt32';
{ .AddField }
Script337.Field := field339;
field340 := TfieldNode.Create;
field340.NameField := 'ProjectileWeight';
field340.AccessType := 'outputOnly';
field340.Type := 'SFFloat';
{ .AddField }
Script337.Field := field340;

Script337.SetSourceCode('''ecmascript:\n"+
"\n"+
"function set_boolean (boolean_input, eventTime)\n"+
"{\n"+
"	if ( boolean_input== false ) { return; } // ignore unclick\n"+
"        whichchoice = whichchoice +1;\n"+
"        if (whichchoice == 0)ProjectileWeight=10.00;\n"+
"        if (whichchoice == 1)ProjectileWeight=1000.00;\n"+
"	if (whichchoice == 2)ProjectileWeight=5;\n"+
"\n"+
"	if ( whichchoice ==3 ) { whichchoice = 0; ProjectileWeight=10.00; }\n"+
"	Browser.println ('Projectile Weight'+ProjectileWeight);\n"+
"}''');
{ .AddChildren }
Transform291.AddChildren([Script337]);
Script341 := TScriptNode.Create;
field342 := TfieldNode.Create;
field342.NameField := 'set_boolean';
field342.AccessType := 'inputOnly';
field342.Type := 'SFBool';
{ .AddField }
Script341.Field := field342;
field343 := TfieldNode.Create;
field343.NameField := 'whichchoice';
field343.AccessType := 'outputOnly';
field343.Type := 'SFInt32';
{ .AddField }
Script341.Field := field343;

Script341.SetSourceCode('''ecmascript:\n"+
"\n"+
"function set_boolean (boolean_input, eventTime)\n"+
"{\n"+
"	if ( boolean_input== false ) { return; } // ignore unclick\n"+
"\n"+
"        whichchoice = whichchoice +1;\n"+
"\n"+
"        if ( whichchoice ==2 )  whichchoice = 0;\n"+
"\n"+
"\n"+
"}''');
{ .AddChildren }
Transform291.AddChildren([Script341]);
Script344 := TScriptNode.Create;
field345 := TfieldNode.Create;
field345.NameField := 'set_fraction';
field345.AccessType := 'inputOnly';
field345.Type := 'SFFloat';
{ .AddField }
Script344.Field := field345;
field346 := TfieldNode.Create;
field346.NameField := 'set_MassCounterWeight';
field346.AccessType := 'inputOnly';
field346.Type := 'SFFloat';
{ .AddField }
Script344.Field := field346;
field347 := TfieldNode.Create;
field347.NameField := 'set_MassProjectileWeight';
field347.AccessType := 'inputOnly';
field347.Type := 'SFFloat';
{ .AddField }
Script344.Field := field347;
field348 := TfieldNode.Create;
field348.NameField := 'MassCounterWeight';
field348.AccessType := 'initializeOnly';
field348.Type := 'SFFloat';
field348.Value := '1';
{ .AddField }
Script344.Field := field348;
field349 := TfieldNode.Create;
field349.NameField := 'MassProjectileWeight';
field349.AccessType := 'initializeOnly';
field349.Type := 'SFFloat';
field349.Value := '1';
{ .AddField }
Script344.Field := field349;
field350 := TfieldNode.Create;
field350.NameField := 'transparent';
field350.AccessType := 'outputOnly';
field350.Type := 'SFVec3f';
{ .AddField }
Script344.Field := field350;
field351 := TfieldNode.Create;
field351.NameField := 'value_changed';
field351.AccessType := 'outputOnly';
field351.Type := 'SFVec3f';
{ .AddField }
Script344.Field := field351;

Script344.SetSourceCode('''ecmascript:\n"+
"\n"+
"function initialize ()\n"+
"{\n"+
"	MassCounterWeight=100;\n"+
"	MassProjectileWeight=10;\n"+
"	Browser.println ('MassCounterWeight =' + MassCounterWeight);\n"+
"	Browser.println ('MassProjectileWeight =' + MassProjectileWeight);\n"+
"}\n"+
"\n"+
"function set_MassProjectileWeight (value, timestamp)\n"+
"{\n"+
"	MassProjectileWeight = value;\n"+
"	Browser.println ('new MassProjectileWeight =' + MassProjectileWeight);\n"+
"}\n"+
"function set_MassCounterWeight (value2, timestamp)\n"+
"{\n"+
"	MassCounterWeight = value2;\n"+
"	Browser.println ('new MassCounterWeight =' + MassCounterWeight);\n"+
"}\n"+
"\n"+
"\n"+
"function set_fraction ( fraction, eventTime )\n"+
"{\n"+
"	var TrebuchetHeight=45;\n"+
"	var Height =25;\n"+
"      	var x = (2*(MassCounterWeight/MassProjectileWeight)*Height*fraction)-.5*TrebuchetHeight;\n"+
"	// start at TrebuchetHeight and keep along z axis (z=zero)\n"+
"	var y =  (MassCounterWeight/MassProjectileWeight)*Height*Math.sin(fraction*3.14);\n"+
"        var z = 0;\n"+
"        transparent = new SFVec3f (1,1,1);\n"+
"     if (y <1.5*TrebuchetHeight  )if (x<TrebuchetHeight)\n"+
"		{\n"+
"		x=x-10;\n"+
"		y=y+1;\n"+
"		transparent = new SFVec3f(.01, .01, .01);\n"+
"			}\n"+
"\n"+
"	value_changed = new SFVec3f (x, y, z);\n"+
"	Browser.println ('x=' + value_changed[0] + ' y=' + value_changed[1] + ' z=' + value_changed[2]);\n"+
"}''');
{ .AddChildren }
Transform291.AddChildren([Script344]);
{ .AddChildren }
Transform104.AddChildren([Transform291]);
{ .AddChildren }
Group17.AddChildren([Transform104]);
TimeSensor352 := TTimeSensorNode.Create;
TimeSensor352.CycleInterval := 10;
{ .AddChildren }
Group17.AddChildren([TimeSensor352]);
PositionInterpolator353 := TPositionInterpolatorNode.Create;
PositionInterpolator353.SetKey([0,0.1,0.2,0.2,0.3,0.9]);
PositionInterpolator353.SetKeyValue([Vector3(1.4,1.6,0),Vector3(1,-8,0),Vector3(-3.5,-12,0),Vector3(-3.5,-12,0),Vector3(1.2,-8,0),Vector3(1.4,1.6,0)]);
{ .AddChildren }
Group17.AddChildren([PositionInterpolator353]);
OrientationInterpolator354 := TOrientationInterpolatorNode.Create;
OrientationInterpolator354.SetKey([0,0.1,0.2,0.2,0.3,0.9]);
OrientationInterpolator354.SetKeyValue([Vector4(0,0,1,0.82),Vector4(0,0,1,-0.77),Vector4(0,0,1,-1.57),Vector4(0,0,1,-1.57),Vector4(0,0,1,-0.77),Vector4(0,0,1,0.82)]);
{ .AddChildren }
Group17.AddChildren([OrientationInterpolator354]);
PositionInterpolator355 := TPositionInterpolatorNode.Create;
PositionInterpolator355.SetKey([0,0.01,0.95,1]);
PositionInterpolator355.SetKeyValue([Vector3(0,0,-3),Vector3(0,0,-10),Vector3(0,0,-10),Vector3(0,0,-3)]);
{ .AddChildren }
Group17.AddChildren([PositionInterpolator355]);
OrientationInterpolator356 := TOrientationInterpolatorNode.Create;
OrientationInterpolator356.SetKey([0,0.7,1]);
OrientationInterpolator356.SetKeyValue([Vector4(0,0,1,0),Vector4(0,0,1,-3.14),Vector4(0,0,1,0)]);
{ .AddChildren }
Group17.AddChildren([OrientationInterpolator356]);
PositionInterpolator357 := TPositionInterpolatorNode.Create;
PositionInterpolator357.SetKey([0,0.2,0.98,0.99]);
PositionInterpolator357.SetKeyValue([Vector3(1,1,1),Vector3(0.01,0.01,0.01),Vector3(0.01,0.01,0.01),Vector3(1,1,1)]);
{ .AddChildren }
Group17.AddChildren([PositionInterpolator357]);
Group17.AddRoute(TimeSensor352.EventFraction_changed, PositionInterpolator357.EventSet_fraction);
{ .AddX3DRoute }
Group17.AddRoute(PositionInterpolator357.EventValue_changed, Transform208.FdScale);
{ .AddX3DRoute }
Group17.AddRoute(Script333.FdCounterweight, Script344.EventSet_masscounterweight);
{ .AddX3DRoute }
Group17.AddRoute(Script337.FdProjectileweight, Script344.EventSet_massprojectileweight);
{ .AddX3DRoute }
Group17.AddRoute(TimeSensor352.EventFraction_changed, Script344.EventSet_fraction);
{ .AddX3DRoute }
Group17.AddRoute(Script344.EventValue_changed, Transform323.FdTranslation);
{ .AddX3DRoute }
Group17.AddRoute(Script344.FdTransparent, Transform323.FdScale);
{ .AddX3DRoute }
Group17.AddRoute(TouchSensor76.EventTouchtime, TimeSensor352.FdStarttime);
{ .AddX3DRoute }
Group17.AddRoute(TouchSensor76.FdIsactive, Script341.EventSet_boolean);
{ .AddX3DRoute }
Group17.AddRoute(TouchSensor76.EventTouchtime, AudioClip72.FdStarttime);
{ .AddX3DRoute }
Group17.AddRoute(TouchSensor76.EventTouchtime, AudioClip75.FdStarttime);
{ .AddX3DRoute }
Group17.AddRoute(Script341.FdWhichchoice, Switch69.FdWhichchoice);
{ .AddX3DRoute }
Group17.AddRoute(TouchSensor207.EventTouchtime, AudioClip85.FdStarttime);
{ .AddX3DRoute }
Group17.AddRoute(TouchSensor207.EventTouchtime, AudioClip92.FdStarttime);
{ .AddX3DRoute }
Group17.AddRoute(TouchSensor207.EventTouchtime, AudioClip99.FdStarttime);
{ .AddX3DRoute }
Group17.AddRoute(TouchSensor207.FdIsactive, Script337.EventSet_boolean);
{ .AddX3DRoute }
Group17.AddRoute(Script337.FdWhichchoice, Switch209.FdWhichchoice);
{ .AddX3DRoute }
Group17.AddRoute(Script337.FdWhichchoice, Switch78.FdWhichchoice);
{ .AddX3DRoute }
Group17.AddRoute(TouchSensor50.FdIsactive, Script333.EventSet_boolean);
{ .AddX3DRoute }
Group17.AddRoute(Script333.FdWhichchoice, Switch33.FdWhichchoice);
{ .AddX3DRoute }
Group17.AddRoute(TimeSensor352.EventFraction_changed, OrientationInterpolator354.EventSet_fraction);
{ .AddX3DRoute }
Group17.AddRoute(OrientationInterpolator354.EventValue_changed, Transform129.FdRotation);
{ .AddX3DRoute }
Group17.AddRoute(TimeSensor352.EventFraction_changed, PositionInterpolator353.EventSet_fraction);
{ .AddX3DRoute }
Group17.AddRoute(PositionInterpolator353.EventValue_changed, Transform227.FdTranslation);
{ .AddX3DRoute }
Group17.AddRoute(TimeSensor352.EventFraction_changed, PositionInterpolator355.EventSet_fraction);
{ .AddX3DRoute }
Group17.AddRoute(PositionInterpolator355.EventValue_changed, Transform256.FdTranslation);
{ .AddX3DRoute }
{ .AddGroup }
X3D0.AddChildren([Group17]);
Result := X3D0;
end;
