var initialFileData = [
            { name: "NavigationInfo type (With EXAMINE)", files: [
		"../data/AllenBox.x3dj",
		"../data/AllenDutton.x3dj",
		"../data/ball.x3dj",
		"../data/ballx3dom.x3dj",
		"../data/ballx_ite.x3dj",
		"../data/BoxEm.x3dj",
		"../data/BoxEm2.x3dj",
		"../data/bubble.x3dj",
		"../data/bubs.x3dj",
		"../data/bubs2.x3dj",
		"../data/bubs3.x3dj",
		"../data/bumpyfreewrljsonverse.x3dj",
		"../data/bumpyfreewrlsliders.x3dj",
		"../data/bumpyx_ite.x3dj",
		"../data/bumpyx_itesliders.x3dj",
		"../data/CameraPrototypes.x3dj",
		"../data/cgeparticleflowers.x3dj",
		"../data/fwparticleflowers.x3dj",
		"../data/gears.x3dj",
		"../data/geo.x3dj",
		"../data/indexedfaceset_pixeltexture_entire.x3d",
		"../data/indexedfaceset_pixeltexture_part.x3d",
		"../data/indexedfaceset_pixeltexture_plus.x3d",
		"../data/indexedfaceset_pixeltexture_whole.x3d",
		"../data/john.x3dj",
		"../data/john2.x3dj",
		"../data/john3.x3dj",
		"../data/jumpcut_loadurl.x3dj",
		"../data/Oxytocin.x3dj",
		"../data/particleballs.x3dj",
		"../data/particleflowers.x3dj",
		"../data/rgb_alpha.x3dj",
		"../data/rubik.x3dj",
		"../data/rubikFurnace.x3dj",
		"../data/rubikOnFire.x3dj",
		"../data/rubikPly.x3dj",
		"../data/SimpleShader.x3dj",
		"../data/ThreeDTexture.x3dj",
		"../data/variationalflowers.x3dj",
		"../data/variationalflowers2.x3dj",
		"../data/ViewFrustumExample.x3dj"
            ]},
            { name: "Personal Files (index3dom.html)", files: [
                "../personal/app.x3dj", "../personal/asmallbox.x3dj", "../personal/BoxEm.x3dj", "../personal/ifscubeworks.x3dj",
                "../personal/pp3.x3dj", "../personal/rubik.x3dj", "../personal/rubikFurnace.x3dj",
		"../personal/rubikOnFire.x3dj", "../data/rubikPly.x3dj",
                "../personal/app.x3d", "../personal/asmallbox.x3d", "../personal/BoxEm.x3d", "../personal/ifscubeworks.x3d",
                "../personal/pp3.x3d", "../personal/rubik.x3d", "../personal/rubikFurnace.x3d",
		"../personal/rubikOnFire.x3d", "../data/rubikPly.x3d"
            ]},
            { name: "STL Files (index3dom.html)", files: [
                "../stl/cleat_clamp.stl", "../stl/example.stl", "../stl/UavBeehive.stl"
            ]},
            { name: "PLY Files (index3dom.html)", files: [
                "../ply/Dodecahedron.ply", "../ply/example.ply", "../ply/Icosahedron.ply",
                "../ply/IcosahedronSubdivisionLevel1.ply", "../ply/IcosahedronSubdivisionLevel2.ply",
                "../ply/IcosahedronSubdivisionLevel3.ply", "../ply/IcosahedronSubdivisionLevel4.ply",
                "../ply/IcosahedronSubdivisionLevel5.ply", "../ply/Octahedron.ply",
                "../ply/OrigamiCrane.ply", "../ply/Tetrahedron.ply", "../ply/mobius.ply"
            ]},
            { name: "General Data (three.html / index.html)", files: [
                "../data/mobius.x3dj", "../data/AllenDutton.x3dj", "../data/AllenBox.x3dj",
		"../data/app.x3dj", "../data/arc.x3dj",
                "../data/sphereflowers.x3dj",
                "../data/arc2.x3d", "../data/ArchHalf.x3d", "../data/browser.x3d",
                "../data/bubbles.x3d", "../data/bubble.x3d",
                "../data/flower.x3d", "../data/flower3.x3d", "../data/flowers4.x3d", "../data/flowers7.x3d",
                "../data/geobubbles.x3d", "../data/mirror.x3d", "../data/mirror2.x3d", "../data/MyBounce.x3d",
		"../data/ObliqueStrategies.x3d", "../data/TextExamples.x3dj"
            ]},
            { name: "X3D Examples Viewer (X3DExamplesViewer.html)", files: [
                "../data/force.x3dj",
		"../data/SuperCobraLightsOn.x3dj"
            ]},
            { name: "Proto Examples (proto.html)", files: [
		"../data/ArtDecoExamples.x3dj",
		"../data/ArtDecoPrototypes.x3dj",
		"../data/asmallbox.x3dj",
		"../data/bub.x3dj",
		"../data/bubble.x3dj",
		"../data/bubs.x3dj",
		"../data/bubs2.x3dj",
		"../data/flowers.x3dj",
		"../data/flowers2.x3dj",
		"../data/force.x3dj",
		"../data/forcenode.x3dj",
		"../data/force_tidy.x3dj",
		"../data/fors.x3dj",
		"../data/fors2.x3dj",
		"../data/qq3.x3dj",
		"../data/x3dconnector.x3dj",
		"../data/x3dconnectorProto.x3dj",
		"../data/x3domflowers.x3dj"
            ]}
        ];
export default initialFileData;
