#!/bin/bash
# Window defines this, use ${USERNAME:....} something instead
export HOMESFOLDER=C:/Users
export USERNAME=jcarl

export X3DJSONLD=${HOMESFOLDER}/$USERNAME/X3DJSONLD
export GRAALX3DJSONLD=${HOMESFOLDER}/$USERNAME/X3DJSONLD
export CLASSPATH=".;${X3DJSONLD}/src/main/java;${X3DJSONLD}/saxon-he-12.4.jar;${X3DJSONLD}/target/X3DJSONLD-1.0-SNAPSHOT.jar;${X3DJSONLD}/target/classes;${X3DJSONLD}/src/main/java;../java;${HOMESFOLDER}/$USERNAME/pythonSAI/X3DJSAIL.4.0.full.jar;${HOMESFOLDER}/$USERNAME/pythonSAI/xmlresolver-5.1.1.jar;${HOMESFOLDER}/$USERNAME/pythonSAI/xmlresolver-5.1.1-data.jar"

# GRAAL DOES NOT TAKE C:
export GRAAL_CLASSPATH=".;${GRAALX3DJSONLD}/saxon-he-12.4.jar;${GRAALX3DJSONLD}/target/X3DJSONLD-1.0-SNAPSHOT.jar;${GRAALX3DJSONLD}/src/main/graaljs;../java;${HOMESFOLDER}/$USERNAME/pythonSAI/X3DJSAIL.4.0.full.jar;${HOMESFOLDER}/$USERNAME/pythonSAI/xmlresolver-5.1.1.jar;${HOMESFOLDER}/$USERNAME/pythonSAI/xmlresolver-5.1.1-data.jar"
export PYTHONPATH="${PYTHONPATH-"."}:net/coderextreme/data:net/coderextreme/personal"
export PATH="${JAVA_HOME}/bin;${JAVA_HOME}/jre/bin/server;${PATH}"

export PYTHON=graalpy
alias python='${PYTHON} --jvm'
source ${X3DJSONLD}/src/main/python/venv/Scripts/activate
export PIP=pip3
export NODE=node.exe
export NODEDIR=${HOMESFOLDER}/$USERNAME/X3DJSONLD/src/main/node
# ${HOME}\\apache-maven-3.5.2\\bin\\mvn clean install
# sh replaceclass.sh
# ${HOME}\\apache-maven-3.5.2\\bin\\mvn install

function jjs() {
	# C:/graalvm-jdk-20_windows-x64_bin/graalvm-jdk-20.0.2+9.1/bin/js.cmd "$@"
	# C:/graaljs-community-jvm-23.1.2-windows-amd64/graaljs-community-23.1.2-windows-amd64/bin/js.exe --experimental-options --polyglot --vm.Djs.allowAllAccess=true --vm.Xss1g --vm.Xmx4g --jvm --vm.classpath="${GRAAL_CLASSPATH}" "$@"
	C:/graaljs-community-jvm-24.0.0-windows-amd64/graaljs-community-24.0.0-windows-amd64/bin/js.exe --experimental-options --polyglot --vm.Djs.allowAllAccess=true --vm.Xss1g --vm.Xmx4g --jvm --vm.classpath="${GRAAL_CLASSPATH}" "$@"

}

