#!/bin/bash
# Window defines this, use ${USERNAME:....} something instead
export USERNAME=coderextreme

export X3DJSONLD=/home/$USERNAME/X3DJSONLD
export NASHORNX3DJSONLD=/home/$USERNAME/X3DJSONLD
export CLASSPATH=".:/home/$USERNAME/pythonSAI/X3DJSAIL.4.0.full.jar:${X3DJSONLD}/saxon9he.jar:${X3DJSONLD}/target/X3DJSONLD-1.0-SNAPSHOT.jar:${X3DJSONLD}/target/classes:${X3DJSONLD}/src/main/java"
# NASHORN DOES NOT TAKE C:
export NASHORN_CLASSPATH=".:/home/$USERNAME/pythonSAI/X3DJSAIL.4.0.full.jar:${NASHORNX3DJSONLD}/saxon9he.jar:${NASHORNX3DJSONLD}/target/X3DJSONLD-1.0-SNAPSHOT.jar:${NASHORNX3DJSONLD}/src/main/nashorn"
export PYTHONPATH=/usr/bin:/c/Python27:/c/Python27/Scripts
export PATH="${PYTHONPATH}:${JAVA_HOME}/bin:${JAVA_HOME}/jre/bin/server:/home/coderextreme/Downloads/graalvm-ce-java11-windows-amd64-20.3.0/graalvm-ce-java11-20.3.0/bin/:${PATH}"

export PYTHON=python
export PIP=pip3
export NODE=node
export NODEDIR=/home/$USERNAME/X3DJSONLD/src/main/node
# ${HOME}\\apache-maven-3.5.2\\bin\\mvn clean install
# sh replaceclass.sh
# ${HOME}\\apache-maven-3.5.2\\bin\\mvn install
