#!/bin/bash
export PYTHONSAI=/Users/coderextreme/pythonSAI
export X3DJSONLD=/Users/coderextreme/X3DJSONLD
export CLASSPATH=".;${PYTHONSAI}/X3DJSAIL.3.3.classes.jar;${PYTHONSAI}/saxon9he.jar;${X3DJSONLD}/target/X3DJSONLD-1.0-SNAPSHOT.jar"
# NASHORN DOES NOT TAKE C:
export NASHORN_CLASSPATH="${CLASSPATH};${X3DJSONLD}/src/main/nashorn"
export PYTHONPATH=/usr/bin:/c/Python27:/c/Python27/Scripts
export PATH="${PYTHONPATH};${JAVA_HOME}/bin;${JAVA_HOME}/jre/bin/server;${PATH}"
export PYTHON=python.exe
export PIP=pip.exe
export NODE=node.exe
export NODEDIR=/c/Users/coderextreme/X3DJSONLD/src/main/node
# ${HOME}\\apache-maven-3.5.0\\bin\\mvn clean install
# sh replaceclass.sh
# ${HOME}\\apache-maven-3.5.0\\bin\\mvn install
