print('<!--')
import x3d
print('-->')
X3D0 = x3d.X3D()
X3D0.profile = "Immersive"
X3D0.version = "4.0"
head1 = x3d.head()
meta2 = x3d.meta()
meta2.name = "title"
meta2.content = "Oxytocin.x3d"

head1.children.append(meta2)
meta3 = x3d.meta()
meta3.name = "description"
meta3.content = "Autogenerated version of Oxytocin.x3d scene produced from Oxytocin.xml Chemical Markup Language (CML) version 1.0 source file."

head1.children.append(meta3)
meta4 = x3d.meta()
meta4.name = "creator"
meta4.content = "Nicholas F. Polys"

head1.children.append(meta4)
meta5 = x3d.meta()
meta5.name = "translator"
meta5.content = "Don Brutzman"

head1.children.append(meta5)
meta6 = x3d.meta()
meta6.name = "created"
meta6.content = "24 November 2005"

head1.children.append(meta6)
meta7 = x3d.meta()
meta7.name = "translated"
meta7.content = "2 JAN 2025"

head1.children.append(meta7)
meta8 = x3d.meta()
meta8.name = "modified"
meta8.content = "2 JAN 2025"

head1.children.append(meta8)
meta9 = x3d.meta()
meta9.name = "reference"
meta9.content = "Oxytocin.xml"

head1.children.append(meta9)
meta10 = x3d.meta()
meta10.name = "reference"
meta10.content = "CML sources https://www.xml-cml.org"

head1.children.append(meta10)
meta11 = x3d.meta()
meta11.name = "reference"
meta11.content = "Wikipedia https://en.wikipedia.org/wiki/Chemical_Markup_Language"

head1.children.append(meta11)
meta12 = x3d.meta()
meta12.name = "reference"
meta12.content = "JUMBO Chemical Format Conversion Tool"

head1.children.append(meta12)
meta13 = x3d.meta()
meta13.name = "reference"
meta13.content = "https://webbook.nist.gov/chemistry"

head1.children.append(meta13)
meta14 = x3d.meta()
meta14.name = "reference"
meta14.content = "Polys.StylesheetTransformationsInteractiveVisualization.Web3d2003Symposium.pdf"

head1.children.append(meta14)
meta15 = x3d.meta()
meta15.name = "reference"
meta15.content = "Originally Published in Proceedings of Web3D 2003, ACM Press"

head1.children.append(meta15)
meta16 = x3d.meta()
meta16.name = "generator"
meta16.content = "CmlToX3d.xslt"

head1.children.append(meta16)
meta17 = x3d.meta()
meta17.name = "identifier"
meta17.content = "https://www.web3d.org/x3d/content/examples/Basic/ChemicalMarkupLanguage/Oxytocin.x3d"

head1.children.append(meta17)
meta18 = x3d.meta()
meta18.name = "license"
meta18.content = "../license.html"

head1.children.append(meta18)

X3D0.head = head1
Scene19 = x3d.Scene()
ProtoDeclare20 = x3d.ProtoDeclare()
ProtoDeclare20.name = "Carbon"
ProtoInterface21 = x3d.ProtoInterface()
field22 = x3d.field()
field22.name = "position"
field22.accessType = "inputOutput"
field22.type = "SFVec3f"
field22.value = [0,0,0]

ProtoInterface21.field.append(field22)
field23 = x3d.field()
field23.name = "materialTransparency"
field23.accessType = "inputOutput"
field23.type = "SFFloat"
field23.value = 0.6

ProtoInterface21.field.append(field23)

ProtoDeclare20.ProtoInterface = ProtoInterface21
ProtoBody24 = x3d.ProtoBody()
Group25 = x3d.Group()
Transform26 = x3d.Transform(DEF="atoC")
IS27 = x3d.IS()
connect28 = x3d.connect()
connect28.nodeField = "translation"
connect28.protoField = "position"

IS27.connect.append(connect28)

Transform26.IS = IS27
Shape29 = x3d.Shape()
Appearance30 = x3d.Appearance()
Material31 = x3d.Material(DEF="atoC_mat")
Material31.diffuseColor = [0,0,0]
Material31.shininess = 0.8
Material31.specularColor = [0.29,0.3,0.29]
IS32 = x3d.IS()
connect33 = x3d.connect()
connect33.nodeField = "transparency"
connect33.protoField = "materialTransparency"

IS32.connect.append(connect33)

Material31.IS = IS32

Appearance30.material = Material31

Shape29.appearance = Appearance30
Sphere34 = x3d.Sphere()
Sphere34.radius = 0.77

Shape29.geometry = Sphere34

Transform26.children.append(Shape29)
Shape35 = x3d.Shape()
Appearance36 = x3d.Appearance()
Material37 = x3d.Material()
Material37.diffuseColor = [0.9,0.9,0.9]

Appearance36.material = Material37

Shape35.appearance = Appearance36
Text38 = x3d.Text()
Text38.string = ["C"]
FontStyle39 = x3d.FontStyle()
FontStyle39.size = 0.8

Text38.fontStyle = FontStyle39

Shape35.geometry = Text38

Transform26.children.append(Shape35)

Group25.children.append(Transform26)

ProtoBody24.children.append(Group25)

ProtoDeclare20.ProtoBody = ProtoBody24

Scene19.children.append(ProtoDeclare20)
ProtoDeclare40 = x3d.ProtoDeclare()
ProtoDeclare40.name = "Hydrogen"
ProtoInterface41 = x3d.ProtoInterface()
field42 = x3d.field()
field42.name = "position"
field42.accessType = "inputOutput"
field42.type = "SFVec3f"
field42.value = [0,0,0]

ProtoInterface41.field.append(field42)
field43 = x3d.field()
field43.name = "materialTransparency"
field43.accessType = "inputOutput"
field43.type = "SFFloat"
field43.value = 0.6

ProtoInterface41.field.append(field43)

ProtoDeclare40.ProtoInterface = ProtoInterface41
ProtoBody44 = x3d.ProtoBody()
Group45 = x3d.Group()
Transform46 = x3d.Transform(DEF="atoH")
IS47 = x3d.IS()
connect48 = x3d.connect()
connect48.nodeField = "translation"
connect48.protoField = "position"

IS47.connect.append(connect48)

Transform46.IS = IS47
Shape49 = x3d.Shape()
Appearance50 = x3d.Appearance()
Material51 = x3d.Material(DEF="atoH_mat")
Material51.ambientIntensity = 0.0933
Material51.diffuseColor = [0.38,0.38,0.42]
Material51.shininess = 0.5
Material51.specularColor = [0.53,0.53,0.53]
IS52 = x3d.IS()
connect53 = x3d.connect()
connect53.nodeField = "transparency"
connect53.protoField = "materialTransparency"

IS52.connect.append(connect53)

Material51.IS = IS52

Appearance50.material = Material51

Shape49.appearance = Appearance50
Sphere54 = x3d.Sphere()
Sphere54.radius = 0.32

Shape49.geometry = Sphere54

Transform46.children.append(Shape49)
Shape55 = x3d.Shape()
Appearance56 = x3d.Appearance()
Material57 = x3d.Material()
Material57.diffuseColor = [0.9,0.9,0.9]

Appearance56.material = Material57

Shape55.appearance = Appearance56
Text58 = x3d.Text()
Text58.string = ["H"]
FontStyle59 = x3d.FontStyle()
FontStyle59.size = 0.4

Text58.fontStyle = FontStyle59

Shape55.geometry = Text58

Transform46.children.append(Shape55)

Group45.children.append(Transform46)

ProtoBody44.children.append(Group45)

ProtoDeclare40.ProtoBody = ProtoBody44

Scene19.children.append(ProtoDeclare40)
ProtoDeclare60 = x3d.ProtoDeclare()
ProtoDeclare60.name = "Nitrogen"
ProtoInterface61 = x3d.ProtoInterface()
field62 = x3d.field()
field62.name = "position"
field62.accessType = "inputOutput"
field62.type = "SFVec3f"
field62.value = [0,0,0]

ProtoInterface61.field.append(field62)
field63 = x3d.field()
field63.name = "materialTransparency"
field63.accessType = "inputOutput"
field63.type = "SFFloat"
field63.value = 0.6

ProtoInterface61.field.append(field63)

ProtoDeclare60.ProtoInterface = ProtoInterface61
ProtoBody64 = x3d.ProtoBody()
Group65 = x3d.Group()
Transform66 = x3d.Transform(DEF="atoN")
IS67 = x3d.IS()
connect68 = x3d.connect()
connect68.nodeField = "translation"
connect68.protoField = "position"

IS67.connect.append(connect68)

Transform66.IS = IS67
Shape69 = x3d.Shape()
Appearance70 = x3d.Appearance()
Material71 = x3d.Material(DEF="atoN_mat")
Material71.diffuseColor = [0,0,0.72]
Material71.emissiveColor = [0,0,0.13]
Material71.specularColor = [0.5,0.5,0.5]
IS72 = x3d.IS()
connect73 = x3d.connect()
connect73.nodeField = "transparency"
connect73.protoField = "materialTransparency"

IS72.connect.append(connect73)

Material71.IS = IS72

Appearance70.material = Material71

Shape69.appearance = Appearance70
Sphere74 = x3d.Sphere()
Sphere74.radius = 0.75

Shape69.geometry = Sphere74

Transform66.children.append(Shape69)
Shape75 = x3d.Shape()
Appearance76 = x3d.Appearance()
Material77 = x3d.Material()
Material77.diffuseColor = [0.9,0.9,0.9]

Appearance76.material = Material77

Shape75.appearance = Appearance76
Text78 = x3d.Text()
Text78.string = ["N"]
FontStyle79 = x3d.FontStyle()
FontStyle79.size = 0.8

Text78.fontStyle = FontStyle79

Shape75.geometry = Text78

Transform66.children.append(Shape75)

Group65.children.append(Transform66)

ProtoBody64.children.append(Group65)

ProtoDeclare60.ProtoBody = ProtoBody64

Scene19.children.append(ProtoDeclare60)
ProtoDeclare80 = x3d.ProtoDeclare()
ProtoDeclare80.name = "Oxygen"
ProtoInterface81 = x3d.ProtoInterface()
field82 = x3d.field()
field82.name = "position"
field82.accessType = "inputOutput"
field82.type = "SFVec3f"
field82.value = [0,0,0]

ProtoInterface81.field.append(field82)
field83 = x3d.field()
field83.name = "materialTransparency"
field83.accessType = "inputOutput"
field83.type = "SFFloat"
field83.value = 0.6

ProtoInterface81.field.append(field83)

ProtoDeclare80.ProtoInterface = ProtoInterface81
ProtoBody84 = x3d.ProtoBody()
Group85 = x3d.Group()
Transform86 = x3d.Transform(DEF="atoO")
IS87 = x3d.IS()
connect88 = x3d.connect()
connect88.nodeField = "translation"
connect88.protoField = "position"

IS87.connect.append(connect88)

Transform86.IS = IS87
Shape89 = x3d.Shape()
Appearance90 = x3d.Appearance()
Material91 = x3d.Material(DEF="atoO_mat")
Material91.ambientIntensity = 0.487
Material91.diffuseColor = [0.54,0.05,0.25]
Material91.shininess = 0.2
Material91.specularColor = [0.81,0.77,0.75]
IS92 = x3d.IS()
connect93 = x3d.connect()
connect93.nodeField = "transparency"
connect93.protoField = "materialTransparency"

IS92.connect.append(connect93)

Material91.IS = IS92

Appearance90.material = Material91

Shape89.appearance = Appearance90
Sphere94 = x3d.Sphere()
Sphere94.radius = 0.73

Shape89.geometry = Sphere94

Transform86.children.append(Shape89)
Shape95 = x3d.Shape()
Appearance96 = x3d.Appearance()
Material97 = x3d.Material()
Material97.diffuseColor = [0.9,0.9,0.9]

Appearance96.material = Material97

Shape95.appearance = Appearance96
Text98 = x3d.Text()
Text98.string = ["O"]
FontStyle99 = x3d.FontStyle()
FontStyle99.size = 0.8

Text98.fontStyle = FontStyle99

Shape95.geometry = Text98

Transform86.children.append(Shape95)

Group85.children.append(Transform86)

ProtoBody84.children.append(Group85)

ProtoDeclare80.ProtoBody = ProtoBody84

Scene19.children.append(ProtoDeclare80)
ProtoDeclare100 = x3d.ProtoDeclare()
ProtoDeclare100.name = "Fluorine"
ProtoInterface101 = x3d.ProtoInterface()
field102 = x3d.field()
field102.name = "position"
field102.accessType = "inputOutput"
field102.type = "SFVec3f"
field102.value = [0,0,0]

ProtoInterface101.field.append(field102)
field103 = x3d.field()
field103.name = "materialTransparency"
field103.accessType = "inputOutput"
field103.type = "SFFloat"
field103.value = 0.6

ProtoInterface101.field.append(field103)

ProtoDeclare100.ProtoInterface = ProtoInterface101
ProtoBody104 = x3d.ProtoBody()
Group105 = x3d.Group()
Transform106 = x3d.Transform(DEF="atoF")
IS107 = x3d.IS()
connect108 = x3d.connect()
connect108.nodeField = "translation"
connect108.protoField = "position"

IS107.connect.append(connect108)

Transform106.IS = IS107
Shape109 = x3d.Shape()
Appearance110 = x3d.Appearance()
Material111 = x3d.Material(DEF="atoF_mat")
Material111.diffuseColor = [1,0.48,0.79]
Material111.emissiveColor = [0.09,0.04,0.07]
IS112 = x3d.IS()
connect113 = x3d.connect()
connect113.nodeField = "transparency"
connect113.protoField = "materialTransparency"

IS112.connect.append(connect113)

Material111.IS = IS112

Appearance110.material = Material111

Shape109.appearance = Appearance110
Sphere114 = x3d.Sphere()
Sphere114.radius = 0.72

Shape109.geometry = Sphere114

Transform106.children.append(Shape109)
Shape115 = x3d.Shape()
Appearance116 = x3d.Appearance()
Material117 = x3d.Material()
Material117.diffuseColor = [0.9,0.9,0.9]

Appearance116.material = Material117

Shape115.appearance = Appearance116
Text118 = x3d.Text()
Text118.string = ["F"]
FontStyle119 = x3d.FontStyle()
FontStyle119.size = 0.8

Text118.fontStyle = FontStyle119

Shape115.geometry = Text118

Transform106.children.append(Shape115)

Group105.children.append(Transform106)

ProtoBody104.children.append(Group105)

ProtoDeclare100.ProtoBody = ProtoBody104

Scene19.children.append(ProtoDeclare100)
ProtoDeclare120 = x3d.ProtoDeclare()
ProtoDeclare120.name = "Silicon"
ProtoInterface121 = x3d.ProtoInterface()
field122 = x3d.field()
field122.name = "position"
field122.accessType = "inputOutput"
field122.type = "SFVec3f"
field122.value = [0,0,0]

ProtoInterface121.field.append(field122)
field123 = x3d.field()
field123.name = "materialTransparency"
field123.accessType = "inputOutput"
field123.type = "SFFloat"
field123.value = 0.6

ProtoInterface121.field.append(field123)

ProtoDeclare120.ProtoInterface = ProtoInterface121
ProtoBody124 = x3d.ProtoBody()
Group125 = x3d.Group()
Transform126 = x3d.Transform(DEF="atoSi")
IS127 = x3d.IS()
connect128 = x3d.connect()
connect128.nodeField = "translation"
connect128.protoField = "position"

IS127.connect.append(connect128)

Transform126.IS = IS127
Shape129 = x3d.Shape()
Appearance130 = x3d.Appearance()
Material131 = x3d.Material(DEF="atoSi_mat")
Material131.diffuseColor = [0.8,0.8,0.8]
IS132 = x3d.IS()
connect133 = x3d.connect()
connect133.nodeField = "transparency"
connect133.protoField = "materialTransparency"

IS132.connect.append(connect133)

Material131.IS = IS132

Appearance130.material = Material131

Shape129.appearance = Appearance130
Sphere134 = x3d.Sphere()
Sphere134.radius = 1.18

Shape129.geometry = Sphere134

Transform126.children.append(Shape129)
Shape135 = x3d.Shape()
Appearance136 = x3d.Appearance()
Material137 = x3d.Material()
Material137.diffuseColor = [0.9,0.9,0.9]

Appearance136.material = Material137

Shape135.appearance = Appearance136
Text138 = x3d.Text()
Text138.string = ["Si"]
FontStyle139 = x3d.FontStyle()
FontStyle139.size = 0.8

Text138.fontStyle = FontStyle139

Shape135.geometry = Text138

Transform126.children.append(Shape135)

Group125.children.append(Transform126)

ProtoBody124.children.append(Group125)

ProtoDeclare120.ProtoBody = ProtoBody124

Scene19.children.append(ProtoDeclare120)
ProtoDeclare140 = x3d.ProtoDeclare()
ProtoDeclare140.name = "Phosphorus"
ProtoInterface141 = x3d.ProtoInterface()
field142 = x3d.field()
field142.name = "position"
field142.accessType = "inputOutput"
field142.type = "SFVec3f"
field142.value = [0,0,0]

ProtoInterface141.field.append(field142)
field143 = x3d.field()
field143.name = "materialTransparency"
field143.accessType = "inputOutput"
field143.type = "SFFloat"
field143.value = 0.6

ProtoInterface141.field.append(field143)

ProtoDeclare140.ProtoInterface = ProtoInterface141
ProtoBody144 = x3d.ProtoBody()
Group145 = x3d.Group()
Transform146 = x3d.Transform(DEF="atoP")
IS147 = x3d.IS()
connect148 = x3d.connect()
connect148.nodeField = "translation"
connect148.protoField = "position"

IS147.connect.append(connect148)

Transform146.IS = IS147
Shape149 = x3d.Shape()
Appearance150 = x3d.Appearance()
Material151 = x3d.Material(DEF="atoP_mat")
Material151.ambientIntensity = 0.11
Material151.diffuseColor = [0.9,0.41,0]
Material151.emissiveColor = [0.1,0.04,0]
Material151.shininess = 0.8
Material151.specularColor = [0.1,0.1,0.1]
IS152 = x3d.IS()
connect153 = x3d.connect()
connect153.nodeField = "transparency"
connect153.protoField = "materialTransparency"

IS152.connect.append(connect153)

Material151.IS = IS152

Appearance150.material = Material151

Shape149.appearance = Appearance150
Sphere154 = x3d.Sphere()
Sphere154.radius = 1.1

Shape149.geometry = Sphere154

Transform146.children.append(Shape149)
Shape155 = x3d.Shape()
Appearance156 = x3d.Appearance()
Material157 = x3d.Material()
Material157.diffuseColor = [0.9,0.9,0.9]

Appearance156.material = Material157

Shape155.appearance = Appearance156
Text158 = x3d.Text()
Text158.string = ["P"]
FontStyle159 = x3d.FontStyle()
FontStyle159.size = 0.8

Text158.fontStyle = FontStyle159

Shape155.geometry = Text158

Transform146.children.append(Shape155)

Group145.children.append(Transform146)

ProtoBody144.children.append(Group145)

ProtoDeclare140.ProtoBody = ProtoBody144

Scene19.children.append(ProtoDeclare140)
ProtoDeclare160 = x3d.ProtoDeclare()
ProtoDeclare160.name = "Sulphur"
ProtoInterface161 = x3d.ProtoInterface()
field162 = x3d.field()
field162.name = "position"
field162.accessType = "inputOutput"
field162.type = "SFVec3f"
field162.value = [0,0,0]

ProtoInterface161.field.append(field162)
field163 = x3d.field()
field163.name = "materialTransparency"
field163.accessType = "inputOutput"
field163.type = "SFFloat"
field163.value = 0.6

ProtoInterface161.field.append(field163)

ProtoDeclare160.ProtoInterface = ProtoInterface161
ProtoBody164 = x3d.ProtoBody()
Group165 = x3d.Group()
Transform166 = x3d.Transform(DEF="atoS")
IS167 = x3d.IS()
connect168 = x3d.connect()
connect168.nodeField = "translation"
connect168.protoField = "position"

IS167.connect.append(connect168)

Transform166.IS = IS167
Shape169 = x3d.Shape()
Appearance170 = x3d.Appearance()
Material171 = x3d.Material(DEF="atoS_mat")
Material171.ambientIntensity = 0.0467
Material171.diffuseColor = [0.25,0.39,0.25]
Material171.emissiveColor = [0.05,0.08,0.05]
Material171.shininess = 0.6
Material171.specularColor = [0.11,0.12,0.08]
IS172 = x3d.IS()
connect173 = x3d.connect()
connect173.nodeField = "transparency"
connect173.protoField = "materialTransparency"

IS172.connect.append(connect173)

Material171.IS = IS172

Appearance170.material = Material171

Shape169.appearance = Appearance170
Sphere174 = x3d.Sphere()
Sphere174.radius = 1.3

Shape169.geometry = Sphere174

Transform166.children.append(Shape169)
Shape175 = x3d.Shape()
Appearance176 = x3d.Appearance()
Material177 = x3d.Material()
Material177.diffuseColor = [0.9,0.9,0.9]

Appearance176.material = Material177

Shape175.appearance = Appearance176
Text178 = x3d.Text()
Text178.string = ["S"]
FontStyle179 = x3d.FontStyle()
FontStyle179.size = 0.8

Text178.fontStyle = FontStyle179

Shape175.geometry = Text178

Transform166.children.append(Shape175)

Group165.children.append(Transform166)

ProtoBody164.children.append(Group165)

ProtoDeclare160.ProtoBody = ProtoBody164

Scene19.children.append(ProtoDeclare160)
ProtoDeclare180 = x3d.ProtoDeclare()
ProtoDeclare180.name = "Chlorine"
ProtoInterface181 = x3d.ProtoInterface()
field182 = x3d.field()
field182.name = "position"
field182.accessType = "inputOutput"
field182.type = "SFVec3f"
field182.value = [0,0,0]

ProtoInterface181.field.append(field182)
field183 = x3d.field()
field183.name = "materialTransparency"
field183.accessType = "inputOutput"
field183.type = "SFFloat"
field183.value = 0.6

ProtoInterface181.field.append(field183)

ProtoDeclare180.ProtoInterface = ProtoInterface181
ProtoBody184 = x3d.ProtoBody()
Group185 = x3d.Group()
Transform186 = x3d.Transform(DEF="atoCl")
IS187 = x3d.IS()
connect188 = x3d.connect()
connect188.nodeField = "translation"
connect188.protoField = "position"

IS187.connect.append(connect188)

Transform186.IS = IS187
Shape189 = x3d.Shape()
Appearance190 = x3d.Appearance()
Material191 = x3d.Material(DEF="atoCl_mat")
Material191.diffuseColor = [0.28,0.7,0]
Material191.emissiveColor = [0.06,0.15,0]
Material191.shininess = 0.8
Material191.specularColor = [0.5,0.5,0.5]
IS192 = x3d.IS()
connect193 = x3d.connect()
connect193.nodeField = "transparency"
connect193.protoField = "materialTransparency"

IS192.connect.append(connect193)

Material191.IS = IS192

Appearance190.material = Material191

Shape189.appearance = Appearance190
Sphere194 = x3d.Sphere()
Sphere194.radius = 1.01

Shape189.geometry = Sphere194

Transform186.children.append(Shape189)
Shape195 = x3d.Shape()
Appearance196 = x3d.Appearance()
Material197 = x3d.Material()
Material197.diffuseColor = [0.9,0.9,0.9]

Appearance196.material = Material197

Shape195.appearance = Appearance196
Text198 = x3d.Text()
Text198.string = ["Cl"]
FontStyle199 = x3d.FontStyle()
FontStyle199.size = 0.8

Text198.fontStyle = FontStyle199

Shape195.geometry = Text198

Transform186.children.append(Shape195)

Group185.children.append(Transform186)

ProtoBody184.children.append(Group185)

ProtoDeclare180.ProtoBody = ProtoBody184

Scene19.children.append(ProtoDeclare180)
ProtoDeclare200 = x3d.ProtoDeclare()
ProtoDeclare200.name = "Bromine"
ProtoInterface201 = x3d.ProtoInterface()
field202 = x3d.field()
field202.name = "position"
field202.accessType = "inputOutput"
field202.type = "SFVec3f"
field202.value = [0,0,0]

ProtoInterface201.field.append(field202)
field203 = x3d.field()
field203.name = "materialTransparency"
field203.accessType = "inputOutput"
field203.type = "SFFloat"
field203.value = 0.6

ProtoInterface201.field.append(field203)

ProtoDeclare200.ProtoInterface = ProtoInterface201
ProtoBody204 = x3d.ProtoBody()
Group205 = x3d.Group()
Transform206 = x3d.Transform(DEF="atoBr")
IS207 = x3d.IS()
connect208 = x3d.connect()
connect208.nodeField = "translation"
connect208.protoField = "position"

IS207.connect.append(connect208)

Transform206.IS = IS207
Shape209 = x3d.Shape()
Appearance210 = x3d.Appearance()
Material211 = x3d.Material(DEF="atoBr_mat")
Material211.ambientIntensity = 0.0833
Material211.diffuseColor = [0.5,0.3,0.19]
Material211.emissiveColor = [0.12,0.13,0.08]
Material211.shininess = 0.17
Material211.specularColor = [0.08,0.08,0.05]
IS212 = x3d.IS()
connect213 = x3d.connect()
connect213.nodeField = "transparency"
connect213.protoField = "materialTransparency"

IS212.connect.append(connect213)

Material211.IS = IS212

Appearance210.material = Material211

Shape209.appearance = Appearance210
Sphere214 = x3d.Sphere()
Sphere214.radius = 1.14

Shape209.geometry = Sphere214

Transform206.children.append(Shape209)
Shape215 = x3d.Shape()
Appearance216 = x3d.Appearance()
Material217 = x3d.Material()
Material217.diffuseColor = [0.9,0.9,0.9]

Appearance216.material = Material217

Shape215.appearance = Appearance216
Text218 = x3d.Text()
Text218.string = ["Br"]
FontStyle219 = x3d.FontStyle()
FontStyle219.size = 0.8

Text218.fontStyle = FontStyle219

Shape215.geometry = Text218

Transform206.children.append(Shape215)

Group205.children.append(Transform206)

ProtoBody204.children.append(Group205)

ProtoDeclare200.ProtoBody = ProtoBody204

Scene19.children.append(ProtoDeclare200)
ProtoDeclare220 = x3d.ProtoDeclare()
ProtoDeclare220.name = "Iodine"
ProtoInterface221 = x3d.ProtoInterface()
field222 = x3d.field()
field222.name = "position"
field222.accessType = "inputOutput"
field222.type = "SFVec3f"
field222.value = [0,0,0]

ProtoInterface221.field.append(field222)
field223 = x3d.field()
field223.name = "materialTransparency"
field223.accessType = "inputOutput"
field223.type = "SFFloat"
field223.value = 0.6

ProtoInterface221.field.append(field223)

ProtoDeclare220.ProtoInterface = ProtoInterface221
ProtoBody224 = x3d.ProtoBody()
Group225 = x3d.Group()
Transform226 = x3d.Transform(DEF="atoI")
IS227 = x3d.IS()
connect228 = x3d.connect()
connect228.nodeField = "translation"
connect228.protoField = "position"

IS227.connect.append(connect228)

Transform226.IS = IS227
Shape229 = x3d.Shape()
Appearance230 = x3d.Appearance()
Material231 = x3d.Material(DEF="atoI_mat")
Material231.diffuseColor = [0.56,0.37,0.74]
Material231.emissiveColor = [0.15,0.1,0.2]
Material231.shininess = 0.09
Material231.specularColor = [0.12,0.12,0.12]
IS232 = x3d.IS()
connect233 = x3d.connect()
connect233.nodeField = "transparency"
connect233.protoField = "materialTransparency"

IS232.connect.append(connect233)

Material231.IS = IS232

Appearance230.material = Material231

Shape229.appearance = Appearance230
Sphere234 = x3d.Sphere()
Sphere234.radius = 1.33

Shape229.geometry = Sphere234

Transform226.children.append(Shape229)
Shape235 = x3d.Shape()
Appearance236 = x3d.Appearance()
Material237 = x3d.Material()
Material237.diffuseColor = [0.9,0.9,0.9]

Appearance236.material = Material237

Shape235.appearance = Appearance236
Text238 = x3d.Text()
Text238.string = ["I"]
FontStyle239 = x3d.FontStyle()
FontStyle239.size = 0.8

Text238.fontStyle = FontStyle239

Shape235.geometry = Text238

Transform226.children.append(Shape235)

Group225.children.append(Transform226)

ProtoBody224.children.append(Group225)

ProtoDeclare220.ProtoBody = ProtoBody224

Scene19.children.append(ProtoDeclare220)
ProtoDeclare240 = x3d.ProtoDeclare()
ProtoDeclare240.name = "unknown"
ProtoInterface241 = x3d.ProtoInterface()
field242 = x3d.field()
field242.name = "position"
field242.accessType = "inputOutput"
field242.type = "SFVec3f"
field242.value = [0,0,0]

ProtoInterface241.field.append(field242)
field243 = x3d.field()
field243.name = "materialTransparency"
field243.accessType = "inputOutput"
field243.type = "SFFloat"
field243.value = 0.6

ProtoInterface241.field.append(field243)

ProtoDeclare240.ProtoInterface = ProtoInterface241
ProtoBody244 = x3d.ProtoBody()
Group245 = x3d.Group()
Transform246 = x3d.Transform(DEF="ato_")
IS247 = x3d.IS()
connect248 = x3d.connect()
connect248.nodeField = "translation"
connect248.protoField = "position"

IS247.connect.append(connect248)

Transform246.IS = IS247
Shape249 = x3d.Shape()
Appearance250 = x3d.Appearance()
Material251 = x3d.Material(DEF="ato__mat")
Material251.diffuseColor = [1,1,1]
Material251.emissiveColor = [0.15,0.1,0.2]
Material251.shininess = 0.09
Material251.specularColor = [0.12,0.12,0.12]
IS252 = x3d.IS()
connect253 = x3d.connect()
connect253.nodeField = "transparency"
connect253.protoField = "materialTransparency"

IS252.connect.append(connect253)

Material251.IS = IS252

Appearance250.material = Material251

Shape249.appearance = Appearance250
Sphere254 = x3d.Sphere()
Sphere254.radius = 1.001

Shape249.geometry = Sphere254

Transform246.children.append(Shape249)
Shape255 = x3d.Shape()
Appearance256 = x3d.Appearance()
Material257 = x3d.Material()
Material257.diffuseColor = [0.9,0.9,0.9]

Appearance256.material = Material257

Shape255.appearance = Appearance256
Text258 = x3d.Text()
Text258.string = ["?"]
FontStyle259 = x3d.FontStyle()
FontStyle259.size = 0.8

Text258.fontStyle = FontStyle259

Shape255.geometry = Text258

Transform246.children.append(Shape255)

Group245.children.append(Transform246)

ProtoBody244.children.append(Group245)

ProtoDeclare240.ProtoBody = ProtoBody244

Scene19.children.append(ProtoDeclare240)
ProtoDeclare260 = x3d.ProtoDeclare()
ProtoDeclare260.name = "line"
ProtoInterface261 = x3d.ProtoInterface()
field262 = x3d.field()
field262.name = "bond_set"
field262.accessType = "inputOutput"
field262.type = "MFVec3f"
field262.value = [(-1, 0, 0),(1, 0, 0)]

ProtoInterface261.field.append(field262)

ProtoDeclare260.ProtoInterface = ProtoInterface261
ProtoBody263 = x3d.ProtoBody()
Group264 = x3d.Group()
Shape265 = x3d.Shape()
Appearance266 = x3d.Appearance()
Material267 = x3d.Material()
Material267.diffuseColor = [1,1,1]
Material267.emissiveColor = [1,1,1]

Appearance266.material = Material267

Shape265.appearance = Appearance266
IndexedLineSet268 = x3d.IndexedLineSet()
IndexedLineSet268.coordIndex = [0,1,-1]
Coordinate269 = x3d.Coordinate(DEF="bondo")
IS270 = x3d.IS()
connect271 = x3d.connect()
connect271.nodeField = "point"
connect271.protoField = "bond_set"

IS270.connect.append(connect271)

Coordinate269.IS = IS270

IndexedLineSet268.coord = Coordinate269

Shape265.geometry = IndexedLineSet268

Group264.children.append(Shape265)

ProtoBody263.children.append(Group264)

ProtoDeclare260.ProtoBody = ProtoBody263

Scene19.children.append(ProtoDeclare260)
ProtoDeclare272 = x3d.ProtoDeclare()
ProtoDeclare272.name = "title_text"
ProtoInterface273 = x3d.ProtoInterface()
field274 = x3d.field()
field274.name = "txt"
field274.accessType = "inputOutput"
field274.type = "MFString"

ProtoInterface273.field.append(field274)

ProtoDeclare272.ProtoInterface = ProtoInterface273
ProtoBody275 = x3d.ProtoBody()
Transform276 = x3d.Transform()
Group277 = x3d.Group()
Transform278 = x3d.Transform()
Shape279 = x3d.Shape()
Appearance280 = x3d.Appearance()
Material281 = x3d.Material()
Material281.diffuseColor = [0.9,0.9,0.9]

Appearance280.material = Material281

Shape279.appearance = Appearance280
Text282 = x3d.Text(DEF="cmpd_name")
IS283 = x3d.IS()
connect284 = x3d.connect()
connect284.nodeField = "string"
connect284.protoField = "txt"

IS283.connect.append(connect284)

Text282.IS = IS283
FontStyle285 = x3d.FontStyle()

Text282.fontStyle = FontStyle285

Shape279.geometry = Text282

Transform278.children.append(Shape279)

Group277.children.append(Transform278)

Transform276.children.append(Group277)

ProtoBody275.children.append(Transform276)

ProtoDeclare272.ProtoBody = ProtoBody275

Scene19.children.append(ProtoDeclare272)
ProtoDeclare286 = x3d.ProtoDeclare()
ProtoDeclare286.name = "ano1_text"
ProtoInterface287 = x3d.ProtoInterface()
field288 = x3d.field()
field288.name = "txt"
field288.accessType = "inputOutput"
field288.type = "MFString"

ProtoInterface287.field.append(field288)

ProtoDeclare286.ProtoInterface = ProtoInterface287
ProtoBody289 = x3d.ProtoBody()
Transform290 = x3d.Transform()
Group291 = x3d.Group()
Transform292 = x3d.Transform()
Shape293 = x3d.Shape()
Appearance294 = x3d.Appearance()
Material295 = x3d.Material()
Material295.diffuseColor = [0.9,0.9,0.9]

Appearance294.material = Material295

Shape293.appearance = Appearance294
Text296 = x3d.Text(DEF="cmpd_name1")
IS297 = x3d.IS()
connect298 = x3d.connect()
connect298.nodeField = "string"
connect298.protoField = "txt"

IS297.connect.append(connect298)

Text296.IS = IS297
FontStyle299 = x3d.FontStyle()
FontStyle299.size = 0.8

Text296.fontStyle = FontStyle299

Shape293.geometry = Text296

Transform292.children.append(Shape293)

Group291.children.append(Transform292)

Transform290.children.append(Group291)

ProtoBody289.children.append(Transform290)

ProtoDeclare286.ProtoBody = ProtoBody289

Scene19.children.append(ProtoDeclare286)
ProtoDeclare300 = x3d.ProtoDeclare()
ProtoDeclare300.name = "ano2_text"
ProtoInterface301 = x3d.ProtoInterface()
field302 = x3d.field()
field302.name = "txt"
field302.accessType = "inputOutput"
field302.type = "MFString"

ProtoInterface301.field.append(field302)

ProtoDeclare300.ProtoInterface = ProtoInterface301
ProtoBody303 = x3d.ProtoBody()
Transform304 = x3d.Transform()
Group305 = x3d.Group()
Transform306 = x3d.Transform()
Shape307 = x3d.Shape()
Appearance308 = x3d.Appearance()
Material309 = x3d.Material()
Material309.diffuseColor = [0.9,0.9,0.9]

Appearance308.material = Material309

Shape307.appearance = Appearance308
Text310 = x3d.Text(DEF="cmpd_name2")
IS311 = x3d.IS()
connect312 = x3d.connect()
connect312.nodeField = "string"
connect312.protoField = "txt"

IS311.connect.append(connect312)

Text310.IS = IS311
FontStyle313 = x3d.FontStyle()
FontStyle313.size = 0.6

Text310.fontStyle = FontStyle313

Shape307.geometry = Text310

Transform306.children.append(Shape307)

Group305.children.append(Transform306)

Transform304.children.append(Group305)

ProtoBody303.children.append(Transform304)

ProtoDeclare300.ProtoBody = ProtoBody303

Scene19.children.append(ProtoDeclare300)
Background314 = x3d.Background()
Background314.groundAngle = [1.309,1.570796]
Background314.groundColor = [(0, 0.5, 0.7),(0, 0.4, 0.7),(0.6, 0.5, 0.7)]
Background314.skyAngle = [1.309,1.570796]
Background314.skyColor = [(0, 0.5, 0.8),(0, 0.6, 0.7),(0.6, 0.6, 0.7)]

Scene19.children.append(Background314)
PointLight315 = x3d.PointLight()
PointLight315.ambientIntensity = 1
PointLight315.location = [0,0,5]
PointLight315.radius = 30

Scene19.children.append(PointLight315)
NavigationInfo316 = x3d.NavigationInfo()
NavigationInfo316.type = ["EXAMINE","FLY","ANY"]

Scene19.children.append(NavigationInfo316)
Viewpoint317 = x3d.Viewpoint()
Viewpoint317.description = "Inspect Oxytocin"
Viewpoint317.position = [0,2,20]

Scene19.children.append(Viewpoint317)
Scene19.children.append(x3d.Comment("""Copyright by the U.S. Sec. Commerce on behalf of U.S.A. All rights reserved."""))
Scene19.children.append(x3d.Comment("""type=\"3D\" <date day=\"23\" month=\"11\" year=\"1995\"/>"""))
Transform318 = x3d.Transform(DEF="infogroupa")
Transform318.translation = [-8,2,-4]
Transform319 = x3d.Transform()
Transform319.translation = [0,6,0]
Viewpoint320 = x3d.Viewpoint()
Viewpoint320.description = "title billboard"
Viewpoint320.position = [6,-2,10]

Transform319.children.append(Viewpoint320)
ProtoInstance321 = x3d.ProtoInstance()
ProtoInstance321.name = "title_text"
fieldValue322 = x3d.fieldValue()
fieldValue322.name = "txt"
fieldValue322.value = "\"Oxytocin: \""

ProtoInstance321.fieldValue.append(fieldValue322)

Transform319.children.append(ProtoInstance321)

Transform318.children.append(Transform319)

Scene19.children.append(Transform318)
Group323 = x3d.Group()
Transform324 = x3d.Transform()
ProtoInstance325 = x3d.ProtoInstance(DEF="a1")
ProtoInstance325.name = "Nitrogen"
fieldValue326 = x3d.fieldValue()
fieldValue326.name = "position"
fieldValue326.value = "-2.0514 1.8507 0"

ProtoInstance325.fieldValue.append(fieldValue326)

Transform324.children.append(ProtoInstance325)

Group323.children.append(Transform324)
Transform327 = x3d.Transform()
ProtoInstance328 = x3d.ProtoInstance(DEF="a2")
ProtoInstance328.name = "Carbon"
fieldValue329 = x3d.fieldValue()
fieldValue329.name = "position"
fieldValue329.value = "-3.601 1.9845 0"

ProtoInstance328.fieldValue.append(fieldValue329)

Transform327.children.append(ProtoInstance328)

Group323.children.append(Transform327)
Transform330 = x3d.Transform()
ProtoInstance331 = x3d.ProtoInstance(DEF="a3")
ProtoInstance331.name = "Carbon"
fieldValue332 = x3d.fieldValue()
fieldValue332.name = "position"
fieldValue332.value = "-1.2821 0.4905 0"

ProtoInstance331.fieldValue.append(fieldValue332)

Transform330.children.append(ProtoInstance331)

Group323.children.append(Transform330)
Transform333 = x3d.Transform()
ProtoInstance334 = x3d.ProtoInstance(DEF="a4")
ProtoInstance334.name = "Carbon"
fieldValue335 = x3d.fieldValue()
fieldValue335.name = "position"
fieldValue335.value = "-1.4159 3.2554 0"

ProtoInstance334.fieldValue.append(fieldValue335)

Transform333.children.append(ProtoInstance334)

Group323.children.append(Transform333)
Transform336 = x3d.Transform()
ProtoInstance337 = x3d.ProtoInstance(DEF="a5")
ProtoInstance337.name = "Carbon"
fieldValue338 = x3d.fieldValue()
fieldValue338.name = "position"
fieldValue338.value = "-4.649 0.8473 0"

ProtoInstance337.fieldValue.append(fieldValue338)

Transform336.children.append(ProtoInstance337)

Group323.children.append(Transform336)
Transform339 = x3d.Transform()
ProtoInstance340 = x3d.ProtoInstance(DEF="a6")
ProtoInstance340.name = "Carbon"
fieldValue341 = x3d.fieldValue()
fieldValue341.name = "position"
fieldValue341.value = "-3.9355 3.5341 0"

ProtoInstance340.fieldValue.append(fieldValue341)

Transform339.children.append(ProtoInstance340)

Group323.children.append(Transform339)
Transform342 = x3d.Transform()
ProtoInstance343 = x3d.ProtoInstance(DEF="a7")
ProtoInstance343.name = "Carbon"
fieldValue344 = x3d.fieldValue()
fieldValue344.name = "position"
fieldValue344.value = "0.2341 0.4905 0"

ProtoInstance343.fieldValue.append(fieldValue344)

Transform342.children.append(ProtoInstance343)

Group323.children.append(Transform342)
Transform345 = x3d.Transform()
ProtoInstance346 = x3d.ProtoInstance(DEF="a8")
ProtoInstance346.name = "Oxygen"
fieldValue347 = x3d.fieldValue()
fieldValue347.name = "position"
fieldValue347.value = "-2.0514 -0.8362 0"

ProtoInstance346.fieldValue.append(fieldValue347)

Transform345.children.append(ProtoInstance346)

Group323.children.append(Transform345)
Transform348 = x3d.Transform()
ProtoInstance349 = x3d.ProtoInstance(DEF="a9")
ProtoInstance349.name = "Carbon"
fieldValue350 = x3d.fieldValue()
fieldValue350.name = "position"
fieldValue350.value = "-2.5753 4.3034 0"

ProtoInstance349.fieldValue.append(fieldValue350)

Transform348.children.append(ProtoInstance349)

Group323.children.append(Transform348)
Transform351 = x3d.Transform()
ProtoInstance352 = x3d.ProtoInstance(DEF="a10")
ProtoInstance352.name = "Nitrogen"
fieldValue353 = x3d.fieldValue()
fieldValue353.name = "position"
fieldValue353.value = "-6.1764 1.1595 0"

ProtoInstance352.fieldValue.append(fieldValue353)

Transform351.children.append(ProtoInstance352)

Group323.children.append(Transform351)
Transform354 = x3d.Transform()
ProtoInstance355 = x3d.ProtoInstance(DEF="a11")
ProtoInstance355.name = "Oxygen"
fieldValue356 = x3d.fieldValue()
fieldValue356.name = "position"
fieldValue356.value = "-4.1585 -0.6132 0"

ProtoInstance355.fieldValue.append(fieldValue356)

Transform354.children.append(ProtoInstance355)

Group323.children.append(Transform354)
Transform357 = x3d.Transform()
ProtoInstance358 = x3d.ProtoInstance(DEF="a12")
ProtoInstance358.name = "Nitrogen"
fieldValue359 = x3d.fieldValue()
fieldValue359.name = "position"
fieldValue359.value = "0.4905 2.0402 0"

ProtoInstance358.fieldValue.append(fieldValue359)

Transform357.children.append(ProtoInstance358)

Group323.children.append(Transform357)
Transform360 = x3d.Transform()
ProtoInstance361 = x3d.ProtoInstance(DEF="a13")
ProtoInstance361.name = "Carbon"
fieldValue362 = x3d.fieldValue()
fieldValue362.name = "position"
fieldValue362.value = "0.4905 -1.0257 0"

ProtoInstance361.fieldValue.append(fieldValue362)

Transform360.children.append(ProtoInstance361)

Group323.children.append(Transform360)
Transform363 = x3d.Transform()
ProtoInstance364 = x3d.ProtoInstance(DEF="a14")
ProtoInstance364.name = "Carbon"
fieldValue365 = x3d.fieldValue()
fieldValue365.name = "position"
fieldValue365.value = "-7.2243 0.0223 0"

ProtoInstance364.fieldValue.append(fieldValue365)

Transform363.children.append(ProtoInstance364)

Group323.children.append(Transform363)
Transform366 = x3d.Transform()
ProtoInstance367 = x3d.ProtoInstance(DEF="a15")
ProtoInstance367.name = "Carbon"
fieldValue368 = x3d.fieldValue()
fieldValue368.name = "position"
fieldValue368.value = "1.2041 3.3892 0"

ProtoInstance367.fieldValue.append(fieldValue368)

Transform366.children.append(ProtoInstance367)

Group323.children.append(Transform366)
Transform369 = x3d.Transform()
ProtoInstance370 = x3d.ProtoInstance(DEF="a16")
ProtoInstance370.name = "Sulphur"
fieldValue371 = x3d.fieldValue()
fieldValue371.name = "position"
fieldValue371.value = "1.1706 -2.4081 0"

ProtoInstance370.fieldValue.append(fieldValue371)

Transform369.children.append(ProtoInstance370)

Group323.children.append(Transform369)
Transform372 = x3d.Transform()
ProtoInstance373 = x3d.ProtoInstance(DEF="a17")
ProtoInstance373.name = "Carbon"
fieldValue374 = x3d.fieldValue()
fieldValue374.name = "position"
fieldValue374.value = "-8.7071 0.3568 0"

ProtoInstance373.fieldValue.append(fieldValue374)

Transform372.children.append(ProtoInstance373)

Group323.children.append(Transform372)
Transform375 = x3d.Transform()
ProtoInstance376 = x3d.ProtoInstance(DEF="a18")
ProtoInstance376.name = "Carbon"
fieldValue377 = x3d.fieldValue()
fieldValue377.name = "position"
fieldValue377.value = "-6.7226 -1.4382 0"

ProtoInstance376.fieldValue.append(fieldValue377)

Transform375.children.append(ProtoInstance376)

Group323.children.append(Transform375)
Transform378 = x3d.Transform()
ProtoInstance379 = x3d.ProtoInstance(DEF="a19")
ProtoInstance379.name = "Carbon"
fieldValue380 = x3d.fieldValue()
fieldValue380.name = "position"
fieldValue380.value = "2.3078 4.4929 0"

ProtoInstance379.fieldValue.append(fieldValue380)

Transform378.children.append(ProtoInstance379)

Group323.children.append(Transform378)
Transform381 = x3d.Transform()
ProtoInstance382 = x3d.ProtoInstance(DEF="a20")
ProtoInstance382.name = "Oxygen"
fieldValue383 = x3d.fieldValue()
fieldValue383.name = "position"
fieldValue383.value = "-0.0446 4.3368 0"

ProtoInstance382.fieldValue.append(fieldValue383)

Transform381.children.append(ProtoInstance382)

Group323.children.append(Transform381)
Transform384 = x3d.Transform()
ProtoInstance385 = x3d.ProtoInstance(DEF="a21")
ProtoInstance385.name = "Sulphur"
fieldValue386 = x3d.fieldValue()
fieldValue386.name = "position"
fieldValue386.value = "2.2855 -3.5118 0"

ProtoInstance385.fieldValue.append(fieldValue386)

Transform384.children.append(ProtoInstance385)

Group323.children.append(Transform384)
Transform387 = x3d.Transform()
ProtoInstance388 = x3d.ProtoInstance(DEF="a22")
ProtoInstance388.name = "Nitrogen"
fieldValue389 = x3d.fieldValue()
fieldValue389.name = "position"
fieldValue389.value = "-9.7662 -0.7804 0"

ProtoInstance388.fieldValue.append(fieldValue389)

Transform387.children.append(ProtoInstance388)

Group323.children.append(Transform387)
Transform390 = x3d.Transform()
ProtoInstance391 = x3d.ProtoInstance(DEF="a23")
ProtoInstance391.name = "Oxygen"
fieldValue392 = x3d.fieldValue()
fieldValue392.name = "position"
fieldValue392.value = "-9.2088 1.8507 0"

ProtoInstance391.fieldValue.append(fieldValue392)

Transform390.children.append(ProtoInstance391)

Group323.children.append(Transform390)
Transform393 = x3d.Transform()
ProtoInstance394 = x3d.ProtoInstance(DEF="a24")
ProtoInstance394.name = "Carbon"
fieldValue395 = x3d.fieldValue()
fieldValue395.name = "position"
fieldValue395.value = "-7.7483 -2.5753 0"

ProtoInstance394.fieldValue.append(fieldValue395)

Transform393.children.append(ProtoInstance394)

Group323.children.append(Transform393)
Transform396 = x3d.Transform()
ProtoInstance397 = x3d.ProtoInstance(DEF="a25")
ProtoInstance397.name = "Nitrogen"
fieldValue398 = x3d.fieldValue()
fieldValue398.name = "position"
fieldValue398.value = "3.6902 5.1841 0"

ProtoInstance397.fieldValue.append(fieldValue398)

Transform396.children.append(ProtoInstance397)

Group323.children.append(Transform396)
Transform399 = x3d.Transform()
ProtoInstance400 = x3d.ProtoInstance(DEF="a26")
ProtoInstance400.name = "Carbon"
fieldValue401 = x3d.fieldValue()
fieldValue401.name = "position"
fieldValue401.value = "1.3936 5.7416 0"

ProtoInstance400.fieldValue.append(fieldValue401)

Transform399.children.append(ProtoInstance400)

Group323.children.append(Transform399)
Transform402 = x3d.Transform()
ProtoInstance403 = x3d.ProtoInstance(DEF="a27")
ProtoInstance403.name = "Carbon"
fieldValue404 = x3d.fieldValue()
fieldValue404.name = "position"
fieldValue404.value = "3.6568 -4.2253 0"

ProtoInstance403.fieldValue.append(fieldValue404)

Transform402.children.append(ProtoInstance403)

Group323.children.append(Transform402)
Transform405 = x3d.Transform()
ProtoInstance406 = x3d.ProtoInstance(DEF="a28")
ProtoInstance406.name = "Carbon"
fieldValue407 = x3d.fieldValue()
fieldValue407.name = "position"
fieldValue407.value = "-11.2825 -0.4459 0"

ProtoInstance406.fieldValue.append(fieldValue407)

Transform405.children.append(ProtoInstance406)

Group323.children.append(Transform405)
Transform408 = x3d.Transform()
ProtoInstance409 = x3d.ProtoInstance(DEF="a29")
ProtoInstance409.name = "Carbon"
fieldValue410 = x3d.fieldValue()
fieldValue410.name = "position"
fieldValue410.value = "-7.2243 -4.0693 0"

ProtoInstance409.fieldValue.append(fieldValue410)

Transform408.children.append(ProtoInstance409)

Group323.children.append(Transform408)
Transform411 = x3d.Transform()
ProtoInstance412 = x3d.ProtoInstance(DEF="a30")
ProtoInstance412.name = "Carbon"
fieldValue413 = x3d.fieldValue()
fieldValue413.name = "position"
fieldValue413.value = "-8.7963 -2.4081 0"

ProtoInstance412.fieldValue.append(fieldValue413)

Transform411.children.append(ProtoInstance412)

Group323.children.append(Transform411)
Transform414 = x3d.Transform()
ProtoInstance415 = x3d.ProtoInstance(DEF="a31")
ProtoInstance415.name = "Carbon"
fieldValue416 = x3d.fieldValue()
fieldValue416.name = "position"
fieldValue416.value = "5.2064 5.4405 0"

ProtoInstance415.fieldValue.append(fieldValue416)

Transform414.children.append(ProtoInstance415)

Group323.children.append(Transform414)
Transform417 = x3d.Transform()
ProtoInstance418 = x3d.ProtoInstance(DEF="a32")
ProtoInstance418.name = "Carbon"
fieldValue419 = x3d.fieldValue()
fieldValue419.name = "position"
fieldValue419.value = "2.0291 7.1797 0"

ProtoInstance418.fieldValue.append(fieldValue419)

Transform417.children.append(ProtoInstance418)

Group323.children.append(Transform417)
Transform420 = x3d.Transform()
ProtoInstance421 = x3d.ProtoInstance(DEF="a33")
ProtoInstance421.name = "Carbon"
fieldValue422 = x3d.fieldValue()
fieldValue422.name = "position"
fieldValue422.value = "5.1841 -4.4818 0"

ProtoInstance421.fieldValue.append(fieldValue422)

Transform420.children.append(ProtoInstance421)

Group323.children.append(Transform420)
Transform423 = x3d.Transform()
ProtoInstance424 = x3d.ProtoInstance(DEF="a34")
ProtoInstance424.name = "Carbon"
fieldValue425 = x3d.fieldValue()
fieldValue425.name = "position"
fieldValue425.value = "-12.3304 -1.6054 0"

ProtoInstance424.fieldValue.append(fieldValue425)

Transform423.children.append(ProtoInstance424)

Group323.children.append(Transform423)
Transform426 = x3d.Transform()
ProtoInstance427 = x3d.ProtoInstance(DEF="a35")
ProtoInstance427.name = "Carbon"
fieldValue428 = x3d.fieldValue()
fieldValue428.name = "position"
fieldValue428.value = "6.7561 5.1841 0"

ProtoInstance427.fieldValue.append(fieldValue428)

Transform426.children.append(ProtoInstance427)

Group323.children.append(Transform426)
Transform429 = x3d.Transform()
ProtoInstance430 = x3d.ProtoInstance(DEF="a36")
ProtoInstance430.name = "Oxygen"
fieldValue431 = x3d.fieldValue()
fieldValue431.name = "position"
fieldValue431.value = "5.2399 6.9791 0"

ProtoInstance430.fieldValue.append(fieldValue431)

Transform429.children.append(ProtoInstance430)

Group323.children.append(Transform429)
Transform432 = x3d.Transform()
ProtoInstance433 = x3d.ProtoInstance(DEF="a37")
ProtoInstance433.name = "Nitrogen"
fieldValue434 = x3d.fieldValue()
fieldValue434.name = "position"
fieldValue434.value = "1.126 8.4507 0"

ProtoInstance433.fieldValue.append(fieldValue434)

Transform432.children.append(ProtoInstance433)

Group323.children.append(Transform432)
Transform435 = x3d.Transform()
ProtoInstance436 = x3d.ProtoInstance(DEF="a38")
ProtoInstance436.name = "Oxygen"
fieldValue437 = x3d.fieldValue()
fieldValue437.name = "position"
fieldValue437.value = "3.5787 7.3135 0"

ProtoInstance436.fieldValue.append(fieldValue437)

Transform435.children.append(ProtoInstance436)

Group323.children.append(Transform435)
Transform438 = x3d.Transform()
ProtoInstance439 = x3d.ProtoInstance(DEF="a39")
ProtoInstance439.name = "Carbon"
fieldValue440 = x3d.fieldValue()
fieldValue440.name = "position"
fieldValue440.value = "6.7226 -4.2253 0"

ProtoInstance439.fieldValue.append(fieldValue440)

Transform438.children.append(ProtoInstance439)

Group323.children.append(Transform438)
Transform441 = x3d.Transform()
ProtoInstance442 = x3d.ProtoInstance(DEF="a40")
ProtoInstance442.name = "Nitrogen"
fieldValue443 = x3d.fieldValue()
fieldValue443.name = "position"
fieldValue443.value = "5.1841 -6.0203 0"

ProtoInstance442.fieldValue.append(fieldValue443)

Transform441.children.append(ProtoInstance442)

Group323.children.append(Transform441)
Transform444 = x3d.Transform()
ProtoInstance445 = x3d.ProtoInstance(DEF="a41")
ProtoInstance445.name = "Nitrogen"
fieldValue446 = x3d.fieldValue()
fieldValue446.name = "position"
fieldValue446.value = "-13.8466 -1.2709 0"

ProtoInstance445.fieldValue.append(fieldValue446)

Transform444.children.append(ProtoInstance445)

Group323.children.append(Transform444)
Transform447 = x3d.Transform()
ProtoInstance448 = x3d.ProtoInstance(DEF="a42")
ProtoInstance448.name = "Oxygen"
fieldValue449 = x3d.fieldValue()
fieldValue449.name = "position"
fieldValue449.value = "-11.8622 -3.0659 0"

ProtoInstance448.fieldValue.append(fieldValue449)

Transform447.children.append(ProtoInstance448)

Group323.children.append(Transform447)
Transform450 = x3d.Transform()
ProtoInstance451 = x3d.ProtoInstance(DEF="a43")
ProtoInstance451.name = "Nitrogen"
fieldValue452 = x3d.fieldValue()
fieldValue452.name = "position"
fieldValue452.value = "8.1385 4.4706 0"

ProtoInstance451.fieldValue.append(fieldValue452)

Transform450.children.append(ProtoInstance451)

Group323.children.append(Transform450)
Transform453 = x3d.Transform()
ProtoInstance454 = x3d.ProtoInstance(DEF="a44")
ProtoInstance454.name = "Carbon"
fieldValue455 = x3d.fieldValue()
fieldValue455.name = "position"
fieldValue455.value = "7.2243 6.6781 0"

ProtoInstance454.fieldValue.append(fieldValue455)

Transform453.children.append(ProtoInstance454)

Group323.children.append(Transform453)
Transform456 = x3d.Transform()
ProtoInstance457 = x3d.ProtoInstance(DEF="a45")
ProtoInstance457.name = "Nitrogen"
fieldValue458 = x3d.fieldValue()
fieldValue458.name = "position"
fieldValue458.value = "8.1051 -3.5341 0"

ProtoInstance457.fieldValue.append(fieldValue458)

Transform456.children.append(ProtoInstance457)

Group323.children.append(Transform456)
Transform459 = x3d.Transform()
ProtoInstance460 = x3d.ProtoInstance(DEF="a46")
ProtoInstance460.name = "Oxygen"
fieldValue461 = x3d.fieldValue()
fieldValue461.name = "position"
fieldValue461.value = "7.202 -5.7193 0"

ProtoInstance460.fieldValue.append(fieldValue461)

Transform459.children.append(ProtoInstance460)

Group323.children.append(Transform459)
Transform462 = x3d.Transform()
ProtoInstance463 = x3d.ProtoInstance(DEF="a47")
ProtoInstance463.name = "Carbon"
fieldValue464 = x3d.fieldValue()
fieldValue464.name = "position"
fieldValue464.value = "9.2422 3.3669 0"

ProtoInstance463.fieldValue.append(fieldValue464)

Transform462.children.append(ProtoInstance463)

Group323.children.append(Transform462)
Transform465 = x3d.Transform()
ProtoInstance466 = x3d.ProtoInstance(DEF="a48")
ProtoInstance466.name = "Carbon"
fieldValue467 = x3d.fieldValue()
fieldValue467.name = "position"
fieldValue467.value = "8.7406 6.9791 0"

ProtoInstance466.fieldValue.append(fieldValue467)

Transform465.children.append(ProtoInstance466)

Group323.children.append(Transform465)
Transform468 = x3d.Transform()
ProtoInstance469 = x3d.ProtoInstance(DEF="a49")
ProtoInstance469.name = "Carbon"
fieldValue470 = x3d.fieldValue()
fieldValue470.name = "position"
fieldValue470.value = "9.2088 -2.4304 0"

ProtoInstance469.fieldValue.append(fieldValue470)

Transform468.children.append(ProtoInstance469)

Group323.children.append(Transform468)
Transform471 = x3d.Transform()
ProtoInstance472 = x3d.ProtoInstance(DEF="a50")
ProtoInstance472.name = "Carbon"
fieldValue473 = x3d.fieldValue()
fieldValue473.name = "position"
fieldValue473.value = "9.9335 1.9845 0"

ProtoInstance472.fieldValue.append(fieldValue473)

Transform471.children.append(ProtoInstance472)

Group323.children.append(Transform471)
Transform474 = x3d.Transform()
ProtoInstance475 = x3d.ProtoInstance(DEF="a51")
ProtoInstance475.name = "Oxygen"
fieldValue476 = x3d.fieldValue()
fieldValue476.name = "position"
fieldValue476.value = "10.4797 4.3034 0"

ProtoInstance475.fieldValue.append(fieldValue476)

Transform474.children.append(ProtoInstance475)

Group323.children.append(Transform474)
Transform477 = x3d.Transform()
ProtoInstance478 = x3d.ProtoInstance(DEF="a52")
ProtoInstance478.name = "Carbon"
fieldValue479 = x3d.fieldValue()
fieldValue479.name = "position"
fieldValue479.value = "9.2422 8.4507 0"

ProtoInstance478.fieldValue.append(fieldValue479)

Transform477.children.append(ProtoInstance478)

Group323.children.append(Transform477)
Transform480 = x3d.Transform()
ProtoInstance481 = x3d.ProtoInstance(DEF="a53")
ProtoInstance481.name = "Carbon"
fieldValue482 = x3d.fieldValue()
fieldValue482.name = "position"
fieldValue482.value = "10.4797 -3.3446 0"

ProtoInstance481.fieldValue.append(fieldValue482)

Transform480.children.append(ProtoInstance481)

Group323.children.append(Transform480)
Transform483 = x3d.Transform()
ProtoInstance484 = x3d.ProtoInstance(DEF="a54")
ProtoInstance484.name = "Carbon"
fieldValue485 = x3d.fieldValue()
fieldValue485.name = "position"
fieldValue485.value = "9.9335 -1.0591 0"

ProtoInstance484.fieldValue.append(fieldValue485)

Transform483.children.append(ProtoInstance484)

Group323.children.append(Transform483)
Transform486 = x3d.Transform()
ProtoInstance487 = x3d.ProtoInstance(DEF="a55")
ProtoInstance487.name = "Nitrogen"
fieldValue488 = x3d.fieldValue()
fieldValue488.name = "position"
fieldValue488.value = "10.1787 0.4682 0"

ProtoInstance487.fieldValue.append(fieldValue488)

Transform486.children.append(ProtoInstance487)

Group323.children.append(Transform486)
Transform489 = x3d.Transform()
ProtoInstance490 = x3d.ProtoInstance(DEF="a56")
ProtoInstance490.name = "Carbon"
fieldValue491 = x3d.fieldValue()
fieldValue491.name = "position"
fieldValue491.value = "11.4274 2.4862 0"

ProtoInstance490.fieldValue.append(fieldValue491)

Transform489.children.append(ProtoInstance490)

Group323.children.append(Transform489)
Transform492 = x3d.Transform()
ProtoInstance493 = x3d.ProtoInstance(DEF="a57")
ProtoInstance493.name = "Nitrogen"
fieldValue494 = x3d.fieldValue()
fieldValue494.name = "position"
fieldValue494.value = "10.7585 8.774 0"

ProtoInstance493.fieldValue.append(fieldValue494)

Transform492.children.append(ProtoInstance493)

Group323.children.append(Transform492)
Transform495 = x3d.Transform()
ProtoInstance496 = x3d.ProtoInstance(DEF="a58")
ProtoInstance496.name = "Oxygen"
fieldValue497 = x3d.fieldValue()
fieldValue497.name = "position"
fieldValue497.value = "8.2166 9.6324 0"

ProtoInstance496.fieldValue.append(fieldValue497)

Transform495.children.append(ProtoInstance496)

Group323.children.append(Transform495)
Transform498 = x3d.Transform()
ProtoInstance499 = x3d.ProtoInstance(DEF="a59")
ProtoInstance499.name = "Carbon"
fieldValue500 = x3d.fieldValue()
fieldValue500.name = "position"
fieldValue500.value = "10.3237 -4.8943 0"

ProtoInstance499.fieldValue.append(fieldValue500)

Transform498.children.append(ProtoInstance499)

Group323.children.append(Transform498)
Transform501 = x3d.Transform()
ProtoInstance502 = x3d.ProtoInstance(DEF="a60")
ProtoInstance502.name = "Oxygen"
fieldValue503 = x3d.fieldValue()
fieldValue503.name = "position"
fieldValue503.value = "11.4274 -1.5274 0"

ProtoInstance502.fieldValue.append(fieldValue503)

Transform501.children.append(ProtoInstance502)

Group323.children.append(Transform501)
Transform504 = x3d.Transform()
ProtoInstance505 = x3d.ProtoInstance(DEF="a61")
ProtoInstance505.name = "Carbon"
fieldValue506 = x3d.fieldValue()
fieldValue506.name = "position"
fieldValue506.value = "12.5534 1.427 0"

ProtoInstance505.fieldValue.append(fieldValue506)

Transform504.children.append(ProtoInstance505)

Group323.children.append(Transform504)
Transform507 = x3d.Transform()
ProtoInstance508 = x3d.ProtoInstance(DEF="a62")
ProtoInstance508.name = "Carbon"
fieldValue509 = x3d.fieldValue()
fieldValue509.name = "position"
fieldValue509.value = "11.7507 4.0024 0"

ProtoInstance508.fieldValue.append(fieldValue509)

Transform507.children.append(ProtoInstance508)

Group323.children.append(Transform507)
Transform510 = x3d.Transform()
ProtoInstance511 = x3d.ProtoInstance(DEF="a63")
ProtoInstance511.name = "Carbon"
fieldValue512 = x3d.fieldValue()
fieldValue512.name = "position"
fieldValue512.value = "8.8855 -5.5297 0"

ProtoInstance511.fieldValue.append(fieldValue512)

Transform510.children.append(ProtoInstance511)

Group323.children.append(Transform510)
Transform513 = x3d.Transform()
ProtoInstance514 = x3d.ProtoInstance(DEF="a64")
ProtoInstance514.name = "Carbon"
fieldValue515 = x3d.fieldValue()
fieldValue515.name = "position"
fieldValue515.value = "11.5612 -5.8085 0"

ProtoInstance514.fieldValue.append(fieldValue515)

Transform513.children.append(ProtoInstance514)

Group323.children.append(Transform513)
Transform516 = x3d.Transform()
ProtoInstance517 = x3d.ProtoInstance(DEF="a65")
ProtoInstance517.name = "Carbon"
fieldValue518 = x3d.fieldValue()
fieldValue518.name = "position"
fieldValue518.value = "14.0473 1.9064 0"

ProtoInstance517.fieldValue.append(fieldValue518)

Transform516.children.append(ProtoInstance517)

Group323.children.append(Transform516)
Transform519 = x3d.Transform()
ProtoInstance520 = x3d.ProtoInstance(DEF="a66")
ProtoInstance520.name = "Carbon"
fieldValue521 = x3d.fieldValue()
fieldValue521.name = "position"
fieldValue521.value = "8.7183 -7.0794 0"

ProtoInstance520.fieldValue.append(fieldValue521)

Transform519.children.append(ProtoInstance520)

Group323.children.append(Transform519)
Transform522 = x3d.Transform()
ProtoInstance523 = x3d.ProtoInstance(DEF="a67")
ProtoInstance523.name = "Carbon"
fieldValue524 = x3d.fieldValue()
fieldValue524.name = "position"
fieldValue524.value = "11.3939 -7.347 0"

ProtoInstance523.fieldValue.append(fieldValue524)

Transform522.children.append(ProtoInstance523)

Group323.children.append(Transform522)
Transform525 = x3d.Transform()
ProtoInstance526 = x3d.ProtoInstance(DEF="a68")
ProtoInstance526.name = "Carbon"
fieldValue527 = x3d.fieldValue()
fieldValue527.name = "position"
fieldValue527.value = "9.9892 -7.9824 0"

ProtoInstance526.fieldValue.append(fieldValue527)

Transform525.children.append(ProtoInstance526)

Group323.children.append(Transform525)
Transform528 = x3d.Transform()
ProtoInstance529 = x3d.ProtoInstance(DEF="a69")
ProtoInstance529.name = "Oxygen"
fieldValue530 = x3d.fieldValue()
fieldValue530.name = "position"
fieldValue530.value = "9.7885 -9.5321 0"

ProtoInstance529.fieldValue.append(fieldValue530)

Transform528.children.append(ProtoInstance529)

Group323.children.append(Transform528)

Scene19.children.append(Group323)
Group531 = x3d.Group()
ProtoInstance532 = x3d.ProtoInstance(DEF="b1")
ProtoInstance532.name = "line"
fieldValue533 = x3d.fieldValue()
fieldValue533.name = "bond_set"
fieldValue533.value = "-2.0514 1.8507 0 -3.601 1.9845 0"

ProtoInstance532.fieldValue.append(fieldValue533)

Group531.children.append(ProtoInstance532)
ProtoInstance534 = x3d.ProtoInstance(DEF="b2")
ProtoInstance534.name = "line"
fieldValue535 = x3d.fieldValue()
fieldValue535.name = "bond_set"
fieldValue535.value = "-2.0514 1.8507 0 -1.2821 0.4905 0"

ProtoInstance534.fieldValue.append(fieldValue535)

Group531.children.append(ProtoInstance534)
ProtoInstance536 = x3d.ProtoInstance(DEF="b3")
ProtoInstance536.name = "line"
fieldValue537 = x3d.fieldValue()
fieldValue537.name = "bond_set"
fieldValue537.value = "-2.0514 1.8507 0 -1.4159 3.2554 0"

ProtoInstance536.fieldValue.append(fieldValue537)

Group531.children.append(ProtoInstance536)
ProtoInstance538 = x3d.ProtoInstance(DEF="b4")
ProtoInstance538.name = "line"
fieldValue539 = x3d.fieldValue()
fieldValue539.name = "bond_set"
fieldValue539.value = "-3.601 1.9845 0 -4.649 0.8473 0"

ProtoInstance538.fieldValue.append(fieldValue539)

Group531.children.append(ProtoInstance538)
ProtoInstance540 = x3d.ProtoInstance(DEF="b5")
ProtoInstance540.name = "line"
fieldValue541 = x3d.fieldValue()
fieldValue541.name = "bond_set"
fieldValue541.value = "-3.601 1.9845 0 -3.9355 3.5341 0"

ProtoInstance540.fieldValue.append(fieldValue541)

Group531.children.append(ProtoInstance540)
ProtoInstance542 = x3d.ProtoInstance(DEF="b6")
ProtoInstance542.name = "line"
fieldValue543 = x3d.fieldValue()
fieldValue543.name = "bond_set"
fieldValue543.value = "-1.2821 0.4905 0 0.2341 0.4905 0"

ProtoInstance542.fieldValue.append(fieldValue543)

Group531.children.append(ProtoInstance542)
ProtoInstance544 = x3d.ProtoInstance(DEF="b7")
ProtoInstance544.name = "line"
fieldValue545 = x3d.fieldValue()
fieldValue545.name = "bond_set"
fieldValue545.value = "-1.3021 0.4905 0 -2.0714 -0.8362 0"

ProtoInstance544.fieldValue.append(fieldValue545)

Group531.children.append(ProtoInstance544)
ProtoInstance546 = x3d.ProtoInstance(DEF="b7_2")
ProtoInstance546.name = "line"
fieldValue547 = x3d.fieldValue()
fieldValue547.name = "bond_set"
fieldValue547.value = "-1.2621 0.4905 0 -2.0314 -0.8362 0"

ProtoInstance546.fieldValue.append(fieldValue547)

Group531.children.append(ProtoInstance546)
ProtoInstance548 = x3d.ProtoInstance(DEF="b8")
ProtoInstance548.name = "line"
fieldValue549 = x3d.fieldValue()
fieldValue549.name = "bond_set"
fieldValue549.value = "-1.4159 3.2554 0 -2.5753 4.3034 0"

ProtoInstance548.fieldValue.append(fieldValue549)

Group531.children.append(ProtoInstance548)
ProtoInstance550 = x3d.ProtoInstance(DEF="b9")
ProtoInstance550.name = "line"
fieldValue551 = x3d.fieldValue()
fieldValue551.name = "bond_set"
fieldValue551.value = "-4.649 0.8473 0 -6.1764 1.1595 0"

ProtoInstance550.fieldValue.append(fieldValue551)

Group531.children.append(ProtoInstance550)
ProtoInstance552 = x3d.ProtoInstance(DEF="b10")
ProtoInstance552.name = "line"
fieldValue553 = x3d.fieldValue()
fieldValue553.name = "bond_set"
fieldValue553.value = "-4.669 0.8473 0 -4.1785 -0.6132 0"

ProtoInstance552.fieldValue.append(fieldValue553)

Group531.children.append(ProtoInstance552)
ProtoInstance554 = x3d.ProtoInstance(DEF="b10_2")
ProtoInstance554.name = "line"
fieldValue555 = x3d.fieldValue()
fieldValue555.name = "bond_set"
fieldValue555.value = "-4.6290000000000004 0.8473 0 -4.1385000000000005 -0.6132 0"

ProtoInstance554.fieldValue.append(fieldValue555)

Group531.children.append(ProtoInstance554)
ProtoInstance556 = x3d.ProtoInstance(DEF="b11")
ProtoInstance556.name = "line"
fieldValue557 = x3d.fieldValue()
fieldValue557.name = "bond_set"
fieldValue557.value = "0.2341 0.4905 0 0.4905 2.0402 0"

ProtoInstance556.fieldValue.append(fieldValue557)

Group531.children.append(ProtoInstance556)
ProtoInstance558 = x3d.ProtoInstance(DEF="b12")
ProtoInstance558.name = "line"
fieldValue559 = x3d.fieldValue()
fieldValue559.name = "bond_set"
fieldValue559.value = "0.2341 0.4905 0 0.4905 -1.0257 0"

ProtoInstance558.fieldValue.append(fieldValue559)

Group531.children.append(ProtoInstance558)
ProtoInstance560 = x3d.ProtoInstance(DEF="b13")
ProtoInstance560.name = "line"
fieldValue561 = x3d.fieldValue()
fieldValue561.name = "bond_set"
fieldValue561.value = "-6.1764 1.1595 0 -7.2243 0.0223 0"

ProtoInstance560.fieldValue.append(fieldValue561)

Group531.children.append(ProtoInstance560)
ProtoInstance562 = x3d.ProtoInstance(DEF="b14")
ProtoInstance562.name = "line"
fieldValue563 = x3d.fieldValue()
fieldValue563.name = "bond_set"
fieldValue563.value = "0.4905 2.0402 0 1.2041 3.3892 0"

ProtoInstance562.fieldValue.append(fieldValue563)

Group531.children.append(ProtoInstance562)
ProtoInstance564 = x3d.ProtoInstance(DEF="b15")
ProtoInstance564.name = "line"
fieldValue565 = x3d.fieldValue()
fieldValue565.name = "bond_set"
fieldValue565.value = "0.4905 -1.0257 0 1.1706 -2.4081 0"

ProtoInstance564.fieldValue.append(fieldValue565)

Group531.children.append(ProtoInstance564)
ProtoInstance566 = x3d.ProtoInstance(DEF="b16")
ProtoInstance566.name = "line"
fieldValue567 = x3d.fieldValue()
fieldValue567.name = "bond_set"
fieldValue567.value = "-7.2243 0.0223 0 -8.7071 0.3568 0"

ProtoInstance566.fieldValue.append(fieldValue567)

Group531.children.append(ProtoInstance566)
ProtoInstance568 = x3d.ProtoInstance(DEF="b17")
ProtoInstance568.name = "line"
fieldValue569 = x3d.fieldValue()
fieldValue569.name = "bond_set"
fieldValue569.value = "-7.2243 0.0223 0 -6.7226 -1.4382 0"

ProtoInstance568.fieldValue.append(fieldValue569)

Group531.children.append(ProtoInstance568)
ProtoInstance570 = x3d.ProtoInstance(DEF="b18")
ProtoInstance570.name = "line"
fieldValue571 = x3d.fieldValue()
fieldValue571.name = "bond_set"
fieldValue571.value = "1.2041 3.3892 0 2.3078 4.4929 0"

ProtoInstance570.fieldValue.append(fieldValue571)

Group531.children.append(ProtoInstance570)
ProtoInstance572 = x3d.ProtoInstance(DEF="b19")
ProtoInstance572.name = "line"
fieldValue573 = x3d.fieldValue()
fieldValue573.name = "bond_set"
fieldValue573.value = "1.1841 3.3892 0 -0.0646 4.3368 0"

ProtoInstance572.fieldValue.append(fieldValue573)

Group531.children.append(ProtoInstance572)
ProtoInstance574 = x3d.ProtoInstance(DEF="b19_2")
ProtoInstance574.name = "line"
fieldValue575 = x3d.fieldValue()
fieldValue575.name = "bond_set"
fieldValue575.value = "1.2241 3.3892 0 -0.0246 4.3368 0"

ProtoInstance574.fieldValue.append(fieldValue575)

Group531.children.append(ProtoInstance574)
ProtoInstance576 = x3d.ProtoInstance(DEF="b20")
ProtoInstance576.name = "line"
fieldValue577 = x3d.fieldValue()
fieldValue577.name = "bond_set"
fieldValue577.value = "1.1706 -2.4081 0 2.2855 -3.5118 0"

ProtoInstance576.fieldValue.append(fieldValue577)

Group531.children.append(ProtoInstance576)
ProtoInstance578 = x3d.ProtoInstance(DEF="b21")
ProtoInstance578.name = "line"
fieldValue579 = x3d.fieldValue()
fieldValue579.name = "bond_set"
fieldValue579.value = "-8.7071 0.3568 0 -9.7662 -0.7804 0"

ProtoInstance578.fieldValue.append(fieldValue579)

Group531.children.append(ProtoInstance578)
ProtoInstance580 = x3d.ProtoInstance(DEF="b22")
ProtoInstance580.name = "line"
fieldValue581 = x3d.fieldValue()
fieldValue581.name = "bond_set"
fieldValue581.value = "-8.7271 0.3568 0 -9.2288 1.8507 0"

ProtoInstance580.fieldValue.append(fieldValue581)

Group531.children.append(ProtoInstance580)
ProtoInstance582 = x3d.ProtoInstance(DEF="b22_2")
ProtoInstance582.name = "line"
fieldValue583 = x3d.fieldValue()
fieldValue583.name = "bond_set"
fieldValue583.value = "-8.687100000000001 0.3568 0 -9.1888 1.8507 0"

ProtoInstance582.fieldValue.append(fieldValue583)

Group531.children.append(ProtoInstance582)
ProtoInstance584 = x3d.ProtoInstance(DEF="b23")
ProtoInstance584.name = "line"
fieldValue585 = x3d.fieldValue()
fieldValue585.name = "bond_set"
fieldValue585.value = "-6.7226 -1.4382 0 -7.7483 -2.5753 0"

ProtoInstance584.fieldValue.append(fieldValue585)

Group531.children.append(ProtoInstance584)
ProtoInstance586 = x3d.ProtoInstance(DEF="b24")
ProtoInstance586.name = "line"
fieldValue587 = x3d.fieldValue()
fieldValue587.name = "bond_set"
fieldValue587.value = "2.3078 4.4929 0 3.6902 5.1841 0"

ProtoInstance586.fieldValue.append(fieldValue587)

Group531.children.append(ProtoInstance586)
ProtoInstance588 = x3d.ProtoInstance(DEF="b25")
ProtoInstance588.name = "line"
fieldValue589 = x3d.fieldValue()
fieldValue589.name = "bond_set"
fieldValue589.value = "2.3078 4.4929 0 1.3936 5.7416 0"

ProtoInstance588.fieldValue.append(fieldValue589)

Group531.children.append(ProtoInstance588)
ProtoInstance590 = x3d.ProtoInstance(DEF="b26")
ProtoInstance590.name = "line"
fieldValue591 = x3d.fieldValue()
fieldValue591.name = "bond_set"
fieldValue591.value = "2.2855 -3.5118 0 3.6568 -4.2253 0"

ProtoInstance590.fieldValue.append(fieldValue591)

Group531.children.append(ProtoInstance590)
ProtoInstance592 = x3d.ProtoInstance(DEF="b27")
ProtoInstance592.name = "line"
fieldValue593 = x3d.fieldValue()
fieldValue593.name = "bond_set"
fieldValue593.value = "-9.7662 -0.7804 0 -11.2825 -0.4459 0"

ProtoInstance592.fieldValue.append(fieldValue593)

Group531.children.append(ProtoInstance592)
ProtoInstance594 = x3d.ProtoInstance(DEF="b28")
ProtoInstance594.name = "line"
fieldValue595 = x3d.fieldValue()
fieldValue595.name = "bond_set"
fieldValue595.value = "-7.7483 -2.5753 0 -7.2243 -4.0693 0"

ProtoInstance594.fieldValue.append(fieldValue595)

Group531.children.append(ProtoInstance594)
ProtoInstance596 = x3d.ProtoInstance(DEF="b29")
ProtoInstance596.name = "line"
fieldValue597 = x3d.fieldValue()
fieldValue597.name = "bond_set"
fieldValue597.value = "-7.7483 -2.5753 0 -8.7963 -2.4081 0"

ProtoInstance596.fieldValue.append(fieldValue597)

Group531.children.append(ProtoInstance596)
ProtoInstance598 = x3d.ProtoInstance(DEF="b30")
ProtoInstance598.name = "line"
fieldValue599 = x3d.fieldValue()
fieldValue599.name = "bond_set"
fieldValue599.value = "3.6902 5.1841 0 5.2064 5.4405 0"

ProtoInstance598.fieldValue.append(fieldValue599)

Group531.children.append(ProtoInstance598)
ProtoInstance600 = x3d.ProtoInstance(DEF="b31")
ProtoInstance600.name = "line"
fieldValue601 = x3d.fieldValue()
fieldValue601.name = "bond_set"
fieldValue601.value = "1.3936 5.7416 0 2.0291 7.1797 0"

ProtoInstance600.fieldValue.append(fieldValue601)

Group531.children.append(ProtoInstance600)
ProtoInstance602 = x3d.ProtoInstance(DEF="b32")
ProtoInstance602.name = "line"
fieldValue603 = x3d.fieldValue()
fieldValue603.name = "bond_set"
fieldValue603.value = "3.6568 -4.2253 0 5.1841 -4.4818 0"

ProtoInstance602.fieldValue.append(fieldValue603)

Group531.children.append(ProtoInstance602)
ProtoInstance604 = x3d.ProtoInstance(DEF="b33")
ProtoInstance604.name = "line"
fieldValue605 = x3d.fieldValue()
fieldValue605.name = "bond_set"
fieldValue605.value = "-11.2825 -0.4459 0 -12.3304 -1.6054 0"

ProtoInstance604.fieldValue.append(fieldValue605)

Group531.children.append(ProtoInstance604)
ProtoInstance606 = x3d.ProtoInstance(DEF="b34")
ProtoInstance606.name = "line"
fieldValue607 = x3d.fieldValue()
fieldValue607.name = "bond_set"
fieldValue607.value = "5.2064 5.4405 0 6.7561 5.1841 0"

ProtoInstance606.fieldValue.append(fieldValue607)

Group531.children.append(ProtoInstance606)
ProtoInstance608 = x3d.ProtoInstance(DEF="b35")
ProtoInstance608.name = "line"
fieldValue609 = x3d.fieldValue()
fieldValue609.name = "bond_set"
fieldValue609.value = "5.186400000000001 5.4405 0 5.2199 6.9791 0"

ProtoInstance608.fieldValue.append(fieldValue609)

Group531.children.append(ProtoInstance608)
ProtoInstance610 = x3d.ProtoInstance(DEF="b35_2")
ProtoInstance610.name = "line"
fieldValue611 = x3d.fieldValue()
fieldValue611.name = "bond_set"
fieldValue611.value = "5.2264 5.4405 0 5.259899999999999 6.9791 0"

ProtoInstance610.fieldValue.append(fieldValue611)

Group531.children.append(ProtoInstance610)
ProtoInstance612 = x3d.ProtoInstance(DEF="b36")
ProtoInstance612.name = "line"
fieldValue613 = x3d.fieldValue()
fieldValue613.name = "bond_set"
fieldValue613.value = "2.0291 7.1797 0 1.126 8.4507 0"

ProtoInstance612.fieldValue.append(fieldValue613)

Group531.children.append(ProtoInstance612)
ProtoInstance614 = x3d.ProtoInstance(DEF="b37")
ProtoInstance614.name = "line"
fieldValue615 = x3d.fieldValue()
fieldValue615.name = "bond_set"
fieldValue615.value = "2.0091 7.1797 0 3.5587 7.3135 0"

ProtoInstance614.fieldValue.append(fieldValue615)

Group531.children.append(ProtoInstance614)
ProtoInstance616 = x3d.ProtoInstance(DEF="b37_2")
ProtoInstance616.name = "line"
fieldValue617 = x3d.fieldValue()
fieldValue617.name = "bond_set"
fieldValue617.value = "2.0491 7.1797 0 3.5987 7.3135 0"

ProtoInstance616.fieldValue.append(fieldValue617)

Group531.children.append(ProtoInstance616)
ProtoInstance618 = x3d.ProtoInstance(DEF="b38")
ProtoInstance618.name = "line"
fieldValue619 = x3d.fieldValue()
fieldValue619.name = "bond_set"
fieldValue619.value = "5.1841 -4.4818 0 6.7226 -4.2253 0"

ProtoInstance618.fieldValue.append(fieldValue619)

Group531.children.append(ProtoInstance618)
ProtoInstance620 = x3d.ProtoInstance(DEF="b39")
ProtoInstance620.name = "line"
fieldValue621 = x3d.fieldValue()
fieldValue621.name = "bond_set"
fieldValue621.value = "5.1841 -4.4818 0 5.1841 -6.0203 0"

ProtoInstance620.fieldValue.append(fieldValue621)

Group531.children.append(ProtoInstance620)
ProtoInstance622 = x3d.ProtoInstance(DEF="b40")
ProtoInstance622.name = "line"
fieldValue623 = x3d.fieldValue()
fieldValue623.name = "bond_set"
fieldValue623.value = "-12.3304 -1.6054 0 -13.8466 -1.2709 0"

ProtoInstance622.fieldValue.append(fieldValue623)

Group531.children.append(ProtoInstance622)
ProtoInstance624 = x3d.ProtoInstance(DEF="b41")
ProtoInstance624.name = "line"
fieldValue625 = x3d.fieldValue()
fieldValue625.name = "bond_set"
fieldValue625.value = "-12.350399999999999 -1.6054 0 -11.8822 -3.0659 0"

ProtoInstance624.fieldValue.append(fieldValue625)

Group531.children.append(ProtoInstance624)
ProtoInstance626 = x3d.ProtoInstance(DEF="b41_2")
ProtoInstance626.name = "line"
fieldValue627 = x3d.fieldValue()
fieldValue627.name = "bond_set"
fieldValue627.value = "-12.3104 -1.6054 0 -11.8422 -3.0659 0"

ProtoInstance626.fieldValue.append(fieldValue627)

Group531.children.append(ProtoInstance626)
ProtoInstance628 = x3d.ProtoInstance(DEF="b42")
ProtoInstance628.name = "line"
fieldValue629 = x3d.fieldValue()
fieldValue629.name = "bond_set"
fieldValue629.value = "6.7561 5.1841 0 8.1385 4.4706 0"

ProtoInstance628.fieldValue.append(fieldValue629)

Group531.children.append(ProtoInstance628)
ProtoInstance630 = x3d.ProtoInstance(DEF="b43")
ProtoInstance630.name = "line"
fieldValue631 = x3d.fieldValue()
fieldValue631.name = "bond_set"
fieldValue631.value = "6.7561 5.1841 0 7.2243 6.6781 0"

ProtoInstance630.fieldValue.append(fieldValue631)

Group531.children.append(ProtoInstance630)
ProtoInstance632 = x3d.ProtoInstance(DEF="b44")
ProtoInstance632.name = "line"
fieldValue633 = x3d.fieldValue()
fieldValue633.name = "bond_set"
fieldValue633.value = "6.7226 -4.2253 0 8.1051 -3.5341 0"

ProtoInstance632.fieldValue.append(fieldValue633)

Group531.children.append(ProtoInstance632)
ProtoInstance634 = x3d.ProtoInstance(DEF="b45")
ProtoInstance634.name = "line"
fieldValue635 = x3d.fieldValue()
fieldValue635.name = "bond_set"
fieldValue635.value = "6.7026 -4.2253 0 7.182 -5.7193 0"

ProtoInstance634.fieldValue.append(fieldValue635)

Group531.children.append(ProtoInstance634)
ProtoInstance636 = x3d.ProtoInstance(DEF="b45_2")
ProtoInstance636.name = "line"
fieldValue637 = x3d.fieldValue()
fieldValue637.name = "bond_set"
fieldValue637.value = "6.7425999999999995 -4.2253 0 7.2219999999999995 -5.7193 0"

ProtoInstance636.fieldValue.append(fieldValue637)

Group531.children.append(ProtoInstance636)
ProtoInstance638 = x3d.ProtoInstance(DEF="b46")
ProtoInstance638.name = "line"
fieldValue639 = x3d.fieldValue()
fieldValue639.name = "bond_set"
fieldValue639.value = "8.1385 4.4706 0 9.2422 3.3669 0"

ProtoInstance638.fieldValue.append(fieldValue639)

Group531.children.append(ProtoInstance638)
ProtoInstance640 = x3d.ProtoInstance(DEF="b47")
ProtoInstance640.name = "line"
fieldValue641 = x3d.fieldValue()
fieldValue641.name = "bond_set"
fieldValue641.value = "7.2243 6.6781 0 8.7406 6.9791 0"

ProtoInstance640.fieldValue.append(fieldValue641)

Group531.children.append(ProtoInstance640)
ProtoInstance642 = x3d.ProtoInstance(DEF="b48")
ProtoInstance642.name = "line"
fieldValue643 = x3d.fieldValue()
fieldValue643.name = "bond_set"
fieldValue643.value = "8.1051 -3.5341 0 9.2088 -2.4304 0"

ProtoInstance642.fieldValue.append(fieldValue643)

Group531.children.append(ProtoInstance642)
ProtoInstance644 = x3d.ProtoInstance(DEF="b49")
ProtoInstance644.name = "line"
fieldValue645 = x3d.fieldValue()
fieldValue645.name = "bond_set"
fieldValue645.value = "9.2422 3.3669 0 9.9335 1.9845 0"

ProtoInstance644.fieldValue.append(fieldValue645)

Group531.children.append(ProtoInstance644)
ProtoInstance646 = x3d.ProtoInstance(DEF="b50")
ProtoInstance646.name = "line"
fieldValue647 = x3d.fieldValue()
fieldValue647.name = "bond_set"
fieldValue647.value = "9.2222 3.3669 0 10.4597 4.3034 0"

ProtoInstance646.fieldValue.append(fieldValue647)

Group531.children.append(ProtoInstance646)
ProtoInstance648 = x3d.ProtoInstance(DEF="b50_2")
ProtoInstance648.name = "line"
fieldValue649 = x3d.fieldValue()
fieldValue649.name = "bond_set"
fieldValue649.value = "9.2622 3.3669 0 10.499699999999999 4.3034 0"

ProtoInstance648.fieldValue.append(fieldValue649)

Group531.children.append(ProtoInstance648)
ProtoInstance650 = x3d.ProtoInstance(DEF="b51")
ProtoInstance650.name = "line"
fieldValue651 = x3d.fieldValue()
fieldValue651.name = "bond_set"
fieldValue651.value = "8.7406 6.9791 0 9.2422 8.4507 0"

ProtoInstance650.fieldValue.append(fieldValue651)

Group531.children.append(ProtoInstance650)
ProtoInstance652 = x3d.ProtoInstance(DEF="b52")
ProtoInstance652.name = "line"
fieldValue653 = x3d.fieldValue()
fieldValue653.name = "bond_set"
fieldValue653.value = "9.2088 -2.4304 0 10.4797 -3.3446 0"

ProtoInstance652.fieldValue.append(fieldValue653)

Group531.children.append(ProtoInstance652)
ProtoInstance654 = x3d.ProtoInstance(DEF="b53")
ProtoInstance654.name = "line"
fieldValue655 = x3d.fieldValue()
fieldValue655.name = "bond_set"
fieldValue655.value = "9.2088 -2.4304 0 9.9335 -1.0591 0"

ProtoInstance654.fieldValue.append(fieldValue655)

Group531.children.append(ProtoInstance654)
ProtoInstance656 = x3d.ProtoInstance(DEF="b54")
ProtoInstance656.name = "line"
fieldValue657 = x3d.fieldValue()
fieldValue657.name = "bond_set"
fieldValue657.value = "9.9335 1.9845 0 10.1787 0.4682 0"

ProtoInstance656.fieldValue.append(fieldValue657)

Group531.children.append(ProtoInstance656)
ProtoInstance658 = x3d.ProtoInstance(DEF="b55")
ProtoInstance658.name = "line"
fieldValue659 = x3d.fieldValue()
fieldValue659.name = "bond_set"
fieldValue659.value = "9.9335 1.9845 0 11.4274 2.4862 0"

ProtoInstance658.fieldValue.append(fieldValue659)

Group531.children.append(ProtoInstance658)
ProtoInstance660 = x3d.ProtoInstance(DEF="b56")
ProtoInstance660.name = "line"
fieldValue661 = x3d.fieldValue()
fieldValue661.name = "bond_set"
fieldValue661.value = "9.2422 8.4507 0 10.7585 8.774 0"

ProtoInstance660.fieldValue.append(fieldValue661)

Group531.children.append(ProtoInstance660)
ProtoInstance662 = x3d.ProtoInstance(DEF="b57")
ProtoInstance662.name = "line"
fieldValue663 = x3d.fieldValue()
fieldValue663.name = "bond_set"
fieldValue663.value = "9.2222 8.4507 0 8.1966 9.6324 0"

ProtoInstance662.fieldValue.append(fieldValue663)

Group531.children.append(ProtoInstance662)
ProtoInstance664 = x3d.ProtoInstance(DEF="b57_2")
ProtoInstance664.name = "line"
fieldValue665 = x3d.fieldValue()
fieldValue665.name = "bond_set"
fieldValue665.value = "9.2622 8.4507 0 8.2366 9.6324 0"

ProtoInstance664.fieldValue.append(fieldValue665)

Group531.children.append(ProtoInstance664)
ProtoInstance666 = x3d.ProtoInstance(DEF="b58")
ProtoInstance666.name = "line"
fieldValue667 = x3d.fieldValue()
fieldValue667.name = "bond_set"
fieldValue667.value = "10.4797 -3.3446 0 10.3237 -4.8943 0"

ProtoInstance666.fieldValue.append(fieldValue667)

Group531.children.append(ProtoInstance666)
ProtoInstance668 = x3d.ProtoInstance(DEF="b59")
ProtoInstance668.name = "line"
fieldValue669 = x3d.fieldValue()
fieldValue669.name = "bond_set"
fieldValue669.value = "9.9135 -1.0591 0 11.4074 -1.5274 0"

ProtoInstance668.fieldValue.append(fieldValue669)

Group531.children.append(ProtoInstance668)
ProtoInstance670 = x3d.ProtoInstance(DEF="b59_2")
ProtoInstance670.name = "line"
fieldValue671 = x3d.fieldValue()
fieldValue671.name = "bond_set"
fieldValue671.value = "9.9535 -1.0591 0 11.4474 -1.5274 0"

ProtoInstance670.fieldValue.append(fieldValue671)

Group531.children.append(ProtoInstance670)
ProtoInstance672 = x3d.ProtoInstance(DEF="b60")
ProtoInstance672.name = "line"
fieldValue673 = x3d.fieldValue()
fieldValue673.name = "bond_set"
fieldValue673.value = "11.4274 2.4862 0 12.5534 1.427 0"

ProtoInstance672.fieldValue.append(fieldValue673)

Group531.children.append(ProtoInstance672)
ProtoInstance674 = x3d.ProtoInstance(DEF="b61")
ProtoInstance674.name = "line"
fieldValue675 = x3d.fieldValue()
fieldValue675.name = "bond_set"
fieldValue675.value = "11.4274 2.4862 0 11.7507 4.0024 0"

ProtoInstance674.fieldValue.append(fieldValue675)

Group531.children.append(ProtoInstance674)
ProtoInstance676 = x3d.ProtoInstance(DEF="b62")
ProtoInstance676.name = "line"
fieldValue677 = x3d.fieldValue()
fieldValue677.name = "bond_set"
fieldValue677.value = "10.3237 -4.8943 0 8.8855 -5.5297 0"

ProtoInstance676.fieldValue.append(fieldValue677)

Group531.children.append(ProtoInstance676)
ProtoInstance678 = x3d.ProtoInstance(DEF="b63")
ProtoInstance678.name = "line"
fieldValue679 = x3d.fieldValue()
fieldValue679.name = "bond_set"
fieldValue679.value = "10.303700000000001 -4.8943 0 11.5412 -5.8085 0"

ProtoInstance678.fieldValue.append(fieldValue679)

Group531.children.append(ProtoInstance678)
ProtoInstance680 = x3d.ProtoInstance(DEF="b63_2")
ProtoInstance680.name = "line"
fieldValue681 = x3d.fieldValue()
fieldValue681.name = "bond_set"
fieldValue681.value = "10.3437 -4.8943 0 11.581199999999999 -5.8085 0"

ProtoInstance680.fieldValue.append(fieldValue681)

Group531.children.append(ProtoInstance680)
ProtoInstance682 = x3d.ProtoInstance(DEF="b64")
ProtoInstance682.name = "line"
fieldValue683 = x3d.fieldValue()
fieldValue683.name = "bond_set"
fieldValue683.value = "12.5534 1.427 0 14.0473 1.9064 0"

ProtoInstance682.fieldValue.append(fieldValue683)

Group531.children.append(ProtoInstance682)
ProtoInstance684 = x3d.ProtoInstance(DEF="b65")
ProtoInstance684.name = "line"
fieldValue685 = x3d.fieldValue()
fieldValue685.name = "bond_set"
fieldValue685.value = "8.8655 -5.5297 0 8.6983 -7.0794 0"

ProtoInstance684.fieldValue.append(fieldValue685)

Group531.children.append(ProtoInstance684)
ProtoInstance686 = x3d.ProtoInstance(DEF="b65_2")
ProtoInstance686.name = "line"
fieldValue687 = x3d.fieldValue()
fieldValue687.name = "bond_set"
fieldValue687.value = "8.9055 -5.5297 0 8.738299999999999 -7.0794 0"

ProtoInstance686.fieldValue.append(fieldValue687)

Group531.children.append(ProtoInstance686)
ProtoInstance688 = x3d.ProtoInstance(DEF="b66")
ProtoInstance688.name = "line"
fieldValue689 = x3d.fieldValue()
fieldValue689.name = "bond_set"
fieldValue689.value = "11.5612 -5.8085 0 11.3939 -7.347 0"

ProtoInstance688.fieldValue.append(fieldValue689)

Group531.children.append(ProtoInstance688)
ProtoInstance690 = x3d.ProtoInstance(DEF="b67")
ProtoInstance690.name = "line"
fieldValue691 = x3d.fieldValue()
fieldValue691.name = "bond_set"
fieldValue691.value = "8.7183 -7.0794 0 9.9892 -7.9824 0"

ProtoInstance690.fieldValue.append(fieldValue691)

Group531.children.append(ProtoInstance690)
ProtoInstance692 = x3d.ProtoInstance(DEF="b68")
ProtoInstance692.name = "line"
fieldValue693 = x3d.fieldValue()
fieldValue693.name = "bond_set"
fieldValue693.value = "9.9892 -7.9824 0 9.7885 -9.5321 0"

ProtoInstance692.fieldValue.append(fieldValue693)

Group531.children.append(ProtoInstance692)
ProtoInstance694 = x3d.ProtoInstance(DEF="b69")
ProtoInstance694.name = "line"
fieldValue695 = x3d.fieldValue()
fieldValue695.name = "bond_set"
fieldValue695.value = "-3.9355 3.5341 0 -2.5753 4.3034 0"

ProtoInstance694.fieldValue.append(fieldValue695)

Group531.children.append(ProtoInstance694)
ProtoInstance696 = x3d.ProtoInstance(DEF="b70")
ProtoInstance696.name = "line"
fieldValue697 = x3d.fieldValue()
fieldValue697.name = "bond_set"
fieldValue697.value = "9.9335 -1.0591 0 10.1787 0.4682 0"

ProtoInstance696.fieldValue.append(fieldValue697)

Group531.children.append(ProtoInstance696)
ProtoInstance698 = x3d.ProtoInstance(DEF="b71")
ProtoInstance698.name = "line"
fieldValue699 = x3d.fieldValue()
fieldValue699.name = "bond_set"
fieldValue699.value = "11.3739 -7.347 0 9.9692 -7.9824 0"

ProtoInstance698.fieldValue.append(fieldValue699)

Group531.children.append(ProtoInstance698)
ProtoInstance700 = x3d.ProtoInstance(DEF="b71_2")
ProtoInstance700.name = "line"
fieldValue701 = x3d.fieldValue()
fieldValue701.name = "bond_set"
fieldValue701.value = "11.4139 -7.347 0 10.0092 -7.9824 0"

ProtoInstance700.fieldValue.append(fieldValue701)

Group531.children.append(ProtoInstance700)

Scene19.children.append(Group531)

X3D0.Scene = Scene19
f = open("../data/Oxytocin.new.python.x3d", mode="w", encoding="utf-8")
f.write(X3D0.XML())
f.close()
f = open("../data/Oxytocin.new.python.x3dv", mode="w", encoding="utf-8")
f.write(X3D0.VRML())
f.close()
f = open("../data/Oxytocin.new.python.x3dj", mode="w", encoding="utf-8")
f.write(X3D0.JSON())
f.close()
