from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("pp3.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("translator").setContent("John Carlson")
head1.addMeta(meta4)
meta5 = metaObject().setName("created").setContent("5 May 2015")
head1.addMeta(meta5)
meta6 = metaObject().setName("modified").setContent("05 May 2017")
head1.addMeta(meta6)
meta7 = metaObject().setName("description").setContent("A process pipeline between three spheres (try typing on spheres and blue")
head1.addMeta(meta7)
meta8 = metaObject().setName("identifier").setContent("http://coderextreme.net/x3d/pp3.x3d")
head1.addMeta(meta8)
meta9 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta9)
X3D0.setHead(head1)
Scene10 = SceneObject()
ProtoDeclare11 = ProtoDeclareObject().setName("Process")
ProtoBody12 = ProtoBodyObject()
Group13 = GroupObject()

Group13.addComments(CommentsBlock("left"))
Transform14 = TransformObject().setScale([0.5,0.5,0.5])
Shape15 = ShapeObject()
Appearance16 = AppearanceObject()
Material17 = MaterialObject().setDiffuseColor([0.7,1,0]).setTransparency(0.5)
Appearance16.setMaterial(Material17)
Shape15.setAppearance(Appearance16)
Extrusion18 = ExtrusionObject().setCreaseAngle(0.785).setCrossSection([1,0,0.92,-0.38,0.71,-0.71,0.38,-0.92,0,-1,-0.38,-0.92,-0.71,-0.71,-0.92,-0.38,-1,0,-0.92,0.38,-0.71,0.71,-0.38,0.92,0,1,0.38,0.92,0.71,0.71,0.92,0.38,1,0]).setSpine([-2.5,0,0,-1.5,0,0])
Shape15.setGeometry(Extrusion18)
Transform14.addChild(Shape15)

Transform14.addComments(CommentsBlock("<Transform translation=\"-2.5 0 0\"> <Shape> <Text DEF=\"LeftString\" string='\"l\"'/> </Shape> </Transform> <StringSensor DEF=\"LeftSensor\" enabled=\"false\"/> <TouchSensor DEF=\"LeftTouch\" enabled=\"true\"/>"))
Group13.addChild(Transform14)

Group13.addComments(CommentsBlock("right"))
Transform19 = TransformObject().setScale([0.5,0.5,0.5])
Shape20 = ShapeObject()
Appearance21 = AppearanceObject()
Material22 = MaterialObject().setDiffuseColor([0,0.7,1]).setTransparency(0.5)
Appearance21.setMaterial(Material22)
Shape20.setAppearance(Appearance21)
Extrusion23 = ExtrusionObject().setCreaseAngle(0.785).setCrossSection([1,0,0.92,-0.38,0.71,-0.71,0.38,-0.92,0,-1,-0.38,-0.92,-0.71,-0.71,-0.92,-0.38,-1,0,-0.92,0.38,-0.71,0.71,-0.38,0.92,0,1,0.38,0.92,0.71,0.71,0.92,0.38,1,0]).setSpine([1.5,0,0,2.5,0,0])
Shape20.setGeometry(Extrusion23)
Transform19.addChild(Shape20)
Transform24 = TransformObject().setTranslation([2,0,0])
Shape25 = ShapeObject()
Appearance26 = AppearanceObject()
Material27 = MaterialObject().setDEF("MaterialLightBlue").setDiffuseColor([1,1,1])
Appearance26.setMaterial(Material27)
Shape25.setAppearance(Appearance26)
Text28 = TextObject().setDEF("RightString").setString(["r"])
Shape25.setGeometry(Text28)
Transform24.addChild(Shape25)
Transform19.addChild(Transform24)
StringSensor29 = StringSensorObject().setDEF("RightSensor").setEnabled(False)
Transform19.addChild(StringSensor29)
TouchSensor30 = TouchSensorObject().setDescription("touch to activate").setDEF("RightTouch")
Transform19.addChild(TouchSensor30)
Group13.addChild(Transform19)

Group13.addComments(CommentsBlock("up"))
Transform31 = TransformObject().setScale([0.5,0.5,0.5])
Shape32 = ShapeObject()
Appearance33 = AppearanceObject()
Material34 = MaterialObject().setDiffuseColor([0,0.7,1]).setTransparency(0.5)
Appearance33.setMaterial(Material34)
Shape32.setAppearance(Appearance33)
Extrusion35 = ExtrusionObject().setCreaseAngle(0.785).setCrossSection([1,0,0.92,-0.38,0.71,-0.71,0.38,-0.92,0,-1,-0.38,-0.92,-0.71,-0.71,-0.92,-0.38,-1,0,-0.92,0.38,-0.71,0.71,-0.38,0.92,0,1,0.38,0.92,0.71,0.71,0.92,0.38,1,0]).setSpine([0,1.5,0,0,2.5,0])
Shape32.setGeometry(Extrusion35)
Transform31.addChild(Shape32)
Transform36 = TransformObject().setTranslation([-0.5,2,0])
Shape37 = ShapeObject()
Appearance38 = AppearanceObject()
Material39 = MaterialObject().setUSE("MaterialLightBlue")
Appearance38.setMaterial(Material39)
Shape37.setAppearance(Appearance38)
Text40 = TextObject().setDEF("UpString").setString(["u"])
Shape37.setGeometry(Text40)
Transform36.addChild(Shape37)
Transform31.addChild(Transform36)
StringSensor41 = StringSensorObject().setDEF("UpSensor").setEnabled(False)
Transform31.addChild(StringSensor41)
TouchSensor42 = TouchSensorObject().setDescription("touch to activate").setDEF("UpTouch")
Transform31.addChild(TouchSensor42)
Group13.addChild(Transform31)

Group13.addComments(CommentsBlock("down"))
Transform43 = TransformObject().setScale([0.5,0.5,0.5])
Shape44 = ShapeObject()
Appearance45 = AppearanceObject()
Material46 = MaterialObject().setDiffuseColor([0.7,1,0]).setTransparency(0.5)
Appearance45.setMaterial(Material46)
Shape44.setAppearance(Appearance45)
Extrusion47 = ExtrusionObject().setCreaseAngle(0.785).setCrossSection([1,0,0.92,-0.38,0.71,-0.71,0.38,-0.92,0,-1,-0.38,-0.92,-0.71,-0.71,-0.92,-0.38,-1,0,-0.92,0.38,-0.71,0.71,-0.38,0.92,0,1,0.38,0.92,0.71,0.71,0.92,0.38,1,0]).setSpine([0,-2.5,0,0,-1.5,0])
Shape44.setGeometry(Extrusion47)
Transform43.addChild(Shape44)

Transform43.addComments(CommentsBlock("<Transform translation=\"-0.5 -2.5 0\"> <Shape> <Text DEF=\"DownString\" string='\"d\"'/> </Shape> </Transform> <StringSensor DEF=\"DownSensor\" enabled=\"false\"/> <TouchSensor description='touch to activate' DEF=\"DownTouch\" enabled=\"true\"/>"))
Group13.addChild(Transform43)

Group13.addComments(CommentsBlock("center"))
Transform48 = TransformObject()
Shape49 = ShapeObject()
Appearance50 = AppearanceObject()
Material51 = MaterialObject().setDiffuseColor([1,0,0.7])
Appearance50.setMaterial(Material51)
Shape49.setAppearance(Appearance50)
Sphere52 = SphereObject()
Shape49.setGeometry(Sphere52)
Transform48.addChild(Shape49)
Transform53 = TransformObject().setScale([0.5,0.5,0.5]).setTranslation([-0.5,0,1])
Shape54 = ShapeObject()
Appearance55 = AppearanceObject()
Material56 = MaterialObject().setUSE("MaterialLightBlue")
Appearance55.setMaterial(Material56)
Shape54.setAppearance(Appearance55)
Text57 = TextObject().setDEF("CenterString")
Shape54.setGeometry(Text57)
Transform53.addChild(Shape54)
Transform48.addChild(Transform53)
StringSensor58 = StringSensorObject().setDEF("CenterSensor").setEnabled(False)
Transform48.addChild(StringSensor58)
TouchSensor59 = TouchSensorObject().setDescription("touch to activate").setDEF("CenterTouch")
Transform48.addChild(TouchSensor59)
Group13.addChild(Transform48)
ProtoBody12.addChild(Group13)
Script60 = ScriptObject().setDEF("RightSingleToMultiString")
field61 = fieldObject().setType(fieldObject.TYPE_SFSTRING).setName("set_rightstring").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
Script60.addField(field61)
field62 = fieldObject().setType(fieldObject.TYPE_MFSTRING).setName("rightlines").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY)
Script60.addField(field62)

Script60.setSourceCode("ecmascript:\n"+
"\n"+
"function initialize() {\n"+
"	rightlines = new MFString(\"\");\n"+
"}\n"+
"\n"+
"function set_rightstring(rightstr) {\n"+
"	rightlines = new MFString(rightstr);\n"+
"}\n"+
"")
ProtoBody12.addChild(Script60)
Script63 = ScriptObject().setDEF("UpSingleToMultiString")
field64 = fieldObject().setType(fieldObject.TYPE_SFSTRING).setName("set_upstring").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
Script63.addField(field64)
field65 = fieldObject().setType(fieldObject.TYPE_MFSTRING).setName("uplines").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY)
Script63.addField(field65)

Script63.setSourceCode("ecmascript:\n"+
"\n"+
"function initialize() {\n"+
"	uplines = new MFString(\"\");\n"+
"}\n"+
"\n"+
"function set_upstring(upstr) {\n"+
"	uplines = new MFString(upstr);\n"+
"}\n"+
"")
ProtoBody12.addChild(Script63)
Script66 = ScriptObject().setDEF("CenterSingleToMultiString")
field67 = fieldObject().setType(fieldObject.TYPE_SFSTRING).setName("set_centerstring").setAccessType(fieldObject.ACCESSTYPE_INPUTONLY)
Script66.addField(field67)
field68 = fieldObject().setType(fieldObject.TYPE_MFSTRING).setName("centerlines").setAccessType(fieldObject.ACCESSTYPE_OUTPUTONLY)
Script66.addField(field68)

Script66.setSourceCode("ecmascript:\n"+
"\n"+
"function initialize() {\n"+
"	centerlines = new MFString(\"\");\n"+
"}\n"+
"\n"+
"function set_centerstring(centerstr) {\n"+
"	centerlines = new MFString(centerstr);\n"+
"}\n"+
"")
ProtoBody12.addChild(Script66)
ROUTE69 = ROUTEObject().setFromField("enteredText").setFromNode("CenterSensor").setToField("set_centerstring").setToNode("CenterSingleToMultiString")
ProtoBody12.addChild(ROUTE69)
ROUTE70 = ROUTEObject().setFromField("centerlines").setFromNode("CenterSingleToMultiString").setToField("set_string").setToNode("CenterString")
ProtoBody12.addChild(ROUTE70)
ROUTE71 = ROUTEObject().setFromField("isOver").setFromNode("CenterTouch").setToField("set_enabled").setToNode("CenterSensor")
ProtoBody12.addChild(ROUTE71)
ROUTE72 = ROUTEObject().setFromField("enteredText").setFromNode("RightSensor").setToField("set_rightstring").setToNode("RightSingleToMultiString")
ProtoBody12.addChild(ROUTE72)
ROUTE73 = ROUTEObject().setFromField("rightlines").setFromNode("RightSingleToMultiString").setToField("set_string").setToNode("RightString")
ProtoBody12.addChild(ROUTE73)
ROUTE74 = ROUTEObject().setFromField("isOver").setFromNode("RightTouch").setToField("set_enabled").setToNode("RightSensor")
ProtoBody12.addChild(ROUTE74)
ROUTE75 = ROUTEObject().setFromField("enteredText").setFromNode("UpSensor").setToField("set_upstring").setToNode("UpSingleToMultiString")
ProtoBody12.addChild(ROUTE75)
ROUTE76 = ROUTEObject().setFromField("uplines").setFromNode("UpSingleToMultiString").setToField("set_string").setToNode("UpString")
ProtoBody12.addChild(ROUTE76)
ROUTE77 = ROUTEObject().setFromField("isOver").setFromNode("UpTouch").setToField("set_enabled").setToNode("UpSensor")
ProtoBody12.addChild(ROUTE77)
ProtoDeclare11.setProtoBody(ProtoBody12)
Scene10.addChild(ProtoDeclare11)
NavigationInfo78 = NavigationInfoObject()
Scene10.addChild(NavigationInfo78)
Viewpoint79 = ViewpointObject().setDescription("Process pipes").setOrientation([1,0,0,-0.4]).setPosition([0,5,12])
Scene10.addChild(Viewpoint79)
Transform80 = TransformObject().setTranslation([0,-2.5,0])
ProtoInstance81 = ProtoInstanceObject().setName("Process")
Transform80.addChild(ProtoInstance81)
Scene10.addChild(Transform80)
Transform82 = TransformObject()
ProtoInstance83 = ProtoInstanceObject().setName("Process")
Transform82.addChild(ProtoInstance83)
Scene10.addChild(Transform82)
Transform84 = TransformObject().setTranslation([0,2.5,0])
ProtoInstance85 = ProtoInstanceObject().setName("Process")
Transform84.addChild(ProtoInstance85)
Scene10.addChild(Transform84)
X3D0.setScene(Scene10)

X3D0.toFileX3D("../new/orig/pp3.new.x3d")
