from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("title").setContent("rubikOnFire.x3d")
head1.addMeta(meta2)
meta3 = metaObject().setName("creator").setContent("John Carlson")
head1.addMeta(meta3)
meta4 = metaObject().setName("generator").setContent("manual")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/rubikOnFire.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("a white rubik cube")
head1.addMeta(meta6)
X3D0.setHead(head1)
Scene7 = SceneObject()
NavigationInfo8 = NavigationInfoObject().setType(["EXAMINE"])
Scene7.addChild(NavigationInfo8)
Viewpoint9 = ViewpointObject().setDescription("Rubiks Cube on Fire").setPosition([0,0,12])
Scene7.addChild(Viewpoint9)
ProtoDeclare10 = ProtoDeclareObject().setName("anyShape")
ProtoInterface11 = ProtoInterfaceObject()
field12 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("xtranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface11.addField(field12)
field13 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Sphere14 = SphereObject()
field13.addChild(Sphere14)
ProtoInterface11.addField(field13)
ProtoDeclare10.setProtoInterface(ProtoInterface11)
ProtoBody15 = ProtoBodyObject()
Transform16 = TransformObject()
IS17 = ISObject()
connect18 = connectObject().setNodeField("translation").setProtoField("xtranslation")
IS17.addConnect(connect18)
Transform16.setIS(IS17)
Shape19 = ShapeObject()
IS20 = ISObject()
connect21 = connectObject().setNodeField("geometry").setProtoField("myShape")
IS20.addConnect(connect21)
Shape19.setIS(IS20)
Appearance22 = AppearanceObject()
Material23 = MaterialObject().setDiffuseColor([1,1,1])
Appearance22.setMaterial(Material23)
Shape19.setAppearance(Appearance22)
Transform16.addChild(Shape19)
ProtoBody15.addChild(Transform16)
ProtoDeclare10.setProtoBody(ProtoBody15)
Scene7.addChild(ProtoDeclare10)
ProtoDeclare24 = ProtoDeclareObject().setName("three")
ProtoInterface25 = ProtoInterfaceObject()
field26 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ytranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface25.addField(field26)
field27 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Sphere28 = SphereObject()
field27.addChild(Sphere28)
ProtoInterface25.addField(field27)
ProtoDeclare24.setProtoInterface(ProtoInterface25)
ProtoBody29 = ProtoBodyObject()
Transform30 = TransformObject()
IS31 = ISObject()
connect32 = connectObject().setNodeField("translation").setProtoField("ytranslation")
IS31.addConnect(connect32)
Transform30.setIS(IS31)
ProtoInstance33 = ProtoInstanceObject().setName("anyShape")
fieldValue34 = fieldValueObject().setName("xtranslation").setValue("0 0 0")
ProtoInstance33.addFieldValue(fieldValue34)
IS35 = ISObject()
connect36 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS35.addConnect(connect36)
ProtoInstance33.setIS(IS35)
Transform30.addChild(ProtoInstance33)
ProtoInstance37 = ProtoInstanceObject().setName("anyShape")
fieldValue38 = fieldValueObject().setName("xtranslation").setValue("2 0 0")
ProtoInstance37.addFieldValue(fieldValue38)
IS39 = ISObject()
connect40 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS39.addConnect(connect40)
ProtoInstance37.setIS(IS39)
Transform30.addChild(ProtoInstance37)
ProtoInstance41 = ProtoInstanceObject().setName("anyShape")
fieldValue42 = fieldValueObject().setName("xtranslation").setValue("-2 0 0")
ProtoInstance41.addFieldValue(fieldValue42)
IS43 = ISObject()
connect44 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS43.addConnect(connect44)
ProtoInstance41.setIS(IS43)
Transform30.addChild(ProtoInstance41)
ProtoBody29.addChild(Transform30)
ProtoDeclare24.setProtoBody(ProtoBody29)
Scene7.addChild(ProtoDeclare24)
ProtoDeclare45 = ProtoDeclareObject().setName("nine")
ProtoInterface46 = ProtoInterfaceObject()
field47 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ztranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface46.addField(field47)
field48 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Sphere49 = SphereObject()
field48.addChild(Sphere49)
ProtoInterface46.addField(field48)
ProtoDeclare45.setProtoInterface(ProtoInterface46)
ProtoBody50 = ProtoBodyObject()
Transform51 = TransformObject()
IS52 = ISObject()
connect53 = connectObject().setNodeField("translation").setProtoField("ztranslation")
IS52.addConnect(connect53)
Transform51.setIS(IS52)
ProtoInstance54 = ProtoInstanceObject().setName("three")
fieldValue55 = fieldValueObject().setName("ytranslation").setValue("0 0 0")
ProtoInstance54.addFieldValue(fieldValue55)
IS56 = ISObject()
connect57 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS56.addConnect(connect57)
ProtoInstance54.setIS(IS56)
Transform51.addChild(ProtoInstance54)
ProtoInstance58 = ProtoInstanceObject().setName("three")
fieldValue59 = fieldValueObject().setName("ytranslation").setValue("0 2 0")
ProtoInstance58.addFieldValue(fieldValue59)
IS60 = ISObject()
connect61 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS60.addConnect(connect61)
ProtoInstance58.setIS(IS60)
Transform51.addChild(ProtoInstance58)
ProtoInstance62 = ProtoInstanceObject().setName("three")
fieldValue63 = fieldValueObject().setName("ytranslation").setValue("0 -2 0")
ProtoInstance62.addFieldValue(fieldValue63)
IS64 = ISObject()
connect65 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS64.addConnect(connect65)
ProtoInstance62.setIS(IS64)
Transform51.addChild(ProtoInstance62)
ProtoBody50.addChild(Transform51)
ProtoDeclare45.setProtoBody(ProtoBody50)
Scene7.addChild(ProtoDeclare45)
ProtoDeclare66 = ProtoDeclareObject().setName("twentyseven")
ProtoInterface67 = ProtoInterfaceObject()
field68 = fieldObject().setType(fieldObject.TYPE_SFVEC3F).setName("ttranslation").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT).setValue("0 0 0")
ProtoInterface67.addField(field68)
field69 = fieldObject().setType(fieldObject.TYPE_SFNODE).setName("myShape").setAccessType(fieldObject.ACCESSTYPE_INPUTOUTPUT)
Sphere70 = SphereObject()
field69.addChild(Sphere70)
ProtoInterface67.addField(field69)
ProtoDeclare66.setProtoInterface(ProtoInterface67)
ProtoBody71 = ProtoBodyObject()
Transform72 = TransformObject()
IS73 = ISObject()
connect74 = connectObject().setNodeField("translation").setProtoField("ttranslation")
IS73.addConnect(connect74)
Transform72.setIS(IS73)
ProtoInstance75 = ProtoInstanceObject().setName("nine")
fieldValue76 = fieldValueObject().setName("ztranslation").setValue("0 0 0")
ProtoInstance75.addFieldValue(fieldValue76)
IS77 = ISObject()
connect78 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS77.addConnect(connect78)
ProtoInstance75.setIS(IS77)
Transform72.addChild(ProtoInstance75)
ProtoInstance79 = ProtoInstanceObject().setName("nine")
fieldValue80 = fieldValueObject().setName("ztranslation").setValue("0 0 2")
ProtoInstance79.addFieldValue(fieldValue80)
IS81 = ISObject()
connect82 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS81.addConnect(connect82)
ProtoInstance79.setIS(IS81)
Transform72.addChild(ProtoInstance79)
ProtoInstance83 = ProtoInstanceObject().setName("nine")
fieldValue84 = fieldValueObject().setName("ztranslation").setValue("0 0 -2")
ProtoInstance83.addFieldValue(fieldValue84)
IS85 = ISObject()
connect86 = connectObject().setNodeField("myShape").setProtoField("myShape")
IS85.addConnect(connect86)
ProtoInstance83.setIS(IS85)
Transform72.addChild(ProtoInstance83)
ProtoBody71.addChild(Transform72)
ProtoDeclare66.setProtoBody(ProtoBody71)
Scene7.addChild(ProtoDeclare66)
ProtoInstance87 = ProtoInstanceObject().setName("twentyseven")
fieldValue88 = fieldValueObject().setName("ttranslation").setValue("0 0 0")
ProtoInstance87.addFieldValue(fieldValue88)
fieldValue89 = fieldValueObject().setName("myShape")
Box90 = BoxObject().setSize([1,1,1])
fieldValue89.addChild(Box90)
ProtoInstance87.addFieldValue(fieldValue89)
Scene7.addChild(ProtoInstance87)
X3D0.setScene(Scene7)

X3D0.toFileX3D("../new/orig/rubikOnFire.new.x3d")
