from jnius import autoclass
from X3Dautoclass import *
X3D0 =  X3DObject().setProfile("Immersive").setVersion("3.3")
head1 = headObject()
meta2 = metaObject().setName("creator").setContent("John W Carlson")
head1.addMeta(meta2)
meta3 = metaObject().setName("created").setContent("December 13 2015")
head1.addMeta(meta3)
meta4 = metaObject().setName("title").setContent("text.x3d")
head1.addMeta(meta4)
meta5 = metaObject().setName("identifier").setContent("http://coderextreme.net/X3DJSONLD/text.x3d")
head1.addMeta(meta5)
meta6 = metaObject().setName("description").setContent("test text")
head1.addMeta(meta6)
meta7 = metaObject().setName("generator").setContent("Vim, X3D-Edit, https://savage.nps.edu/X3D-Edit")
head1.addMeta(meta7)
X3D0.setHead(head1)
Scene8 = SceneObject()
Transform9 = TransformObject()
Shape10 = ShapeObject()
Text11 = TextObject().setString(["Node\"\"\""])
FontStyle12 = FontStyleObject().setJustify(["MIDDLE","MIDDLE"]).setSize(5)
Text11.setFontStyle(FontStyle12)
Shape10.setGeometry(Text11)
Appearance13 = AppearanceObject()
Material14 = MaterialObject().setDiffuseColor([0,0,1])
Appearance13.setMaterial(Material14)
Shape10.setAppearance(Appearance13)
Transform9.addChild(Shape10)
Scene8.addChild(Transform9)
X3D0.setScene(Scene8)

X3D0.toFileX3D("../new/orig/text.new.x3d")
